RPCS3/rpcs3

- README.md
We've not been using Azure for a while, and the Cirrus CI badge is reflecting the whole CI status, not FreeBSD specifically, so we also rename it
> readme: Remove Azure, rename Cirrus CI badges

- rpcs3/Emu/RSX/rsx_methods.cpp
Match the previous behavior before we started wrapping enums.
Fixes https://github.com/RPCS3/rpcs3/issues/13308
Fixes https://github.com/RPCS3/rpcs3/issues/13244
> rsx: Relax face culling config checks

- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
cellOskDialog does increase y to the top of the screen.
Our overlays increase it to the bottom.
I forgot to fix the offset addition 🤦
> overlays/osk: fix y offset direction

- rpcs3/Emu/System.cpp
If the user made a mistake and removed a custom Virtual File System directory or moved it, RPCS3 shouldn't create the old path by force and use it. Instead encourage him to fix it himself, it also avoids his confusion as to why games won't appear on the new path.
> System.cpp: Do not create VFS directories outside of RPCS3 dir

- rpcs3/Input/sdl_pad_handler.cpp
SDL currently always returns 1 if a button is pressed
fixes #13337
> SDL: Fix button presses

- rpcs3/rpcs3qt/game_list_frame.cpp
Applies to disc games.
Before (using 1.00 icon from /dev_bdvd):
After (using 1.11 icon from /dev_hdd0):
> Game list: Use the latest game icon instead of 1.00's

- rpcs3/Emu/RSX/GL/GLOverlays.cpp
- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
- rpcs3/Emu/RSX/Overlays/overlay_controls.h
- rpcs3/Emu/RSX/Program/GLSLSnippets/OverlayRenderFS.glsl
- rpcs3/Emu/RSX/Program/GLSLSnippets/OverlayRenderVS.glsl
- rpcs3/Emu/RSX/Program/RSXOverlay.h
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/Emu/RSX/VK/VKOverlays.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- Unify overlay rendering shaders to reduce the headache of maintaining 2 separate paths
- Add support for disabling vertex snap on the overlays. This fixes rendering the round parts of rounded rectangles.
- Fix grid snap code which was broken for years due to a misplaced bracket 🙈 
- Force disable the rounded rectangles feature on mac OS which doesn't support triangle fans. A workaround will be provided at a later time.
> rsx/overlays: Misc Improvements

- rpcs3/Emu/RSX/Program/GLSLSnippets/OverlayRenderFS.glsl
I'm sure this is utterly wrong, but it fixes the OpenGl overlay colors:
fixes #13365
> Fix OpenGl overlay colors

- rpcs3/Input/pad_thread.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- Adds convenient "--fullscreen" option to allow to boot games in fullscreen in "--no-gui" mode
- Adds convenient "--pad-profile=<profile>" option to override the pad profile in "--no-gui" mode
fixes #13276
fixes #10332
> CLI: Add fullscreen and pad profile options

- rpcs3/rpcs3qt/rsx_debugger.cpp
- Use buffer cache instead of allocating a raw buffer
- This also happens to fix a memory leak in the stencil buffer widget
> rsx_debugger: replace malloc with buffer cache

- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- Fixes mounting of game path and path in games.yml if m_sfo_dir ends with C00
- Fixes argv[0] if m_sfo_dir ends with C00 (USRDIR was cropped to DIR)
- Removes /USRDIR/../ from C00 sfo paths
fixes #13383
> Fix C00 boot from external HG games

- rpcs3/main.cpp
- rpcs3/rpcs3qt/gl_gs_frame.cpp
- rpcs3/rpcs3qt/gl_gs_frame.h
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
- rpcs3/rpcs3qt/gui_settings.h
- Adds the CLI argument "game-screen" which can be used to set a preferred screen for the game window. Use it for example like: `rpcs3.exe --no-gui --game-screen=1`
- Saves the last game window screen and re-uses it in the no-gui mode if no game-screen is set
- Moves the global parameter for the fullscreen mode to member variables of gui_application and gs_frame
fixes #12828
> CLI: add game-screen parameter, save last game window screen in no-gui mode

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUModule.h
Without this fix rpcs3 sometimes crashes on start. I guess it happens because the order of static initialization is undefined.
> fix order of static initialization

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
A comment in a forum mentioned a fatal error in Lair that is fixed by LLE libVdec.
Turns out we were decreasing the au_count to 0 when the start_sequence command was executed.
This meant that it could not be decreased to 0 when the already enqueued follow-up decode command was executed.
We should not set it to 0 at all and let the queue work it off instead.
> cellVdec: fix au_count race condition

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
Aligns cellVdecGetPicture outBuffer pitch to 128.
The buffer itself is aligned to 128, so this seems like the correct alignment.
I tried with other alignments, but in all other cases the image looked crooked.
~~Additionally, I re-use existing alpha caches if possible.~~
Before:
After:
fixes #11751
> cellVdec: fix pitch of RGBA/ARGB images

- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/main.cpp
There was a missing ":" in some places, which was very confusing
> Fix boot by RPCS3_GAMEID constants

- Utilities/lockless.h
- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
- rpcs3/Emu/Cell/Modules/cellUserInfo.cpp
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu.cpp
- rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp
- rpcs3/Emu/RSX/Overlays/overlay_cursor.cpp
- rpcs3/Emu/RSX/Overlays/overlay_manager.cpp
- rpcs3/Emu/RSX/Overlays/overlay_manager.h
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message.h
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3qt/save_data_dialog.cpp
- rpcs3/rpcs3qt/trophy_notification_helper.cpp
Instead of having each async dialog spawning its own thread, let's just have the manager handle this. Interfaces are pushed onto a LIFO stack which also inserts some Z-ordering. Multiple open dialogs do not fight for input, the last active dialog retains the input target until it releases it.
The current implementation here is far from complete. As there is no input pre-emption, the currently opened dialog must finish inputs before handing over to the next one. This actually works out ok for what we need, but can be improved upon.
TODOs:
> rsx/overlays: Unified overlay input

- rpcs3/util/atomic.hpp
- rpcs3/util/media_utils.cpp
- rpcs3/util/media_utils.h
For some reason there's an internal compiler error related to atomic wait.
I could work around this issue when I commented `mask = default_mask<X>;`.
So after playing around a bit I had the suspicion that the VS parser can't handle some of the templatization.
Giving the decltype its own alias seems to fix this issue (and makes the code a bit more readable anyway in my opinion).
> Fix Visual Studio 17.5.0 compilation

- rpcs3/Emu/RSX/Overlays/overlay_manager.cpp
Input thread gets stuck in the lf_queue.wait() routine and never wakes up to exit. Just insert a dummy node to wake it on exit.
Fixes https://github.com/RPCS3/rpcs3/issues/13447
> rsx/overlays: Fix emu close

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.h
Fixes Windows returns ENOTCONN when using recvfrom/sendto on connecting socket instead of the expected EAGAIN.
> Fix for Windows ENOTCONN on connecting socket

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
Found these bugs using AddressSanitizer.
> Misc. asan fixes

- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
A race condition could have led the local copy of notify be accessed after destruction.
> cellMsgDialog: fix use-after-free

- rpcs3/Emu/RSX/Common/simple_array.hpp
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.h
Avoid unnecessary copies on the hot path. Profiling identified millions of memory copies every frame in msvc-compiled builds that actually add up enough to hurt performance with draw-call-heavy titles. A modest 3-10% uplift is observed in "infamous" which regularly issues 10-20k draw calls per frame.
> rsx: Minor memory optimizations

- rpcs3/Emu/Cell/Modules/cellRtc.cpp
Turns out you should listen to warnings once in a while...
sprintf actually wrote more than 3 characters into the microDigits buffer !!!
```cpp
CellRtcDateTime date_time{};
date_time.microsecond = 123456;
std::array<char, 3> microDigits{};
snprintf(microDigits.data(), microDigits.size(), "%02u", u32{date_time.microsecond});
char microDigits2[3];
sprintf(microDigits2, "%02u", u32{date_time.microsecond});
sys_log.error("sprintf='%s'", microDigits2);
sys_log.error("snprintf='%s'", microDigits.data());
```
```
E SYS: sprintf='123456'
E SYS: snprintf='12'
```
> cellRtc: fix out of bounds write

- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Common/TextureUtils.h
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/io_buffer.h
Drastically reduces memory pressure and improves frametime smoothness in some titles when using vulkan. With modern GPUs, we don't actually use the upload heap much since there is a 1:1 DMA layer between emulated CELL and RSX. However, we were still spamming memory allocations and not using them which could lead to long GPU stalls if many textures are uploaded in a frame.
Partially addresses https://github.com/RPCS3/rpcs3/issues/13465
> rsx: Implement deferred buffer allocations for GPU write

- rpcs3/Crypto/unpkg.cpp
- rpcs3/Crypto/unpkg.h
- rpcs3/rpcs3qt/main_window.cpp
- Do not use a generic error if the error is already set.
- Abort installation immediately without processing the other packages if an error occured in order to properly determine the failed package.
- Skip workers on error. No real code change here as it was already done internally. But it was confusing to read without the extra check in the loop.
maybe fixes #13472
> pkg install: return correct error if possible

- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/tooltips.h
- The psn connection is only needed for some games, so let's hide it in the global config dialog.
- Also move some common code to helper functions
> Qt: disable psn setting in global settings

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
Two new patch types, "move_file" and "hide_file":
**"hide_file":**
Specify the PS3 path of the file to mark as non-existant in offset field, the value field is unused. This can be used to "remove" cutscenes for example without needing to make any modification to game files. When specifying an already non-existant file this will prevent its creation further on. (ENOENT error code)
**"move_file":**
Specify the PS3 path of the file to "move" in offset field, and the destination path in value field. The original PS3 path does not have to exist for this operation to work. This can be used to install configurable mods and texture packs without modifying the original game files. 
Do note that this can also be used on directories and PS3 partitions.
You do not have to specify "/dev_" at the start …
> Patches: Virtual move/remove/create game files patches

- rpcs3/Emu/VFS.cpp
- rpcs3/main_application.cpp
resolve_path is just a simplification of path compariosns I added in the past for savestates. It is not  
required to succeed, nor should VFS care whether the file path exists or not.
> VFS: Fix mounting non-existant paths

- Utilities/File.cpp
- Utilities/StrFmt.cpp
- Utilities/StrFmt.h
- Utilities/Thread.cpp
- rpcs3/Emu/RSX/VK/VKDMA.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/tooltips.h
- rpcs3/util/cpu_stats.cpp
- rpcs3/util/vm_native.cpp
- Re-enable RPCN as global config
- Hide Fake PSN in global config instead
- Hide "IP/Host Switches" and "Bind Address" in global config
- Properly log some win errors
> Qt: Disable some network settings in global config. Re-enable RPCN in global config.

- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
Affected linux build as the icon wasn't copied to config dir.
> Add missing spinning icon from resources

- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.h
The wstring_view outlasted the actual value coming from enumeration.
> Fix hid_pad_handler

- Utilities/JIT.cpp
- rpcs3/Emu/CPU/CPUTranslator.cpp
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
I updated the coded to use the new LLVM API, which uses [opaque pointers](https://llvm.org/docs/OpaquePointers.html). I tested it with the bundles LLVM 13 and with newer LLVM versions, with one game.
If you define `OLDLLVM` then it will use the old deprecated API.
> llvm: update code to new API

- rpcs3/Emu/Cell/SPURecompiler.cpp
My PR #13500 had a bug. Sorry, I didn't notice because I didn't test with "SPU Block Size" Mega. The fix in #13533 uses the deprecated LLVM API. I fixed it to use the new LLVM API.
> use new LLVM API in SPURecompiler

- rpcs3/Emu/NP/rpcn_client.cpp
Also improved the logic to ensure the beginning of a packet received near timeout realization would not result in a timeout.
Fixes #13539
> Fix recvn high cpu usage

- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/System.cpp
* Turns out cellFsReaddir is always writing data even when it goes out of entries: on HDD1: it copies bytes of the last entry, on HDD0: it copies bytes of the last entry, but also sets the first 3 bytes to 0. Th game was expecting this and looped until it got a zero, but the zero never came.
Game code:
Testcase: https://github.com/elad335/myps3tests/commit/8f311ccdecc3186a8cc5b82335baa1fb13e29262
* Fix deadlock when loading savestate when there is a PPU executing deallocation syscall under IDM mutex such as sys_vm_unmap before GUI thread had completed FinalizeRunRequest(), which caused the PPU to wait for RSX, RSX to wait for GUI thread (to update emulation state), GUI thread for PPU to release IDM lock. Fixes savestating after reaching new gameplay with Far Cry Classic. This happened …
> cellFsReaddir: Fix termination sequence / Fix savestate crash on load

- rpcs3/Emu/NP/signaling_handler.cpp
Re-queueing disconnection packets from an already dead signaling connection resulted in a logic error where the packets were not cleared from the packet queues and resulted in spam.
> Fix timeout spam from signaling

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Input/evdev_joystick_handler.h
Fix inaccuracies pointed out in https://pvs-studio.com/en/blog/posts/cpp/1014/.
I didn't touch the m_finfo one as actually https://github.com/RPCS3/rpcs3/blob/cf5346c263111760752cabb94767c07c501207c4/rpcs3/Emu/Cell/SPURecompiler.cpp#L5299 so it can't be null.
So either the m_info nullptr checks after are redundant or implicit insertion into m_functions with [] is an error, I'm unsure.
> Fix inaccuracies pointed out by PVS-Studio

- 3rdparty/MoltenVK/CMakeLists.txt
Update MoltenVK to [version 1.2.3](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.3)
Changelog: 
- Add support for extensions:
- `VK_EXT_external_memory_host`
- `VK_EXT_pipeline_creation_cache_control`
- `VK_EXT_shader_atomic_float`
- `VK_EXT_surface_maintenance1`
- `VK_EXT_swapchain_maintenance1`
- Fix crash when `VkCommandBufferInheritanceInfo::renderPass` is `VK_NULL_HANDLE` during dynamic rendering.
- Do not clear attachments when dynamic rendering is resumed.
- Allow ending dynamic rendering to trigger next multiview pass if needed.
- Fix premature caching of occlusion query results during tessellation rendering.
- `vkCmdCopyQueryPoolResults()`: Fix loss of queries when query count is not a multiple of GPU threadgroup execution width.
- Disable occlusion recording while …
> 3rd Party: Update MoltenVK to 1.2.3 (Vulkan SDK 1.3.243)

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/Modules/cellAudio.h
- rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
- rpcs3/Emu/Cell/Modules/cellMic.cpp
- rpcs3/Emu/Cell/Modules/cellMic.h
Apparently games have to register the second and subsequent microphones before they can use them.
> [TESTERS NEEDED] cellMic: wait for registration before using secondary microphones

- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.cpp
1. Fix detection of apple GPUs. I'm only using the vendor ID here for detection as we assume all apple-made GPUs to behave the same way at this time.
2. Don't unconditionally assume free DEPTH<->COLOR conversions for D16F emulation.
Fixes https://github.com/RPCS3/rpcs3/issues/13590
> vk: Improve hardware detection for M1

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/System.cpp
1. Do not mount dev_usbXXX if its path is not properly specified since this can cause confusion to some games that detect and determine which USB flash drive to use.
2. Allow dev_usbXXX to be mounted, unmounted, and formatted(newfs) by the corresponding sys_fs syscalls as some games do format the attached USB flash drives in some cases.
3. Improve the permission check for the three syscalls mentioned above: PS3 root permission is required in order to perform actions on devices other than dev_usbXXX.
4. Add read-only flag check to sys_fs_newfs() to prevent devices with this flag from being formatted.
5. Implement CELL_FS_PATH path-as-device support.
> sys_fs & VFS: Misc bug fixes

- rpcs3/Emu/System.cpp
BlockingCallFromMainThread has been called on std::thread inside Resume() resultiing in a verification failure.
> Fix emulator crash when stopping emulation after being paused

- 3rdparty/llvm.cmake
-LLVM_TARGETS_TO_BUILD now needs to be set as CACHE
-Directories were a bit weird so changed them to be absolute
-LLVM lib is only for dynamically linked LLVM, used llvm_map_components_to_libnames(as recommended by LLVM documentation) to set the minimal set of libraries
> Fix BUILD_LLVM option

- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/PPUTranslator.h
- rpcs3/Emu/Cell/SPURecompiler.cpp
Now that rpcs3 uses opaque pointers we can remove the superfluous pointer bitcasts.
> remove unnecessary pointer bitcasts

- .ci/build-freebsd.sh
- .ci/get_keys-windows.sh
- .ci/setup-windows.sh
- BUILDING.md
- Utilities/JIT.cpp
- Utilities/JIT.h
- rpcs3/Emu/CPU/CPUTranslator.cpp
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
Also fix AVX-512 detection bug for Zen4+.
> Update to LLVM 16.0.1

- rpcs3/Emu/Io/Skylander.cpp
Should fix https://github.com/RPCS3/rpcs3/issues/12887
Audio transfers are 64 bytes long (32 x 16 bit audio samples, 8khz mono), but the current code ensures the buf size is 32 only for interrupt transfers. This fix should let users play through Trap Team with the Emulated Portal, by allowing 64 byte transfers and not returning the status of the portal if it is an audio transfer.
Note that this is untested, it is simply based on the work I did within Dolphin to implement the same.
> Skylander Portal: Trap Team Audio Transfers

- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/cache_utils.cpp
- rpcs3/Emu/system_progress.hpp
- rpcs3/rpcs3qt/cheat_manager.cpp
Previously, when launching a game there used to be a pause of anywhere between half a second to a few seconds in which the emulator appeared frozen and you couldn't interact with any button on UI.
This is because the hefty step of PPU executable function code mining took place entirely on the UI thread.
Moved to be executed by PPU main thread instead. This also allows to terminate the emulation in this step and making the game window open sooner with an "Analyzing PPU Executable..." message.
> Loader: Make executable analyzation not halt UI when launching games

- rpcs3/rpcs3qt/debugger_frame.cpp
Fix stepping over branches which do not have the link flag. This is of course based on the wrong assumption that all linked branches must return but oh well.
> Debugger: Fix step over

- rpcs3/Emu/Cell/Modules/cellMic.cpp
- Fallback to 4,2,1 channels by default if requested channels are not supported
- Fallback to 48000, 32000, 24000, 16000, 12000, 8000 samplingrate if not supported
- Change channel count of cellMicOpen to 1 (I hope I saw that correctly)
- Add some error checks to cellMicReset
- Ensure that singstar devices have 1, respective 2 channels
- Change device type back to USB
Should fix the 0 channel error seen in the comment #11266
> cellMic: fallback to lower channel count and sampling rate if requested is not supported

- Utilities/JIT.cpp
- Emit pcmpeqd instead of the incorrect pcmpeqw
Fixes https://github.com/RPCS3/rpcs3/issues/13157
> jit: Fix vec_cmp_eq<u32>

- rpcs3/Emu/Io/PadHandler.cpp
For the default squircle value of 8000, I observed the following behavior:
`ConvertToSquirclePoint(128,128) --> (128,128)`. This makes sense to me.
`ConvertToSquirclePoint(127,127) --> (126,126)`. Huh.
If you don't cast the coordinate values to integer, you get the following:
`ConvertToSquirclePoint(128,128) --> (128.0625, 128.0625)`
`ConvertToSquirclePoint(127,127) --> (126.9375, 126.9375)`
To me, it makes sense to round the coordinate values to the nearest whole number instead of just casting them to integers. This way, joysticks centered at (127,127) remain centered at (127,127) instead of getting recentered to (126,126).
Implementing this allows me to implement #13636 without having to workaround joysticks being centered at (126,126).
> Round squircled axis values to the nearest whole number

- rpcs3/Emu/Io/Turntable.cpp
Back when I submitted turntable emulation in #9965, I set the crossfader bind such that Crossfade Left was Y Up and Crossfade Right was Y Down, intending to imitate the binds of an Xbox 360 turntable.
Turns out I messed up. On Xbox 360 turntables, Crossfade Left is Y Down, Crossfade Right is Y Up.
This PR flips the crossfader bind to match the real turntable's inputs.
This will flip the crossfader for all emulated turntable users until they rebind, but I'm familiar with the DJ Hero community and I think it's worth a one-time change for accuracy.
Also fix turntable/left stick input overflow while I'm here.
> Invert the DJ Hero Turntable crossfader axis bind.

- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/settings.cpp
- rpcs3/rpcs3qt/settings.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- rpcs3/rpcs3qt/update_manager.cpp
- rpcs3/rpcs3qt/update_manager.h
- Adds a "don't show again" checkbox to the restart hint at the end of a RPCS3 update
> Qt: add checkbox to restart dialog

- rpcs3/rpcs3qt/game_list_frame.cpp
- add option to reset time played to game list context menu
fixes #13615
> Qt: add option to reset time played

- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/GL/GLTexture.h
- rpcs3/Emu/RSX/GL/glutils/fbo.cpp
- rpcs3/Emu/RSX/GL/glutils/fbo.h
Make the whole thing a standalone command wrapper to avoid unnecessary state meddling. Previously any changes made before the actual clear step were overwritten by other intermediary steps. In the dragon's dogma case, a memory barrier forced attachment merging which destroyed the state before the glClear was issued.
Fixes https://github.com/RPCS3/rpcs3/issues/13693
> gl: Refactor attachment clear logic

- rpcs3/Emu/Cell/SPURecompiler.cpp
Not sure if it has any positive effect, but need to try.
> SPU LLVM: improve DSE

- buildfiles/msvc/rpcs3_debug.props
When compiling in Debug in Visual Studio, there is an error of not finding an LLVM library, correcting this path, everything works normally
> Path to LLVM library fixed in Debug

- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
Avoid using expensive IO when there is no need to. (flushing to disk)
Avoid other IO when simply loading the game library.
This also improves booting disc games.
May or may not speed up loading the emulator with NAS or HDD drives.
> Reduce IO With Game Library Loading

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/games_config.cpp
- rpcs3/Emu/games_config.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3qt/game_list_frame.cpp
- Only load games.yml once during lifetime of rpcs3.
- Only save games.yml once after adding games
This means that if you had 200 games in your /games folder, you will now have at least 200 reads less during startup than before.
The reduction in write during startup won't be as amazing, since we only saved the games.yml when an entry was added (at least with the commit prior to this one).
> Emu: Cache games.yml and only save when necessary

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/game_compatibility.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/game_list_grid.cpp
- rpcs3/rpcs3qt/game_list_grid_delegate.cpp
- rpcs3/rpcs3qt/movie_item.cpp
- rpcs3/rpcs3qt/movie_item.h
- rpcs3/rpcs3qt/table_item_delegate.cpp
- rpcs3/rpcs3qt/table_item_delegate.h
- Use const Node to fetch games.yml entries to prevent creation of new entries
- Decrease time spent in lock during list refresh
- Move path checks to async section of refresh.
We now only accumulate paths in the main thread and then do all the file interactions in the async thread pool.
This should increase responsiveness.
- Use lazy icon loading for list layout (only visible items)
- Use lazy dir size calculation for list layout (only visible items)
> Qt: Optimize hard list refresh

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/game_list.cpp
- rpcs3/rpcs3qt/game_list.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/main_window.cpp
* Focus to game searchbar on load.
* Make return key press focus to game list's first entry if game searchbar is focused.
* Ignore trademarks, hyphen, colons and duplicated spaces when searching games. (fallback when otherwise no search results have not been yielded):
This means you can now search easily for game titles such as **"Spider-Man: Web of Shadows"** or **"Killzone®3 Demo"**.
* Make Ctrl+F focus to game search bar.
This pull request makes it easily doable to launch any game even from large game lists without lifting the hands from keyboard within no time!
> User Interface: Game searching improvements

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/game_list_delegate.cpp
- rpcs3/rpcs3qt/game_list_delegate.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/table_item_delegate.cpp
- rpcs3/rpcs3qt/table_item_delegate.h
> Qt: fix table item delegate usage

- rpcs3/rpcs3qt/game_list_delegate.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_grid_delegate.cpp
- rpcs3/rpcs3qt/movie_item.cpp
- rpcs3/rpcs3qt/movie_item.h
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/save_manager_dialog.h
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.h
- Multithreaded savedata dialog directory parsing
- Lazy load savedata dialog icons (only loaded once visible)
- Fixes item indices in the lazy loading of the trophy dialog
- Fixes some QVector<int> metatype warnings that may pop up in QDebug
All in all, this should decrease the loading time for the savedata dialog.
> Qt: lazy load save data icons

- rpcs3/Emu/System.cpp
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/flow_layout.cpp
- rpcs3/rpcs3qt/flow_layout.h
- rpcs3/rpcs3qt/flow_widget.cpp
- rpcs3/rpcs3qt/flow_widget.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/screenshot_manager_dialog.cpp
- rpcs3/rpcs3qt/screenshot_manager_dialog.h
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- Show the main window earlier
- Move the experimental build warning to the gui_application, which is created earlier anyway.
- Move a bunch of directory parsing to a separate thread
- Show a progress dialog if gamelist parsing takes more than 200ms.
Earlier would be annoying on fast drives.
Later would be dangerous due to unwanted user interaction during loading.
- Optimizes screenshot manager scrolling a bit
> Qt: Load gamelist asynchronously while showing a progress dialog

- rpcs3/Emu/games_config.cpp
- rpcs3/Emu/games_config.h
- rpcs3/rpcs3qt/qt_utils.h
- Fixes a potential data race and undefined behaviour when iterating over games.yml content
- Fixes premature futurewatcher cancelation which led to the abortion of the directory parser (isStarted is basically always true)
fixes #13767
> Qt: Fix data race and undefined behaviour in games_config, fix premature futurewatcher cancelation

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- Mostly refrain from hard refresh after game boot if the game was already known to the game list
- Optimizes switching between list and grid mode by using a soft instead of a hard refresh (possible now without repercussions as far as I can tell)
This should take away some pain for users with large game collections and particularly slow drives.
> Optimize game list refresh behaviour

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/movie_item.cpp
- rpcs3/rpcs3qt/movie_item.h
- rpcs3/rpcs3qt/screenshot_manager_dialog.cpp
- rpcs3/rpcs3qt/screenshot_manager_dialog.h
- Fix segfault when accessing invalid pointers in IconReady function
- Fix narrow icon column when opening rpcs3 after closing it with a visibly empty list
- Don't mount dev_hdd0 in screenshot manager
> Qt: game list fixes

- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/games_config.cpp
- rpcs3/Emu/games_config.h
- rpcs3/main.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- Splits add_only code into own neat function that doesn't affect emulation
- Fixes missing games from "/games" when refreshing the game list during gameplay
I think it's better to have the boot and add stuff seperated, as it got really confusing over time and I realized there's not really much to it.
The new code does not require any modifications to the emulation state apart from loading and mounting parts of the VFS.
This also means less logging which confuses our discord bot.
I first copy pasted the loader code into a different file and started removing all the sections that are not affected by add_only.
Then I removed all the sections that were unreachable (unbeknownst to us).
And finally I reduced the remaining logic to simply log some notes instead of doing more analysis.
I'm sure …
> Loader: split add_only into own function

- .ci/deploy-linux.sh
The previous system is basically unmaintained, this new AppImage packager has proper support for Qt6, and active support from the AppImage team.
In addition, I'm removing a bunch of our old lib hacks and the old ugly C++ library check system.
> Change AppImage packaging to actively maintained system

- rpcs3/Emu/RSX/GL/GLOverlays.cpp
blur_intensity is a float, so the cast needs to be f32 instead of s32
Fixes validation layers spam when using OpenGL and an emulator overlay is visible on the screen
`E RSX: [DEBUG_OUTPUT] [API] [ERROR] [1]: GL_INVALID_OPERATION in glUniform1("blur_intensity"@9 is float, not int)`
> gl: Fix blur_intensity GL_INVALID_OPERATION validation layers error

- rpcs3/rpcs3qt/game_list_delegate.cpp
- Fixes a bug that causes the first item in the game list to have an invisible icon.
Once the first icon got smaller than 30 pixels it wasn't counted as visible.
It turns out that the visibleRegion of the table has an offset that is exactly the size of the table headers.
So the visibleRegion started at (0,30), while the icons' visualRects started at the origin of the table itself (without headers).
When a small icon was at (0,0) with a height below 30 it would therefore never pass the visibility checks.
Simply offsetting the visibleRegion by the header size brought its position back to (0,0), meaning we can properly do the check.
> Qt: fix invisible first icon in game list

- rpcs3/Emu/games_config.cpp
- rpcs3/Emu/games_config.h
Deadlock caused hang when booting a new game through "Boot Game" menu.
> Fix deadlock in games_config

- rpcs3/Emu/RSX/GL/GLTexture.cpp
Use a hand-picked set of routines instead of tying to be clever and autogenerate them. The texel width tells us nothing about the internal layout. 8x1byte is very different from 2x4byte channels.
Fixes https://github.com/RPCS3/rpcs3/issues/13724
> gl: Fix typeless casts

- rpcs3/rpcs3qt/gui_application.cpp
Fixes unwanted and duplicate languages in the language selection.
> Qt: filter for rpcs3_*.qm files when enumerating languages

- Utilities/StrUtil.h
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/Cell/lv2/sys_game.h
- rpcs3/Emu/system_config.h
1. Fixed potential bugs in sys_game_get_system_sw_version().
2. Implemented sys_game_set_system_sw_version().
3. Improved the efficiency of the conversion from device names to mount points for sys_fs_mount() and sys_fs_newfs().
4. Implemented mount_info_map in sys_fs to keep proper track of mounted devices.
5. Further implemented cellFsArcadeHddSerialNumber (0xc0000007) so that the virtual HDD's model name and serial number are now configurable in config.yml.
> sys_fs & sys_game: Misc syscalls enhancement

- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/system_config.h
Implements an approximate but deterministic FREST and FRSQEST.
Moved the intrinsic version to the relaxed accuracy option.
Should fix https://github.com/RPCS3/rpcs3/issues/13714, https://github.com/RPCS3/rpcs3/issues/13683.
Fixes #13733, #13685.
Need testing against the games in https://github.com/RPCS3/rpcs3/issues/5886.
Those games need testing:
> Changes to FREST, FRQEST, FI logic

- rpcs3/Emu/NP/np_handler.cpp
Config was only loaded for rpcn which resulted in config reset when using Simulated.
Thanks @CookiePLMonster for debugging.
> Fix rpcn config reset

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_table.cpp
Fixes a regression caused by copy pasting the list construction to its own constructor.
Fixes #13828
> Qt: fix game list event filter

- rpcs3/Emu/RSX/GL/GLOverlays.cpp
- rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp
- rpcs3/Emu/RSX/Overlays/overlay_fonts.h
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/Emu/RSX/VK/VKOverlays.h
- rpcs3/Emu/System.h
- rpcs3/main_application.cpp
Get the font directory from Windows instead of hard coding it to `C:/Windows/Fonts/`. Also contains a small refactor of `font::render_text_ex`.
> Get the font directory from Windows

- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
* Ensure that only GD game data is used for booting an update.
* Ensure that TITLE_ID matches between game update and disc. (otherwise maybe a different application created it with the same directory name as far as we know)
* Ensure no theoretical recursion occurs in Load. (in reality you need to hack the filesystem with rpcs3 controlled by debugger for it to occur I believe but it shouldn't be possible in the first place)
* Log an error explicitly about disc game update corruption.
> System.cpp: Make boot of disc updates more strict

- rpcs3/rpcs3qt/log_frame.cpp
Value from previous boot was not respected.
> Logs: fix Stack Cell Errors setting reading

- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/memory.cpp
- rpcs3/Emu/RSX/VK/vkutils/memory.h
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
- rpcs3/Emu/system_config.h
This work is mostly focused on getting the vulkan renderer working in overallocated scenarios, such as having upscaling and MSAA enabled with a limited budget. The code was aggressively tested and tuned at 1.5GB, 1GB and 750MB to ensure crashing does not happen easily. I was able to run the test scenario for about 15 minutes without crashing, though on a subsequent run the crash could be reproduced in a few minutes. This is an extreme torture test (5k render res on a AAA title and less than 1G of VRAM allocated) so real-world situations should fare much better.
A new option has also been added (config file only) to control how much VRAM you want to allocate to rpcs3. This is mostly useful for debugging purposes.
This changeset is not final, the memory spilling behavior is not so great as …
> vk/rsx: Improve out-of-memory handling

- rpcs3/Emu/Cell/SPURecompiler.cpp
The value was determined completely empirically by ratios between intrinsics values and accurate value. It is not constant but this version seems more accurate and is faster.
Fixes https://github.com/RPCS3/rpcs3/issues/13839
Fixes https://github.com/RPCS3/rpcs3/issues/13824
Fixes https://github.com/RPCS3/rpcs3/issues/13861
> Better accuracy for FREST/FRSQEST

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/Infinity.cpp
- rpcs3/Emu/Io/Infinity.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/infinity_dialog.cpp
- rpcs3/rpcs3qt/infinity_dialog.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
Having recently made the same changes for Dolphin - I am bringing the code across to Emulate the Disney Infinity Base on RPCS3. The main appeal for this is the wider variety of figures and games available to play - the Wii only has 1.0 (and it runs fairly poorly due to the game's extensive MMU access). I haven't been able to test this much, as the games don't run very well on my M1 Mac - but hoping someone interested will be able to test this out on a powerful Windows device!
There will likely be changes or RPCS3 utils that I can use instead of what I have used currently, but I have largely tried to replicate the same code styling as the skylander dialog tool.
> sys_usbd: Emulate Disney Infinity Base

- rpcs3/rpcs3qt/main_window.cpp
It is not necessary to refresh the game grid after stopping a game.
Fixes some annoyingly flashing grid. (which seems longer than usual on top of that)
> Qt: don't refresh game grid after emu stop

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
- rpcs3/rpcs3qt/main_window.cpp
Usage:
1. You select an address from text on the log or TTY, such as "0x12345678".
2. Right click to show context menu.
3. Click on the added "Go-To On The Debugger" action to jump directly to that address on the debugger.
Additional:
* Make the "Go To Address" dialog non-blocking, simply refocus the existing dialog if one is shown already. This allows to copy addresses from the debugger.
> Logs/Debugger: Go-To-Address signal from log text

- rpcs3/rpcs3qt/microphone_creator.cpp
- rpcs3/rpcs3qt/midi_creator.cpp
This is redundant since it's only used in the settings_dialog where it is manually refreshed anyway.
fixes #13884
> Qt: Don't refresh mic and midi list in constructor

- rpcs3/Emu/Cell/SPURecompiler.cpp
`op` was being used out of scope which led to undefined behaviour.
Thanks to @Nekotekina for figuring it out.
> Fix spu_fm

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_list.cpp
* Scroll through threads conveniently using Ctrl+PageUp or Ctrl+PageDown.
> Debugger: Implement key-scrolling through threads

- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_page.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_page.h
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.h
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_save_dialog.h
- rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.h
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
Currently there's a nasty sound stakkato going on if you keep the dpad pressed to the left in the home menu for example.
> overlays: do not play sounds on fast auto repeat

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
* Fix time underflows in log and kernel explorer regarding waiting time (mixed guest and host time in calculation). Also prevent them in general.
* Display more SPU functions on the debugger.
* Display SPU function names on errors.
* Prevent duplication of entries in kernel explorer when refreshing contents, this occurred because the unique key identifying elements was wrong for many elements and relied on volatile data.
* Fix an emulator crash on exit when there are pending errors to log (in error_code::error_report, dereferenced null SPU context), this fixes stopping emulation in GT6. This also fixes it when an SPU exists in such case.
* Better time consistency in kernel explorer by evaluating current time on first use.
> SPU/Debug Fixes

- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKFormats.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/sampler.cpp
- rpcs3/Emu/RSX/VK/vkutils/sampler.h
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
- rpcs3/Emu/RSX/rsx_utils.h
Turns out some games are really using some unusual border colors (e.g transparent white)
Previous fallback will still exist in case of GPUs without support for this.
Also includes a refactor of how we handle optional features, so that a migration up is easier if we decide to raise our base vulkan version to 1.1 or higher.
Fixes https://github.com/RPCS3/rpcs3/issues/12451
> vk: Add support for VK_EXT_custom_border_color

- Utilities/Thread.cpp
- rpcs3/util/dyn_lib.hpp
This allows to view thread name on visual studio on manual attachment without the need to be attached on boot.
> Take advantage of WIN10 Thread Name API

- 3rdparty/MoltenVK/CMakeLists.txt
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
[Release notes](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.4): 
- Add support for extensions:
- VK_KHR_map_memory2
- Deprecate the obsolete and non-standard VK_MVK_moltenvk extension.
- Add mvk_config.h, mvk_private_api.h, and mvk_deprecated_api.h, and deprecate vk_mvk_moltenvk.h.
- Support BC compression on iOS/tvOS where available (iOS/tvOS 16.4 and above and supported by the GPU).
- Support separate depth and stencil attachments during dynamic rendering.
- Fix memory leak when waiting on timeline semaphores.
- Fix race condition when updating values in VkPastPresentationTimingGOOGLE, and ensure swapchain image presented time is always populated when requested.
- Report error, but do not fail on request for timestamp query pool that is too large for …
> Update MVK to 1.2.4 for Vulkan SDK 1.3.250

- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
Fixes disabling pad interception when closing the media list dialog.
This is just a band-aid until the whole input loop refactoring is finished.
fixes #13463
> overlays: fix media list dialog pad interception

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_list.cpp
* Ctrl+F: focues on the combo box which allows to search thread by text.
* Ctrl+C (handled by QListWidget): copies selected instruction contents. 
* Propagate unhandled key presses to the main window.
> Qt/Debugger: Add Ctrl+F (find thread), Ctrl+C (copy)

- rpcs3/rpcs3qt/debugger_list.cpp
QListWidget::keyPressEvent sets event->isAccepted to false when using some key combinations such as Alt or Ctrl, simply always accept event to avoid event repeatation in debugger_frame.
> Fixup debugger_frame double events

- rpcs3/Emu/RSX/Common/simple_array.hpp
- rpcs3/Emu/RSX/VK/VKCompute.cpp
- rpcs3/Emu/RSX/VK/VKCompute.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
- rpcs3/Emu/RSX/VK/VKHelpers.cpp
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/Emu/RSX/VK/VKOverlays.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKResolveHelper.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.h
- rpcs3/Emu/RSX/VK/VKTextOut.h
- rpcs3/Emu/RSX/VK/vkutils/descriptors.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.h
- rpcs3/Emu/RSX/VK/vkutils/garbage_collector.h
- rpcs3/VKGSRender.vcxproj
- rpcs3/VKGSRender.vcxproj.filters
Removes the old method of using per-frame descriptor pools that was copied from the original vulkan tutorials in 2016. It scales very poorly and forces us to have callbacks all over the place as well as setting hard limits on number of descriptor sets that can be allocated per frame.
This PR makes a few changes to the vulkan backend:
1. Some minor refactoring of the garbage collector allowing callbacks to be pushed to the dispose queue. These execute in-order so we can safely reclaim resources once the execution queue releases them.
2. You can now allocate as many descriptors as your driver and setup can handle (virtually infinite). The allocator will just create more pools as demand increases.
Some more cleanup is needed - we should never have any of those "reset_resources" or …
> vk: Rewrite descriptor allocations

- Utilities/rXml.cpp
- Utilities/rXml.h
- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/Loader/TROPUSR.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
Turns out we never cared to check whether pugixml returns valid objects.
This led to the possibility of assersions in the pugixml backend when calling functions on invalid root nodes.
Let's just log errors and skip the trophy enumerations instead in these cases.
Also fixes the random selection of a game when opening the trophy manager.
> Trophies: Add more sanity checks to pugixml backend

- rpcs3/Emu/System.cpp
Fixes Skyrim Legendary Edition missing installations.
> Extra PS3_EXTRA fix

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/vkutils/descriptors.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.h
Improves VRAM utilization drastically especially with some games known for excessive number of surface cache objects (e.g the insomniac engine)
Changeset:
1. If the number of "invalidated" i.e temp storage items reaches a set limit, attempt to collapse some objects to free up memory. Currently the hard limit is 256 which is arbitrary but seems to keep VRAM usage under 2GB at default settings which is what we want.
2. When handing out-of-memory situations, remove invalidated resources by collapsing as many dependency chains as we can. This was missing previously, and made it so that out-of-memory recovery was not recovering tons of memory in some situations.
3. Minor tweaks to avoid crash on exit after the descriptor rewrite PR.
Fixes https://github.com/RPCS3/rpcs3/issues/13928
> rsx: Improve surface cache trimming

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.h
- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.h
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.h
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.h
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/Cell/lv2/sys_timer.h
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
- rpcs3/rpcs3qt/register_editor_dialog.cpp
- rpcs3/util/asm.hpp
I've been laying low lately because I've been working on imprvements to Gran Turismo 5' stability. After many hours debugging and head-racking here are all the fixes to make GT5 not freeze anymore, enjoy.
One thing to not is that you need RSX FIFO Accuracy set to Atomic and enable Accurate RSX reservation access.
Fixes #10882
> Gran Turismo Improvements

- Utilities/File.cpp
- Utilities/File.h
- Utilities/StrUtil.h
- rpcs3/Emu/Cell/Modules/cellSysCache.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_ss.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/VFS.cpp
- Implemented sys_fs_mount() with argument prot=1 for mounting VFS devices in read only mode (mainly used by XMB).
- Further implemented Update Manager service so that the progress of firmware update in XMB can go to 99%, tested in DEX&DECR.
- Implemented sys_usbd_unregister_extra_ldd() and improved the other ldd-related syscalls.
> sys_fs, sys_ss, and sys_usbd: LV2 syscalls enhancements

- rpcs3/rpcs3qt/call_stack_list.cpp
- rpcs3/rpcs3qt/call_stack_list.h
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
* Do not access IDM's containers when their FXO entry is inactive.
* Save smart thread pointers in the debugger instead of raw pointers.
* Fix segfault when a double click signal occurs after ui callstack has been cleared.
* Add return key press in addition to double click to jump to callstack item address.
* Fix debugger shortcuts when callstack is the focused widget.
Fixes #13865
> debugger: Bugfixes

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
See https://github.com/RPCS3/rpcs3/pull/13840#discussion_r1218553582
> [Hotfix] sys_fs: fix map entry removal in destructor

- rpcs3/Emu/Io/pad_config.cpp
- rpcs3/Input/pad_thread.cpp
> input: fix pad profile override with existing custom pad configs

- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/Crypto/unpkg.cpp
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
- rpcs3/rpcs3qt/register_editor_dialog.cpp
Thread joining on stop was missing in a few places where they would previously be detached from IDM. Fortunately no lingering shared_ptr copies of spu/ppu_thread were made previous to #13948 on a regular basis so this went unnoticed. (although some debugger tools made use of make_check_cpu so that crash could have been reproducible before in some cases)
Hopefully fixes https://github.com/RPCS3/rpcs3/issues/13962
> Fix bugs related to lingering spu/ppu thread copies

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
I tested what happens if I let a thread return without calling sys_ppu_thread_exit, at first when a debugger was attached the process was paused.
But after detaching it the process would emit a thread dump but the other threads kept running!
This is what happens in #13274 which lets its thread do that and even relies on that, because just before the return of the entry function there is a store that releases the main PPU thread from a loop waiting for that byte to be set.
Fixes #13274.
> PPU: Sleep after returning from thread entry function

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKQueryPool.cpp
Just disable conditional render. Tile-based GPUs are not compatible with some of our sneaky speedhacks for cond-render such as streaming query results while a renderpass is active. Doing it the "right way" cuts performance down significantly so the only viable approach is to disable the fast path entirely and force use of the fallback used by OpenGL.
Fixes https://github.com/RPCS3/rpcs3/issues/12158
> vk: Fix broken rendering on apple M-series GPUs

- rpcs3/Emu/Cell/lv2/sys_ss.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Loader/PSF.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- Debugger: don't query cpu if the emulation is stopped anyway
- Rename ProcureCurrentEmulationCourseInformation to GetEmulationIdentifier, which seems much easier to understand to me.
- Fix typo in restore_on_no_boot: duplicate m_config_mode vs m_config_path
- Fix start/restart shortcut mixup in main window. At least I think this makes more sense.
- Fix menu/thumbnail play button texts on stop and ready. They were always showing 'Resume' for no apparent reason (legacy code?).
- Always use last original boot path for GUI game boot actions.
This fixes an issue which caused decryption issues booting a recent game after booting a game from a loader.
The GUI should now always boot the loader and not some self.
> Random fixes

- 3rdparty/robin_hood/include/robin_hood.h
- rpcs3/Emu/RSX/Common/unordered_map.hpp
- rpcs3/Emu/RSX/Core/RSXDisplay.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
- rpcs3/Emu/RSX/rsx_cache.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3qt/settings_dialog.cpp
- Allow MTRSX to work well with the vertex cache.
- Optimize the vertex cache routines. It is now around 5x faster than before in games with decent hit ratios. In overall terms, we get a ~5-10% in draw-call-limited scenarios (e.g infamous)
This PR introduces use of robin-hood, a drop-in replacement for std::unordered_map that is much faster with large datasets.
> rsx: Vertex cache improvements

- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- Always release barrier references before destroying surfaces. In rare cases the surface may be detached without a collapse ever being triggered.
Fixes https://github.com/RPCS3/rpcs3/issues/13935
> vk: Improved OOM handling

- .ci/install-freebsd.sh
`llvm16` [built fine](https://pkg-status.freebsd.org/beefy16/data/131amd64-default/b848aeb67d45/logs/llvm16-16.0.5.log) and available again:
```
$ fetch -s https://pkg.freebsd.org/FreeBSD:13:amd64/latest/All/llvm16-16.0.5.pkg
198935032
```
> CI: use more recent FreeBSD packages again

- rpcs3/Emu/System.cpp
It seems like a few non-system SELFs could be affected by the previous definition (by #13840).
In this PR, I modified the definition of user-space LV2 CoreOS SELFs (determined by `Emu.IsVsh()`) to be stricter.
> [Hotfix] System.cpp: Updated the definition of user-space LV2 CoreOS SELFs

- rpcs3/Crypto/decrypt_binaries.cpp
- rpcs3/Crypto/decrypt_binaries.h
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/main_window.cpp
* Make it non-blocking. This tool requires to copy the KLIC from the log, cannot do that conviently without access to log or without the ability to execute a game.
* Allow the prefix "KLIC=0x" to be added at the start of the KLIC text, and add this to the log message for it be easier to understand and search it by users.
> Qt: Improve PS3 Binaries Decryption tool

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.cpp
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/rpcn_client.cpp
No idea if this is necessary, but there's a warning for the socket return value
> np_handler: fix warning: check socket in discover_ip_address

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
- rpcs3/Emu/RSX/VK/VKHelpers.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.cpp
- rpcs3/Emu/RSX/VK/vkutils/shared.cpp
The intel driver only support 1 million descriptor objects (we use update-after-bind everywhere) which sounds like a lot until you consider that we consume something like 50 of them every draw call. The moment a complex scene appears the driver implodes.
This fix adds a fallback in the form of a full stall to reset the queues. The downside to this is that intel GPUs will never be able to render high-draw-call-count titles at any reasonable framerates. Anything with over 10k draws will just crater.
Fixes https://github.com/RPCS3/rpcs3/issues/13997
> vk: Handle VK_ERROR_FRAGMENTATION when allocating descriptor pools

- rpcs3/Crypto/decrypt_binaries.cpp
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
There seems to be an unwanted - or at least mishandled - std::move of the ppu function map in ppu_module::analyse.
The object is used later again, so this seems like a bug to me.
> PPUAnalyser: fix std::move misuse

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/Emu/system_progress.hpp
For some reason setting the member of the progress_dialog_server to true doesn't work.
But it works if i again add the workaround.
I don't know why :)
> progress dialog fix

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKQueryPool.cpp
- rpcs3/Emu/RSX/VK/VKQueryPool.h
RPCS3 emits query begin/end pairs corresponding to PS3 occlusion queries. Some PS3 games spam occlussion queries quite a lot, and we can end up generating hundreds of these per frame. We then read the data back using vkCmdCopyQueryResults with VK_RESULT_WAIT_BIT set to copy over the data to a buffer when available.
Unfortunately, this command and flag combo has an unusually high cost on NVIDIA drivers. We can't bring down the number of queries requested, but we can exploit the fact that our query generator uses a stack-based allocator which almost guarantees that every set of query objects will have adjacent descending query indices. This setup allows us to group the indices into larger batches for the copy operation which results in a major speedup.
Fixes the unbearable single-digit …
> vk: Batch query copy requests to reduce number of vulkan commands used

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp
Should fix https://github.com/RPCS3/rpcs3/issues/14002
> Move connect workaround to connect interface

- Utilities/JIT.cpp
This fixes the assertion `Second attempt to perform debug registration.` which happens in `GDBJITRegistrationListener`. It happens on Linux if compiled in debug mode. 
```
auto cache = ObjectCache::load(path);
```
This variable contains the code. A reference to it is added to the JIT compiler and then it is destroyed at the end of the function `jit_compiler::add` and the JIT compiler now has a reference to destroyed code.
I changed it to pass the ownership of the code to the JIT compiler.
> jit: fix assertion in GDBJITRegistrationListener

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/memory_viewer_panel.cpp
- rpcs3/rpcs3qt/memory_viewer_panel.h
- rpcs3/util/asm.hpp
* Add auto-refresh mode for the memory viewer, refreshing contents in 60hz.
* Shortcut in RSX debugger to view RSX semaphores area. (Alt+S)
* Add Grey8 and a special G32MAX (shows the max color between sets of neighboring 4-byte groups) image formats.
* Fix memory leak in the memory viewer.
* Add Ctrl+PageDown, Ctrl+PageUp shortucts for faster scrolling.
* Add Ctrl+F to refocus on the address line.
* Add Ctrl+F5 for manual, single memory refresh.
* Added image scaling for image viewer with Ctrl+Plus, Ctrl+Minus.
* Added hover position for image viewer to see which address is being pointed at, when double clicking on it the image viewer is closed and the memory viewer jumps to the clicked memory data.
> Memory Viewer Improvements

- rpcs3/Emu/RSX/VK/VKAsyncScheduler.cpp
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
Vulkan 1.0 events kinda suck and caused artifacts in some titles which I had worked around using simple GPU lock structures. This PR introduces synchronization2 for these scenarios where synchronization1 is inadequate.
Closes https://github.com/RPCS3/rpcs3/issues/13718
(Hopefully) Closes https://github.com/RPCS3/rpcs3/issues/12021
> vk: Use synchronization2 extension for events

- Utilities/File.cpp
- Utilities/File.h
Should fix #14031 .
Tagging @brian218 to explain the change.
Issues's problem is that std::path("＄locks") returns "ï¼„locks/" with japanese locale.
Keep in mind that we already call setlocal("C") on startup so some code overwrites it.
Some places in code also use the pattern `(file_path.substr(get_parent_dir(file2_path_in_x_directory, x_times).size()) == trail path from parent directory)` which breaks with the code on master.
> File.cpp: revert get_parent_dir change

- Utilities/File.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
I implemented `fs::get_normalized_path()` and accordingly updated some sys_fs code as per the conclusion suggested by @Nekotekina and @elad335 in #14086.
> sys_fs: Updated some fs-related code following up #14086

- rpcs3/rpcs3qt/about_dialog.cpp
- rpcs3/rpcs3qt/about_dialog.ui
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/welcome_dialog.cpp
- rpcs3/rpcs3qt/welcome_dialog.h
- rpcs3/rpcs3qt/welcome_dialog.ui
* Allow to drag-and-drop RAP + EDAT + PKG together onto the UI. Previously PKG could not be dropped with other file types.
* Make "Add Games" not required to stop emulation.
* Fix memory leak in the welcome dialog.
* Make the Welcome Dialog accessible through F1 or the Help section in the main toolbar.
* Enable the Window Close button in the welcome dialog after "I have read the Quickstart" is checked.
* Allow creating shortcuts to RPCS3 in the welcome dialog. 
* Make the 100% Resolution Scale appear as "100% (1280x720) (Default)" instead of "100% (Default)"
* Add RPCS3 Discord and Wiki to the About Dialog.
> RPCS3 Setup QoL Improvements

- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/Cell/lv2/sys_rsx.cpp
- rpcs3/Emu/RSX/Capture/rsx_replay.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_main_menu.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/main_window.cpp
* Like #13630 which made loading games not freeze UI, before this pull request stopping emulation made the UI freeze and if took too long Windows may even make the window white and try to kill the application. But with this pr the UI is fully responsive when stopping emulation, this is also true for savestates which had an even longer pause. (albeit currently still suffering from regressions)
* If you have been unlucky, you could have randomly encounter "Stopping emulation took too long" message after a few seconds when quitting the game and then the emulator simply crashed. Now you can choose to wait more for it to close safely or force terminate RPCS3. In case it closes safely while the dialog is open the dialog would close automatically. There is an indication of how many seconds have …
> Make stopping emulation not pause or crash UI

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/shortcut_settings.cpp
- rpcs3/rpcs3qt/shortcut_settings.h
- rpcs3/rpcs3qt/welcome_dialog.cpp
- Fixes weird closing of the welcome dialog when checking the "I have read..." checkbox
- Use a shortcut instead of the hardcoded keypress for the welcome dialog
- Remove some hardcoded shortcut hint that seems to be leftover code
> Fix Welcome Dialog regression

- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/system_config.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
> input/overlays: add option to lock overlay input to player one

- rpcs3/Emu/Io/RB3MidiGuitar.cpp
Rock Band 3 has support for playing the regular guitar mode with the pro guitar. While the real MPA does not support this, the game accepts it just fine so there's no harm in emulating it.
> RB3MidiGuitar.cpp: Support the regular guitar mode.

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/IdManager.h
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/util/types.hpp
* Fix Create PPU Cache, allow it to be usable again.
* Implement PPU SELF precompilation, preventing compilation ingame with many game collections, RDR, GT6 and more.
* Make bad game patches not able to crash the emulator, simply ignore them (bad addresses resulted in segfaults)
* Add one fix of savestate.
Fixes #12320
Fixes #13534
> Fix Create PPU Cache, Implement SELF precompilation, Savestate fix 1 out of 3 

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
* init_mem_contianer was called during precompilation of RDR2.self (set up by _sys_process_exit2), this is wrong and fixed.
* Empty after_kill_callback before use to avoid situations in which its called recursively if calling Emu.Stop() inside Emu.Load(), same with init_mem_container but there is just for safety.
* Disable PPU precompilation for child processses (already done in parent process), speeding up boot a little in RDR.
Fixes #14110
> Hotfix after #14090

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.h
- rpcs3/rpcs3qt/rsx_debugger.cpp
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.h
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
* Paramters may have changed before the destructor of Qt objects have been called, save UI geometry and settings in closeEvent instead.
* Save to disk once the dialor or main window is closed so force application termination won't cause the settings to be lost.
> Qt: Save UI settings and geometry safely on closeEvent

- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/garbage_collector.h
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
Turns out the acquire barrier in vkCmdSetEvent2 may not synchronize host operations properly. This is mostly a grey area in the spec, so let's not take any chances.
TODO:
Fixes https://github.com/RPCS3/rpcs3/issues/14106
> vk: Use pipeline barriers for proper event sync

- rpcs3/Emu/Io/pad_types.h
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/rpcs3qt/microphone_creator.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/tooltips.h
- Adds tooltips for button mapping (hover on a button).
- Allows for updates on already pressed keyboard buttons when pressing the pressure sensitivity button.
- Should hopefully fix all issues with multibuttons when using the keyboard.
Previously, the mouse presses, mouse wheel and mouse move would override any other key on the same button.
Additionally, mouse interaction was not working in tandem at all anyway.
Last but not least this should also fix any issues regarding stick or button interpolation with multibuttons on the keyboard.
> Input: Fix multibutton input for mouse interaction

- rpcs3/util/vm_native.cpp
Needs testing with #14115
Fixes #14115 (reopen if persists)
> vm_native.cpp: Workaround for rpcs3_vm_sparse.tmp crashes

- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureMSAAOps.glsl
Fixes https://github.com/RPCS3/rpcs3/issues/12514
> rsx: Clamp MSAA sampling weights to avoid clipping

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
I have been working on a microcontroller [firmware](https://github.com/sanjay900/guitar-configurator) for the last few years that is being used by a lot of people playing clone hero, guitar hero, rock band and dj hero. At this point, its being used by most modded guitar hero controllers out there, and a fair amount of Wii extension usb adapters are being sold running it as well.
I have been working on a update to the firmware that can detect what console it is plugged into, and switch to the correct mode for that console. I would like RPCS3 to also trigger this, but unfortunately the requests i look for on a PS3 are never triggered with RPCS3. A simple control request is enough to jump to PS3 mode, and since my controllers automatically install WINUSB drivers, this even works perfectly …
> sys_usbd: Implement support for Santroller devices

- rpcs3/Emu/System.h
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Option to pause automatically emulation when RPCS3 losses its focus or the application becomes inactive.
This option is targeted to save CPU time and reduce power consumption when you are not using RPCS3.
The actual pausing is being delayed by one second after inactive state is detected so Emu.Pause() would not be spammed. (this function is not perfect so spam-calling is not a good idea)
The setting is called "Pause emulation on RPCS3 focus loss" and is found on Emulator tab.
The setting is dynamic.
> UX: Option to pause emulation when RPCS3 is not focused

- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_utils.cpp
- rpcs3/Emu/system_utils.hpp
- rpcs3/main_application.cpp
Turns out disabling the log at all times is a bit counter productive.
> Only silence logging during gameplay

- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
The dynamic interpreter is also allowed in this case.
Fixes it for games such as FIFA Street 3 which use the decrementer event interrupt.
> SPU: Fix static interpreter requirement with interrupts

- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_components.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_settings.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_settings.h
- Move "Driver Wake-Up Delay" to advanced page
- Move "VBlank NTSC Fixup" to advanced page
- Move "VBlank Frequency" to advanced page
- Change "VBlank Frequency" step size to 30
- Add support for value label overrides
- Replace 0 with "Auto" in "Anisotropic Filter Override"
- Add "x" suffix to "Anisotropic Filter Override" (2x,4x,8x vs 2,4,8)
> Home menu: settings improvements

- rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.h
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureOps.glsl
- rpcs3/Emu/RSX/Program/GLSLTypes.h
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
https://github.com/RPCS3/rpcs3/issues/14142
Testing needed:
> rsx: Reimplement projected texturing to play nice with the subimage views

- rpcs3/Emu/System.cpp
> Write config.yml if it was empty on boot

- rpcs3/Emu/RSX/Common/TextureUtils.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- rpcs3/Emu/RSX/GL/glutils/sampler.h
- rpcs3/Emu/RSX/RSXThread.h
Adds a transformation stack to the texture references. The subimage transform is destructive and we may decide to roll back later.
Also lowers a fatal assert into a logged error message.
Fixes https://github.com/RPCS3/rpcs3/issues/14176
Fixes https://github.com/RPCS3/rpcs3/issues/14103
> rsx: Preserve the texcoord transform around destructive modifications

- .ci/build-mac.sh
- .cirrus.yml
Adds Cirrus CI caches for /Users/admin/Library/Caches/Homebrew and qt-downloader.
> macOS CI: add Homebrew and Qt caches

- rpcs3/Emu/RSX/VK/VKTexture.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/14121
> VUID-vkCmdCopyBufferToImage-commandBuffer-07737
If the queue family used to create the [VkCommandPool](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkCommandPool.html) which commandBuffer was allocated from does not support VK_QUEUE_GRAPHICS_BIT or VK_QUEUE_COMPUTE_BIT, the bufferOffset member of any element of pRegions must be a multiple of 4
> vk: Don't load depth-stencil textures on the transfer queue

- rpcs3/Input/keyboard_pad_handler.cpp
> Qt: ignore Qt::Key_unknown when parsing key sequences

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
CR register is composed of 8 different fields which are 32 bits in total, it's not easy to track and intuitively understand its relavant bits to the current code and how they affect the current thread code and being affected by it.
So this pull requests aims to predict what is the most relavant CR field to the current code and display it in an intuitive manner.
There is a specialization for STDCX and STWCX. (but other CR0 modifing instructions are currently not being detected)
Example: detected used CR4 field in context.
But when I keep stepping in this code and encounter an instruction using CR7:
> PPU/Debugger: View the currently used CR field content in register panel

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
* Stuff like writing u32 to 0xffffffff could have resulted in an RPCS3 crash due to size of patch not being taken intoi account when checking memory validity.
* Add a new patch type called "cutf8" which is a null-terminated UTF8 string. (same semantics as std::string)
* Fix alloc patch type recent regression and fix its behavior with PRX/SPU patches.
> Patches: Fix potential RPCS3 crashes due to invalid patches

- Utilities/bin_patch.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/elf_memory_dumping_dialog.cpp
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/memory_viewer_panel.cpp
- rpcs3/rpcs3qt/patch_creator_dialog.cpp
- rpcs3/rpcs3qt/patch_creator_dialog.h
- rpcs3/rpcs3qt/rsx_debugger.cpp
- rpcs3/rpcs3qt/system_cmd_dialog.cpp
- rpcs3/rpcs3qt/vfs_dialog_usb_input.cpp
- rpcs3/util/yaml.cpp
- rpcs3/util/yaml.hpp
Backend:
- Validate yml patch offset values (prevent overflow)
- Do not allow empty patch names
- Fix logging for locations of node iterators (previously "location: invalid node")
- Improve location logging of some other invalid patch nodes
Frontend:
- Add validator to patch creator bottom offset line edit (updates depending on patch type)
- Add clear buttons to patch creator bottom line edits
- Highlight faulty lines in patch creator
- Fix some memory leaks regarding QValidators
Caveats:
- The table itself doesn't validate the offset input, but at least you now get better feedback in general.
fixes #14169
> Qt/Patches: Improve patch validation and patch creator

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
* Drop PPU linking stage from precompilation, this does not affect EBOOT.BIN compilation when booting games of course but affects the precompilation of SELF, MSELF and SPRX.
* Fixes a tiny race when stopping emulation which could resulted in PPU attempting to execute LLVM compiled code but no function pointers have been written yet.
> PPU LLVM: Improve precompilation time

- rpcs3/rpcs3qt/main_window.cpp
Sometimes users attempt to drag-and-drop unfitting file types like ISO onto the main window, and because RPCS3 accepts any file type - it results in confusion of both RPCS3 and the user.
Restrict dropable file formats to - directory, "rap", "edat", "pkg", "pup", "rrc", "savestat", "sprx", "self", "bin", "prx", "elf" and "o".
The emulator can still load any file type using CLI or from "Boot "(S)ELF" in the main toolbar if this is required.
> Qt: Restrict file types for drag-and-drop

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
Before it used to check file attributes of dropped file list every time the mouse pointer changed its location on the screen even by a pixel, this is not very useful and only spams the disk. Instead, cache the information for half a second before re-evaluating it.
> Qt: Cache drag-and-drop result when moving it

- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/system_config.h
This setting ("Usleep Time Addend" in game config file) affects the sleeping time passed to the sys_timer_usleep PPU syscall by adding the specified value to it. Significant performance improvements have been noted when using this setting with some games (see https://github.com/RPCS3/rpcs3/pull/12598#issuecomment-1236063568). This setting allows negative values for up to -1000 and positive values for up to 1500. (default is 0 - no adjustments to sleeping time)
> Implement PPU usleep control setting hack

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Crypto/unedat.h
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
Mimicking std::filesystem::equivalent() when comparing two file IDs, also adds readable information about the types of the overriding classes.
This feature is needed for savestates.
> Implement fs::file::get_id()

- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/util/logs.cpp
- rpcs3/util/logs.hpp
Simplifying issue-creation a bit.
This exits RPCS3 and lets tge user choose where to save the log file. 
I made it so it would also rename the log file to "{GAME TITLE} [{TITLE ID}].log" (the last game that was running) in the directory that the user chooses when pressing that button specifically, otherwise it is remained "RPCS3.log".
This also fixes the long lasting issue that RPCS3 erases old log file when it opens (because it only writes to new RPCS3.log, leaving the previous one untouched).
> Qt: Exit And Save Log - toolbar action

- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/util/dyn_lib.hpp
I noticed that RPCS3 could use some more PS3 file structures.
Main intention is to aid converting savedata for usb users of Apollo Save Tool [NP0APOLLO]
> Create New Paths for Dev_USB and mms

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
Japanese PS3 games often use unicode paths which hard crash the std::filesystem::string() method.
wstring() would work in these cases, but I guess we can just use path() instead of u8path().
No idea why it was proposed by @Nekotekina .
Fixes #14135 (probably)
For reference, this code will reproduce the crash:
```cpp
sysutil_register_cb([](ppu_thread& cb_ppu) -> s32
{
vm::var<char[]> str = vm::make_str("/dev_bdvd/PS3_GAME/USRDIR/DATA/SOUND/VOICE/OBLIVION.ESM/イン/M/GENERIC_POWERATTACK_000C454A_1.MP3");
auto [err, vpath] = translate_to_sv(str);
cellOskDialog.error("translate_to_sv(str=%s, vpath=%s)", str.get_ptr(), vpath);
std::string path;
std::string local_path = vfs::get(vpath, nullptr, &path);
cellOskDialog.error("get(path=%s, local_path=%s)", path, local_path);
const lv2_fs_mount_info& …
```
> sys_fs: use path instead of u8path

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/rpcs3qt/main_window.cpp
* Allow non-english leetters.
* Fix missing ']'.
* Deduplicate spaces.
* Show log directory on success to further simplify log finding.
> Qt: Fix saved log filename

- rpcs3/Emu/Io/usio.cpp
Some games such as Tekken Tag Tournament 2 would throw the BACKUP MEMORY ERROR on boot because we didn't emulate the whole USIO SRAM, which the games refer to as backup memory.
> USIO: Fixed BACKUP MEMORY ERROR for some games

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/main_window.cpp
In addition, fix allowance of caches/games to be removed while the game is still running.
Imagine removing the currently running game lol!
> Game List: Add Remove HDD1 Cache option

- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/Io/usio.h
- rpcs3/Emu/Io/usio_config.h
Added support for Tekken Tag Tournament 2.
Support Dragon Ball: Zenkai Battle by the same function as well.
With this PR merged, the following 3 System 357/369 arcade games are fully supported by RPCS3:
- Taiko no Tatsujin series
- Tekken Tag Tournament 2 (Unlimited)
- Dragon Ball: Zenkai Battle
By the way, in my opinion, there's no any point keeping the small drum hits for Taiko, so I removed them to make the configuration tidy. It's not by accident.
> USIO: Added support for Tekken Tag Tournament 2 and Dragon Ball: Zenkai Battle

- rpcs3/rpcs3qt/gl_gs_frame.cpp
- rpcs3/util/vm_native.cpp
I tried fixing the Qt warnings that are printed when you compile RPCS3 in debug mode.
```
warning: QOpenGLContext::swapBuffers() called with non-exposed window, behavior is undefined
```
```
warning: Attempting to create QWindow-based QOffscreenSurface outside the gui thread. Expect failures.
```
> opengl: fix Qt warnings

- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/System.cpp
Fixes backed up config path during Emu.Restart. (Looks like copy pasta error from the same bug that was present in BootGame())
Adds some more logging to some errors in cellSaveData.
Maybe addresses #13709
> Loader: Fix config path in Emu.Restart

- Utilities/File.cpp
- Utilities/File.h
- Utilities/bin_patch.cpp
- rpcs3/Emu/Cell/Modules/cellPhotoImport.cpp
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/RSX/rsx_cache.h
- rpcs3/Emu/System.cpp
- rpcs3/Loader/TAR.cpp
- rpcs3/rpcs3qt/main_window.cpp
GCC on Windows broke because `stat` is macro in mingw-w64 headers. I have renamed `fs::stat` to `fs::get_stat` just like I did in my other PR.
> rename fs::stat to fs::get_stat

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Io/usio.cpp
I tested `sys_fs_fcntl(0xc0000007)` aka `cellFsArcadeHddSerialNumber` on my real hardware, validated the result, and compared the output values with the ones obtained from some other methods on my PC.
It turned out that padding and alignment (model: left, serial: right) are used by `sys_fs_fcntl(0xc0000007)` to compose the output.
Following is the information of my HDD obtained through `sys_fs_fcntl(0xc0000007)` for example:
```
Model Name: "TOSHIBA MK3265GSX H                     "
Serial Number: "           0A1B2C3D4"
```
Also, it seems like the syscall doesn't care about the device name in the arguments, though it's supposed to be "CELL_FS_IOS:ATA_HDD".
I also tested `sys_fs_fcntl(0xc0000015&0xc000001c)` on my real hardware, and it turned out the error handling was a little bit …
> sys_fs: Fixed up sys_fs_fcntl(0xc0000007, 0xc0000015, and 0xc000001c) according to real hardware testing

- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
~~* Parse TTY.log at the end of rpcs3.log anytime emulation is stopped.~~
~~* Add TTY headers between each application boot.~~
~~* Replace std::stringstream with std::string (GUI TTY), faster processing.~~
~~## Bugfixes~~
~~* Use the same file descriptor for GUI TTY and sys_tty. This fixes a situation where buffers are not flushed from the filesystem onto the disk, resulting in missing lines in GUI. TTY.log file itself remains so if rpcs3 crashed the user can still see TTY output.~~
Ouput TTY data of the emulation session when stopping emulation.
> Place TTY output in log when stopping emulation

- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/System.cpp
* Dump it to the log after emulation has been stopped.
* Fix potential filesystem related crash when spu.log cannot be accessed during function dumping.
> Include spu.log inside RPCS3.log when SPU Debug is enabled

- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
Adds detection for new AVX10 features: https://cdrdv2.intel.com/v1/dl/getContent/784267
In short, AVX10 is AVX-512 with optionality to not implement 512-wide vectors. Since much of the code in RPCS3 that uses AVX-512 doesn't use 512-wide vectors, we need new bools to guard 128/256 wide code that's using AVX-512 instructions, since both AVX-512 and AVX10 processors can execute these paths.
> Utils: Add initial AVX10 support

- rpcs3/Emu/Cell/SPURecompiler.cpp
- Takes advantage of vrangeps and the new float to uint instructions from AVX-512
- Down from 6 to 3 instructions
<Details>
<summary> Before </summary>
</Details>
<Details>
<summary> After </summary>
</Details>
> SPU LLVM: AVX-512 optimization for CFLTU

- Utilities/Thread.cpp
- rpcs3/Emu/RSX/RSXDisAsm.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/gcm_enums.cpp
- rpcs3/Emu/RSX/gcm_printing.cpp
- rpcs3/Emu/RSX/gcm_printing.h
- rpcs3/Emu/RSX/rsx_decode.h
- rpcs3/rpcs3qt/rsx_debugger.cpp
Each `rsx::thread::dump_regs()` call, thousands of strings were allocated and copied. This resulted in the debugger being sluggish.
This is changed with this pr which replaces acopies and allocatings with appending to one unified string result.
> Optimize RSX Debugger

- rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
Fixes #13977 (spams cellMsgDialogAbort, ignoring CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED)
> cellMsgDialogAbort: do not return CELL_MSGDIALOG_ERROR_DIALOG_NOT_OPENED

- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Memory/vm.cpp
Needs PPU cache removal and rebuilt to test the pr.
Not to be merged before #14404 so perf comparison would accurate to what it was earlier.
Although testers are welcome.
Imnproves Persona 5 performance a bit.
May improve #14386
> PPU LLVM/SPU/Non-TSX: Obnoxiously responsive and obedient PPU for SPU requests

- rpcs3/Crypto/decrypt_binaries.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Loader/ELF.h
* Fix regression with manual-KLIC-required files from #13990 
* Dump PPU executables (currently not PRX or OVL) when enabling PPU debug when booting games or on process exitspawn.
* Optimize memory usage of ELF loader, found by accident when testing the PR.
This was the difference in file size when using this dumping code and the decryption tool because elf_object::open/save were not optimized to include inner sections.
> Auto-dump binaries (PPU Debug), reduce ELF loader RAM usage

- rpcs3/main.cpp
The "Current date" information that's printed at start of log file was missing leading zero if current time is only one digit number.
```
Current Time: 2023-08- 4T10:23:29
```
With this change the leading zero is added and the timestamp is ISO 8601 compliant
```
Current Time: 2023-08-04T11:17:10
```
> Fix current date format

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
In some cases, we may have to update a texture reference without the RSX state having changed. This can happen for example if the game tries to use a color texture for depth read, so we swap the color texture with a depth one in-place. In this case, we would detect the change and switch the texture, but the shader would still be expecting the original texture because core RSX registers relating to texturing were not changed.
If we trivially detect the format class changed, reload the shader texture state. This isn't sophisticated, but should work for all of cases that would result in a crash.
Fixes https://github.com/RPCS3/rpcs3/issues/14071
> rsx: Rebuild shader texture state if we detect a silent mismatch

- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
In Metal Gear Online there are certain situations where you should be unable to type or use the on screen keyboard, for example when you are stunned/asleep or when transitioning through a loading screen. This change more or less makes the OSK work as it should in MGO, however I'm not sure what real hardware expects or if this affects any of the other games that use native keyboard handling (there aren't many).
> overlays/osk: respect ignore_device_events

- .ci/build-mac.sh
Works around a possibly broken Homebrew package update.
Fixes https://github.com/RPCS3/rpcs3/issues/14419
> macOS CI: build faudio from source

- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/main.cpp
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
Uses user mode wait instructions when available, and an appropriate number of threads on the machine are detected.
Should improve power efficiency on windows particularly for users with Ryzen and at least 12 threads, or users with 12th gen intel and at least 12 threads.
Also has some improvements for linux timers, thanks to the ability to set the timerslack.
> timerslack improvements for linux and usermode waiting 

- rpcs3/rpcs3qt/gui_application.cpp
Fixes an issue that prevents unofficial builds from working correctly (at least on macOS) since the switch to Qt 6.
Specifically, the game window does not open (but the game still runs in the background and audio can be heard), and right clicking on the log window does not show the context menu even though the cursor changes.
Setting the warning window to "modal" (as it seemingly was before switching to Qt 6) fixes this.
Changes this:
To this:
I'm not sure if the cause is a Qt bug, or just the way Qt handles non-modal windows with no parent on macOS.
> Make experimental build warning modal

- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Since **Mesa 22.2.0 (2022-09-21)**, commit [f06da59fd75d7ce7708d159753fcdbc11de16f9e](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/11027/diffs?commit_id=f06da59fd75d7ce7708d159753fcdbc11de16f9e), the deviceName property has included the name of the GPU, thus invalidating our previous method of detecting RADV as a driver vendor.
Because the AMD check looks for "Radeon" and comes before the RADV one, RADV drivers started wrongly being detected as AMD proprietary. The fix is to simply do the RADV check before the AMD one.
Examples:
Before: "AMD RADV NAVY_FLOUNDER"
After: "AMD Radeon RX 6700M (RADV NAVI22)"
Before: "AMD RADV RENOIR"
After: "AMD Radeon Graphics (RADV RENOIR)"
> vk: Fix detection of RADV on get_driver_vendor()

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/lv2/sys_memory.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/System.cpp
~~May fix VSH. Many thanks to @Darkhost1999 for finding the pull request that caused the regression!~~
> PPU LLVM Cache Fix

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
* ~~The first commit fixes the infinite loading with [Transformers: Rise of the Dark Spark](https://forums.rpcs3.net/thread-200305.html). This was a proven fix on real hw for a long time that I forgot after a while, turned out this fixes this game.~~
This commit was actually merged as part of the GT5 fixes.
* Interestingly, after the first attempt when it got to menu, the savedata it created caused a fatal access violation on the next boot until I removed savedata. After some investigation, it turned out adding a single lv2_obj::sleep to cellGameDataCheck fixed it even without time sleeping, but I've added more with timed sleep to it and more cellGame functions to better match real PS3 as those functions take a really long PPU time to process on real hw. (time in which the caller PPU is …
> cellGame: Add sleep when waiting for VSH

- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
Turns out parental_level is only checked once for being heigher than 11 and then the used register is recycled for a different purpose. I searched the entire dissassembly for another load from this member and could not find any.  This likely was a reverse-engineering mistake caused by looking at the following check, because before https://github.com/RPCS3/rpcs3/pull/6206 there was an array check there instead. I also implemeneted the following listParam checks.
Fixes #14245
> cellSaveData: Fix check 58, implement checks 77 and 76

- rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- rpcs3/Emu/RSX/GL/GLTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
Now supports writing scaled output to 3D and CUBE targets.
Fixes https://github.com/RPCS3/rpcs3/issues/14410
Fixes https://github.com/RPCS3/rpcs3/issues/14184
Fixes https://github.com/RPCS3/rpcs3/issues/13277
> rsx: Rewrite image merging routines

- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Cell/Modules/cellMouse.cpp
- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Cell/Modules/cellPad.h
- rpcs3/Emu/Cell/Modules/sys_io_.cpp
- rpcs3/Emu/Cell/lv2/sys_hid.cpp
- rpcs3/Emu/Cell/lv2/sys_hid.h
- rpcs3/Emu/Io/PadHandler.cpp
* Fix max_connect value in cellPadGetInfo, this value is the unmodified one from cellPadInit.
* cellPadGetInfo does not execute even a single syscall to read controller state, it relies on data updates from the _cfg_ev_hndlr input thread. This thread has a priority of 512 and most of the threads in The Simposns Game have priority of 256 including the main thread which calls the cellPad functions. This means, that in order for a connection to be registered the IO thread (_cfg_ev_hndlr) needs to able to run first which means it is dependant on the LV2 schedular to allow it. ~~I went along and implemented this functionality HLE style for LV2, I think this probably has more uses.~~ Written in LLE style with event queue in the end.
This fixes input in The Simpsons Game which expects controller …
> LV2/cellPad: Implement priority-based connection updates

- rpcs3/Emu/Cell/PPUModule.cpp
This originally came from that I knew for a while that R1 of main thread is not accurate to realh unlike in other threads, I did not fix it originally when discovered because I was not sure why R1 changes sometimes.
Today it hitted me that it may because the argv and envp are passed on the stack and their size may differ when using different arguments.
So I tested it on realhw, fixing it by moving `argv` and `envp` to stack instead of dynamic memory. Saving a whopping 128KB of RAM as a side effect ;)
But this was not playing nice with `envp`, after some reversing it turned out we were emulating `envp` wrong.
Originally, the `argv` and `envp` pointer arrays are 64-bit arrays because CELL is natively a 64-bit processor, but games use 32-bit pointers exclusively. So the workaround embedded …
> PPU Loader: Fix main()'s envp, move process arguments to stack

- rpcs3/Emu/Cell/SPURecompiler.cpp
vcvvtps2udq doesn't turn negative numbers into 0, fix by using signed integer max with 0 instead of vrangeps
fixes: https://github.com/RPCS3/rpcs3/issues/14462
> SPU LLVM: Fix for AVX-512 CFLTU path

- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/system_config.h
Use RDTSC to inline timer reads in SPU code.
May not have a large impact on most titles, but might speedup RDR since it has a sequence of code that looks something like this
```
for (int i = 0; i < 2400; i++)
{
int tmp = read_decrementer();
}
```
> SPU LLVM: Inline timer reads for WrDec and RdDec

- rpcs3/Emu/Cell/Modules/cellRec.cpp
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GSFrameBase.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/rpcs3qt/camera_settings_dialog.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
- rpcs3/util/image_sink.h
- rpcs3/util/media_utils.cpp
- rpcs3/util/media_utils.h
- rpcs3/util/video_provider.cpp
- rpcs3/util/video_provider.h
Turns out the pitch was accidentally used as width, leading to an out of bounds read/write. I kept the pitch in the struct for completeness' sake. It may be needed later, if only for error checks.
This fixes echochrome, which seems to be using recordings for some gameplay reason.
I didn't really bother trying to figure out how the gameplay works though.
Fixes #14466
Proof of the recording saved to dev_hdd1 and then exported to dev_hdd0
> cellRec: fix width of encoder frames

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
* Try to postpone address notification to when PPU is asleep or join notifications on the same address. This also optimizes a mutex - won't notify after lock is aqcuired (prolonging the critical section duration), only notifies on unlock
* Use usermode waiting for supported CPUs on detection GETLLAR busy-waiting loop in order to reduce power consumtion and improve performance
Please compare:
1. Framerate.
2. SPU usage.
3. PPU usage.
Note: Make sure that you are using the default setting for "Maximum Number Of SPURS Threads" and "Preferred SPU Threads".
> CELL: Selective and postponed address notifications

- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Memory/vm.h
- rpcs3/util/endian.hpp
> utils/endian.hpp: Use std::byteswap

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
cellAudioSetNotifyEventQueue waits for VSH threads to respond for port creation and connection to the event queue key provided. I believe this delay is what caused the need for the hack in sys_ppu_thread_start. I added the delay to cellAudioSetNotifyEventQueue for any key and added a long loop (but not infinite as before) waiting for _mxr000 to be created.
Edit: the delay is actually due to cellAudioPortOpen.
> cellAudio: Move and partially fix _mxr000 hack

- .ci/build-mac.sh
- 3rdparty/MoltenVK/CMakeLists.txt
Bumps MoltenVK to 1.2.5 matching Vulkan SDK 1.3.261
[Changelog](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.5): 
- Add support for extensions:
- VK_KHR_incremental_present
- VK_KHR_shader_non_semantic_info
- VK_EXT_4444_formats
- VK_EXT_calibrated_timestamps
- VK_EXT_pipeline_creation_feedback
- VK_EXT_shader_demote_to_helper_invocation
- VK_EXT_shader_subgroup_ballot
- VK_EXT_shader_subgroup_vote
- Add support for VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN.
- Support building MoltenVK for visionOS.
- Ensure non-dispatch compute commands don't interfere with compute encoding state used by dispatch commands.
- Support maximizing the concurrent executing compilation tasks via - MVKConfiguration::shouldMaximizeConcurrentCompilation
- Support VK_PRESENT_MODE_IMMEDIATE_KHR if …
> 3rdParty: Bump MoltenVK to 1.2.5 - Vulkan SDK 1.3.261

- Utilities/lockless.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/util/asm.hpp
- rpcs3/util/bless.hpp
- rpcs3/util/shared_ptr.hpp
This is a workaround for a Clang 16.0.5 crash which I reported [here](https://github.com/llvm/llvm-project/issues/64450).
> workaround for Clang crash

- rpcs3/Emu/Audio/XAudio2/XAudio2Backend.cpp
- rpcs3/Emu/Audio/XAudio2/XAudio2Backend.h
mingw-w64 has recently added IXAudio2Extension, so I enabled again.
> xaudio2: enable IXAudio2Extension for mingw-w64

- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUDisAsm.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
Make call stack smooth - no distinguishes between leaf function vs non-leaf function, start function or the the end of the function.
The most simple callstack as possible from user POV like x86 by analysing instructions, this has been partially implemented on SPU side already. (TODO there)
> Debugger/PPU: Superior Callstack Detection

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_memory.cpp
- rpcs3/Emu/Memory/vm.cpp
For a while I knew memory area addresses are inaccurate.
From what has been tested: if .ppu_private segment exists, it allocates its own 256MB block of 64k pages. If .rsx_image segment it allocates its own 256MB block of 1M pages. This seems to make sense because access rights (PPU/SPU/RSX flags) are block wide and not allocation specific.
At first, user64k is placed at `0x10000000` if no such special allocfation is made and user1m on `0x30000000`. Adding ppu private and rsx image segment to the ELF causes this addresses to become `0x30000000` and `0x50000000` respectively.
In #4522, the game tries to access a region of memory by mistake that would already be allocated on PS3 but not RPCS3 hence it crashes.
By fixing those addresses the game can be played and not crash anymore.
Fixes …
> LV2/Loader: Fix kernel regions addresses

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/Emu/system_progress.hpp
- rpcs3/rpcs3qt/gs_frame.cpp
If more than one PPU thread was loading PPU PRX/OVL, there could have been a race that would make the "Compiling PPU Modules" message never disappear because one thread was storing the string the other thread stored. (g_progr never gets null again)
> Progress Dialog: Fix race on PPU compilation status

- rpcs3/Emu/system_progress.cpp
* This is similar to how SPU GETLLAR works by loading all the values again and comparing to old state to check for whole load-atomicity of multiple values in a lock-free manner.
* Avoid PPU compilation pop-up on short linkage.
> Progress Dialog: Fix race that could lead to ever-inaccurate results

- rpcs3/Emu/RSX/Core/RSXVertexTypes.h
- rpcs3/Emu/RSX/RSXThread.cpp
In #9055, modulo op with frequency was used on vertex indices wiuth some values already surpoassing frequency divider value. We incorrectly assumed that this means that the upper bound of vertex data memory data is the frequency divider in this case, but actually we still need to check for each element max_index = max(index % frequency, max_index). This is also true for min_index.
This re-iteration over all indices can be quite expensive for this exceptionally rare case, so do it if an access violation is guarenteed due to unallocated memory access. I think this can be optimized in the future for single frequency across the entire vertex arrays but I won't do it in this pr.
Fixes #9055
> rsx: Fix index vertex array range with modulo calculation

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/system_progress.cpp
* Fixes #13815, although it was always a race. Fixes infinite linking for me with Star Ocean 5.
* Fixup a regression from #14505.
> Progress Dialog: Fix race when PPU compilation is super fast, RSX #14505 fixup

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/PPUAnalyser.cpp
* Slow down sceNpDrmIsAvailable, this function takes about 80 to 120ms on PS3.
* Slow down cellGameDataCheck, this function is incredibly slow. Takes around 80ms to 150ms with non-existant GAMEDATA. and 280ms to 300ms with DISC type even if /dev_bdvd is not mounted.
* Fix PPU Analyzer crashes with unaligned sections.
Fixes [SingStar](https://forums.rpcs3.net/thread-201485.html) PSN version loading.
Fixes [SingStar: Back to the 80s](https://forums.rpcs3.net/thread-186971.html) booting.
> cellGame/sceNpDrm/Loader: Few fixes

- rpcs3/Emu/RSX/RSXDisAsm.cpp
- rpcs3/Emu/RSX/rsx_decode.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/rpcs3qt/syntax_highlighter.cpp
Testcase https://github.com/elad335/myps3tests/tree/master/rsx_tests/write%20output%20mask
This testcase tests what happens on a write to ones to reserved of color mask register
It does this by iterating and ORis valid masks with a single reserved bit at a time, for completeness it also tests it with valid bit masks as well and examines buffer state.
Results: writes with reserved bits set are being ignored by RSX.
Fixes the colors in #13101.
Fixes #10530
> rsx: Discard color mask writes with reserved bits

- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Cell/Modules/sys_io_.cpp
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/savestate_utils.cpp
Previously, savestates 99% of the time caused a second, and much longer (!) PPU LLVM compilation in addition to the already existing cache because it is scanning the whole segment 0. This was done in order to support analysis of patches applied within the savestate file on instructions located outside of registered code regions in executable.
Now, why savestates do not simply allow patches to be reused and re-register them instead? because applying patches after boot (on savestates for example) and before boot (normal patches) is not the same operation and may have different and unexpected consequences on farther execution.
The idea here is simply to avoid this and compile segment 0 at all times, so there won't be a second compilation for savestates. In order to avoid compiling garbage …
> PPU Analyzer/Savestates: Usability improvements, Reduce LLVM compilation of garbage data

- rpcs3/Emu/RSX/RSXFIFO.cpp
This is a pattern I've seen in Persona 5, multiple CALLs on following statements.
The avoids a few redundant fetches when Atomic FIFO is used by not performing a complete fetch for the code section containing the CALL because RSX is just leaving it for another.
This is a minor optimization for Atomic FIFO.
> rsx: Optimize RET returning to following CALL

- rpcs3/Emu/Io/RB3MidiKeyboard.cpp
Some keyboards send a note on message with zero velocity instead of a note off. As the MIDI spec permits this, it needs to be handled here.
This ends up fixing several bugs caused from keyboards that do this and likely explains a lot of the issues some people report with this.
> RB3MidiKeyboard.cpp: fix some note off messages being processed incorrectly

- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Io/pad_config.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- Adds some more insights to cellPadPeriphGetData for future use
- Improves pad class data handling in pad settings dialog
> cellPad/input: prepare some peripheral data code

- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Cell/Modules/sys_io_.cpp
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/RB3MidiGuitar.h
- rpcs3/Emu/Io/RB3MidiKeyboard.h
- CELL_PAD_STATUS_CUSTOM_CONTROLLER was lost in cellPad_NotifyStateChange. Use the whole status instead.
I don't know what config_event_entry usually sets. If it only sets the connection, I can update the code to work with the old param.
- Fixes a potential out of bounds read in cellPad_NotifyStateChange (max_connect vs. get_max_connect())
- Fixes some u32 warning in Midi code
- Improves readability a bit by using some local references
Probably fixes #14493
> cellPad: fix custom controller status

- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
Was not actually working, thanks for @CookiePLMonster. Did not test.
> SPU LLVM Precompilation Fixup

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
The slider could be used when it shouldn't.
> Qt: fix pressure intensity deadzone enabled state

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/System.cpp
- rpcs3/Loader/ELF.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
* Add SPU Precompilation to Create PPU Cache
* Add partial support for pure SPU embedded code segment.
> Improve SPU LLVM Precompilation

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
Ideally we should track a list of referenced PRX/OVL paths in main executable and only if existing, precompile their SPU code.
In addition: Add ".PRX" and ".ELF" extensions to precompiled PPU LLVM files, seen "PRX" extension instead of "SPRX" in some games. (although they are really all encrypted, real sys_prx load does not accept files not starting with SCE prefix)
> Hotfix SPU Cache Spam For Game Collections

- .ci/build-linux.sh
- .cirrus.yml
- azure-pipelines.yml
This
- Disables Linux and Windows Cirrus builds
- Re-enables pushing for Linux and Windows on Azure
- Updates the Azure build
> Setup Azure Pipelines

- rpcs3/Emu/Io/pad_config.cpp
- rpcs3/Emu/Io/pad_config.h
- rpcs3/Emu/system_utils.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- rpcs3/rpcs3qt/pad_settings_dialog.ui
It became clear that the pad profiles aren't really what you would interpret as pad profiles in other emulators, but rather entire input config files.
This confused several users, so I decided to rename everything related to pad profiles to make this clear in the codebase.
- Renames all occurences of pad profiles to input configs or similar
- Renames active_profiles.yml file to active_input_configurations.yml
(sorry, but I think this is necessary. you can just copy the contents of the old one if necessary and rename "Active Profiles" to "Active Configurations")
- Renames the pad-profile cli arg to input-config (same reason)
> Qt: rename pad profiles to input config files

- rpcs3/Crypto/unedat.cpp
- rpcs3/Crypto/unself.cpp
- rpcs3/Crypto/utils.h
Encountered a crash when experimenting with stuff on SCE decrypter because SCE prefix is used not only for executables.
Also fixed endiness swapping - does not fit big endian architectures like ARM so it may improve compatibility there.
> Crypto: Fix endianess, avoid crashing on invalid values

- rpcs3/Emu/RSX/Common/texture_cache_utils.h
The variable existed a long time ago (~5yrs ago) due to use of a self-modifying (conditional erase) unordered_set loop. The design was changed years ago but we never removed the workaround.
Fixes https://github.com/RPCS3/rpcs3/issues/14510
> rsx/texture-cache: Remove archaic short-circuit during purge-xxxxx routines

- rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
Do not break blocks on interrupt-disabling branch-to-next. Maybe improves performance in TLoU and some other Sony's exclusives.
Example:
> SPU LLVM: Optimize spu_idisable

- Utilities/git-version-gen.cmd
- azure-pipelines.yml
Seems like Azure changed how it's SYSTEM_PULLREQUEST_SOURCEBRANCH works, and now is undefined if it's not a PR build.
> Actually fix build id issue

- Utilities/File.cpp
- Utilities/lockless.h
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUAnalyser.h
- rpcs3/Emu/Cell/SPUDisAsm.h
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/RSX/RSXDisAsm.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/rpcs3qt/debugger_list.cpp
- rpcs3/util/simd.hpp
* A fix for SPU fdunction discovery, do not count non-r0 link branches and branch-to-self or branch-to-next. A bit sad but this cuts found functions in TLoU from around 22xx to exacly 1800.
* Fix GOTO in the debugger in some conditions.
* Fix instriuction scrolling direction with the arrow keys in the debugger.
* Add CRC check to prevent use of invalid cache entries. (not perfect of-course)
* Add minimal discovery of tail-calls for precompilation.
* Revert a PPU Analyzer change, may address #14600.
> SPU LLVM: Precompilation Improvements and misc fixes

- rpcs3/Crypto/unself.cpp
- rpcs3/Crypto/unself.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/system_progress.cpp
spu_cache::initialize can now be called inside PPU precompilation which creates a deadlock. Avoid the use of progress dialog updates forr SPU Precompilation inside PPU precompilation for now (TODO).
> [HOTFIX] Do not wait for progress dialog cleanup for SPU Precompilation

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPUDisAsm.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.h
* Fix greedy PPU instruction search, there was a typo there and it was not considering BCLR and BCCTR.
* Add an optimization for PPU LLVM whener there are direct-unconditional branches following one another or ending up in an empty function (BLR).
* Add an optimization regarding PPU traps conditions, detect "always trap" forms and detect possible but theorectical simple "inequality" trap form. (either when both signed greater/lower or unsigned greater/lower are set).
* Improve SPU LLVM precompilation a bit.
* PPU LLVM: Patch unregistered BLRs.
May fix #14555
May fix #14600
May fix #14613
> SPU/PPU LLVM: Fixups and minor optimizations

- rpcs3/Emu/system_progress.cpp
- rpcs3/util/asm.hpp
It was showing the total time.
Also removes the 00m if the time is less than 60 seconds.
(Ignore the first commit, it's a rebase)
> Progress dialog: Fix remaining time

- rpcs3/Emu/Cell/Modules/cellMic.cpp
- rpcs3/Emu/Cell/Modules/cellMic.h
- Changes the default channel volume from 145 to 100, since apparently that's the max.
- Returns the proper channel volume the same way it's set in cellMicSetDeviceAttr.
We always wrote the wrong volume to the index argument, leaving the value argument untouched.
Maybe helps with #14639
> cellMic: Improve cellMicGetDeviceAttr for channel volume

- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/14652
> vk: Fix section merge calculations when using a temp resource

- .gitignore
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUDisAsm.cpp
- rpcs3/Emu/perf_monitor.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/welcome_dialog.cpp
- rpcs3/rpcs3qt/welcome_dialog.h
- rpcs3/rpcs3qt/welcome_dialog.ui
Add the ability to set dark theme in the welcome dialog, set dark by default if the system-wide theme is already dark.
Probably the most important PR in RPCS3 history.
> Welcome Dialog: Add ability to set Dark Theme

- rpcs3/Emu/Cell/SPURecompiler.cpp
Saves one subtract instruction from the common case and breaks dependency on input.
> SPU LLVM: Optimize remaining rotate instructions which take a twos compliment value as input

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/Emu/System.h
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/breakpoint_list.cpp
- rpcs3/rpcs3qt/breakpoint_list.h
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
- rpcs3/rpcs3qt/debugger_list.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
* Allow to add savable breakpoints using the patch system with patch type "bpex". Fixes #10059. Although this process need to be done manually.
* Allow to display thread from thread ID text on log.
* Add Got-To from function pointer on log. (PPU addresses starting with asterisk)
> Patches: Add savable breakpoints patch type

- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
Make use of file::read_at to allow concurrent fixed file reads.
> sys_fs: Optimize concurrent file reads

- rpcs3/Emu/Io/pad_config.cpp
- rpcs3/rpcs3qt/emu_settings.cpp
The "," (or comma) key wasn't working in the keyboard pad handler, since "," is also the separator for multi-assignments.
- Check if the config is solely "," and assign it properly
- Check if the config contains a sequence of multiple "," which most likely means that it was assigned in a multi-assignment.
The alternative would be user error or a Qt bug I guess.
> Input: Fix "," key in keyboard pad handler

- rpcs3/Emu/Cell/PPUModule.cpp
Kernel aligns segment memory to 256 bytes internally.
May fix some crash observed on discord.
> PPU Loader: Fix relocation offset verification

- 3rdparty/rtmidi/CMakeLists.txt
RTMidi links to libjack which makes the appimage unusable when jack is not installed.
> Disable RTMidi linking to jack

- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/Io/usio.h
Fixed a bug that switch-kind USIO buttons got released when game window lost focus.
Also implemented more USIO commands like ClearSram, so now it's possible to use this feature in game without having to manually edit usiobackup.bin and then manually restart the game.
> [Bugfix] USIO: Fixed switch-kind buttons got released when game window lost focus

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/MFC.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/rpcs3qt/debugger_frame.cpp
Fix memory leak in Thread.cpp due to not exiting threads.
Fixes #14764
> Utilities/Thread.cpp: Fix threads memory leak

- rpcs3/Emu/RSX/VK/vkutils/chip_class.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/rsx_utils.h
- Add chip detection for intel DG2 cards. They're more popular now, so we may need to start tuning for them in some places.
- Remove ANV workaround for a bug that has since been fixed in mesa.
- Add some comments in convert-linear-swz code to explain padding behavior and assumptions.
> rsx: Maintenance improvements

- .ci/build-mac.sh
- 3rdparty/MoltenVK/CMakeLists.txt
New [MoltenVK 1.2.6 release](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.6) 
New features or changes include:
- Add support for extensions:
- `VK_KHR_synchronization2`
- `VK_EXT_extended_dynamic_state` (requires Metal 3.1 for `VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE`)
- `VK_EXT_extended_dynamic_state2`
- Fix rare case where vertex attribute buffers are not bound to Metal when no other bindings change between pipelines.
- Ensure objects retained for life of `MTLCommandBuffer` during `vkCmdBlitImage()` & `vkQueuePresentKHR()`.
- Fix case where a `CAMetalDrawable` with invalid pixel format causes onscreen flickering.
- Fix deadlock when reporting debug message on `MVKInstance` destruction.
- Fix MSL code used in `vkCmdBlitImage()` on depth-stencil formats.
- Improve …
> Bump MoltenVK to 1.2.6 (Vulkan 1.3.268)

- bin/GuiConfigs/Darker Style by TheMitoSan.qss
Before
After
This isn't my custom stylesheet and may get taken over by a different pull request. But keynotes to look for. 
The box being filled in with white is ticked throughout the entire theme until it comes to the firmware tree. 
So I added QListWidget and QTreeWIdget names to the checkboxes section so as not to mess with any of the colors, borders, margins, padding, or anything else. This enables clear communication to the user what is ticked, unticked, enabled, disabled or anything else by simply keeping a uniform interface for the user to interact with and not just changing the rules when it comes to a specific group/location of the interface.
I notice the checkbox size appears a little big in the after vs before among many other modernizations I'd love to change. Yet this isn't …
> [UI/UX] Fix Firmware tree checkboxes for Darker Style by TheMitoSan file

- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- rpcs3/Emu/RSX/Program/VertexProgramDecompiler.cpp
- Fixes a bug when the program entry is at the end of an ubershader block. In this scenario, the entry is the dispatch block and the subroutines sit above it which could cause a crash if there is padding in the structure.
- More aggressive DCE. In case a loop is detected, we don't need to walk the loop again as it will always end the same way. Previously, we walked over the blocks and consumed the tail sections which could add hundreds of instructions of unreachable code at the end of ubershaders.
Closes https://github.com/RPCS3/rpcs3/issues/13443
> rsx: Vertex program analyser improvements

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Crypto/unself.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/NP/np_structs_extra.cpp
- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/Emu/RSX/Program/CgBinaryFragmentProgram.cpp
- rpcs3/Emu/RSX/Program/CgBinaryProgram.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/Emu/savestate_utils.hpp
- rpcs3/Loader/TAR.cpp
- rpcs3/Loader/TAR.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/util/fixed_typemap.hpp
- rpcs3/util/serialization.hpp
Savestates may weigh anywhere from few hundreds of MB to few GBs if not more. Until now, the entire file contents were kept in RAM. This applies to both reading and writing of savestates.
Implement "breathing" points where the file contents may or may move from RAM to disk when writing savestates, or simply discarding data when reading savestates. This depends on the size of contents accumulated, because frequent disk accesses have negative impacts on performance as well.
This prevents RAM shortages by reducing total memory consumption.
This pull request also affects RSX captures loading and saving in a similar manner.
> Savestates: Implement initial RAM ventilation system

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/main_window.cpp
- zips rsx captures to .gz before saving them
- unzips rsx captures if necessary
- Add GUI filters for file selection and drag&drop
> rsx: zip and unzip rsx captures

- rpcs3/Emu/RSX/Core/RSXVertexTypes.h
- rpcs3/Emu/RSX/RSXThread.cpp
This bug is technically a regression. We switched from a allocate-per-draw-call to reusing the vertex input data due to the large performance impact of allocating the struct each draw call (basically millions of times per second in some games). We need to make sure previous state does not affect validation results.
- Memcpy/memset is too slow at this level of frequency, so just reset the attributes you're using before using them.
- Also changes the validation routine to only check attributes we're actually using.
Fixes https://github.com/RPCS3/rpcs3/issues/14815
> rsx: Fix vertex input validation failure

- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- Adds a trophy count column to trophy manager game list which allows you to sort the games by trophy count
> Qt: add trophy count column to trophy manager game list

- Utilities/File.cpp
- rpcs3/Crypto/unzip.h
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/Emu/Cell/Modules/sys_io_.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/IdManager.cpp
- rpcs3/Emu/IdManager.h
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/Emu/savestate_utils.hpp
- rpcs3/Loader/TAR.cpp
- rpcs3/Loader/TAR.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/util/serialization.hpp
Along with #14784, this pull requests aims to reduce significantly the file size of savestates which can anywhere from few hundreds of MBs to few GBs or even more.
Initial measurements suggest more size reduction of more than 50 percent! But it is probably more in most cases, need user testing!
TODO:
Additional bugfixes:
> [TESTERS NEEDED!] Savestates: Compressed files

- Utilities/StrFmt.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/util/serialization_ext.cpp
This PR fixes some Clang warnings.
```
[17/410] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/savestate_utils.cpp.obj
C:/src/rpcs3/rpcs3/Emu/savestate_utils.cpp:123:9: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
123 |         return std::move(ver_data);
|                ^
C:/src/rpcs3/rpcs3/Emu/savestate_utils.cpp:123:9: note: remove std::move call here
123 |         return std::move(ver_data);
|                ^~~~~~~~~~        ~
C:/src/rpcs3/rpcs3/Emu/savestate_utils.cpp:186:10: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
186 |                 return std::move(path_compressed);
|                        ^
C:/src/rpcs3/rpcs3/Emu/savestate_utils.cpp:186:10: note: remove …
```
> fix Clang warnings

- rpcs3/Emu/GameInfo.h
- rpcs3/rpcs3qt/game_list_base.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_grid.cpp
- rpcs3/rpcs3qt/game_list_table.cpp
- rpcs3/rpcs3qt/movie_item_base.cpp
- rpcs3/rpcs3qt/movie_item_base.h
- rpcs3/rpcs3qt/qt_camera_video_sink.cpp
- rpcs3/rpcs3qt/qt_camera_video_sink.h
- Plays the ICON1.PAM (found next to ICON0.PNG) in the gamelist/grid when the user hovers over the icon.
- The existing hover gif will still be prioritized
- Replace raw buffer in camera sink with std::vector
- Only load videos when they are needed
- Release resources once the video is stopped
Known issues:
- some ICON1.PAM don't seem to work
- there's one second of delay before the video plays
> Qt: Play ICON1.PAM on hover in gamelist if available

- rpcs3/Emu/Audio/audio_resampler.cpp
- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/Modules/cellRec.cpp
- rpcs3/util/media_utils.cpp
- rpcs3/util/video_provider.cpp
- rpcs3/util/video_provider.h
- rpcs3/util/video_sink.h
Bugfix:
- Fix time stretching facepalm regression
Recording:
- Use separate locks for audio and video. This should reduce possible audio/video stutter during recording.
- Fix audio mutex usage in cellRec. This was a typo and should've caused audio issues in recordings of games like Just Cause 2.
- Removes can_consume_sample, since we don't do any processing between can_consume_sample and present_samples.
- Use get_system_time in video_provider for consistency.
- Move video_provider pts reset to set_video_sink, which basically acts like a start/stop function.
- Make video_provider start time atomic to ensure only one track can initialize it. (We need to initialize it when we get the first input, not any earlier)
- Remove frame and sample counts. These were only needed for the start time …
> Recording: optimize access to video recorder

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_dbg.cpp
Implement properly sys_dbg_write_process_memory which was used in PS3 to modify executable code at runtime, this only works for PPU interpreter atm.
Should fix a crash in portal 2 multiplayer but I did not test it :)
> PPU/sys_dbg: Implement self-modifying code

- rpcs3/Emu/Cell/Modules/cellRec.cpp
- rpcs3/rpcs3qt/screenshot_manager_dialog.cpp
- rpcs3/rpcs3qt/screenshot_preview.cpp
- cellRec: Remove outdated frame size check
We are rescaling the images to the desired output format in the encoder.
The frames themselves are not a fixed container anymore.
- Qt: only allow double leftclick in screenshot manager.
You could click any mouse button before, which was weird.
fixes #14871
> cellRec: Remove outdated frame size check

- rpcs3/util/serialization_ext.cpp
Should test the current state rather then the future state, otherwise the thread may wait for its own byte to process even though it did not commit anything.
> Savestates: Fix compressed serialization handler deadlock

- rpcs3/Emu/RSX/rsx_methods.cpp
Some games use 308a::color to implement custom sync primitives (ETQW). When the color data is written, the engine assumes all occlusion reports are ready which can cause severe flickering if we don't flush the pipeline.
Fixes https://github.com/RPCS3/rpcs3/issues/12425
> rsx: Let 308a::color have a synchronization side-effect in strict mode

- rpcs3/util/asm.hpp
I'd like to try again to fix usage of `_mm_prefetch`.
`prefetch_exec` has the following comment.
```
// Try to prefetch to Level 2 cache since it's not split to data/code on most processors
template <typename T>
constexpr void prefetch_exec(T func)
```
I changed the argument from `2` to `_MM_HINT_T1`.
```
// MSVC
#define _MM_HINT_T1     2
// GCC/Clang
_MM_HINT_T1 = 2,
```
As you can see there was no change. T1 is also [correct](https://www.felixcloutier.com/x86/prefetchh):
> T1 (temporal data with respect to first level cache misses)—prefetch data into level 2 cache and higher.
`prefetch_read` has the following comment
```
// Try to prefetch to Level 1 cache
constexpr void prefetch_read(const void* ptr)
```
I changed `3` to `_MM_HINT_T0`.
```
// MSVC
#define _MM_HINT_T0     1
// GCC/Clang …
```
> asm.hpp: fix usage of _mm_prefetch

- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
* "Add Games" would now prompt the post-install assistant, which was previously only done when installing game packages.
* I added the option to precompile CPU caches right after installation for your convenience. Preventing the wait on boot before first boot when you actually want to play the game!
> Qt: Post Game-Installation Assistant

- .ci/build-mac.sh
- .ci/deploy-mac.sh
Safer than create-dmg on Ventura
https://github.com/actions/runner-images/issues/7522#issuecomment-1556766641
> macOS CI: use 7-Zip for artifacts

- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm.h
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/util/asm.hpp
Attempts to fix #14882, introduce a safe string reader.
> sceNp/vm: Fix strings read, implement safe string reader

- rpcs3/Emu/NP/rpcn_client.cpp
Should fix most issues with getting already logged in error when trying to reconnect.
> Force sending a FIN packet on rpcn disconnect

- rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- input/evdev: handle flatness deadzone value:
This may fix issues with sticky axis on evdev, especially if you are not using any of the usual sticks or triggers whose deadzones can be configured.
The flatness of an axis seems to be a suggested deadzone. I could not find any mention of it being filtered pre-event, so we most likely are supposed to do this on our own.
I took the opportunity to refactor some partially redundant axis scaling functions and re-use the same function more often.
- rsxaudio: fix ensure order and remove some unnecessary scoping.
fixes #14886
> input/evdev: handle flatness deadzone value

- rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
- rpcs3/Emu/Cell/lv2/sys_net/network_context.h
Fixes crashes when restarting a game that had active sockets.
> Fix initialization order for network_thread

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp
- rpcs3/Emu/Cell/lv2/sys_rsxaudio.h
- rpcs3/Emu/IPC_socket.cpp
- rpcs3/Emu/IPC_socket.h
- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/ipc_settings_dialog.cpp
Fixes some dependency issues revealed by #14896
> Fix fxo dependencies

- BUILDING.md
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.h
- rpcs3/Emu/Io/usb_device.h
Originally `sys_usbd_get_descriptor()` didn't take the argument `desc_size` into account when writing the descriptor into the vm memory and it didn't check if the given `descriptor` pointer is null, so there were chances that the syscall could run into access violation.
I also added some more arguments to `sys_usbd_attach()`'s logging for better debugging (especially the argument `device_handle` is notable when debugging sys_usbd).
> sys_usbd: Prevent sys_usbd_get_descriptor() from buffer overflow & Add some more arguments to sys_usbd_attach()'s logging for better debugging

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/usb_device.cpp
Today I carried out a hardware test for this syscall in response to @elad335's last comment in #14900 yesterday.
I tested the following conditions on my real hardware, and fixed up the error handling of this syscall accordingly:
1. descriptor=NULL, desc_size=0x32 -> CELL_EINVAL
2. descriptor=*ptr, desc_size=0 -> CELL_ENOMEM
3. descriptor=NULL, desc_size=0 -> CELL_EINVAL
> sys_usbd: Fix up sys_usbd_get_descriptor() error handling according to hardware test

- rpcs3/Emu/RSX/Common/surface_utils.h
- rpcs3/Emu/RSX/Common/texture_cache.h
There is a data loss path if WCB is enabled when CELL writes to RSX mem, or RSX commands do a write that causes a flush from GPU to CPU then is overwritten. If we don't detect it in the surface "test" method (very likely due to low sample count) we just lock the memory again and the writes are lost forever. This is extremely bad in some cases because we can lose shaders and other important RSX data causing all kinds of problems and crashes.
Closes https://github.com/RPCS3/rpcs3/issues/14901
Relates to https://github.com/RPCS3/rpcs3/issues/9133
> rsx: Avoid data loss in blit engine when WCB/WDB + RCB/RDB is active

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Crypto/unedat.cpp
- rpcs3/Crypto/utils.cpp
- rpcs3/Crypto/utils.h
- rpcs3/Emu/Cell/Modules/cellRec.cpp
- rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.h
- rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
- rpcs3/Emu/Memory/vm.h
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/np_handler.h
- rpcs3/Emu/NP/signaling_handler.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/VFS.cpp
- rpcs3/util/auto_typemap.hpp
- rpcs3/util/fixed_typemap.hpp
- rpcs3/util/serialization.hpp
- rpcs3/util/types.hpp
* Set up a trap for uninitialized access to FXO objects, see #14897.
* Fix independent threads with FXO management, launch threads only after all default-constructibles have been created.
* Resolve a dependency chain between PSN handler and network thread.
* Fix TCP monitor thread abort in some cases, the previous bug could have led to deadlocks when trying to quit games.
* Fix UB with g_fxo->init regarding multi-threaded access in some cases.
> Util/fixed_typemap.hpp: Fixes

- rpcs3/main.cpp
- Does not allow running rpcs3 from any path containing "Rar$"
Usually the temporary location would suffice, but apparently there are some edge cases with WinRar and OneDrive
Fixes #14912
> Do not allow running RPCS3 from Rar directories

- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- Allows the selection of all the available native system styles.
- In windows, the default style is windowsvista and is basically the same as "None". It is always bright.
The other styles work with both bright and dark mode (I don't know about other OS).
- Fixes #14762
> Qt/Stylesheets: allow to use native styles

- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.h
Let the user choose whether he wants to duplicate global settings or default settings when creating game config.
> Game Settings: Add an option to create game config using default settings

- rpcs3/Emu/Cell/lv2/sys_fs.h
Fixes VSH crash due to uninitialized mutex use due to default_sys_fs_container not being default-constructible (so it was not initialized via g_fxo->init())due to it having a deleted constructor, I removed the explicit constructor erasure instead of declaring a default constructor due to shared_mutex already being non-copyable. Bug was found on discord using this log file:
[VSH.log.gz](https://github.com/RPCS3/rpcs3/files/13729868/VSH.log.gz)
> VSH fix: Fix sys_fs_fcntl default_sys_fs_container use

- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
- Use the initial style on boot as default style applied before changing stylesheets (kinda like a foundation).
- It's a bit dumb because accoring to Qt it should be the first style in the list...
- This may fix a regression with stylesheets on linux (unless it's the same style after all)
> Qt: use initial style as default style

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/patch_creator_dialog.cpp
- rpcs3/rpcs3qt/patch_creator_dialog.h
- rpcs3/rpcs3qt/qt_utils.cpp
- rpcs3/rpcs3qt/qt_utils.h
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/syntax_highlighter.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- rpcs3/rpcs3qt/welcome_dialog.cpp
Fixes several color issues when using native styles:
- Sets icon background colors to transparent
- Uses the native styles' label foreground color for any regular texts
- Uses the native styles' label foreground color for toolbar icons
- Uses the native styles' label foreground color for the gamepad image in the pad settings
- Uses green/red color some patch creator labels
- Uses blue/brightblue link color depending on dark mode (ironically link colors are broken in Qt 6.6.0)
- Uses log colors inspired by existing stylesheets depending on dark mode
- Repaints the UI when the OS switches between light and dark mode
Fusion:
> Qt: use default colors for native styles

- Utilities/Thread.h
Execution header that ships with GCC has issues compiling and we aren't currently using std::execution. LLVM ships its own pstl headers.
> Do not include pstl headers (execution namespace)

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.cpp
lv2_socket_native should get upnp unbound during close() call during emulation.
nt_p2p_port are only destroyed on network_thread termination.
In both those cases if there are any straggling upnp binds left upnp_handler will unbind them in its destructor on emulation termination.
> Remove destructor dependencies on nph

- rpcs3/util/auto_typemap.hpp
- rpcs3/util/fixed_typemap.hpp
Fixes crashes when fxo destructors call other fxo.
> Typemap: Set init to false after each individual destructor

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/RSX/rsx_utils.h
- De-spaghettify nv3089::image_in and refactor into readable units.
- Add support for RSX tiled addressing in the CPU blit path.
Closes https://github.com/RPCS3/rpcs3/issues/6688
> rsx: CPU blit refactor and support RSX tiled addressing

- rpcs3/Emu/RSX/rsx_methods.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/14940
> [HOTFIX] rsx: Fix typo

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp
- rpcs3/Emu/Cell/lv2/sys_rsxaudio.h
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/IdManager.cpp
- rpcs3/Emu/IdManager.h
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/rpcs3_version.h
- rpcs3/util/fixed_typemap.hpp
- rpcs3/util/types.hpp
* Fix audio_out_configuration initialization. This was a recent regression caused by #14897.
* Fix SPU access violations when loading savestates with SPU LLVM.
* Implement SPU reservation saving, remove its hack.
* Add data tags in savestates to ensure state integrity on savestate load.
* Improve compression rate of savestate by saving PS3 memory blocks together.
* Invalidate all old savestates.
* Add  saving date and time and RPCS3 build title to the file data itself.
> Fix and improve savestates

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/System.cpp
Some games are installed with other dir names than title id.
- Use the actual directory name instead of clamping it to 9 characters.
- Pass the actual directory name in cellGameBootCheck.
fixes #14954
> sys: Fix hdd game dir name

- rpcs3/rpcs3.metainfo.xml
I validated the file with `appstreamcli` and only warnings remain, one of them a pedantic one:
The deprecated `developer_name` is still required by the old version of AppStream that Flathub uses and the `<releases>` section is added downstream: https://github.com/flathub/net.rpcs3.RPCS3/blob/a2cf3ae4e309ffb5943339bdb21e2f0f9cb77dbd/net.rpcs3.RPCS3.yaml#L86
```
$ flatpak run org.freedesktop.appstream.cli validate --pedantic --explain rpcs3/rpcs3.metainfo.xml
P: net.rpcs3.RPCS3:5: cid-contains-uppercase-letter net.rpcs3.RPCS3
The component ID should only contain lowercase characters.
W: net.rpcs3.RPCS3:9: developer-name-tag-deprecated
The toplevel `developer_name` element is deprecated. Please use the `name` element in a
`developer` block instead.
P: net.rpcs3.RPCS3:~: releases-info-missing …
```
> Update AppStream Metainfo for Linux software centers

- rpcs3/Emu/RSX/Common/tiled_dma_copy.hpp
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXMemoryTiling.glsl
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
- Out of bounds write fix to fix some crashing scenarios.
- Allow CPU side to pick the correct image texel size depending on the bpp. This is still not as complete as the GPU code which can do all sizes from 1 byte to 16, but it's something at least.
> rsx: Misc tiling improvements

- Utilities/BitField.h
- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Cell/Modules/cellMouse.cpp
- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Cell/Modules/cellPad.h
- rpcs3/Emu/Cell/Modules/sys_io_.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.h
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/Loader/TAR.cpp
- rpcs3/main.cpp
- rpcs3/util/fixed_typemap.hpp
- rpcs3/util/serialization.hpp
- rpcs3/util/serialization_ext.cpp
- rpcs3/util/serialization_ext.hpp
* Fix an optimization miss in SPU LLVM when using GPR barriers.
* Fix TAR serialization for individual files if they need to be processed in more than 1 iteration due to their size.
* Don't block the compression-requesting thread until all bytes are processed and written to file, instead free the thread the moment it can continue execution in order to improve saving performance.
* Fix an infinite loop in compression thread.
* Fix lv2_timer_thread abort
* Fix pad_state_notify_state_change
* Make bf_t<T> warning-friendly by using small integers when possible.
* Add cellPad event when registering LDD pads.
* Do not rely solely on value-inequality in sys_spu, this can cause a theoretical bug when overflows.
> Fixes for 0.0.30

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Common/texture_cache_utils.h
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
Allows tiled targets to work properly with linear DMA sections. This keeps performance up while allowing the detiler to work properly.
Closes https://github.com/RPCS3/rpcs3/issues/14984
> rsx: Fix RSX tiling when using optimized DMA views

- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/games_config.cpp
- Fixes a regression from the previous game path mounting fixes (we pass the emu dir now instead of title id)
- Mount ps1 and psp remasters with their full dir name instead of the title id
- Mount hdd games located in /games with their full dir name instead of the title_id
probably fixes #14994
> Fix games.yml hdd paths

- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/main.cpp
* Fix PPU progress dialog hint - it actually did not work for a while now, because the integral division resulted in 0.
* Fixup fatal error dialog message.
* Fix a bug in Emulator::GetNdvdDir and make it perform less filesystem operations. May address #14679
> More fixes

- rpcs3/Emu/Cell/Modules/cellMic.cpp
- rpcs3/Emu/Cell/Modules/cellSearch.cpp
- rpcs3/Input/keyboard_pad_handler.cpp
- Fixes mounting of files in cellSearch (file vs. dir)
- Mount with `/dev_hdd0/.tmp` instead of only `/.tmp`. It omits the `/` if the path starts with `/.tmp`.
- The combination of both allows WipEout HD to play songs with too long titles.
fixes #14972
> Improve cellSearch paths handling and mounting

- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
In very rare cases, we can see a developer choosing a backbuffer of the wrong format compared to what they declared when setting up the display. In such scenarios, the output format of the compositing render does not actually match the display format. We need to correct this before present or the colors will not match what is expected.
Fixes https://github.com/RPCS3/rpcs3/issues/11324
> rsx: Display output format correction

- rpcs3/Emu/RSX/VK/VKTexture.cpp
This only really applies to buffer loads from tiled regions.
Fixes https://github.com/RPCS3/rpcs3/issues/14981
> vk: Force GPU texture processing if the input is already GPU-resident

- rpcs3/Emu/NP/np_cache.cpp
- rpcs3/Emu/NP/np_cache.h
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/rpcn_client.cpp
- Fixes Aquapazza sending invalid SceNpMatching2CreateJoinRoomRequest(random pointer to the stack and hardcoded 100 for allowedUser/allowedUserNum)
> Fix games passing invalid npids

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_ss.cpp
sys_fs_unlink() used to fail to delete files in dev_usbXXX because it used `mp->root`, which is always "dev_usb" for all dev_usbXXX devices, as argument `dev_root` passed to `vfs::host::unlink()` for further processing.
This PR fixed the bug mentioned above.
> [Bugfix] sys_fs: Fixed sys_fs_unlink()'s failing to delete files in dev_usbXXX & Misc syscall implementation fixups

- rpcs3/Emu/Cell/Modules/cellSysCache.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/Memory/vm_ptr.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/VFS.cpp
- rpcs3/Emu/VFS.h
> Ensure HDD1 is never damaged or corrupted due to unexpected RPCS3/game close

- rpcs3/Emu/Cell/Modules/cellAdec.cpp
- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- rpcs3/util/media_utils.cpp
- use avio_closep instead of avio_close in order to properly reset the pointer
- don't use avcodec_close. use avcodec_free_context as mentioned in the avcodec_close description
- don't use avformat_free_context if we already used avformat_close_input which sets the pointer to null anyway
fixes #15039
> media_utils: fix segfault when stopping a recording

- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/mm_joystick_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- Connect the mmjoy device ingame if it was not connected before (you had to go to the settings and save if you did this before)
- Only try to reconnect the device once per second if it was disconnected due to performance issues
- Early out if joyGetDevCaps returns an error. This reduces the time spent checking a device connection.
> input: implement dynamic mmjoy device reconnection

- Utilities/File.cpp
- rpcs3/rpcs3qt/update_manager.cpp
- Use fs::get_temp_dir during updates, GetTempPathW was falsely using size in bytes instead of string length.
- Remove duplicate to_utf8 function in fs::file
- Move buf in fs::get_config_dir from stack to heap to silence some VS warning
> Windows: file path fixes

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/util/asm.hpp
Fixes https://github.com/RPCS3/rpcs3/issues/14949.
Clang optimizes vm::_ref<atomic_t<u8>>(test / 4096 == begin / 4096 ? begin : test) += 0; to a simple memory barrier as it considers it's the only possible side effect:
```x86asm
lock orl $0x0,-0x40(%rsp)
```
I added a function with inline assembly to make sure it's not optimized away with a fallback to a volatile value that shouldn't be optimized away either.
> Replaces page fault triggers with assembly

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
When reusing surfaces, attach the new properties correctly.
Fixes some mismatches when debugging but no games have been observed so far with visual changes.
> rsx: Properly propagate surface properties on surface reuse.

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/system_utils.cpp
- rpcs3/Emu/system_utils.hpp
- rpcs3/rpcs3qt/shortcut_utils.cpp
- rpcs3/rpcs3qt/update_manager.cpp
Adds support for using a portable data directory. Similar to other emulators, you can put a directory named "portable" next to the executable, and it will be auto-detected and used for all emulator data.
As part of this, I moved the utility functions for getting the executable path over to `Utilities/File.cpp` and cleaned them up a bit, so that they can be used to locate the portable directory. Now there are two main functions for this purpose:
* `get_executable_path()`: Gets the path of the executable itself. This is the actual binary file on Windows/Linux, and the .app bundle on macOS.
* `get_executable_dir()`: Gets the path of the directory that the executable is in.
Tested on a Mac and confirmed that when a portable directory is next to the .app bundle, it is used instead of the …
> Utilities: Add support for portable user directory.

- rpcs3/Emu/Cell/Modules/cellSysCache.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_raw.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/Loader/TAR.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/util/types.hpp
* Fixup HDD1 corruption detection.
* Fixup a minor bug in PPU module compilation overlay hint.
* Optimize PS3 filesystem reads when possible by using complete reads.
* Early protection againt space shortage when installing PUP (avoid incomplete installation).
* Fix P2P sockets saving for save-states.
> Savestate and filesystem fixes

- Utilities/File.cpp
- rpcs3/Emu/Cell/Modules/cellImeJp.cpp
- rpcs3/Emu/Cell/Modules/cellImeJp.h
- rpcs3/main.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- Fixes some new GetModuleFileNameW warnings
- Fixes deadlock in cellImeJpConvertCancel
- Adds focus area wrap around in cellImeJp and fixes an issue where its length would always return at least 1
- Adds a differentiation between cursor and focus area, although this doesn't seem to work properly (neither really better nor worse)
- Adds a fake conversion candidate so that the game doesn't break if you open the candidate list
> cellImeJp: fix softlock and improve some of the logic

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentPrologue.glsl
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXProgrammableBlendPrologue.glsl
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXROPEpilogue.glsl
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXROPPrologue.glsl
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/rsx_utils.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
1. Do not write to host channels that are disabled. This largely applies to RGBX formats where on PS3 the alpha channel is disabled. On PC we were writing to this non-existent channel which is wrong.
2. Refactor shader ROP stuff in preparation for programmable blending down the line. The full implementation will come in a later PR.
3. Correctly perform float->fixed conversion for 8-bit formats. During the vanillaware investigation it became clear that PS3 wraps negatives before clamping.
> rsx: Improved 24-bit format handling and shader refactoring

- rpcs3/rpcs3qt/emu_settings.cpp
- Trim whitespace in text fields used for emu settings
- Update miniupnp to 2.3.4
Fixes #15082
> Trim Network settings line edit input (+ update miniupnp)

- Utilities/File.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/vfs_config.cpp
- rpcs3/rpcs3qt/vfs_dialog_usb_input.cpp
- Check if strings are empty before accessing their behinds
- Add libusb log callback
fixes #15093
> VFS; try to fix some segfaults (+ add libusb log callback)

- rpcs3/rpcs3qt/main_window.cpp
Avoid showing this message when Add Games dialog is cancelled:
> Don't search games when the dialog is cancelled

- rpcs3/Emu/NP/rpcn_client.cpp
- rpcs3/Emu/NP/rpcn_client.h
To help FlexBy regain some sanity :D.
> Terminate RPCN connection cleanly

- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/np_handler.h
- rpcs3/Emu/NP/rpcn_client.cpp
- rpcs3/rpcs3qt/rpcn_settings_dialog.cpp
- rpcs3/rpcs3qt/rpcn_settings_dialog.h
Implement all APIs related to player history and shows a list of it in rpcn=>friends where you can add friends quickly that way. Of note is that this list is purely local to your instance of RPCS3 and not stored on RPCN.
> Add player history

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/PPUModule.cpp
Hopefully fixes https://github.com/RPCS3/rpcs3/issues/15149.
The module was missing from hle list and the file wasn't even in the CMakeLists.txt
> Add sceNpPlus to registered modules

- buildfiles/cmake/ConfigureCompiler.cmake
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/RSX/GL/GLTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- Do not add x64 switches to arm64 output. This happens on clang which exports both compilerx86 and compilerarm somehow.
- Do not use x86-specific intrinsics without preprocessor guards. This fixes SPU module compilation allowing SPU llvm to be used in some games.
Most games still hang after loading modules when using llvm. I haven't really checked why and tbh it's not a priority right now.
> Minor arm64 improvements

- rpcs3/Emu/RSX/VK/VKHelpers.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- Explicitly add support for dozen and lavapipe by identifying them.
- Show a warning box if the user selected the dozen driver. With exception of developers, this driver should really never be used outside of environments like WSL.
- Make more required features "optional". This allows dozen to complete swapchain creation successfully. The driver will obviously crash later but the user has been warned approrpiately by then.
Fixes https://github.com/RPCS3/rpcs3/issues/15131
> vk: Driver compatibility improvements

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
Thanks to extensive testing and debugging the game from @RipleyTom, we discovered that on real PS3 (it seems), when a thread with a higher priority than the caller is signaled and that there is an available space on the running queue for the other hardware thread to start, It prioritizes 
the signaled thread by switching the caller's hardware thread instantly to the signaled thread code while notifying the other hardware thread to execute the caller's code. Resulting in an at first a mysterious delay in the caller's code after such thread is signaled.
This fixes Sega Rally Online freeze on load. In this game there is a race condition that is not sequencing a freeze on ps3 due to this delay.
Fixes #14663
Fixes #14375
> PPU/LV2: Implement HW threads switching delay when signaling higher priority threads

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_components.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_main_menu.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_main_menu.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_message_box.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_message_box.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_page.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_page.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_settings.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_settings.h
- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
- rpcs3/Emu/RSX/Overlays/overlay_controls.h
- rpcs3/Emu/RSX/Overlays/overlay_cursor.cpp
- rpcs3/Emu/RSX/Overlays/overlay_cursor.h
- rpcs3/Emu/RSX/Overlays/overlay_message.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message.h
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/Emu/RSX/Overlays/overlay_progress_bar.cpp
- rpcs3/Emu/RSX/Overlays/overlay_progress_bar.hpp
- rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp
- Fixes positioning an overlay to the top and/or left of the screen. This would previously overflow and disappear
- This fixes the mouse/move pointer disappearing partially or completely when it's near to the left or upper border
This was previously invisible at that location:
> overlays: use signed short for position to allow negative positions

- rpcs3/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/MouseHandler.h
- rpcs3/Emu/system_config_types.cpp
- rpcs3/Emu/system_config_types.h
- rpcs3/Input/basic_mouse_handler.cpp
- rpcs3/Input/raw_mouse_config.h
- rpcs3/Input/raw_mouse_handler.cpp
- rpcs3/Input/raw_mouse_handler.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/main_application.cpp
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- Adds a raw mouse handler to the mouse handler selection
- The raw mouse handler can be used as replacement for the basic mouse or as ps move mouse
- As with the existing ps move mouse, the raw ps move mouse only works if the regular mouse handler is set to null
- Currently the raw mouse handler just takes all mice it can find until it reaches the max allowed number (set by the game)
- Mouse acceleration for relative movement is supported, yet not configurable at the moment
TODO:
implements #15158
> input: implement raw mouse handler

- rpcs3/Emu/Io/RB3MidiDrums.cpp
- rpcs3/Emu/Io/RB3MidiDrums.h
- rpcs3/Input/raw_mouse_handler.cpp
Build failed locally without that include.
Commented some unused variables that created warnings and added [[maybe_unused]] to draw_overlay_cursor(as it seems to be used on windows).
> Add <optional> to RB3MidiDrums.h

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_memory.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Loader/ELF.h
* Fixes #15209 (lv2_file::file_view::read() regressed)
* Fixes lv2_file::file_view::size() too.
* Avoid changing file position in elf_object::open(), should allow concurrent usage if we ever need it.
* Fix a potential access violation with PPU LLVM builder.
* Prevent using duplicate MSELF entries.
* Fix crash on analyzing invalid code when searching SPU code for the first time.
* Make PPU LLVM compile more MSELF entries by relaxing file name constraints.
> Fix lv2_file::file_view::size() and fix SPU cache gen on first boot

- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/Modules/sceNp2.cpp
- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.h
- rpcs3/Emu/NP/np_contexts.cpp
- rpcs3/Emu/NP/np_contexts.h
- rpcs3/Emu/NP/rpcn_client.cpp
- rpcs3/Emu/NP/signaling_handler.cpp
- rpcs3/Emu/NP/signaling_handler.h
- Improves sys_net logging
- Improves context handling
- Fixes source vport not being given to op(fixes MvC2)
(This needs a concurrent server update to make sure everyone is on latest version of udpp2p protocol)
> improves sig_ctx handling, sys_net logging and fixes udpp2p protocol

- darwin/util/sysinfo_darwin.mm
- rpcs3/Input/gui_pad_thread.cpp
- rpcs3/display_sleep_control.cpp
> Fix Apple Clang build

- Utilities/lockless.h
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
1. Prefer using inactive worker threads to ompile new SPU blocks for maximum concurrency.
2. Postpone thread notifications to when block queue is drained so all threads would start at once, not delaying the managing thread to push more blocks.
3. If more than one block has the same use count as others, apply for compilation first the one which has been queued earlier. Similarly to distance / time = speed, here the time here is compared (estimation) for rate of block usage. 
Some of these affect only CPUs with 12 or more threads at the current implementation, point 3 affects all.
Tests: Tested to improve massively the perfprmance of SPU LLVM ingame compilation for Red Dead Redemption on 14600KF
> SPU LLVM: Improve runtime SPU compilation preferences

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
With game patches, it's possible to patch certain music games to use Wii instruments rather than PS3 ones, so expose those to the emulator. 
(Since the protocol is 1:1 identical - see https://github.com/TheNathannator/PlasticBand/blob/main/Docs/Instruments/Pro%20Keyboard/PS3%20and%20Wii.md - it might be better to remap them internally in the emulator rather than making game patches to do it)
> Add Wii Harmonix instruments to USB device whitelist

- rpcs3/main.cpp
Improves the error message added with #15237.
I've already updated to 14.3.1, so I cannot test this.
> Improve macOS < 14.3 Rosetta blocker message

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/util/init_mutex.hpp
Because PPU threads were awake when waiting on mutex lock, deadlocks occurred when multiple threads used cellGame functions.
This fixes #14672
> cellGame: Fix PPU deadlocks  on concurrent execution

- .ci/build-mac.sh
This should speed up builds, and possibly prevent conflicts.
> macOS CI: Don't upgrade installed dependents

- rpcs3/Emu/system_config.h
Related to https://github.com/RPCS3/rpcs3/issues/14606.
Changing this configuration should allow games such as NFS The Run and Harry Potter Deathly Hallows: Part 1 to go further during ingame.
> Increase VBlank Frequency hertz setting

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_tty.cpp
* Related to #15271 (indirectly)
* Improve TTY logging to not spam debug data when not needed and not make the log ugly by outputting trailing newlines.
> rsx/cpu_thread: Fix cpu_thread::get_name() for RSX

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
* Detect invalid SPU relative branches (rely on the size of the SPU local storage), this would decrease the amount of false positives in SPU code mining.
* Detect 'argument passing' block before the main function.
* Detect tail calls by inspecting the called code of branches too, not just the previous code to the branch.
> SPU LLVM: Improve SPU code precompilation

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Make SPU threads happy by releasing the LLVM block pointer as early as possible by writing block data to disk *after* it is compiled and SPUs see and able to use it.
Aims to improve perfiramce while compiling SPU blocks ingame.
> SPU LLVM: Postpone cache writes until compiled

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
Target: SPU Compilation performance 🚀🚀🚀
Add another compilation thread for 6+ threaded cpus, at the expense of making some SPU threads relax a bit while compiling blocks.
This PR only affects 6-11 threaded CPUs.
> [Experimental] SPU LLVM: More compilation threads

- rpcs3/rpcs3qt/curl_handle.cpp
- rpcs3/rpcs3qt/curl_handle.h
- rpcs3/rpcs3qt/downloader.cpp
- rpcs3/rpcs3qt/downloader.h
- rpcs3/rpcs3qt/update_manager.cpp
- Don't deleteLater the progress_dialog. It's already deleted on close by Qt anyway (at least in the downloader).
- Don't close the progress_dialog if it's already closing anyway.
- Also, remove QObject from curl_handle.(thanks @RipleyTom)
Maybe this fixes random crashes when accepting or canceling the updater.
> Qt: don't deleteLater the progress_dialog

- rpcs3/rpcs3qt/downloader.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/progress_dialog.cpp
- make sure the gamelist refresh progress dialog runs on the main thread
- make sure to actually delete the progress dialog when it is closed instead of using deleteLater
- use accept instead of close to close the progress dialogs in order to prevent unwanted cancel signals
> Qt: Try to fix some edge cases related to the progress dialogs

- rpcs3/Emu/RSX/Common/ranged_map.hpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/rpcs3qt/gl_gs_frame.cpp
- Move entire creation of QOffscreenSurface to main thread (assert due to signal from wrong thread)
- Fix invalid ranged_map iterator comparison (assert due to different iterator types).
This happens if m_it is not set to an iterator of the same object as other.m_it.
```
iterator it1 = obj1.find(...);
iterator it2 = obj2.find(...);
iterator def1 = {};
iterator def2 = {};
it1 == def1       // assert
it1 == it2        // assert
def1 == def2       // fine
it1 == obj1.end() // fine
```
> RSX: Fix Visual studio debug runtime 

- .ci/deploy-linux.sh
libvulkan.so being bundled in the AppImage causes issues with gamescope, see https://github.com/RPCS3/rpcs3/issues/14917
Tested with: 
- Manjaro Linux 23.1.3 with mesa RADV
- Steam Deck LCD on Desktop Mode
- Steam Deck OLED with Gamescope
AppImage now requires the system to have [vulkan-icd-loader](https://archlinux.org/packages/extra/x86_64/vulkan-icd-loader/) installed, as many other gaming related packages such as steam
> appimage: Do not bundle libvulkan.so

- rpcs3/rpcs3qt/game_list_frame.cpp
- Remove some redundant duplicate code
- Only connect refresh watcher signals once
> Qt: more game list progress dialog fixes

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/progress_dialog.cpp
For some reason setValue crashes in the progressValueChanged slot for no apparent reason.
I'm losing my patience with this and blame the Qt devs as they've proven to produce QtConcurrent bugs :)
So let's just use a timer to update the dialog.
> Qt: replace refresh progress slot with timer

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Seems to fix the loading of Fuel Overdose Demo.
> HLE: clear lower bits of Free Disk Space value

- 3rdparty/curl/libcurl.vcxproj
- 3rdparty/wolfssl/CMakeLists.txt
- 3rdparty/wolfssl/extra/win32/user_settings.h
Fixes https://github.com/RPCS3/rpcs3/issues/15321.
By default WolfSSL doesn't consider alternate certificate chains and cloudflare recently changed their certificates to include a reference to an old certificate that is not in modern trust stores which caused issues.
> Enable WOLFSSL_ALT_CERT_CHAINS

- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/PPCDisAsm.h
- rpcs3/Emu/Cell/PPUDisAsm.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/PPUTranslator.h
Instead of resolving all function addresses externally one by one, resolve them all internally within a single function that populates the PPU jumptable which is almost instantaneous. I learned some nice things during the making of this PR, first, it took extremely long amount of time to compile this function when the loop has been unrolled instead looped over arrays, so this made me learn new concepts such as the usage of PHI nodes. This makes the booting of "Skate 3" much smoother for example.
For this purpose, I had the audacity to partially invalidate LLVM cache. (only the last module, which contains the resolver function, is invalidated for each file) 
Also fixes #14909 for some reason.
> PPU LLVM:  Get rid of "Applying PPU Code" Stage, use smart symbol resolver function instead

- rpcs3/Emu/Cell/PPUThread.cpp
Following #15333, there is no need to resolve the address of BLR-only function externally because at this point of code there are already samples of it laid down on the jumptable by the resolver function.
Also fix related UBs regarding jumptable access.
> PPU LLVM: Remove one external symbol resolve for BLR

- Utilities/Thread.h
- rpcs3/Crypto/decrypt_binaries.cpp
- rpcs3/Crypto/unzip.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/util/serialization.hpp
- rpcs3/util/serialization_ext.cpp
- rpcs3/util/shared_ptr.hpp
Savestate creation is relatively long due to compression, it makes some users think savestates do not work or that RPCS3 crashed. So I propose for now a progress dialog for savestate creation which shows how much time passed and how many bytes were written.
The percentage shown is not accurate and is an estimation of the amount of bytes written, never actually reaching 100% before completion in order to simplify the implementation.
> GUI/SaveState: Progress Dialog On Save State Creation,  Saving Fixes And Speed Improvement

- rpcs3/rpcs3qt/gui_application.cpp
It was counting uncompressed bytes before, so now it should show the current amount of bytes written to disk.
> Fixup Savestate Progress

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/util/serialization_ext.cpp
- rpcs3/util/serialization_ext.hpp
* Fixup savestates that I broke again in #15346 
* Include RawSPU's loops  for SPU-Compatible Savestates Mode by making RCHCNT IN_MBOX/EVENT_STAT a safe return point. (because they are likely in a loop)
> Fixup a race in emulation stopping, More SaveState fixes

- rpcs3/Emu/Audio/Cubeb/CubebBackend.cpp
- rpcs3/Emu/Audio/FAudio/FAudioBackend.cpp
- rpcs3/Emu/Audio/XAudio2/XAudio2Backend.cpp
- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- log some more audio backend info
- simplify some cellPad code
- Rename Navigation device class to PS Move Navigation
> cellAudio: log some more audio backend info

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/Modules/cellScreenshot.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Cell/lv2/sys_time.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
* Save PPU threads running order.
* Extend RCHCNT safe returns to include more channels when using SPU-Compatible Savestates setting.
* Make SPU STOP instruction a safe return point for savestates also in SPU Mega mode.
* Fix conflicts between shutting down emulation and savestates.
* Fix PRX functions with savestates.
> Savestates: More fixes

- rpcs3/Emu/RSX/GL/GLPresent.cpp
It turns out that image_to_flip2 is nullptr in GLGSRender::flip, which then leads to a simple_array of size 2 and then images.map(FN...). It then tries to call xform with the dereferenced nullptr in simple_array::map.
So there's 3 potential bugs here:
1. deref nullptr in map
2. using a simple_array of size 2 even though image_to_flip2 is nullptr
3. having a nullptr in image_to_flip2 in the first place
I tried to check the iterator for nullptr, but it seems to enter the scope and call xform anyway.
So we can just make sure not to call map with a nullptr in the first place.
fixes #15361
> GL: fix segfault in GLGSRender::flip

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLTypes.h
- rpcs3/Emu/RSX/Program/SPIRVCommon.cpp
- rpcs3/Emu/RSX/Program/SPIRVCommon.h
- rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp
- rpcs3/Emu/RSX/VK/VKCommonDecompiler.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp
- rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
First part of the effort to add SPIRV support to OpenGL backend. Unfortunately a lot of the final code for OGL was lost after an angry hard reset :(
SPIRV shaders will be required for some buggy drivers to function with rpcs3 such as intel.
> rsx: Move SPIRV stuff into common code

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- rpcs3/Emu/Cell/PPUModule.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/Emu/savestate_utils.hpp
- rpcs3/util/serialization_ext.cpp
* Fix a deadlock regarding VM locks with emulation stopping and savestate loading.
* Fixup emulation stopping.
* Fix SPU LLVM sinking stores beyond a saveable code point.
* Make saving state impossible while a cellSaveData operation is active.
* Save pending RSX flip, fixes savestate freeze on load with Tales Of Xillia 2, or I guess, every game that needs PS3 Native frame rate mode.
I can't anymore find bugs in games with savestates anymore, if you do, please report.
> Savestates: Fixes Maxima

- rpcs3/Emu/RSX/RSXThread.cpp
Run begin() immediately after hardware initialization to pre-create the framebuffer cache and prefetch shaders. This seems to be enough.
> rsx: Fix loading savestates captured during draw calls

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
* In #15376, vsh.self is being precompiled. And when that happens, RPCS3 attempts to precompile nearly every PPU executable it finds lying inisde the firmware. By itself this is currently the intended behavior, but after some debugging I discovered that the memory of every executable lying inisde the "/dev_flash/sys/" is not being released after it finalizes.
The proper way to do it is: whitelist only file under "/dev_flash/sys/external", of PRX type only and only if being done ingame.
* The second problem is that RPCS3 naively allows concurrent loads of executable PPU files and their entire LLVM workloads per CPU thread. This is not only a cause for massive memory usages during precompilation but is also not really needed as each files may get multiple threads to compile it as well …
> PPU LLVM: Fix memory leaks and protect against the rise of CPU threads in the coming years

- rpcs3/rpcs3qt/update_manager.cpp
Add a button that links to the Patreon on update successful dialog, nothing fancy.
> Updater: Add RPCS3's Patreon link to update dialog

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/rpcs3qt/about_dialog.cpp
- rpcs3/rpcs3qt/instruction_editor_dialog.cpp
- rpcs3/rpcs3qt/instruction_editor_dialog.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/update_manager.cpp
- rpcs3/rpcs3qt/welcome_dialog.cpp
Should fix the last SPU crash with savestates.
> SPU LLVM: Fix store elimination within common blocks and MFC commands

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.h
- rpcs3/Emu/savestate_utils.cpp
Mimic the behavior of TCP sockets of losing the connection with the server on savestate load.
I don't know the errors for some operations, leaving it for @RipleyTom to review.
> Savestates/Network: Feign connection failure on startup

- rpcs3/rpcs3qt/update_manager.cpp
QLabel auto detects if the text is html so adding spaces to it didn't lengthen it, needed to use \&nbsp; to actually add spaces.
An extra space is added the first time otherwise it considers the word update and all the spaces as a single word and puts it on a new line.
> Fix changelog size hack

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellGame.h
- Allow to insert a disc if no disc is mounted
- Only Allow to eject a disc if a disc is mounted
- Don't init the state as inserted. It may be an HDD game
> cellGame: Enable disc insert/eject based on disc mount state

- rpcs3/Emu/Cell/lv2/sys_net.cpp
- Reset queue member after move (moved containers are in an undefined state)
> lv2_socket: reset queue after move

- rpcs3/Emu/Cell/Modules/cellCamera.cpp
- rpcs3/Emu/Io/camera_config.h
- Fixes loading of camera setting (which was a regression from the Qt6 refactoring of the camera classes)
- Trace some cellCamera log messages
> cellCamera: fix config from_string

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- add size param check to cellHddGameGetSizeKB
- add version param check to cellHddGameCheck
- add dirName nullptr check to cellGameDataCheckCreate2
- remove errDialog param check (I don't know why this check existed)
- remove comment about CELL_GAMEDATA_ERRDIALOG_NONE. errDialog seems to be checked for == 1
- check systemVersion string in cellGameDataSetSystemVer and cellHddGameSetSystemVer
> cellGame: add some more error checks

- rpcs3/Emu/Cell/Modules/cellRtc.cpp
- implement Rfc3339 part of cellRtcParseDateTime
- simplify cellRtcParseRfc3339
- return a value in cellRtcGetCurrentSecureTick
> cellRtc: some improvements

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Allow the SPU Analyzer to look for more instructions after encountering an absoulte-branch instruction.
> SPU Analyzer: Do not terminate blocks on BRA

- rpcs3/Emu/Cell/Modules/cellRtc.cpp
- rpcs3/Emu/Cell/Modules/cellRtc.h
- Both date_time_to_tick() and tick_to_date_time() now have constant run time
- date_time_to_tick():
- Replaced with implementation from cellRtcGetTick() which already is exactly what LLE does
- Instead of counting the days that have passed in previous months in a loop, it now uses a lookup table since those values are always the same for each month
- tick_to_date_time():
- Microseconds, seconds, minutes, and hours are already calculated the same way as LLE
- Day, month, and year are calculated differently from LLE but produces the same result for every input and is less complex
- The amount of days that fit into a u64 tick is small enough that I was able to test this for every single possible day
- Fixed the null pointer check in cellRtcGetTick(). LLE actually returns CELL_OK here.
- Set …
> cellRtc: tick conversion improvements

- rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
- Implement shared function of cellSysutilAvc2Load and cellSysutilAvc2LoadAsync
- Only send cellSysutilAvc2LoadAsync callback with CELL_SYSUTIL_AVC2_VOICE_CHAT
> cellSysutilAvc2Load: param checks

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/debugger_list.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
* If the savestate file does not contain a version supported, ensure it is 0 so the serialization can be skipped entirely later.
* Log sub-versions supported by the savestate file on load.
* Fix out-of-range access bug when encountering a savestate with versions unknown. (from newer builds)
* Add names for the saving stages for the save progress dialog.
* Add SPU Profiler setting to UI in advanced tab.
> Savestates: Some improvements

- rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/util/fixed_typemap.hpp
Skip serialization tagging on missing cellSysutilAvc2 object from save file. Fixes #15444 
Ironically this tagging mechanism is what enables such good debugging of savestate load failures.
> Savestates: Fixup

- rpcs3/Emu/Io/Buzz.cpp
- rpcs3/Emu/Io/usb_device.cpp
- Update the USB descriptors to be easy to read
- Silence an Unhandled Query error and move it to Trace level
- Call set_interface for emulated devices
> Buzz cleanup

- rpcs3/Emu/RSX/NV47/HW/common.cpp
- rpcs3/Emu/RSX/NV47/HW/nv4097.cpp
- Ignore latch since we may have another barrier queued. Barriers cost essentially nothing so there is no problem with extra pushes.
- Remove unnecessary use of "else" statements.
The real reason for the breakage was that latching optimizations were completely broken before and are now working properly after the refactor. The bug was always there, it just never triggered before now.
Fixes https://github.com/RPCS3/rpcs3/issues/15445
> rsx: Fix intra-draw-call barrier queueing

- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentPrologue.glsl
- Lower 12 bits seem to be unused based on empirical sampling.
Fixes https://github.com/RPCS3/rpcs3/issues/15063
> [NVIDIA TESTERS NEEDED] rsx: Improve ROP output rounding precision

- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
- rpcs3/Emu/Io/GameTablet.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/RSXZCULL.h
- Don't use meta out key code in the osk overlay.
The out key code is simply used to store the meta key ID. It is not meant to be a real key code.
- fix some warnings and typos
> overlays/osk: Don't use meta out key code in the osk overlay

- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
Don't re-use sound effect objects.
Allow 3 sounds simultaneously.
Maybe fixes #15478
> Qt: try to fix sound effects

- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/savestate_utils.cpp
Seeing on discord, https://discord.com/channels/272035812277878785/277227681836302338/1230390083736047667
This happend because JIT instance was not initialized due to a failure to find functions.
I fixed that and also added an experimental fallback to find PPU functions using callers like in SPU precompilation.
> PPU LLVM: Fix crash in Unity games (regression)

- rpcs3/Emu/Io/KeyboardHandler.cpp
- rpcs3/Emu/Io/KeyboardHandler.h
- rpcs3/Input/basic_keyboard_handler.cpp
- Use unordered_map to store the keys. This may improve latency ever so slightly.
- Separates US and Japanese backslash and bracket mapping
- This together fixes those keys in the osk dialog and maybe also in cellKb in general since the US key was replaced by the japanese key due to the loop missign a break (now only one can be selected due to the map)
- Set the arrange value (keyboard type) properly.
This was apparently forgotten to add during some other refactoring and may fix some cellKb issues with non-US keyboards.
> Keyboard improvements

- rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- Silence some nonsensical nullptr deref warning in cellSysutilAvc2MicRead
- Silence llvm warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
> Silence some warnings

- rpcs3/Emu/Cell/Modules/cellMusic.cpp
- Adds the same check to cellMusicGetContentsId2 as in cellMusicGetContentsId
- Fixes some error typos (same code)
Found this commit somewhere. No idea if the checks are even correct.
> cellMusic: add missing error check

- Utilities/JITASM.cpp
- rpcs3/Input/gui_pad_thread.cpp
Don't create perf map files unless specified.
This seems like a development feature anyway.
Also fixes some missing include for some linux code.
Fixes #15462
Fixes #15448
Fixes #15341
> Don't create perf map files in linux unless enabled

- rpcs3/rpcs3qt/pad_settings_dialog.cpp
Don't crash the game if only a LDD controller is present
Steps to reproduce:
- Disconnect all the controllers
- Start a game which connect a LDD controller
- Open the Pads window
> Don't crash the game if only a LDD controller is present

- Utilities/BitField.h
- Utilities/StrFmt.cpp
- Utilities/StrFmt.h
- Utilities/bit_set.h
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/PPUCallback.h
- rpcs3/Emu/Cell/PPUFunction.h
- rpcs3/Emu/Cell/PPUModule.h
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/IdManager.h
- rpcs3/Emu/Memory/vm_ptr.h
- rpcs3/Emu/Memory/vm_ref.h
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Common/simple_array.hpp
- rpcs3/Emu/RSX/Common/surface_utils.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Core/RSXContext.h
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_components.h
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
- rpcs3/Loader/ELF.h
- rpcs3/rpcs3qt/cheat_manager.cpp
- rpcs3/util/atomic.hpp
- rpcs3/util/endian.hpp
- rpcs3/util/fnv_hash.hpp
- rpcs3/util/to_endian.hpp
- rpcs3/util/types.hpp
I was learning C++ templates and made these changes. It does not improve anything but makes the code a bit shorter.
> Cleanup templates

- rpcs3/Emu/Cell/PPUTranslator.cpp
Seems to be a regression from #15477, causing detection of some garbage code.
Convert compile-time crash to runtime crash instead for unimplemented PPU features. (likely won't reach this code at runtime)
PPU cache needs to be cleaned for it to take affect.
Proper fixes would be added in the future.
> PPU LLVM: Do not crash on linkage of garbage code

- .gitignore
- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Io/KeyboardHandler.cpp
- rpcs3/Emu/Io/KeyboardHandler.h
- rpcs3/Emu/Io/Null/NullKeyboardHandler.h
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Input/basic_keyboard_handler.cpp
- rpcs3/Input/basic_keyboard_handler.h
Currently it is possible to initialize a basic keyboard handler in the overlay input loop, ignoring cellKb.
This can potentially cause bugs or unexpected behaviour if a game uses cellKb (like having key repeat active by mistake).
- Adds consumer subscription model to the basic keyboard handler.
- cellKb and the overlay input loop now each have their own subscription.
- This allows the overlay input loop to use key repeat by default without influencing cellKb behaviour.
- Properly ignore basic keyboard input in the osk if the pad handler is set to keyboard and pad input is disabled
- Added the caps lock and the meta key (windows key) to the basic keyboard handler
- Added opencv to gitignore for undisclosed reasons
Supersedes #15501 
Thanks for finding these issues @cipherxof
> input: use keyboard consumers to seperate cell and overlay logic

- rpcs3/Emu/Cell/lv2/lv2.cpp
Should fix #15529
According to [psdevwiki](https://www.psdevwiki.com/ps3/Talk:LV2_Functions_and_Syscalls), sys_time_get_system_time is syscall 0x95
> syscall: Register syscall 149 sys_time_get_system_time

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/usb_device.cpp
- rpcs3/Emu/Io/usb_device.h
Steps:
- Launch the PSP game on a physical PSP  or [PSVita](https://github.com/isage/adrenaline_usb_enabler).
- Connect the USB cable between PSP/PSVita and PC.
- Find the menu which enables the PS3 connection - sometimes it is enabled automatically.
- A new USB device should connect with VendorID=0x054c, ProductID=**[0x01cb](https://github.com/RPCS3/rpcs3/assets/2995486/c2496620-a712-4f62-ad79-b6e519327fc1)**.
- Follow the [cellUsbd Set-up Instructions](https://wiki.rpcs3.net/index.php?title=Help:Peripherals_and_accessories#cellUsbd_Set-up_Instructions)
- Always start the PS3 game only after the Device=0x01cb is attached because USB hotplug isn't supported (#15074).
> USB: Allow UsbPspCm passthrough

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/util/console.cpp
- rpcs3/util/console.h
Every time that more than one space was repeated in a log message, the Qt log frame would display it as one. Replace it with non-breaking space.
Also: Remove two redundant copies of the `QString` on HTML escaping when not needed. The first was being done by `QString::toHtmlEscaped()`, and the second was done as an unfortunate result of `QString::replace()` return lvalue reference, which creates a copy upon rvalue conversion. (this matters mostly for huge log messages)
Misc commits:
* Fixup SPU profiler floating point inaccuracies on bounds.
* Fix potential nullptr deference in savestates on saving. (race condition)
* Debugging improvements, add SPRX booting option and always log its function exports.
> Qt/Logs: Fixing spaces, optimize string to html conversion

- rpcs3/Emu/Cell/Modules/cellMusicExport.cpp
- rpcs3/Emu/Cell/Modules/cellPhotoExport.cpp
- rpcs3/Emu/Cell/Modules/cellVideoExport.cpp
No idea what's the real logic here.
I was just winging it with the title before.
It's most likely just meant for metadata.
probably fixes #15547
> HLE: use original filename for media exports

- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
- rpcs3/Emu/Cell/lv2/sys_net/network_context.h
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.h
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/rpcn_client.cpp
- rpcs3/Emu/NP/rpcn_client.h
- Split normal(STREAM & DGRAM) sockets polling from p2p sockets polling into 2 separate threads. This should help a little bit with responsiveness(as before there was a 1ms added delay for native/p2p socks polls).
- Add a mechanism to both threads to make sure it's sleeping if no sockets are polling/no p2p sockets are active(the p2p thread must constantly poll to check for new data as it operates simulating the system receiving raw data and spreading it to potential active sockets/rpcn internal systems/signaling).
- Simplified a few things to avoid code repetition.
> Split normal sockets and p2p sockets handling v2

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
> USB: Disconnect the virtual device only for TRANSFER_NO_DEVICE error

- rpcs3/Emu/Audio/AudioBackend.cpp
- rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
- rpcs3/Emu/Cell/Modules/cellVoice.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.h
- rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.h
- rpcs3/Emu/NP/signaling_handler.cpp
- rpcs3/util/media_utils.cpp
Various improvements focused on P2PS sockets:
- Fixes SYN|ACK being sent from the listening socket instead of the newly created socket(because of this it kept being sent and was never cleared, breaking further connections as it spammed connection received with wrong seq being sent).
- Added static incremental vport assignment instead of always starting at 30000 and finding the first one free.
- Add proper disconnection mechanism, clearing all pending packets and clearing connected state from relevant maps.
- Add extra check for EAGAIN on the p2ps sockets as there can be sendto concurrency on the socket from the tcp timeout monitor thread. Now we keep trying until it goes through or another error happens.
- Send RST on receiving a valid P2PS packet aimed at a non-existent socket.
- …
> sys_net improvements

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- fix: "reference to local binding 'b2' declared in enclosing function"
- Also optimize some vector lookups
probably fixes #15596
> spu llvm: fix compilation and optimize some vector lookups

- rpcs3/Emu/Cell/Modules/sceNp2.cpp
- rpcs3/Emu/NP/fb_helpers.cpp
- rpcs3/Emu/NP/np_cache.cpp
- rpcs3/Emu/NP/np_cache.h
- rpcs3/Emu/NP/np_contexts.cpp
- rpcs3/Emu/NP/np_contexts.h
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/np_handler.h
- rpcs3/Emu/NP/np_notifications.cpp
- rpcs3/Emu/NP/np_requests.cpp
- rpcs3/Emu/NP/np_structs_extra.cpp
Matching2 contexts have an option setting that had gone unnoticed until now, it can specify if the game is interested in online name and avatar url data.
Until know we ignored that setting and gave the games both but some games fail on SceNpMatching2GetRoomMemberDataInternalLocal because they use a static buffer size for data which is insufficient for both online name and avatar url.
> Add matching2 option handling

- rpcs3/Emu/Cell/Modules/cellPad.cpp
> PAD: Fix ldd_data transfer

- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Input/pad_thread.cpp
- Query LDD pad data in the overlay input loop
We usually only care for the rpcs3 input wrapper when we handle input in the overlays.
But LDD pads are basically extra pads registered by the game (like a custom controller or some instrument).
The input state of these LDD pads is populated by the game itself instead of us.
So in order to receive input of these pads in the overlays, we have to manually check the proper ldd_data buffer.
probably fixes #15164
> overlays/input: allow ldd pad input

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_rsx.cpp
- rpcs3/Emu/GDB.cpp
- rpcs3/Emu/Io/GunCon3.cpp
- rpcs3/Emu/Io/GunCon3.h
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/RSX/Capture/rsx_trace.h
- rpcs3/Emu/RSX/Core/RSXIOMap.hpp
- rpcs3/Emu/RSX/NV47/HW/nv4097.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/rpcs3qt/breakpoint_list.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_list.cpp
- rpcs3/rpcs3qt/instruction_editor_dialog.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
- rpcs3/rpcs3qt/memory_viewer_panel.cpp
- rpcs3/rpcs3qt/memory_viewer_panel.h
- rpcs3/rpcs3qt/register_editor_dialog.cpp
- rpcs3/util/serialization_ext.cpp
- Replace magic number id_type with thread_class
- Initialize some uninitialized rsx thread members
- Fix spu_thread audit check
- Add comments to reference old scheduler at least somewhere in the code
> threads: some cleanup

- rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- rpcs3/Emu/Cell/Modules/cellSysutil.h
- rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
Sets the ground for #15586 to use, implementing the correct interface for HLE callbacks unloading for this purpose. Credit to @RipleyTom for the thorough inspection and debugging of the bug.
> cellSysutil: Implement dispatcher callback unloading

- rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
- rpcs3/Emu/NP/np_cache.cpp
Some inaccuracies in the way we handle CBs led to some issues for DBZ: RB2.
This emulates the behaviour of the internal Avc2 dispatcher.
> Improve CB accuracy for Avc2

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/System.cpp
Turns out the previous fix was only partial.. lol
It missed barriers from the direct block targets.
Fixes some SPU crashes on savestate load.
> Savestates/SPU LLVM: Fix sinking store finally

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXZCULL.cpp
* Attempt to fix regressions with GOWA with #15429 while also improving accuracy by invalidating reservation timestamps.
* Partially import RSX accurate reservations functionality to default settings. The core part that was put in place for GOWA.
* Disable PUTLLC16 optimization when using accurate RSX reservations.
> RSX/SPU: Import and improve RSX accurate reservations functionality

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Revert the previous workaround.
> SPU LLVM: Implement PUTLLC16 for accurate RSX reservations

- rpcs3/Input/raw_mouse_handler.cpp
- rpcs3/Input/raw_mouse_handler.h
- rpcs3/rpcs3qt/basic_mouse_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/raw_mouse_settings_dialog.cpp
- rpcs3/rpcs3qt/raw_mouse_settings_dialog.h
- Adds device enumeration thread to the raw mouse handler (updates once per second)
- Adds device enumeration timer to the raw mouse config dialog (updates once per second)
- The enumeration only takes a couple of microseconds, so once a second should be fine
- Increases the max amount of devices in the dropdown to 16
- Ignore right click to clear input config button if the button is disabled (this seems to have been a bug since the beginning)
> Implement raw mouse hot swap

- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- Use raw cell key code in CellOskDialogKeyMessage (🤦 we don't need the Qt code)
- Clarify cellKbCnvRawCode alphabet conversion (this was a bit confusing to read)
- Don't use caps lock as shift lock unless we are using the qwertz or azerty layout
maybe fixes #15516
> Fix OSK event hook callback key code

- rpcs3/Emu/RSX/VK/VKCompute.cpp
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/15632
> vk: Don't always preserve the renderpass for all drivers when doing transform hot-patch

- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
There was a typo in PR [15636](https://github.com/RPCS3/rpcs3/pull/15636) that disabled early discard for Nvidia GPUs where it should be the opposite
> Fix logic typo from PR 15636

- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
There are a few rare reports of device creation failing and crashing the application. Dump the requested extensions and enabled features if that happens.
We can't do much about missing features since we need some of them for proper emulation without ridiculous bugs, but with more information gathered we can identify reasonable workarounds.
> vk: Dump diagnostic messages if device creation fails

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
We all deserve to enjoy this weekend. (enabled only if SPU Debug option is on still)
Issues about performance regressions from this commit would be closed.
> SPU LLVM: Disable PUTLLC16 for the weekend

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
In metal gear online, whenever a socket error occurred in sendto, the game would halt indefinitely spamming an infinite loop of errors. 
It turns out sendto was never actually returning the error code.
> sys_net: properly return error in sendto

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
Currently, if a Santroller device is detected but it is already in use, RPCS3 crashes.
This fixes that by not trying to send control transfers to devices that can't be opened.
> USB: If a Santroller device is in use elsewhere, don't send it commands

- .cirrus.yml
FreeBSD 13.2 image was removed from freebsd-org-cloud-dev. 
As mentioned in https://cirrus-ci.org/guide/FreeBSD/, only _official FreeBSD VMs on Google Cloud Platform are supported_.
Security support for 13.2 ends at the end of the month (30 Jun 2024) too, so we will both switch to active 13.3 to keep up-to-date and fix the CI not working.
Fixes #15661.
> Cirrus: Update to FreeBSD 13.3

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Fixes #14147, turns out it was simply missing target registration. (the random freezing with the game is still present though)
> SPU Analyzer: Fix of Crysis

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/rpcs3qt/tooltips.h
- Update raw mouse connection info in cellGemGetInfo
This was not necessary before, because the enumeration took place during initialization.
Now that the enumeration is run periodically in a thread, we need to query the connection state on each cellGemGetInfo call.
fixes #15665
> Fix raw mouse move handler

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
> SPU: Silence some warnings

- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_progress.cpp
* Use exported functions as the baseline for function analysis if none other is found. (PRX)
* Implement SUBFO, ADDCO and NEGO instruction forms. (setting overflow bit)
* Fix fallback function analysis with conditional link branches.
* Fix Branches with link to the next instruction, this is apparently how DOT.NET's PS3 SPRX files resolve relative addresses for data within PRX. They never heard of TOC which is also why function analysis used to not detect a single function of it.
* Dump decrypted PRX when PPU debug is enabled
Fixes #15524, while also properly supporting LLVM for them. (they used slower interpreter fallback)
> PPU LLVM: Support Unity games properly

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
I was doing some real hardware testing, and when I compared the results on hardware vs on RPCS3, I noticed that RPCS3's sys_ppu_thread_join() implementation doesn't check whether the target thread is joinable or detached, hence causing unexpected behaviors.
> sys_ppu_thread: Fixed up sys_ppu_thread_join()'s check for detached threads

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Honestly.. I don't know why it is needed for some games, but it's better than not utilizing PUTLLC16 at all which is a wonderful concept.
> SPU: Enable PUTLLC16 with RTIME checks

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Io/mouse_config.cpp
- rpcs3/Emu/RSX/GL/glutils/program.cpp
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
- rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/rpcs3qt/game_list_frame.cpp
*  Add shortcut to open cache directory in context menu. (developers only feature)
* Fix some file write bugfixes.
> Game List: Add shortcut to open cache dir

- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Common/TextureUtils.h
- rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.h
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureOps.glsl
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
Unlike desktop, PS3 has per-channel SNORM flags to toggle between UNORM and SNORM behavior. In the past I had attempted implementing this with true desktop SNORM formats, but the whole thing got messy very fast once we had titles with SNORM RGB and UNORM A configuration and others with SNORM, UNORM and sRGB flags all set. We moved to a software emulation model but the SNORM behavior was not correctly implemented, instead sharing code with the BX2 (sign expand) code which was incorrect.
This PR implements the sext behavior for SNORM textures properly.
It sorta fixes and breaks things at the same time and I don't have enough time to figure out all the corner cases, so I'm submitting this as-is as it is technically complete.
> rsx: Properly implement signed normalized texture emulation

- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds3_pad_handler.h
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/hid_pad_handler.h
- rpcs3/Input/skateboard_pad_handler.cpp
- rpcs3/Input/skateboard_pad_handler.h
- Dualsense: Don't turn off the lights when the game closes.
- Replace raw buffer access with struct casts
- Add more enum values
- Allow to access touchpads internally (not in use by rpcs3)
- Fixes #15519
> DS3/DS4/Dualsense: Improvements

- rpcs3/Emu/Io/Null/NullPadHandler.h
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds3_pad_handler.h
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/gui_pad_thread.cpp
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.h
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/mm_joystick_handler.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/pad_thread.h
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/sdl_pad_handler.h
- rpcs3/Input/skateboard_pad_handler.cpp
- rpcs3/Input/skateboard_pad_handler.h
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.h
I noticed that the pad connection state in games doesn't respond to pad settings changes properly anymore.
For instance, after switching from a disconnected DS4 handler to a connected xbox handler I had to first disconnect and then connect the controller again before I could control the game again.
I think it's best to move the pad_state_notify_state_change to a dedicated spot in the pad thread.
This has several advantages:
- The connection state notifications are now independent from the pad handlers and their settings
- The code now has a single point of failure. We had 3 spots before and the conditions didn't even match.
- Fixes an issue where the passed index was always based on the pad count in the individual handlers instead of the total pad count
- We can remove the "emulation" …
> input: Try to fix ingame pad connection updates

- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.h
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
It was missing signaled bit reset whenever _sys_lwmutex_unlock2 was used without a waiter.
> Fix sys_lwmutex_lock for SYS_SYNC_RETRY

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/system_config.h
You got fooled.. click-baited.. hoodwinked.. The reason being I want you test this.
What this pr does is to detect long GETLLAR loops using data from the past to determine if operating system sleep need to be involved. This is related to #12523 but brings GETLLAR wait detection into the masses by carefully observing the time it takes for the reservation data change to come through before deciding to opt for CPU sleep.
Edit: In addition, I have added detection for concurrent waiting on the same data between multiple threads, so each thread can notify the others in the case of the data change. That is what (hopefully) prevented most of performance regressions, allowing mostly improvements. 
What to compare:
* CPU and SPU usage.
* Performance difference, especially on lower threaded CPUs. …
> [Testers Needed #3] SPU: Use AI for GETLLAR spin detection

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
Doing so in code not belonging to loops is non-beneficiary and may result in adverse effects on performance because the value has to be carried farther until the store.
> SPU LLVM: Avoid sinking stores out of non-loops

- rpcs3/rpcs3qt/gui_application.cpp
When launching emulator on linux, the following line appears in console:
> E CFG: cfg::try_to_float('0.000000'): invalid float
It happens because my systems locale uses comma as decimal separator while rpcs3 expects dot.
RPCS3 does try to set locale to C when launching:
https://github.com/RPCS3/rpcs3/blob/7e27e1420e9bf6545a6f642987f56ac335649bcd/rpcs3/main.cpp#L86-L91
But Qt sets this back to system default as documented [in here](https://doc.qt.io/qt-6/qcoreapplication.html):
> On Unix/Linux Qt is configured to use the system locale settings by default. This can cause a conflict when using POSIX functions, for instance, when converting between data types such as floats and strings, since the notation may differ between locales. To get around this problem, call the POSIX function …
> Fix locale on linux

- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Cell/Modules/cellMouse.cpp
- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Io/KeyboardHandler.cpp
- rpcs3/Emu/Io/KeyboardHandler.h
- rpcs3/Input/basic_keyboard_handler.cpp
- rpcs3/Input/keyboard_pad_handler.cpp
- Adds missing Control key back to basic keyboard handler (this was a recent regression)
- Distinguish between left and right modifier keys by using native scan codes (Qt doesn't provide us with proper info)
- Use seperate log channels for cellPad, cellMouse and cellKb
NOTE: Alt Gr may not work properly, due to the way Qt passes it as "CTRL-Left" and then "ALT-Right"
fixes #15718
fixes #3393
> Improve keyboard modifier handling

- rpcs3/Emu/Cell/PPUFunction.h
- rpcs3/Emu/Cell/PPUThread.cpp
Do not read from memory at CIA address, this can lead to unexpected access violations especially for RawSPU's PPU Interrupt thread handlers.
> PPU: Fix access violation on logging

- rpcs3/Emu/Io/KeyboardHandler.cpp
- This should fix a segfault I encountered when closing a game.
I think the consumers were removed while the window went out of focus.
> input: add missing lock to keyboard handler ReleaseAllKeys

- rpcs3/Emu/Io/Turntable.cpp
- DJ Hero does not register input if the turntable is 0, so force it to 1.
This will happen if you map it to the left stick and push it all the way down, or if you use a keyboard, which sends the max value on key press.
probably fixes #15739
> input: fix minimum turntable input

- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.h
- Invalidate ds4/dualsense calibration instead of disabling the controller (same as linux kernel)
- Use same dualsense gyro calibration values as linux kernel
maybe fixes #15728
> Invalidate ds4/dualsense calibration instead of disabling the controller

- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/System.cpp
- Fix warning: std::move of const variables
- Fix warning: dangling pointer (construct string_view from temporary string)
> Fix some warnings

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.h
* Allow detection of values modified in an inner loop for PUTLLC16  pattern detection with the use of value origins and invalidation while stepping through the code. Also fix some missed detections by comparing source register instead of the value itself at PUTLLC time, this is to allow selection of two potential write destinations at runtime inside the atomic loop such as by if statement.
* Fix LSA state analysis. (do not override it in GETLLAR, instead save a masked value individually)
> SPU Analyzer: Fix support for multi-block value merge

- rpcs3/Emu/Io/RB3MidiDrums.cpp
Hotfix for last commit.
Should fix initial midi drum button mapping.
> input: actually initialize midi drum notes and combos

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/util/atomic.cpp
- rpcs3/util/atomic.hpp
Do not call `cpu_thread::check_state()` in log utilities because it is dangerous and can cause deadlocks. After some consideration I removed imkplicit check_state() calls from all thread notification locations.Thanks to @Megamouse for debugging the randm freeze of and the bug associated.
> Remove check_state() inside thread notificatios

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
* Exclude most notifications related to reservations residing on identical reservation metadata.
* Discard pending but outdated reservation notification requests. (another reservation update has been made since)
> CELL: More efficient reservation notificatins

- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/MouseHandler.cpp
- rpcs3/Emu/Io/MouseHandler.h
- rpcs3/emucore.vcxproj.filters
- rpcs3/main_application.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- Load midi drum config before creating the objects. This should fix initial note overrides and combos.
- Ignore raw mouse double click when used as move handler (just to be consistent with the other mouse handler. I was considering removing it, but I guess it's just annoying to have to set the option manually)
- Simplify mouse handler initialization
- Fix some warnings
> Fix midi drum config loading order

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXZCULL.cpp
As noted in issue https://github.com/RPCS3/rpcs3/issues/15754 (and likely issue https://github.com/RPCS3/rpcs3/issues/15645 as well), one of the optimizations added in pull request https://github.com/RPCS3/rpcs3/pull/15618 causes some games to consistently freeze at various points. This change reverts one of the optimizations made as part of this pull request, thereby fixing the freeze problems.
> revert problematic optimization introduced in pull request #15618

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/pad_thread.h
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/skateboard_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/rpcs3qt/pad_led_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_led_settings_dialog.h
- rpcs3/rpcs3qt/pad_led_settings_dialog.ui
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- rpcs3/rpcs3qt/qt_camera_video_sink.cpp
- Fix player LED groupbox label
- Fix initial battery indicator checkbox state
- Disable battery LED settings if the pad handler doesn't support it
- Allow running pad thread without emulation (useful if you need to access pads in GUI dialogs)
- Copy JPG and RGBA camera data if needed
> Input GUI fixes

- rpcs3/Crypto/unpkg.cpp
- rpcs3/Crypto/unpkg.h
- rpcs3/Emu/system_utils.cpp
- rpcs3/rpcs3qt/main_window.cpp
Should hopefully make error messages easier to decipher for end users, and maybe also helps people trying to give help for those issues.
Before:
After:
Closes #15259
> Improve error message when update cannot be installed due to version mismatch

- rpcs3/Emu/Io/GunCon3.cpp
- rpcs3/Emu/Io/guncon3_config.h
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Input/pad_thread.cpp
- Process the mouse buttons even when x/y_max aren't yet determined.
- Allows to start the calibration without shaking the mouse before.
- Extend support to 4 players. The games can't use more than 2, but it allows more flexibility to mix DS3 and GC3.
- Avoid OOB for unsupported Pads
| Menu                                         | 1 Player (Basic)                               | 1 Player (Raw)                                 | 2 Players                                        |
|----------------------------------------------|------------------------------------------------|------------------------------------------------|--------------------------------------------------|
| Configuration - Input/Output - Mouse Handler | Basic                                          | Raw …
> USB: GunCon3 updates

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.h
- rpcs3/Emu/system_progress.cpp
This is a draft, it does not do anything until later :)
This is an example of the pattern in the most simple form of it:
It spins until the IN_MBOX channel has a value without side effects in the loop, in which case RPCS3 can use channel waiting to reduce CPU time.
Edit: I decided to merge it with only basic detection of the pattern without actual use because it has other commit s to solve regressions and that users would potentially respond to what games the pattern applies. (although the detection is yet to be tested)
* I also made the progress dialog's remaining time calculation much more stable
*  fixed some recent regressions.
> [WIP] SPU: Channel Loop Pattern Detection

- rpcs3/rpcs3qt/qt_camera_handler.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- Fixes camera id string comparison in settings dialog IO tab
- Fixes "Default" camera id format selection in camera handler
> Qt: fix camera id bugs

- .github/FUNDING.yml
As mentioned in #15805 the Alipay link on project page is broken as we no longer use that platform for donations and the page for it on rpcs3.net has been deleted.
> Remove Alipay link from FUNDING.yml

- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/PPUTranslator.h
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
Affects perhaps less thqan 100 games, if no "Channel pattern loop" message appears then no affect on games.
Makes RCHCNT busy loops waiting for channel to be accessible with no side effects in games, use operating system sleep and thread notifications to save CPU time.
> SPU: Utilize Operating System sleep in detected RCHCNT loop

- .ci/build-mac.sh
- 3rdparty/MoltenVK/CMakeLists.txt
Testing: 
- Ensure CI passes
- Ensure macOS build works without issue
Changelog: 
- Improvements to bindless resources and descriptor indexing:
- Add support for Metal 3 argument buffers.
- Support argument buffers on all platforms, when Metal 3 is available.
- Support argument buffers on macOS when Metal 3 is not available.
- Use Metal argument buffers by default when they are available.
- Revert `MVKConfiguration::useMetalArgumentBuffers` and env var `MVK_CONFIG_USE_METAL_ARGUMENT_BUFFERS` to a boolean value, and enable it by default.
- Support multiplanar images in Metal argument buffers.
- Support a descriptor pool with less descriptors than the descriptor set layout, as long as the pool has enough descriptors for the variable descriptor count,
- Update max number of bindless buffers …
> 3rd Party: Bump MoltenVK to 1.2.10 (Vulkan SDK 1.3.290)

- rpcs3/Emu/Io/Dimensions.h
missing optional header (from commmit 500bf0f3f5422b31ea4c2b70e2b0b19329deac7f).
This was caught when compiling rpcs3 from this repo: https://github.com/second-reality/linux-emulation/.
Since there is no build error through RPCS3 repo, I guess different flags must have been used. Anyway, the include is still missing.
> Fixed compilation

- rpcs3/Emu/Cell/Modules/sceNp.cpp
`sceNpScoreRecordGameData` could be sending results in batches, but an error caused the transaction to reset every time, so those partial submissions would get corrupted.
Fixes Ghost Data in Ridge Racer 7.
> sceNp: Fix sending partial results from sceNpScoreRecordGameData

- rpcs3/Input/pad_thread.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
- Reload Viewport gui settings when changing visibility or active state of the game window
- Log used pad config
It's been increasingly annoying to read log files of input issues and not being able to see what pad config was actually used.
> Input: Reload viewport gui settings when changing visibility or active state of the game window

- rpcs3/rpcs3qt/config_adapter.cpp
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- Fixes custom config creation error for games that have no resolution.
- Fixes empty dropdowns if resolution flags are 0 by adding all resolutions.
- Make sure to keep 720p as option if the dropdown would be empty after all.
- Adds some missing break and fixes some const correctness in the emu_settings class.
> Qt: Fix resolution dropdown if resolution flags of game are empty

- rpcs3/Emu/Cell/Modules/cellMic.cpp
When using the emulated SingStar microphone, the device is only registered when initializing `cellMic`. However, the `mic_context` thread is only woken up when calling `register_device`. The registration happens before initializing `cellMic`, so the thread is never woken up after registering the device.
Add call to `wake_up` in `load_config_and_init` inside the emulated SingStar microphone specific code to fix this issue, allowing the thread to detect the device and update the microphone data.
This allows SingStar to receive the microphone data when using the emulated SingStar microphone that it previously wasn't receiving.
> cellMic: Wake up upon registering emulated SingStar microphone

- Utilities/JITLLVM.cpp
- Utilities/StrFmt.cpp
- Utilities/StrFmt.h
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/Modules/cellMic.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/shortcut_settings.cpp
- rpcs3/rpcs3qt/shortcut_settings.h
* When SPU Debug is option is enabled, percent of usage of SPU programs is added to the log when dumping SPU code.
* Remove welcome dialog shortcut and add description in debugger that F1 invokes the help dialog. Fixes #15839
* Fix some minor bugs regarding potential overflows.
> Add SPU usage for program dump, remove welcome dialog keyboard-shortcut

- rpcs3/Emu/Io/Dimensions.cpp
- rpcs3/rpcs3qt/dimensions_dialog.cpp
Some sections of Lego Dimensions require figures to be picked up and placed in the same spot, so I have changed the button on the move dialog to represent this, and have the backend code changed to just send responses to the game when this happens, rather than the loading and moving of file pointers when moving to a new spot.
> sys_usbd: Allow 'Moving' figure to same slot on Dimensions Toypad

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/sdl_pad_handler.h
- Adds touchpad mapping support to the DualShock 4 handler.
- Adds touchpad mapping support to the DualSense handler.
- Adds touchpad mapping support to the SDL handler.
This allows you to map your touchpad to any button, stick or trigger.
You can for example use it to control to the fake ps move cursor.
See #15834
> DS4/DualSense/SDL: Add touchpad support

- rpcs3/Input/raw_mouse_handler.cpp
- rpcs3/Input/raw_mouse_handler.h
Fixes button map out of bounds access in the raw mouse handler.
- Reload the mouse config when the index changes.
- Clear the button map before reloading the config.
- Check if the button really is in the map.
Probably fixes #15832
> raw_mouse: Fix button map out of bounds access

- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GL/glutils/fbo.cpp
- rpcs3/Emu/RSX/GL/glutils/fbo.h
- rpcs3/Emu/RSX/GSFrameBase.h
- rpcs3/Emu/RSX/Program/GLSLSnippets/VideoOutCalibrationPass.glsl
- rpcs3/rpcs3qt/gl_gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
This PR is part of the arm64 bringup series. I'm starting to merge these in.
Fixes:
1. Asahi linux (fedora version) has a full RGBA backbuffer for OpenGL by default when using Qt. Qt source code explictly sets 8 alpha bits on wayland-egl. By default when presenting to such a backbuffer, graphics get corrupted within a few seconds due to blending accumulation on the compositor. Fixed by detecting alpha on the backbuffer and using a fallback that forces alpha to 1.
2. We had double window creation for OpenGL. gs_frame calls create then gl_gs_frame calls create again. This is idempotent on windows but wayland doesn't like that at all.
Closes https://github.com/RPCS3/rpcs3/issues/15865
> gl: Fixes for wayland (asahi linux, aarch64)

- rpcs3/util/types.hpp
Formatting pointers for this purpose may be risky due to memory safety, but we can format C char arrays which would be used most of the time.
> types.hpp: Format C arrays too for assert errors

- rpcs3/Emu/Cell/Modules/cellMic.cpp
The microphone index given in `arg1` is 1-indexed, so we have to subtract 1 from the index to access the proper value.
This wasn't caught up before since we were doing direct access of the array instead of using `::at32` which wouldn't check that the value is within bounds.
This allows the original SingStar game (with no updates installed) to boot up again, as it would otherwise crash then trying to set the volume to the second channel due to the index being out of bounds.
> cellMic: Fix CELLMIC_DEVATTR_CHANVOL handling

- Utilities/JIT.h
- Utilities/JITLLVM.cpp
- rpcs3/Emu/CPU/CPUTranslator.cpp
Previously it was guessed that llvm would guess some recent version of the CPU e,g last generation intel or AMD, but instead it returns "generic" which can break the heurestics.
Adds a guessing framework to help detect CPUs better when llvm fails.
> Add fallback CPU detection when llvm is not aware of the CPU model

- rpcs3/Emu/Io/Dimensions.cpp
- rpcs3/Emu/Io/Dimensions.h
- rpcs3/Emu/Io/Infinity.cpp
- rpcs3/rpcs3qt/dimensions_dialog.cpp
- Do not try to fetch figures if the index in the request is out of bounds. Just ignore the read/write instead
- Add lock to pop_added_removed_response
- Add lock to move_figure (somewhat recursive)
- Make some functions static
maybe fixes #15886
> Dimensions: Try to fix out of bounds array access

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Aims to fix https://github.com/RPCS3/rpcs3/issues/15845
> SPU LLVM: Revert store postponing restrictrictions

- rpcs3/Emu/Io/Dimensions.cpp
Use the default reply for color commands for all Color commands. Should fix https://github.com/RPCS3/rpcs3/issues/15888
> sys_usbd: Default replies for Dimensions Color Commands

- rpcs3/Emu/Cell/Modules/cellMic.cpp
- rpcs3/Emu/Cell/Modules/cellMic.h
- Check device pointers and log openal error codes
- Early out if the sample count is 0
- Use single mic device struct vector instead of 3 seperate vectors
- Refactor duplicate sample getter code into a single function
- Only call sample getter function once before distributing the data
- Add paranoid size checks to the sample getter
- Optimize sample getter loops a bit
- Drop superfluous memcpy to temp_buf in the real_singstar case
- Do not allocate temp_buf unless necessary
> cellMic: improvements

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/CPU/Backends/AArch64JIT.cpp
- rpcs3/Emu/CPU/Backends/AArch64JIT.h
- rpcs3/Emu/CPU/CPUTranslator.cpp
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/CPU/Hypervisor.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/PPUTranslator.h
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/util/simd.hpp
Adds support for arm64 LLVM JIT.
Closes https://github.com/RPCS3/rpcs3/issues/15867
Closes https://github.com/RPCS3/rpcs3/issues/15868
Only linux has been tested so far. MacOS should work though may require some fiddling, that is work for later.
The implementation presented here uses a post-processing method on the LLVM IR as it was the most flexible approach (you can see remnants of the original idea in the first commit). Previous ideas like x86-ifying the IR also worked but were slow likely due to all the stack management and pushng/popping of return addresses and the like. Previous attempts (all worked to some degree) include.
- Stack-based call/ret management. Clumsy and slow. Often crashed if anything misbehaved.
- Custom LLVM. First approach I used, not scalable.
- Explicit "gates" …
> aarch64/cpu: Add LLVM support

- 3rdparty/pine/pine_server.h
Hello! This small pull request aims to fix the PINE IPC socket file naming for Mac and Linux users. Essentially, the port is now only concatenated to the socket name if it is different than the default port.
This change was made to match with the specification of the [PINE protocol](https://github.com/GovanifY/pine/blob/master/standard/draft.dtd#L79-L115) and [the other emulators implementing it](https://github.com/PCSX2/pcsx2/blob/edeb0d7bd7258c58273cc4a88a9f9a823d71e48c/pcsx2/IPC.cpp#L95-L96).
> PINE: Fix socket naming for Mac and Linux to match protocol specification

- Utilities/JITLLVM.cpp
Following this example:
https://github.com/RPCS3/rpcs3/blob/master/Utilities%2FJITLLVM.cpp#L73
I resolved:
```
Class "llvm:StringRef" has no member 'Startswith'
if (brand.startswith("AMD"))
```
and
```
Class "llvm:StringRef" has no member 'Startswith'
else if (brand.startswith("VirtualApple"))
```
observed when checking out
LLVM 19.1.0-rc2
This resolves 1 problem with compilation on later versions of LLVM
> Class "llvm:StringRef" has no member 'Startswith'

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/mouse_config.cpp
- rpcs3/Input/basic_mouse_handler.cpp
- rpcs3/Input/raw_mouse_handler.cpp
- Fix initial reload of mouse handler configs. Ignore mouse events while the handler isn't initialized.
- Log any input config file contents if in use
- Only allow each move mouse handler button to be used for one action unless it's the combo button.
> Fix initial reload of mouse handler configs

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/mm_joystick_handler.h
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/sdl_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- Pad settings: Ignore button press or stick values unless they increase
This basically means that already pressed buttons or sticks won't trigger a remap unless you release them and press them again.
This hopefully improves mapping your buttons and sticks in the pad settings dialog.
fixes #15086
> Pad settings: Ignore button press or stick values unless they increase

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/mm_joystick_handler.h
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/sdl_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
The latest button mapping changes that ignore already pressed buttons or axis when trying to remap a button do not to work properly due to the event based way evdev works.
We don't have all the events in the first call to get_next_button_press, so we have to set all the buttons that are not found in the first call to max in order to properly check them in the subsequent events.
> evdev: try to improve button mapping

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/System.cpp
Turns out PUTLLC16 optimization was not accurate due to data usage from GETLLAR after the atomic loop ends, but was compatible with a surprising number of games and had significant performance benefits for some such Metal Gear Solid Online.
So, I keep it, when SPU Accurate Reservations is off.
Fixes #15702
Fixes #15802
Fixes #15645
Fixes #15710
> SPU: Fix bug in GETLLAR, Enable PUTLLC16 if accurate reservations is off

- rpcs3/rpcs3qt/rpcn_settings_dialog.cpp
Enables users to cancel/reject friend requests
Sender
Recipient
May fix #15353
> Enable users to cancel/reject friend requests

- rpcs3/CMakeLists.txt
- rpcs3/Emu/RSX/GL/OpenGL.cpp
- rpcs3/rpcs3qt/gl_gs_frame.cpp
1. Do not force vsync on by default. Some of the poor opengl performance observed in rpcs3 is actually just caused by this bug.
2. Do not use glxSwapInterval under wayland. We should use eglSwapInterval instead.
3. Show the OGL window after creation. This solves so many weird problems in wayland such as invisible game window or crashes with a wayland error in the log.
> gl: Fix OpenGL behavior under wayland-egl

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/tooltips.h
By pressing ALT while clicking on a button in the pad settings, you can now enable a special mode for XInput.
This allows you to map the XInput triggers as positive or negative triggers.
We previously basically always treated XInput triggers as buttons. So you could only map pressing the trigger to a button.
The special mode will treat triggers that are pressed more than 50% as positive triggers and triggers that are pressed less than 50% as negative triggers.
You can therefore map a trigger to an entire stick axis, for example by mapping LT+ to LY+ and LT- to LY-.
This has only become feasible recently when I implemented that the initial state is ignored during a re-map.
In order to map a negative trigger, you will have to press the trigger before clicking one of the buttons in the pad …
> xinput: allow to map triggers as positive or negative

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/util/yaml.cpp
- rpcs3/util/yaml.hpp
- Improve patch.yml value validation.
Turns out that we were accepting values that were too large for data types <= 32bit.
This fix shouldn't break the official patch file. It seems to work fine.
- Use fs::write_file in patch code
- Use show instead of exec for some message boxes
- Fix some random msvc warnings
> Improve patch.yml value validation

- Utilities/bin_patch.cpp
- rpcs3/rpcs3qt/patch_creator_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.ui
- Patch creator: use YAML emitter to produce valid YAML blocks
- Patch manager: allow to select text (notes etc.) with the mouse, so you can copy them
- Patch validation: check if serial is 9 characters long and alphanumeric
- Patch validation: check if app version is 5 characters long and like 01.00
- Patch validation: don't allow duplicate app versions
One "downside" is that it doesn't look exactly as before, since yaml-cpp adds or omits some spaces in places.
In theory we could omit the "" in keys if they are not needed, but I kept it in for consistency.
fixes #14168
> Qt: Improve patch creator and patch manager dialogs

- rpcs3/rpcs3qt/pad_motion_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
Increase input timers back to 1000Hz. The DS4 lags if it's slower.
Decrease all pad UI update timers from 1000Hz to 100 Hz.
fixes #15951
> Qt: fix pad settings latency

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/GDB.cpp
- rpcs3/Emu/perf_monitor.cpp
- rpcs3/Emu/system_progress.cpp
Make loops with constant duration intervals more accurate by accounting time spent in code, by implementing and using a function parallel to `std::this_thread::sleep_until()`.
> Implement thread_ctrl::wait_until()

- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/hid_pad_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/sdl_pad_handler.h
- rpcs3/Input/skateboard_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- Always send output report after at least 300ms to prevent lost updates (for example rumble won't stop)
- Qt/XInput: Don't report two direction trigger values unless actually requested
Fixes a bug in the pad settings dialog where you could map LT- in XInput even if you weren't pressing ALT when clicking on the button before.
Fixes #15955
> input: Some fixes

- Utilities/Thread.cpp
- rpcs3/Emu/CPU/Backends/AArch64/AArch64JIT.cpp
- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPUInterpreter.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/util/types.hpp
- Fix "unused variable" warnings caused by arm64 path not consuming some variables.
- Fix hang when compiling leaf blocks
- Add more instruction families to the write detection code. Fixes hangs in some games.
Fixes https://github.com/RPCS3/rpcs3/issues/15970
> aarch64 fixes

- Utilities/Thread.cpp
- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/CPU/Backends/AArch64/AArch64Signal.cpp
- rpcs3/Emu/CPU/Backends/AArch64/AArch64Signal.h
Decode fault details from parsing the machine context instead of trying to maintain a list of known instructions. Unlike x86, arm instructions are a jumbled mess without simple byte patterns.
The decoder is reversed from linux kernel sources, so I have only enabled it for linux.
> Rework aarch64 signal handling

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/settings_dialog.ui
- config: Set minimum allowed resolution scale to 25%
- Allows rendering at PSP resolution with 38%, required for aarch64 devices with extremely weak GPUs
- spu: Workaround GCC 14.1 compiler bug
- Stumbled upon this issue with gcc 14.1.1+r1+g43b730b9134-1 on aarch64, failing compilation due to implicit fallthrough warnings being treated as errors
> config: Set minimum allowed resolution scale to 25%

- rpcs3/Emu/RSX/VK/VKCompute.cpp
- rpcs3/Emu/RSX/VK/VKHelpers.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
v3dv supports BC1-BC3 which is all we require, support is reported as  false since not all formats are supported
Fixes #15969
> vk: Support v3dv, allow creating device without textureCompressionBC

- rpcs3/Emu/CPU/CPUDisAsm.h
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/rpcs3qt/breakpoint_list.cpp
- rpcs3/rpcs3qt/breakpoint_list.h
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_list.cpp
- rpcs3/rpcs3qt/debugger_list.h
Avoid using free-after-use pointers, even for simple stuff as comparison.
> Debugger: Pointer comparison bugfix

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/CPU/Backends/AArch64/AArch64Common.cpp
- rpcs3/Emu/CPU/Backends/AArch64/AArch64Common.h
- rpcs3/Emu/CPU/Backends/AArch64/AArch64Signal.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/util/sysinfo.cpp
- Add some basic CPU brand name detection. I do not have a complete list, but we have enough to get started.
- Fix macOS arm64 compilation.
Closes https://github.com/RPCS3/rpcs3/issues/15980
Closes https://github.com/RPCS3/rpcs3/issues/15972
> aarch64: CPU branding info and misc improvements

- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp
WSAENETRESET is returned instead of ECONNRESET on windows when the disconnection happens because of keep alive packets timeout and not reset by opponent.
> Handle WSAENETRESET error

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
Seems to reduce reservation CPU time in Dark Souls from 96% to 46%. (beware that resrvation CPU time is not an accurate measure and more testing needs to be done)
> SPU: Remove condition from GETLLAR spin detection

- Utilities/JITASM.cpp
- Utilities/JITLLVM.cpp
- rpcs3/Emu/CPU/Backends/AArch64/AArch64Common.cpp
1. CPU topology, brand names, etc are available from sysctl. I couldn't find much info if these variables have codes we can use with sysconf command so I just used a shell to get it. Works well enough on my system where the CPU brand and number of P and E cores is correctly detected.
2. Change JIT environment to linux-android instead of linux-gnu. MacOS and android reserve use of the x18 register and it should not be used in emitted JIT.
3. Fix a rare crash when compiling a large number of SPU blocks without overcommit being available.
With these changes, LLVM is now usable on the M-series apple chips natively without going through rosetta. Same caveats as linux apply - not all games will work right now, but most of them should be fine, including AAA titles.
> MacOS - Implement remaining portions for native ARM64

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/persistent_settings.cpp
- rpcs3/rpcs3qt/persistent_settings.h
- rpcs3/rpcs3qt/rsx_debugger.cpp
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/settings.cpp
- rpcs3/rpcs3qt/settings.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/shortcut_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
Maybe reduces some strange UI errors that may happen when a game crashes.
> Qt: sync gui settings by default after setting or removing values

- rpcs3/Emu/RSX/GL/GLOverlays.cpp
- rpcs3/Emu/RSX/Program/RSXOverlay.h
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/Emu/RSX/VK/vkutils/graphics_pipeline_state.hpp
When blending a source pixel with alpha less than 1 onto a texture, we will end up having even less alpha than before.
This can lead to ugly "holes" in the overlays, especially on the edges of glyphs with smooth fonts for example.
We can fix this by only blending the RGB values while keeping the destination's alpha value.
I haven't really seen this happen in RPCS3 (yet), but it's better to be safe than sorry.
> Vk/Gl/Overlays: Do not blend the alpha channel when rendering overlays

- Utilities/bin_patch.cpp
- Utilities/ppu_patch.h
- rpcs3/Emu/CPU/Backends/AArch64/AArch64JIT.cpp
- rpcs3/Emu/CPU/Backends/AArch64/AArch64JIT.h
- rpcs3/Emu/Cell/PPUTranslator.cpp
Closes https://github.com/RPCS3/rpcs3/issues/16014
The calloc setup inserts a call to a function at the address that has the same signature as the source address from the IR POV. The calloced block isn't injected as a regular function though, we go through a thunk so it is equivalent to an indirect branch from a flow pov. Assume we don't actually know enough about the target in that situation and do not trap on return. The callee is responsible for making sure they do not spill anything to our stack, same as indirect branches.
> aarch64: Support calloc patch blocks

- BUILDING.md
- BUILDING: Bump gcc/clang versions to the ones used in rpcs3-docker
- gcc: 11 -> 13
- clang: 12 -> 17 
- BUILDING: Add qt6-svg for archlinux systems
> BUILDING: Add qt6-svg for archlinux, update gcc/clang versions

- rpcs3/Emu/Cell/Modules/cellMic.cpp
- rpcs3/Emu/Cell/Modules/cellMic.h
libmic provides three types of audio streams from the microphone input:
- DSP stream: Echo-cancelled and noise-reduced data stream (format : 32-bit float)
- RAW stream: Raw data stream directly from the device (format : 16-bit PCM)
- AUX stream: Reference data stream for echo cancellation (format : 16-bit PCM)
The PS3 captures raw data and then converts it to 32-bit float (higher precision) for digital signal processing.
The `get_dsp` function in `cellMic.cpp` has been updated to use the new `convert16BitPCMtoFloat` function when `attr_dsptype` is not `0x01`, converting the 16-bit PCM audio data to 32-bit float format before writing it to `rbuf_dsp`. If `attr_dsptype` is 
`0x01`, the original behavior of writing the raw buffer data is retained.
If there’s anything that needs to be …
> cellMic: add 16-bit PCM to 32-bit float conversion for DSP stream

- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.h
- Set config_key_role to current key after handle_item_selected
- The key was never changed if you selected different configurables in the same item. This means that all configurables used the same value list.
fixes #16037
> patch_manager: fix multiple configurable value dropdowns per patch

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
- Force reset of debugger when a different instance was booted between hide and show.
- Don't start the debug update timer in the constructor.
This caused the timer to be active even when the debugger is initially hidden.
fixes #16042
> Qt: Fix debugger state when emulation was stopped since the debugger was last shown

- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/RSX/Overlays/overlay_debug_overlay.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- Scale emulated skateboard IR input down.
This seems to improve the IR in Tony Hawk's RIDE when using a controller instead of a skateboard.
- Added an IO debug overlay that shows all the current input values of the emulated DS3 of player one.
> cellPad: scale emulated skateboard IR input down

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
- rpcs3/rpcs3qt/debugger_list.cpp
Do not use blocking-wait on IDM's mutex for the debugger as, in the case of emulation crash or simply long hold of IDM's mutex ownership, can cause the UI to deadlock.
Instead, if locking fails queue the thread-list refresh to next QT events workload. 
This is also an optimization, moving thread refresh away from the constant update timer onto the moment you click on the thread-selector combo box.
> Debugger/Qt: Non-blocking thread list refreshing

- rpcs3/rpcs3.plist.in
This is just a minor change involving how macOS/Mac OS X reports arm64-only app bundles (so not Intel only or Universal) as being iOS apps in various places like Settings and System Information unless the bundle's Info.plist explicitly specifies it is only supported on Mac OS X, in which case it will then be correctly reported as an Apple Silicon app. This PR just adds the necessary entry to rpcs3.plist.in to handle the above.
> Fix arm64 RPCS3 being reported by macOS as an iOS app

- 3rdparty/CMakeLists.txt
- 3rdparty/DetectArchitecture.cmake
Enables `USE_SYSTEM_FFMPEG=OFF` default compatibility with linux arm64
Requires the submodule update to be merged first:
https://github.com/RPCS3/ffmpeg-core/pull/4
> ffmpeg: Update submodule, supports linux arm64

- Utilities/Thread.cpp
- buildfiles/cmake/ConfigureCompiler.cmake
- rpcs3/CMakeLists.txt
- rpcs3/util/sysinfo.cpp
Gets native arm64 binaries for windows, One caveat is that ASLR is mandatory for WoA, but for whatever reason, the emulator seems to work even with dynamic base enabled. LLVM also works.
Not much testing has been done on the platform due to lack of testing hardware, but cube and the other simple demos work fine.
> arm64: Fix remaining issues for WoA

- rpcs3/Emu/Cell/Modules/cellSysutilAvc.cpp
- rpcs3/Emu/Cell/Modules/cellSysutilAvcExt.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- Fix cellSysutilAvcEnumPlayers error check
- Set log level of cellSysutilAvcExtInitOptionParam to notice
- Fix some new narrowing conversion warning
> cellSysutilAvc: Fix cellSysutilAvcEnumPlayers error check

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Emu/Io/pad_config.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.ui
- Enable squircle settings in the keyboard pad handler settings dialog
- Set all squircling defaults to 8000 except DS3. (No idea why evdev was 5000)
- Clamp all squircles to the squircle resulting from a circle of radius of 1
Fixes #16064
> input: enable squircle settings in keyboard pad handler

- rpcs3/rpcs3qt/update_manager.cpp
The other OSes are kept on V2 until V3 is fully implemented for them. The API requires all parameters (although they can be empty).
> Updater API V3 (macOS only)

- rpcs3/Emu/Cell/Modules/cellCrossController.cpp
- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
- rpcs3/Emu/Cell/Modules/cellMsgDialog.h
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/Emu/RSX/Overlays/Network/overlay_sendmessage_dialog.cpp
- rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h
- rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/rpcs3qt/save_data_dialog.cpp
- rpcs3/rpcs3qt/save_data_list_dialog.cpp
- Only abort dialogs that were actually spawned by cellMsgDialog when calling cellMsgDialogAbort
- Only close dialogs that were actually spawned by cellMsgDialog when calling cellMsgDialogClose
- Improve logging of cellSaveData overlays
This fixes the save data dialog of Oddworld: Munch's Oddysee HD.
The game keeps spamming cellMsgDialogAbort each frame.
This causes the confirmation dialog during the savedata op to close and return an error.
Fixes #16073
> Do not close savedata confirmation dialogs in cellMsgDialogAbort

- rpcs3/Emu/CPU/Backends/AArch64/AArch64Signal.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- Fix unused variable warning in MacOs Arm64 build
- Add AArch64 files to VS Project
> AArch64: fix warning, add files to VS

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.h
Instead of limiting how many SPURS threads are initialized, limit how many concurrent SPURS tasks are active at the same time.
Makes it compatible with The Last Of Us (because it uses the last thread in its group for special tasks, this should make it be able operate at times too).
May perform differently than the how it the SPURS limiter was before, needs testing.
Edit: this has effect on the SPURS limiter setting in advanced tab, when setting to other values than unlimited.
> [Testers Needed][Performance] SPU: Task-based SPURS limiter

- .ci/build-mac-arm64.sh
- .ci/build-mac.sh
- azure-pipelines.yml
- rpcs3/CMakeLists.txt
Small changes that are bundled into one PR, which fix a few Qt-related problems on macOS RPCS3 builds from my testing.
-Added a line to CMakeLists that apparently is needed to ensure Qt permission prompt handling works, fixing camera support on macOS.
-Made CI scripts for macOS also download the qtimageformats plugin, which is needed for successful icon creation when making Desktop/Launchpad shortcuts.
Should fix #14795 properly, partially deals with #16017 when it comes to shortcut icon creation failure only.
> [Misc] Fix some Qt-related issues on macOS

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_settings.cpp
- rpcs3/Emu/system_config.h
#16109 made the "Max SPURS threads" setting be based on limiting dynamic execution of SPURS tasks instead of selectively deactivating thread altogether.
This approach with few adjustments allows us to update the limit dynamically each time SPURS task wait is encountered.
> SPU: Make SPURS limit a dynamic setting

- 3rdparty/hidapi/hidapi.vcxproj
- 3rdparty/hidapi/hidapi.vcxproj.filters
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/shortcut_utils.cpp
- rpcs3/rpcs3qt/shortcut_utils.h
- rpcs3/rpcs3qt/welcome_dialog.cpp
- Shortcuts: Try to create shortcut link path if it doesn't exist
- Shortcuts/ MacOs/Arm64: Add more plist entries for shortcuts
- Adds macOs and linux hidapi files to the VisualStudio filters for improved input debugging
maybe fixes #16017
> MacOs/Arm64: Try to fix shortcuts

- rpcs3/Emu/Cell/SPUThread.cpp
Test performance regressions with #16128 please.
Also fixes #16127
> SPU: Improve SPURS Task limit algorithm

- bin/GuiConfigs/Classic (Bright).qss
Try to fix classic stylesheet after Qt 6.7.3 update.
The menu was transparent.
> Qt: Try to fix classic stylesheet after Qt 6.7.3 update

- azure-pipelines.yml
- rpcs3/rpcs3qt/shortcut_utils.cpp
Made arm64 CI build with Qt 6.7.3, and adjusted shortcut creation so that it's independent of app bundle path now (so users can move the RPCS3 bundle freely and still have their game shortcuts work fine)
> Small macOS fixes

- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/welcome_dialog.cpp
The merging of Qt 6.7.3 makes the native macOS style look good enough across Light and Dark mode that for the time being, until the RPCS3 default stylesheet can be fixed to support dark mode properly, it should be the default for this platform. Otherwise you end up with hilariously broken UI as seen currently by default: 
Versus with this PR (or manually switching to the native style currently):
The PR handles this by (on macOS only):
-Setting the default selected stylesheet choice to Native on macOS
~~-Removing broken style choices (e.g. Native styles for Windows which look awful on macOS, and the Default (Bright) style due to unreadability) so that only the Native style and other custom stylesheets are shown~~
~~-Overriding the default style if still selected with Native (affects users …
> [macOS] Force native style as macOS default

- .ci/deploy-linux.sh
Drops wayland shell integration from x64 linux appimages. Wayland is still shipping for arm64 binaries however as it is the primary compositor in use for most arm64 distros.
> linux/amd64: Fix steam deck compositor issues

- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Use vfixupimmps (avx-512 only) for spu_re_acc special cases:
Speeds up the SPU Reciprocal Accurate test from 2480ms to 2195ms
Before: 
After:
Compute frest exponent at runtime rather than using the lookup table:
Speeds up the SPU Reciprocal Accurate test (with the spu_re_acc pattern matching disabled) from 8846ms to 8264ms
Before:
After:
> SPU LLVM: Some frest optimizations

- Utilities/JITLLVM.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/16180
LLVM has no detection for Family 0x12.
I added a log which should make it easier if that happens again.
> Improve AMD cpu detection

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
* Fix a bug in PUTLLC, not releasing the thread semaphore while waiting.
* Add an experimental opportunistic thread-switch interval in which a single thread can slip in and take over execution.
> SPURS limiter tweaks

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/system_config.h
* Avoid redundant call to thread_ctrl::wait_on()
* Fix repeated waitings in PUTLLC under SPURS task notification code.
Fixes #16155
From testers:
Yakuza Dead Souls, 53.7 -> 57.0 & improved audio
> SPU: Fix "Max SPURS Threads" performance

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
This is an experimental idea. Previously SPURS task pause time was fixed at 10ms.
This would allow greater flexibility among games when using the SPURS limiter setting, improving results and consistency,
> SPU: SPURS limiter pause duration based on average task duration

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
* increase minimum wait duration.
* Use SPURS data 0x73 to tell if SPU has already been waiting or entering Idle state,
> SPU: More SPURS limiter fixes

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/pad_thread.cpp
- Fix segfault caused by lockless std::move of stick vector (copy keeps the same memory)
- Use std::array for sticks, sensors and motors. We always have the same amount of those. So using a vector has always been a bit confusing.
fixes #16207
> Fix keyboard pad handler segfault

- rpcs3/Emu/Cell/lv2/sys_spu.cpp
This syscall does not report errors for the disconnection of the event port, nor for the event port type.
> Fix sys_spu_thread_group_disconnect_event

- rpcs3/rpcs3qt/game_list.cpp
- rpcs3/rpcs3qt/game_list.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- Make sure that table columns and their actions have the same state after restoring the layout.
In theory this shouldn't be necessary, but sometimes the GuiSettings may contain different states for both.
Related to #16198
> Qt: Make sure that table columns and their actions have the same state after restoring the layout

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/GL/GLCompute.h
- rpcs3/Emu/RSX/GL/GLDMA.cpp
- rpcs3/Emu/RSX/GL/GLDMA.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/GL/glutils/buffer_object.cpp
- rpcs3/Emu/RSX/GL/glutils/buffer_object.h
- rpcs3/Emu/RSX/GL/glutils/capabilities.cpp
- rpcs3/Emu/RSX/GL/glutils/capabilities.h
- rpcs3/Emu/RSX/GL/glutils/common.h
- rpcs3/Emu/RSX/GL/glutils/ring_buffer.cpp
- rpcs3/Emu/RSX/GL/glutils/ring_buffer.h
- rpcs3/Emu/RSX/GL/upscalers/fsr1/fsr_pass.cpp
- rpcs3/Emu/RSX/Host/RSXDMAWriter.cpp
- rpcs3/Emu/RSX/Host/RSXDMAWriter.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
- rpcs3/GLGSRender.vcxproj
- rpcs3/GLGSRender.vcxproj.filters
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
Implements the host labels feature for OpenGL including dependencies such as a passthrough DMA layer simulating RSX memory views into CELL XDR memory. Only AMD supports GPU commands working on user-provided memory through the GL_AMD_pinned_memory extension so this implementation focuses on that. I have also refactored the core implementation to support other vendors in a separate update using callback hooks, but that work is still WIP.
Eventually the host labels will be decoupled from passthrough DMA support which should allow more devices to run correctly. The option will then be auto-enabled with the "Strict Rendering Mode" toggle as it offers a correct RSX label synchronization implementation.
Closes https://github.com/RPCS3/rpcs3/issues/16197
> gl: Implement host GPU labels [AMD only for now]

- rpcs3/Emu/RSX/RSXThread.cpp
Closes https://github.com/RPCS3/rpcs3/issues/16237
> rsx: Fix crash when host labels option is disabled

- Utilities/File.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_time.cpp
- rpcs3/Emu/RSX/Common/profiling_timer.hpp
- rpcs3/Emu/RSX/Common/time.hpp
- rpcs3/Emu/RSX/NV47/HW/nv406e.cpp
- rpcs3/Emu/RSX/Overlays/overlay_animated_icon.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message.cpp
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/RSXFIFO.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXZCULL.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/main.cpp
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
> Filesystem/Win32: Recreate hardlinks on fs::pending_file

- Utilities/File.cpp
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
* Filesystem fix: According to documentation, `ReplaceFile` seems to not actually replace a file, but rather its data so hard-links are preserved. Use it instead of `MoveFileEx` to preserve hardlinks 
* Exclude RSX events from VM mutex, should fix some deadlocks.
Test #16255 please.
Fixes  #16270
> Sulfuric Fixes

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
I removed the pointer bitcasts once, but this one has somehow snuck in.
> SPULLVMRecompiler: remove unnecessary bitcast

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/Cell/Modules/cellSync.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/util/atomic.cpp
- rpcs3/util/atomic.hpp
From https://github.com/RPCS3/rpcs3/pull/16272#issuecomment-2451827694
Fixes #16278
> Fixup GCM unmap event sending

- rpcs3/Emu/System.cpp
Some games are missing PIC1.PNG (the previous default) and instead were resorting to ICON0.PNG which is a low-resolution image. Do something else entirely for image picking - pick the image path between ICON0.PNG, PIC0.PNG, PIC1.PNG, PIC2.PNG and PIC3.PNG that exists and it is the largest in disk size. (assume it is the highest resolution one)
Before:
After:
> High-Resolution Game Background for loading

- rpcs3/Emu/System.cpp
Was not detecting some images for disc-based games with updates.
> Fixup Emulator::GetBackgroundPicturePath()

- rpcs3/Emu/Cell/lv2/lv2.cpp
Another attempt to address #16310 
This time because it did not terminate the thread notification list correctly.
> LV2: Fix thread notifications regression

- Utilities/lockless.h
- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/scoped_progress_dialog.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/Emu/system_progress.hpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/util/vm_native.cpp
* Fix use-after-free of m_text.c_str() by system_progress_dialog after the object of scoped_progress_dialog is freed.
> Progress Dialog: Fix recursion and concurrency use of text updates

- rpcs3/Emu/System.h
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/about_dialog.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/log_viewer.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
Both functions are discouraged by Qt for various reasons, it is of course unrealistic to replace them all
> Qt: Replace some QApplication::processEvents() and QDialog::exec()

- Utilities/File.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/main_application.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/ps_move_tracker_dialog.cpp
- rpcs3/util/types.hpp
* Deprecate more QCoreApplication::processEvents() usages. Followup to #13876.
* Fix recursion of booting inside GetBootConfirmation(). Fixes #13800 
* Fix emulator args restoration on failed Emulator::BootGame(), queue the restoration to Emulator::Kill() if emulation sop is pending.
> GUI: Fix recursion of booting inside GetBootConfirmation()

- Utilities/Thread.cpp
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
In addition to dumping the information of the crashed thread:
* Dump PPU main thread information.
* If it is a threaded SPU, dump the information of each SPU thread in the group.
> Debugger: Dump related thread information on crash

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Input/ps_move_tracker.cpp
- rpcs3/Input/ps_move_tracker.h
- (All ps move handlers) Fix ps move tracking in the following scenario:
When calling cellGemTrackHues with CELL_GEM_DONT_TRACK_HUE, the games expect cellGemGetState to return CELL_GEM_HUE_NOT_SET.
This may fix lost input during calibration in certain games, since cellGemTrackHues is being used in the same fashion before calibrations in some of the libgem examples.
- (Real ps move handler) Calculate distance from sphere to camera based on common webcam focal length and sensor width.
This may help some games to determine if the controller is near or far from the camera
> PS Move improvements

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm_reservation.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
1. Do not postpone reservation notification if there is more than one SPU waiter on this reservation, potentially resulting in a loss of CPU time.
2. Do not use local reservation time to check for notification redundancy, this was a bug as other thread may walk through the same path of updating reservation then postponing notification then no notification is made at all.
3. Notify SPU waiters while the PPU itself is idle.
May fix or aid with #16360
> CELL: Rewrite reservation notification postponing

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
Sources
https://www.psdevwiki.com/ps3/Bluray_disc
http://www.osta.org/specs/pdf/udf260.pdf
2.2.4.2 Uint32 LogicalBlockSize
> Logical Block Size will be the same as the logical sector size of the
Volume
Update dev_bdvd in compliance to the UDF file system standard.
Fixes [prototype] cutscenes and title screens, [prototype 2] cutscenes.
Closes https://github.com/RPCS3/rpcs3/issues/14013
> UDF Filesystem Block Size

- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/qt_utils.h
- rpcs3/rpcs3qt/welcome_dialog.cpp
- rpcs3/rpcs3qt/welcome_dialog.h
**BUGFIXES:**
* Fixed broken switching to dark theme in case it is selected on the initial welcome dialog. Currently, dark theme is never engaged when selected on initial welcome dialog.
* Disabled `Use Dark Theme (Can Be Configured Later)` checkbox on welcome dialog opened from `Help->View The Welcome Dialog` menu (from that menu, the checkbox has no effect on switching theme; it can be changed only from `Config->GUI` tab)
> fix dark theme switching on initial welcome dialog

- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/welcome_dialog.cpp
- rpcs3/rpcs3qt/welcome_dialog.ui
Followup of #16373 according to some received feedbacks
**IMPROVEMENTS:**
* Contextual Welcome dialog:
*  `initial welcome`: at application startup, a dialog asking to accept or reject RPCS3's usage conditions is provided. In case the reject button (`Exit`) is pressed, the application is gracefully terminated. Accept button (`Continue`) is enabled only if the agreement checkbox (`I have read the Quickstart guide`) is checked
* `standard welcome`:  welcome dialog opened from `Help` menu will show only main info and applicable settings. Dark theme, reject button and agreement checkbox are not provided
**BUGFIXES:**
* Fixed crash due to access violation on` main_window::SaveWindowState()` method in case the `gui_application::Init()` method failed (`false` was returned) to initialize some …
> Improved welcome dialog

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Input/ps_move_tracker.cpp
- rpcs3/Input/ps_move_tracker.h
- Lock tracker mutex in get_info (better data consistency)
- Ignore sporadic invalid results for a couple of frames and report the last valid result instead.
There are some possible reasons for invalid results:
We fail to find any contours
We get an unreasonably large or small sphere compared to the last result
We get an unreasonably large positional jump compared to the last result
> PS Move tracker: try to filter out noise

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Input/ps_move_calibration.cpp
- rpcs3/Input/ps_move_handler.cpp
- Fixes some calibration logging for the real ps move
- Disables gain in Fusion algorithm, which caused a constant delay and drift in the real ps move
- Improve mouse move handler orientation by using proper quaternions and adding a cone parameter that lets us easily change the range of the angle per moved pixel
- Increase the default distance of the ps move to potentially make mouse movements less crazy
> PS Move: Improve mouse handler orientation

- rpcs3/Emu/Cell/Modules/cellCamera.cpp
- rpcs3/Emu/Io/Null/null_camera_handler.h
- rpcs3/Emu/Io/camera_handler_base.h
- rpcs3/rpcs3qt/qt_camera_handler.cpp
- rpcs3/rpcs3qt/qt_camera_handler.h
- Set camera state to open on cellCameraStop (it was set to closed whenever the camera gets inactive)
- Add some more logging if the camera changes activity unexpectedly
maybe fixes #16404
> cellCamera: try to fix internal state after camera stop

- rpcs3/Emu/Cell/Modules/cellPhotoDecode.cpp
This fixes a mem access violation in Top Darts.
The game still doesn't work due to other cellGem issues.
> cellPhotoDecode: allow dev_bdvd paths

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Input/ps_move_handler.cpp
- rpcs3/Input/ps_move_handler.h
- Resets the current orientation during ps move calibration
- This is helpful when the controller drift gets too bad
> cellGem: request orientation reset during calibration

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Input/ps_move_handler.cpp
- rpcs3/Input/ps_move_handler.h
- Read magnetometer value from input report (model ZCM1 only)
- Pass magnetometer to fusion algorithm (if enabled)
- Allow cellGem to enable or disable the magnetometer
NOTE: It's not clear yet how all of these sensors are used correctly, which is noticeable by the bad tracking.
This can be the fault of the used library or simply a misconfiguration.
During testing, I sometimes had fantastic results, while having obnoxious drift on the next try.
> cellGem: add magnetometer support

- rpcs3/Emu/RSX/RSXTexture.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
Use VK_EXT_border_color_swizzle to decide whether to preswizzle the border color or not. Different vendors treat the colors differently when using a non-identity mapping.
Closes https://github.com/RPCS3/rpcs3/issues/16345
> vk: Fix border color swizzling behavior

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Input/ps_move_config.h
- rpcs3/Input/ps_move_tracker.cpp
- rpcs3/Input/ps_move_tracker.h
- rpcs3/rpcs3qt/ps_move_tracker_dialog.cpp
- Limit PS Move tracker min and max radii to 50%. It makes no sense to get larger than that.
- Fix the min anx max radii labels in the tracker dialog. They were showing a number that was way too small.
- Draw the min and max radii into the live image, including the current tracking result.
This gives additional visual feedback and helps to understand the values better.
> ps move tracker: improve min and max radii settings

- Utilities/StrFmt.cpp
- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/Cell/lv2/sys_config.cpp
- rpcs3/Emu/Cell/lv2/sys_config.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/GDB.cpp
- rpcs3/Emu/IdManager.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/util/shared_ptr.hpp
Bugs fixed:
* stx::shared_ptr::reset() was resetting pointer storage only if reference count became 0. (should always reset pointer storage)
* Fixup serialization in sys_process.
* Move destructor code in sys_config to IDM designated abort notification, operator=(thread_state), where it should be.
Do a similar thing with lv2_socket and spu_thread.
Optimization:
* atomic_ptr constructors were adding a redundant atomic_t::store instead of raw access.
flixes #16447
> util/shared_ptr.hpp: STX pointers library fixes

- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/main.cpp
Example:
```
! SYS: argc: 1, argv: 'D:\?\rpcs3.exe'
! SYS: argv_utf8: 'D:\Я\rpcs3.exe'
```
> Windows: log command line args in utf8

- rpcs3/Emu/Cell/lv2/sys_storage.cpp
- rpcs3/Emu/NP/np_contexts.cpp
- rpcs3/Emu/NP/np_contexts.h
- rpcs3/util/shared_ptr.hpp
idm remove calls shared_ptr::exchange with a null_ptr.
This calls the stored object's constructor with null args.
Let's just add an exchange overload for null_ptr
fixes #16457
fixes #16458
> Fix idm remove

- rpcs3/rpcs3qt/qt_utils.cpp
macOS uses decimal multiples (i.e. 1KB = 1000B) for filesizes system-wide, prior to this PR it could lead to RPCS3 reporting very different values for, e.g., free disk space than what macOS itself reports elsewhere.
With the PR it'll be within a few GBs of what macOS reports in Settings (the rest of the difference is 'purgeable space' nonsense).
( I have a feeling other OSes may also report decimal multiples like macOS, and that Windows may be the odd one out in reporting binary multiples. If so then the include guards could be more broadly adjusted to only use multiples of 1024 on WIN32. )
> [Minor] Report filesizes on macOS as decimal multiples

- 3rdparty/qt6.cmake
Check: https://doc.qt.io/qt-6/qcheckbox.html
QCheckBox::checkStateChanged used in
https://github.com/search?q=repo%3ARPCS3%2Frpcs3%20checkStateChanged&type=code
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/pad_motion_settings_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.cpp
> qt6: QT_MIN_VER should be 6.7 because of QCheckBox::checkStateChanged

- rpcs3/Input/sdl_pad_handler.cpp
This PR refactors logic associated with SDL gamepads so that `SDL_Quit` is called on the same thread which calls `SDL_Init` as a fix for crash at exit on macOS.
The use-after-free bug this addresses occurs because some of the `IOKit` objects created during `SDL_Init` are automatically torn down when the creating thread finishes leaving SDL with dangling pointers which may cause memory access faults during shutdown.
For me this usually results in the error/backtrace below:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x691b6edcc010)
frame #0: 0x000000018072d020 libobjc.A.dylib`objc_msgSend + 32
libobjc.A.dylib`objc_msgSend:
->  0x18072d020 <+32>: ldr    x10, [x16, #0x10]
0x18072d024 <+36>: lsr    x11, x10, #48
0x18072d028 <+40>: and …
```
> MacOS: fix for crash in SDL_Quit w/ gamepad input

- rpcs3/Emu/Cell/lv2/sys_time.cpp
> sys_time.cpp: Anti TSC measures

- rpcs3/Emu/system_progress.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- Stop batch compilation immediately on cancel
- Keep batch progress dialog open until user closed it (as originally intended)
- Fix bug: batch compilation may not always work after a game was running beforehand
> Batch compilation fixes

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- Delete settings_dialog on close (regression from "exec vs open" PR)
- Create patches path on patch update (failed if you removed the folder while in the patch manager)
closes #16492
> Some minor fixes

- 3rdparty/wolfssl/CMakeLists.txt
- rpcs3/CMakeLists.txt
I get and error when I try building on Windows.
```
[608/611] Linking CXX executable bin\rpcs3.exe
FAILED: bin/rpcs3.exe
C:\WINDOWS\system32\cmd.exe /C "cd . && C:\msys64\clang64\bin\clang++.exe -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG -gdwarf-aranges -g -mwindows  -Wl,--allow-multiple-definition -Wl,--stack -Wl,8388608 -Wl,--image-base,0x10000 @CMakeFiles\rpcs3.rsp -o bin\rpcs3.exe -Wl,--out-implib,rpcs3\librpcs3.dll.a -Wl,--major-image-version,0,--minor-image-version,0 && C:\WINDOWS\system32\cmd.exe /C "cd /D E:\build-rpcs3-clang\rpcs3 && C:\msys64\clang64\bin\cmake.exe -E copy E:/build-rpcs3-clang/3rdparty/OpenAL/openal-soft/OpenAL32.dll E:/build-rpcs3-clang/bin && C:\msys64\clang64\bin\cmake.exe -E copy_directory C:/src/rpcs3/bin/Icons E:/build-rpcs3-clang/bin/Icons && …
```
> cmake: remove "--no-quick" from windeployqt

- Utilities/bin_patch.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.h
Symbol resolver function is located on the last PPU module. Previously, its hash was dependent on its hosting module code alone. This led to potential misses of PPU code flow changes in other modules.
Include all the PPU function table addresses when hashing the last module for it.
Fixes #16517
> PPU LLVM: Function table dependent resolver hashing

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Io/Null/NullPadHandler.h
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Emu/Io/pad_config.h
- rpcs3/Emu/Io/pad_types.cpp
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/ps_move_handler.cpp
- rpcs3/Input/ps_move_handler.h
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/sdl_pad_handler.h
- rpcs3/Input/skateboard_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- rpcs3/rpcs3qt/pad_settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- Adds a new toggle for enabling/disabling the PS Move sensor orientation to the pad settings
- Adds a new button mapping for PS Move sensor orientation reset
- Adds sensor orientation support to the fake move handler (DS3/DS4/Dualsense/SDL/evdev/skateboard/custom XInput)
NOTE: sensor orientation for DS3 and any other pad handler that has less than 3 accelerometers and 3 gyros may not work correctly
> PS Move: more gyro support

- rpcs3/Emu/Io/MouseHandler.cpp
- rpcs3/Input/basic_mouse_handler.cpp
- rpcs3/Input/basic_mouse_handler.h
- rpcs3/rpcs3qt/basic_mouse_settings_dialog.cpp
- rpcs3/rpcs3qt/basic_mouse_settings_dialog.h
- Allow mapping keyboard keys to basic mouse buttons
This gives the user more freedom when trying to emulate certain devices such as the ps move
fixes #16018
> input: Allow mapping keyboard keys to basic mouse buttons

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Io/Buzz.cpp
- rpcs3/Emu/Io/GHLtar.cpp
- rpcs3/Emu/Io/GunCon3.cpp
- rpcs3/Emu/Io/TopShotElite.cpp
- rpcs3/Emu/Io/TopShotFearmaster.cpp
- rpcs3/Emu/Io/Turntable.cpp
- rpcs3/Emu/Io/emulated_pad_config.h
- rpcs3/Emu/Io/gem_config.h
- rpcs3/Emu/Io/pad_types.cpp
- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/RSX/Overlays/Trophies/overlay_trophy_list_dialog.cpp
- rpcs3/Input/raw_mouse_config.cpp
- rpcs3/Input/raw_mouse_config.h
- rpcs3/rpcs3qt/emulated_pad_settings_dialog.cpp
- rpcs3/rpcs3qt/emulated_pad_settings_dialog.h
- rpcs3/rpcs3qt/localized_emu.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/raw_mouse_settings_dialog.cpp
- Adds a new configuration dialog for "PS Move (mouse)" to the usb device settings
- You can use this to configure the previously hardcoded mouse buttons
- Combos are still possible with the extra button configuration
- Add empty dropdown item to usb device settings. This can be used to clear the button.
> ps move: allow to configure mouse move handler buttons

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/Common/surface_store.cpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/GL/GLShaderInterpreter.cpp
- rpcs3/Emu/RSX/GL/GLShaderInterpreter.h
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.h
- rpcs3/Emu/RSX/Program/FragmentProgramRegister.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramRegister.h
- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- rpcs3/Emu/RSX/Program/ProgramStateCache.h
- rpcs3/Emu/RSX/Program/RSXFragmentProgram.h
- rpcs3/Emu/RSX/Program/RSXVertexProgram.h
- rpcs3/Emu/RSX/Program/ShaderParam.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/rsx_cache.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/util/fnv_hash.hpp
Gathers aliased registers when writing to output for ROP operations. This phenomenon was observed when messing around in real hardware a while ago. Technically you can do perfectly ok rendering without ever touching the output registers if the corresponding half-registers are written to (and vice-versa).
Closes https://github.com/RPCS3/rpcs3/issues/15651
> rsx: Shader decompiler improvements

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- Update controllers at 10 Hz in separate thread instead of cellGemGetInfo
Some games don't use cellGemGetInfo, which means we had to reboot the game if the controller wasn't connected on boot.
Updating controllers outside of the cell functions fixes this problem.
> cellGem: Update controllers at 10 Hz in separate thread

- rpcs3/Input/raw_mouse_config.cpp
- rpcs3/Input/raw_mouse_config.h
- rpcs3/Input/raw_mouse_handler.cpp
- rpcs3/Input/raw_mouse_handler.h
- rpcs3/rpcs3qt/emulated_pad_settings_dialog.cpp
- rpcs3/rpcs3qt/raw_mouse_settings_dialog.cpp
- rpcs3/rpcs3qt/raw_mouse_settings_dialog.h
- Fix raw mouse button assignment.
There was a mixup between cell codes and button codes.
This caused the raw mouse settings dialog to only accept button presses that were already configured.
For example, if you had only assigned buttons 1,2 and 3, you couldn't assign buttons 4 and 5 anymore.
- Only propagate mouse events once in the raw mouse settings dialog.
It was done for all mice, which was unnecessary.
> Qt/input: fix raw mouse button assignment

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- Ignores any PS Move input while the pads are intercepted (this includes fake/mouse handlers)
This fixes an issue that causes input propagation to the game while in the home menu and other overlays
> cellGem: ignore intercepted input

- rpcs3/Emu/Cell/Modules/cellAtracXdec.cpp
- rpcs3/Emu/Cell/Modules/cellAtracXdec.h
Other PPU threads were apparently being blocked from executing while waiting on shared_mutexes/cond_variables.
Should fix #16538
> cellAtracXdec: replace shared_mutexes/cond_variables with lv2 mutexes/conds

- rpcs3/Emu/RSX/Core/RSXDrawCommands.cpp
- rpcs3/Emu/RSX/Core/RSXDrawCommands.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureMSAAOps.glsl
- rpcs3/Emu/RSX/Program/program_util.cpp
- rpcs3/Emu/RSX/Program/program_util.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKResolveHelper.h
1. Fixes some crashes when using shader interpreter.
2. Fix emulated MSAA sampling in "wrap" mode when coords have negative sign.
3. Fix out-of-bounds write in MSAA resolve pass that can cause GPU crash.
Closes https://github.com/RPCS3/rpcs3/issues/16541
Closes https://github.com/RPCS3/rpcs3/issues/16539
TODO:
> rsx: Shader and MSAA fixes

- rpcs3/Emu/RSX/rsx_cache.h
Correct shaders are cached but the broken loading makes it so that most shaders will fail the comparison later and force a recompilation anyway.
Closes https://github.com/RPCS3/rpcs3/issues/16565
Closes https://github.com/RPCS3/rpcs3/issues/16562
> rsx: Fix shader cache loading

- rpcs3/Emu/Io/MouseHandler.cpp
- rpcs3/Emu/Io/MouseHandler.h
- rpcs3/Input/basic_mouse_handler.cpp
- rpcs3/Input/basic_mouse_handler.h
- Issue a basic mouse move event on window leave (moving the mouse out of the window)
- This may help with moving the mouse to the screen borders in windowed mode
> input: issue basic mouse move event on window leave

- rpcs3/Emu/Cell/Modules/sys_prx_.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.h
Implements 2 sys_prx features:
* sys_prx_get_module_id_by_name, self explanatory
* version 2 of sys_prx_module_info, which includes addresses to the import/export stub tables
> sys_prx: implement get_module_id_by_name, module_info_v2

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/Common/simple_array.hpp
- rpcs3/Emu/RSX/Program/GLSLInterpreter/FragmentInterpreter.glsl
- rpcs3/Emu/RSX/VK/VKCommonPipelineLayout.cpp
- rpcs3/Emu/RSX/VK/VKCommonPipelineLayout.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.h
- rpcs3/VKGSRender.vcxproj
- rpcs3/VKGSRender.vcxproj.filters
1. Reworks descriptor binding layout so that we can reuse the same code for both main RSX shaders and the interpreter.
2. Fixes a texturing regression in the interpreter that caused most textures to be black.
Closes https://github.com/RPCS3/rpcs3/issues/16374
> rsx: Shader interpreter improvements

- 3rdparty/CMakeLists.txt
Compiling on older versions fails due to std::string_view functions not being available.
> Update minimum pugixml version to 1.15

- rpcs3/Emu/Io/pad_config.cpp
- rpcs3/Emu/Io/pad_config.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/ps_move_handler.cpp
- rpcs3/Input/sdl_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- rpcs3/rpcs3qt/pad_settings_dialog.ui
- Replaces the vibration toggles with vibration multipliers (0-200%)
- Fixes a crash in the pad settings dialog that happens when you close the dialog right after triggering a vibration
fixes #16579
> input: add vibration multiplier

- rpcs3/Input/gui_pad_thread.cpp
- rpcs3/Input/gui_pad_thread.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- Reset gui pad thread when closing pad settings in order to apply the new settings
- Log gui pad thread pad configs
fixes #16595
> Qt/input: reset gui pad thread when closing pad settings

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- cellGem: mark fake/mouse device as not visible at the screen borders
- Decrease log level of some new "already exists" log messages regarding new config file move
This may fix issues with moving the ps move out of screen when using a mouse, gun or controller.
May fix #15705
> cellGem: mark fake/mouse device as not visible at the screen borders

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.h
- rpcs3/Emu/Io/Buzz.cpp
- rpcs3/Emu/Io/Buzz.h
- rpcs3/Emu/Io/Dimensions.cpp
- rpcs3/Emu/Io/Dimensions.h
- rpcs3/Emu/Io/GHLtar.cpp
- rpcs3/Emu/Io/GHLtar.h
- rpcs3/Emu/Io/Infinity.cpp
- rpcs3/Emu/Io/Infinity.h
- rpcs3/Emu/Io/Skylander.cpp
- rpcs3/Emu/Io/Skylander.h
- rpcs3/Emu/Io/Turntable.cpp
- rpcs3/Emu/Io/Turntable.h
- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/Io/usio.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
Implement hotplug using hotplug events where supported, and a periodic scan where hotplug isn't available
For windows, the periodic scan in some scenarios had negative effects on controller responsiveness, as `libusb_get_device_list` can take a few seconds on some machines, so I've opted to instead hook into the `nativeEventFilter` and implement a native hotplug myself.
* migrated from lambda calls to const whitelist structure, and have merged the emulation aspect into this
* Use a combination of the device port, address and vid and pid for differentiating devices, as suggested by some sample code from libusb
* Implemented native hotplug with a small delay as usb hotplug events tend to arrive before devices are fully enumerated
* If multiple LDDs match a device, only the first LDD wins …
> libusb: support hotplug

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/savestate_manager_dialog.cpp
- rpcs3/rpcs3qt/savestate_manager_dialog.h
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- Adds a savestate manager dialog (manage -> savestates)
- Allows to view, delete and boot savestates per game
> Qt: add savestate manager dialog

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
Fixes a regression after the hotplug changes, that was stopping emulated devices from working
> sys_usbd: Fix emulated devices not being created without a physical device

- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
The main window does not exist if we boot with no-gui.
Needs testing if USB hotplug works on windows with no-gui.
fixes #16612
> Qt: Fix device notification registration segfault

- Utilities/JIT.h
- Utilities/JITASM.cpp
- Utilities/JITLLVM.cpp
- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/Modules/cellCamera.cpp
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/Cell/lv2/sys_uart.cpp
- rpcs3/Emu/GDB.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/util/vm_native.cpp
PPU LLVM's memory manager was not able to handle more than 512MB of data, but at same time instead of reporting an error on outage it reused memory buffers. This resulted in corrupted PPU LLVM cache files for affected titles.
Fixes PES games with their humongous executable file.
Fixes #11469 (you need to remove broken PPU LLVM and SPU LLVM cache)
* Reduces RPCS3 RAM memory consumption by 100MB-300MB ingame and more than twice this amount during PPU LLVM compilation. This is because PPU analyzer information is stored much more efficiently, size of data members has been reduced and PPU LLVM compilation no longer makes copies of this memory.
**Before (Demon's Souls)**
**After - Around 160MB reduction in memory!**
> PPU LLVM: Memory Consumption Enhancements

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- Fixes recent savestate freeze checkbox
- Fixes recent savestate tooltips
- Fixes recent savestate shortcuts (Use Alt+N)
- Add path to recent game/savestate tooltips
fixes #16609
> Fix recent savestates menu

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/system_config.h
Use a 512bit wide "xorsum" (even for machines with 128b and 256b simd) hash in place of a full comparison for SPU verification. In theory, hash collision is nearly impossible here, even though a human could create two matching hashes by hand pretty easily, but luckily for us, all PS3 programs were written a long time ago. 
With a true random distribution of numbers, the chance of collision should be astronomically small, (1 in 2^512?) but I'm not sure how the chance changes when we change from true random to valid SPU opcodes. Either way, I don't think that collisions are likely, and the performance uplift is real. Just to be safe, the xorsum path is only taken if there are atleast 3 64byte blocks to hash.
The full_width_avx512 option is also removed, since even on CPUs which experienced …
> SPU LLVM: Use 512bit xorsum for SPU verification

- rpcs3/Emu/Cell/PPUAnalyser.cpp
`fmap` was growing as the loop proceeded, resulting in squared number of iterations for affected games. Previously `fmap` was copied on loop beginning to avoid this issue, but instead I choose to iterate by key values instead of true iterators to avoid the RAM overload of copying it.
Fixes #16624
> PPU Analyzer: Fix per-instruction code submission

- rpcs3/Emu/Cell/lv2/sys_time.cpp
- rpcs3/util/sysinfo.cpp
> Enable Time-based TSC for non-Ryzen CPUs

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Use a stupid simple checksum instead of the xorsum for spu verification. The xorsum has issues with repeating data.
This fixes crashes in GTAV.
Please test other games.
Fixes: https://github.com/RPCS3/rpcs3/issues/16647
Note: Might be slightly slower for 512b machines for now, a future PR will add 2 dependency chains to fix this issue, if the checksum works well.
> SPU LLVM: Replace xorsum with simple checksum

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
Gets rid of corrupted visuals when running in hybrid mode (async recompiler + interpreter). This makes the "switching" imperceptible in most games and drastly improves usability of the interpreter.
Technically this is a regression, but it crept in slowly over many changes.
Closes https://github.com/RPCS3/rpcs3/issues/15851
> rsx: Fix graphics corruption when switching between shader interpreter and recompiler at runtime

- rpcs3/util/sysinfo.cpp
1. TSC is force-enabled on windows where it is known to work correctly. Typically laptop firmware writers give windows special treatment.
2. On linux, check if the kernel thinks the TSC is usable. If it is marked as available, use it.
Closes https://github.com/RPCS3/rpcs3/issues/16643
Closes https://github.com/RPCS3/rpcs3/issues/16604
Closes https://github.com/RPCS3/rpcs3/issues/16545
> Re-enable TSC on ryzen CPUs

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- cellGemPrepareCamera: Deactivate some camera attributes (it's what's actually happening on real hardware)
- cellGemPrepareCamera: Set some other camera attributes (kinda RE'd, but no 100% accurately)
This reduces a lot of cellGemPrepareCamera spam in combination with cellCameraGetAttribute in LBP3.
The game calls cellGemPrepareCamera and checks with cellCameraGetAttribute if one of the attributes is disabled.
The game repeats this indefinitely if the attribute is not disabled as expected.
I don't know if this improves performance or if this fixes any other camera issues in the game.
> cellGemPrepareCamera: reduce cellCamera log spam by setting some camera features

- rpcs3/Emu/Cell/Modules/cellMusic.cpp
- rpcs3/Emu/Cell/Modules/cellMusic.h
- rpcs3/Emu/Cell/Modules/cellMusicDecode.cpp
- rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp
- rpcs3/Emu/Cell/Modules/cellRtc.cpp
- rpcs3/rpcs3qt/qt_music_handler.cpp
- rpcs3/rpcs3qt/qt_music_handler.h
- Fix volume of custom music (this was always either on 0% or 100% due to a wrong volume range passed to the player)
- Mark playlists as valid as soon as the playlist is set (this was previously only done after loading them from file)
- Always provide the whole playlist when a track is selected in an overlay dialog (we previously only ever returned the track as a single song playlist)
- Silence some cellRtc log spam
This fixes the music player in LBP3. I hope this doesn't break any other games.
NOTE: rewind doesn't work because Qt doesn't support it. So don't complain about that xD
fixes #16649
> cellMusic: fix some custom music issues

- rpcs3/Emu/RSX/RSXThread.cpp
Omit shadowmap passes which just introduce large square dimensions to the tracker.
> rsx: Fix internal res tracking

- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- rpcs3/Emu/RSX/Program/ProgramStateCache.h
Raises FPS from ~180 to ~200 in Ninja Gaiden Sigma
It's difficult to verify how good the hashing is myself, so please test with a lot of games, checking for any visual issues and performance improvements. I do think that simpler hashes should be sufficient when we are hashing valid opcodes instead of random data though.
Before:
After:
Note: The functions are small enough now that the compiler decided to inline them. In the before screenshot `get_vertex_program_ucode_hash` is using 1.65% of cpu time. In the after screenshot, the function is inlined into `vertex_program_storage_hash` and the combined code is only taking up 0.56% of cpu time.
NoteNote: I tested without the rotation, and none of my games had issues, but I was nervous about instructions getting swapped around, so I added the …
> RSX: Use checksum with rotated inputs for shader hashing instead of FNV

- .ci/build-linux-aarch64.sh
- .ci/setup-windows.sh
- .github/workflows/rpcs3.yml
Cache is supported on the penguin
Cold: https://github.com/illusion0001/rpcs3/actions/runs/10871089443/attempts/1
Warm: https://github.com/illusion0001/rpcs3/actions/runs/10871089443
Plans for later, build in clang and gcc on Windows and OSX and releases to upload repo
> GitHub Actions CI Port

- .github/workflows/rpcs3.yml
`windows-latest` defaults to `windows-2022` runner, the benefits of updating the runner are to be able to use newer packages like the Windows SDK.
- windows-2022 = 10.0.20348
- windows-2025 = 10.0.26100
> CI: Use windows-2025 Runner

- rpcs3/Emu/Cell/Modules/cellMic.cpp
- rpcs3/Emu/Cell/Modules/cellMic.h
Attempt to calculate a reasonable decibel value (40 to 90 dB) for a microphones audio level.
Allows voice chat to work in Metal Gear Online, which expects values between 45 and 72 depending on the player's game settings. MGO2 only allows 2 players to speak at any given time, so hardcoding a value from within that range wasn't a viable solution.
> cellMic: Implement SIGSTATE_MICENG

- rpcs3/Crypto/unpkg.cpp
- rpcs3/Crypto/unpkg.h
Add support for NPDRM pkg maker version 0x1500, which seems to be the common maker of IDU packages.
I have added an additional check for empty QA Digest which seems to be a second distinguishing difference.
Closes https://github.com/RPCS3/rpcs3/pull/16730
> unpkg: Add support for IDU packages

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
When one operand is a constant, finite number, clamp the other input and directly compare.
Ideally compiles down to just two instructions.
The nonzero optimization is removed since it's already handled by the finite number optimization.
> SPU LLVM: Small FCGT optimization

- Utilities/BitField.h
- Utilities/File.h
- Utilities/StrFmt.h
- Utilities/bit_set.h
- rpcs3/Emu/CPU/CPUDisAsm.h
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/ErrorCodes.h
- rpcs3/Emu/Cell/Modules/cellSail.h
- rpcs3/Emu/Cell/Modules/sceNpTrophy.h
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/IdManager.h
- rpcs3/Emu/Memory/vm_ptr.h
- rpcs3/Emu/Memory/vm_ref.h
- rpcs3/Emu/RSX/Common/expected.hpp
- rpcs3/util/asm.hpp
- rpcs3/util/atomic.hpp
- rpcs3/util/endian.hpp
- rpcs3/util/fixed_typemap.hpp
- rpcs3/util/fnv_hash.hpp
- rpcs3/util/serialization.hpp
- rpcs3/util/to_endian.hpp
- rpcs3/util/types.hpp
I was learning C++ concepts and decided to replace usages of `std::enable_if` and `std::void_t` with concepts.
> use concepts instead of std::enable_if

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/Common/texture_cache_types.cpp
- rpcs3/Emu/RSX/Common/texture_cache_types.h
- rpcs3/Emu/RSX/NV47/HW/nv3089.cpp
- rpcs3/Emu/RSX/rsx_utils.cpp
- rpcs3/Emu/RSX/rsx_utils.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- move texture_cache_types implementation to cpp (removes system_config header in header dependency)
- Make some stuff const
> move texture_cache_types implementation to cpp

- .cirrus.yml
- .github/workflows/rpcs3.yml
PR is draft until RPCS3_TOKEN has been set.
> Deploy aarch64 builds via via GitHub Actions instead of Cirrus

- rpcs3/Crypto/decrypt_binaries.cpp
- rpcs3/Crypto/key_vault.cpp
- rpcs3/Crypto/key_vault.h
- rpcs3/Crypto/unself.cpp
- rpcs3/Crypto/unself.h
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.h
- rpcs3/Emu/System.cpp
- rpcs3/util/serialization.hpp
This pull request implements initial import / firmware functions caller analysis.
While many uses are now possible, I implemented one use for Metal Gear Solid 4. 
The use here is to statically analyse the firmware calls to sceNpDrm which contain the key in passed arguments to the function to decrypt its executable.
This is required in order to precompile its PPU LLVM cache properly for all its executables.
Implements #16748  
Fixes #12320
> PPU Analyzer, MGS4: Firmware/import caller analysis and KLIC finding pass

- .ci/deploy-windows.sh
- .ci/setup-windows.sh
- .github/workflows/rpcs3.yml
- 3rdparty/libpng/libpng.vcxproj
- 3rdparty/zlib/zlib.vcxproj
- azure-pipelines.yml
- buildfiles/msvc/ci_no_debug_info.targets
This properly caches our Windows builds using ccache, instead of just caching dependencies, this will drastically reduce build times on a warm cache.
Ccache doesn't support the /Zi flag, so I added a .targets file that removes it from the CI build. We don't ship .pdbs in our official releases so this won't change anything for users or developers.
> Use ccache on Windows CI build

- rpcs3/Emu/Cell/PPUThread.cpp
Improves on: https://github.com/RPCS3/rpcs3/issues/12320
Also fixes an issue where the progress bar was not updating correctly when a self failed to decrypt.
Possible solutions to precompile encrypted modules:
1. Get the key at runtime df0d4a458863b1530b08e1b289971c173bcda066
2. Use pattern matching 77812a7ad7f47fd4d524969c12442bff9f0a9f8b
3. module hash / key or elf address lookup (this is probably the best solution for targeting a handful of games where it would matter)
> PPU: Report encrypted modules with KLIC in main file, opportunistic compilation at exit-spawn

- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- Place avx-512 function attributes in their own functions
Can you find the AVX-512 instruction that was not guarded by utils::has_avx512_icl()?
It's this one:
Not sure why the compiler even opted to emit this, since the AVX form will have a smaller encoding.
Fixes: https://github.com/RPCS3/rpcs3/issues/16792, https://github.com/RPCS3/rpcs3/issues/16796
> RSX: Fix issue where linux builds could hit illegal instruction on machines without AVX-512

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/game_list_base.cpp
- rpcs3/rpcs3qt/game_list_base.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_table.cpp
- rpcs3/rpcs3qt/gui_game_info.cpp
- rpcs3/rpcs3qt/gui_game_info.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.h
- Refactor some code to remove some code duplication
- Only consider bootable games in patch manager
This should fix some issues with showing wrong versions when selecting "show owned games only"
> Qt/Patches: only consider bootable games in patch manager dialog

- rpcs3/Emu/RSX/VK/VKHelpers.cpp
Not required for most drivers and has a measurable performance impact.
Fixes a minor performance regression introduced in OGL MSAA PR.
> vk: Do not force strict query scopes by default

- rpcs3/Emu/RSX/RSXFIFO.cpp
If memory was invalid on the next 4 pages, std::span was referencing invalid memory which is undefined behaviour.
Clamp it to the current page or onto the next if it is valid too.
> RSX: Fix UB in FIFO_control::get_current_arg_ptr()

- rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Fixes value propagation in loops for the use of SPU pattern analyzer.
> @elad335 SPU Analyzer: Fix for value propagation

- rpcs3/Emu/RSX/Common/texture_cache.h
The combination of flags observed during debugging (thanks @digant73) really only means one thing - we have a stale pointer. Normally changes in surface cache invalidate samplers, but with all the optimizations done over the years there is a chance that we're holding on to some reference to a surface that was last seen a long time ago (in computing terms, so like a half a second lol).
In such a case, the dynamic cast will fail, and the surface cache will deny knowledge of the image despite the fact that we have a fully compliant descriptor. Simply treat the descriptor as invalid at that point and redo the upload.
Fixes https://github.com/RPCS3/rpcs3/issues/14809
> rsx: Reupload surface if the surface cache denies knowledge of it

- rpcs3/main.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- Hide legacy shader mode interpreter_only unless it is selected or the debug mode is active
- Fix some warning in main.cpp
Follow up to #16805
> Qt: Hide legacy shader mode interpreter_only unless it is selected or the debug mode is active

- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- rpcs3/Emu/RSX/Program/ProgramStateCache.h
- rpcs3/Emu/RSX/RSXThread.cpp
It's a simple op which just checks if the static properties have changed. This really only applies to textures because they can be evaluated very late and fail to trigger invalidation during prefetch.
Fixes https://github.com/RPCS3/rpcs3/issues/16856
> rsx: Invalidate program cache hint if the current vertex or fragment program is re-evaluated

- .cirrus.yml
Followup to #16701 and prevent CI breakage in ~3 months.
```
$ c++ --version
FreeBSD clang version 19.1.7 (https://github.com/llvm/llvm-project.git llvmorg-19.1.7-0-gcd708029e0b2)
Target: x86_64-unknown-freebsd13.5
Thread model: posix
InstalledDir: /usr/bin
```
> CI: upgrade FreeBSD to 13.5

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
This fixes a crash inside libusb for users who would fail libusb_init* (e.g. running in a mount namespace and not any using USB peripherals, so not giving the container direct USB access).
We also might as well not call deregister if register failed (but doing so wouldn't cause problems in this case).
> sys_usbd: Fix null pointer deref on destruction

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Fixes broken graphics in god of war ascension when AVX-512 was enabled.
Fixes: https://github.com/RPCS3/rpcs3/issues/16770
> SPU LLVM: Preserve sign on inf to NaN conversion in spu_re_acc with vfixupimmps

- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/rpcs3qt/game_compatibility.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- Uses game icons in shader compile dialog based on current config language
- Uses game title in game window based on current config language
- Uses game icons in GUI dialogs based on current UI language
- Uses game titles in GUI dialogs based on current UI language
fixes #16865
> Qt: Use localized game icons and titles

- rpcs3/rpcs3qt/game_list_base.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_grid.cpp
- rpcs3/rpcs3qt/game_list_table.cpp
- rpcs3/rpcs3qt/gui_game_info.h
- Qt: fix code style of some variables
- Qt: Do not use gamedata icon if game has custom icon
- Qt/optimization: Don't look for PAM files if the game has a hover gif
- Qt: Simplify hover movie code
Fixes #16879
> Qt: Fix custom icons if disc game gamedata icons are present

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
The vperm2b function uses vperm2b256to128 when it's ideal, so there's no reason to use it outside. I missed these earlier when replacing them with vperm2b. Oops!
> SPU LLVM: Don't use vperm2b256to128 outside of CPUTranslator.h

- rpcs3/rpcs3qt/game_list_frame.cpp
- Qt: fix custom icons when "Prefer game data icons" is set
fixes #16927
> Qt: fix custom icons when "Prefer game data icons" is set

- rpcs3/CMakeLists.txt
- rpcs3/rpcs3.vcxproj
- Windows/Qt: do not deploy dx and ffmpeg libs
Since Qt 6, windeployqt was unnecessarily deploying
- avcodec-61.dll
- avformat-61.dll
- avutil-59.dll
- dxcompiler.dll
- dxil.dll
> Windows/Qt: do not deploy dx and ffmpeg libs

- .github/workflows/rpcs3.yml
- azure-pipelines.yml
- buildfiles/msvc/ci_only.targets
- buildfiles/msvc/rpcs3_release.props
- VS/MSVC: Move LTCG and GL to CI only
This was taking too long on my local builds after simple code changes.
> VS/MSVC: Move LTCG and GL to CI only

- rpcs3/Emu/RSX/Overlays/FriendsList/overlay_friends_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/FriendsList/overlay_friends_list_dialog.h
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_main_menu.cpp
- overlays: hide friends list in home menu if rpcn is not configured
related to #16918
> overlays: hide friends list in home menu if rpcn is not configured

- rpcs3/Crypto/unpkg.cpp
#16739 Removed the ability to install PSP and Vita packages because it stopped using the PSP PKG key for getting the file entries. This just restores the line to the way it was before that PR, but shouldn't break IDU packages.
> unpkg: Restore support for PSP/Vita packages

- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
cellSpursAddUrgentCommand searches in 4 slots for an empty slot to put the command at.
At first, it seems to do so unordered.
Meanwhile, on SPU side, it expects an order between all the commands because it pops them it in FIFO manner.
Not keeping track of how many commands are queued in total.
This is the SPU function resposible:
[SPU_unqueue.txt](https://github.com/user-attachments/files/19407636/SPU_unqueue.txt.txt)
After second observation of cellSpursAddUrgentCommand, something odd takes places here.
Usually, reservation loops are individual and are expected to be closed without any changes of the previous loop affected by the proceeding one.
But in this case, after a single failure, the entire operation is reset, a loop of 4 reservation operations suddenly is reset completely.
This …
> PPU/cellSpurs: MGS4: Fix cellSpursAddUrgentCommand race condition

- rpcs3/rpcs3qt/game_list.cpp
- rpcs3/rpcs3qt/game_list.h
- rpcs3/rpcs3qt/game_list_base.cpp
- rpcs3/rpcs3qt/game_list_base.h
- rpcs3/rpcs3qt/game_list_grid.cpp
- rpcs3/rpcs3qt/game_list_grid.h
- rpcs3/rpcs3qt/game_list_table.cpp
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/save_manager_dialog.h
- rpcs3/rpcs3qt/savestate_manager_dialog.h
- Play ICON1.PAM in the save data manager when hovering over the icon
NOTE: I'll probably implement playing the video in the big icon in the details in a follow up PR
> Qt: Play ICON1.PAM in save data manager when hovering over the icon

- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/game_list_base.cpp
- rpcs3/rpcs3qt/game_list_grid.cpp
- rpcs3/rpcs3qt/game_list_table.cpp
- rpcs3/rpcs3qt/movie_item_base.cpp
- rpcs3/rpcs3qt/movie_item_base.h
- rpcs3/rpcs3qt/qt_video_source.cpp
- rpcs3/rpcs3qt/qt_video_source.h
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/save_manager_dialog.h
- rpcs3/rpcs3qt/video_label.cpp
- rpcs3/rpcs3qt/video_label.h
- rpcs3/util/video_source.h
- Play ICON1.PAM in save data manager details view on mouse hover
- Move movie player capabilities from movie_item_base into new qt_video_source
> Qt: Play ICON1.PAM in save data manager details view

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Input/pad_thread.cpp
- Disable pad vibration after no new data was sent for 3 seconds. This is supposedly how the lib does it.
> input: disable pad vibration after no new data was sent for 3 seconds

- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/shortcut_settings.cpp
- Disable shortcuts completely if "disable keyboard hotkeys" is enabled
- Add Ctrl+ to audio hotkey defaults (so it's now Ctrl + Shift + M/+/-)
- Update discord-rpc for CMake 4.0
Note: QShortcuts basically prevent the event propagation if activated, so I couldn't find out how to allow both normal input + hotkey input at the same time.
fixes #16969
fixes #16673
> Qt/Input: Hotkey fixes

- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
The previous code targets x86's behaviour of `minps` and `maxps` instructions, in which if one of the operands is a NaN, the second argument is returned.
What's is expected on PowerPC (PPU) is that if any of the arguments is NaN, a QNaN would be returned.
The bug was that the codegen of VMAXFP does not return a NaN if only either of its arguments is a NaN.
Fixes https://github.com/RPCS3/rpcs3/issues/16236
PPU LLVM cache needs to be cleared for testing.
> PPU LLVM: Fix VMAXFP and VMINFP

- .ci/deploy-linux.sh
AppImage size savings:
- **x86-64:** 106.5 MiB -> 100.6 MiB
- **aarch64:** 88.6 MiB -> 82.6 MiB
> linux: Do not bundle unused Qt6 libraries, reduce AppImage size

- rpcs3/rpcs3qt/richtext_item_delegate.h
Fixes #16895 by undoing the workaround in #12692 which actually introduces this issue
I don't think this workaround is required anymore. We used Qt 5.15.2 back then, and now we're on Qt 6.8.3. Testing locally on both local build and AppImage allows the entries to display properly.
AppImage
Local
@RipleyTom to verify if it still displays fine without the workaround
Tested on KDE Plasma 6.3.3.
> Qt: Fix multi package install dialog on Linux

- rpcs3/Emu/RSX/NV47/FW/draw_call.cpp
- rpcs3/Emu/RSX/NV47/FW/draw_call.hpp
We tend to have so many more draw barriers per set that checking them all slows everything down by a lot.
Also moves the now-optimized barrier checks up-top as that is likely to kill the remaining checks trivially.
- Significant drop in "RSX load" metric observed in draw-call heavy titles (-20% in the extreme case)
- Partially addresses performance regression noted in https://github.com/RPCS3/rpcs3/issues/16958
- Relates to https://github.com/RPCS3/rpcs3/issues/16468
> rsx: Track command barrier types during recording for faster instancing compatibility checks

- rpcs3/rpcs3qt/game_list_delegate.cpp
- Fix visibility check of table widget items
- Fixes icon loading in some game tables in certain styles
In certain styles, only the top and bottom icons were being loaded, e.g. in the save manager game list.
The intersection check of the visible region did not work for some reason.
There's a bug on Qt side that creates a set of smaller rects that don't really fill the entire region.
So let's just use the bounding rect of the region instead.
> Qt: fix visibility check of table widget items

- rpcs3/Emu/RSX/VK/VKResolveHelper.h
Issue discovered by @digant73 (see https://github.com/RPCS3/rpcs3/issues/16916#issuecomment-2794924520)
The issue only occurs on the NVIDIA-specific workaround for stencil export hence the variability in reproducing.
Closes https://github.com/RPCS3/rpcs3/issues/16916
> vk: Fix typo in NVIDIA-specific stencil unresolve path

- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/Emu/Cell/Modules/sceNpTrophy.h
* Raise callbacks after the PPU has returned from the funtion.
* Make the wait between callbacks manadatory with minimum waiting time, even if the previous callback is handled.
* Add more SCE_NP_TROPHY_STATUS_PROCESSING_FINALIZE steps.
~~- [ ] TODO: Test wait times against real hw.~~
> sceNpTrophyRegisterContext: Send signals asynchronously

- rpcs3/rpcs3qt/qt_video_source.cpp
- Fix game list image reset after a movie was stopped
- Update icon when stopping the movie from the game list
- This fixes a regression that appeared after updating to Qt 6.9.0.
They seem to have removed a signal that was conveniently sent before whenever a movie stopped.
> Qt: fix game list image reset after a movie was stopped

- rpcs3/rpcs3qt/game_list_grid.cpp
- rpcs3/rpcs3qt/game_list_table.cpp
- rpcs3/rpcs3qt/qt_video_source.cpp
- rpcs3/rpcs3qt/qt_video_source.h
- Do not set an icon if it's null. This happens because we save memory by clearing the pixmap of non-movie items.
Also don't stop the movie here, as it should be stopped already anyway.
- Use unique_ptr in qt_video_source
- Use image_change_callback function to ensure the member is valid
fixes #17053
> Qt: Fix gamelist icons vanishing after stopping a movie

- rpcs3/rpcs3qt/vfs_dialog_path_widget.cpp
- rpcs3/rpcs3qt/vfs_dialog_path_widget.h
- Add checkboxes to the VFS list to make selection more user friendly
- This properly shows which path is currently selected
> Qt: Add checkboxes to VFS list to make selection more user friendly

- rpcs3/Crypto/unself.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.h
* Implement sys_spu_image_open_by_fd syscall.
* Use the vm::user64k memory allocations for LV2 SPU image loading type. from reversing it is the same allocation type as PRX.
* Allow unsigned SPU ELF, as  long as the main PPU executable is also unsigned. (I don't allow it regardless due to accuracy reasons)
Fixes spu_alu test from https://github.com/RPCS3/ps3autotests, although I should also fix the test to not use the syscall. Instead, loading the ELF from memory which would allow it be unsigned and run on real PS3 as well.
> Implement sys_spu_image_open_by_fd, fix sys_spu_image_open

- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Memory/vm.h
Specifically: `STVX`, `STVXL`, `STDBRX`, `STWBRX`, `STFSX`, `STFSUX`, `STFDX`, `STFDUX`, `STHBRX`, `STFS`, `STFSU`, `STFD`, `STFDU`.
Closes https://github.com/RPCS3/rpcs3/issues/17062.
Open to feedback regarding the chosen approach with the added `vm::write` func.
> PPU: Fix memory write breakpoints for 13 instructions

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/Emu/RSX/Common/ring_buffer_helper.h
- rpcs3/Emu/RSX/NV47/FW/draw_call.cpp
- rpcs3/Emu/RSX/NV47/FW/draw_call.hpp
- rpcs3/Emu/RSX/VK/VKDataHeapManager.cpp
- rpcs3/Emu/RSX/VK/VKDataHeapManager.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKFrameContextManager.cpp
- rpcs3/Emu/RSX/VK/VKFrameContextManager.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKProcTable.h
- rpcs3/Emu/RSX/VK/VKRenderPass.cpp
- rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
- rpcs3/Emu/RSX/VK/VulkanAPI.cpp
- rpcs3/Emu/RSX/VK/VulkanAPI.h
- rpcs3/Emu/RSX/VK/vkutils/buffer_object.cpp
- rpcs3/Emu/RSX/VK/vkutils/data_heap.cpp
- rpcs3/Emu/RSX/VK/vkutils/data_heap.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/shared.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
- rpcs3/VKGSRender.vcxproj
- rpcs3/VKGSRender.vcxproj.filters
This is a collection of minor optimizations and reworks that were done over the past few months. Should result in a minor performance boost in most RSX-limited scenarios when using Vulkan.
> vk: Forgotten improvements

- rpcs3/Crypto/unself.cpp
In 7de2869a5364ca5d48ea0a2212621adc0e20bc2f this was changed to be a bit more safe, however it was reading from offset 0 instead of where the real elf started, meaning every debug self would just fail to load immediately.
I've fixed it to actually function properly
> Fix debug self always reporting as "not an elf"

- rpcs3/Emu/RSX/Common/ring_buffer_helper.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
1. Proper initialize EXT_multidraw extension for vulkan
2. Fix a bug in the ringbuffer static allocator where the result could point out of bounds
3. Do not delete vertex attribute buffer views when they are full. Always use the GC instead!
Closes https://github.com/RPCS3/rpcs3/issues/17086
Somewhat relates to https://github.com/RPCS3/rpcs3/issues/12585
> vk: Minor fixes and improvements

- rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.cpp
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.h
- rpcs3/Emu/NP/ip_address.cpp
- rpcs3/Emu/NP/rpcn_client.cpp
- rpcs3/Emu/NP/rpcn_config.cpp
- rpcs3/Emu/NP/rpcn_config.h
- rpcs3/rpcs3qt/rpcn_settings_dialog.cpp
Simplify IPv6 detection to be only in one function which removes the need to store if the socket is ipv6 in structures, either it's supported and all p2p sockets are ipv6 or none of them are.
Use g_fxo instead of a singleton so the detection is reset when a game restarts.
Fixes a bug where IPv6 was available but connecting to a RPCN server that only had an IPv4 it got forcefully disabled.
> Fix IPv6 support detection

- .ci/build-linux-aarch64.sh
- .ci/build-linux.sh
- buildfiles/cmake/ConfigureCompiler.cmake
Only use -fuse-ld in linking steps, also adds "-Wl,-O2" for all builds.
> Avoid passing -fuse-ld to non-linking step

- rpcs3/rpcs3qt/breakpoint_handler.cpp
- rpcs3/rpcs3qt/breakpoint_handler.h
Compiling with `HAS_MEMORY_BREAKPOINTS`  incurs a massive performance penalty while running in PPU interpreter mode. This caused the game I was testing to take 2x to 3x longer to even reach the point where I need to set a breakpoint. This made debugging quite a chore, and I was often switching between builds even when using interpreter mode in both simply because of how long it took. 
This PR speeds up RPCS3 while no breakpoints are set by bypassing the mutex locking in favor of an atomic check.
> PPU: HasBreakpoint fast path when empty

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
Fixes  #17106
* Allow 16-byte aligned images, 16-byte alignment is the minimum required alignment for SPU transfers.
* Fix range lookups.
* Fix SPU code validation that its true location and bounds are unknown. 
* Fix embedded SPU image size estimation, this allows to find nearby images which were skipped, allowing more SPU programs to be precompiled!
**1853 -> 2356  SPU modules (27% improvement)**
> Embedded SPU Image Search Fixes, Improve SPU Code Precompilation 

- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.h
Test with #17114 
The game seems to be doing recursion on the same function without mapping any memory.
Postpone file descriptor allocation to be done at first memory map time.
> sys_mmapper: Lazily allocate shared memory descriptors

- 3rdparty/CMakeLists.txt
- rpcs3/Emu/RSX/VK/VulkanAPI.h
- rpcs3/Emu/RSX/VK/vkutils/instance.cpp
- rpcs3/Emu/RSX/display.h
VK_USE_xxxx are internal API header initialization flags. They're not meant for switching around generic code, use HAVE_X11 and HAVE_WAYLAND instead.
> vk: Stop using internal defines to structure platform-specific code

- .gitignore
- buildfiles/msvc/rpcs3_default.props
- rpcs3.sln
- rpcs3/rpcs3.vcxproj
- rpcs3/tests/packages.config
- rpcs3/tests/rpcs3_test.vcxproj
- rpcs3/tests/test.cpp
- rpcs3/tests/test_fmt.cpp
- Adds the rpcs3 test project to Visual Studio (proof of concept)
- It is built automatically with the solution if you have the GoogleTest Adapter installed
- It now also creates rpcs3.lib if you have the GoogleTest Adapter installed, since it is necessary for the linker
- You can enable automatic test runs in the VS test explorer settings
> Add unit test project to VS

- Utilities/StrFmt.cpp
- rpcs3/tests/test_fmt.cpp
- Adds some unit tests for StrUtil functions
- Fixes fmt::trim, which did not actually trim the back of a string (second argument is not the end index, but the count)
> fmt: add some unit tests and fix fmt::trim

- .ci/build-linux-aarch64.sh
- .ci/build-linux.sh
- .ci/build-mac-arm64.sh
- .ci/build-mac.sh
- rpcs3/CMakeLists.txt
- Adds gtest unit tests to the Linux clang CI (gcc doesn't seem to link for some reason)
> Add unit tests to CI

- 3rdparty/version_check.sh
- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/tests/test_fmt.cpp
- Fixes an infinite loop if the "from" parameter in fmt::replace_all is empty
- Adds some unit tests for fmt::replace_all and fmt::split and fmt::merge
- Removes unused fmt::merge function
- Updates libpng to [1.6.48](https://github.com/pnggroup/libpng/blob/libpng16/CHANGES#L6254)
- Adds version_check.sh script to 3rdparty. I use this script to check if any submodule has a new version.
> Fix infinite loop in fmt::replace_all if "from" is empty

- .github/workflows/rpcs3.yml
- rpcs3/tests/rpcs3_test.vcxproj
- Fixes NuGet package install in the solution
- Ignores build in solution if the package is not installed without touching the source file units
- Install and cache NuGet packages in CI
- Set PreferredToolArchitecture to x64 to fix heap space error in CI
- Run unit test in CI
> CI: Add windows unit tests

- rpcs3/Emu/Io/LogitechG27.cpp
- rpcs3/Emu/Io/LogitechG27.h
- rpcs3/Emu/Io/LogitechG27Config.cpp
- rpcs3/Emu/Io/LogitechG27Config.h
- rpcs3/rpcs3qt/emulated_logitech_g27_settings_dialog.cpp
- rpcs3/rpcs3qt/emulated_logitech_g27_settings_dialog.h
Cleanup previous PR:
- code style
- fix warnings
- replace defines with lambdas
- more const correctness
- replace hex_buf with fmt method
- use enum class
- add missing localizations
NOTE:
This will replace numbers with strings in the config file.
So you have to remap the buttons etc.
> Logitech G27 cleanup

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- Interpolation introduces bit leakage
Closes https://github.com/RPCS3/rpcs3/issues/17148
> rsx: Do not interpolate when performing image reconstruction (D24X8 <-> BGRA8)

- .ci/build-mac-arm64.sh
- .ci/build-mac.sh
- 3rdparty/MoltenVK/CMakeLists.txt
Bumps MoltenVK to v1.3.0
This includes full support for Vulkan 1.3 and adds the following extensions: 
-  VK_KHR_index_type_uint8
-  VK_KHR_load_store_op_none
-  VK_KHR_maintenance4
-  VK_KHR_maintenance6
-  VK_KHR_maintenance7
-  VK_KHR_shader_expect_assume
-  VK_KHR_shader_subgroup_rotate
-  VK_KHR_shader_terminate_invocation
-  VK_KHR_vulkan_memory_model
-  VK_KHR_zero_initialize_workgroup_memory
-  VK_EXT_depth_clip_control
-  VK_EXT_external_memory_metal.
-  VK_EXT_image_2d_view_of_3d
-  VK_EXT_index_type_uint8
-  VK_EXT_load_store_op_none
-  VK_EXT_pipeline_robustness
-  VK_EXT_tooling_info
Full changelog is available [here](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.3.0)
> 3rd Party: Update MoltenVK to v1.3.0

- 3rdparty/libsdl-org/SDL.vcxproj
- Updates SDL to [3.2.12](https://github.com/libsdl-org/SDL/releases/tag/release-3.2.12)
This contains a commit that fixes statically linked SDL in tandem with hidapi on windows.
This means that we can enable SDL_HIDAPI again, which fixes the switch pro controller issues on my end.
fixes #16862
maybe fixes #16948
maybe fixes #17003
> Update SDL to 3.2.12

- rpcs3/Emu/Cell/PPUModule.cpp
Take into calculations the memory required for the PS3 applicatrion binary to load.
This is the most signficant change from #12747
This will also reduce host RAM usage and savestate size a bit for some games, because they would now use less memory of their own which are based on the memory statistics RPCS3 reports through the syscall: `sys_memory_get_user_memory_size`.
It does not fix Brink (the game in target) because the changeset is not complete, it would instead be commited and tested on HW gradually.
This improves accuracy for all games.
> PPU Loader: Consume Executable Memory

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp
- rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_main_menu.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/System.cpp
- rpcs3/headless_application.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/tests/test_fmt.cpp
- rpcs3/util/logs.cpp
- rpcs3/util/logs.hpp
- rpcs3/util/video_provider.cpp
- rpcs3/util/video_provider.h
- Grant more seconds for game termination. This fixes Sonic Unleashed termination for me.
- Allow auto exit in home menu's exit game function in case the game does not terminate itself properly
- Add more logging for game termination and rpcs3 termination
- Use std::string_view in log functions
- Add some strcpy_trunc unit tests
Fixes #17147
> System: Increase callback counter earlier to take into account how long games take to properly react to the exit request

- rpcs3/Emu/Io/LogitechG27.cpp
- rpcs3/Emu/Io/LogitechG27.h
- LogitechG27: use named_thread instead of std::thread
This names the thread and should minimize wait time when closing the game, which was 5 extra seconds in the worst case.
> LogitechG27: use named_thread instead of std::thread

- rpcs3/Emu/Io/LogitechG27.cpp
- rpcs3/Emu/Io/LogitechG27.h
- rpcs3/Emu/Io/LogitechG27Config.h
- rpcs3/rpcs3qt/emulated_logitech_g27_settings_dialog.cpp
- rpcs3/rpcs3qt/emulated_logitech_g27_settings_dialog.h
Fanatec windows drivers doesn't mux a single device into a single software device. Instead they have two identical devices in terms of vendor and product id. Add a mostly stable way to tell between the two.
Currently working wheels should not be affected, Fanatec users please map the wheel again.
Should partially address https://github.com/RPCS3/rpcs3/issues/17191
Edit: Please remap after this change, as the old config migration code was rejected
> Logitech G27 Expand SDL device identification, add mapping note

- rpcs3/Emu/Cell/Modules/cellCrossController.cpp
- rpcs3/Emu/Cell/Modules/cellRec.cpp
- rpcs3/Emu/Cell/Modules/sceNpUtil.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Io/LogitechG27.cpp
- rpcs3/Input/gui_pad_thread.cpp
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/raw_mouse_handler.cpp
- rpcs3/rpcs3qt/pad_motion_settings_dialog.cpp
- rpcs3/rpcs3qt/ps_move_tracker_dialog.cpp
- rpcs3/util/media_utils.cpp
* if code position has changed, disable operating system sleep.
* if GETLLAR output buffer address has changed, , disable operating system sleep.
* If GETLLAR output buffer belongs to the stack of a caller function, , disable operating system sleep.
Test #17200 please.
> SPU: Improved GETLLAR spin detection conditions

- rpcs3/Emu/Io/LogitechG27Config.h
- rpcs3/rpcs3qt/emulated_logitech_g27_settings_dialog.cpp
- rpcs3/rpcs3qt/emulated_logitech_g27_settings_dialog.h
- Simplify LogitechG27 settings dialog by deduplicating some code
- This removes the necessity to maintain two seperate translations for the mappings (which was already not identical in case of Gear R/r )
- Fixes some style/naming issues
- Improve layout to better align buttons
> Gui: simplify LogitechG27 settings dialog

- rpcs3/Emu/Io/LogitechG27.cpp
- rpcs3/Emu/Io/LogitechG27.h
- rpcs3/Emu/Io/LogitechG27Config.h
- rpcs3/rpcs3qt/emulated_logitech_g27_settings_dialog.cpp
Based on the information provided by @Florin9doi
https://github.com/RPCS3/rpcs3/pull/17199#issuecomment-2883934412
Although it seems that (some) Logitech shifters mechanically requires press down to shift into reverse (but not out of), keep press down as a user mapping for flexibility against different hardware and games; if desired, users can map both shifter_r and shifter_press onto the same input.
> Logitech G27 update shifter input

- rpcs3/Emu/Io/LogitechG27.cpp
Make it so when reverse gear is engaged, stick pressed bit is set to 1, while retaining the ability to press down the stick in case there exists games that uses neutral press as an input
This is based on looking up on mechanical design of Logitech shifters
- G29 shifter mechanical explanation https://youtu.be/d7qCn3o8K98?t=1124
- same mechanism on the G27 https://youtu.be/rdjejtIfkVA?t=760
- same mechanism on the G25 https://youtu.be/eCyt_4luwF0?t=130
@Florin9doi I hope with this change, it makes more sense to you now.
Make it easier to examine possible issues from inaccurate control transfers, and to probe real devices outside of RPCS3.
> Logitech G27 update bit 86 shifter_pressed behavior, log control transfers as todo

- .github/workflows/rpcs3.yml
This ensures that PR caches wouldn't take presidence on any other build, and also save us some cache space for the more important caches since cache space is pretty tight.
> Setup build caches to only save on master builds

- .ci/deploy-linux.sh
Fixes https://github.com/RPCS3/rpcs3/issues/17269
Running `ldd /tmp/.mount_*/usr/plugins/multimedia/libffmpegmediaplugin.so` will list the linked dependencies.
The AppImage will search for system libs if not packaged in the image, and will fail if not a version match.
> restore ffmpeg dependencies on linux

- rpcs3/util/logs.cpp
Constinit can't be used on std::string or std::vector.
So let's just use thread_local. maybe it helps...
closes #16287
> Logs: use thread_local

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Memory/vm_reservation.h
Avoid halting PPUs for writes which can be ignored because they do not change data. Simply update reservation timestamp and leave.
> SPU: Skip PUTLLUC writes of the same data

- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
According to the C++ standard, comparison functions used in sorting algorithms such as std::sort must establish a strict weak ordering. Specifically, the comparator must be irreflexive: for all values x, comp(x, x) must be false.
The original comparator used >= for descending order, which violates this requirement in the case of equal values (i.e., when a == b, both comp(a, b) and comp(b, a) would return true). This can result in undefined behavior in sorting algorithms, including potential segmentation faults due to invalid iterator manipulation.
This change replaces >= with > to ensure irreflexivity and compliance with the standard's requirement for a strict weak ordering.
> Fix invalid comparator in savedata_op sorting

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
Maybe "fixes" flash videos in VSH
fixes #17347
> cellVdec: log uknown arguments instead of throwing an error

- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.h
- Fix configurable value dropdown visibility in the patch manager (it stayed hidden after selecting a differen patch)
- Optimize patch_manager_dialog::handle_item_changed. This was always running a lot of code for every single item regardless of the content
> Patch manager:  Fix configurable value dropdown visibility

- rpcs3/Emu/CPU/CPUTranslator.cpp
Apparently this gen there's an `arrowlake` AND `arrowlake-s` target cause arrowlake mobile has lowpower e-cores
> Missed arrowlake-S and lunarlake

- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Regressed by e72cb6801a4e083360f20700116f80a780185a1a
> vk: Fix textureCompressionBC check for v3dv/panvk

- rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
Since LLVM pointers are opaque it does not make sense for `spu_ptr` and `_ptr` to have type parameters. I also removed an unused overload of `spu_ptr`.
> SPULLVMRecompiler: remove unused parameters from spu_ptr and _ptr

- .ci/build-mac-arm64.sh
- .ci/build-mac.sh
As the title states, Homebrew decided to 'kill' (aka hide) support for installing formulae directly from local .rb files. The official solution is some convoluted BS involving taps and whatnot, but simply enabling HOMEBREW_DEVELOPER when installing just MVK then disabling it after works fine enough (and this would be enabled when making a tap anyways).
This fixes the current state of Intel Mac builds failing and preempts the Apple Silicon builds possibly failing in the future too, should GH update the Actions image with a newer Homebrew version.
> [macOS CI] Fix mvk formulae causing builds to fail

- rpcs3/Input/raw_mouse_handler.cpp
Fixes keypresses assigned as mouse buttons being "ignored" in-game for the raw mouse handler & functionality that relies on it e.g. the emulated PS Move handler.
> Fix raw mouse handler keypress logic

- rpcs3/rpcs3qt/vfs_dialog_path_widget.cpp
- Minor fixes and code reduction
- Improved user experience:
- Clicking on the small checkbox area and double clicking on the main checkbox's text area is managed in the same way as recently implemented in the `Patch Manager` panel. That means:
- A click on the small checkbox area will check/uncheck the item. No impact on row selection
- A double click on the main checkbox's text area will select the row and also check/uncheck the item
- `-` button properly enabled/disabled according to the selected row (e.g. disabled for row 1)
- Removal of a selected row is made consistent. That row will remain the selected row. Current code is broken; on first removal, the selection is moved to the checked row
Below some screenshots.
> Minor improvements and cleanup on VFS panel

- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
Since we hide the gs_frame on several occasions before closing, we are almost always saving the fallback.
This is a regression, since it used to save the proper visibility in the past when it was first implemented.
We now save the last known visibility unless it's hidden or maximized.
fixes #16854
> Qt: fix saved gs_frame visibility

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm_reservation.h
* Add postponing streak of up to 4 updates for a reservation. such as for mutex or more complex operation which needs to cover more than 8 bytes of the reservation.
* Minor bugfix in asynchnous LR notifications.
* Notify waiters on sys_mutex_unlock.
> SPU: Restore postponed LR notifications (with tweaks)

- rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
SCE NP port is always bound, so the the optimization of letting the thread rest when there are no bound ports does not work.
Make it rest when there have not been previous activity. Saves a bit of CPU time.
> Network: Make P2P listener thread rest properly

- rpcs3/rpcs3.vcxproj
- rpcs3/tests/rpcs3_test.vcxproj
Update opencv to [4.12.0](https://github.com/opencv/opencv/wiki/OpenCV-Change-Logs#version4120)
This new version seems to optimize some of the functions we use for PSMove tracking.
> Update opencv to 4.12.0

- rpcs3/Input/hid_pad_handler.cpp
Follow up of an old possible regression reported in #14063 related to emulator crash when a pad (DS3, DS4 etc.) got disconnected (e.g. due to inactivity).
It was reported by many users that build 0.0.25-14523 (#13175) (updating lib `hidapi` from 0.12.0 to  0.13.0) was possibly causing the crash of the emulator, since some random time, after the pad got disconnected.
That issue was reported by users on `Windows` and `Linux`. I also verified that since that build I also have the same issue on my env (`Windows 11`).
So, I just applied on current build the old `hidapi` version 0.12.0 (reported as working) and 0.13.0 (possibly broken) and verified that the emulator was crashing with both.
After some testing, I simply verified that the issue is caused by threads concurrent access to some (non …
> Fix emulator crash when a pad gets disconnected (e.g. due to inactivity)

- rpcs3/rpcs3qt/settings_dialog.cpp
I minor, and last, follow up of #17459 and #17442 allowing to check/uncheck an entry in the firmware libraries panel by double-clicking.
For that panel, a solution based on single-clicking was preferrable but it seems it was conflicting with the existing itemChanged (single click was triggered twice so producing no state change).
IMO, better than nothing.
> Add selection on firmware libraries panel by double-clicking

- rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- rpcs3/Emu/system_config.h
- rpcs3/Emu/system_config_types.cpp
- rpcs3/Emu/system_config_types.h
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- Expose date format as setting (Year/Month/Day, Month/Day/Year, Day/Month/Year)
- Expose time format as setting (12-hour clock, 24-hour clock)
This may and will only have an impact on games (untested)
> System: expose date format and time format as settings

- rpcs3/Emu/Cell/PPUThread.cpp
Previous code did not respect the 32-byte long area on the stack frame called the home space - area on the stack frame area that is specific to Microsoft's x64 calling convention, leading to corrupted values after a callback.
Bug noticed by @capriots
> Win32: Respect home space / shadow space on the stack frame

- rpcs3/Emu/Cell/PPUInterpreter.cpp
fixes [ppu_integer_arithmetic](https://github.com/RPCS3/ps3autotests/tree/master/tests/cpu/ppu_integer_arithmetic) test crashing to desktop with interpreter.
VSLDOI and MFOCRF also exhibit the same symptom (0x0 in ptrs), but they are special and have 16 variants in addition to the base instruction. And all the other variants (_0..._15) have values, so perhaps it's not an issue for those two?
> Fix rc variants of ADDE and SUBFE in interpreter

- rpcs3/Emu/Cell/Modules/cellDmux.cpp
- rpcs3/Emu/Cell/Modules/cellDmux.h
- rpcs3/Emu/Cell/Modules/cellDmuxPamf.cpp
- rpcs3/Emu/Cell/Modules/cellDmuxPamf.h
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
The PPU side doesn't really do much, it more or less just sets up the context and forwards events produced by the SPU thread to the user and forwards commands to the SPU thread.
The code is very bloated due to all the savestate handling and checking for `cpu_flag::again` after `sys_mutex_lock()`, `sys_cond_wait()`, etc.
Changes in cellDmux are only so it still compiles, since I had to change a bunch of structs in cellDmux.h.
I set `libdmuxpamf.sprx` to HLE by default since it's completely implemented with this.
> [Testing Needed] cellDmuxPamf implementation part 2: PPU thread

- rpcs3/Emu/Cell/lv2/sys_ss.cpp
- rpcs3/Emu/Cell/lv2/sys_ss.h
- rpcs3/Emu/system_config.cpp
- rpcs3/Emu/system_config.h
As the title suggests, this PR randomises the PSID stored in RPCS3s configuration during startup.
This is required at least for ModNation Racers when playing online, as it uses the consoles PSID to differenciate players in a lobby, and all emulator instances having a PSID of 0 breaks matchmaking.
Tested that the random values are writing to the config. Draft PR whilst I figure out updating existing configs with a PSID of zero.
**I would more than welcome any feedback on how best to approach the above, if theres somewhere in particular its best to slip in a value check :)**
Any constructive critisim or changes please let me know.
> Generate random OpenPSID upon config initalisation
