rpcs3/Emu/RSX/VK/VKHelpers.h
With https://github.com/RPCS3/rpcs3/pull/6842 fixing the fp16 bug, it is worth retesting for owners of Vega GPUs that games are rendering correctly again even with fp16 enabled.
=> vk: Restore vega native use of FP16 in shaders

rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/Cell/lv2/sys_vm.h
Create temporary variable to resolve undefined reference.
[ 98%] Linking CXX executable ../bin/rpcs3
/usr/bin/ld : Emu/librpcs3_emu.a(sys_vm.cpp.o) : dans la fonction « sys_vm_t::~sys_vm_t() » :
/mnt/raid/Git/rpcs3/rpcs3/Emu/Cell/lv2/sys_vm.cpp:21 : référence indéfinie vers « id_manager::id_traits<sys_vm_t, void>::invalid »
collect2: erreur: ld a retourné le statut de sortie 1
make[2]: *** [rpcs3/CMakeFiles/rpcs3.dir/build.make:426: bin/rpcs3] Error 1
=> Fix debug build gcc/clang linker.

Utilities/Log.cpp, rpcs3/rpcs3qt/update_manager.cpp
Should hopefully stop people having "Another instance is running" when restarting after an update.
=> Add a file lock to check if we're restarting

rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/progress_dialog.cpp, rpcs3/rpcs3qt/update_manager.cpp
1. Adds the quickstart link to SSL warnings.
2. Updates error handling for the compatibility database updater.
Needs https://github.com/DAGINATSUKO/www-rpcs3/pull/42 to be deployed first.
fixes #6874
=> Adds quickstart link to SSL warnings

rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_utils.h
This lowers the relative cost of this function from ~2.25% to ~1.80% on gcc 9 which I found quite surprising, some of it probably gets inlined better in the callers, but I haven’t been able to isolate which parts.
=> rsx: Make input_is_swizzled a template parameter

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKResourceManager.h
- Remove block alignment on compressed textures as long as the unpack alignment is well defined.
- Improve the vulkan sampler cache to not cause slowdown in games that have random parameters set. In some cases, uninitialized variables seem to make their way into unused variables but since we cannot assume they're unused, it causes a lot of permutations and can kill performance.
- Round lod bias to the nearest half integer for vulkan to work around issue 2 above when point mipmap sampling is used. Should provide near-correct results at all times while filtering out parameter noise.
=> rsx: Minor fixups

rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/gcm_enums.cpp, rpcs3/Emu/RSX/gcm_enums.h, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.h
* If the restart index is above max valid index value, it won't ever be equal to one of the indices. (upper bits aren't ignored)
* because #6737 made index array type always valid, replace to_index_array_type() with a static_cast.
* Added restart_index_enabled_raw() in case we want the actual register value.
Default restart index value is UINT32_MAX so it's not unlikely that we enabled the restart index when there's no need to.
edit: disabled primitive restart array may be faster to process (byteswap etc) indices.
=> rsx: Enable primitive restart index only when needed

Utilities/JIT.cpp
I don't see why not ? Is this low area of memory used for anything else ? 
Avoids LLVM out of memory fatal error when too many PPU modules get compiled and linked in.
=> Rewrite the way LLVM JIT does memory allocation to allow use of more than one contiguous segment

rpcs3/Emu/Cell/SPUThread.cpp
must be cleared for each thread separerately.
=> sys_spu Fixup after #6864

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h
AMD windows driver does not support alpha-to-one and crashes when alpha-to-one feature is enabled.
To properly work around this would require also emulating the whole sample masking stage but this is very rarely used due to the fact that you can just disable blending when using alphaToCoverage. I have not encountered any PS3 application that actually uses this, but if one is found, a fallback implementation could theoretically be written. Leaving that task for the future as it is not a priority.
Fixes AMD windows driver crashing on boot when MSAA is enabled (regression).
=> [Hotfix] vk: Add checks for alphaToOne support

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLOverlays.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKOverlays.h
- Adds support for other primitive types other than triangle strips. This will come in handy very soon.
- Adds a video-out calibration pass for vulkan. This already existed on OpenGL and fixes some games that use video-out gamma correction to calibrate ingame brightness. In these games, the brightness settings usually have no effect on vulkan, but work on OpenGL.
=> rsx: Overlay improvements

rpcs3/Emu/Audio/ALSA/ALSABackend.cpp, rpcs3/Emu/Audio/ALSA/ALSABackend.h, rpcs3/Emu/Audio/FAudio/FAudioBackend.cpp, rpcs3/Emu/Audio/FAudio/FAudioBackend.h, rpcs3/Emu/Audio/Pulse/PulseBackend.cpp, rpcs3/Emu/Audio/Pulse/PulseBackend.h, rpcs3/Emu/CMakeLists.txt
This PR mirrors 9253f7d645c891cb57a8785bdaeb93d02a80f307, in that it stops building audio backends which are disabled.
It also allows the user to disable OpenAL at build-time like other audio backends, this disables microphone input at the same time.
This PR is more easily read commit per commit.
=> Stop building ALSA/PulseAudio/FAudio when disabled, and make OpenAL optional

rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKResolveHelper.h
- Allows bypassing all remap shenanigans to make some operations that rely on the raw image to work correctly.
Fixes "blue" filter in some games with newer builds where AV filters are implemented. Since the image being drawn to the screen is 'raw', image transform is undesired. The "blue" is because the PS3 format ARGB is actually the PC format BGRA but with endianness inverted for the 32-bit block.
=> [Hotfix] vk: Add explicit support for identity image views

rpcs3/rpcs3qt/update_manager.cpp
Fixes issues where rpcs3 appimage and /tmp/ directory were on different devices.
Old appimage is now renamed to old app image name + "_old" in the same directory.
Fixes https://github.com/RPCS3/rpcs3/issues/6858 .
=> Stop autoupdater renaming file across devices

Utilities/BitField.h, rpcs3/Emu/Cell/Modules/cellAudio.cpp, rpcs3/Emu/Cell/lv2/sys_event.cpp, rpcs3/Emu/Cell/lv2/sys_sync.h
Contains 3 commits:
* Remove limits lib dependency from Utilities/BitField.h.
* Add EINVAL check for invalid ipc_key in - general lv2 shared sync object creation (instead of CELL_OK), sys_event_port_connect_ipc (instead of ESRCH).
* Add missng check for key in cellAudioSetNotifyEventQueue.
=> Fixes cleanup

rpcs3/rpcs3qt/game_list_frame.cpp
Context menu was created twice, so selecting something from it once brought up yet another menu. They were constructed in an identical way - although name `pad_configure` implies that maybe the second menu was there to allow navigating it via gamepad, I checked and it wasn't the case.
=> Fix context menu showing twice in Game List

rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/rsx_methods.cpp
Another changeset that almost got buried and forgotten; this PR makes several minor tweaks to ZCULL synchronization that can give tangible performance improvements in some cases.
- Avoid hard sync condition as much as possible. This is done by implementing more sync hints for the backends.
- Implements reading of partial results. I can only use RADV as the reference here since it is open source, but this should likely improve the API-side waiting.
- Allow delaying report transfers until they are ready even when using imaging methods to move the bits.
This doesn't solve all the ZCULL problems, but a lot was learned when implementing this that makes the bottlenecks a lot more obvious.
=> rsx: ZCULL tweaks

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKResolveHelper.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
GPU deswizzle was attempted in the past and was a failure, but my approach back then was a bit different. Ultimately it failed because it attempted to do deswizzle as a texture coordinate transformation which did not work too well. Even with a lookup table the texels were too far apart for emulated filters to work properly. This new approach just adds on top of the existing GPU decoders and implements deswizzle as an upload transformation. You can see some of my thoughts on this in https://github.com/RPCS3/rpcs3/issues/6882.
A downside of using GPU deswizzle is that each LOD has to be processed separately which is very inefficient to run on a GPU. Poor occupancy of lower LODs just robs the rest of the graphics pipeline of resources which actually hurts graphics throughput. There is also a …
=> rsx: GPU texture deswizzle and other compute enhancements

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellSysCache.cpp, rpcs3/Emu/Cell/Modules/cellSysutil.cpp, rpcs3/Emu/Cell/Modules/cellSysutil.h, rpcs3/Emu/System.cpp, rpcs3/Emu/VFS.cpp, rpcs3/Emu/VFS.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/main_window.cpp
Since cache is useful to improve startup times, why limit it to only one game at time?
This PR isolates the whole /dev_hdd1 mount point, basing on game id.
=> Virtualize cellSysCache

rpcs3/rpcs3qt/auto_pause_settings_dialog.cpp, rpcs3/rpcs3qt/breakpoint_list.cpp, rpcs3/rpcs3qt/cg_disasm_window.cpp, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/log_frame.cpp, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/trophy_manager_dialog.cpp, rpcs3/rpcs3qt/user_manager_dialog.cpp
This should fix the custom context menu position.
It was offset by some amount which led to some linux users activating menu options by releasing their mouse buttons.
=> Qt: adjust custom context menu positions

rpcs3/Emu/RSX/RSXThread.cpp
If depth write is disabled, depth test is enabled but depth test func is not per-fragment, skip the depth stage. Fixes contention is some games that incorrectly set up framebuffer data. e.g a game sets all of the targets for depth and color to the same address and wants to render to color. They disable depth write, but depth test is enabled and using always pass function to skip the test instead of actually disabling depth test itself (MLB 08 The Show).
=> rsx: Validate depth test setup to avoid address contention

rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h
A total rewrite completely removing m_dev would be a good idea but I'm too lazy to do it.
=> Fixes evdev settings & multiple pads handling

Utilities/Config.cpp, Utilities/File.cpp, Utilities/File.h, Utilities/Log.cpp, Utilities/StrFmt.cpp, Utilities/StrFmt.h, Utilities/types.h, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/GDB.cpp, rpcs3/Emu/GDB.h, rpcs3/Emu/System.cpp, rpcs3/Emu/VFS.cpp
Bits of exception removal.
Also potential minor bugfix related to network share locations on Windows.
=> Minor exception removal

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.h
- When the point sprite flag is set, overrides the input similar to the
2D mask. The returned X and Y values are always the gl_PointCoord values
for the fragment.
- Stacks with the 2D mask to override the z and w coordinates.
Fixes https://github.com/RPCS3/rpcs3/issues/6317
=> rsx: Implement point sprite coordinate generation

rpcs3/Emu/Cell/PPUInterpreter.cpp
=> Fixup SSSE3 usage in PPUInterpreter.cpp

rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/Modules/cellSysCache.cpp, rpcs3/Emu/Cell/Modules/cellSysutil.cpp, rpcs3/Emu/Cell/Modules/cellSysutil.h, rpcs3/Emu/Cell/PPUModule.cpp
* Default sdk version is -1. (SYS_PROCESS_PARAM was not set)
* Implement sysutil_check_name_string:
- Only limited set of characters is allowed in parameters of a few sysutil functions (`\` or `/` for example aren't allowed, thus the need to escape from `/` no longer needed there).
- It turns out if sdk version is below 3.70 it is allowed to insert another character at the end of buffer length, must be proceeded by a null terminator. (e.g for cellSysCacheMount this null term is found at getCachePath[0].)
=> Implement sysutil_check_name_string, Fix process default sdk version

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
This instruction *does not* enforce ordering of instruction-fetches, this means recompilers do not need to to invalidate the instruction stream after encountering it.
What this may potentialy benefits:
* Less, larger SPU functions would be compiled.
* Because this instruction is being used nearly 100-percent of the times after GETLLAR and spu functions compilation isn't a short process, it may reduce the time spent in atomic loops which may improve success rates.
=> SPU: Optimize DSYNC instruction

Utilities/BitField.h
Fixes a warning that causes a lot of noise to compiler output.
=> Fix warning in BitField.h

rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/cheat_manager.cpp, rpcs3/rpcs3qt/cheat_manager.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui
First draft of a cheat manager.
Note that the cheats you make probably won't survive another launch of the game if the offset is on the heap. I may add a more complex parameter to make some level of redirection possible in the future.
edit:
I added a redirection system, completely untested, syntax is:
$ is offset
[] for dereferencing
+/- for adding offset
ex: [[$]+8]+16
It will get the u32 offset is pointing at, add 8 to that, get the u32 that is pointing to and add 16 to that which will be the final offset.
If the Script cell is left blank it will act as before.
=> Cheat Engine

rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp, rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.h, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
Adds individual settings for the framerate graph and the frametime graph and detaches them from the "High" detail level.
Fixes a division by zero bug where the chip usage would show "-nand(ind)".
Moves code to a new header file.
Fixes the vertical center option when graphs are shown.
Disables the overlay margin options in the settings dialog while the center option is enabled.
I noticed that the graphs adjust to the body width while the graph description does an auto-resize instead. I probably won't fix it in this PR.
=> Performance Overlay: Add graph settings and fix some minor issues

rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
This matches the firmware as it errors if `gamma NGE 0.8` (Not Greater Equal Than).
=> Disallow NaN in cellVideoOutSetGamma

rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h
Rename a struct to avoid violating the one definition rule.
Fixes #6953
=> Qt: rename pad_info to pad_device_info for ODR

rpcs3/rpcs3qt/gui_application.cpp
Avoid "QSettings::setValue: Empty key passed" logging when installing
PUP firmware (Release/Debug build).
> game_list_frame.cpp was not done as FW dont go in the list.
=> Avoid Start/StopPlaytime when installing firmware.

rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/SPURecompiler.cpp
Thanks to @Niram7777 for research.
=> SPU LLVM bugfixes

rpcs3/Emu/Cell/SPUThread.cpp
This replaces the totally messed up PR #6728
Some games make heavy use of getllar() & putllc() without even changing data.
In this case avoid unneccesary heavy locking of the PPU threads on non-TSX
hosts.
=> Lightweight putllc() for non-TSX if no data changed

rpcs3/Emu/Cell/Modules/cellAudio.cpp
Same as firmware: NaN and Inf are flushed to zero, otherwise clamp to +-16.f range.
TODO: Check actual values specified at src?
=> Clamp volume in cellAudioAdd/2c/6c/Data

rpcs3/Emu/RSX/Common/BufferUtils.cpp
- Fixes min-max calculation for arbitrary N-sided polygons. This solves vertex flickering in some titles like Tlou. Other parts of the improvements changeset were already slowly added to master.
=> rsx: Fixup for polygon rendering

rpcs3/Emu/Cell/Modules/cellAudio.cpp, rpcs3/Emu/Cell/Modules/cellAudio.h, rpcs3/Emu/Cell/Modules/cellVoice.cpp, rpcs3/Emu/Cell/Modules/cellVoice.h, rpcs3/Emu/Cell/lv2/sys_prx.cpp
* Use shared lock wherever possible. (std::unordered_map::find is safe to use under shared lock)
* Fix cellVoiceSetVolume.
* Fix NOT_INIT checks.
* Fix error logging of cellVoiceCreateNotifyEventQueue, cellAudioCreateNotifyEventQueue.
* Fix cellVoiceCreatePort.
* Implement 0 event source handling.
* Implement cellAudioCreateNotifyEventQueueEx.
* Implement event source for cellAudio events
* Fix cellAudioCreateNotifyEventQueue queue depth.
* Minor error checking fixes for sys_prx from firmware.
Fixes #6884
Fixes Test Drive Unlimited.
=> cellVoice/cellAudio Fixes

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.h, rpcs3/Emu/Cell/lv2/sys_gpio.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/Memory/vm_ptr.h
Doesn't improve anything for end users, but may break something.
=> Annoying refactoring

rpcs3/Emu/Cell/Modules/cellGem.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
* Check if attribute->max_connect is zero in cellGemInit.
* Emulate side-effects of cellGemInit allocating an internal buffer if memory_ptr provided is nullptr. (freed at cellGemEnd)
* Fix state reset of cellGem.
* Avoid calling lv2_obj::sleep sequantially in sceNpTrophyRegisterContext. (doesnt depend on usleep timers accuracy setting, faster respond after calling Emu.Stop(), lv2_obj::sleep doesnt need to be called on already sleeping thread)
* cellGem is now thread-safe.
* Make sceNpTrophyRegisterContext "queued" counter access thread-safe.
=> cellGem and sceNpTrophyRegisterContext improvements

rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h
* When type = 0, `lsa % type` was raising an exception. This is fixed and also move all EINVAL conditions before ESTAT and ESRCH checks as fw.
* Stub sys_spu_thread_group_log.
* Fix sys_spu_thread_un/bind_queue queue existence check. (check if binded, regardless of pointer experation)
=> Fix possible division by zero in sys_spu_thread_write/read_ls, sys_spu_thread_un/bind_queue bugfix and stubs

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/rpcs3qt/gui_application.cpp
Might fix some issues with Qt Dialogs when using the no-gui option.
With this you should be able to run games using the recompilers.
maybe improves #7015
=> Improve no-gui option

rpcs3/Emu/Cell/Modules/cellOskDialog.cpp, rpcs3/Emu/System.h, rpcs3/headless_application.cpp, rpcs3/main_application.cpp, rpcs3/main_application.h, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/save_data_dialog.cpp, rpcs3/rpcs3qt/trophy_notification_helper.cpp, rpcs3/rpcs3qt/trophy_notification_helper.h, rpcs3/rpcs3qt/user_manager_dialog.cpp
Fixup for a mistake in #7053 that caused trophy notifications and savedata dialogs to be hidden in no-gui mode despite using native game-window dialogs.
=> Qt: properly skip trophy and savedata dialogs in no-gui mode

rpcs3/Emu/RSX/VK/VKHelpers.h
Because `sampleShadingEnable`  is used, `sampleRateShading` needs to be set to `VK_TRUE` for the device:
https://github.com/RPCS3/rpcs3/blob/9dab0575fa3fd8ba0c3e089464427723f750ca6c/rpcs3/Emu/RSX/VK/VKHelpers.h#L3252-L3253
Fix the following messages when "Debug Output" is enabled:
```
E {RSX [0x0192250]} RSX: ERROR: [Validation] Code 0 :  [ VUID-VkPipelineMultisampleStateCreateInfo-sampleShadingEnable-00784 ] Object: VK_NULL_HANDLE (Type = 0) | vkCreateGraphicsPipelines(): parameter pCreateInfos[0].pMultisampleState->sampleShadingEnable. The Vulkan spec states: If the sample rate shading feature is not enabled, sampleShadingEnable must be VK_FALSE (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-VkPipelineMultisampleStateCreateInfo-sampleShadingEnable-007 …
```
=> vk: Add sampleRateShading to the list of device enabled features

rpcs3/ds4_pad_handler.cpp, rpcs3/ds4_pad_handler.h
I was messing around with some non-OEM ds4 clone and found it has some broken HID reports, specifically 0x81 (get mac address). The actual PS4 seems to use 0x12 instead (another command to get bluetooth radio mac address) so I tried using that instead and it works. Also, the calibration data seems to be in bluetooth mode when the controller is not genuine, something which is likely fixed in the real console by just checking if value is less than 0 and not whether its connected via bluetooth, but that's an issue for another day. Checked the same changes into the linux kernel driver for ds4 and it does get the controller to work. Ofc if you get the genuine check error with something you paid full price for, just get a refund instead.
=> ds4: Add workarounds for some 3rd party controllers

Utilities/Thread.cpp, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h, rpcs3/Emu/Cell/lv2/sys_tty.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
This originated from the docs mentioning that you can specify "primary" SPU thread for sys_spu_thread_group_terminate in addition to group id.
Looking at firmware disasm there is no such thing which seem to serve this feature at first,
BUT what is possible to specify to the 5th threads' id, why ? because it matches its' SPU group id.
The pattern of SPU id seem to be `SPU id = (spu group id & 0xFFFFFF) | (spu thread internal number) << 24)`
the "internal number" of the thread is specified by the counter of its creation starting from 0.
SPU group id base is 4, meaning that the 5th thread always has the same id as its' group.
[testcase](https://github.com/elad335/myps3tests/tree/master/spu_tests/Threaded%20SPU%20ID)
results on rpcs3:
```
SPU Group Id = 0x04000100
SPU Thread(0) Id = …
```
=> sys_spu: Fix SPU Thread Id

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
Improves further on #7077, also includes branch-to-self sync points as they also raise sync_point_request flag.
=> rsx: Delay FIFO recovery point creation if is in in_begin_end scope

rpcs3/Emu/Cell/Modules/cellNetCtl.cpp, rpcs3/Emu/Cell/lv2/sys_net.cpp
that are shown in Metal Gear Online. Also aligns with implementations on non win32 platforms.
=> Updated sys_net to use WSAPoll on win32 to fix connection issues

rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
This moves the firmware settings and libraries from the cpu tab to the advanced tab.
This was decided because the common user shouldn't need to worry about these things when playing most games and thus let the setting stay on liblv2 only.
=> Qt: move firmware settings to the advanced tab

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.h
It was returning unlock state of different trophies than it should lol, now fixed. (endianness typo)
=> Hotfix sceNpTrophyGetTrophyUnlockState

rpcs3/rpcs3qt/trophy_manager_dialog.cpp, rpcs3/rpcs3qt/trophy_manager_dialog.h
Adds the "platinum relevance" to the trophy table.
This indicates if a trophy is needed in order to unlock the platinum trophy.
Adds minor optimizations that might further speed up loading the trophy manager dialog.
=> Improve trophy manager dialog

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h
This PR enhances game list filtering by also taking custom names (_Rename in Game List..._) into account when filtering.
`m_titles.value()` is used instead of `operator[]`, since `.value()` returns a default initialized entry should the key not exist in the map - so if custom name does not exist, this `QString` will be an empty string and `.contains` will naturally never return true, thus I decided branching the code for whether the custom case exists or not is pointless.
=> Qt: Look for custom game titles when filtering via Search

Utilities/JIT.cpp, rpcs3/Emu/CPU/CPUTranslator.cpp, rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/SPURecompiler.cpp
Should improve perf and accuracy for modern processors, but will be slower on older CPUs.
=> [WIP] SPU LLVM: use FMA with approx xfloat when available

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
- Disable denormals for SPU threads
- add clamping helper
- rewrite multiply_zero()
- make use of FMA if possible
=> Improve approximate xfloat

rpcs3/Emu/Cell/PPUOpcodes.h
Because `me` is allowed to be lower than `mb`, substruction will cause shift count to be greater than max allowed shift count which is undefined behavior, mask the shift to 6 bits to avoid this.
=> Avoid shifting by greater/equal than max bits values in ppu_rotate_mask

rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/log_frame.cpp, rpcs3/rpcs3qt/log_frame.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
Since some users complain about log performance and the log appears to be too slow for certain amounts of spam I decided to add some more options and to rewrite the log a bit.
I created a new log that uses QPlainTextEdit with html for colorization instead of the old QTextEdit.
I added new log options in the GUI tab:
Maximum block amount:
Limits the amount of log lines/blocks. This should improve performance since the log is slower the longer it gets. (0 is default and means unlimited log length)
=> Improve log

Utilities/JIT.cpp, rpcs3/Emu/Cell/PPUThread.cpp
Compress new files in .gz format. Backward compatible with uncompressed files.
=> LLVM: compress PPU cache

rpcs3/rpcs3qt/game_list_frame.cpp
Further narrows down the file filter for ppu and spu cache removal in order to prevent future fixes and also removal of wrong files.
=> Qt: use more specific file filters for cache removal

rpcs3/Input/keyboard_pad_handler.cpp, rpcs3/Input/keyboard_pad_handler.h, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h
Adds mousewheel as a bindable button to keyboard handler. Theoretically supports 4-directional scroll wheels, but I don't have one to test with.
Since there's no event for "wheel movement has stopped", I've added a check that releases the button on the emulated controller when 0,1 seconds has passed since last wheel scroll to the same direction. This means that the button is considered to being held down as long as you keep scrolling, but it makes button mashing more difficult.
Should support scroll gestures on touchpads as well, but I doubt anyone is interested in trying that in action.
Closes #5396
=> Support mouse wheel binding

rpcs3/Emu/Cell/lv2/sys_net.cpp
Don't call WSAPoll with empty socket list.
May fix #7137
=> sys_net: add a workaround for WSAPoll with timeout

rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
There was a typo with float comparison type (unordered makes negative Nan result to true, writing -1 instead of 0) in CFLTU.
While also make CFLTU on non-xfloat path accurate as xfloat path now.
* optimize PPU FCTIW. (unoptimized form was given from thought of non-existing corner case)
=> SPU LLVM: rewrite comparison on non-xfloat path of CFLTU, CFLTS

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
I assumed that only "fixed" cellSaveData functions had the funcFixed param and therefore allowed confirmation dialogs to be shown during some auto save/load/delete operations.
By checking for "fixed" functions on top of the funcFixed param this should now be fixed (pardon the pun).
=> cellSaveData: only show dialogs in fixed functions

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/rpcs3qt/cheat_manager.cpp
Allows to modify PPU executable code when the application is running, exclusive to interpreters.
=> Implement runtime PPU executable code modification via Cheat Manager

rpcs3/Emu/Cell/Modules/cellVoice.cpp, rpcs3/Emu/Cell/Modules/cellVoice.h, rpcs3/Emu/Cell/SPUThread.h
Fixes a possible unintended state (overriding last element with 0) by clearing last element before zeroing count. (race between the exiting thread and the one calls sys_spu_thread_write_spu_mb).
Regressed by #6917.
=> spu_channel_4_t fix

Utilities/File.cpp, Utilities/File.h, rpcs3/Crypto/unpkg.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/progress_dialog.cpp, rpcs3/rpcs3qt/progress_dialog.h
This PR corrects miscellaneous issues I spotted when trying to make RPCS3 break by feeding it very long paths on Windows. Those are:
- Several WinAPI functions throw `ERROR_FILENAME_EXCED_RANGE` when the input file name/directory name is longer than the function accepts (typically `MAX_PATH`). This error was not recognized by RPCS3, thus making it throw an "unknown error" exception, effectively crashing the emulator. Even worse, by relocating `$(EmulatorDir)` to such long path RPCS3 would consistently crash on startup, forcing the user to fix config files by hand!
After those changes, RPCS3 will gracefully report failure with a "Path too long" message.
* `pkg_install` was totally oblivious of installation failure and reported "success" to the user even if some files failed to unpack (due …
=> Improvements to misc failure conditions

rpcs3/Crypto/unself.cpp, rpcs3/Crypto/unself.h, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_process.cpp, rpcs3/Emu/Cell/lv2/sys_process.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_ss.cpp, rpcs3/Emu/Cell/lv2/sys_ss.h, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/Emu/System.cpp
Needed for VSH (has root flags), separated from games.
List of currently affected syscalls:
* `sys_ppu_thread_set_priority`.
* `sys_ppu_thread_create`.
* `sys_spu_thread_group_set_priority`.
* `sys_spu_thread_group_create`.
* `sys_ss_access_control_engine`.
=> Implement ps3 application root flags detection

rpcs3/Crypto/unself.cpp
Fixes a crash when using Utilities->Decrypt PS3 Binaries on PSN binaries that require a RAP file for decryption.
=> Avoid using vfs::get to let decrypt work on PSN binaries

rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/Modules/cellDmux.cpp, rpcs3/Emu/Cell/Modules/cellGem.cpp, rpcs3/Emu/Cell/Modules/cellKb.cpp, rpcs3/Emu/Cell/Modules/cellL10n.cpp, rpcs3/Emu/Cell/Modules/cellMouse.cpp, rpcs3/Emu/Cell/Modules/cellNetCtl.cpp, rpcs3/Emu/Cell/Modules/cellOskDialog.cpp, rpcs3/Emu/Cell/Modules/cellPngDec.cpp, rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp, rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/Modules/sceNpSns.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/Cell/Modules/sys_ppu_thread_.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_tty.cpp, rpcs3/Emu/Cell/lv2/sys_usbd.cpp, rpcs3/Emu/Io/Null/NullKeyboardHandler.h, rpcs3/Emu/Io/Null/NullMouseHandler.h, rpcs3/Emu/RSX/Common/texture_cache_checker.h, rpcs3/Emu/RSX/GCM.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Input/pad_thread.cpp
* Prefer default initializer over std::memset 0.
* Use std::format in trophy files name obtaining.
* Use vm::ptr<>::operator bool() instead of comparing vm::ptr to vm::null or using addr().
* Set common sceNpBasic, cellGem, cellCamera and a few others to warning level.
* Disable logging some "offline", cellCamera error codes and a few others.
=> Some cleanup and log messages silencing

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.h
- Implement sceNpTrophyAbortHandle, if handle is aborted an error code will be returned on its usage.
- Free contexts & handles in sceNpTrophyTerm.
- Return invalid argument error code on invalid context & handles ids.
- Implement id resource shortage error checking.
=> Implement sceNpTrophyTerm resources deallocation, sceNpTrophyAbortHandle

rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
- PS3 matches OGL behavior where writing to the depth export register results in clamping.
Fixes missing overlays and effects in GOW1 from the HD collection.
=> vk: Clamp depth export in FS

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h
Fixed a minor bug where saving or removing custom configs or custom pad configs only repainted the icons for that exact entry, but not the related other entries that share the same title id.
=> Qt: repaint all related icons for custom configs

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
- Flush DMA queue on RSX semaphore release (a form of pipeline barrier). Applications use these as signals that DMA operations are complete and will usually reuse texture and vertex memory immediately afterward. Flushing the DMA queue in this situation guarantees correct data is used for draw calls and fixes vertex flickering and rendering garbage in some games when MTRSX is enabled.
- Minor alteration to cond render emulation to avoid generating possible NaNs. This is a non-functional change intended to solve a theoretical problem that may not exist in practice.
=> rsx: Sync improvements

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/RSX/Common/ShaderParam.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog.cpp, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog.h, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.h, rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VulkanAPI.h, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
1. Removes an unused function declaration after its body removal in an earlier PR.
2. Fixes the update loop for non-interactive native dialogs.
3. Refactors native shader dialogs to get rid of duplicate code in both renderer backends.
4. Removes a duplicate sleep in a recently added cellSaveData confirmation dialog
=> Native overlay fixes

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/RSX/Overlays/overlay_animation.cpp, rpcs3/Emu/RSX/Overlays/overlay_animation.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
Adds animation support. This commit adds the base framework and implements a translate animation used to slide elements around the screen. This is then used to implement the sliding animation for the trophy notification.
The main animations that will be added to various dialogs include fade_in, fade_out and sliding for the time being. Rotation is also fairly easy to add if required. Basically any transform that can be trivially represented in an equation. The only other remaining task here is adding the fade_in/out to the OSK to make its spawning/despawning a bit softer but that is for a later date.
=> rsx/overlays: Add support for animations

3rdparty/CMakeLists.txt
On windows, BCrypt library has to be specified for linker or otherwise the linker will not find implementations for the BCrypt functions. Fixes compiling when using MSVC with CMake.
=> Link BCrypt library on MSVC + CMake

rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/rpcs3qt/trophy_notification_helper.cpp
- Allow multiple trophies to be displayed at once. The trophies will be queued up and displayed when it is their turn to do so.
- Slightly increase trophy font and dialog size. This solves a long-standing problem where some libre fonts refused to work properly with the trophy notification dialog resulting is broken text.
=> overlays: Misc trophy improvements

rpcs3/rpcs3qt/vfs_dialog_tab.cpp
+/- should be self-explanatory, but in case somebody doesn't get it tooltips have been added.
Also made `"+"` and `"-"` not translatable as it was stupid.
=> Qt: Add tooltips to Virtual File System buttons

rpcs3/Input/keyboard_pad_handler.cpp, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.cpp
* Changes the Null microphone option to Disabled to match renderer and audio output settings.
* Disables antialiasing dropdown for renderers which do not support it. Hopefully makes it more clear that AA hasn't been implemented for OpenGL.
* Some minor refactoring of mousewheel binding
=> Miscellaneous updates

rpcs3/Emu/Cell/lv2/sys_fs.cpp
* Ensure cellFsDirectoryEntry array is filled with zeroes on places above data_count range.
* Limit cellFsGetDirectoryEntries to be able to read only one entry at a time.
* Set uid, gid to -1 instead of 0 for dev_hdd1.
* Make negative whence not throw and return proper error code in cellFsLseek, also fix its checking order.
Moves Arthur and the Revenge of Maltazard [[BLES00772](https://forums.rpcs3.net/thread-178418.html)] from Intro (stuck on loading) to ingame, possibly playable.
[Testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellFsGetDirectoryEntries)
Part image of previously faulty game code:
https://user-images.githubusercontent.com/18193363/71748601-bf168280-2e7b-11ea-9f76-85c8fb8fa4cb.png
Function tries to read from d_type which if entry is written should be …
=> cellFs: Few Improvements

rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/pkg_install_dialog.cpp, rpcs3/rpcs3qt/pkg_install_dialog.h
Dialog allows users to preview the order in which PKG's will be installed and allows users to move items around if needed.
Because clicking "Install" on this new dialog acts as a confirmation and user has a second chance to eyeball what is to be installed, "Install package X?" dialogs have been removed and instead user is only notified of success. In case of failure, batch installation aborts with a descriptive error.
This should greatly help setting up games with lots of patches, like Gran Turismo.
That's what the dialog looks like:
=> Qt: Add a dialog to Batch PKG Install

rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
- All registers tested on hw show contents to be 0, 0, 0, 1. Make default output registers match this pattern.
Fixes broken output in games with shaders that do not properly initialize the whole register block and makes the missing grass in flower visible.
=> rsx/vp: Properly initialize vertex output registers.

rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_fs.h
As a side effect, protect dev_bdvd mount from accidental unwanted changes.
=> Implement lv2_fs_mount_point

rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/rsx_cache.h
Back in the day I left the "Loading pipeline object" step of the initial shader compilation alone and only bothered with "Compiling" step. Turns out lately AMDs shader cache finally began to work for RPCS3 with Vulkan on my end so the first "Loading" step became more evident and I decided to take a better look at it.
From what I checked I haven't missed any synchronization points but I'm definitely not keen if I'm violating Vulkan specs.
OpenGL again doesn't get any love since it doesn't like multi-threading. I don't really like the different Vulkan and OpenGL paths being nearly copies of each other but not sure on how to improve it. 
ProgramStateCache.h changes could cause problems with OpenGL but from what I understand there is only one RSX Decompiler Thread. That said, there is …
=> Multithreaded shader compliation follow-up

rpcs3/Emu/RSX/Overlays/overlay_animation.cpp, rpcs3/Emu/RSX/Overlays/overlay_animation.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp, rpcs3/Emu/RSX/Overlays/overlay_utils.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
Instead of speed, direction and distance, the user now specifies start/end offsets and how much time the transition should take.
Fixes:
- Stuttering caused from framerate estimation.
- An edge case where animations would go over their supposed limit.
Adds:
- The ability to specify arbitrary easing functions for the animations
- Implemented quadratic ease in and ease out and cubic ease in/out.
- Usage of cubic ease in/out in the trophy notification
=> overlays: Redesign animation system (add easing functions, fix bugs)

rpcs3/Emu/Cell/Modules/cellVideoOut.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json
- The auto option is used when requesting the system is works like a "dont care" specifier to tell the system to use what settings have been passed in by HDMI EDID or the user TV type setting. Since this option simulates the "TV type setting", auto makes no sense and is also not something you can select on a PS3.
=> video: Remove pointless aspect ratio option 'Auto'

Utilities/geometry.h, rpcs3/Emu/RSX/Overlays/overlay_animation.cpp, rpcs3/Emu/RSX/Overlays/overlay_animation.h, rpcs3/Emu/RSX/Overlays/overlay_osk.cpp, rpcs3/Emu/RSX/Overlays/overlays.h
- Adds fading transition implementation and applies it to the osk dialog to ease the spawning and despawning of the interface.
=> overlays/osk: Add fade transition

rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_fs.h
I made some tests and it looks like these syscalls have no observable effect.
=> sys_fs: disable sys_fs_lsn_lock/unlock and other fixes

rpcs3/Emu/RSX/VK/VKHelpers.h
Asking for partial results is borked on NVIDIA drivers; this is a spec violation:
> If VK_QUERY_RESULT_PARTIAL_BIT is set, VK_QUERY_RESULT_WAIT_BIT is not set, and the query’s status is unavailable, an intermediate result value between zero and the final result value is written to pData for that query.
However, the value written to the result is non-zero for a fully occluded object, breaking the fast result logic which assumes results are accumulating if a non-zero result is returned.
This works around the issue by not using partial results on all nvidia drivers.
=> vk: Workaround for NVIDIA occlusion query failure

rpcs3/Emu/Cell/lv2/sys_vm.cpp
Simply adds a missing argument write for sys_vm_get_statistics.
=> sys_vm_get_statistics: Write timestamp

rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/VFS.cpp
On Windows, GetDiskFreeSpaceExW is limited since it doesn't properly support long paths. It could be a problem but doesn't seem to be, since on PS3 similar functions are limited in a specific way to be able to obtain free space only by mountpoint name.
=> Minor accuracy improvements for cellFsGetFreeSize

rpcs3/Emu/Cell/SPUThread.cpp
* Use c++'s placement-new feature to assign values in a few places to allow/force optimizations.
This also allows to initialize structures which are non-copy constructible such if the type is atomic_t or one of its members is.
Examples:
* In spu_thread::cpu_init() : Initailizing spu_thread::gpr by `gpr = {};` was actually constructing a temporary std::array<v128, 128> object on the stack and then copying it into spu_thread::gpr on MSVC, now only default-initialize with memset 0 as intended.
Before:
After:
* In spu_thread::cpu_init(): Avoid using atomic instructions in spu_thread::ch_in_mbox initialization. 
* Force copy-elision when assigning std::shared_ptr object in idm::create_id().
=> Minor spu_thread::cpu_init() optimization

rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/progress_dialog.cpp, rpcs3/rpcs3qt/progress_dialog.h, rpcs3/rpcs3qt/update_manager.cpp
Improve batch package installation:
Currently - when installing multiple .pkg files - a dialog will pop up and close itself for each file with a generic message and you don't have any indication on how far the installation has proceeded. This can get annoying if you install let's say 20 patches for Gran Turismo 6.
So I unified all installations into one dialog that stays opened until all files are installed or you cancel the installation. The dialog still tracks progress for each pkg seperately, but the message was improved in order to show how many packages are left.
I also added a new parameter to the progress_dialog that patches a bug which causes the whole application to terminate when you cancel the pkg installation.
But: package installation can't be canceled immediately, so once …
=> Smoother batch package installation

appveyor.yml
Update Appveyor to Qt 5.14.
This will mainly improve high dpi settings.
- The environment variable QT_AUTO_SCREEN_SCALE_FACTOR was changed to QT_ENABLE_HIGHDPI_SCALING.
- The environment variable QT_SCALE_FACTOR_ROUNDING_POLICY was added and we default to Qt::PassThrough, which means that we don't round zoom factors anymore (e.g. 150% > 100%).
See https://doc.qt.io/qt-5/qt.html#HighDpiScaleFactorRoundingPolicy-enum
Should fix #5455
Partially handles #7204
=> Update Appveyor to Qt 5.14

rpcs3/Emu/RSX/RSXOffload.cpp, rpcs3/Emu/RSX/RSXOffload.h, rpcs3/Emu/RSX/VK/VKCommandStream.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Queueing commands on the offloader is a good idea but unfortunately
page faults can still happen causing a cyclic dependency and eventual
deadlock. Characterized by a vk::wait_for_event timed out error
accompanied by severe hitching.
- Drain the fault-able commands before pushing a submit operation to the
queue. If a fault is in progress, bypass the queue system and submit
raw. Technically this is incorrect but there isn't much that can be
done about it right now.
=> vk: Restructure command queue flushing behavior to avoid deadlock

rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/PPUFunction.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_process.cpp, rpcs3/Emu/Cell/lv2/sys_process.h
* Due to signed checks and do-while behavior of sys_process_get_id ids processing (checking bufsize), negative and 0 values are treated as 1.
* sys_process_get_id and sys_process_get_id2 are not the same syscall handling code, infact they have a few different error checks and capabilities.
Testcase : https://github.com/elad335/myps3tests/tree/master/ppu_tests/sys_process_get_id
=> sys_process: Fix sys_process_get_id, add error_code

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
Add offset range verifications in rsx::get_address for the following locations:
* RSX local memory: must not go above rsx::thread::local_mem_size.
* DMA DEVICE: must not go above 1mb.
* DMA SEMAPHORE and DMA REPORT: must not go above sizeof(RsxReports::semaphore/report) respectively.
Those offsets are all game determined, on rsx fifo corruption offsets may be invalid.
=> rsx: Verify local memory offset

rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
Attempts to grow the scratch heap if it is not large enough for whatever task is needed. This is now possible for some time since the unified resource manager was added a while ago and the same has already been implemented for other memory structures.
Also includes some misc bugfixes.
Fixes https://github.com/RPCS3/rpcs3/issues/5938
=> vk: Compute fixups

rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
This attempts to provide a workaround for a very old problem with emulation: because usually emulators choose performance and simplicty of code over cycle accuracy, some programs may not work well because of it.
In PS3 emulation this problem is generally expressed as "RSX desyncs". Whats causing those desyncs usually is that the RSX executed more code than what Cell (PPU/SPU) already prepared for it, due to "design optimizations" in many games the RSX does not always stops and waits for the Cell to write more code for it to execute.
This worked in realps3 because the Cell always won the race and provided more code than what RSX already executed.
The workaround here attempts to delay, according to setting, the RSX wake-up just about there may be an important synchronization point, allowing …
=> rsx: FIFO wake-up pause control

rpcs3/Emu/RSX/VK/VKCompute.h
Stencil dword is shared between 4 texels, make access to stencil block atomic.
- Fixes https://github.com/RPCS3/rpcs3/issues/7241
=> vk: Fix compute race condition

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
- Touch locked memory when a destination write occurs to invalidate previous sync. https://github.com/RPCS3/rpcs3/issues/7224
- vk: Fixups for depth format scaling. Avoids using floats to interpolate and also adds some missing memory barriers.
Fixes https://github.com/RPCS3/rpcs3/issues/7224
=> rsx/vk: Texturing bug fixes

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/rsx_cache.h
Fixes https://github.com/RPCS3/rpcs3/issues/7225
=> rsx: Fix section length calculations when generating new blit targets.

rpcs3/Emu/RSX/GL/GLHelpers.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
There are a lot of redundant imaging operations that can be collapsed together and combined into one step. Discovered this bottleneck when reviewing https://github.com/RPCS3/rpcs3/issues/6341
It seems OGL is the most affected, I was able to gain about 75% performance improvement at 1440p on PDF (Internal res becomes 5120x2880 for that title as it uses 4x supersampling). Doesn't seem to do much for vulkan which is already very fast in that test, but I suppose it couldn't hurt to avoid doing useless work.
Fixes https://github.com/RPCS3/rpcs3/issues/6341
=> rsx: Optimize some imaging operations

rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
Using rcpps instead of divps seem to produce values closer to realhw's, it is unknown if there is a range of values which the difference is so big it would make sense it completely fixes #5886. ~~(testers needed)~~ (tested) Currently fixes it for Captian America on all SPU LLVM variations and SPU Precise interpreter.
It seems there are alot of inaccuracies around frest and frsqesr instructions but it can be fixed after this pr.
TODO: FRSQEST as well?
=> SPU: Fix FREST

rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_grid.cpp, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/trophy_manager_dialog.cpp
Uses floating point values instead of integers for pixel ratio. Might help with #7248, test both grid and list modes for improvements.
=> Improve game icon rendering for HighDPI users

rpcs3/Emu/RSX/RSXThread.h, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/gui_application.h, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/persistent_settings.cpp, rpcs3/rpcs3qt/persistent_settings.h, rpcs3/rpcs3qt/settings.cpp, rpcs3/rpcs3qt/settings.h
Move the playtime and last_played gui settings into a new persistent_settings.dat file,
while still prefering to read the deprecated data from the CurrentSettings.ini file.
fixes #7237
=> Use persistent_settings for playtimes

rpcs3/Emu/RSX/VK/VKGSRender.cpp
Number of combined samplers changed when the killzone 2 crash regression was fixed. This introduced another regression https://github.com/RPCS3/rpcs3/issues/7263
Fixes https://github.com/RPCS3/rpcs3/issues/7263
=> vk: Fixup descriptor pool layout

rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
PPU thread name max length is 27 max excluding null character.
Truncate string properly to 27 characters when no null terminator was found.
Threaded SPU thread name max length is 127 characters excluding null terminator (otherwise return error code), also fix empty name checking logic.
=> Fix sys_ppu_thread_create/rename and sys_spu_thread_initialize thread name range

rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.h, rpcs3/rpcs3qt/settings_dialog.ui
I felt like the tooltip areas were not covering the entire area of certain settings, so I made them larger.
I needed to wrap the additional layouts with a widget because they themselves didn't seem to fire events on hover.
=> Enlarge some tooltip hover areas in the settings dialog

rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/Modules/cellVdec.h
This improves the error checks in cellVdec.
~~For me this fixes a dead end in the menus when starting a new game in Lair.~~
Edit: Turns out this was just random behaviour.
Allow experimtal AV_PIX_FMT_YUVJ420P pixel format: This is basically AV_PIX_FMT_YUV420P, but with a wider color range. So expect washed out colors at worst.
may fix #5845
=> cellVdec: improve error checks

rpcs3/Emu/Cell/SPUThread.cpp
This race could lead to spu status bits indicate RUNNING status, but cpu state being stopped.
Fix it by making sure cpu state is set before spu status.
=> RawSPU: fix race between spu start and stop

rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp
* Fixups after pull requests #7281, #6998, #7257 
* Add LS address range to the debugger, remove obsolute spu group id entry (can be determined by `spu.lv2_id | 0x4000000`).
=> Regression fixes

rpcs3/Emu/RSX/rsx_methods.cpp
One game uses texture semaphore for zcull sync which is rather bizzare. However, it works on realhw as the depth test happens before fragment shader completion.
Need confirmation that this PR does not degrade performance in ZCULL heavy games (RDR, skate series, unreal engine, etc) before I can merge. If a performance regression is uncovered even later on, I'd rather the fix be a revert of this one rather than attempted extension.
Fixes https://github.com/RPCS3/rpcs3/issues/5526
=> [TESTERS NEEDED] rsx: Sync on texture read semaphore

rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/Modules/cellSsl.cpp, rpcs3/Emu/GDB.cpp, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKDMA.cpp, rpcs3/Input/evdev_joystick_handler.cpp
Hello
I fixed some common issues in the code. Access to moved variable is not a good idea, for example. Also several unused local variables are removed. And lost `&` in a function argument.
But, some expressions are really need to be clarified, they looks like some kind of issues:
1. rpcs3/Emu/RSX/VK/VKDMA.cpp (lines 52, 213)
`VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT, 0);`
This is a same constants in a both sides of | operation;
2. rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp:696
`ctxt->selectWorkloadAddr = isKernel2 ? CELL_SPURS_KERNEL2_SELECT_WORKLOAD_ADDR : CELL_SPURS_KERNEL1_SELECT_WORKLOAD_ADDR;`
Looks legit, but in rpcs3/Emu/Cell/Modules/cellSpurs.h:114,115
`CELL_SPURS_KERNEL1_SELECT_WORKLOAD_ADDR = 0x290,`
`CELL_SPURS_KERNEL2_SELECT_WORKLOAD_ADDR = 0x290,` …
=> small improvement

rpcs3/rpcs3qt/game_list_frame.cpp
This PR extends "Remove HDD Game" option with proper failure reporting. `fs::remove_all` already returned failure but UI code ignored it.
Now in case of failure to remove game files, caches/configs are left untouched. Error message informs the use about that appropriately.
Fixes #7228
=> Qt: Present game removal failure to the user

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Do not sample from incomplete textures! Raises minimum texel completeness to 99% if only one texture is found inside a range. This should exclude textures smaller than the required and avoid introducing black regions to partial blit engine textures.
- If a trivial blit operation is happening, but a live shader_read resource exists in the same range, this signifies a flush is very likely to occur. Use CPU fallback instead for performance reasons.
- Fix blit engine resources having needless memory barriers in vulkan.
- Fix some leaking texels when flushing incomplete textures using the revised vulkan DMA system. Some extensions need to be added to properly handle strided data operations.
Fixes https://github.com/RPCS3/rpcs3/issues/6822
=> rsx: Fix a few texture data leaks

rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
Place graph text on top, split in 2 lines, center it horzintally.
Also if it's wider than the graph, match up graph's width to it.
---
=> overlays: Graph label tune-up

Utilities/bin_patch.cpp, Utilities/bin_patch.h, rpcs3/Emu/Cell/PPUModule.cpp
Adds a system for finding SPU code that was embedded in PPU executables, and allows us to patch it before it is loaded by any game code. Also prints the SPUNAME if it exists in the note section.
Patches for this system still use SPU LS (Local Storage) addresses despite the fact that we aren't loading anything into SPU LS at this time. The patch addresses are checked against each segment and patched in place.
The motivation for this was brought on by the gains that can be seen when patching out SPU EDGE MLAA (A library created by Sony to do a form of post processing anti aliasing on the CPU!) out of games. Depending on the game, framerates gains of about 15-400% can be seen from removing this effect. But rather than patching every game, every version and region of that game, It seemed more …
=> Embedded SPU elf patching

Utilities/JIT.cpp
s_unfire was written to concurrently leading to crashes.
=> Fix a crash in multithreaded spu LLVM compilation

rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/System.h
Allow x30 times the speed of vblank rate + clocks scale of original PS3.
In theory a 60 fps limit game which scales frame limit perfectly with vblank rate can be played at up to 1800 fps with this change.
And:
* Fixed lv2 sleep with Clocks Scaling.
* Make these settings dynamicaly adjustable.
=> Increase Maximum Vblank Rate and Clocks Scale

rpcs3/rpcs3qt/main_window.cpp
… is an UTF-8 character and those don't really belong in messages like this anyway.
Prevents a broken character from displaying:
=> Fix ellipsis

rpcs3/Crypto/unpkg.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h
This should fix the following issue:
When using drag&drop to install stuff the windows explorer instance was useless until the installation was complete.
=> Don't block the explorer during installations

rpcs3/Emu/Audio/XAudio2/XAudio2Backend.cpp, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/main_window.cpp
Example on a running game:
And fix re/booting when running a game, using disabled "Show Boot Game Dialog" setting and using these options in game context menu.
=> Qt: Display "Reboot With Custom/Global config" on running game

rpcs3/Emu/Cell/lv2/sys_usbd.cpp
A `return` is used which cancels out the whole function and not the device iteration loop.
=> sys_usbd: Fix bug preventing multiple USB devices

rpcs3/Emu/RSX/Common/texture_cache.h
- Allows sections reclaimed by the surface store due to overlap/inheritance to be identified and removed.
- Additionally, potentially lowers the number of flushes required per block with multiple overlaps improving efficiency and theoretically performance.
Fixes https://github.com/RPCS3/rpcs3/issues/6719
=> rsx: Remove sections that are wholly inherited by new blocks

rpcs3/Emu/Cell/Modules/cellVdec.cpp
Some of it was dumped from hw tests, some reversed from fw. (e.g. memory sizes are all hw tested, some cellVdecOpen/Query error checks reversed)
Fixes #5948
=> cellVdec: Improve cellVdecQuery and cellVdecOpen

rpcs3/Emu/RSX/Common/ProgramStateCache.h
With multiple shader compiler workers, it was possible to have multiple threads execute `get_graphics_pipeline` concurrently, with one thread adding contents to `m_storage` while another thread was executing `.find()` on it.
I only crashed on it once, but it's pretty obvious looking at the code. I scoped the find and added a reader lock to resolve this.
=> RSX: Protect m_storage.find(key) to fix a race

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/gui_application.h, rpcs3/rpcs3qt/persistent_settings.h
Use current locale for displaying last played dates in gamelist.
Also save new entries with ISO-8601 to make them readable from file when the locale shifts.
Also sets some of the groundwork for Qt translations which will eventually be implemented in the distant future.
fixes #7390
=> Use english locale for last played in gamelist

rpcs3/Emu/Cell/Modules/cellGame.cpp
* Avoid resizing string value in cellGameGetParamString in case bufsize is unusually large.
* Log not found sfo params in cellGameGetParamString/Int.
* Report fs::remove_all failure in content_permission dtor. (for unknown reasons try-catch were used but fs::remove_all shouldn't throw any)
=> cellGame: add some diagnostic

rpcs3/Emu/Cell/Modules/cellVdec.cpp
* Add a workaround codec specific information ptr passed to cellVdecQueryEx, add some groundwork for proper fix.
* Few fixes in cellVdecGetPicItem including race condition fix (vdec->mem_bias modification need to be atomic).
=> cellVdec Fixup

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h
* Following #4331, register all SPU group types with no scheduler context.
For those type don't check priority, return EINVAL in sys_spu_thread_receive_event, sys_spu_thread_group_suspend/resume.
Those are all the types with either SYS_SPU_THREAD_GROUP_TYPE_NON_CONTEXT (0x8) or SYS_SPU_THREAD_GROUP_TYPE_COOPERATE_WITH_SYSTEM (0x20) flags enabled.
* Implement SYS_SPU_THREAD_GROUP_TYPE_MEMORY_FROM_CONTAINER (0x4) flag.
* Add root permission checks for types which need it.
* Add checks in for sys_spu_thread_group_yield/resum/suspend if spceific system root group flags are set (0xf00). 
RE-ed from fw, includes types used by vsh as well.
=> sys_spu: Implement proper SPU group flags

rpcs3/rpcs3qt/qt_utils.cpp
This fixes the case on Windows where one of the paths ends up consisting only of a drive letter and no trailing slash - in which case Windows treats it as "current directory on drive X" and not "root of drive X" and GetFileAttributes throws an invalid param error.
Effectively fixes a crash on Windows when attempting to Open a folder with no game which is either a root drive directory (`C:\`) or a directory directly above it (`C:\games\`).
=> Qt: Include trailing separators in section split

rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h
- Fixes an unreported bug with OpenGL framebuffer access barriers.
- Adds RCB/RDB to OpenGL which fixes some regressions.
- Fixes an unreported barrier glitch with vulkan when MSAA is disabled.
Fixes https://github.com/RPCS3/rpcs3/issues/7316
=> rsx: Misc fixups and improvements

CMakeLists.txt
Project files are already using latest c++, so CMake should be updated to match as well. I think other compilers are exluded for a reason, so I'm leaving them out for now.
Fixes obnoxious warning spam when compiling with said combination. No change to end users.
=> Enable C++20 for MSVC when using CMake

rpcs3/Emu/GDB.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/headless_application.cpp, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/gui_application.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h
Don't update the playtime clock or the last played date on running rsx captures or ppu cache creation.
fixes #7411
=> Only start the playtime clock if it makes sense

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/game_list_frame.cpp
Pass requested configuration to recursive game load.
This should fix inconsistencies in used configs when either:
- restarting a game in the GUI
- loading a disc game that has updates installed on dev_hdd0/game
- or loading a disc game that was falsely booted from dev_hdd0/game.
Also fixes game category localization.
fixes #7433 
closes #7435
=> Fix Boot inconsistencies for Reloads

rpcs3/Emu/RSX/rsx_methods.cpp
- Adds a backend notification when point size changes.
- Refactors all those separate notifiers into one reusable template.
Fixes https://github.com/RPCS3/rpcs3/issues/6311
=> rsx: Minor improvements to backend notifiers

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLPresent.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKPresent.cpp, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/rpcs3qt/rsx_debugger.cpp
Report line and filename of caller rsx::get_address upon failure of address translation.
Note: Also added verification for RSXIO REPORT memory for offsets out of range: offset must be lower than 10m.
=> Make rsx::get_address report caller location

rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
I'm a dummy, I'll duplicate the description of previous pr (#7419) to show in build updates in discord.
That pr added empty functions stubs used by VSH and missing files for them in order to ease future work on it.
=> Compilation fix for VSH pr

rpcs3/Emu/RSX/VK/VKPresent.cpp
Fixes resizing the window in AMD GPUs which signal swapchain status with the suboptimal flag.
=> vk: Fixup for VK_ERROR_SUBOPTIMAL_KHR

common_default.props, rpcs3_default.props
This way stdcpplatest  and FH4 disabling propagates to all projects except llvm and glslang.
- stdcpplatest would need to be changed to stdcpp20 after MS actually adds it as a standard.
Maybe `common_default.props` should be loaded when building llvm and glslang the same way FH4 disabling is implemented for glslang? I wonder if that is a good decision but right now both use default stdcpp where with #7448 when using cmake to generate MSVC solution some projects use default (in VS 2019 it defaults to stdcpp17) and some use latest.
=> [MSVC][props] Move stdcpplatest and FH4 to common_default.props

.travis.yml, .travis/build-linux.bash
The changes to the docker since xenial 1.0 are as follows:
- CMake bumped to 3.16.4
- Vulkan headers and libraries bumped to 1.1.126
- Vulkan headers and libraries are now built from source, rather than based on a package
- Clang bumped to 10
- LLD added
- GCC bumped to 9
- Qt bumped to 5.14.1
- SDL2 actually added to the docker, allowed compilation test for FAudio backend.
- Qt5Svg package was specifically installed. Hopefully should fix issue #6986 
Changes to the actual repo:
- glslang submodule bumped, for some reason it wouldn't compile with clang 10.
- Xcode bumped for no particular reason.
- FAudio backend was specifically disabled. Previously it just failed to build due to missing SDL2 dependency. Now it builds fine, but it doesn't package nicely, I'm going to be looking into …
=> New Travis fun things

BUILDING.md, rpcs3/main.cpp, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/qt_utils.h
Sets the mininum Qt version to 5.14, since both travis and appveyor are now on Qt 5.14.
Needs #7459 to be merged first.
fixes #6107
fixes #7204
=> Set mininum Qt version to 5.14

Utilities/Thread.cpp
Exceptions in access violation handler is probably a bad idea.
Imagine an access violation when in mutex lock scope, I don't think platforms require to call dtor of mutex lock in this case for example.
In #7428 I replaced an explicit exception with logging, other exceptions such as narrowing failures will trigger std::terminate.
=> Make handle_access_violation noexcept

rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_grid.cpp, rpcs3/rpcs3qt/game_list_grid_delegate.cpp, rpcs3/rpcs3qt/game_list_grid_delegate.h, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/table_item_delegate.h, rpcs3/rpcs3qt/trophy_manager_dialog.cpp
I read on discord that some icons looked like crap with the "new high dpi settings" and that we should revert those changes.
So I tried it on my end and set my windows 10 scaling to 125% and it seems they looked bad after all.
- game list icons (including the colored circle for game compatibility)
- game grid icons and font (including the colored circle for game compatibility and the custom config icons)
- trophy manager icons
- the save manager icons
- and last but not least the stick deadzones in the pad settings dialog
=> GUI Icon improvements

rpcs3/Emu/Cell/lv2/sys_usbd.cpp
Improved some logic and added the SYS_USBD_ATTACH delay hack to the 2nd exit of sys_usbd_receive_event.
=> Small sys_usbd changes

rpcs3/main.cpp, rpcs3/rpcs3qt/game_list_frame.cpp
Sets the DISPLAY variable if undefined.
maybe fixes #5959
maybe fixes #4498
=> [TESTERS NEEDED] Fix opening links for linux

Utilities/geometry.h, rpcs3/Emu/RSX/GL/GLHelpers.cpp, rpcs3/Emu/RSX/GL/GLOverlays.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKPresent.cpp
It requires static_cast<> to call them.
=> geometry.h: make conversion operators explicit

rpcs3/Emu/Cell/Modules/cellSearch.cpp
This PR effectively picks up #4714 by @Brolijah and implements VFS linking in a simpler way. For reference, please refer to that PR.
I salvaged whatever was possible from `cellSearch.cpp` and added improvements on top of it, such as:
- memory leak fixes
- buffer overrun fixes
- style cleanups
Same TODO's apply - ID3 tags are not read from music or photos, sorting is also not implemented because it bases on this specific data.
For linking, instead of building a whole new VFS functionality, hard links are now created only when needed (as in, when filenames are too long) and kept as an internal `cellSearch` implementation detail until the game requests a proper link to be created via `cellSearchPrepareFile`. Only then said link is "externalized" and created as a file-to-file mount in VFS …
=> cellSearch + VFS Linking II

.travis/deploy-linux.bash
Fixes #7465 
We used to only check for `CXXABI_1.3.11` but with the recent C++ requirement bump we now also need to check for a minimum of `GLIBCXX_3.4.26`.
The related commit on the AppImageKit-checkrt side is here: https://github.com/RPCS3/AppImageKit-checkrt/commit/6645ad73baf1524a47555c647222a1435eaf6882
=> Add a check for GLIBCXX_3.4.26 support in the AppImage checker binary

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
* Fix size argument passed to `rsx::thread::read_barrier()` in image_in.
* Fix a typo in cellGcm HLE which led to memory size and io address to be x100000 as smaller as they should.
* Make fifo call/ret recovery from unexpected stack state be the same as invalid cmd recovery, add logging for its cmd hex representation in this case.
=> rsx: zcull fix, cellGcm regression fix after #7262, FIFO recovery improvements

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/IdManager.cpp, rpcs3/Emu/IdManager.h
* Fix an off by one "bug" in idm traits static asserts.
* Fix recursive locking of shared lock in scepTrophyUnlockTrophy.
* Log returned required space in sceNpTrophyGetRequiredDiskSpace, and add logging for other corner cases.
=> Minor sceNpTrophy improvements, Idm assert fix

rpcs3/rpcs3qt/rsx_debugger.cpp
Thanks to @CookiePLMonster for reporting this bug.
=> rsx debugger: Fix a crash on opening before rsx was intialized

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/util/atomic.hpp
Use std::bit_cast, reinterpret_cast and const_cast instead.
=> atomic.hpp: C-style casts cleanup

rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp
Only add the version update hint to bootable games in the gamelist.
Allow "duplicates" in the game list.
In the past we removed duplicate entries in the game list. This also happened when the source had a different path, which is common if you have multiple game data directories for a game. But that also meant that we didn't set the game version properly if we found the older patch (game data) first and discarded the second, newer patch.
In consequence you'll see multiple game data entries from now on, or even multiple same disc games if you have them added from seperate directories (who knows why you'd do that in the first place).
Also fixes a regression caused by recent localization changes, which caused the gamelist to randomly not display patched versions for disc games.
=> Fix gamelist app version and firmware version

rpcs3/Emu/RSX/VK/VKRenderPass.cpp
Turns out to properly remove subpass dependencies you have to declare at least two.
Seeks to address https://gitlab.freedesktop.org/mesa/mesa/issues/2502
=> [TESTERS NEEDED] vk: Explicitly declare null subpass dependencies

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/Emu/title.cpp, rpcs3/Emu/title.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/input_dialog.cpp, rpcs3/rpcs3qt/input_dialog.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/tooltips.h
Follow-up to #7478
Gives you the possibility to change the game window title in the emulator tab in the settings.
Removes the obsolete "Show FPS in title" settings.
=> Add custom title format to settings dialog

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
* Don't writeback data when an error returned in sceNpTrophyGetTrophyInfo.
* Fix error code of invalid trophy ID in sceNpTrophyGetTrophyInfo.
* Fix off-by-one progress callbacks count in sceNpTrophyRegisterContext, substruct 1 from "total" value reported.
This means for a trophy config with 0 trophies progress callbacks won't be executed, instead of 1 callback in master.
* Fix arguments in the first callback of sceNpTrophyRegisterContext.
Testcase for these : https://github.com/elad335/myps3tests/tree/master/ppu_tests/Unregistered%20Trophy%20Context
=> Minor sceNpTrophy Fixes (déjà vu)

rpcs3/rpcs3qt/main_window.cpp
This fixes a case where perfoming these steps would desync Game List Icon selected value with the real value:
1. Have Game List Mode set to List View and Icon size set to Tiny.
2. Change Game List Mode to Grid View and Icon size to Large.
3. Change Game List mode back to List View.
4. Observe icons are small, but Icon size is still set to Large.
=> Qt: Update Game List Icons on changing Game List Mode

.travis.yml
Thanks to @Nekotekina for the eye noticing that both the builds were using the same cache previously.
Now we specify the `compiler: ` travis variable, which enables them to have difference caches.
The GCC build is about 5 minutes behind the clang build, but it's good to be testing both compilers
=> Re-enable gcc matrix in Travis CI

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.h, rpcs3/rpcs3qt/settings_dialog.ui
=> Add apply button to settings dialog

rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/lv2/sys_ss.cpp, rpcs3/Emu/Cell/lv2/sys_ss.h
**improvements to sys_ss_random_number_generator**:
* Replace CELL_EABORT with exception.
* Improve error codes a bit.
* pkg_id == 1 should not return an error if root permission is present.
* Avoid passing vm pointers to native API, use temp buffer instead.
**cellGame/DiscGame improvements**:
* Fix cellDiscGameGetBootDiscInfo on error, always set first dword to 0, other bytes are untouched.
* Check dirName in cellGameDataCheckCreate(2), same as fw.
* Set nullptr in setParam by default.
* if setParam is null after funcStat and it's new data, return error code.
Testcase for cellGame commits : https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellGameDataCheckCreate2
beware of chonky results.
=> cellGame, sys_ss rng fixes

rpcs3/Emu/Cell/Modules/cellGame.cpp
* IsNewData is false only if PARAM.SFO exists at target directory.
* Don't create directory on error (setParam == nullptr && isNewData). (fixup)
* Return CELL_GAMEDATA_ERROR_BROKEN if PARAM.SFO exists on target directory yet is not from GD category.
Fixes #7373.
Closes #7377.
I updated the previous testcase I posted in #7547 here https://github.com/elad335/myps3tests/commit/d1809fb23efd255984ecc61e6ccc3189d89e9321 to include the new findings.
=> cellGameDataCheckCreate(2): More improvements

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLOverlays.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/Overlays/overlay_edit_text.cpp, rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp, rpcs3/Emu/RSX/Overlays/overlay_fonts.h, rpcs3/Emu/RSX/Overlays/overlay_list_view.cpp, rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk.cpp, rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp, rpcs3/Emu/RSX/Overlays/overlay_progress_bar.cpp, rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp, rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp, rpcs3/Emu/RSX/Overlays/overlay_utils.h, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/Emu/RSX/VK/VKFramebuffer.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKResourceManager.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
Rewrites font handling and rendering to support wchar types. Allows extensible support for pretty much any language in the basic multi-lingual plane and even beyond to the extended unicode planes.
Newly supported character sets include but are not limited to:
- Japanese
- Chinese
- Korean
- Cyrillic
- etc
Dialogs have been adjusted to use the new system and should therefore work out of the box. Should solve the problem where some users have to disable the native dialogs to get the emulator usable.
=> overlays: Proper multi-language support

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellAuthDialog.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUModule.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
Did some quick RE on this module to stub functionality. This is imported by Torne TV App, though the app is stuck on other things and doesn't get to the part where it calls this yet.
Thanks to Clienthax for providing bruteforce of 2 of the function names.
Library is libsysutil_authdialog.sprx named cellAuthDialogUtility internally.
=> hle: cellAuthDialogUtility

rpcs3/Emu/Cell/Modules/cellAudioOut.cpp, rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp, rpcs3/Emu/Cell/Modules/cellVideoOut.cpp
Co-authored-by: Clienthax
Torne TV App exposed an unregistered function
` E {PPU[0x1000000] Thread (main_thread) [0x005d0000]} PPU: Unregistered function called (LR=0x2a3b8)`
We figured out it was from libsysutil_avconf_ext
```
·! 0:01:52.448828 ppu_loader: ** Imported module 'cellSysutilAvconfExt' (ver=0x1, attr=0x9, 0x0, 0x0) [0x49940c]
·! 0:01:52.448829 ppu_loader: **** cellSysutilAvconfExt import: [cellVideoOutSetCopyControl] -> 0x490ecc
·! 0:01:52.448831 ppu_loader: **** cellSysutilAvconfExt import: [0x341D9459] -> 0x490eec
·! 0:01:52.448832 ppu_loader: **** cellSysutilAvconfExt import: [0x9FAA12BE] -> 0x490f0c
```
Upon checking, we noticed some functions were registered to the wrong modules. 0x9FAA12BE (cellVideoOutConfigure2) was already registered, but to cellSysutil instead of …
=> hle: Fix cellAvconfExt wrongly registered functions

Utilities/File.cpp
Fixes a lonely warning during build.
=> File.cpp: Make var ref instead of copy

rpcs3/Emu/RSX/Null/NullGSRender.cpp
It didn't clear draw ranges and failed with a verification failure in rsx_methods.h.
=> rsx: Fix NULL renderer

rpcs3/Emu/Io/PadHandler.cpp, rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/Io/pad_config.h, rpcs3/Input/keyboard_pad_handler.cpp, rpcs3/Input/keyboard_pad_handler.h
Adds new lerp factors to the keyboard pad handler in order to simulate triggers and analog buttons.
See "Analog Button Lerp Factor" and "Trigger Lerp Factor" in the yml in InputConfigs/Keyboard/.
Values Range from 0-100 as before, where 100 is instant press and 0 is never.
Currently I'm not planning any GUI element for this.
=> Add "pressure sensitivity" to the keyboard pad handler

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/tooltips.h
* Change tooltip for native UI to match current status.
* Convert "Invalid disc path registered for" log message to trace level as it was causing issues with discord bot.
=> Minor fixes

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h
This pull request adds dialog messages which inform the user when booting a game fails. This doesn't aim to give detailed techical explanations for the errors, but instead gives an simple, general explanation on the possible cause. The messages are also translateable.
As a side effect, makes emulator not log "Boot successful" when booting fails due to an error.
Example dialog:
Suggestions on how to improve wording on the messages are appriciated.
=> Show error dialogs to user when booting fails

rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
- Both ZCULL stats and ZPASS stats require hardware queries, but ZCULL stats should not contribute to ZPASS stats and vice versa!
- Disables hardware queries for ZCULL stats by themselves, we cannot generate them correctly anyway and no game so far has been found to actually use them. Should lessen the load on the backend for games that do not actually require it.
- Fixes sun shining indoors in Dark Souls
- Also significantly lowers the number of issued hw queries and could theoretically improve performance in some applications.
=> rsx: Restructure ZCULL query triggers

rpcs3/main.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/vfs_dialog_tab.cpp
Currently, when you boot a game from the command line or from the menu with File > Boot SELF/ELF or File > Boot Game, RPCS3 will resolve any symlinks in the game path. I can't think of any reason why RPCS3 should resolve such symlinks. This can break HDD (PSN) games because RPCS3 expects them to be in dev_hdd0/game. If you boot the games from the game list, this issue is not present.  This PR corrects this issue; should fix #5507 and fix #4829.
=> Don't improperly resolve symlinks when booting games.

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_fs.h
* Do not fail to create savedata on empty directory. Fixes #6689.
* Fix padding bytes reset of g_savedata_context.
* Avoid passing vm pointers to native API.
* memset 0 *fileSet and fileGet->reserved before each funcFile call, testcase : https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellSaveData_FuncFile
=> cellSaveData: Indirect fixes

rpcs3/Emu/Cell/PPUModule.cpp
Do not allow to allocate segments memory on areas beyond the reach of those functions. (overlay memory is using 0x30000000 address as base)
=> PPU exec/ovlm ldr: restrict allocations

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Previously some positive and negative (less than CELL_SAVEDATA_CBRESULT_ERR_INVALID) callback results were either continuing execution normally or returning CELL_SAVEDATA_ERROR_CBRESULT which is wrong, param error 22 should be raised instead.
=> cellSaveData: Implement/Fix param error 22 for funcFile, funcDone, funcFixed and funcList

rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/Modules/sceNp.cpp
* sceNpDrmVerifyUpgradeLicense(2): copied string from content_id is 47 chars in length at max, is no null term was found it forces string termiation.
* sceNpDrmIsAvailable(2): Same with drm path just that it's 256 chars at max.
These are due to fw executing strncpy on these strings.
=> Improve sceNpDrmVerifyUpgradeLicense(2), sceNpDrmIsAvailable(2)

rpcs3/Emu/RSX/RSXOffload.cpp
Hangs on exit if MTRSX is enabled.
=> Fix RSX Offloader thread exit (MTRSX fix)

rpcs3/Emu/RSX/RSXOffload.cpp
=> RSXOffload: fix dma_manager::sync() freeze on exit

Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/System.cpp
It's rarely necessary, but can cause unexpected problems.
thread_ctrl::spawn purge follow-up.
=> Try to purge thread detaching

rpcs3/Emu/CPU/CPUTranslator.cpp, rpcs3/Emu/Cell/Modules/cellSail.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_timer.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
* Restore behaviour for ppu_load_exec before #7506, just with more logging. https://discordapp.com/channels/272035812277878785/319224795785068545/682951364317413391
iirc vm::main and vm::user64k are the same on realhw, but it can be left to another pr.
* cellSaveData: Add error param 72, 73 checks for file write ops.
* Fix sys_timer_destroy regression.
=> Demi-regressions fixes

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
- Fix ZSTATS clears destroying ZPASS data.
- Restores workaround for buggy games that leak zcull data across frames. Happens when the application sets the stats to enabled but never reads the data using reports, causing zcull to run out of allocation pool.
Fixes https://github.com/RPCS3/rpcs3/issues/7629
=> rsx: ZCULL fixups

rpcs3/Emu/Cell/lv2/sys_timer.cpp
* sys_timer_disconnect_event_queue sets STATE_STOP regardless of port connection status.
* sys_timer_get_information sets 0 for period and next_expire if the timer is stopped.
* Fix two minor races in lv2_timer thread regarding timer.expire updating in the middle of sending an event. (see commit description for more details)
testcase : https://github.com/elad335/myps3tests/tree/master/ppu_tests/timer%20state%20info%20when%20stopped%20or%20event%20queue%20disconnected
=> Improve sys_timer_get_information

rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
It's true that after issueing a RawSPU stop request the spu thread does not need to stop immediatly, but it does need to allow further start requests to issue immediatly.
Should address #7562, and hopefully all the related freezes for it that were there even before the offending pr.
=> RawSPU: fix race condition on setting run request after stop request

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
It's ordered specially for some functions. (not in savedata_check_args)
So all callbacks before it execute normally.
Try to address #7630.
=> cellSaveData: Add null funcStat check

rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKResourceManager.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Implements execution barriers for simple scope dependencies.
- Implements event object as properly wrapped classes to allow for behavior extension.
- Implements a workaround for vkCmdSetEvent/vkGetEventStatus on AMD proprietary drivers which does not actually honor the scope dependency.
Fixes https://github.com/RPCS3/rpcs3/issues/7372
=> vk: Restructure events and add AMD driver bug workaround

rpcs3/Emu/Cell/Modules/cellVideoOut.cpp, rpcs3/Emu/RSX/VK/VKPresent.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_utils.h
If the resolution is changed via cellVideoOutConfigure, subsequent requests to cellVideoOutGetState should either match the requested setting (successful mode change) or roll back the changes to avconf completely (modeset failure).
Fixes https://github.com/RPCS3/rpcs3/issues/7349
=> rsx/video-out: Obey resolution set by application if video mode was reported to application

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
* Don't return error on fileSet->fileBuf == null if fileBufSize is 0. (there may be more to that, todo)
* Check fixedSet->dirName using the sysutil name checking.
* Check fileSet->fileName using sysutil name checking, check 8.3 format validity.
* Check fixedSet->option.
=> cellSaveData: Add some error checks for fixedSet, fileSet params

rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
Should fix regression caused by #7627
=> sys_ppu: Hotfix for detached threads

rpcs3/Emu/Cell/Modules/cellVideoOut.cpp
Do not use 'auto' aspect ratio as a display mode, it's for input only, never output. Must assign a real aspect ratio when changing mode.
=> [HOTFIX] videoOut: Resolve 'auto' aspect ratio

rpcs3/Emu/Io/GHLtar.cpp
Emulating the D-pad up/down inputs would result in duplicate presses on Guitar Hero Live.
=> sys_usbd: Fix duplicate inputs for GHLtar strumming

rpcs3/rpcs3qt/settings_dialog.cpp
- Elide game window title label
- Add tooltip with format and resolved title
- Remove max length (do not wrap text to show how ridiculous it will look if it's too long)
=> Remove game window title size restriction

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp
* Every 10 seconds
* On normal exit
=> Print PPU Syscall Usage Stats

rpcs3/Emu/Cell/Modules/cellGame.cpp
=> Fix cellGameDataCheck's game data creation with PARAM.SFO set/get

rpcs3/Emu/Cell/PPUThread.cpp
New approach better reuses existing threads.
=> Refactor PPU LLVM compiling threading

rpcs3/Emu/RSX/Common/texture_cache.h
- It is possible to have a RTV<->DSV transfer with compatible-sized formats.
Mark the depth size as typeless in such a situation to avoid crossing the aspect barrier with the API.
Discovered while investigating some crashes on AMD cards.
=> rsx/blit-engine: Account for a rare corner case

Utilities/StrFmt.cpp, Utilities/Thread.cpp, rpcs3/Emu/GDB.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/ShaderParam.h, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp, rpcs3/Emu/System.cpp, rpcs3/Input/ds3_pad_handler.cpp, rpcs3/Input/ds4_pad_handler.cpp, rpcs3/Input/evdev_joystick_handler.cpp, rpcs3/Input/xinput_pad_handler.cpp, rpcs3/Loader/TAR.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/register_editor_dialog.cpp, rpcs3/rpcs3qt/update_manager.cpp
Decreases character amount in the codebase.
=> Important fix

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp
0 - 1 results in an overflow, so writing a null character at that position is a bug. Also some cleanup.
=> Fix _sys_prx_get_module_info p0pt->filename writing with 0 size

Utilities/Config.h, rpcs3/Emu/Io/PadHandler.cpp, rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/Io/pad_config.h, rpcs3/Input/ds3_pad_handler.cpp, rpcs3/Input/ds3_pad_handler.h, rpcs3/Input/ds4_pad_handler.cpp, rpcs3/Input/ds4_pad_handler.h, rpcs3/Input/evdev_joystick_handler.cpp, rpcs3/Input/evdev_joystick_handler.h, rpcs3/Input/keyboard_pad_handler.h, rpcs3/Input/mm_joystick_handler.cpp, rpcs3/Input/mm_joystick_handler.h, rpcs3/Input/xinput_pad_handler.cpp, rpcs3/Input/xinput_pad_handler.h, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/pad_led_settings_dialog.cpp, rpcs3/rpcs3qt/pad_led_settings_dialog.h, rpcs3/rpcs3qt/pad_led_settings_dialog.ui, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/pad_settings_dialog.ui
Added a battery level indicator in the pad settings UI (only visible when DS4 handler is selected), extended `PadHandlerBase` to return a battery level and implemented a method to return battery level into `ds4_pad_handler`.
Also added a code block in `ds4_pad_handler` that allows battery level indication by changing the LED color according to a preset gradient. Currently disabled and subject to being fully implemented with a corresponding way to control the new function in the pad settings UI.
Battery indicator screenshot:
=> pad_settings: show ds4 battery status in UI; use LED as an indicator

rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_fs.h, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
Used to return accurate error codes in prx_load_module, sys_spu_image_open and overlay_load_module with the logic of sys_fs_open instead of the host OS'.
=> Implement lv2_file::open()

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/system_config.h
* Improve frame limiter accuracy.
* Improve lv2_obj::wait_timeout response time for aborting threads.
* Make stretch to display area setting dynamic.
* Make frame limiter setting dynamic.
* Redefine 'auto' frame limiter to obey vblank rate, allows to set custom frame limit according to vblank rate setting.
=> rsx: Improve frame-limiter

rpcs3/Emu/System.h, rpcs3/rpcs3qt/game_list.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/persistent_settings.cpp, rpcs3/rpcs3qt/settings.cpp, rpcs3/rpcs3qt/settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.h
- Improve network tab tooltip areas. They were really small.
-  Adds a missing boot error message dialog that appeared when you tried to restart a game that failed to boot before.
- Fixes a code bug that led to a deselection of the game in the game grid when you booted a game. It was always supposed to keep its current selection.
- Add game title and title id to the tooltips for the play/pause/resume/restart/stop buttons
- The play button's tooltip now actually says "Play" instead of "Start"
- The play button now prefers the current game list/grid selection unless a game was started with "Automatically start games after boot" set to off before.
- Removes "default" logic from the gui settings dropdown in the gui tab. When resetting to default, the current file is now changed instead.
- …
=> GUI fixes and play button shenanigans

rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
It was not matching the order laid out for normal textures uploaded from CPU.
Fixes https://github.com/RPCS3/rpcs3/issues/5731
=> rsx: Fix framebuffer native layout for X32_FLOAT

rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/NP/np_handler.cpp
Restore its logic which was commented out in #7516, probably due to incorrect setting of the SceNpId structure, so fix that as well.
=> Fix sceNpUtilCmpNpId

rpcs3/rpcs3qt/settings_dialog.ui
Not sure what happened, but according to Qt Creator the box containing aspect ratio and framelimit suddendly got implict 9 pixel wide margings to all sides.
Before:
After:
=> Fix settings layout

rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLProgramBuffer.h, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKProgramBuffer.h, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_utils.h
A critical design flaw in the async decompiler made it so that shaders that are used for exactly one draw call per application run (e.g for generating a lookup table or rendering something related to a save file entry, etc) would not get saved to disk. This is because the decompiler relied on pings from the main renderer to send back information about which shaders were ok to store instead of performing all actions by itself.
The new approach is such that the decompiler thread handles everything from the moment it receives the shader request to the saving of contents on disk, which guarantees even a shader used only once will get saved correctly for subsequent runs.
Fixes black screen in RR7 stage 'sunset heights' as well as numerous other glitches reported elsewhere wherein a game only …
=> rsx: Rewrite async decompiler

rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/rpcs3qt/game_list_frame.cpp
Came from RE.
* Other improvements:
* Don't call sys_rsx syscalls in HLE cellGcmSys from rsx code. 
* Show "Reboot" on current running game when there's no config on game context menu.
=> Add forgotten error check in sys_spu_thread_group_connect_event

Utilities/Thread.cpp, rpcs3/main.cpp, rpcs3/util/logs.hpp
Mostly addressing minor problems
=> Minor fixups

Utilities/JIT.cpp, Utilities/sysinfo.cpp, Utilities/sysinfo.h, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
This commit actually doesn't fix any problems.
I've recently noticed this little confusion in code.
All similar functions have explicit "avx" in their name. But 512 doesn't.
So I explicitly added "avx" and moved the function closer to other has_avx functions.
I didn't build the project myself, so hopefully I didn't break anything.
P.S. I would be thankful for "Amazing Contribution" tag.
P.P.S. Appreciate your work a lot.
=> Explicitly rename has_512 into has_avx512

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp, rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk.cpp, rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp, rpcs3/Emu/RSX/Overlays/overlay_shader_compile_notification.cpp, rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/Overlays/overlays.h
Closing shader compilation hints and trophy notifications canceled the pad interception during proper dialogs (OSK, save data, message dialog etc.) and led to unexpected user input in the background while navigating said dialogs.
fixes #7711
=> Fix background game input during overlays

Utilities/Thread.cpp, rpcs3/Emu/System.cpp, rpcs3/main.cpp
* It should fix error dialogs on Windows since it decomposes the arg string.
* Fixes stop watchdog to decrease its interference with the debugging.
* Fixes crash at exit (at least one of) caused by null pointer dereference.
=> Unnatural fixes

rpcs3/Emu/RSX/VK/VKResourceManager.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
Use global resource manager instead of using the 2-frame hold behavior. Fixes high VRAM usage in some games.
Fixes https://github.com/RPCS3/rpcs3/issues/7424
=> vk: Change texture cache memory management for disposed textures

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/rpcs3qt/debugger_frame.cpp
* Fix rsx capture state after fmt::throw_exception.
* Disable capture button if no game is running!
* Fix UB/race in rsx captures. (unprotected variables are read and written concurrently)
=> rsx capture: Fix regression after #7730

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/rsx_utils.h
Followup to https://github.com/RPCS3/rpcs3/pull/7766. Fixes a possible race condition between RSX thread and the offloader thread that can cause a recursive submit. Also adds a proper assert if such a condition is ever encountered.
=> vk: Fix potential MTRSX deadlock in case of a race condition

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
* Add more logging, simplify code to use std::string subfunctions and strcpy_trunc and add one more error condition.
* Allow '_' at filenames start and extension.
* Check if reading offset is valid, fix error code to CELL_SAVEDATA_ERROR_FAILURE.
* Don't create empty file on error of write ops.
* Don't allow "." and ".." filenames on funcFile, return CELL_SAVEDATA_ERROR_BROKEN.
* Check listSet->fixedListNum.
* Check listSet->fixedList, listSet->focusDirName,  listSet->newData->dirName for nullptr and its directory items names.
* Check listSet->newData->iconPosition.
* Check statSet->setParam->parental_level for old sdk.
* Return an error if listSet->focusPosition is NEWDATA and listSet->newData is nullptr.
* Simplify savedata directory list selection.
* Fixed savedata lock after …
=> cellSaveData: funcFile improvements, some error checks added

rpcs3/Emu/VFS.cpp, rpcs3/Emu/VFS.h
Thanks to @elad335 who hinted this.
I'll try to escape more invalid stuff like NUL.
=> Fix VFS escape

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/PPCDisAsm.h, rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/PPUDisAsm.h, rpcs3/Emu/Cell/SPUDisAsm.h
* Return ERROR_FAILURE on funcFile deletion failures.
* Fix adding file entries to PARAM.SFO on error after funcFile.
* Do not allow to read/write/delete directly system files (such as PARAM.SFO) in funcFile, return param error 70 in this case.
* PPU Disasm: Fix branches spacing: Null terminator was added at the end which prevented proper spacing.
So now use std::string fmt formatting and avoid adding null terminator in the first place.
before:
after:
=> cellSaveData/PPU Disasm: Minor fixes

Utilities/Thread.cpp, rpcs3/Emu/Cell/Modules/cellAdec.cpp, rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/Modules/sceNpSns.cpp, rpcs3/Emu/Cell/Modules/sys_mempool.cpp, rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/IdManager.h, rpcs3/Emu/Memory/vm.cpp
* Makes the id of the exiting ppu thread no longer available in sync with the release of its scheduler entry.
* Fixed race conditions on non-atomic idm::get + idm::remove usages. idm::get may return an object which its idm entry can be destroyed and recreated in idm, so idm::remove can remove an object which differs from the one we want and used before.
The new idm::remove overload detects it and won't remove the new object, instead it will return false and fail.
* Fixup after #7775 
* Log all guest (ps3) vm memory bases at startup.
=> Make PPU id removal after exit atomic with descheduling

rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
At first I thought its some typo I made in #7663 or something, but it actually goes way back to #6722.
Also minor optimization in sys_interrupt to avoid copying a shared ptr, instead use weak ptr. (can't move because its const)
=> PPU Disasm: Fix non-link extended BCCTR forms

rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKRenderPass.cpp, rpcs3/Emu/RSX/VK/VKRenderPass.h, rpcs3/Emu/RSX/VK/VKTextOut.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
Rewrites the Vulkan backend's handling of renderpass open/close scopes. This is made possible by previous commits refactoring renderpasses many months ago, as it would have been impossible before to dynamically open and close renderpasses on a global scale. With the new structure, renderpasses are always assumed to be in the open state and individual API driver calls that require renderpasses to be closed have to manually request to close the current renderpass. This allows the GPU to batch together related draw calls significantly improving rendering efficiency.
See https://youtu.be/iJfulnNr-eI
=> vk: Lazy evaluate renderpass scope

rpcs3/rpcs3qt/log_frame.cpp
Fixes issues where e.g. < will be interpreted as starting tag in the GUI.
Maybe there's a faster way.
Needs some performance comparison to current code.
=> log: properly escape all html except newlines

rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
* Use cpu_flag::exit instead of cpu_flag::stop to avoid issues with MMIO start requests.
* Protect spu_thread::int_ctrl from changing in sys_raw_spu_destroy.
*  Test tag.expired() inside idm shared lock in spu_int_ctrl_t::set().
* Use lv2_obj::sleep when joing interrupt ppu thread.
* Followup fix to #7663 in cellVdecClose.
* Optimization: make sys_raw_spu_destroy not copying a shared ptr, move it instead. (copied because it was const wrongly)
=> Fix sys_raw_spu_destroy

Utilities/BEType.h, rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.h, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/rpcs3qt/kernel_explorer.cpp
* Turns out the syscall does return a value from quick reversing: 0 if a context switch occured, 1 if nothing happend, although the returned value is ignored by known ps3 compilers.
* Fixed a regression from #6933 which made the condition `prio != -4` always evaluate to true, leading to false early returns from yield.
* Uncomment sys_ppu_thread_stop/restart as their handlers functions exist.
* Move name64 helper to lv2_obj::name64, use std::string_view instead of temporary NTS string.
* Use common initial sequance in v128 to partially obey 'strict type aliasing'.
=> Fix sys_ppu_thread_yield

rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp, rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.h, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.h, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_sync.h
liblv2.sprx's sys_lwmutex/lwcond_create functions load the attribute's name (type=char[8]) via `ld` (big endian 64-bit) instruction in LLE.
Then name (type=u64) argument passed to the syscalls _sys_lwmutex/lwcond_create  which treat it as big endian as well on ps3 fw, so we need to byteswap it as well before reading as a NTS-like string.
Of course this also means that our HLE sys_lwcond/lwmutex_create liblv2 functions also need modification to byteswap when passing name argument to the syscalls.
This applies to related log messages as well.
Before:
After:
=> Fix lv2 sys_lwcond/sys_lwmutex kernel explorer names

rpcs3/Emu/Cell/PPUTranslator.cpp
This PR improves the accuracy of the `VMADDFP` and `VUMSUBFP` PPU instructions. `VMADDFP` was written to use native FMA if possible, but I couldn't get the accuracy of `VNMSUBFP` to match the behavior of the emulated FMA path, so it's not using native FMA for now.
This fixes an issue in Nier that caused a boss's turn rate to go haywire, which would then cause the boss to dive out of bounds rendering the fight impossible.
fixes https://github.com/RPCS3/rpcs3/issues/7158
I tested against the tests here: https://github.com/RPCS3/ps3autotests/tree/master/tests/cpu/ppu_vpu
ppu_vpu diff against master
[diff_vpu_fma_master.txt](https://github.com/RPCS3/rpcs3/files/4349762/diff_vpu_fma_master.txt)
ppu_vpu diff against this pr
[Diff_vpu_fma_pr.txt](https://github.com/RPCS3/rpcs3/files/4349773/Diff_ …
=> PPU LLVM: Improve VMADDFP and VNMSUBFP

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/rpcs3qt/debugger_list.cpp, rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/rsx_debugger.cpp
* Fix a segfault when viewing unmapped memory as image in memory viewer, simply do nothing in this case. Also use super ptr because non-emu threads do not support rsx access violation handling.
* Remove one '>' or space from the disassembler view, there were 4 characters reserved only for breakpoints which looked weird imo, now there are only 3.
Also make it consistent with 'no thread' view, add the remaining 3 spaces there as well.
* Fix memory leaks regarding wrong usage of QImage passed raw pointers in rsx debugger and memory image viewer.
* Fix a corner case when viewing unaligned spu memory at the end of SPU LS by force aligning the address to 4 bytes. For non-aligned memory view the proper memory viewer tool should be used instead of the disassembler.
* Avoid a segfault when reading …
=> Minor improvements for debugging tools

.travis/build-linux.bash
Turns out linking with LTO still doesn't play nice with Qt.
=> Revert using LTO in AppImage

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellOskDialog.cpp, rpcs3/Emu/Cell/Modules/cellOskDialog.h, rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk.h, rpcs3/Emu/RSX/Overlays/overlay_osk_panel.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk_panel.h, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/osk_dialog_frame.cpp, rpcs3/rpcs3qt/osk_dialog_frame.h
- Refactors the overlay osk to use panels that can be switched out dynamically
- Fixes wrongly enabled control buttons (shift and layer/mode)
- Fix Full-Width alphabet, which could not be displayed before
- Uses L2 and R2 for switching between the panels
- Adds URL Panel
- Adds Password Panel (No *** yet)
- Adds Halfwidth Numeric Panel
- Adds Fullwidth Numeric Panel
- Adds Halfwidth Alphabet Panel
- Adds Fullwidth Alphabet Panel
- Adds Basic Japanese Panel (no dictionary)
- Adds Basic Hiragana Panel (no dictionary)
- Adds Basic Katakana Panel
- Adds English Panel
- Takes the osk panel modes passed by games into account and uses the system language by default
- Uses English Panel as Fallback for other languages
TODO:
- Add visual clues for current/available panels and L2/R2
=> overlays: implement osk panels

rpcs3/rpcs3qt/game_list_frame.cpp
For some reason these requested changes weren't applied in other PRs 🤔 
Using ternary inside translates will result in their absence from the translator files.
=> Fix some bad translation strings

Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp, rpcs3/Emu/System.cpp, rpcs3/rpcs3qt/main_window.cpp
State after calling thread emergency_exit() function.
Also default-construct thread result in this case.
=> Implement thread_state::errored

rpcs3/Emu/Cell/PPUInterpreter.cpp
Those are double precision instructions, not actually single as suggested (they only cast to single at the end of operation), thus they require fma as well because the double-precision arguments multiply+add is not enough. I didn't think about it in #6556 because of a misunderstanding.
=> PPU Precise: Fix FMADDS, FMSUBS, FNMSUBS, FNMADDS

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/Modules/cellUserInfo.cpp
* Add CELL_SAVEDATA_ERROR_NOUSER if user does not exist, check if userId is greater than CELL_SYSUTIL_USERID_MAX (param error 91).
* Set listSet->focusPosition to LISTHEAD by default, REd.
* Add error checks for cellSaveData(User)GetListItem: check dirName for nullptr, name format, id > CELL_SYSUTIL_USERID_MAX, user existence.
* Allow stat == nullptr in cellUserInfoGetStat, fix error code of id > CELL_SYSUTIL_USERID_MAX to param error 1 (REd).
* Skip directory items in savedata_get_list_item.
* memset 0 setBuf->buf (to bufSize) before funcStat if the savedata direcory is not new.
* memset 0 setBuf->buf (to bufSize) if listGet->dirNum became non-zero (listGet->dirListNum can be zero yet memset still occurs) .
* Clear traces of setList setup in setBuf->buf before funcStat (after …
=> cellSaveData: Add some error checks and default values of some members

rpcs3/Emu/RSX/RSXThread.h
- Tweaks attrib divisor optimization logic a bit. Fixes particle rendering in Rachet & Clank future fames which resulted in vertex explosion before.
=> rsx: Properly calculate vertex range when divisor is active

rpcs3/Emu/Cell/Modules/sys_spinlock.cpp, rpcs3/Emu/Cell/PPUFunction.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
* Implement the ability to view lwmutex owner and lock count, this is a debugging feature.
* Do not lose r3's content in syscalls to allow to get lv2 sync objects id by looking at r3 whenever a syscall happens.
=> kernel explorer: Implement ability to view lwmutex owner

rpcs3/Emu/Cell/SPUThread.cpp
In some very unscientific benchmark, at some spot in NieR:
`spu_thread::do_dma_transfer()` was taking 2.27% of my CPU before, now 0.07%, while `__memmove_avx_unaligned_erms()` was taking 1.47% and now 2.88%, which added makes about 0.8% saved.
=> [Testers Needed] SPU: Copy with memmove() instead of hand-rolled SSE2

rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/curl_handle.cpp, rpcs3/rpcs3qt/curl_handle.h, rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/localized.cpp, rpcs3/rpcs3qt/localized.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/update_manager.cpp, rpcs3/rpcs3qt/update_manager.h
- The welcome dialog is now shown before showing anything else.
- The auto update will be delayed until the welcome dialog was closed
Furthermore:
- Simplifies some code and fixes a log message in the update manager
- Unifies the displayed (translateable) string for verbose time displays (Last played in game list and time difference in update manager message box)
=> Fix Welcome Dialog interfering with Update Manager

rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/screenshot_manager_dialog.cpp, rpcs3/rpcs3qt/screenshot_manager_dialog.h, rpcs3/rpcs3qt/screenshot_preview.cpp, rpcs3/rpcs3qt/screenshot_preview.h
This adds a very basic screenshot manager to Manage->Screenshots.
The screenshots are read from the actual screenshot directory, which contains the screenshots made by the user as well as the screenshots made by the cellScreenshot utility.
Currently there is no distinction in the viewer.
You can doubleclick an image to open a preview that can be resized, stetched and even copied to the clipboard.
I think this is a nice base for future improvements and kept simple enough so that new contributors may practice their skills.
=> Screenshot manager

rpcs3/rpcs3qt/pad_led_settings_dialog.cpp
fix build with Qt 5.15
~~~
[ 96%] Building CXX object rpcs3/rpcs3qt/CMakeFiles/rpcs3_ui.dir/save_data_info_dialog.cpp.o
/tmp/makepkg/sl1-rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/pad_led_settings_dialog.cpp: In member function 'void pad_led_settings_dialog::redraw_color_sample()':
/tmp/makepkg/sl1-rpcs3-git/src/rpcs3/rpcs3/rpcs3qt/pad_led_settings_dialog.cpp:82:15: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined
82 |  QPainterPath path;
|               ^~~~
~~~
=> Fix build with Qt 5.15+

rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
If lwcond_waiters became zero after was set to be destroyed ibefore it t means that destroyed bit was turned off and all lwcond waiters quit (but lwmutex sleep queue state is unknown), so need to recheck lwmutex sleep queue and set/relock destroyed bit in this case to ensure it stays this way.
=> Another fixup after #7826

appveyor.yml, rpcs3/Emu/Cell/PPUTranslator.cpp
Strange codegen bug didn't promote s32 to u64.
=> Workaround for VS 16.5

rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp, rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.h, rpcs3/Emu/RSX/RSXThread.cpp
In realhw this mode uses the lwmutex only to emplace the thread into the lwmutex sleep queue and then unlock immediatly the lwmutex, it means the ordering of the current lwmutex sleep queue needs to be respected. 
Also followup for #7663 in sys_lwcond and sys_cond reagrding ppu threads existence checks.
=> _sys_lwcond_signal: Make mode 3 respect ordering of the sleep queue

rpcs3/main.cpp, rpcs3/rpcs3qt/update_manager.cpp
Increase timeout to 10s before giving up, in the case of updating.
=> Improve auto-updater experience

rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
I was surprised to see sysPrxForUser (liblv2 HLE related) channel in the log even when liblv2.sprx is LLEd by default, then I relalized we were calling the HLE handlers of sys_game_process_exitspawn(2) unconditionally.
Hopefully I've written it right.
=> Make sceNpDrmProcessExitSpawn(2) execute sys_game calls correctly

rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk_panel.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk_panel.h
- Adds all the remaining panels
- Improves the URL panel
- Refactors some of the logic into the osk panel parent class
Known issues:
- The chinese panels are almost useless because there is no dictionary.
- The Special character sections may differ from PS3 for some panels (I forgot to take screenshots) 
- The translations for the control buttons of the different panels are missing
- There still is no indication for choosing panel modes (currently we use L2/R2)
=> Add more OSK panels

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/qt_utils.h, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/screenshot_manager_dialog.cpp, rpcs3/rpcs3qt/screenshot_manager_dialog.h, rpcs3/rpcs3qt/screenshot_preview.cpp, rpcs3/rpcs3qt/screenshot_preview.h
- Adds "Open File Location" to the screenshot preview context menu
- Adds a form of lazy loading to the screenshot manager to hopefully fix crashes caused by huge amounts of screenshots
=> Improve Screenshot manager

rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/Cell/lv2/sys_prx.h
* Implement sys_prx_get_module_list: Used by sys_prx_exitspawn_with_level to get list of modules and call sys_prx_stop_module for each module id, which (I think) is used by exitspawn functions and normal prcosess exit.
* Add missing logic and error codes for sys_prx_start/stop/unload_module.
=> sys_prx Improvements

rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h
* Fix NV308A_COLOR methods range.
* Batch NV308A_COLOR methods execution together (optimization).
* Fix termination of bind_range<> in rsx methods binding.
* Reset all method registers at each boot. 
Fixes #6803
Fixes #3493
=> rsx: Improve NV308A_COLOR

rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
Hint the user to increase Driver Wake-up Delay in this case.
=> rsx: Implement basic infinite FIFO desync detection

rpcs3/Emu/Cell/Modules/sys_prx_.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/RSX/RSXThread.cpp
* Add more u16 relocations (4, 5, 6) support for instructions which already supported atleast one of them inclusing ADDIS as mentioned in #7855.
* More strict infinite desync detection, 
* Fix sys_prx_start/stop_module in liblv2.sprx HLE, add missing result reset.
=> PPU LLVM: Add relocation 5 for ADDIS

rpcs3/CMakeLists.txt
Same as https://github.com/RPCS3/rpcs3/commit/a5ba4a18dfed96a24e98c512013322aae385559e but for cmake
=> cmake: Fix windeployqt command line for release builds

BUILDING.md
Makes the links of the prebuilt LLVM and glslang libs point to the `_mt` version, as the current ones make RPCS3 fail to compile on latest. Thanks to @JohnHolmesII for pointing me to it.
=> Update building instructions

Utilities/StrFmt.cpp, Utilities/StrUtil.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/curl_handle.cpp
Roundabout way of getting ansi path out of utf-8 path but tested and it works.
This should fixes issues where `Problem with the SSL CA cert (path? access rights?)` error was reported.
=> Gives ANSI path to curl CURLOPT_CAINFO

.gitignore, rpcs3/Emu/Cell/Modules/cellSysutilNpEula.cpp
Bruteforced remaining function names with Clienthax and elad helped with verification on argument types
Stubs the module's functions.
=> hle: cellSysutilNpEula

azure-pipelines.yml
See azure docs
> Target | (Required) This is the commit SHA for which the GitHub release will be created. E.g. 48b11d8d6e92a22e3e9563a3f643699c16fd6e27. You can also use variables here.
=> Change target to the correct commit SHA on RPCS3/RPCS3-binaries-win side

3rdparty/CMakeLists.txt
ABI is not an issue on rolling distributions (e.g., Arch, FreeBSD) because packages are frequently rebuilt. libcurl upstream frequently publishes vulnerability fixes, so I'd prefer to avoid chasing updates downstream.
See [example build log](https://github.com/RPCS3/rpcs3/files/4396158/rpcs3-0.0.9.10053.log).
=> Allow using system libcurl

rpcs3/Emu/Cell/lv2/sys_event.cpp, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_mutex.cpp, rpcs3/Emu/Cell/lv2/sys_net.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
Second attempt at implementing this, the first attempt didn't work out because of bug in cpu_thread::check_state() which has been fixed.
It is already implemented in sys_cond_wait on master which works well.
=> lv2: Wait for rescheduling before confirming timeouts

rpcs3/Emu/RSX/Common/ProgramStateCache.cpp
log spam from analyzer was lowering fps in R&C and maybe others (Resistance 3?). In this case there was a huge FPS boost from 23 to 66fps. This stops the output to be less/once a loop rather than every instruction. 
Games that spam this should improve. 
**RSX: vp_analyser: Possible infinite loop detected**
<details>
<summary>Before</summary><p>
</p>
</details>
<details>
<summary>After</summary><p>
</p>
</details>
=> RSX: Restrict analyser loop error

README.md
Change Project ID from 5 (RPCS3.glslang) to 4 (RPCS3.rpcs3)
previously leads to RPCS3.glslang instead of RPCS3.RPCS3
=> readme.md: Fix Azure Badge URL

rpcs3/Emu/Cell/PPUModule.cpp
Embedded spu elfs are actually 128 byte (1024 bit) aligned, not 4 byte (32 bit) aligned like I thought earlier.
I was mislead earlier since the word ELF appears in binaries at 32 bit alignment sometimes, but these weren't true elf headers, just the word ELF on its own.
This shouldn't really impact anything beyond making games boot ever so slightly faster.
=> Fix alignment on embedded spu elf searching

.travis/deploy-windows.sh, .travis/export-azure-vars.sh, .travis/setup-windows.sh, Utilities/git-version-gen.cmd, azure-pipelines.yml
The latest installment in my never-ending PR series.
Info in commits.
=> More CI/Build Fixes

rpcs3/rpcs3qt/emu_settings.cpp
Not sure when it regressed. I don't usually test builds without Vulkan.
```
In file included from rpcs3/rpcs3qt/emu_settings.cpp:16:
In file included from rpcs3/Emu/RSX/VK/VKHelpers.h:18:
In file included from rpcs3/Emu/RSX/GSRender.h:3:
In file included from rpcs3/Emu/RSX/RSXThread.h:10:
In file included from rpcs3/Emu/RSX/rsx_cache.h:11:
In file included from rpcs3/Emu/RSX/Common/texture_cache_checker.h:3:
In file included from rpcs3/Emu/RSX/Common/../rsx_utils.h:3:
rpcs3/Emu/RSX/../system_config.h:1:5: error: bootlegging test
```
=> Unbreak -DUSE_VULKAN=OFF build

rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
As long as owner LSB is set sys_rwlock_tryrlock and sys_rwlock_rlock would think the rwlock is unavailable, so clear this bit on last writer waiter so the readers can see its availabilty again.
Heck, sys_rwlock_rlock can wait forever waiting for a non-existing writer to quit in this case.
=> Fix sys_rwlock_wlock timeout event

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/system_config.h
Force allowed rsx main memory range to be 512mb, only if debug console mode is enabled.
This is compatible with rsx capture, ps3 memory availability, FIFO registers and commands address clamping, rsx method registers offset clamping and many more.
This is somethong that rsx allows in realhw but was forcefully disabled in gcm. (TODO..)
=> rsx: Implement DECR memory layout

rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_net.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp
* Replace writer lock with reader lock in sys_lwcond.
* Fix wrong boolean change in #7906.
* Read buffer in sys_net_bnet_sendto only when needed.
=> Some typos

.gitignore, Utilities/Config.cpp, Utilities/Thread.cpp, rpcs3/Crypto/key_vault.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/Emu/system_config.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/util/logs.cpp, rpcs3/util/logs.hpp
It is possible to change log levels for all the log channels by editing the config file.
Previously, the log levels were applied whenever a config file was decoded.
This meant that we updated the log channels whenever any config file, either global or custom, was read. Apart from being suboptimal in the first place, this also meant that changing the "Silence All Logs" option was ignored whenever a config was changed.
So what did I do to improve the situation?
- The channel map will only be applied to the log channels when we actually apply a config
- Custom configs do not override the global setting anymore and vice-versa
Figure out a better way to apply the interaction between silencing and changing levels:
- At rpcs3 boot ?
- Can custom configs also non-cell-channels, like GUI or …
=> Try to make log silencing dynamic

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/PPUTranslator.h, rpcs3/Emu/system_config.h
Followup for #7135, implements as "PPU Accurate FMA" setting in config file. When this option enabled changes PPU cache version changes and if you do not have cache for x option state it will generate new PPU LLVM cache.
Note that the setting is enabled by default, and for cpus with hw FMA support it can't be disabled.
=> PPU LLVM: Add FMA accuracy setting

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKRenderPass.cpp
- Remove obsolete RADV workaround fixed in newer spec version.
- Remove obsolete NVIDIA workaround fixed in newer drivers.
- Reduce unwanted log spam when compiling shaders.
Fixes https://github.com/RPCS3/rpcs3/issues/7896
Fixes https://github.com/RPCS3/rpcs3/issues/7897
=> rsx: Misc cleanup

rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h
* Batch vertex program load methods.
* Detect data changes of vertex program.
* Remove `rsx::thread::invalid_command_interrupt_raised` flag.
* Reset vertex program/constants at each boot.
* Add more conditions to fragment data program invalidation in NV308A_COLOR. (and fixes a regression from #7846), and add more invalidation checks for IMAGE_IN and BUFFER_NOTIFY.
TODO: Comapre raw fragment shader data in case changed by memcpy etc.
=> rsx: Batch vp program load methods, improve vertex/fp program invalidation

rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_cond.h
Don't rely on misleading reference count of lv2_cond to end before declaring that the cond var is detached from mutex, instead do it immediatly in sys_cond_destroy.
=> Fix sys_cond_destroy

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/rpcs3qt/register_editor_dialog.cpp, rpcs3/util/atomic.hpp
Consists of some fixups after #7905, #7825 and minor spacing fixes.
Still a TODO: Fix the need to scroll after setting/removing ppu breakpoint for it to be displayed properly. (regression from #7905)
=> Minor debugger fixups

rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp, rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp
Forgot to set lwmutex owner to reserved.
bonus: Implemented as atomic op.
=> liblv2 HLE: Fix sys_lwcond_signal mode 3

rpcs3/Emu/Cell/PPUThread.cpp
=> Fix ppu_thread::dump_callstack()

Utilities/sysinfo.cpp, Utilities/sysinfo.h
Adds detection for FMA3 and FMA4, along with INVARIANT_TSC
These aren't used anywhere yet.
Fixes https://github.com/RPCS3/rpcs3/issues/7916
=> Util: Add FMA and INVARIANT_TSC detection

rpcs3/Crypto/unedat.h, rpcs3/Emu/Cell/Modules/cellFs.cpp, rpcs3/Emu/Cell/Modules/cellSysCache.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_fs.h
Thanks for @CookiePLMonster for debugging, implemented as an atomic NPDRM file descriptors count check at creation.
Should fix #4091
=> sys_fs: Limit NPDRM FDs to 16

Utilities/Config.cpp, Utilities/Config.h, rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/system_config.h
Fixes PS1 Classics with SPU LLVM.
=> SPU LLVM Improvements

Utilities/StrFmt.cpp, rpcs3/rpcs3qt/update_manager.cpp
Instead of relaunching old executable launch rpcs3.exe.
For Hula mainly :D.
=> Always launch rpcs3.exe on restart

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
Stack size specified seems to be one-to-one with reduced memory stats after ppu thread creation, even if isn't 64k aligned. So implement this functionality.
=> sys_ppu_thread: reduce global memory stats after thread creation

rpcs3/Emu/Cell/Modules/cellSearch.cpp
It makes sense to change cellSearch state before invoking an user callback, since it acts as a broadcast for state change. WipEout HD uses those callbacks to start a new search, which would errorerously fail due to cellSearch still being "busy".
This "fixes" WipEout HD's searches failing - since it relies on yet unimplemented playlists, custom songs still don't work but now the game thinks search has succeeded and found 0 entries (instead of failing).
=> cellSearch: Change search state before invoking callbacks

Utilities/sysinfo.cpp
Try to get rough TSC frequency by sampling it.
Should fix "TSC: Bad" in most cases.
Please report your results after running RPCS3 several times (10-20).
=> [WIP] Implement TSC calibration

rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/microphone_creator.cpp, rpcs3/rpcs3qt/microphone_creator.h, rpcs3/rpcs3qt/settings_dialog.cpp
=> Even more translation fixes

Utilities/sysinfo.cpp
Save first TSC value and reuse it.
=> Optimize utils::get_tsc_freq()

rpcs3/Emu/Cell/Modules/cellGame.cpp
=> Fix cellGameDataCheckCreate2 error broken check

rpcs3/Emu/Cell/Modules/cellSysutil.cpp, rpcs3/Emu/Io/KeyboardHandler.cpp, rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/pad_settings_dialog.ui, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/tooltips.h, rpcs3/rpcs3qt/trophy_notification_frame.cpp
- Extended the names of the XMB's languages (what was the reason why these were shortened?).
- Added some missing spaces before the parentheses in the keyboard options.
- Fixed some typos.
- Tweaked the wording of the tooltips and added some ending periods.
- Changed a couple of terms to follow the official namings. I have other official naming changes, but I'm unsure if those are interesting or not for the team, so I haven't added them into the PR.
- Changed one tooltip so the "If unsure..." structure is followed.
=> Linguistic changes

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
* Write FIFO get+put atomically in FIFO start command.
* Reset and set flip flip flags atomically, the gcm methods neither use a lock so it's a expected that sys_rsx will handle synchronization.
* Always wait for sys_rsx events to be sent, EBUSY is not a success error code! (EBUSY means the event queue is full by the time of sending the event)
* Optimize vblank events by squashing it into one event instead of two.
* Send events only if they are masked by gcm.
=> sys_rsx: Minor atomicity fixes

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp
ppu_thread::dump_misc() has been detached from cpu_thread::dump_misc(), call each separately in ppu_thread::dump_all(). (same for spu_thread)
=> Fixup ppu/spu_thread::dump_all()

rpcs3/Emu/Cell/Modules/sys_ppu_thread_.cpp, rpcs3/Emu/Cell/PPUCallback.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.h, rpcs3/Emu/Memory/vm_ptr.h
Function descriptor should be read immediatly in _sys_ppu_thread_create by the calling thread, in interrupt thread it occurs every interrupt is being sent and in other ppu thread types its being done asynchronously by the created thread which both are wrong.
In theory it protects against cases where the function descriptor is being overwritten after the creating thread syscall ended but shouldn't happen in reality in games iirc, so it's just an accuracy improvement. 
Also log ppu thread start entry, example: `_sys_ppu_thread_create(): Thread “LIBDG_dummyflip” created (id=0x1000011, func=*0xf8cdc, rtoc=0x3df5e8)`
=> sys_ppu_thread_create: read function descriptor immediately and save it

Utilities/sysinfo.cpp, rpcs3/Emu/Cell/SPUThread.cpp
I realized that the calibration was more accurate than I initially thought, and the TSC frequency rarely equals CPU frequency.
=> Tweak TSC calibration

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/system_config.h, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/emu_settings_type.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/tooltips.h
Note: the setting's value of "PPU Accurate FMA" will reset.. it has been renamed to "LLVM Accurate FMA".
Also fix a corner case of SPU FNMS in LLVM decoders.
=> SPU LLVM: Add accurate double-precision FMA support

rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/tooltips.h
Follow-up to #7981
If you had a CPU with FMA support, the option was greyed out and it was showed as unchecked. This PR aims to fix that. It also tweaks the tooltip for the option a bit to reflect that you can't disable it if your CPU has FMA support, and simplifies the code.
Master:
This PR:
Waiting for my `Amazing Contribution` label, tyvm
=> Show state of Accurate LLVM DFMA option in GUI for CPUs that support FMA

rpcs3/Emu/IdManager.h
Use std::static_pointer_cast in a few places to better mark the intent, also use std::move and copy elision wherever seems appropriate to avoid redundent copies.
=> idm: Minor update to use std::static_pointer_cast

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Common/texture_cache_helpers.h, rpcs3/Emu/RSX/GCM.h, rpcs3/Emu/RSX/GL/GLHelpers.cpp, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
* Implement LLE cellGcmSysGetLastVBlankTime.
* Check zcull/tiles offset if bigger than memory limits of MAIN/LOCAL memory.
* Check memory mapping of offset if location is MAIN.
* Check pitch/size for 0 as coming from hw tests.
* In addition: fix 'bound' check of tiles, seem to rely on the bits location is in. (0 means not bound, anything else is bound)
* Add locks for zcull/tiles/displaybuffer binding.
* Fix vblank thread stop regression from #7978, add missing emulation state check in EBUSY wait loop.
* Fix get_optimal_blit_target_properties for local memory.
* Write FIFO ref+get atomically.
* Warn if RSX is not idle during crucial points.
=> sys_rsx: Implement cellGcmSysGetLastVBlankTime, add some error checks

Utilities/types.h, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/lv2/sys_usbd.cpp, rpcs3/Emu/IdManager.h
Fixes huge regression from #7998 because std::static_pointer_cast doesnt have rvalue reference overloads yet.
=> Implement ::as_rvalue

rpcs3/Emu/Cell/PPUTranslator.cpp
One quirk of the altivec ISA is that only floating multiply add (FMA) and floating add instructions are provided. To execute a floating multiply without an add you had to execute an FMA with an addend of 0. 
Let's detect this case and emit only a floating multiply when a constant addend of 0 is used.
On skylake the gains are very small, since FMA and floating multiply ops are executed with the same latency, but on ryzen floating multiply has lower latency than FMA, so it may benefit more. Anything without native FMA support should also benefit plenty.
=> PPU LLVM: Optimize altivec FMA with 0 addend

Utilities/Thread.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/Emu/Cell/lv2/sys_mutex.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
Ensure IDM is not locked by the current thread waiting on page fault notification.
=> vm: Fix possible IDM deadlock with Page Fault Notifications

Utilities/BEType.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.h
* Obey strict type aliasing rule in rsx fragment/vertex program analyzers.
* Optimize instructions reads using SSE loads instead of using references/pointers to specific instruction members at a time. (memcpy 16 bytes is compiled to unaligned 128-bit SSE2 loads and stores)
* Remove lots of reinterpret casts, make the code easier to read.
* Replace `qword` type with the much more useful `v128` type which provides extra utilities such as builtin operators ==, != for instruction comparisons.
=> rsx fp/vp analyzers: Fix strict type aliasing and improve codegen

rpcs3/Loader/TAR.cpp, rpcs3/util/atomic.hpp
For some reason it fails to overwrite font files for some users.
This is an attempt to workaround this problem.
=> Fixup for firmware installer

Utilities/types.h, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_net.cpp
I saw Gran Turismo 5 still fails randomly with access violations on Network Thread due to incorrect handling of page faults notifications even after #7901, so Instead of hunting down each case I've decided to fix them all at once.
Additional improvements:
- Added many EINVAL checks.
- Added missing write to optlen in sys_net_bnet_getsockopt.
=> sys_net Fixes

rpcs3/Emu/Cell/PPUThread.cpp
=> PPU: Merge reservations store functions into one

rpcs3/Emu/Cell/lv2/sys_net.cpp
Turns out I revived a "sleeping" bug in #8019, never read from `addr` if it's null, before the mentioned pr it would have always done that for  SYS_NET_SOCK_DGRAM_P2P socket type so fix that as well.
=> Fix sys_net_bnet_sendto

.ci/setup-windows.sh
This allows the Continuous Integration System to continuously integrate the latest libs from dependencies.
Relies on https://github.com/RPCS3/glslang/pull/1 being merged.
=> CI: Auto update LLVM and GLSLANG when those releases change

rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/ring_buffer_helper.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLDraw.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLProgramBuffer.h, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp, rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_utils.h, rpcs3/rpcs3qt/cheat_manager.cpp, rpcs3/rpcs3qt/rsx_debugger.cpp
Fix warnings found with `-Wimplicit-fallthrough=5`
@RipleyTom Can you confirm the fallthrough is expected in `rpcs3/rpcs3qt/cheat_manager.cpp`? It looks a bit suspicious to me but since I didn't take the time to understand your code, I don't really know.
=> Add fallthrough attribute

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
Dump current blocking SPU functions, currently includes two functions: sys_spu_thread_receive_event and MFC events reading.
Also show the amount of time each thread spends on it from the time the function starts until current time.
Allows to detect some SPU deadlocks for example.
=> SPU debugger: Implement blocking functions dumping

Utilities/asm.h, Utilities/cfmt.h, Utilities/cond.h, rpcs3/Emu/Cell/PPUAnalyser.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUOpcodes.h, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPUThread.cpp
Partial revert due to bad codegen.
Also fixed missing include removal.
=> Revert "Replace rotate utils with std::rotl"

.ci/build-linux.sh, CMakeLists.txt, rpcs3/CMakeLists.txt, rpcs3/Emu/CMakeLists.txt
From [cotire's README.md](https://github.com/sakra/cotire/blob/master/README.md):
> The functionality provided by cotire has been superseded by features added to CMake 3.16. Support for pre-compiling and unity builds is now built into CMake. Thus, there will not be any further updates or support for this project.
With CMake 3.16, `target_precompile_headers` can be used to replace cotire's pre-compiling functionality.
=> cmake: Add support for target_precompiled_headers if available

rpcs3/Emu/RSX/GL/GLDraw.cpp, rpcs3/Emu/RSX/GL/GLPresent.cpp, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKDraw.cpp, rpcs3/Emu/RSX/VK/VKPresent.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/system_config.h
- Makes "Anisotropic Filter Override" dynamic
- Makes "Use full RGB output range" dynamic *
- Makes "Enable Frame Skip" dynamic *
- Makes "Consecutive Frames To Draw" dynamic *
- Makes "Consecutive Frames To Skip" dynamic *
* Needs manual change in config.yml and saving settings once
=> Make some more settings dynamic

rpcs3/Emu/Cell/Modules/sys_spu_.cpp
I have discovered this bug while investigating isolated SPUs load for PSP remaster emulator.
=> liblv2 HLE: Fix spu_elf_info loader for SCE SPU images

rpcs3/Emu/RSX/RSXThread.cpp
is_fifo_idle() is called inside _cellGcmInitBody before rsx::thread::ctrl is initialized
=> rsx: Fix is_fifo_idle with hle gcm

rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h, rpcs3/Emu/Cell/lv2/sys_ss.cpp, rpcs3/Emu/Cell/lv2/sys_ss.h
Isolated SPUs are similar to raw SPU with most of the difference lying inside sys_isolated_spu_create.
Gets PSP resmaster emulator a bit further.
=> Implement sys_isolated_spu

rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/qt_utils.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/tooltips.h
- fixes translation bugs that may break audio settings widget behavior
- implements a way to find out if a setting is dynamic using emu_settings
=> GUI maintenance

rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/config_adapter.cpp, rpcs3/rpcs3qt/config_adapter.h, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/emu_settings_type.h
- Move m_settings_type map to emu_settings_type.h
- Move cfg_adapter stuff from emu_settings to its own file
This makes it easier to use the mentioned code in other classes and also cleans up emu_settings in the process.
=> More Maintenance

rpcs3/Emu/Cell/PPUTranslator.cpp
Should fix #8047, to test this pull request literally remove all rpcs3/cache contents.
The fix itself can merged immediately and the issue will be closed, reopen if still occurs after rpcs3/cache removal.
=> PPU LLVM: Fix rounding regression of FNMADDS, FNMSUBS

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/RSXThread.cpp
* Check if depth surface format and antialiasing samples match zcull bound buffer as documented by gcm.
* Add some error checks for zcull binding sys_rsx command.
=> rsx: More strict zcull stats enabling

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/config_adapter.cpp, rpcs3/rpcs3qt/config_adapter.h, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gui_save.h, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
- Adds "File->Firmware->Create Firmware Cache"
- Adds "File->Firmware->Remove Firmware Cache"
- Adds confirmation dialogs to user interactions that may unexpectedly close the running game
=> Add firmware cache options and more confirmation dialogs

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_frame.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/main_window.ui
- Moves the "RSX Capture" button from the debugger to "Utilities->Create RSX Capture"
- Adds confirmation dialogs that prevent accidentally closing the running game by drag and drop
- some minor refactoring
=> Move RSX capture to Utilities menu and add drag and drop confirmation dialogs

rpcs3/Emu/Cell/lv2/sys_rsx.cpp
* Fix error code instead of success on invalid context, did some RE on this. cellGcmSys code documentation seems to rely on this as well by not mentioning what happens if cellGcmSys is not intialized when calling specific functions even though they always use the syscall.
* Fix sys_rsx zcull bind command height. Fixes a regression from #8065.
=> Minor sys_rsx fixes

rpcs3/Emu/system_config.h
Fixes an issue addressed on discord for games at 60fps, where audio delay was introduced at the lowest duration (20ms). This changes the minimum duration to 0, fixing the audio delay in 60fps games.
=> Change minimum duration for audio buffering

rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Memory/vm.cpp
=> Don't use std::popcount (workaround)

rpcs3/Input/evdev_joystick_handler.h
I'll probably rework the current system sometime soon so that I don't have to add keys every now and then
(or I'll just add them all XD)
this should impove the situation in #8089
=> evdev: add keys used by wii controller driver

llvm_build/llvm_build.vcxproj
Since cmake cmd is the same for all configurations and build commands it is extracted to msbuild variable. It should be easier to make changes.
=> [llvm_build, msbuild] Minor refactor

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
Tuning for compiling for more CPU variants, such as znver1 or ivybridge (mainly for GCC).
=> SPU DMA: more tuning for mov_rdata_avx

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp
* SPU GETLLAR: Remove TSX specific code, do not use locking for non-TSX.
* Fix race in PPU load reservations instructions on TSX path.
* Detect SPU reservation load spinning loop.
=> SPU: New GETLLAR technique

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp
Seen as PPU LDARX/LWARX log spam introduced by #8051 that wasn't before it in some games.
=> Fix preformance regression on TSX path

Utilities/address_range.h, rpcs3/Emu/Cell/MFC.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h, rpcs3/rpcs3qt/kernel_explorer.cpp
* Fix cpu_flag::pause check in SPU GETLLAR (affects TSX), fixes #8116 .
* Return error code on PRIORITY_INHERIT protocol for sys_rwlock, this protocol is not allowed for it.
* Fix address_range::start_length(0, 0) constructor (created a valid range of 0...UINT32_MAX where it should be an invalid range), also make constructors constexpr.
* Make spu_mfc_cmd fmt properly show stalled commands.
* Fix sys_ppu_thread_get_priority page faults.
* Fix sys_ppu_thread_start error checking.
* Fix sys_ppu_thread_create when the created thread has the same id as ppu_thread::id_base, can happen when the main thread exited (by sys_ppu_thread_exit) before the thread created. (valid situation)
* Add more information about SPU/PPU threads in kernel explorer.
=> Lööp of fixups

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp
Prevent edge case of missing store.
=> SPU DMA: Fix PUTLLUC (TSX)

Utilities/File.cpp, Utilities/File.h
Should be less cryptic than 0x70 or 0x1C.
=> Add fs::error for when disk is full

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp
* Loop detection in GETLLRAR was causing transactions failres on TSX path which are not present on non-TSX path.
* Clear PPU reservation on context switch, ensure that no more than 2 PPU reservations are active at a time as realhw.
Attempts to address #8133.
=> SPU GETLLAR: Don't use loop detection for TSX

rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_config.h, rpcs3/Emu/Cell/lv2/sys_event.cpp, rpcs3/Emu/Cell/lv2/sys_event.h, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
* Fix forced lv2 event queue destruction, ~~empty sleep queue after awakening~~ add last existence check under mutex on event sending. This matters for event sending which either does not check for `lv2_event_queue::check` or does check but not under IDM mutex such as threaded SPU events sending "syscalls", sys_timer events, cellAudio events, etc.
Fixes a case where a waiter gets ECANCELLED and after it returnes from the syscall, in ppu r4-r7 registers for is changing, lv2_obj::awake if forced called on him.
For SPU thread a similar modification occurs in mailbox and cpu flags state even after the thread finished the syscall.
* Use SYS_SYNC_PRIORITY protocol in sys_cond_signal_all to signal threads, documentation says when signalling all threads the first thread to try acquiring the mutex …
=> Minor sys_cond/sys_event fixes

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp
Makes it better aligned and does not need the additional space character between register name and '='.
=> SPU/PPU debugger: use ':' instead of '='

rpcs3/Emu/Memory/vm.cpp
less resets of memory overall, and deallocated memory will get invalidated with zeroes so it will be viewed as zeroes if you use vm::get_super_ptr on it.
=> vm: reset stack memory after deallocation

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h
We should always use the global config when adding games.
The VFS stuff for example is only supposed to be read from the global config.
There is no need to load any custom config anyway.
=> Don't load custom configs when adding games

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_utils.h
A very strange observation I made when working on https://github.com/RPCS3/rpcs3/issues/4172 was that the game is clamping alpha output to not go below 0.1 but alpha test setup is checking for alpha greater than 0 causing all pixels to pass. Inspecting the RSX replay dump shows that the game is setting fp16 values in alpha ref which means the ROP output register is likely compared directly to the alpha ref register directly and therefore format must be converted to match ROP format.
This allows for alpha ref to be greater than 1 or even negative values when rendering into a floating point texture.
f32 rendering is known to not work correctly with blending and is of no consequence.
Fixes https://github.com/RPCS3/rpcs3/issues/4172
=> rsx: Fix alpha ref

rpcs3/Emu/RSX/Common/Interpreter/VertexInterpreter.glsl, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/system_config.h
Disables writing to output registers from SCA instructions. A bit to toggle output from SCA has not been identified, but there is evidence of titles where dst tmp write is invalid but vector output bit is set. This means there are only two options:
a. SCA opcodes cannot write to output.
b. SCA opcodes share the vector output bit in exclusive fashion.
I am not able to find any games that write to output mask using SCA opcodes, so please test this for regressions, it can break everything.
EDIT: It appears option b is the correct one. Option a causes some regressions in Portal 2, GOW3, etc
Fixes https://github.com/RPCS3/rpcs3/issues/4196
=> rsx: Vertex decompiler fixup

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h
* Fix ESTAT check of sys_spu_thread_get_exit_status, its enough for exit status to be written once by sys_spu_thread_exit for it to report CELL_OK and last thread exit status as long as the group lives. even after the SPU is restarted and currently running.
* When the last SPU thread in the group exits by sys_spu_thread_exit, set the exit status in conjunction with group state changes, I do not know if this is guarenteed by realhw as well but its better to be safe.
* Write 0 into the group exit status when it's (re)started, this affects the value returned in sys_spu_thread_group_join when SYS_SPU_THREAD_GROUP_JOIN_ALL_THREADS_EXIT is the termination cause.
Testcase : https://github.com/elad335/myps3tests/tree/master/spu_tests/sys_spu_thread_get_exit_status
Results on current master :
``` …
```
=> sys_spu: Improve sys_spu_thread_get_exit_status and reset group exit status in group start

rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.h
NOP shaders are used to stub rendering when a pass is supposed to be disabled. It is unclear whether they affect other parts of the pipeline such as Z pass testing.
Fixes https://github.com/RPCS3/rpcs3/issues/8170
=> rsx: Fix NOP shader passing

rpcs3/rpcs3qt/main_window.cpp
In order to make it easier for the user to take RSX captures.
=> Qt: remove debug tab wall for Utilities menu

rpcs3/Emu/RSX/VK/VKProgramBuffer.h
Should fix compiling with newer version of vulkan headers.
=> vk: Remove deprecated enum VK_DYNAMIC_STATE_RANGE_SIZE

rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp, rpcs3/Emu/RSX/VK/VKTextOut.h
Followup to #8202 
Fixes #8196
=> vk: Remove more deprecated VK_DYNAMIC_STATE_RANGE_SIZE usage

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h
* After #8182, the conditional variable is no longer needed and can be replaced with waitable atomics signaling and direct lv2_obj::awake for joining thread so it won't need to awake itself manually using ppu.test_stopped() afterwards.
* Add short sleep in sys_spu_thread_group_terminate to emulate PPU waiting on a sys_cond_t for a termination signal as realhw.
* Implement spu_channel_(4_t)::try_read(), reading the channel's content without modification, cleaning up some code.
* Minor EFAULT fix in sys_semaphore_get_value/sys_event_flag_get.
=> sys_spu: Minor cleanup of group termination process

rpcs3/Emu/RSX/Common/texture_cache.h
In blit engine logic there is a tendancy to over-allocate so as to avoid having to stitch together textures later. Sometimes this can lead to out of bounds access and crash applications, so memory must be validated.
Fixes virtualprotect crash in https://github.com/RPCS3/rpcs3/issues/2192
=> rsx: Improve blit engine memory validation

rpcs3/Emu/Cell/SPUThread.cpp
If sys_spu_thread_group_terminate returned CELL_OK, the exit status + cause obtained with sys_spu_thread_group_join must match it. If a sys_spu_thread_group_exit call occured afterwards it cannot be the source of these values.
=> sys_spu: Fix sys_spu_thread_group_terminate vs sys_spu_thread_group_exit race on values

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/RSX/rsx_methods.cpp
Turns out SMEAPHORE_RELEASE writes 16-byte of aligned data instead of 4-bytes, the rest of the bytes are filled with zeroes.
Similarly texture and backend labels write zeroes as well for the rest of the 12 bytes of data and not rsx timestamp as it used to thought of.
Also fix the initial data of the upper 8 bytes of semaphores, they are not initilaized to UINT64_MAX but special values as a "joke" of Sony. (if you look at the values you'll see...)
testcase : https://github.com/elad335/myps3tests/blob/master/rsx_tests/FIFO%20Semaphores%20data/expected.txt
The first buffer output is of the initial data of 6 semaphores, the second is of the first 3 semaphores used in the first output after SEMEPHORE_RELEASE, texture weite label and backend write label.
=> rsx: Fix data written to RSX semaphores and the initial data of them

rpcs3/Emu/RSX/GL/GLDraw.cpp, rpcs3/Emu/RSX/GL/GLHelpers.h
Avoid glEnable/glDisable GL_DEPTH_BOUNDS_TEST_EXT flood that returns 
GL_INVALID_ENUM if the feature isn't supported
=> gl: Check for GL_EXT_depth_bounds_test

rpcs3/Emu/RSX/GL/GLCompute.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.h, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLOverlays.h, rpcs3/Emu/RSX/GL/GLProgramBuffer.h, rpcs3/Emu/RSX/GL/GLShaderInterpreter.cpp, rpcs3/Emu/RSX/GL/GLShaderInterpreter.h, rpcs3/Emu/RSX/GL/GLTextOut.h, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.h
More work towards the OpenGL render, refactors all shader compilation code into using the unique `gl::glsl::shader` path
gl: Refactor shader compilation
- Refactors the three existing shader compilation paths into an unique `gl::glsl::compile` path
- `GLVertexProgram`: Removes unused `interleaved` var
- `gl::glsl::shader`: Stores shader source on struct for usage in other places
- `gl::glsl::shader`: Remove `recreate()` and partial constructors
gl: Refactor shader type usage
- Removes duplicated `type` in `gl::glsl::shader` in favor of Common `glsl::program_domain` types: stores program_domain in the `gl::glsl::shader` struct and converts to OpenGL specific GLenum when needed
gl: Only log shaders if g_cfg.video.log_programs is enabled
=> gl: Refactor shader compilation

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
RSX MAD instruction appears to be broken. Unlike other instructions, for this one only arg0 has clamping applied to it. However, when neg flag is set, the precision clamping works correctly. For example, consider this set of inputs (input clamping is set to [0,1] for all cases):
a) 1 * 100 + 0 = 100
b) 100 * 1 + 0 = 1
c) 1 * -100 + 0 = -1
d) 1* 1 + 100 = 101
etc
This fixes some rare graphical glitches such as the sea in one piece pirate warriors and the sky in GTA V. Also fixes post-processing in Crysis.
Fixes https://github.com/RPCS3/rpcs3/issues/2262
=> rsx/fp: Fix precision clamping on MAD instruction

rpcs3/Emu/Cell/SPUThread.cpp
PUTQLLUC may be executed inside do_mfc() which may execute more commands, wait flat needs to be cleared before them otherwise the SPU thread execution is not tracked by cpu_suspend lock which may result in a data race.
In PUTLLUC it doesn't change anything as other commands can't be executed after it.
=> SPU reservations (TSX): Remove wait flag in PUTQLLUC

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/RSX/rsx_methods.cpp
* Use 4-byte data writes for all semaphores, I added another case for the tests where I reset all the samphores with 0xff bytes instead of 0x0 bytes and the upper 12 bytes didn't change for all semaphores! Although, offsets which are not 16-byte aligned on NV4097 semaphores crash the DECR so put FIFO recovery point there. 
* Ignore unaligned writes from SEMAPHORE_RELEASE, literally no data is changing. (TODO: Test unaligned SEMAPHORE_ACQUIRE as well)
Updated testcase (same link) : https://github.com/elad335/myps3tests/blob/master/rsx_tests/FIFO%20Semaphores%20data/expected.txt
=> rsx: Write 4-byte long data to all semaphores

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/GL/GLHelpers.h
gl: Restrict insert_vertex_input_fetch workaround to Intel proprietary
- It works fine on Mesa iris
- Fixes detection of Mesa as recent Mesa does not have "x.org" on vendor string, allowing vendor_MESA to become true instead of vendor_INTEL on Mesa Intel
Tested on Yakuza 0 Demo which generates dozens of shaders using the compilant path in insert_vertex_input_fetch and game does not crash nor any difference is graphics is noticeable
=> gl: Restrict insert_vertex_input_fetch workaround to Intel proprietary

Utilities/BEType.h, rpcs3/Emu/Cell/PPUInterpreter.cpp
If any of the operands is a NaN of any kind it is 'quited' (MSB of fraction is set) and returned with the following ordering of selection between the NaNs: VA, VB, VC, result of operation.
The resulted NaN of operation is returned as a NaN if none of the arguments is a NaN.
Sign and fraction bits (other than NaN's signaling bit) are preserved across operands in all instructions.
It's not implemented at PPU LLVM atm.
=> PPU interpreters: Implement AltiVec (vector) NaN precedence and data preservation

rpcs3/rpcs3qt/about_dialog.ui
fixes #8225
What this PR does
1. Removes keyboard interaction with labels, so multiple cursors doesn't appear.
2. Removes double-include resources in about dialog.ui.
3. Removes some flags as they are in a more general one.
=> [Qt] Optimize properties in about_dialog

rpcs3_llvm.props
Previously llvm libs were linked (embedded actually, because Librarian does that with all libs from input) into all lib pjojects that import `rpcs3_llvm.props` which resulted in 200+ MB libs and probably longer compile time.
=> [msbuild] only link llvm libs to Applications

rpcs3/Emu/Cell/MFC.h, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
* Deliver SPU interrupts immediately as they are received. L.A. Noire expects this as it executes code relying on occurence of previous interrupt after certain actions making sure the interrupt has occured on realhw. (e.g. reading MFC stalled status)
When we didn't execute the interrupt in time, the code relying on this received unwritten MFC data which eventually made it crash.
* After the above fix, the game was going a bit further and started executing MFC_SDCRZ_CMD. (sets all EA memory to zeroes) 
arguments seem valid. Implementing this command made it finally boot.
Fixes #8064, note that PPU interpreter fast/precise and LLE libvdec.sprx are still required for it to proceed after the first logos.
=> SPU MFC: Fix SN interrupts, Implement MFC_SDCRZ_CMD

rpcs3/Emu/RSX/VK/VKDraw.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKPresent.cpp
Partial stencil buffer clears were not implemented. This is for example where a game can choose to clear only some bits from the stencil buffer. Vulkan does not support masked stencil clears natively, it has to be implemented as a graphics operation.
Also refactors vulkan overlay passes to use global resource system instead of forcing the render backend to own all of them and manage lifetimes.
Fixes https://github.com/RPCS3/rpcs3/issues/5079
=> vk: Implement masked stencil buffer clears

rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/rpcs3qt/debugger_list.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
* Distinguish between executable code and data-only memory by not disassembling data-only memory at all.
* Add information about first PRX/overlay segment in kernel explorer, this is an executable code segement.
=> PPU disasm: do not disassmble non-executable memory

rpcs3/Emu/Cell/Modules/cellSpurs.h
very small typo  fix in cellSpurs.h
=> very small typo  fix in cellSpurs.h

Utilities/Thread.cpp
* Release reservation lock before waiting for page fault notification.
=> SPU: Fix page faults notifications on TSX

.ci/build-freebsd.sh, .ci/install-freebsd.sh, .cirrus.yml, .travis.yml
TravisCI [supports](https://github.com/travis-ci/travis-build/pulls?q=is%3Apr+freebsd+is%3Aclosed) FreeBSD nowadays. Let's see how well it works. Fixes #7885
Caveats:
- `pkg` addon maybe missing on job runners, so install manually
- `ccache` maybe not installed/configured, so do manually like on `osx`
- LLVM needs hooking into `cache: directories`, so disabled for now to avoid long builds
=> Add FreeBSD to CI

.ci/setup-windows.sh, Vulkan/spirv-tools-build/spirv-tools-build.vcxproj, azure-pipelines.yml, rpcs3.sln
Also, I think that if a single Intermediate dir is created it could be cached along with libs and bin folders to drastically speed up compilation, thou it would require not updating cache on Pull Requests at all or creating a separate cache per Pull Request and using either PR specific cache or falling back to the general cache on the first PR build if that is possible to do with azure at all.
EDIT:
I will try to do that in another PR so no longer WIP.
=> [CI,Windows] Build SPIRV-Tools separately

Vulkan/glslang-build/glslang-build.vcxproj, Vulkan/spirv-tools-build/spirv-tools-build.vcxproj, llvm_build/llvm_build.vcxproj
Should fix `Microsoft.MakeFile.Targets(46,5)` error on Visual Studio 16.6 when building `_BULD_BEFORE` projects. If it does not ping me.
=> [MSVC 16.6] Microsoft.MakeFile.Targets(46,5) :thisisfine:

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/rsx_methods.cpp
Those strange offsets noted in some games seem to match to subpixel addressing. For example, when scaling down by a factor of 4, a pixel offset of 2 will end up inside pixel 0 of the output. Uses coverage area to determine the address (u, v) of the real corner address.
Fixes https://github.com/RPCS3/rpcs3/issues/5890
=> nv3089: Account for subpixel addressing

rpcs3/Emu/RSX/RSXTexture.cpp
Adds the missing 0xEE and 0x44 variants of the 2-component data format remapper. Followup to https://github.com/RPCS3/rpcs3/pull/8199
Fixes https://github.com/RPCS3/rpcs3/issues/8271
Fixes https://github.com/RPCS3/rpcs3/issues/8266
=> rsx: Fix data format remapping

rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/Emu/IdManager.cpp, rpcs3/Emu/IdManager.h
When destructing an object belongs to the following group: lv2_obj, lv2_spu_group, ppu_thread 
(and may be more lv2 types) the ID value of the object is guaranteed to not reappear for atleast 256 creations from the same object type.
This means that in code like so:
```
sys_ppu_thread_t ppu_id, ppu_id2;
sys_ppu_thread_create(&ppu_id, ...);
u64 ret;
sys_spu_thread_join(ppu_id, &ret);
sys_ppu_thread_create(&ppu_id2, ...);
int prio;
assert(ppu_id != ppu_id2 && sys_ppu_thread_get_priority(ppu_id, &prio) == ESRCH);
```
The assert will never trigger, assuming no other thread is executing sys_ppu_thread_create at the time.
In realhw bits 16-23 are incremeneted each time for this purpose, although we use those bits for object indexing so use bits 0-7 for this instead.
After 256 times of …
=> IDM: Implement IDs creation/destruction invalidation counter

.ci/get_keys-windows.sh, azure-pipelines.yml
Adds per dependency cache.
EDIT:
all hashes and version numbers can be combined and used as a single key then all deps can be in a single cache but the pros and cons of that are questionable.
EDIT:
trying singe cache with proper versioning
EDIT:
seems like deps don't update often so it is probably better to do a single cache with fallback.
=> [CI, Cache] Add proper cache versioning

rpcs3/Emu/Cell/MFC.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp
This PR works around a rare LLVM bug causing SPU LLVM crash on Windows. New approach is also better for future SPU LLVM object retention.
=> SPU LLVM: implement get_segment_base()

Utilities/Config.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/system_config.h
Works both on PPU interpreters and LLVM recompiler, when the setting's value is zero the stubbing is disabled and the old exception is raised.
When the setting's value is non-zero it jumps the amount of instructions from the address of the PPU trap.
Range of 64 instructions forwards (positive) and backwards (negative) can be specified.
The Last Of Us and Uncharted Series need the value to be 1 for it to work properly.  
Implements #5700.
=> PPU: Implement PPU Traps Stubbing option

rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm_reservation.h
* Do not ever lock vm memory that is meant to be page faulted on or unmapped memory in general, this bug always existed but #8008 added another single case where the bug finally made it crash GT6.
Fixes #8109.
=> SPU: Fix page faults notifications (non-TSX)

rpcs3/Emu/Audio/XAudio2/XAudio2Backend.cpp
I was wondering why my games were inexplicably loud, even when I went down to 20%.
Thanks to @Nekotekina I found out, that the volume in the XAudio2 backend was set to 400% for some reason.
By setting the volume to 100% the games now finally sound normal again and the master volume slider works as expected.
=> XAudio2: turn down the volume

rpcs3/Emu/Cell/SPURecompiler.cpp
Uses clamping helpers for the FMA family and FM spu instructions, which appears to improve performance and fixes some issues.
fixes an issue in LBP2 where gas prevents you from progressing (the game is now probably playable)
fixes: https://github.com/RPCS3/rpcs3/issues/7958
fixes: https://github.com/RPCS3/rpcs3/issues/7704
fixes: https://github.com/RPCS3/rpcs3/issues/6333
maybe fixes or breaks some other stuff, try testing
=> SPU LLVM: Use clamping helpers for FMA32x4 and FM

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/GL/GLPresent.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/VK/VKPresent.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h
- Do not allocate too many surface objects. This is a problem in games using dynamic memory allocators that can make it rare for a surface to fall on the same address twice, keeping zombie RTVs and DSVs alive much longer than needed.
- Current limit used is 256M of virtual VRAM which is impossible on retail PS3 and is a good indicator to start removing unnecessary data.
Fixes https://github.com/RPCS3/rpcs3/issues/6253
=> rsx: Improve surface cache resource management

rpcs3/Emu/RSX/Common/surface_store.h
Fixes some over or under counting which leads to crashes when doing sanity checks on exit.
Fixes https://github.com/RPCS3/rpcs3/issues/8324
=> rsx: Properly account for memory sizes of reused surfaces

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
- Fix copypasta for SET_POLYGON_STIPPLE_PATTERN vs SET_POLYGON_STIPPLE method binding. This is a regression from stippled rendering PR.
- Use proper enums for ROP_control bits to avoid confusion.
Fixes https://github.com/RPCS3/rpcs3/issues/8332
=> rsx: Fix fragment state updates

rpcs3/Emu/Cell/lv2/sys_net.cpp
On #8019, a buffer for the `fds` parameter was added
However, the `fds_buf` buffer was only copied to the `fds` parameter on only one out of three possible function returns (at the very end of the function)
I'm unsure why this change was made, but copying the `fds_buf` buffer to the `fds` parameter before every possible return fixes networking issues such as failed Netflix connection
---
Before: 
After:
---
Before: Black Screen
After: 
Requesting review from @elad335
=> Fix sys_net_bnet_poll regression

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/main.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
* Avoid double check for id_type in ```CPUThread.cpp```
* Comment out unused object construction in ```PPUThread.cpp```
* Comment out 'never-true' condition in ```SPUThread.cpp```
```s_tsx_avx``` contains avx capability. Since avx is a processor feature, it can't be changed on runtime. It means, that by the time this line is executed, values are the same.
* Avoid double check in ```report_fatal_error``` in ```main.cpp```
* Avoid double check in ```kernel_explorer::Update()```
=> Avoid some useless checks

README.md
#8261 Introduced Free BSD builds via Cirrus CI. 
While Azure and Travis have their badges on the main page, Cirrus was left abandoned.
This PR adds a badge. 
[![Build Status](https://api.cirrus-ci.com/github/RPCS3/rpcs3.svg?task=FreeBSD%2012.2%20(snapshot))](https://cirrus-ci.com/github/RPCS3/rpcs3)
=> Add Cirrus Free BSD badge

rpcs3/Emu/Cell/SPURecompiler.cpp
- Fix a theoretical issue with FCGT optimizations
There was a silly issue where FCGT could produce bad results if constant `0x7f7fffff` was used as an input, but it's unlikely that any game hit this case
- Partial revert for FM/FMA changes and other improvements
Partially reverts the changes made in https://github.com/RPCS3/rpcs3/pull/8316
Sadly RDR and some other games were effected negatively by the changes in that PR. This PR reverts enough to make both RDR and LBP2 happy, but maybe something else is still regressed.
also:
- Allow non accurate/approx FMA family instructions to use native FMA
- Minor optimization for FMA ops with a constant 0 multiply
- fixes an unreported regression with shadows in NCAA 14
edit:
- Added additional optimizations for FCGT
- Added an optimization for FM …
=>  SPU LLVM: Partial revert for FM/FMA changes and other improvements

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h
SRC0, SRC1 and SRC2 have different bits for precision modifiers all stored inside SRC1. This explains the strange observed behavior of the MAD instruction which has 3 inputs.
Fixes https://github.com/RPCS3/rpcs3/issues/6088
Fixes https://github.com/RPCS3/rpcs3/issues/6187
Fixes https://github.com/RPCS3/rpcs3/issues/6460
Fixes https://github.com/RPCS3/rpcs3/issues/6611
Fixes https://github.com/RPCS3/rpcs3/issues/6626
Fixes https://github.com/RPCS3/rpcs3/issues/6641
Fixes https://github.com/RPCS3/rpcs3/issues/7295
Fixes https://github.com/RPCS3/rpcs3/issues/7455
Fixes https://github.com/RPCS3/rpcs3/issues/7812
Fixes https://github.com/RPCS3/rpcs3/issues/7920
Fixes https://github.com/RPCS3/rpcs3/issues/8245
Fixes https://github.com/RPCS3/rpcs3/issues/8288
Fixes …
=> rsx/fp: Separate SRC precision modifiers

rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLProgramBuffer.h
On multithreaded mesa, the program initialization routine was not being flushed correctly. Set up synchronization fence after initialization is complete. If you don't call glFlush on a secondary context, the commands in the buffer may never be submitted forever.
Fixes a bug with mesa_glthread https://gitlab.freedesktop.org/mesa/mesa/-/issues/2965
=> gl: Improve async compiler synchronization with initialization

azure-pipelines.yml
Before: 
After: 
I was curious about, why artifacts have non-unified names. 
And accidentally found that artifacts are produced on any build results, even on failure.
I've made the title "RPCS3 for [platform]"
Feel free to suggest your Bundle Name.
=> Unify Azure artifacts names and Produce them only on successful build

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/rpcs3qt/kernel_explorer.cpp
Added many small and medium improvements to the kernel explorer, a few notable ones are:
* Added last PPU syscall/function executed, with a note if PPU thread is cuurently executing it or if it's only the last.
* SPU thread type added. (Raw/Isolated/Threaded SPU)
* lv2_obj::name64 removes invalid/newline characters automatically to avoid garbage output in objects' names.
* IPC key of lv2 objects has been added.
* It is now reported if event ports are bound to an event queue or not. 
* Shared memory information has been added.
* RSX Context information has been added, some of the added info includes IO mapping, Zculls and display buffers information.
=> Kernel Explorer: Improvements

rpcs3/rpcs3qt/tooltips.h
Improve description of Create SPU Cache tooltip.
Add descriptions to "Never use this" settings.
Offtop.
I've found that lower_spu_thread_priority and accurate_rsx_access do not affect the emulation at all.
=> Improve tooltips

Utilities/bin_patch.cpp, Utilities/bin_patch.h, rpcs3/Emu/System.cpp, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/patch_manager_dialog.cpp, rpcs3/rpcs3qt/patch_manager_dialog.h, rpcs3/rpcs3qt/patch_manager_dialog.ui, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/qt_utils.h, rpcs3/rpcs3qt/user_manager_dialog.cpp
- Support legacy patch.yml as before and automatically mark those patches as enabled.
- Support new patch.yml version 1.0 containing multiple hashes:
```
Version: 1.0
Anchors:
super_60fps: &super_60fps
- [ be32, 0x00081ccc, 0x980902F8 ]
- [ be32, 0x00081acc, 0x980912F8 ]
PPU-8007056e52279bea26c15669d1ee08c2df321d00:
Title: Best Game Ever
Serials: ABCD12345, SUPA13337 v1.3
Patches:
Debug:
Author: Batman bin Suparman
Notes: ABCD
Patch:
- [ be32, 0x00081cc8, 0x38000001 ]
Menu:
Author: Batman bin Suparman
Notes: I like potato
Patch:
- [ be32, 0x00081ccc, 0x980902F8 ]
Disable depth of field:
Author: Batman bin Suparman
Version: 1.2
Notes: Dat game
Patch:
- [ be32, 0x000e522c, 0x995d0072 ]
Disable motion blur:
Author: Batman bin Suparman
Notes: Cool
Patch:
- [ be32, 0x000e5234, 0x995d0074 ] …
```
=> Implement simple patch manager

README.md
Looks like Azure has broken API a bit, so link to the full list of the latest builds in the meantime
=> Workaround broken Azure badge link

rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Cell/lv2/sys_memory.h
* Do not iterate through all allocations from sys_memory_allocate_from_container everytime sys_memory_free is called in order to search allocation's associated memory container, instead use atomic lookup table.
* Remove lv2_memory_alloca which used to track sys_memory_allocate_from_container allocations, no longer needed.
* Add missing EALIGN error checks in sys_memory_allocate(_from_contao
iner) syscalls where this error code is returned if size is 0 according to reversing.
* Fixes a case where sys_memory_free could deallocate PPU stack memory where it shouldn't be able to.
* Fix race condition in sys_memory_free syscall where the returned memory could get into the main memory container instead of the one selected by sys_memory_allocate_from_container, this race can occure because …
=> sys_memory: Improve allocation/deallocation syscalls

Utilities/bin_patch.cpp
Assignment of invalid YAML nodes is not possible after all
=> patch manager: hotfix for legacy patches

rpcs3/Emu/RSX/RSXThread.h
Do not use so many atomic instructions which are expensive, instead use relaxed stores.
=> rsx: Optimize rsx::rsx_iomap_table construction

rpcs3/rpcs3qt/breakpoint_list.cpp, rpcs3/rpcs3qt/debugger_list.cpp
* Fix an old regression from #7905 which made breakpoints literally not appear after setting them, they would only appear after scrolling which triggers the missing call to `ShowAddress`. Because this function is also responsible for refreshing breakpoints viewing list.
* Fix foreground/background color of text when encountering non-execuable memory, this bug always existed and can be reproduced by simply jumping to address 0 after setting a breakpoint. you would see that the breakpoints colors are still placed.
=> Fix debugger breakpoints

rpcs3/Emu/Cell/lv2/sys_sync.h
Do not ignore null terminators, because they may hide some more garbage characters after them.
=> Fix lv2_obj::name64 regression

rpcs3/Emu/Cell/Modules/cellAudio.cpp, rpcs3/Emu/Cell/Modules/cellAudio.h
1. cellAudioSetNotifyEventQueue has error checking similar to sys_event_queue_connect_ipc - the events queue key must be valid when connecting, if the original previous attached event queue associated with the same event key has been destroyed the function is allowed to rebind the same key as if the previous event queue was never bound.
2. cellAudioRemoveNotifyEventQueue has similar error checking to sys_event_port_disconnect - if the originally associatyed event queue specified with the same key as the current argument has been destroyed, this funcion returns an error as if the previous key was never bound.
3. If the original event queue associated with `x` key value has been destroyed, but later on a newer event queue with the same `x` key has been created, cellAudio events will not be …
=> cellAudio: Fix event queue attachment

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
Rewrites how surface configuration changes can happen after the surface has been constructed at runtime. Fixes cases where we would miss changes made on the fly such as starting a render pass with depth writing disabled but depth tests enabled, then enabling depth tests for another pass, or turning on and off MRT color buffers by messing with the write masks.
Fixes https://github.com/RPCS3/rpcs3/issues/6766
=> rsx: Improve surface options invalidation

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_cond.h, rpcs3/Emu/Cell/lv2/sys_event.cpp, rpcs3/Emu/Cell/lv2/sys_event.h, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_mutex.cpp, rpcs3/Emu/Cell/lv2/sys_mutex.h, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/rpcs3qt/kernel_explorer.cpp
* ~~Revert a change in #8140 where the protocol was changed to PRIORITY, I will revert it for now as it is probably the cause for the regressions and I haven't hw test it.~~
* Because #7999 and #7931 made the destroy syscalls of sys_event_queue and sys_cond execute destruction code instead of the destructor, IPC support has been broken because with IPC you can have multiple copies (multiple IDs) of the same object and destroy syscall is destroying one ID at a time. The destruction code must happen on last ID destroyed, so you use an existence counter and increment it in lv2_obj::on_id_create(), decrement on destroy syscall and execute destruction code when it becomes 0.
* Fix race between sys_cond_create and sys_mutex_destroy which could lead to a conditional variable creation without any …
=> SPU/sys_cond/mutex/event: Implement lv2_obj::on_id_create(), Write into SPU inbound mailbox under mutex

Utilities/BEType.h
Fixes https://github.com/RPCS3/rpcs3/issues/8443
It's the issue where #pragma once gets ignored in files with utf-8 with bom signatures by gcc:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=56549
=> std header guard in BEType.h

rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- Account for source offsets when grabbing subregions.
- Scale input accordingly when sourcing from fbo in all paths.
Fixes https://github.com/RPCS3/rpcs3/issues/6968
=> rsx: Improve mipmap gathering

rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
When extracting a 1x1 texture from another texture of a different format, width conversion can result in a dimension of 0 if the extracted texel in DST is not a full texel in SRC.
Fixes https://github.com/RPCS3/rpcs3/issues/7274
=> rsx: Account for subpixel precision when converting DST coordinates to SRC coordinates

rpcs3/Emu/Cell/SPURecompiler.cpp
This optimization had some corner cases with -x86(NaN), removing.
Fixes a regression in Ratchet And Clank: TOD.
=> SPU LLVM: Avoid bad optimization in FCGT

Utilities/Thread.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.h, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
* Fix a corner case where an SPU thread has the same ID value as a PPU thread.
* Fix a potential deadlock on Emu.Stop() while sending event in EBUSY loop.
* Thread specific notifications.
=> sys_mmapper: rewrite page fault thread notifications

rpcs3/rpcs3qt/localized.cpp, rpcs3/rpcs3qt/localized.h, rpcs3/rpcs3qt/update_manager.cpp
- Add "RPCS3 will now restart." hint to success message
- Use days to measure time greater than 24 hours
Example: "53 days and 12 hours" instead of "1284 hours and 12 minutes"
=> Improve auto-updater messages

Utilities/bin_patch.cpp, Utilities/bin_patch.h, Utilities/version.cpp, Utilities/version.h, rpcs3/rpcs3qt/patch_manager_dialog.cpp, rpcs3/rpcs3qt/patch_manager_dialog.h, rpcs3/rpcs3qt/patch_manager_dialog.ui, rpcs3/util/yaml.cpp, rpcs3/util/yaml.hpp
Allows dropping a single *patch.yml into the patch manager.
The options are a simple validation, or an import (including validation).
Imported files are appended to "patches/imported_patch.yml".
If two same patches are found, it is only overwritten if the Version of the new patch is bigger.
=> patch manager: import and delete patches

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_utils.h
Colormask and clear color data seems to literally follow the physical memory layout. This means for example, if you pass the same colormask or clear data mask for ABGR vs ARGB you get the same data written to memory because the decoding step is changed to mirror the format layout. This was initially noted for G8B8 format needed for TLOU to render the window correctly, but no tests were made for other formats.
Fixes https://github.com/RPCS3/rpcs3/issues/7277
=> rsx: Fix memory operations on non-standard formats

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
Before:
After:
This only affects debugger and does not affect the log.
=> debugger: Shortend SPU/PPU thread names

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Savedata processing time means calling PPU thread should be asleep until complete, waiting for VSH thread(s) to respond. Let other PPU threads execute code meanwhile as some games rely on this feature.
Fixes #7182
=> cellSaveData: Emulate PPU processing of auto/list post-fixed callback

rpcs3/Emu/Cell/Modules/cellGem.cpp, rpcs3/Emu/System.h, rpcs3/Input/pad_thread.cpp, rpcs3/Input/pad_thread.h, rpcs3/main_application.cpp, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp
fixes #5908
This should also fix a theoretical issue that would allow pads to be enabled if the emu started after the pad settings dialog was opened.
=> Fix pad settings crash during firmware compilation

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
This option was always enabled for NVIDIA cards, but it seems some games would benefit from the option on other GPUs as well.
Fixes https://github.com/RPCS3/rpcs3/issues/7397
=> rsx: Force flushing of NaN/INF to zero for all GPU vendors

rpcs3/Emu/Io/PadHandler.cpp, rpcs3/Input/keyboard_pad_handler.cpp, rpcs3/Input/pad_thread.cpp
fixes #8505
Also fixes a problem with the keyboard pad handler:
You shall not see any ingame input while the pad settings or a native dialog are visible.
=> pad_thread facepalm and keyboard fix

rpcs3/Emu/Cell/MFC.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp
I was adding some more information about tag update and atomic status channels in SPU debugger, but after some testing I've noticed that the value of the tag update wasn't being cleared at points were you had expect it to be empty.
After some debugging I've found that unlike interpreters and asmjit, in LLVM tag mask writing isn't handled the way it should be and thus not updating tag status and tag update when needed.
=> SPU LLVM: Fix WRCH instruction to WrTagMask

Utilities/types.h, rpcs3/Emu/Cell/Modules/cellSpurs.cpp
Remove the ability to access directly the error_code's member value - if someone wants to read it he should use integer operations/casts, if someone wants to write to it he should construct a new error_code variable and assign it.
Some bugfixes in HLE cellSpurs were made as well near code that used direct access to it.
=> Make error_code::value member private

rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
- Invert the NVIDIA cross-aspect transfer hack to work for all GPUs before turing but nothing unknown or after.
- Add more turing GPUs to the list of known NVIDIA cards.
- Adds a warning message in log file if the current GPU is not in the chip tables.
Fixes https://github.com/RPCS3/rpcs3/issues/7774
=> vk: Improve chip-specific workarounds and optimizations

rpcs3/Crypto/unpkg.cpp, rpcs3/Crypto/unpkg.h
Looking at https://www.psdevwiki.com/ps3/PKG_files#ContentType, we can't simply put everything into dev_hdd0/game.
I tested this with themes, avatars and licenses.
I don't really know the correct behavior on PS3, so maybe someone can check the folders accordingly.
There might be a subfolder per ID for example.
=> Use proper install paths depending on pkg content

rpcs3/Crypto/unedat.cpp
Included in Utilities/BEType.h, attempts to address #8526
=> remove redundent include in Crypto/unedat.cpp

Utilities/bin_patch.cpp, Utilities/bin_patch.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/patch_manager_dialog.cpp, rpcs3/rpcs3qt/patch_manager_dialog.h, rpcs3/rpcs3qt/patch_manager_dialog.ui, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/qt_utils.h
- Removed "Patches" Key
- Added optional "Group" key to avoid stupid choices in the GUI
- Changed patch dependency to Serial + AppVersion in order to avoid selection of multiple games with the same mouse click
```
Version: 1.2
PPU-e72e715d646a94770d1902364bc66fe33b1b6606:
30FPS:
Games:
Best Game Ever:
NPUA80697: [ 01.00 ]
NPEA00363: [ 01.00, 01.30 ]
Best Game Never:
NPUA80123: [ 01.00 ]
NPEA00363: [ 01.00, 01.30 ]
Author: Batman bin Suparman
Patch Version: 1.0
Group: FPS
Notes: ABCD
Patch:
- [be32, 0x00010268, 0x9061009C]
- [be32, 0x008fc864, 0x60000000]
60FPS:
Games:
Best Game Ever:
NPUA80697: [ 01.00 ]
NPEA00363: [ 01.00, 01.30 ]
Best Game Never:
NPUA80123: [ 01.00 ]
NPEA00363: [ 01.00, 01.30 ]
Author: Batman bin Suparman
Patch Version: 1.0
Notes: ABCD
Group: FPS
Patch:
- [be32, …
```
=> patch_manager 1.2

rpcs3/Emu/RSX/VK/VKHelpers.cpp
- Disable primitive restart for old GCN cards as it is broken in hardware.
- Also adds more Navi 14 chips to detection table.
Fixes https://github.com/RPCS3/rpcs3/issues/7746
=> vk: Disable primitive restart for old GCN cards

rpcs3/Emu/RSX/Overlays/overlay_edit_text.cpp
I've found a TODO in code and decided to implement this piece of code.
In theory this should allow users to move caret up and down in text edit, but I didn't test it myself. 
So if someone tells the solution is working, than it's proper. :)
To test just run any working game with overlay with multiline text and try to move caret up and down.
I request @elad335 review.
=> Implement Caret upwards and downwards move in overlay_edit_text

rpcs3/rpcs3qt/localized.h
I noticed this on https://github.com/RPCS3/rpcs3/issues/4259 
(Main Window -> (Localized) Replace the category names with either something more gramatically correct or something used in Sony Naming Conventions)
=> localized.h: follow Sony Naming Conventions

rpcs3/Input/keyboard_pad_handler.cpp, rpcs3/Input/keyboard_pad_handler.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp
- Windows only for now
- Works for Ctrl Left and Right
- Works for Shift Left and Right
Keep in mind that you most likely can't press both Ctrl keys or both shift keys at the same time.
Sadly I could not find a way to properly distinguish Alt left and right with this method.
Should fix parts of #3393 for windows users
=> Windows: Distinguish Left and Right Modifiers

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
- Fix multiple queries in queue writing to the same address.
- Add a fast variant of the read_barrier method when we already have the query object to sync.
Fixes https://github.com/RPCS3/rpcs3/issues/7785
=> rsx: Minor ZCULL improvements

rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/downloader.cpp, rpcs3/rpcs3qt/downloader.h, rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/msg_dialog_frame.cpp, rpcs3/rpcs3qt/progress_dialog.cpp, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.h, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/tooltips.h, rpcs3/rpcs3qt/update_manager.cpp, rpcs3/rpcs3qt/update_manager.h
- Fixes some random crashes when closing the emulator while ppu is compiling.
- Cleans up some random code
- Refactors curl stuff into a downloader. (This will come in handy when more downloadable features are added later on)
- Adds a new option to check for updates silently, when RPCS3 is started. There will be a small menu on the top right of the emulator if an update was found.
fixes #8252
partially implements #8254
=> Qt: updater changes

rpcs3/Emu/Cell/SPURecompiler.cpp
This fix was missing from LLVM in https://github.com/RPCS3/rpcs3/pull/6173/commits/35fa117ccd116a1c916e78eac3f221579bbbe1a7
=> SPU LLVM: Fix barrier commands enqueuing

rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/update_manager.cpp, rpcs3/rpcs3qt/update_manager.h
"Update Available" was shown on latest update and triggering it would cause a curl error.
=> Fix update check for most up to date versions

rpcs3/Emu/RSX/Common/texture_cache_helpers.h
Readable height must be corrected to skip the piece that exists before the current slice.
Fixes https://github.com/RPCS3/rpcs3/issues/6639
=> rsx: Fix transfer descriptors for partially overlapping slices in head

rpcs3/Emu/Io/PadHandler.cpp, rpcs3/Emu/Io/PadHandler.h, rpcs3/Input/evdev_joystick_handler.cpp, rpcs3/Input/mm_joystick_handler.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/pad_settings_dialog.ui, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/save_data_list_dialog.cpp
=> Qt: Add stick multipliers to the pad dialog

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
- Unifies the command completion code.
- Allows conditionals to be evaluated with a forwarder present.
Fixes https://github.com/RPCS3/rpcs3/issues/7454
=> rsx: Improve ZCULL queued requests finalization

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/CPU/CPUThread.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/rpcs3qt/call_stack_list.cpp, rpcs3/rpcs3qt/call_stack_list.h, rpcs3/rpcs3qt/debugger_frame.h
* Stack offset was wrong, could fix some issues I had in the past such as threads clearly calling functions and saving LR and r1 onto the stack yet the thread is not reported to be in a function at all by the debugger.
* Add some more validity checks.
* Show stack address of each function in the debugger.
=> PPU debugger: Fix functions stack bounds check

rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
Do not read from or write to the looping texture until previous draw call is completed using it. This is usually not much of a problem until blending operations come into play. In modern GPUs it is common for multiple draws to execute asynchronously. While the feedback loop is reading from itself, the next draw call can execute without a texture barrier if it does not self-reference leading to a race condition in the GPU threads. In such a situation draw 2 can overwrite parts of the texture being accessed as reads in draw 1. 
Fixes https://github.com/RPCS3/rpcs3/issues/7818
=> vk: Inject memory barrier upon conclusion of a framebuffer feedback loop

rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h
Appends a regular menu instead of the corner widget for all linux builds (idk if they were all broken).
Should fix #8567
=> Qt: fix update menu for linux

rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.ui
- Fix scrollArea focus during pad settings button choice.
Assigning arrow keys for keyboard handlers was broken because of this.
- Fix pad settings resize when switching tabs.
The window was sometimes resizing itself, which led to scrollbar issues. This might still happen in some cases.
=> Scroll Area Fixis

rpcs3/Emu/Cell/RawSPUThread.cpp
Log MMIO reads and writes of RawSPU, currently under trace level.
=> RawSPU: Log MMIO access

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp
There were two behaviours that were undocumented regarding tag status updates that led to this pr:
- It was unclear if WrTagUpdate can clear previous tag status update in case the requested update cannot complete immediately.
- Is WrTagUpdate channel count actually depends on if theres a pending tag status update?
The results from hw testing:
* Always report channel count 1 in WrTagUpdate, because in realhw this count is just a performance hint that tells the program if it is beneficial to write a tag update at the same time or doing some other work instead. Otherwise the SPU will have to wait until the MFC internally processes the previous update request which can lead to a loss of performance.
In rpcs3 such "delay" in count is not emulated at all, report 1 immediately.
* WrTagUpdate …
=> SPU MFC/LLVM: Fix WrTagUpdate channel count, Never clear tag status in WrTagUpdate, LLVM related optimizations

rpcs3/Emu/RSX/RSXThread.cpp
Allow depth bounds test to access the Z buffer even when depth test is disabled. The GPU still requires hardware support for the feature to work correctly.
Fixes https://github.com/RPCS3/rpcs3/issues/7869
=> rsx: Fix depth bounds test

rpcs3/rpcs3qt/rsx_debugger.cpp
Becuase non-methods have no extra arguments their count should be displayed as 0.
=> RSX debugger: fix command count on non-method commands

Utilities/bin_patch.cpp
Should be no more "I don't know what patch I applied" meme and easier for patch creators to check if the patch is being applied without having to dig open the log file.
=> Move applied patch log level to success

Utilities/types.h, rpcs3/util/endian.hpp
Generate immediate values instead of emitting runtime byteswap instructions when we know the source values are constant expressions as well. Allowing optimizations, template arguments passing etc.
=> Implement constexpr byteswapping

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
The existing solution is more elegant but can easily trip on false positives.
Fixes https://github.com/RPCS3/rpcs3/issues/8075
=> rsx: Brute-force removal of superseded surfaces

rpcs3/Emu/RSX/RSXFIFO.cpp
There was a bug which led to some rsx crashes where it shouldn't.
=> rsx: Fix false desync events

Utilities/types.h
Check if being able to explicitly construct an object from To type to To type. (assume that is a trivial constructor as std::bit_cast needs)
=> Minor fixup after #8501

rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp
By allowing the SPU Local Storage to wrap around on addressing overflows around 256k+- offsets stores/loads are allowed to not mask the immediate value after the calculating the sum of addresses.
This makes it use a native, single x86 memory address calculation instruction (e.g. as a LEA instruction) instead of separating it into different instructions and masking it everytime.
An example for a start of a function which stores a few registers one after one for registers savings to stack from GOW3:
Before:
https://user-images.githubusercontent.com/18193363/87683427-be936880-c789-11ea-9f88-a94ffd2c7138.png
After:
https://cdn.discordapp.com/attachments/485204327800242177/733052633950191626/unknown.png
Notice how ($SP) is masked with 0x3fff0 only once and there are no additional LEA …
=> SPU LLVM: LS Memory Mirrors (Optimize loads/stores)

rpcs3/Emu/Cell/SPURecompiler.cpp
Try to verify when the FM instruction will produce a result in normalized range for x86 floating point hardware, and avoiding clamping the result when it's used by another instruction. (more performance)
There's more potential in this area but for now only FM is optimized in this way.
=> SPU LLVM: Avoid unecessary clamping in some situations

Utilities/Thread.cpp, Utilities/VirtualMemory.cpp, rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp, rpcs3/Emu/Cell/Modules/sys_spu_.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h, rpcs3/rpcs3qt/breakpoint_list.cpp, rpcs3/rpcs3qt/debugger_list.cpp, rpcs3/rpcs3qt/instruction_editor_dialog.cpp, rpcs3/rpcs3qt/instruction_editor_dialog.h, rpcs3/rpcs3qt/kernel_explorer.cpp
* Hotfix for some versions of Linux which do not ensure 64k aligned allocations by non-fixed mmap after #8592.
* Fix a corner case where utils::shm::unmap_critical breaks virtual allocations on Windows.
* Make spu_thread::offset a private member, all LS accesses are going through spu_thread::_ptr<>() except in DMA transfers and MMIO.
=> SPU: Fixes for LS memory mirrors

rpcs3/Emu/Cell/PPUModule.cpp
Should have made this part of #8582
Creating patches is now one step easier, no need to close the emulator and open the log now. :)
=> Move executable hash log level to success

rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/PPUTranslator.h, rpcs3/Emu/system_config.h
Support enabled Non-Java mode, which originally behaves like FTZ (Flush-To-Zero) and DAZ (Denormals-Are-Zero) both enabled on x86.
On PPU Precise Interpreter both FTZ and DAZ alike behaviours are implemented without changing any setting.
On PPU LLVM only FTZ alike behaviour is supported due to serious needs of optimizations for DAZ alike behaviours, this is not enabled by default and you need the "PPU LLVM Java Mode Handling" setting to be set to true in config file.
I recommend testing this pull request with precise interpreter.
Misc:
Fixes "PPU LLVM Accurate Vector NaN values" to actually respect the settings' value on LLVM which previously was unconditionally enabled in most cases, so if you want to test PPU LLVM you may need to enable this setting as it was unconditionally enabled on …
=> PPU Precise/LLVM: Support NJ modes

rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp
We calculate the `max_width` in `measure_text()` based on the` x_advance` passed to `stbtt_GetPackedQuad`.
But the `render_text` method has a crop functionality that is based on `max_width` and `quad.x1` instead.
`quad.x1` is not equal to `x_advance`, which leads to a mismatch between the measuring logic and the crop logic on some occasions.
Logs:
`for (char c : "abcdefghijklmnopqrstuvwxyz") "Troph" + c;`
```
E {RSX [0x0009350]} RSX: quad.x1 > max_width for 'Trophc': x_advance=29.85 quad.x1=30.23 max_width=30
E {RSX [0x000b76c]} RSX: quad.x1 > max_width for 'Trophf': x_advance=27.47 quad.x1=28.23 max_width=28
E {RSX [0x00080d4]} RSX: quad.x1 > max_width for 'Trophk': x_advance=29.85 quad.x1=30.23 max_width=30
E {RSX [0x00028e8]} RSX: quad.x1 > max_width for 'Trophv': x_advance=29.85 …
```
=> overlays: try to fix unexpected text crop

Utilities/types.h
Hi,
First PR
Trivial fix up to resolve invalid is_constructible test (To,To) to match desired (To,From)
Just one of the changes picked up by my clang compiles so far. Obviously hasn't been a problem so far, but it removes a warning for me :)
Bigger question is probably whether this whole ifdef should be removed, given c++20 has bit_cast
=> Update types.h to fix static_cast test

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKPresent.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKResourceManager.cpp, rpcs3/Emu/RSX/rsx_utils.h
- Fixes a 'bug' where old textures for scratch resources were kept around without being deleted during runtime. It was assumed that there would only ever be a small number of them at any one time, but specially crafted request patterns could cause the number to keep going up forever. See https://github.com/RPCS3/rpcs3/issues/8130
- Implements out of video memory handling. If memory allocation fails, an emergency fallback is invoked that removes as many unneeded resources from the GPU memory as possible. The routines are also run at lower severity level every frame and engage once VRAM usage exceeds 75% for any of the main heaps in use.
- Includes fixup for https://github.com/RPCS3/rpcs3/issues/8075 for some code that mysteriously disappeared during rebase.
Fixes …
=> vk: Improve video memory management

rpcs3/Emu/RSX/VK/VKHelpers.h
another clang directed fix up... might be involved with swizzle..
=> VK_REMAP enum is signed.. but later case comparison is unsigned

rpcs3/Emu/Cell/Modules/cellAudio.cpp
Another simple Clang recommendation.
0.5 being a double, meant that 'left * minus_3db + mid' was being upconverted to double, but then being assigned to out_buffer was truncating without cast.
I think for this we don't need the accuracy of the doubles:
a. we remove a clang warning
b. we possibly gain the most insignificant performance by swapping four double calcs -> float calcs
=> Update cellAudio to use float constants instead of doubles

rpcs3/rpcs3qt/main_window.cpp
- Fix the visibility of the "Update Available!" menu option.
For some reason this works now on my end.
=> Qt: fix download menu visibility

rpcs3/Emu/Cell/SPURecompiler.cpp
Use byte broadcast in order to simplify the code.
=> SPU LLVM: Minor cleanup after #8537

rpcs3/Emu/System.cpp, rpcs3/rpcs3qt/config_adapter.cpp, rpcs3/rpcs3qt/emu_settings.cpp
- Do not crash if a config yml is corrupt. Log an error instead.
- When loading a corrupted config.yml in the gui, a Messagebox is shown.
- Improve error logging when loading a config yml in the Emulator
=> Improve error handling during config loading

Utilities/bin_patch.cpp, Utilities/cheat_info.cpp, Utilities/cheat_info.h, rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/cheat_manager.cpp, rpcs3/rpcs3qt/cheat_manager.h, rpcs3/util/yaml.cpp
Extracted some code from the earlier scrapped PR:
- Don't list search results if the number exceeds 10000. Otherwise memory and rendering time would rise abnormally.
- Disable search buttons if the search field is empty.
- Show "This application is not running" in the value preview when clicking a cheat that belongs to a non-running game.
- Use enum for table columns
- Move cheats.yml to patches folder as requested by some users
- Improve yml parser errors
=> improve cheat manager

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/CPU/CPUThread.h, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp
If the SPU thread was stopped VERY early in its execution it won't even enter spu_thread::cpu_task() which was needed for it to call spu_thread::cpu_stop().
To fix this move it to be a callback of cpu_flag::ret and add this flag to all threads' state when stopping them.
Fixes potential deadlocks in sys_spu_thread_group_join etc when cpu_stop() is not called.
=> SPU: Fix spu_thread::cpu_stop() missed executions

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp
If enabled, SPU tmestamp is always equal to one's complement of the lower 32-bits of PPU timestamp.
Thats what the "Unimplemented SPU Thread options (0x2)" log messages were about.
=> SPU: Implement SYS_SPU_THREAD_OPTION_DEC_SYNC_TB_ENABLE

rpcs3/Emu/CPU/CPUTranslator.cpp, rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
* Add support for 128-bit integers, construct it using the base llvm::APInt.
* Fix the use of llvm::ConstantExpr, we cannot evaluate it as constant data!
Those bugs existed before but they were too rare to be noticed until #8559.
Fixes #8651
=> SPU/PPU LLVM: Fix cpu_translator::get_const_vector<v128>()

rpcs3/headless_application.cpp, rpcs3/main.cpp, rpcs3/main_application.cpp, rpcs3/rpcs3qt/gui_application.cpp
- At the moment only the null video renderer is allowed in headless mode. Abort with a hint otherwise.
- Fix no_return bug introduced in the prior PR.
=> Gracefully abort headless mode with unsupported video renderers

azure-pipelines.yml
Let's give this is shot. Seems to work in testing.
=> CI: Avoid trying to publish builds on forks

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_helpers.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/gcm_enums.h
RSX can generate Z-ordered memory in one- of 2 ways:
1. Through blit engine with the swizzled context flag set. This is handled correctly by forcing all the processing to happen on the CPU, reducing complication.
2. Through the ROPs by rendering in swizzle mode.
Some games are generating 'optimized' textures by first rendering the source linear texture in swizzle mode as the level loads, then copying that memory (now Z ordered) around using blit engine in linear mode and then loading them from the new location as normal swizzled textures. This will work just fine if no flush ever occurs, but if it does happen, we have linear memory in some random address which the game thinks is swizzled. The solution is to keep tracking the bytes from the moment they are marked as swizzled rasterization …
=> rsx: Handle cpu readback of Z-ordered memory

rpcs3/Emu/Cell/Modules/sysPrxForUser.h, rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.h, rpcs3/Emu/Cell/lv2/sys_sync.h
Commit from https://github.com/RPCS3/rpcs3/pull/8227, refactored a bit. Restrict unspecific ppu path to u64(UINT32_MAX) ppu id only, before it was every id that the lower 32-bits of the id were equal to UINT32_MAX such as UINT64_MAX.
=> lv2: Minor fix of "unspecific ppu" path of _sys_lwcond_signal

rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp
Using ordered (and even unordered) floating comparison to determine MIN/MAX floating pointing value results in a bug where the VMAXFP/VMINFP instructions on realhw always select NaN operand as the result if either is a NaN (with the ordering of VA then VB) but on master only the "greater/lower" value is selected making NaN not always return as the result when either of the operands is a NaN.
The correct behaviour is the opposite as x86's instructions MAXPS, MINPS (as std::fmax, std::fmin). So use the opposite operand from the result of the opposite instruction.
Misc: Improve cpu_translator::fre() and cpu_translator::frsqe() to accept unevaluated expressions, evaluate them in-place.
=> PPU: Fix VMAXFP, VMINFP NaN handling

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/patch_manager_dialog.cpp, rpcs3/rpcs3qt/patch_manager_dialog.h, rpcs3/rpcs3qt/persistent_settings.cpp, rpcs3/rpcs3qt/persistent_settings.h, rpcs3/rpcs3qt/save_data_list_dialog.cpp, rpcs3/rpcs3qt/save_data_list_dialog.h, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/save_manager_dialog.h, rpcs3/rpcs3qt/settings.cpp, rpcs3/rpcs3qt/settings.h, rpcs3/rpcs3qt/user_manager_dialog.cpp, rpcs3/rpcs3qt/user_manager_dialog.h
Moves
- Titles
- Notes
- SaveData:Notes
- Users:active_user
to persistent settings
fixes #8670
=> Qt: move some more settings to persistent_settings

rpcs3/rpcs3qt/emu_settings.cpp
Goose complained about seeing a fatal when switching back to a master build from RPCN, because the RPCN option in the PSN Setting combobox doesnt exist. And yeah, fataling doesnt really make sense when you can fall back to a default value just fine.
This PR demotes the logging level to error in every problematic case when there's a default value to fall back to, while parsing a config file.
=> qt/cfg: make some cfg logs error instead of fatal

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/main.cpp, rpcs3/util/yaml.cpp
Add config override as cli arg: `--config <path>`
And add some more logging
With this config parameter the emulator essentially skips all other config files and only applies the config file found in the specified path.
=> CLI config override

rpcs3/rpcs3qt/pad_settings_dialog.cpp
Looks like repainting stuff inside a resizeable layout is slow AF
fixes #8684
=> Qt: fix input lag in pad settings

rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/main_window.ui
- Renamed "Install PKG" to "Install Packages/Raps"
- The related file dialog now accepts rap files too
- The related file dialog now accepts multiple files
- The installation of multiple packages opens the same dialog as the drag and drop action.
- Rap files now overwrite the old files and throw an error if this isn't possible
=> [TESTERS NEEDED] Improve Package install menu option

rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Reset swizzle flag to false automatically on section reset.
- Detect render target payload and extract swizzle information from it.
Follow-up to https://github.com/RPCS3/rpcs3/pull/8664
Fixes https://github.com/RPCS3/rpcs3/issues/8692
=> [HOTFIX] rsx: Improve swizzled layout detection

rpcs3/Emu/Cell/lv2/sys_usbd.cpp
Tidy up fake transfer iterator handling. erase invalidates all iterators including the current iterator (i.e. 'it'), given precedence ordering this was UB prior to C++17.  Splitting out to use return iterator from erase seems cleaner.
Also added some additional info to usb debug message to potentially help with #8666, and used the atomic (dev_counter) less often
=> sys_usbd tidy ups

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUModule.h
Makes for a slightly 'cleaner' interface in my opinion, may also assist with adding thread read/write concurrency support in future if ever required (have left that out of this commit to match existing function).
Very slight performance improvements were seen in representative testing.
https://quick-bench.com/q/GMbgeNc-mZc21aqOKCofnbzPZvg
I didn't investigate whether static initialisation of the static_modules might actually be possible here, perhaps there's a way to do a constexpr / consteval of this.
=> Replace ppu_module_manager Function Static with Class Static variable (static module map)

Utilities/sysinfo.cpp, Utilities/sysinfo.h
Newer processors have a much wider range of AVX-512 instructions avaliable than Skylake-X does, so let's detect that.
Icelake-client tier AVX-512 Implies support for everything that Skylake-X supports (`AVX512F, AVX512CD, AVX512DQ, AVX512BW, AVX512VL`) as well as `AVX512IFMA, AVX512VBMI, AVX512VBMI2, AVX512VPOPCNTDQ, AVX512BITALG, AVX512VNNI, AVX512VPCLMULQDQ, AVX512GFNI,` and `AVX512VAES`
The logging was also changed a little. If you have AVX-512 it will now print AVX-512 in the log, rather than AVX++. Icelake-client tier support is indicated by AVX-512+.
=> Utils: Add detection for Icelake-client tier AVX-512

rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
Fixes signed zeroes handling of FMA instructions.
In short when adding +0 to a -0 the result changes from being negative to posistive zero which means FMA with 0 addend is **not** the same as FM.
=> SPU/PPU LLVM: Fix FMA signed zeroes handling

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
While debugging CoD Ghosts I've noticed that when the game loads its savedata it checks if the file type matches its expectations such as secured files, if they don't it will crash with an error message.
After some debugging I've noticed that all files' information is lost during iteration of savedata_op() when the PARAM.SFO is modified! causing the loaded savedata after modification to fail the checks by the game.
This fixes this issue.
**This means that all savedata created before this pr will remain broken, only newly created savedata with this pr will allow the games to proceed. You must delete it before testing this pr!**
Remaining testing needed:
=> cellSaveData: Fix loss of "BLIST" and files' information in PARAM.SFO

rpcs3/Emu/CPU/CPUTranslator.cpp, rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/PPUTranslator.cpp
new in AVX-512VBMI are the VPERMI2B and VPERMT2B instructions. These instructions are an exact match for the behavior of the altivec instruction VPERM, besides operating in reverse byte order. So let's use them when the cpu supports it.
Saves on 2 pshufbs, 1 shift, and 1 blend.
=> PPU LLVM: Use VPERM2B to emulate VPERM

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/GL/GLPresent.cpp, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/GSRender.h, rpcs3/Emu/RSX/VK/VKFormats.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKPresent.cpp, rpcs3/Emu/RSX/VK/VKResolveHelper.cpp, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
Map these formats to RGBA layout. While this layout was not supported by some drivers when Vulkan launched, things have improved a lot over the years and now RGBA layout is widely supported. This avoids using compute shaders and sampler swizzle shenanigans in several places.
Fixes https://github.com/RPCS3/rpcs3/issues/8456
=> rsx: Simplify support for ABGR formats

rpcs3/Emu/Cell/SPUThread.cpp
Because TSX path of reservations is not really 100% based on actual TSX, the parts which do not need to support RSX reservations setting.
=> SPU: Implement RSX accurate reservations on TSX

rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
Add missing cases for +-0 for CPUs which do not support hw FMA. Also optimize PPU VNMSUBFP hw FMA path a bit.
=> SPU/PPU LLVM: Improve 0 addend FMA detection

rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/SPURecompiler.cpp
The main trick is here is that we make use of the VGF2P8AFFINEQB instruction as a makeshift "shuffle bits" instruction. (see [this ](http://0x80.pl/articles/avx512-galois-field-for-bit-shuffling.html)for an exmaple) This instruction is intended for cryptography purposes and is only 1uop.
The intent is to handle the "special case" values of SHUFB more efficiently, that is:
```
10xxxxxx = 0x00
110xxxxx = 0xFF
111xxxxx = 0x80
```
After executing VGF2P8AFFINEQB with our mask on the SHUFB index we will get the values:
```
10xxxxxx = 0x00
110xxxxx = 0x80
111xxxxx = 0xFF
```
To fix up the results, we need to xor with 0x7F. Luckily VGF2P8AFFINEQB let's us embed that into the instruction itself, which will give us:
```
10xxxxxx = 0x7F
110xxxxx = 0xFF
111xxxxx = 0x80
```
The result for `10xxxxxx` …
=> SPU LLVM: Add icelake optimized paths for SHUFB

3rdparty/7zlib.vcxproj, 3rdparty/hidapi.vcxproj, 3rdparty/libcurl.vcxproj, 3rdparty/libpng.vcxproj, 3rdparty/libusb_static.vcxproj, 3rdparty/pnglibconf.vcxproj, 3rdparty/wolfssl.vcxproj, 3rdparty/xxhash.vcxproj, 3rdparty/yaml-cpp.vcxproj, 3rdparty/zlib.vcxproj, Utilities/types.h, asmjitsrc/asmjit.vcxproj, llvm_build/llvm_build.vcxproj, rpcs3/GLGSRender.vcxproj, rpcs3/OpenAL.vcxproj, rpcs3/VKGSRender.vcxproj, rpcs3/XAudio.vcxproj, rpcs3/emucore.vcxproj, rpcs3/rpcs3.vcxproj
Add support for compilation on x64 toolchain (x86 cl.exe was running out of heap space in vm.cpp)
Also took the opportunity to change compile optimisation from /Ox to /O2, as /O2 provides better optimisation than does /Ox
Also, we shouldn't be explicitly setting compiler tool defines (__cpp_lib_bitops), so remove that from types.h
=> MSVC changes

rpcs3/Emu/RSX/rsx_utils.h
* Fix support for values >= (1 << 31) in rsx::ceil_log2 due to bitshift carry bug, do ceiling manually instead.
* ~~Some cleanup and impovements using c++20.~~ Fuck compilers.
=> rsx: Minor rsx::ceil_log2 bugfix

rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm_reservation.h
This function is very rare but it has a hidden bug of incrementing reservation timestamp unconditionally even when lock bits are set.
=> Fix vm::reservation_update

rpcs3/Input/evdev_joystick_handler.cpp
This may help to understand why some devices just don't work.
Some controllers actually have very bad drivers that may even report additional unused axis.
=> evdev: log axis information in pad settings

rpcs3/Emu/CPU/CPUThread.cpp
Something with unhandled non-TSX reservation pauses so stepping in this case causes a deadlock.
=> Debugger: Fix PPU stepping on non-TSX

rpcs3/Emu/CPU/CPUDisAsm.h, rpcs3/Emu/Cell/PPCDisAsm.h, rpcs3/Emu/Cell/PPUDisAsm.h, rpcs3/Emu/Cell/SPUDisAsm.h
Signed hexadecimal format rules in this pull request:
1. Values which are negative will be preceeded by a minus sign.
2. Values which their absolute value is greater than 9 will be preceeded by a `0x` prefix in addition to the above sign character rule.
Use a single representation for cleaner output with no additional represenation after '#' sign as I will readd this field in the future for a much more useful purpose.
I also took the liberty to fix SPU instructions output which use in practice 8-bit unsigned immediates but in code use op.si10 such as ANDBI.
PPU Examples:
`lwz r31, -256(r1) #ffffff00`
Will become:
`lwz r31, -0x100(r1)`
`xori r6, -8(r1) #fffffff8`
Will become:
`xori r6, -8(r1)`
`ori r3, 2(r1) #2`
Will become:
`ori r3, 2(r1)`
SPU Examples (SPU didn't use # field already): …
=> Debugger: Use Signed Hexadecimal formatting for immediates

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp
What the SPU timers event is for: because the SPU timer is a very incapable 32-bit timer, it underflows relatively frequantely (about a little more than a minute) and when it does the event is there to notify the program to readjust its time calculations. (a bit like a carry on unsigned overflow)
What's fixed:
* The event was fired as long as the value was negative - wrong! only when underflow occurs the event should be fired and only once per undeflow. (i.e. when its value exactly becomes UINT32_MAX after 0)
* As long as ch_dec_value is 0 the event was fired (such as if  SYS_SPU_THREAD_OPTION_DEC_SYNC_TB_ENABLE was unset) - wrong! obvious bug so there's not much to discuss on it,
=> SPU: Fix timer events

rpcs3/Emu/Cell/PPUDisAsm.cpp
Should get rid of most of raw rotate & mask instructions in favour of simple forms.
=> Debugger: Implement PPU SLWI, SRWI, SLDI mnemonics

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_list.cpp, rpcs3/rpcs3qt/register_editor_dialog.cpp, rpcs3/rpcs3qt/register_editor_dialog.h
* Fix scrolling of instructions using PageUp, PageDown, KeyUp and KeyDown keys. They were hilariously broken.
* Fix PPU instructions editor (such thing exists, press e while viewing the debugger), it was failing to patch instructions because they sit on read-only memory. Use memory bypassing protection for patching. Also fix non-executable memory patching as well.
* Fix registers editor (such thing exists, press r while viewing the debugger) on editing of all SPU registers, PPU registers from f0 to f31, v0 to v31, r0 to r31.
* Add new set of "registers" to PPU registers editor, "ff(index)". They refer to the same floating point registers f0 to f31 but in double precision floating point format instead of hexadecimal. (ff31, ff30, ff29 etc.)
* Add new registers available for editing in SPU …
=> Debugger Improvements x999

azure-pipelines.yml
Forces toolkit to 14.25.28610 on Azure so that we don't get the build errors with templates.
It hopefully can be removed once VS 16.8 is the official image on Azure.
=> Forces MSVC Toolkit to 14.25.28610 in Azure Pipelines

rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/tooltips.h
As requested in #4502, the ability to auto-hide the cursor after a configurable timeout period.
This does not 'lock the mouse cursor within the game window boundaries', however I'm not sure that would be desirable.
With this implementation, the cursor is visible again when moved.
If alternative behaviour is desired, perhaps the 'Show Cursor in Fullscreen' could just be converted into a 'Hide Cursor in Game' setting (in which case it would hide the cursor in both windowed and fullscreen modes).
In line with the Show Cursor in Fullscreen settings, these settings are only updated when the render window is first launched, and not during the game.
This could be revised (along with the Fullscreen Cursor) if it's more desired.
Also removed what appeared to be a stray space at the end of the …
=> GUI: Auto-hide of mouse cursor if idle

rpcs3/rpcs3qt/localized.cpp
I noticed there is many if else cases in the file rpcs3/rpcs3qt/localized.cpp.
This file generates messages when there is a update available and compute the diff time in order to print it.
[QT Linguist](https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals) suggest to write them like
```
tr("%n message(s) saved", "", n)
```
instead of
```
n == 1 ? tr("%n message saved") : tr("%n messages saved")
```
This PR is intended to fix that.
**Remarks**
Rebased from #8473 + allows edits from maintainers
=> Qt: simplify GetVerboseTimeByMs logic

rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
The original commits for the mouse hide on idle included definitions for tooltips, but didn't assign them correctly.
This fixes that up, so that tooltips exist.
And the resize height / width settings didn't have any tooltip applied.
So this extends the current resize setting tooltip to also trigger on the height / width hover (at least indicating that they are associated with this setting).
=> GUI: Tooltips for mouse hide if idle and resize on boot

rpcs3/Emu/RSX/rsx_methods.h
In case of element re-arrangement, the barrier should obey the current insertion pointer.
Follow-up to https://github.com/RPCS3/rpcs3/pull/8583
Fixes https://github.com/RPCS3/rpcs3/issues/8722
=> rsx: Fix execution barrier insertion

rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/system_config.h
From CELL BE public docs about single-copy atomicity:
the following
> _"single register accesses are always atomic:
• All byte accesses
• Halfword accesses aligned on halfword boundaries
• Word accesses aligned on word boundaries
• Doubleword accesses aligned on doubleword boundaries
• Quadword accesses aligned on quadword boundaries
• Cache line accesses by DMA commands aligned on cache line boundaries
No other accesses are guaranteed to be atomic.
An access that is not atomic is performed as a set of smaller, disjointed atomic accesses."_ 
(the last point) means both PUT and GET full and aligned cache lines accesses are atomic, I updated the testcase in #8822 to use GET and not GETLLAR and it works. I remember why it didnt work initially and it was my mistake.
I guess its pretty cheap …
=> SPU: Make GET's full and aligned cache line accesses atomic with Accurate DMA

rpcs3/Emu/RSX/CgBinaryProgram.h
Replace manual string creation with call to std::string() constructor passing in char*
Perhaps I'm missing something... but it appears we have a null terminated string (a cstr if you will) within the m_buffer, starting from offset.
We want to create a std::string from it... I say, that std::string will be 'better' at this than anything we would want to hand roll.
=> RSX: Update manual string creation -> std::string()

rpcs3/Emu/Cell/SPUThread.cpp
Sigh... forgot to increment `eal` after each sub-transfer so it tried to acquire the lock of the same address everytime even though we progressed on execution.
The testcase only ever uses 1 cache line so I din't notice that it was broken.
Should also improve the performance of each sub-tranfers as their size can be greater now (the proper size).
Much less spam of LWARX/LDARX took too long on TSX path with Accurate DMA because of it.
=> SPU: Fix acquiring reservation locks on DMA consists of multiple cache lines (Accurate DMA)

rpcs3/Emu/Cell/SPUThread.cpp
Should fix crashes with Accurate DMA on non-MSVC compilers, MSVC doesnt care and emits unaligned instructions unconditionally so it worked there. Consistent with mov_rdata as well.
=> SPU: Use unaligned AVX instructions for cmp_data_avx

rpcs3/rpcs3qt/auto_pause_settings_dialog.cpp, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/instruction_editor_dialog.cpp, rpcs3/rpcs3qt/osk_dialog_frame.cpp, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/trophy_notification_frame.cpp
Standardising on 'OK' for all base language uses (rather than 'Ok', or 'Okay').
It's perceived as the 'most correct' variant, and importantly having a single variant is best from a translation perspective.
Added plurality handling for multiple PPU caches created.
Added plurality handling for multiple items deleted in save manager.
Capitalised trophy grade to align with Sony terminology, and expanded to include 'You have earned ...' portion.
Brought trophy name position into translatable string (for languages that might really want to deviate from SVO)
=> GUI: Additional translation entries

rpcs3/Emu/Cell/SPUThread.cpp
Two explenations:
- We execute MFC transfers immediately and report to the program that the transfer is complete, so it should really be like that.
- Although for all commands which use reservation lock bits PUT transfers appear sequantially consistent, it is not the case for PPU reads/writes which do not use the reservation lock bits.
=> SPU: Make PUT transfers use SEQ-CST ordering on Accurate DMA

rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h
A followup to https://github.com/RPCS3/rpcs3/pull/8664, implements the upload leg of the swizzled Cell<->RSX transfers.
=> gl/vk: Support swizzled data for RCB/RDB

rpcs3/Emu/Cell/SPUThread.cpp
Doesnt really change emitted code because MSVC, just a minor typo fix as the loads are unaligned. And on non-MSVC path unaligned instructions are being used exclusively.
=> SPU: Use unaligned instructions in mov_rdata_avx (MSVC)

Utilities/Thread.h, rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellNetCtl.cpp, rpcs3/Emu/Cell/Modules/cellVoice.cpp, rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/Modules/sceNp.h, rpcs3/Emu/Cell/Modules/sceNp2.cpp, rpcs3/Emu/Cell/lv2/sys_net.cpp, rpcs3/Emu/Cell/lv2/sys_net.h, rpcs3/Emu/NP/np_handler.cpp, rpcs3/Emu/NP/np_handler.h, rpcs3/Emu/NP/np_structs_extra.cpp, rpcs3/Emu/NP/rpcn_client.cpp, rpcs3/Emu/NP/rpcn_client.h, rpcs3/Emu/NP/signaling_handler.cpp, rpcs3/Emu/NP/signaling_handler.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/rpcn_settings_dialog.cpp
If you want to test:
- RPCN Test server is test-np.rpcs3.net
- You need to make an account(email isn't checked, you can just click Create Account after changing host to test server)
- This server is temporary and can be taken down at any time
- Don't use the test server to connect to DeS as you won't be able to connect to other users.
What's in the PR:
- Improved signaling
Now for games that use sceNpMatching2Signaling connectivity is ensured by address negociation if negociation is possible, it should improve connectivity between nat1/2 and nat3 users(though ofc nat3/nat3 is still impossible).
- Implements sceNpSignaling
Some games use an older version of signaling and it's now implemented.
- Fixes, so many fixes!
STREAM_P2P sockets are now properly implemented, fixed many bugs all over …
=> Implement sceNpSignaling & signaling improvements

rpcs3/Emu/Cell/lv2/sys_process.cpp
If exitspawn failed for any reason such as the referenced file is missing the current process must exit anyways, it just won't proceed with a new process. Add logging for it.
=> sys_process: Implement exitspawn error checking

rpcs3/Emu/Cell/Modules/cellSysutil.cpp
Implements `ID_CURRENT_USER_HAS_NP_ACCOUNT`, a boolean that is true when np_psn_status is either Fake or RPCN 
Fixes:
- Plex for PS3
**Before**
One could use Plex in the background but the error is non-closable 
**After**
Plex works without any error
=> hle: Implement ID_CURRENT_USER_HAS_NP_ACCOUNT

rpcs3/Input/keyboard_pad_handler.cpp, rpcs3/Input/keyboard_pad_handler.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/tooltips.h
- Fixes restart of the mouse hide on idle timer.
- Fixes falsely locked mouse in fullscreen when no mouse move was configured by checking for mouse move assignment in the related mouseMoveEvent and skipping it appropriately.
=> Mouse hide and lock fixes

rpcs3/Emu/Cell/SPUThread.cpp
This hack didnt even work until #7297 and there were 0 reports of any related issue in recent years.
=> SPU: Remove STOP 0x0 hack

Utilities/bin_patch.cpp, Utilities/bin_patch.h, rpcs3/rpcs3qt/downloader.cpp, rpcs3/rpcs3qt/downloader.h, rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/patch_manager_dialog.cpp, rpcs3/rpcs3qt/patch_manager_dialog.h, rpcs3/rpcs3qt/patch_manager_dialog.ui, rpcs3/rpcs3qt/update_manager.cpp, rpcs3/util/yaml.cpp
- Improves some layouts in the patch manager to mitigate issues with long strings.
- Adds a scrollarea to the Notes label.
- Adds a download button which downloads the latest official patch file and replaces your patch.yml if the checksum doesn't match.
Reuses some code from rpcs3 updater, so maybe there is a regression.
The old patch file will be backed up to patch.yml.old in case that you realize that you still had some custom stuff in the file.
This should hopefully not be the case, since you aren't supposed to touch that particular file anyway.
=> Patch manager update

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/VK/VKDraw.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
Just use hardware PCF, it makes everyone's life easier.
Fixes https://github.com/RPCS3/rpcs3/issues/8805
=> vk: Simplify shadow comparison operations for non-integer formats

Utilities/File.cpp, Utilities/bin_patch.cpp, rpcs3/rpcs3qt/patch_manager_dialog.cpp
Should fix some file copy errors on linux.
reported by @AniLeo
thx @RipleyTom for finding the solution
This may fix some random issues:
- when downloading patch files and backing up the old patch files
- when installing rap files
- when some ui icons are copied around
=> Fix fs::copy_file on linux

rpcs3/rpcs3qt/patch_manager_dialog.cpp
It was spawning on top of the main window instead of the patch manager
=> Fix patch downloader pop up location

Utilities/BitField.h
There was I, coding innocently using bitfields, until a scary bitfield AND assign operator erased all of the value bits outside of the bitfield!
Now matches bitfield = bitfield & value as it should.
=> Fix bitfield operator &=

.gitmodules, 3rdparty/CMakeLists.txt, 3rdparty/curl_extra/wolfssl/options.h, 3rdparty/libcurl.vcxproj, 3rdparty/libusb_static.vcxproj, 3rdparty/wolfssl.vcxproj
Updates libcurl submodule to use official repo and updates to 7.72.0
Updates wolfssl submodule to use official repo and updates to latest(it was needed for a CMake fix).
Ensures windows/linux version wolfssl are built with same options.
Adds a USE_SYSTEM_WOLFSSL option to try to find package locally.
=> Updates wolfssl and curl to official repos

Utilities/Thread.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/util/atomic.cpp
Hotfix, set state notifier before value comparison! (change to SEQ-CST atomic store for this purpose as well)
Fixes #8807 and might fix some Emulator stopping hanging issue.
=> atomic.hpp/sys_spu: Fix atomic_storage_futex::raw_notify, minor fix of cpu_flag::ret usage

rpcs3/Emu/RSX/Common/GLSLCommon.h
Fixes shader compilation crash when fp16 data types are present as input coordinates to shadow sampling routines.
=> rsx: Add support for mixed data types when sampling shadow coordinates

rpcs3/rpcs3qt/kernel_explorer.cpp
Before it was displaying "unknown" for valid PPU ids, also display "dead" and output raw value for "unknown" owner.
=> kernel-explorer: Fix lwmutex owner display

rpcs3/rpcs3qt/kernel_explorer.cpp
Forgot about this feature which relatively recently added, just use the original idm function instead for simplicity.
=> kernel-explorer: Account for PPU IDs invalidation in lwmutex

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.h, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/rpcs3qt/register_editor_dialog.cpp
The following conditions set the SPU event channel count:
- An event occurs, and the corresponding mask is 1 in the SPU Write Event Mask Channel.
- The SPU Write Event Mask Channel is written with a 1 in a bit position that corresponds to a 1.
- Enabled events are pending after a write of the SPU Write Event Acknowledgment Channel.
The following condition clear the SPU event channel count:
- Reading from SPU Read Event Status Channel.
Interrupt fixes:
Added a missing interrupt invocation check in SPU_WrEventMask in case newly masked events set the events count.
=> SPU: Implement events channel count, Minor Interrupts fixes

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
They seem to be related to cellLibprof or something (performance monitoring) and are no-ops on CEX console.
=> SPU: Implement channels 70, 71, add naming for channel 69

rpcs3/Emu/Cell/Modules/cellFs.cpp, rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp
* Fix cellGame FXO data reset, some members were not reset in verious places such as can_create and restrict_sfo_params. Unify the reset in cellGameContentPermit instead.
* Implement CELL_GAME_ERROR_EXIST error in cellGameCreateGameData on attempt to create existing gamedata. (cellGameDataCheck returned CELL_OK and not CELL_GAME_RET_NONE)
* Make block size reported as size for directories in cellFsStat/cellFsReadDir. seems the case on realhw for dev_hdd0/dev_hdd1/dev_bdvd.
* Do not expose real disk stats (HDD0) to a ps3 guest program, use hardcoded values for now instead.
* More accurate HDD1 available size calculation.
* Return sector aligned size for available drives size instead of unaligned size.
* Always reset size in cellGameGetSizeKB.
* Rewrite cellFsGetFreeSize to use LLE …
=> cellFs/cellGame Improvements

rpcs3/Emu/Cell/Modules/cellGame.cpp
This behaviour was observed in [BCUS98208] LittleBigPlanet, SetParamString is still not allowed though.
Thanks to #8799 the bug was revealed and a fix was made.
=> Fix cellGamePatchCheck PARAM.SFO reads

Utilities/bin_patch.cpp, Utilities/bin_patch.h, rpcs3/Emu/System.cpp
I forgot to check whether part of the game version is empty.
This fix should match the logic we apply in the gamelist and therefore fix some COD3 patch issue.
=> Apply patch when APP_VER is unknown

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
fixes #7431 Soldner-X
Assuming that a SceNpCommunicationId should have a format like "TEST12345", then there is no need to delete termination characters after we already created a truncated string with 9 characters + null terminator.
The current behaviour does not work at all, because in case that we actually have a non-null termination character, deleteTerminateChar will step over the last x chars in the already truncated ID until it forcefully finds a character of its liking. eg. term='2': "TEST12345" => "TEST1" => "TEST1_00"
=> HLE: Fix sceNpTrophyCreateContext

rpcs3/Emu/Io/pad_config.cpp, rpcs3/Emu/Io/pad_config.h, rpcs3/Input/keyboard_pad_handler.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp
We accidentally always saved keyboard to Player 1 if null was selected.
The new code will only apply keyboard by default if the config file was not found.
We do not have a need for a fallback anymore, unless we actually use RPCS3 for the first time.
Since the pad settings are dynamic, the user can change it anytime anyway.
probably fixes #8841
=> Qt/Input: fix default pad handler

rpcs3/Emu/Cell/Modules/cellGame.cpp
Return this error when the game content exists but its type does not match the `type` argument, similar to how cellGameDataCheckCreate2 does this.
=> HLE: Implement ERROR_BROKEN in cellGameDataCheck

rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
- Always force typeless copy if memory is crossing aspect boundary.
- Properly pass format_class information during RTV/DSV resource barriers.
- Improve image transfer and scaling for vulkan. This makes it possible to bind two transfers to/from the same helper resource. Also significantly optimizes transfer handling in the slow path required for scaling operations which had a ton of unnecessary transfers.
Fixes https://github.com/RPCS3/rpcs3/issues/8944
Fixes https://github.com/RPCS3/rpcs3/issues/8846
=> rsx/vk: Image handling improvements

Utilities/File.h, rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/VFS.cpp, rpcs3/Emu/VFS.h, rpcs3/Loader/TRP.cpp
* Do not allow to create corrupted trophy data on failure, either create it whole or not at all. (by creating files in a a temporary directory then renaming to the trophy data directory)
* Do not use exceptions such as when file creation fails, use errors instead. (used to throw fs::file is null)
* Fix fs::g_tls_error error reporting.
* Fix filename of created files: add missing vfs::escape usage on filename.
* Implement SCE_NP_TROPHY_STATUS_NOT_INSTALLED.
* Fix error checking of callback status, do not register context in this case.
=> sceNpTrophyRegisterContext: Improvements

rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/persistent_settings.cpp, rpcs3/rpcs3qt/persistent_settings.h
Fixes playtime being wiped out when running the game with `--no-gui`. Since the initial value of `m_playtime` was not being set, timers added playtime to 0.
To avoid such mistakes in the future, add playtime to the value read from settings.
=> Add playtime to the value from settings

rpcs3/Input/mm_joystick_handler.cpp
The latest MSVC 16.8 Preview 3.1 cl.exe no longer likes the implicit conversion from false->std::shared_ptr
But it's happy with nullptr
Not the ideal solution, but it will kick the can down the road a little.
=> mm_joystick_handler: MSVC 16.8 Preview 3.1 compiler fix

rpcs3/Emu/Cell/Modules/cellGame.cpp
Testcase: https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellGameDataCheck
Also adds tests for #8945 btw.
=> HLE: Always return empty paths if game content does not exist in GameContentPermit

rpcs3/rpcs3qt/register_editor_dialog.cpp
It might be super hacky (and not useful) to allow to change reservation address or acquire a reservation, BUT it is super useful to explicitly clear a reservation for debugging etc while it being not hacky.
Any value you write in the field for this "register" is valid and will cause a reservation lost, its name is "Reserv Invalidation".
=> Registers Editor: Implement PPU/SPU reservation control

Utilities/File.cpp, Utilities/File.h, rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/Modules/cellGifDec.cpp, rpcs3/Emu/Cell/Modules/cellJpgDec.cpp, rpcs3/Emu/Cell/Modules/cellPngDec.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/Modules/cellSysCache.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_fs.h, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/VFS.cpp, rpcs3/Emu/VFS.h, rpcs3/Loader/TRP.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
I've noticed that when MoveFileEx is called on a directory with opened file handles it returns an access error, it even affects one of my cellSysCache tests which was my testcase for this fix.
"Suspend" opened sys_fs file handles in such case by closing, fs::rename then reopen on the new (if succeeded) or old file path.
Partially addresses #8891 (fixes Battlefieled BC2)
Also: add guest filesystem information in kernel explorer and cellSysCache improvemenrs.
=> Win32 FS: Rewrite (fix) vfs::host::rename, Fix fs::utime for directories

rpcs3/Emu/Cell/Modules/cellGame.cpp
And add missing vfs::escape usage.
=> Compilation fix

Utilities/File.cpp, Utilities/File.h, rpcs3/Crypto/utils.cpp, rpcs3/Emu/VFS.cpp
It seems like MSVC 16.8 preview versions do not like ref capturing of constexpr reference for some reason. Cna aslo emit better code because of more constexpr added.
=> MSVC bug workaround

rpcs3/Emu/Cell/lv2/sys_memory.h, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.h
Reversed from syscalls disasm: ![image](https://user-images.githubusercontent.com/18193363/94341811-292c1480-0015-11eb-8d1e-0140cdcb46ca.png)
Notice the comparison for ENOMEM is in 64-bits and not 32-bits.
=> sys_mmapper: return ENOMEM on memory greater than UINT32_MAX

rpcs3/Emu/Cell/Modules/cellKb.cpp, rpcs3/Emu/Cell/Modules/cellMouse.cpp, rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Cell/Modules/sys_io_.cpp, rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Memory/vm.cpp
* Implement sys_config's PPU stack for "_cfg_evt_hndlr" thread, I've discovered this through hw testing of stack spaces after calling cellPad/Kb/MouseInit, to confirm Ive looked at disassmebly as well for the exact behaviour. (one thread for all instances until they all close)
* Demi-fix for vm memory stack deallocation on stack area destructor: Always reset memory flags.
Also always clear stack memory on Emu.Stop(). (do not rely on manual cleanup)
* Fix sys_memory_get_page_attribute stack access rights to match realhw.
Testcase: https://github.com/elad335/myps3tests/tree/master/ppu_tests/print%20ppu%20stacks
Fixes #5875
Why it was fixed? the PPU written to memory outside of its stack bounds and failed on rpcs3, clearly into a poor and inactive firmware PPU stack area so it even goes …
=> vm/sys_config/sys_memory: Stack fixes

3rdparty/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellSearch.cpp, rpcs3/Emu/RSX/Capture/rsx_capture.cpp
Removed build of XXHSUM test application for xxHash also.
~~Migrated existing XXH64 uses to XXH3_64bits (we were providing seeds of 0, so we don't need the third parameter).~~
=> xxHash: Update to v0.8.0 xxHash (and XXH3 hash algorithm)

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp
- Rewrites the vertex decoder to emit much simpler and smaller code which in turn drastically speeds up link time. On GCN GPUs this can result in almost 2x speedup of shader link time which means less time wasted waiting for shaders to compile. Resulting bytecode is almost 30% smaller as well, which may help performance on low end GPUs and/or IGPs.
- Reimplements fp32->fp16 casting to use GPU native instructions. This seems to work on my AMD card correctly and still preserves INF/NaN special encoding after the cast. 10-15% instruction count savings.
- Use intrinsics wherever possible to take advantage of native hardware instructions. Replaces many shift-and operations with a single bfe and shift-or with bfi. Generates slightly smaller code but more importantly - it is much cleaner and …
=> rsx: Improve shader decompiler output

rpcs3/Emu/RSX/Common/GLSLCommon.h
- Bitwise or does not evaluate correctly for some hardware. Substitute with subtraction instead.
Fixes https://github.com/RPCS3/rpcs3/issues/8990
=> rsx/codegen: Workaround for borked hardware

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/system_config.h
Implement support for 128-byte reservation load and store coherency when using the added setting "Accurate PPU 128-byte reservations".
An additional setting "Inaccurate PPU reservations loop instructions count" was added to use accurate path only for long reservations loop if enabled, when specifing 0 for it it's always accurate. (the setting is ignored if accurate 128-byte reservations are disabled)
Accurate 128-byte reservations make the reservation op fail if memory of the whole cache line has changed during the reservation op, not just the pointed 4/8 bytes by LWARX/LDARX, and makes it possible to store in STDCX/STWCX using a different address inside the same cache line as this hw test proves :  https://github.com/elad335/myps3tests/blob/master/spu_tests/atomic%20reservations%20tests/e …
=> PPU: Implement support for 128-byte reservations coherency

rpcs3/Emu/Cell/PPUThread.h
I remember testing it on realhw at some point and thats the limit, it is the limit set by VSH using syscall 55. you can see it even when running VSH with special builds. Kinda like how sys_spu_initialize works.
=> Set max PPU threads to 100

rpcs3/Emu/Cell/SPUThread.cpp
* Use spu_mfc_cmd formatter to log MFC commands, same as the SPU debugger.
* Log all bits of list command items.
* Replace some exceptions with access violations as it should like in "RawSPU Not Found".
=> SPU: Simplify logging of MFC commands

rpcs3/Emu/Cell/SPUThread.cpp
Do not rely on volatile storage (SPU Local Storage) to store constant data as its data may be changed by another thread concurrently.
=> SPU: Fix extremely rare bug of GETLLAR

rpcs3/Emu/Cell/SPURecompiler.cpp
Remove redundent postive 0 additions.
=> SPU: Remove dead additions in Accurate Xfloat

rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/Modules/cellSpurs.h, rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp
* Fix race conditions, bits ordering.
=> cellSpurs: Fix HLE workload signalling, taskset fixes

rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/lv2/sys_process.cpp, rpcs3/Emu/Cell/lv2/sys_process.h
Used by cellSpurs instance creation functions to validate starting 128 byte of specfied CellSpurs address is capable of SPU reservations.
This syscall does not care if the address itself is mapped, only the 256mb region of it. (EINVAL if does not exist)
Restrictions found (EPERM):
* sys_vm memory is not allowed.
* PPU stack are is not allowed.
* Private SPU MMIO is not allowed with RawSPU flag.
Testcase : https://github.com/elad335/myps3tests/tree/master/ppu_tests/sys_process_is_spu_lock_line_reservation_address
The testcase works by finding 2 addressed in every aligned 256mb of the 4GB address space: mapped and unmapped and passses both to the syscall, when unfound it wont be passed to the syscall.
It allocates as many region types as possible, and I also tested when some were not …
=> Implement sys_process_is_spu_lock_line_reservation_address

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/RSX/VK/VKDraw.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKQueryPool.cpp, rpcs3/Emu/RSX/VK/VKQueryPool.h, rpcs3/Emu/RSX/VK/VKResourceManager.h, rpcs3/Emu/RSX/rsx_utils.h, rpcs3/VKGSRender.vcxproj, rpcs3/VKGSRender.vcxproj.filters
Reimplements query pool reference usage so that the same query object is not consumed twice without guarantee that it is not in use anymore. Currently this is just done by deleting the pool and allocating a new one, although host reset is also another possibility. I don't see the point of using host reset though, since queries are only reallocated after many frames, typically about half a minute.
Fixes https://github.com/RPCS3/rpcs3/issues/8889
=> vk: Reimplement GPU query management

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/System.cpp, rpcs3/Loader/ELF.h
* Search SPU images in PRX/overlay modules, allows to patch cellSpurs' SPU images.
* Remove stupid restriction in SPU image search, check if any address contains SPU image and not just aligned 128-byte addresses.
* Dump SPU images into actual files if "SPU Debug" option is enabled in config.
* Optimize SPU image search to be extremely fast.
* Search SPU images in all PS3 binary LOAD segements, not just the first.
=> SPU: Embedded PRX/overlay image patching, Implement images dumping, Image search improvements

rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/Modules/cellSpurs.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm_ptr.h, rpcs3/Emu/Memory/vm_reservation.h
This function currently doesn't have any effect on the RPCS3, but it can be helpful in theory if we are going to HLE some code such as cellSpurs. It takes a mini-transaction in it, and attempts to execute it fast with TSX. If TSX is not available, or it fails, it fallbacks to slower path.
=> Implement vm::reservation_op

rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/System.cpp, rpcs3/Loader/ELF.h, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
Press alt+s to capture SPU memory to an executable SPU ELF when selected on the debugger. It even works with Ghidra and it detects functions in it, mostly useful for dumping CellSpurs workloads because they are raw function data with no SPU image.
* Fixed direct SPU ELF loading (don't start SPU thread in this case).
* Add a bit more info to SPURS kernel explorer.
Implements https://github.com/RPCS3/rpcs3/issues/7317
=> SPU Local Storage capture

rpcs3/Emu/RSX/VK/VKPresent.cpp
VKGSRender::advance_queued_frames may have callbacks to perform memory management. Open active CB before entering that method.
Fixes https://github.com/RPCS3/rpcs3/issues/8978
=> vk: Open CB before doing frame cleanup so that callbacks work

rpcs3/Crypto/unedat.cpp, rpcs3/Crypto/utils.cpp, rpcs3/Crypto/utils.h
Replace MAX_PATH usage with enum CRYPTO_MAX_PATH, this prevents the redefine warning, and ensures that we don't mess up other usages (which will likely want MAX_PATH as 260, like Windows defines, not 4096 like we do).
The replacement has been done based on what MSVC was telling me the define values were at each point (i.e. whether we wanted it or not, these usages were using our 4906 value, not the 260 value from Windows)
=> FIX: MAX_PATH is used within Windows headers, we should use a different define internally

rpcs3/Emu/Cell/SPUThread.cpp
This originally striked me as I realized PPU accurate 128byte reservation mode does not work properly when there are two or more loads from the same address in the atomic loop. Why? because if one loads reads data X and the other reads data Y, if the reservation data there is X for example, meaning the data was changed twice by other thread (X ->Y ->X) the reservation store can even succeed in this case on rpcs3 although clearly the writes occured and the reservation store should fail in this case.
Now this pr doesnt fix, but it fixes a similar case in SPU side, where someone can use GET inside an atomic loop (essentialy reading the data twice as GETLLAR already read it) so add reservation validation checks there if this case is encountered.
Only affects Accurate SPU DMA as mentioned in …
=> SPU: Validate reservation in GET commands (Accurate DMA)

rpcs3/Emu/Cell/PPUModule.cpp
export_addr was 0x0 and caused an access violation in this case, noticed when doing cellSpurs function tests.
=> Fix ppu_execute<Func> for forced HLE functions

rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp
First followup to #9062, on PPU side.
You may need to remove PPU LLVM cache if you played X game with accurate PPU 128 reservations before. (i.e. if you have its cache)
=> PPU: Handle cache line inconsistencies (PPU 128 reservations)

3rdparty/CMakeLists.txt, 3rdparty/libusb_cmake/os.cmake, 3rdparty/libusb_static.vcxproj
May resolve some outstanding issues around libusb/hidapi (i.e. DS4 not being released on rpcs3 shutdown etc..) or may not.
Fixes three outstanding compile warnings on non-Windows OS...
Re-ordered the 3rd party CMake so libusb is in file order above hidapi (just to have document flow match logical flow)
Also took this opportunity to remove the YAML INSTALL action (by setting YAML_CPP_INSTALL to OFF)
Provided capability to use system library for libusb by providing USE_SYS_LIBUSB option to CMAKE
The pkg-config is also used for FreeBSD now to find the dynamic library
Tested under:
~~Further Testing desired:~~
~~- [ ] Other LibUSB devices~~
~~- [ ] Testing under 'other platforms' (FreeBSD?)~~
=> LibUSB: Update to upstream master (and turn off YAML_CPP_INSTALL CMake property)

rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/PPUDisAsm.h
* Display MTCR mnemonic, when crm is UINT8_MAX.
* When a single bit only is set in crm, display cr field instead of mask. such as `mfocrf r0, cr4` or `mtcrf cr4, r0`.
* STDX does not alter cr0 hence it doesn't need a dot after its name, seems like a typo from STDCX which does need it.
=> PPU Debugger: Improve move GPR from/to CR registers instructions

rpcs3/Emu/Cell/SPUThread.cpp
Do not allow to proceed after an invalid address was passed to PUTLLC, trigger page fault notification for page fault enabled memory.
Similar to how I made PPU do this.
=> SPU: Touch unmapped memory in reservation mismatch

rpcs3/Emu/RSX/VK/VKFormats.cpp
- This format is required to emulate RSX_FORMAT_CLASS_D16_FLOAT
Fixes https://github.com/RPCS3/rpcs3/issues/9057
=> vk: Add VK_FORMAT_D32_SFLOAT to format conversion table

rpcs3/Emu/CPU/CPUDisAsm.h, rpcs3/Emu/Cell/SPUDisAsm.cpp, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
* Add made-up MR mnemonic for [ORI x, y, 0] and [SHLQBYI x, y, 0] instructions. MR as in "move register" as the PowerPC mnemonic.
* Optimize debugger thread context update a bit by not iterating over all CELL threads, only the single relevant thread ID to us.
* Detect simple constant command propagation in WRCH and a few more instructoios which should work in most of the cases.
* Add SPURS workload argument in kernel-explorer.
* Cleanup SPU channels logging. (rely entirely on spu_ch_name)
* Fix bug in CPUDisAsm::SignedHex regarding INTx_MIN.
=> SPU Debugger Improvements: Add MR mnemonics, constants propagation and more

Utilities/Thread.cpp, Utilities/Thread.h, Utilities/sync.h, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/perf_meter.cpp, rpcs3/Emu/perf_meter.hpp, rpcs3/util/atomic.cpp
Relatively big change to waitable atomics.
1) Don't return prematurely if condition is not met (does not affect ones with set timeout).
2) Use one semaphore per thread. This seems to improve efficiency in some scenarious for little sacrifice.
=> Rewrite waitable atomics

rpcs3/util/atomic.cpp
Added 3rd path based on std::mutex / std::condition_variable.
It's slower than native futex or some windows syscalls, but better than nothing.
Big welcome would be adding some the most raw and native implementations for other platforms.
=> Waitable atomics for BSD and stuff

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
This PR adds block-level reservation management for RSX vs CELL. The basic design philosophy here is that when "Accurate RSX reservations" is enabled, access to memory shared between CELL and RSX is accessed in an exclusive manner. Multiple CELL threads are free to simultaneously manipulate memory as they have their own synchronization mechanisms, but RSX accesses said memory in an exclusive manner. This fixes a lot of problems where SPU/PPU has a reservation line but data is clobbered by RSX DMA operations. TSX normally fixes this issue for capable CPUs which is why some users can play affected games at good performance with no issues.
The advantage of doing it this way of course is performance, the performance hit is now much less and games that require the option to work see comparable …
=> Reimplement RSX reservation access

rpcs3/Emu/Cell/lv2/sys_vm.cpp
This reverts commit 4599d5841353fdf8096191c30a592fedc844efce.
The issue this works around was fixed in 3265772 ("idm: Implement
creation/destruction invalidation counter") by making the variables
constexpr.
Fixes #6896
=> Revert "Fix debug build gcc/clang linker."

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/VK/VKHelpers.h
- Adds nvidia driver check and logs errors for incompatible drivers.
- Fixes a problem with intel drivers caused by illegal use of doubles.
Fixes https://github.com/RPCS3/rpcs3/issues/8955
=> rsx: Driver compatibility improvements

Utilities/Thread.cpp, Utilities/VirtualMemory.h, Utilities/cond.cpp, Utilities/types.h, rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm_locking.h, rpcs3/Emu/Memory/vm_reservation.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/util/atomic.cpp, rpcs3/util/atomic.hpp
Atomic improvement aims to improve TSX performance by reducing waiting time on some heavy thread notification.
VM changes try to get rid of reservation_lock and reduce the concept of reservation bits as simple contention counter (currently they are split to "unique lock" and "shared lock counter").
In the meantime, some improvements for Non-TSX were made and significantly improved PUT performance (writes from SPU to main memory).
Please test for regressions.
=> Vm and atomic improvements

rpcs3/Emu/Cell/lv2/sys_net.cpp
The OS defaults for SO_RCVBUF / SO_SNDBUF may not match what the defaults for the PS3 are.
And the code may be happy with the PS3 defaults, so may not set this explicitly.
So we'll do it when we establish the socket.
It also looks like the Windows recv behaviour is different for the MSG_PEEK option (and possibly in all situations where a smaller buffer is provided). I believe other platforms will return the size of the data received into the socket buffer, even if the supplied user buffer is smaller. Windows returns WSAEMSGSIZE instead. For the length of '1' MSG_PEEK request that is currently seen, we just mask this and return the full size of the buffer. This might need to be the case in all situations, I assume there will be applications that will supply an artificially small buffer and …
=> NET: Add SO_RCVBUF / SO_SNDBUF defaults to .._bnet_socket

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/patch_manager_dialog.cpp, rpcs3/rpcs3qt/patch_manager_dialog.h
Adds "Configure Game Patches" option to the game list context menu.
This simply opens the patch manager with the title ID preselected as search term.
=> Qt: Add "Configure Game Patches" to game list

rpcs3/rpcs3qt/pad_settings_dialog.cpp
Enables QDialog interaction in the pad settings dialog while not currently remapping a button.
For example closing the dialog with ESC was not possible before.
=> Qt: Pass events to pad settings dialog when not remapping

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp
They weren't actually used due to the bug in code.
=> TSX: fix transaction limits

rpcs3/main.cpp
Logs something like this:
_RPCS3 v0.0.13-11151-09a9d084 Alpha | vCheck | Firmware version: 4.86
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz | 8 Threads | 31.82 GiB RAM | TSC: 1.992GHz | AVX+ | FMA3
Operating system: Windows, Major: 10, Minor: 0, Build: 19041, Service Pack: none, Compatibility mode: 0
**Qt version: Compiled against Qt 5.15.1 | Run-time uses Qt 5.15.1**_
The versions can be different, but I don't have a proper setup to test it right now.
You could probably test it by compiling it with Qt 5.14.2 and then run it with Qt 5.15.1 dlls.
=> Log Qt version

rpcs3/Emu/Cell/Modules/sceNp.cpp
This change fixes the age restrictions for online features in Skate 3. Details of discussion with @RipleyTom are here https://discordapp.com/channels/272035812277878785/738838647176036393/774519382302392322
* Set age in GetAccountAge to 18, this matches the other parental control functions in sceNpManager.
* Fix incorrect function in log message
=> Set AccountAge to 18

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm_locking.h
It is allowed to deallocate memory after a GETLLAR was executed on it! Its only a problem on rpcs3 because our theoretically "hacked" LR events checks which dereference data, although theres not much we can do about it we can however prevent such access violations in this case by checking the address's page attributes.
For now LR event is are raised for this case.
=> SPU reservations: Do not illegally dereference reservation data

Utilities/sync.h, rpcs3/util/atomic.cpp, rpcs3/util/atomic.hpp
It's like poll or WaitForMultipleObjects, although there is no way to make them inter-operable.
Both atomics should belong to the same homebrew type atomic_t.
=> Waiting on multiple atomics (waitable atomic list)

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
* In PPU, leaf functions do not need to save LR, we had a workaround for it by not reading first function call so the callstack would not be empty for it.
But this is wrong as it always skips one function call, so, for leaf functions use LR directly and place it on top of the callstack list.
* Implement SPU callstack, with the same fix from PPU.
=> Debugger: Implement SPU callstack, fix PPU callstack

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/rpcs3qt/call_stack_list.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp, rpcs3/rpcs3qt/kernel_explorer.h
* Make SPU code address checks check destination code validity (STOP 0x0 is considered invalid). replacement for PPU functionality where its checking vm::page_executable. This fixes thinking stuff like zero initilizaed LR save area is valid which is very common especially at the end of SPU stack.
* Ignore PPU HLE stop address, it has no use for us.
* Add some process information in kernel-explorer.
=> Debugger: Improve SPU/PPU callstack handling a bit

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
* Fix logic error in callstacks handling code, always set `first` to false after first iteration.
* Add explicit check for 0 return address. Current code validity checks may not check for it properly because it sits on interrupt handler entry point. (which may contain valid code)
* Do not allow 0x3FFF0 to be a back chain  address because it needs space for LR save area, only 0x3FFE0  and below satisfy this critiria.
=> Debugger fixups

rpcs3/util/vm_native.cpp
Make sure mmap returns 64K-aligned results, as on Windows.
Does not affect Windows, but RPCS3 relies on this logic so need a little workaround.
=> Hotfix for shm->map_self()

rpcs3/Emu/Memory/vm.cpp, rpcs3/main.cpp, rpcs3/util/vm.hpp, rpcs3/util/vm_native.cpp
Print a non-fatal error instead.
On linux, you can increase mem lock limit by editing your:
`/etc/security/limits.conf`
If you see errors, check `ulimit -Hl`, it's probably too small to be useful.
=> Do not crash if memory locking is impossible (hotfix).

rpcs3/Emu/Memory/vm.cpp
Ensure allocated memory contains only zeroes.
=> Fix PPU stack contents on allocation

rpcs3/Emu/CPU/CPUDisAsm.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
* If all 4 32-bit pieces of the 128-bite GPR register are equal, print in short 32-bit format and add '$' after it. (most of the time)
* For insertation masks: do not print the original value which are :think-hang:, print a comment describing it instead. 
* Executable code pointers show first instruction (full diassembly of it) they are pointing, the same technique has been applied for PPU instead of commenting "function-code" after it.
For this feature...
* Improve SPU executable code detection, make it much more reliable. (applies for callstack code as well)
**Before:**
**After:**
=> Make SPU Debugger usable by humans

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/rpcs3qt/register_editor_dialog.cpp
* Improve vector registers display.
* Similar to #9236, if all 4 32-bit pieces of SPU register are equal to each other display a single piece with '$' after it.
This also works for register modification: e.g. `1$` is the same as `0x00000001000000010000000100000001`
=> Debugger: Improve SPU/PPU vector registers further, Implement broadcasting for Registers Editor

Utilities/Thread.cpp
There was no real reason to check full d_size, checking single page should be enough.
Fixes #9245 (should)
=> [HOTFIX] Fix vm::check_addr calls in Thread.cpp

Utilities/Thread.cpp
SIGPIPE seems to happen when a socket is being written to on a stream socket and the the other side closes the socket.
At the moment this terminates the emulator.
Setting it to be ignored shouldn't affect anything as sendto will still return an error and errno will be set properly.
note:
This is a unix only signal so it doesn't need a windows impl.
=> Adds SIGPIPE to ignored exceptions(unix)

Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/util/asm.hpp, rpcs3/util/atomic.cpp, rpcs3/util/atomic.hpp
Fixed some bugs in thread pool as well.
=> New atomic fixups

rpcs3/Emu/Cell/SPUDisAsm.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_frame.h, rpcs3/rpcs3qt/register_editor_dialog.cpp, rpcs3/rpcs3qt/register_editor_dialog.h
* New SPU floating point view of registers, by default it resides after the hexadecimal view. This is real SPU float format and not the x86 float! values such as infinities or NaNs do not exist for it andthere bit representatios in x86 will be presented as huge-ass numbers in SPU debugger. Same as for x86 denormals, its bit pattern is displayed as zero.
e.g.
https://user-images.githubusercontent.com/18193363/99120407-7aaf5380-2603-11eb-92fb-78958412d997.PNG
* Adds a new "floats only mode" after pressing F, it switches to clean view of registers state in floats only format. This required a few  bugfixes to work properly... (described below) https://user-images.githubusercontent.com/18193363/99120376-7125eb80-2603-11eb-87d8-309555b627ef.png
* Fixed debugger shortucts, no longer needs to …
=> SPU Debugger: Implement float registers view + General debugger fixes

Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h
Some description you can see in commits.
Memory locking in this context means certain pages will not be swapped and stay in memory. It does not increase memory consumption, because the same physical memory will be allocated nevertheless. However, it makes "touching" memory for TSX unnecessary because TSX transactions cannot work if certain memory pages are not initializes.
=> Memory locking refactoring

rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache_helpers.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLPresent.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKPresent.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/rsx_utils.h
This PR changes how resolutions scaling works by forcing all upscaling to generate square pixels. The longest dimension is used to decide whether the whole surface shall be upscaled. This fixes some games incompatible with resolution upscaling but also fixes rectangular pixels (see https://github.com/RPCS3/rpcs3/issues/8931)
Upscaling in both axes should also improve output quality in games that require a large upscaling threshold value.
Fixes https://github.com/RPCS3/rpcs3/issues/8931
=> rsx: Resolution scaling overhaul

Utilities/types.h, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/CPU/CPUThread.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/perf_meter.cpp, rpcs3/Emu/perf_meter.hpp
I also sneak other minor changes to check various compilers.
Major change is suspend_all interface, max amount is reduced to 64 since threads are now dynamically added and removed, but I don't expect any perf change (maybe slight regression).
=> Fix perf_meter after thread pool

rpcs3/Emu/Cell/SPUThread.cpp
Helps to indentify unimplemented STOP codes as opposed to invalid instructions.
=> SPU: Log STOP full opcode

.ci/deploy-linux.sh, .ci/github-upload.sh, azure-pipelines.yml
Since Travis CI's new free plan is not sustainable, we're switching entirely to Azure for our Linux builds, which means we need to upload via Azure, instead of via Travis.
Example of uploaded build available here: https://github.com/hcorion/rpcs3-linux-builds/releases/tag/build-89512b1ede27c4e55fb763c0dfd340fb3e8cbe5d
In addition, the body of the GitHub release now no longer has the filename at the end of the hash.
=> Pushing master AppImage Artifacts to GitHub Releases via Azure

README.md, Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/util/atomic.hpp
Make sure thread handles are collected and TLS destructors are executed as well.
=> Clean thread pool at exit

Utilities/Thread.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm_locking.h, rpcs3/util/atomic.cpp
Restore "memory lock" limit to <512MiB.
I originally planned to split huge allocation in chunks, but it can be done later.
This should fix some regressions.
=> vm adjustments

rpcs3/Emu/RSX/GL/GLPresent.cpp, rpcs3/rpcs3qt/gl_gs_frame.cpp
- Disable depth test before rendering to the default framebuffer
- Remove the depth buffer from the default framebuffer as we do not need it and its a waste of VRAM.
Fixes https://github.com/RPCS3/rpcs3/issues/9185
=> gl: Minor fixes

rpcs3/Emu/System.cpp, rpcs3/rpcs3qt/gs_frame.cpp
- Don't quit in Emu.Stop if force boot was set.
- Don't stop the emulator in gs_frame::close when it was already stopped. This would remove the force boot flag by mistake
Fixes a regression from #8550.
Should Fix #8719
=> Fix auto exit

Utilities/BEType.h, Utilities/File.h, Utilities/StrFmt.h, Utilities/types.h, rpcs3/Crypto/unedat.cpp, rpcs3/stdafx.cpp, rpcs3/stdafx.h, rpcs3/util/atomic.hpp, rpcs3/util/endian.hpp, rpcs3/util/logs.hpp, rpcs3/util/shared_ptr.hpp
Try to fix and guard against future issues with precompiled headers with certain files.
=> stdafx.h: remove BOM from custom included headers

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
- Depth func of always or never usually disqualifies depth testing. Invalidate contested surfaces when depth func is changed.
Fixes https://github.com/RPCS3/rpcs3/issues/8668
Fixes https://github.com/RPCS3/rpcs3/issues/8619
Fixes https://github.com/RPCS3/rpcs3/issues/8740
=> rsx: Fix uncaught depth-func changes

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_helpers.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_utils.h
Adds the following fixes for derived sub-surfaces (e.g data cast from 2D to 3D or 2D to cubemap):
- Base the upscaling on the real source and not the "attr" parameter.
- In case of reconstruction, the source is much larger than the subslice in "attr"
These fixes improve upscaling compatibility without requiring large threshold values which can break visuals in some other ways. This is a companion PR to https://github.com/RPCS3/rpcs3/pull/9281. The combined results have upscaled bits that closely match what the layout at default resolution is. This will not fix all upscaling issues, you still cannot (and never will be able to) upscale the individual bytes comprising a floating point value separately.
Fixes https://github.com/RPCS3/rpcs3/issues/9318
=> rsx: Improve upscaling compatibility

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/CPU/CPUThread.h, rpcs3/Emu/Cell/PPUOpcodes.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUOpcodes.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_frame.h, rpcs3/rpcs3qt/debugger_list.cpp, rpcs3/rpcs3qt/debugger_list.h
* Fix+optimize+rewrite debugger GetPc() function to be able to use to use raw ptr and instead of locking weak ptr, unknown PC returns UINT32_MAX instead of 0, decleration moved to cpu_thread class and removed duplicates.
* Code flow tracker has been implemented, pressing N proceeds to "next instruction" on thread's instruction according to code flow.
The specificdation for it is as follows: 
1 - Unconditional branches with known branch target proceed to branch target, conditional branches always the branch target even if the condition would not be met in realtime execution.
2 - Indirect branches (unknown targets) do not proceed to any instruction and pressing N does nothing for them.
3 - Other instructions such as NOP proceed to pc + 4.
Useful to detect loops, go to to a branch target …
=>  Debugger: Implement code flow tracking

rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/GL/GLDraw.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKDraw.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_methods.cpp
This enables two optimizations I have wanted to finish for a long time:
- Allows for conservative texture uploads
- Allows to update a program object without running full ucode analysis for no reason
The changes result in a modest performance uplift in games that are fully RSX limited (99% RSX load) of upto ~5% from tested configurations.
=> rsx: Separate program environment state from program ucode state

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/Loader/ELF.cpp, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/settings_dialog.cpp
HLE missing SPRX files, if no firmware is installed a pure HLE mode is activated.
More stuff:
* Fix manual list loading bugs. (mentioned in https://github.com/RPCS3/rpcs3/issues/6442#issuecomment-717320978 )
* Fix HLE gcm.
* Bugfix to use system fonts instead of depending on firmware fonts.
* Fix HLE sprx path detection. (multip-delim paths or paths with "."/".." such as "/dev_flash//sys/../sys/external////libvdec.sprx" didn't work)
* Another bugfix for HLE detection for non-existing SPRX paths which start with "/dev_flash/sys/external/" such as "/dev_flash/sys/external/not_real_dir/libvdec.sprx", return ENOENT for them instead of doing HLE + CELL_OK. (liblv2list/manual modes)
* Hardcode GUI sprx selection list to allow/fix LLE/HLE setting manipulation regardless of current firmware …
=> Allow emulation to work without firmware

rpcs3/util/atomic.hpp
=> atomic.hpp: fixup (rsp addressing)

rpcs3/Emu/RSX/VK/VKRenderPass.cpp
Adds a missing switch case from depth-float integration.
Fixes https://github.com/RPCS3/rpcs3/issues/9359
=> vk: Properly register D32_SFLOAT as a depth-stencil format

rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKRenderPass.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Adds missing D32_SFLOAT in more places.
- Crash if renderer requests an image size not supported in hardware.
Fixes https://github.com/RPCS3/rpcs3/issues/9349
Fixes https://github.com/RPCS3/rpcs3/issues/9359
=> vk: Minor improvements

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_types.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/GL/GLDraw.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLShaderInterpreter.cpp, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKDraw.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/System.cpp
- Move shader prefetch+analysis code execution point to draw call end.
- Avoid including complex template headers if not needed.
Fixes https://github.com/RPCS3/rpcs3/issues/9393
=> rsx: Minor restructuring

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/system_config.h, rpcs3/Emu/system_config_types.cpp, rpcs3/Emu/system_config_types.h, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/emu_settings_type.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/tooltips.h
* Remove all lib loading types. E.g. "liblv2.sprx only" etc, replace their usage with two lists. Empty lists is default fw loading behaviour.
Selecting an SPRX file via HLE-default list will LLE it, selecting an SPRX file via HLE-default list will LLE it.
As a nice side effect makes HLEing of libs simpler than ever by selecting them in list such as SPURS or GCM. (if they are LLEd by default).
Previously you had to use manual list type and randomly select LLE-by-defaults libs until the game works, only then unselect the lib you want to HLE.
* Minor libsysmodule.sprx loading fix.
* Fixed LLVM compilation of firmware. (simply didn't compile after installation)
* Handle invalid settings in EnhanceRadioButton (GUI button groups), select default setting button instead of selecting nothing.
* …
=> Firmware libraries settings overhaul

rpcs3/Emu/Cell/PPUAnalyser.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/System.cpp
It used to crash on referencing "non-existing" segment index because we did not push all LOAD segments as it expects.
Remove its hack from firmware installation as well.
More stuff:
* Fix IDM IDs leak in firmware installation.
* Add some asserts for cases where relocation offset in segment is out of range, also works on "empty" LOAD segments.
=> PRX loader: Fix libfs_155.sprx loading

rpcs3/Emu/Cell/Modules/StaticHLE.cpp, rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp, rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/PPUFunction.h, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp
* Make PPU UNK instruction interpreter handler check if its sitting on an HLE function and execute it instead if so. Simplifying cross-decoders interpreter functions such as `ppu_reservation_fallback`, not needing to check if its HLE expliclitly.
* RTOC of all HLE function entries is 0, which is an UNK instruction, also a null address too ensure TOC data is not referenced externally. (access violation in such case)
* Add ppu_function_manager::func_addr which is a strict way to obtain HLE function entry address.
=> PPU: Allow HLE execution from pure instruction decoder type interpreter

rpcs3/Emu/RSX/VK/VKHelpers.cpp
Somehow nobody noticed that ampere cards were not registered correctly. Only GA100 was added to the quirks table.
=> vk: Register ampere GPU PCI IDs

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/input_dialog.cpp, rpcs3/rpcs3qt/input_dialog.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/qt_utils.h
* Allow to decrypt binaries even if a game is running in the background, do not stop it. Also take advantage of when a game is running and try to extract another KLIC from it.
* If decryption failed due to missing key licence (KLIC), pop a dialog to enter it manually. It's 32 characters long in hex and is logged with the games it's being used in sceNpDrmIsAvailable and few other sceNpDrm functions. Try to decrypt one more time with specified KLIC.
=> GUI: Improve PS3 decryption tool

rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/memory_viewer_panel.h
* Press M while the debugger is running to launch the memory viewer from it. When the memoy viewer is being launched from the debugger a magical thing happens: it passes to it the address of current instruction selected on the debugger. (or the current PC if none was selected)
It also works with SPUs and the debugger calculates the address of the LS shadow copy in vm and adds it to the address before then passing it to the memory viewer.
=> Link the memory viewer with the debugger

rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/memory_viewer_panel.h
* Group bytes in 4-byte groups. (words)
* Add SPU local storage start headers.
* Address is always aligned to the amount of bytes in a row.
* Make memory viewer address accept "0x" and "0X" prefixes, max length has been extended to 10 characters but because of the added hexadecimal regexp validator without the prefix it will allow only 8 hex characters.
=> GUI: Polish the memory viewer

rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/memory_viewer_panel.h
- Fixes image viewer, especially RGB crash.
- Fixes emu freeze when you resize the memory viewer in some unlucky way.
- Fixes memory viewer layout and resize. Making the dialog smaller is not trivial and is gonna need some patience though. I hope that's fine.
=> More memory viewer improvements

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/headless_application.cpp, rpcs3/rpcs3qt/gui_application.cpp
This should harden our exit process, while also fixing g_fxo deinitialization in no-gui mode.
=> Emu: implement on_exit callback

rpcs3/Emu/RSX/VK/VKDraw.cpp, rpcs3/Emu/RSX/VK/VKRenderPass.cpp, rpcs3/Emu/RSX/VK/VKRenderPass.h
Partially reverts https://github.com/RPCS3/rpcs3/commit/0a865bd9dcad8a6cf2bdb2a867e2cf23baef58ea
Technical information
Validation layers validate a bound pipeline against the active renderpass. The old render pipeline would bind a new pipeline, then end the active renderpass (if mismatched) and start a new one (the correct one) which could trigger errors and undefined driver behavior. The new approach cleanly stops the active renderpass if it is mismatched and binds the draw call requirements outside any renderpass which solves the spec violation.
Fixes https://github.com/RPCS3/rpcs3/issues/9456
Fixes https://github.com/RPCS3/rpcs3/issues/9457
=> vk: Fixup for renderpass issues

rpcs3/Emu/CPU/CPUDisAsm.h, rpcs3/Emu/Cell/PPCDisAsm.h, rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/PPUDisAsm.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUDisAsm.cpp, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/System.cpp, rpcs3/rpcs3qt/breakpoint_list.cpp, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_frame.h, rpcs3/rpcs3qt/debugger_list.cpp, rpcs3/rpcs3qt/debugger_list.h
* Remove m_current_choice for change of thread detection (replace with std::weak_ptr::owner_before()). It's not correct to rely on thread name entry. In extreme corner cases a newly thread can be created, old destroyed with the same entry name. (reoccuring LV2 SPU/PPU ID)
* Remove m_no_thread_selected, can be easily replaced with std::weak_pt::expired() function and is more accurate this way.
* In HandleBreakpointRequest: only remove breakpoint on valid PPU thread and not any thread! also fix potential nullptr deref if thread has recently been destroyed.
* PPU memory must be exec memory when using debugger's "Next Instruction" feature.
* Read instruction data once in disassmblers: Memory is volatile and may be changed by guest threads, ensure the decoded instruction matches with the data. …
=> Debugger fixes

.github/PR-BUILD.md, .github/PULL_REQUEST_TEMPLATE/1-default.md
I noticed many people are struggling to find a PR build, so I decided to implement a small instruction.
=> Add PR-BUILD.md and Pull Request Template

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/rsx_debugger.cpp
* Add the same fixes as memory viewer for rsx debugger and main debugger as #9453. Modified regexp validator to allow endless amount of leftmost zeroes. (until max length is reached)
* Extent max length to 18 to allow 64-bit hexadecimal (16) with hex prefix (2).
* Remove address preview in the main debugger's Goto address dialog.
* Limit SPU address on the main debugger to 0xfffff and less in regexp validator. (stuff like 0x0000000000fffff still works but 0x100000 is not allowed to type)
* memory viewer: Only allow "words" steps in powers of 2.
* Default to current PC/address instead of 0 address on failure to evaluate text in lineedit. (such as empty text or "0x" prefix alone)
* Print SPU reservation data in the debugger.
=> GUI: Rewrite GOTO address tools in debugger tools

rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/stdafx.h, rpcs3/util/auto_typemap.hpp, rpcs3/util/typeindices.hpp
Resembles g_fxo, but intended for use within other classes.
May resemble pimpl pattern, but doesn't leak any implementation details in headers.
Object are created in default constructor automatically.
Has some minor pointer dereference overhead.
=> Implement util/auto_typemap.hpp

CMakeLists.txt
They are currently disabled on all CIs and bring no discernible improvements to compilation time in our case(if the project compiles at all with them enabled, which it currently doesn't).
=> Disables precompiled headers by default

rpcs3/Emu/System.cpp, rpcs3/util/fixed_typemap.hpp
This reverts 'rpcs3/stdafx.h' in commit 567d23d856473297541ea189f67cafa0d5b1b3eb.
Issue : 
```
[ 82%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/PPUTranslator.cpp.o
cc1plus: warning: /home/marin_baron/build/rpcs3/gcc/debug/rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx.gch: not used because `__GXX_RTTI' not defined [-Winvalid-pch]
[ 82%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/RawSPUThread.cpp.o
[ 82%] Building CXX object rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/Cell/SPUAnalyser.cpp.o
In file included from /mnt/z97-a/mnt/crucial_p1/Git/rpcs3/rpcs3/stdafx.h:11,
from /home/marin_baron/build/rpcs3/gcc/debug/rpcs3/Emu/CMakeFiles/rpcs3_emu.dir/cmake_pch.hxx:5,
from <command-line>:
/mnt/z97-a/mnt/crucial_p1/Git/rpcs3/rpcs3/util/fixed_typemap.hpp: In static …
```
=> Revert partially "Implement util/auto_typemap.hpp"

rpcs3/Emu/Io/Skylander.cpp, rpcs3/Emu/Io/Skylander.h, rpcs3/rpcs3qt/skylander_dialog.cpp, rpcs3/rpcs3qt/skylander_dialog.h
Adds support for queries in Skylanders Spyro's Adventure.
Adds support for up to 4 Skylanders at the same time(this can theoretically be pushed to 8 but I don't think any game takes advantage of it).
Improves accuracy of status commands.
Improves overall UI(cleaner main interface, automatic file naming, combobox with search included).
Closes https://github.com/RPCS3/rpcs3/issues/8144 and https://github.com/RPCS3/rpcs3/issues/7101 .
=> Improves skylander portal emulator

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/RSXThread.cpp
- Return null if surface does not exist instead of throwing.
- Revert an inadvertent deletion for supported Z formats which broke shadowmaps.
Fixes https://github.com/RPCS3/rpcs3/issues/9509
Fixes https://github.com/RPCS3/rpcs3/issues/9474
=> rsx: Fix some silly regressions

Utilities/Thread.cpp, rpcs3/cmake_modules/ConfigureCompiler.cmake, rpcs3/util/shared_ptr.hpp
The return-type warning was spammed everywhere, and was caused by custom exception thing. Best to just disable.
Marking noreturn seems to have left some warnings in, but i cant track them down in compiler explorer (I'm probably just blind).
@Nekotekina The other thing I would really like to get in here is a new indexer for v128 bit vectors, since you marked the old one deprecated. Whenever rpcs3 is updated it nukes my whole terminal because of the warnings. Do you have a plan for replacing it, or perhaps some instructions for someone else to be able to change it?
=> Warnings: Micro fixes

rpcs3/Emu/Cell/SPURecompiler.cpp
Fixes bad codegen on the icelake path. I'm pretty sure there's a better solution but debugging this without hardware that can actually run these instructions is way too sadistic.
I'll revisit this later once I get a tigerlake laptop.
Fixes: https://github.com/RPCS3/rpcs3/issues/9254
=> SPU LLVM: Fix edgecase in icelake codegen

3rdparty/qt5.cmake, BUILDING.md
Seems this got missed when updating the build guide and whatnot. This actually threw me off as I tried to build in WSL (Ubuntu 20.04), and I got some Qt errors, because I didn't realize the packaged version was too old (it didn't use to be :p).
So this should help people be aware of when they need the PPA better.
=> Build: Update required clang/Qt version

rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/memory_viewer_panel.h
* 0..SPU_LS_MAX_ADDRESS addressing with wraparound as the main debugger. (instead of the ugly 0xe8000000 sfuff)
* Title of viewer window contains SPU name.
* Memory of the SPU is valid and is saved even after the SPU thread has been destroyed.
* Press M while selecting an SPU thread to pop up the "SPU" type memory viewer.
* SPU regexp validator as the main debugger has been used for address typing.
* Typing an address didn't work well.
* Address was not always aligned in cases when changing Words count.
https://user-images.githubusercontent.com/18193363/103304516-80c18e00-4a11-11eb-9056-c364dd64111b.png
=> memory viewer: Implement SPU mode, fix address GOTO

rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Memory/vm_reservation.h
Can help to reduce lambda depth hell a little.
=> vm: implement vm::atomic_op, fetch_op helpers

rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/util/fifo_mutex.hpp, rpcs3/util/slow_mutex.hpp
Not used anywhere. Prototype.
Occupies 2 bytes and supports up to 256 threads. Tries to maintain acquisition order.
=> Implement fifo_mutex

Utilities/File.h, rpcs3/Emu/RSX/rsx_cache.h
* Fixed crash whenever files are missing from the cache.
* Fixed crash whenever files are empty.
* Fixed crash whenever file creation/overwrite of cache files failed. (handled by fs::write_file)
* Fixed crash whenever there are any subdirectories inside the pipelines cache directories. (didnt check whether filesystem entry is a file or directory, treated directories as files)
* Fixed shader cache of 2 or less pipelines.
* Add some optimizations in compiling shaders. (move constructors, remove redundant copies of buffers, copy elision etc) 
* Overwrite invalid shader cache files if encountered such, restoring proper cache state and allowing the cache to be usable again.
* Make FP shader data loading lock-free.
Fixes #9529
=> rsx: Shaders cache fixes and optimizations

BUILDING.md
The package `qt5-devel` isn't available, but the `qt5-qtbase-devel` package is :smile: 
Before:
```
[root@workstation ~]# dnf install alsa-lib-devel cmake glew glew-devel libatomic libevdev-devel libudev-devel openal-devel qt5-devel qt5-qtbase-private-devel vulkan-devel
Last metadata expiration check: 0:06:39 ago on Mon 04 Jan 2021 08:00:59 PM CST.
Package alsa-lib-devel-1.2.4-5.fc33.x86_64 is already installed.
Package cmake-3.18.4-2.fc33.x86_64 is already installed.
Package glew-2.1.0-8.fc33.x86_64 is already installed.
Package libatomic-10.2.1-9.fc33.i686 is already installed.
Package libatomic-10.2.1-9.fc33.x86_64 is already installed.
Package systemd-devel-246.7-2.fc33.x86_64 is already installed.
No match for argument: qt5-devel
Package vulkan-loader-devel-1.2.148.1-1.fc33.x86_64 is …
```
=> Docs: Update BUILDING.md (Fedora)

rpcs3/Emu/VFS.cpp
Directories and files' name is not allowed to end with a space or a period on Windows.
=> VFS: Escape path components which end with space or period

rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/custom_table_widget_item.cpp, rpcs3/rpcs3qt/custom_table_widget_item.h, rpcs3/rpcs3qt/game_list.h
- Fixes some ugly Qt deprecation warnings by adding ugly code that supposedly is the proper way to do it.
- Removes avcodec_register_all which apparently is not needed anymore in newer ffmpeg versions (probably needs some testing).
=> deprecated

Utilities/StrFmt.cpp, Utilities/StrUtil.h, rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp, rpcs3/Emu/Cell/Modules/cellMic.cpp
* string_view, string_view, string view! (replacing std::string)
* Use c++ functions instead of c functions.
* Make it super fast.
=> Utils: Rewrite fmt::split

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/RSX/CgBinaryFragmentProgram.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk_panel.cpp, rpcs3/Emu/RSX/Overlays/overlay_osk_panel.h, rpcs3/Input/evdev_joystick_handler.cpp, rpcs3/rpcs3qt/osk_dialog_frame.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h
- Rename "Enter" button in OSK to "Return" to minimize confusion.
- Simplify Qt OSK dialog a bit.
- Apply some coding style changes that I came across while debugging.
- Use std::none_of and std::any_of instead of std::find_if (just playing around with new stuff I didn't know before)
- use sv in swizzle comparison (maybe this was intentional and i should remove it ?)
=> Random stuff

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
* Implement handler abortion during context registeration.
* Fixed recursive calls to sceNpTrophy functions by callback from registering context.
* Turns out the reader lock for context registeration was incorrect because ctxt->tropusr and trophy directory are being modified. made it an exclusive lock after callback.
Fixes #9415
=> sceNpTrophy: Fix sceNpTrophyRegisterContext for handler abortion

rpcs3/util/vm.hpp, rpcs3/util/vm_native.cpp
The cost of an atomic op is much lower compared to map(), may as well make this function thread-safe.
=> utils::shm: Make map_self() atomic

rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/memory_viewer_panel.h, rpcs3/util/vm_native.cpp
* Close all memory viewer instances after emulation exit.
* Hotfix for utils::shm::map_self after #9578
=> [+HOTFIX!] memory viewer: Close all instances after emulation exit

rpcs3/Input/keyboard_pad_handler.cpp
This is experimental and should smoothen the existing naive square shaped mouse deadzone into an ellipsis.
Maybe this will work better, maybe it will work worse.
How to test:
1. Configure keyboard as pad and assign mouse movement to a stick
2. Find a game that requires mouse deadzones (I might rename it to mouse boost)
3. Play around with the mouse deadzone settings until the game responds to the slightest mouse movements (there are some hotkeys you can use ingame and then look at the log to find the current value. See the description in the pad settings dialog when hovering over mouse deadzone or mouse acceleration)
4. Reconfigure the pad settings with the newfound values
5. Compare the experience in this PR to Master
=> Improve "mouse deadzones"

rpcs3/rpcs3qt/downloader.cpp, rpcs3/rpcs3qt/downloader.h
The QThread lived longer than the m_curl object.
This led to a crash when closing RPCS3 while the download is still in progress.
=> Qt/curl: fix segfault in curl

rpcs3/util/vm_native.cpp
It was leaving holes in reserved areas.
Windows is unaffected.
=> Memory: fix critical bug in shm::unmap_critical (Linux)

rpcs3/Emu/Cell/Modules/sys_io_.cpp, rpcs3/Emu/Cell/Modules/sys_ppu_thread_.cpp, rpcs3/Emu/Cell/Modules/sys_spu_.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/Memory/vm_var.h
This function promotes "silent" failures of deallocation without error checking by the caller, which is a bad practice.
* Add shm arg for falloc and dealloc functions, both for different reasons: 
dealloc: It may be important sometimes to check if shm matches with the targeted memory to be deallocated, aborting deallocation if not.
falloc: Allow to allocate shm at specific address with this function.
* Do not throw if vm::falloc, vm::dealloc and vm::alloc were called with invalid address but with vm::any location or lower than vm::memory_location_max, this is important for proper error checking by the caller.
=> vm: Remove vm::dealloc_verbose_nothrow

rpcs3/Emu/Memory/vm.cpp, rpcs3/util/vm_native.cpp
Also refactor other madvise() usage.
gcore from working game is now "only" ~15 G uncompressed (~282 M in zip).
Probably there is a room for further optimization.
=> Memory: use MADV_DONTDUMP if available (Linux)

Utilities/JIT.cpp
Embed name into the trampoline for easier debugging.
Only warn about null function during the compilation phase.
=> LLVM: generate trampolines for "null" functions

rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/util/vm_native.cpp
Removes redundant repetitive arguments for zshuffle in some cases.
=> SPU LLVM: add splat_scalar helper

rpcs3/Emu/Cell/SPURecompiler.cpp
FSM following a comparison instruction can be optimized to a single shuffle. In Wipeout HD we can hit this optimization 394/410 times. 
<details>
<summary>Codegen before optimization</summary>
</details>
<details>
<summary>Codegen after optimization</summary>
</details>
=> SPU LLVM: Optimize FSM following comparison

CMakeLists.txt, Utilities/StrFmt.h, rpcs3/Emu/RSX/Common/texture_cache.h
Add _DEBUG in debug mode for consistency (only MSVC does this normally).
This also has an effect on enabling AUDIT macro in Debug mode on other compilers.
=> Fix _DEBUG macro in debug mode

Utilities/File.cpp, Utilities/StrFmt.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/system_config_types.h
Remove explicit destructor for MSVC.
~~Check `__OPTIMIZE__` for other compilers.~~
Second commit may address linkage errors which are currently not supposed to happen.
=> Fix fmt::throw_exception destructor v2

rpcs3/rpcs3qt/downloader.cpp
I accidentally broke the download progress bar in the last related PR.
I should've put more trust in the sanity of the younger version of myself.
This should fix it.
=> Qt: hotfix for downloader

Utilities/Thread.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
* Allow to hold smart pointers of SPU and PPU outside of IDM, need not worrying about delaying the destructors.
* PPU exit syscall delayed stack memory deallocation to the destructor of PPU, causing stack to not be released for some time or not at all with detached PPU thread.
* Fix race-condition in SPU LS mapping and unmapping.
=> Remove SPU and PPU destructors

rpcs3/rpcs3qt/debugger_frame.cpp
=> debugger: Implement F1 helper

rpcs3/Emu/RSX/GSRender.cpp, rpcs3/Emu/RSX/GSRender.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
Removes that initial white screen on boot of every game, even for "Nothing" games or testcases which init rsx but with no frames rendered.
Some games take between half-second to few seconds until this screen changes, when there are no shaders to compile at boot.
It only causes confusion in showing this "frame" for frames the game actually rendered.
* Fixed off-by-one bug in FPS counter of first frame, this fixes stuff like Loadable games clearly displayed a single frame but fps counter is 0.00
* Improve GS frame exit workaround.
=> rsx/gui: Delay game window pop-up until first frame

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/VK/VKDMA.cpp, rpcs3/Emu/RSX/VK/VKDMA.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.cpp, rpcs3/Emu/RSX/VK/vkutils/barriers.cpp, rpcs3/Emu/RSX/VK/vkutils/barriers.h, rpcs3/Emu/RSX/VK/vkutils/buffer_object.cpp, rpcs3/Emu/RSX/VK/vkutils/buffer_object.h, rpcs3/Emu/RSX/VK/vkutils/device.cpp, rpcs3/Emu/RSX/VK/vkutils/device.h, rpcs3/Emu/RSX/VK/vkutils/instance.hpp, rpcs3/Emu/RSX/VK/vkutils/memory.cpp, rpcs3/Emu/RSX/VK/vkutils/memory.h, rpcs3/Emu/RSX/VK/vkutils/sync.cpp, rpcs3/Emu/RSX/VK/vkutils/sync.h, rpcs3/util/vm_native.cpp
This PR allows the GPU to read and write directly into host allocated memory which can give some performance improvements in some cases. It also includes misc fixes in other areas to tighten up the supporting implementation.
Summary
- Redirects all texture upload routines to use the pre-existing DMA emulation mechanism
- Solves a RAW hazard when extending/merging DMA sections by just discarding contents altogether
- Allows special DMA block that is passthrough to the physical GPU
- Fixes a synchronization leak in custom AMD GPU event object
- Adds a hotpath for utils::memory_protect that I found when profiling. There is a decent performance uplift from just assuming the whole range is likely contiguous and falling back to chunked protection in case of failure.
TODO
=> vk: Enable use of a passthrough DMA layer if supported

rpcs3/Emu/Cell/SPURecompiler.cpp
Priority is being lowered on initialization but not restored to 0 after initial cache is built.
=> spu: Restore workers priority after initialization

Utilities/Thread.cpp
Reset priority to 0 when thread goes to the thread pool.
=> Thread pool: reset priority

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/System.cpp
In the old times, we had fixed memory area to store all the executable code and it was so trivially implemented that deallocating something from it was nearly impossible.
Now it's different, but proper deallocation is still a missing piece. Can probably help some games which use a huge amount of sprx modules.
=> PPU LLVM: implement ppu_finalize

Utilities/Thread.cpp
Segfaults on emulation threads will not terminate RPCS3 anymore.
=> Unfatal Segfaults

rpcs3/main.cpp, rpcs3/rpcs3qt/main_window.cpp
- Adds log message for failed cache compilation.
- Adds log message for failed cli boot
- Closes RPCS3 on boot failure when using headless or no-gui mode.
=> Handle missing cases of Emu.BootGame failure

Utilities/Thread.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/RSX/GL/GLPipelineCompiler.cpp, rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/System.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/util/sysinfo.cpp
If the implementation does not implement/support this function, for whatever reason, it can return 0.
=> Fix minor issue with usage of STL thread::hardware_concurrency()

rpcs3/Emu/Cell/PPUThread.cpp
=> Fixup for preloading SPRX from MSELF

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/System.cpp
* Precompile LLVM cache at startup of games, like the GUI "Create PPU Cache" option.
* Implement Metal Gear Solid's 4 overlays executable precompilation support. (.SELF files)
* Precompile firmware cache at startup when missing. (e.g. if changed a setting affecting PPU LLVM cache version, such as "Accurate LLVM DFMA"). 
* Allow to abort precompilation midway fast.
Fixes #9669 
Fixes #8991
=> PPU LLVM: Precompile all executable (PRX, MSELF, overlay) code at startup

rpcs3/Emu/system_config.h
What's `auto` frame limit means again you ask? it synchronizes with vblank rate value to be equal to it. Previous default was no frame limit.
=> rsx: Set frame limit to auto by default

rpcs3/Emu/Cell/Modules/cellMsgDialog.h, rpcs3/Emu/System.cpp, rpcs3/rpcs3qt/msg_dialog_frame.cpp, rpcs3/rpcs3qt/msg_dialog_frame.h
We could only increase the value because we completely based the dialog on cellMsgDialog.
This led to an issue where the dialog would increase its maximum and thus decrease the current percentage.
It then couldn't decrease and was stuck on the old percentage.
=> Fix ppu compilation progress dialog

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h
Naive approach.
- Search for more game data directories for PPU compilation
- Also properly remove duplicate paths.
- Set thread priority to low for GUI updates.
TODO:
=> PPU Compilation: Search for more game data directories.

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/System.cpp
- Simplify compile threads
- Minor optimization for check_only ppu_initialize
- Fix stop exit of check_only ppu_initialize
- Prevent minor race in Progress Dialog Server
=> Fix sum bux

rpcs3/Emu/System.cpp
Good example is MGS4's precompilation: most of the time it would stay on 90%+ when in reality it has much more time to compile.
=>  Fix ppu progress dialog percentage

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/System.cpp
* Allow to load OVL alone.
* Add error checks in ppu_load_exec(), do not crash on error. I encountered such crash when loading an overlay module.
* Fix crash on exit from standalone PRX mode, allow kernel explorer to work with it as well for the added OVL mode.
=> Implement OVL (overlay) loading mode

rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog.cpp, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog.h, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp, rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.h, rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp, rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/System.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h, rpcs3/rpcs3qt/gui_application.cpp
- Updates the native shader loading dialog at a much smoother 60fps instead of the jittery 10fps we currently have.
The smoother update feels much faster and the additional load should be neglectible, especially with multithreading.
- Implements and uses set_value for the native progress dialogs, following my earlier change to the Qt message dialog.
This will come in handy later on and also simplifies some existing code.
=> 60fps shader loading dialog

rpcs3/Emu/RSX/VK/vkutils/device.cpp, rpcs3/Emu/RSX/VK/vkutils/shared.cpp, rpcs3/Emu/RSX/VK/vkutils/shared.h
The message might not be the only reason, but at least it might help someone like me, who had no idea what he was looking at.
=> More informative Error message on Vulkan driver crash

rpcs3/rpcs3qt/debugger_frame.cpp
This allows an option to pause all threads except for one or few, this may come handy in cases where concurrency is not wanted while debugging such as when we want to debug an atomic loop which must not be interfered by other threads in order to succeed.
* When stepping over - first set the breakpoint, then remove pause flags.
=> Debugger: Allow to unpause a thread which has been paused by global pause

Utilities/JIT.cpp, rpcs3/Emu/Cell/Modules/cellAudio.cpp, rpcs3/Emu/Cell/PPUAnalyser.cpp, rpcs3/Emu/Cell/PPUAnalyser.h, rpcs3/Emu/Cell/PPUFunction.cpp, rpcs3/Emu/Cell/PPUFunction.h, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/PPUTranslator.h, rpcs3/Emu/system_config.h
1) Added additional analyser layer which could possibly inflate cache size, but it didn't happen. Please report if you get unusually big executable cache with v4-kusa.
2) Added nounwind attribute to compiled function. It reduced their size significantly.
3) Compiled certain rare functions with "no branch tables" on per-instruction basis.
4) Optimized small blocks with 1-3 instructions, without a terminator: removed state checks for them.
5) Fixed some minor bugs and implemented rare instruction (ADD with overflow check).
6) Removed some silly global variables. Now compiled functions receive 7 parameters, such as mem ptr and some PPU regs.
7) Used GHC calling convention: it allows to pass a lot of arguments and saves no registers.
8) Implemented ppu_escape as very fast equivalent to …
=> PPU LLVM upgrade (v4-kusa)

Utilities/lockless.h, rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
Freezes could accidentally occur on close.
Deprecate range-for loop on lf_queue.
This is a part of PR #9208
Co-authored-by: Eladash <elad3356p@gmail.com>
=> Fix freezes in HLE Vdec and SPU LLVM precompilation.

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/PPUAnalyser.cpp, rpcs3/Emu/Cell/PPUAnalyser.h, rpcs3/Emu/Cell/PPUModule.cpp
1) Workaround for possible freezes on TSX path
2) Significantly reduced PPU LLVM compilation unit weight by using information from sections if available.
=> Fixup for LLVM constraints

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_frame.h, rpcs3/rpcs3qt/instruction_editor_dialog.cpp, rpcs3/rpcs3qt/instruction_editor_dialog.h, rpcs3/rpcs3qt/kernel_explorer.cpp, rpcs3/rpcs3qt/kernel_explorer.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/memory_viewer_panel.cpp, rpcs3/rpcs3qt/memory_viewer_panel.h, rpcs3/rpcs3qt/register_editor_dialog.cpp, rpcs3/rpcs3qt/register_editor_dialog.h
* Implement RSX memory manager hook,
* Set the ground for RSX modes of register editor and instruction editor, do not use shared ptrs directly.
* Make register editor and instruction editor modeless to allow to copypaste values from thread context etc in the background. (they close automatically after switching thread)
* Fixed crash when viewing an image that was out of bounds of SPU LS.
=> memory viewer: Implement RSX mode

rpcs3/Emu/System.cpp, rpcs3/main.cpp
I don't remember if there was a reason to have it set to direct.
Maybe someone knows ?
=> Allow BootGame with indirect paths

rpcs3/rpcs3qt/game_list_frame.cpp
- Fixes a weird issue where tooltips would popup for the wrong game.
I don't know why the event filter was needed.
Maybe the tooltips didn't work otherwise back then (old Qt) or it was just some copy paste from google.
=> Fix gamelist tooltips

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/tooltips.h
No need for hardcore stuff while adding games to the list.
- Moves LimitCacheSize to Init instead of BootGame. This also means that we now implicitly call LimitCacheSize in BootRSXCapture
- Make sure that we use the latest global config file for LimitCacheSize.
- Disable the LimitCacheSize option for custom configs
=> Disable LimitCacheSize option for custom configs and optimize add_only boot process

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
* Fix termination wait for zombie PPU threads.
* Because debugger now relies on the combination of exit + wait flag to tell if thread has been terminated, wait for actual termination for zombie threads to add exit flag.
* Always signal the debugger about SPU termination.
=> Tiny fix for zombie PPU threads

rpcs3/main.cpp
Fixes #9720 , alternative to #9721.
Registers destructors for std::exit as if by std::atexit.
=> Support logger stopping at std::exit

rpcs3/rpcs3qt/downloader.cpp
=> Fixup for downloader

rpcs3/Emu/Cell/PPUThread.cpp
If the PPU has just being paused by the debugger, before it entered the breakpoint handler, the PPU would continue onto the next instruction skipping the breakpoint but then being paused on it instead.
=> Fix tiny race in PPU breakpoints

Utilities/bin_patch.cpp, Utilities/bin_patch.h, rpcs3/Emu/Cell/PPUAnalyser.cpp, rpcs3/Emu/Cell/PPUAnalyser.h, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
Use some information exported from the patch engine.
Also possibly fix SPRX patching.
=> PPU LLVM: properly compile patched instructions (need testing)

rpcs3/rpcs3qt/gui_settings.cpp
Replace relative pathes to resources.
Should fix #9732
=> Qt: fix stylesheets on various platforms

rpcs3/Loader/TAR.cpp, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/main_window.cpp
We forgot to close Qt's file descriptors of PS3 firmware fonts we use when they are present. So attempting to open another file descriptor for writing to the PS3 fonts' file in order to install the file failed with access violation error. Of course reinitialize the Qt fonts after installation has finished.
=> Fix firmware updating/reinstallation

rpcs3/Emu/RSX/VK/VKTexture.cpp
- Always comply when running under strict mode.
- Only allow hacky transport for known-to-work GPUs. All nvidia cards since turing don't like the hack so its removed for all NV gpus except a small curated list.
Fixes https://github.com/RPCS3/rpcs3/issues/9742
=> vk: Improve spec compliance

Utilities/StrFmt.h, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Memory/vm_reservation.h, rpcs3/Emu/perf_meter.cpp, rpcs3/Emu/perf_meter.hpp, rpcs3/cmake_modules/ConfigureCompiler.cmake, rpcs3/util/atomic.cpp, rpcs3/util/types.hpp
Explicitly enable -fstack-protector.
Fix attribute to remove it for a particular function on GCC.
=> Fix SAFE_BUFFERS attribute on GCC
