rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h

Should fix assertion in vm.cpp

Fix vm::page_protect regression

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h

Please test Skate 3 and stuff (against regression).

Optimize vm::range_lock

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h

Removed unused arg.
Linearized some branches.

vm::range_lock cleanup and minor optimization

---

rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/main.cpp

I don't know if this has any impact, but my GPU "Quadro P500" was not matching anything.

Treat "Quadro" gpus as NVIDIA and set some log levels to "always" 

---

Utilities/Thread.cpp
Utilities/sync.h
Utilities/types.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm_reservation.h
rpcs3/util/atomic.cpp
rpcs3/util/atomic.hpp

Reduce memory usage.
Allow notifier to skip notifications on unmet conditions.
Improve raw_notify to always wake up the thread, add thread_id arg.

Atomic improvements.

---

Utilities/Thread.h
rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
rpcs3/Emu/RSX/Capture/rsx_replay.cpp
rpcs3/Emu/RSX/Capture/rsx_replay.h
rpcs3/Emu/RSX/Common/ShaderInterpreter.h
rpcs3/Emu/RSX/Common/surface_store.h
rpcs3/Emu/RSX/Common/surface_utils.h
rpcs3/Emu/RSX/GCM.h
rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp
rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/Emu/RSX/RSXFIFO.cpp
rpcs3/Emu/RSX/RSXFIFO.h
rpcs3/Emu/RSX/RSXOffload.h
rpcs3/Emu/RSX/VK/VKOverlays.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTexture.cpp
rpcs3/Emu/RSX/rsx_vertex_data.h
rpcs3/rpcs3qt/render_creator.cpp
rpcs3/rpcs3qt/rsx_debugger.cpp
rpcs3/rpcs3qt/save_data_dialog.cpp
rpcs3/rpcs3qt/trophy_notification_helper.cpp
rpcs3/rpcs3qt/vfs_dialog_tab.cpp
rpcs3/rpcs3qt/vfs_dialog_tab.h

Seems like some stuff remained from old code.
Maybe I accidentally removed some correct includes, we'll see in the linux builds.

More header cleanup

---

Utilities/bin_patch.cpp

I'm sorry in case this doesn't build.
I currently don't have access to my PC.

unify patch log

---

Utilities/JIT.cpp
Utilities/Thread.cpp
Utilities/typemap.h
rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUInterpreter.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
rpcs3/Emu/Cell/lv2/sys_mmapper.h
rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
rpcs3/Emu/Cell/lv2/sys_time.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/Memory/vm_locking.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/rsx_cache.h
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/util/asm.hpp
rpcs3/util/vm.hpp
rpcs3/util/vm_native.cpp

rsx_cache, oh my...
But could be worse.

Virtual memory minor refactoring

---

rpcs3/rpcs3qt/main_window.cpp

Path was only saved when installing .rap files.

Fix path not being saved on install pkgs

---

Utilities/sync.h
rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_reservation.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/main.cpp
rpcs3/util/dyn_lib.cpp
rpcs3/util/dyn_lib.hpp
rpcs3/util/vm.hpp
rpcs3/util/vm_native.cpp

Locking "sudo" memory because it's used for some perf-critical opetations.

Locking some memory

---

rpcs3/util/atomic.cpp
rpcs3/util/atomic.hpp

Removed too tight limit of 56 threads waiting on a single pointer.
It seems it was an issue.
Testers and comments are welcome.

Rewritten waitable atomics again

---

rpcs3/Emu/Io/PadHandler.cpp

Took me no less than 4 hours to find the origin of the problem...
Fixes https://github.com/RPCS3/rpcs3/issues/9160 .

Fix missing controller mapping

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_dbg.cpp
rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/Emu/Cell/lv2/sys_rsx.cpp
rpcs3/Emu/Cell/lv2/sys_tty.cpp
rpcs3/Emu/GDB.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/Memory/vm_locking.h
rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/rpcs3qt/breakpoint_list.cpp
rpcs3/rpcs3qt/cheat_manager.cpp
rpcs3/rpcs3qt/debugger_list.cpp
rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/rpcs3qt/register_editor_dialog.cpp
rpcs3/rpcs3qt/rsx_debugger.cpp

Why do I have to suffer from all of those rewrites :think-hang:
I dont have even the power to even explain how the code works.
Fixes #9237

Fix vm::range_lock, improve vm::check_addr

---

rpcs3/Emu/System.cpp
rpcs3/util/atomic.cpp
rpcs3/util/atomic.hpp

No effect, but sorry if it breaks Accurate DMA. I hope it doesn't.

Minor (not really) update to waitable atomics API

---

rpcs3/Emu/Cell/Modules/sceNp2.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9155

Add some error checking in sceNp2.cpp

---

rpcs3/Emu/Cell/lv2/sys_net.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9256

Improve disconnected state handling of dns queries

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/util/atomic.cpp

Fix possibly broken logic in suspend_all (may fix freezes on TSX).
Disable memory locking if TSX is not uses (may also fix some freezes).
Better memory locking solution is WIP.

Some fixups

---

Utilities/Thread.cpp
Utilities/Thread.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/util/atomic.cpp
rpcs3/util/atomic.hpp

Shift workarounds towards actual problem detection.

atomic.cpp/threads: remove old wait callback

---

rpcs3/Emu/Cell/Modules/cellGame.cpp

cellGame fixes

---

rpcs3/rpcs3qt/debugger_frame.cpp

Debugger: Fix scrolling in first registers panel

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Fixes #9280
FIxes #8798 (should)

SPU LLVM: fix AND instruction family

---

rpcs3/Emu/System.cpp

hotfix for infinite loop when booting game data

---

Utilities/types.h
rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/util/atomic.cpp

1) Possible improvement for TSX-FA, removes threads from suspend list when they wait for syscalls.
2) Some useless improvements in waitable atomics, mostly to test compilers and prove some concepts.

Interesting optimizations

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp

After #9276, fixes some R&C game.

[HOTFIX] Fix SPU LS MMIO

---

rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/rpcs3qt/main_window.cpp

This shouldn't really change anything and basically just adds a comment to a strange member variable.

Minor changes related to Emu.Stop()

---

Utilities/JIT.cpp
rpcs3/Emu/perf_meter.hpp
rpcs3/util/atomic.cpp
rpcs3/util/slow_mutex.hpp
rpcs3/util/vm_native.cpp

1) Some Linux kernels disable Transparent Huge Pages. Why? No idea. My bad.
2) Fixed a possible bug that could possibly lead to some possible rare freezes on, possibly, Windows (and possibly, FreeBSD).

Snowflake fixups

---

rpcs3/main.cpp
rpcs3/stdafx.h
rpcs3/util/shared_ptr.hpp

Added some assertions which should compile no code if my predictions are correct (at least tested on godbolt), and only fire on bad misuse.

[Fixup] shared_ptr.hpp: fix reference counting

---

rpcs3/Emu/RSX/Capture/rsx_replay.cpp
rpcs3/Emu/System.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9352

Fix RSX replay thread

---

Utilities/Thread.cpp
Utilities/bit_set.h
Utilities/types.h
rpcs3/Emu/Cell/Modules/cellAudio.h
rpcs3/Emu/Cell/Modules/cellPamf.h
rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/cellSpurs.h
rpcs3/Emu/Cell/Modules/cellSync.h
rpcs3/util/atomic.cpp
rpcs3/util/atomic.hpp
rpcs3/util/shared_ptr.hpp

Not much room for improvement, but need to try.

Improve notify_all() in atomic waiting (more batching)

---

rpcs3/Emu/perf_meter.hpp
rpcs3/util/asm.hpp
rpcs3/util/atomic2.hpp
rpcs3/util/dyn_lib.hpp
rpcs3/util/fixed_typemap.hpp
rpcs3/util/init_mutex.hpp
rpcs3/util/slow_mutex.hpp
rpcs3/util/typeindices.hpp
rpcs3/util/yaml.hpp

Forgot to remove BOM from .hpp files in previous PR.

Remove bom from .hpp files

---

azure-pipelines.yml
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h

Set msvc toolkit back to mainline

---

Utilities/File.h
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKMemAlloc.cpp

Thanks everyone for identifying the problem.

File hotfix

---

Utilities/Timer.h
Utilities/types.h
rpcs3/Emu/Cell/Modules/cellPad.cpp
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Io/MouseHandler.h
rpcs3/Emu/NP/rpcn_client.cpp
rpcs3/Emu/NP/rpcn_client.h
rpcs3/Emu/NP/signaling_handler.cpp
rpcs3/Emu/NP/signaling_handler.h
rpcs3/Emu/RSX/Overlays/overlays.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKMemAlloc.cpp
rpcs3/Emu/RSX/rsx_cache.h
rpcs3/Emu/RSX/rsx_utils.h
rpcs3/Input/keyboard_pad_handler.cpp
rpcs3/Input/keyboard_pad_handler.h
rpcs3/Input/xinput_pad_handler.cpp
rpcs3/Input/xinput_pad_handler.h
rpcs3/stdafx.h
rpcs3/util/logs.cpp

Always use steady_clock. Any objections?

std::chrono cleanup

---

rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/VK/VKDraw.cpp
rpcs3/Emu/RSX/VK/VKTexture.cpp

- Fix some vulkan spec compliance issues and update driver workarounds/performance hacks
- Fix a regression in vertex texture updates
Fixes https://github.com/RPCS3/rpcs3/issues/9438
Fixes https://github.com/RPCS3/rpcs3/issues/9418

rsx/vk: Minor bugfixes

---

Utilities/StrFmt.cpp
rpcs3/util/fixed_typemap.hpp

It's really embarrassing...
Also fixed hexadecimal line numbers in error reports, another embarrassing typo.

Fix hangs on exit (3rd attempt?)

---

Utilities/JIT.cpp
Utilities/Thread.cpp
rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUInterpreter.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
rpcs3/Emu/RSX/rsx_utils.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/perf_meter.hpp
rpcs3/Emu/system_config.cpp
rpcs3/Emu/title.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/main.cpp
rpcs3/rpcs3qt/log_frame.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/util/atomic2.cpp
rpcs3/util/sysinfo.cpp
rpcs3/util/sysinfo.hpp

What was wrong with sysinfo?
Well, a bunch of code in headers but used only inside the cpp file.

(HOTFIX) Fix various crashes in GUI

---

rpcs3/util/vm_native.cpp

This flag is used in huge mappings allocated only for reserve purpose but possibly unused. From the description:
```
MAP_NORESERVE
Do not reserve swap space for this mapping.  When swap
space is reserved, one has the guarantee that it is
possible to modify the mapping.  When swap space is not
reserved one might get SIGSEGV upon a write if no physical
memory is available. ...
```
It should make it more close to what MEM_RESERVE flag does on Windows.

Use MAP_NORESERVE when available in mmap (Linux)

---

Utilities/Thread.cpp
rpcs3/util/sysinfo.cpp
rpcs3/util/sysinfo.hpp

- Test if forcing sample shading rate fixes navi borked MSAA
- Test if thread affinity is broken (zen3 test)

Experimental Zen3 scheduler

---

rpcs3/Emu/RSX/Common/GLSLCommon.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9534

rsx: Fix ambiguous call to min(float16_t, float)

---

rpcs3/Emu/RSX/VK/vkutils/physical_device.h

Build: Add include for building on certain configs

---

rpcs3/Emu/Cell/PPUModule.cpp

PS3 Loader: Fix sections memorizing

---

Utilities/StrFmt.h
rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/Io/usb_device.cpp
rpcs3/Emu/RSX/VK/vkutils/fence.cpp
rpcs3/cmake_modules/ConfigureCompiler.cmake
rpcs3/rpcs3qt/custom_table_widget_item.h
rpcs3/rpcs3qt/game_list.h
rpcs3/rpcs3qt/game_list_grid_delegate.cpp
rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/screenshot_preview.cpp

Some of the warnings are false alarms, but others may indicate dangerous problems in code.

Warning fix quest

---

.gitmodules

1) Updated asmjit URL to asmjit/asmjit org.
2) Use oldstable asmjit branch.
3) Include asmjit and LLVM workarounds for gcc-11 possible bug #9557

Minor ASMJIT/LLVM update

---

rpcs3/Emu/RSX/Overlays/overlay_utils.h

Fix compilation for gcc-11

---

rpcs3/Crypto/ec.cpp
rpcs3/Crypto/unedat.cpp
rpcs3/Crypto/unpkg.cpp
rpcs3/Crypto/unpkg.h
rpcs3/Crypto/utils.cpp
rpcs3/Crypto/utils.h
rpcs3/Emu/System.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/game_compatibility.cpp
rpcs3/rpcs3qt/game_compatibility.h
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/numbered_widget_item.h
rpcs3/rpcs3qt/pkg_install_dialog.cpp
rpcs3/rpcs3qt/pkg_install_dialog.h
rpcs3/rpcs3qt/progress_dialog.cpp
rpcs3/rpcs3qt/richtext_item_delegate.h

Adds changelog and real title to the packages.
No more guesswork needed.
It's very basic, so contributors might make it prettier in the future.

Readable Package installation

---

Utilities/Thread.cpp
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/gcm_enums.cpp
rpcs3/Emu/RSX/gcm_enums.h
rpcs3/Emu/RSX/gcm_printing.cpp
rpcs3/Emu/RSX/gcm_printing.h
rpcs3/Emu/RSX/rsx_decode.h
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_frame.h
rpcs3/rpcs3qt/rsx_debugger.cpp
rpcs3/rpcs3qt/rsx_debugger.h

Allows to view complete RSX state. (information about textures, shaders, vertices data, ZCULL and much more)
This string is also logged  upon any RSX crashes.

Introducing RSX debugger entry (main debugger)

---

rpcs3/rpcs3qt/skylander_dialog.cpp

Should fix https://github.com/RPCS3/rpcs3/issues/9562 .

Change the way skylander ID is generated

---

rpcs3/Emu/NP/fb_helpers.cpp

Missed it when I reviewed the PR.

Fix UserInfo2_to_SceNpUserInfo2

---

rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/SPURecompiler.cpp

Save 1 instruction by using vpermb instead of pshufb with a mask of 0xf
Also fix conversion of vperm2b index to ShuffleVector index.

SPU LLVM: Optimize ROTQBY family for VBMI

---

Utilities/Thread.cpp
Utilities/Thread.h
rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/rpcs3qt/render_creator.cpp
rpcs3/util/logs.cpp
rpcs3/util/vm.hpp
rpcs3/util/vm_native.cpp

Helper function, I'll try to use it in SPU LS mirrors.

Implement shm::try_map for SPU LS allocation

---

Utilities/Thread.cpp

Attempt to address #9657
I think I was careless and forgot to add special path for all ones.

Trying to fix thread scheduler regression

---

rpcs3/Input/keyboard_pad_handler.cpp

I probably forgot to remove this before merging some PR.

Input: remove debug error

---

rpcs3/Emu/System.cpp

Check for rsx::thread existence in Emu.Stop/Pause/Resume

---

Utilities/Thread.cpp
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/memory_viewer_panel.cpp

RSX is not a CELL thread, it does not need to be paused for it.
Fixes #9675

Do not account RSX for TSX pauses

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/System.cpp
rpcs3/Loader/mself.hpp

Add ppu_precompile() function in PPUThread.cpp
Co-authored-by: Eladash <elad3356p@gmail.com>

Add MSELF support to SPRX precompilation.

---

rpcs3/main.cpp

useful if used like:
`start /w ./rpcs3 --headless <path>`

Windows: Print report_fatal_error to cmd in headless mode

---

Utilities/File.cpp

Due to unfortunate circumstances, locked (perm 0000) file could remain and prevent new files to appear.
Before it was moved to "backup" directory but then that feature was disabled.

Fix permissions on log.gz (Linux)

---

rpcs3/Emu/Cell/PPUModule.cpp

PPU LLVM: workaround patch handling

---

rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_application.h
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.h

@AniLeo @Nekotekina please test

Qt: Simplify stylesheet logic

---

rpcs3/rpcs3qt/log_frame.cpp

A bit hacky way of repainting the log when we change a stylesheet.
I had to prepend the Always messages with some character, so I chose '-' .
The character is up for debate though.

Qt: Repaint log on stylesheet change

---

rpcs3/rpcs3qt/update_manager.cpp

Reverts RPCS3/rpcs3#9750
Something went wrong (#9754)

Revert "Fix auto updater when RPCS3_CONFIG_DIR is set"

---

rpcs3/Emu/RSX/Common/surface_store.h
rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/VK/VKDMA.cpp
rpcs3/Emu/RSX/VK/VKTexture.cpp

Tries to detect when there are too many sections in a given memory range and remove the duplicates if any.
Fixes https://github.com/RPCS3/rpcs3/issues/9624
Should also improve part of https://github.com/RPCS3/rpcs3/issues/8294

rsx: Add duplicate sections detection

---

rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp

Attempt to fix launch failure for users with outdated vulkan loader.

vk: Fixup and refactor for exclusive fullscreen stuff

---

rpcs3/Emu/CPU/CPUDisAsm.h
rpcs3/Emu/RSX/Overlays/overlay_controls.h
rpcs3/Emu/RSX/VK/VKPipelineCompiler.h
rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp
rpcs3/cmake_modules/ConfigureCompiler.cmake

Had to devirtualize some functions.

Make -Woverloaded-virtual an error

---

rpcs3/cmake_modules/ConfigureCompiler.cmake
rpcs3/util/atomic.hpp

Was fixed before but silenced nevertheless.

Fix -Wstring-aliasing (gcc)

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Emu/Cell/lv2/sys_usbd.cpp
rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/rpcn_client.cpp
rpcs3/Emu/RSX/Capture/rsx_replay.cpp
rpcs3/Emu/RSX/GL/GLPipelineCompiler.cpp
rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp
rpcs3/Emu/RSX/rsx_cache.h

Fix most of "[x] thread is too sleepy" at Emu.Stop()

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h

And fix the last sleepy thread. (SPU LLVM Profiler)

Remove cpu_thread destructor

---

rpcs3/Input/product_info.h
rpcs3/rpcs3qt/pad_settings_dialog.cpp

Add Harmonix Pro-Drum Kit

---

rpcs3/rpcs3qt/log_frame.cpp

Should fix #9832, did not test.

Fix TTY handling of control characters

---

rpcs3/Emu/Cell/Modules/cellNetCtl.cpp
rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/np_handler.h

Add CELL_NET_CTL_INFO_DHCP_HOSTNAME impl

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp
rpcs3/Emu/system_config.h
rpcs3/Emu/system_config_types.cpp
rpcs3/Emu/system_config_types.h
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/emu_settings_type.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/tooltips.h

Should resolve: https://github.com/RPCS3/rpcs3/pull/9504#issuecomment-783683580

Settings to enable/disable Buzz controller emulation

---

rpcs3/Emu/Io/PadHandler.cpp
rpcs3/Emu/Io/PadHandler.h
rpcs3/Input/ds3_pad_handler.cpp
rpcs3/Input/ds3_pad_handler.h
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/ds4_pad_handler.h
rpcs3/Input/dualsense_pad_handler.cpp
rpcs3/Input/hid_pad_handler.h
rpcs3/rpcs3qt/pad_led_settings_dialog.cpp
rpcs3/rpcs3qt/pad_led_settings_dialog.h
rpcs3/rpcs3qt/pad_settings_dialog.cpp

- Implements DS3 player LEDs
- Implements DS3 battery indicators
Only seems to work on linux.
Please test.
- Also fixes #9844

DS3: implement player and battery LEDs

---

rpcs3/Input/ds3_pad_handler.cpp

- Fixes DS3 output report on Linux (Rumble and LED)
```
............................................________
....................................,.-'"...................``~.,
.............................,.-"..................................."-.,
.........................,/...............................................":,
.....................,?......................................................,
.................../...........................................................,}
................./......................................................,:`^`..}
.............../...................................................,:"........./
..............?.....__.........................................:`.........../
............./__.(....."~-,_..............................,:`........../ …
```

DS3: fix linux output report

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp

Adds 2 devices that GT6 searches for.

Add some GT6 devices to whitelist

---

Utilities/StrFmt.cpp
Utilities/Thread.cpp
Utilities/Thread.h
rpcs3/main.cpp
rpcs3/util/sysinfo.cpp
rpcs3/util/sysinfo.hpp

Shouldn't affect current code (or I hope so).

Minor util improvements

---

rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp

When using a high datapoint count, we initially calculate with a lot of 0s that don't represent the runtime data.
Let's initialize those with -1 and skip them in the calculations.
By using a single loop, this might also shave off some microseconds.

overlays: don't count initial garbage values.

---

rpcs3/Emu/CMakeLists.txt
rpcs3/Loader/mself.cpp
rpcs3/Loader/mself.hpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/main_window.ui

GUI: Implement MSELF extraction tool

---

rpcs3/Emu/System.cpp

If m_path is passed per windows cli, the path might differ from fs::get_config_dir. Windows is not case sensitive.
There might be more occasions where m_path is compared like this.
I forgot to add an ifdef. I'll add that later.

make from_hdd0_game check lowercase

---

Utilities/File.cpp
rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/cmake_modules/ConfigureCompiler.cmake

Fixes regressions from #9920 
Thanks @elad335 for pointing out a bug in write_gather

[Test please] Fix regressions

---

rpcs3/Emu/Cell/PPUInterpreter.cpp

PPU interpreter hotfix

---

rpcs3/rpcs3qt/main_window.cpp

Hello, I noticed a minor typo on line 915 'verion' and have changed it to 'version'

Resolve minor typo 'verion'

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/table_item_delegate.h

Qt: Import Custom Icons

---

bin/GuiConfigs/Envy.qss
bin/GuiConfigs/Skyline (Nightfall).qss
bin/GuiConfigs/Skyline.qss

How are we supposed to grab them if they are so tiny?
Old
New

Qt: make some scrollbars thicker.

---

Utilities/Thread.cpp
rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_vm.cpp

Replaced errors of sys_mmapper, sys_vm, sceNpTrophy and some more.

Remove some log errors

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/rpcs3qt/about_dialog.ui

Also trying to workaround possible gcc-11 bug.

Minor maintenance

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.h
rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_save_dialog.h
rpcs3/rpcs3qt/save_data_dialog.cpp
rpcs3/rpcs3qt/save_data_dialog.h

Let the game decide if the save data background should be transparent or not.
I made it a little more transparent btw.

cellSaveDataEnableOverlay

---

rpcs3/rpcs3qt/render_creator.cpp

* Fix a race condition for when the thread did return after 10 seconds by ensuring vulkan_adapters is not being modified.

Fix race in render_creator

---

rpcs3/main.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h

This is a reimplementation of #9342 .
I had to rebase it since there were a lot of conflicts.
I also added some more code to make it less prone to errors.
closes #9342

Firmware cli arg installation

---

Utilities/Config.cpp
Utilities/Config.h
rpcs3/Input/evdev_joystick_handler.cpp
rpcs3/rpcs3qt/config_adapter.cpp
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/emu_settings.h

Log useless config entries

---

Utilities/Thread.cpp
rpcs3/rpcs3qt/debugger_list.cpp

And fix similar problem when recovering from AV.

debugger: Fix SPU memory viewing

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/rpcs3qt/auto_pause_settings_dialog.cpp
rpcs3/rpcs3qt/auto_pause_settings_dialog.h
rpcs3/rpcs3qt/breakpoint_handler.cpp
rpcs3/rpcs3qt/breakpoint_handler.h
rpcs3/rpcs3qt/breakpoint_list.cpp
rpcs3/rpcs3qt/breakpoint_list.h
rpcs3/rpcs3qt/call_stack_list.cpp
rpcs3/rpcs3qt/call_stack_list.h
rpcs3/rpcs3qt/cg_disasm_window.cpp
rpcs3/rpcs3qt/cg_disasm_window.h
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_list.cpp
rpcs3/rpcs3qt/debugger_list.h
rpcs3/rpcs3qt/instruction_editor_dialog.h

- Select the item that is being searched for with any "go to" actions.
- Clean up some code
- Fixed the breakpoint deletion. It was hilariously broken.

Debugger: select target item (usability)

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/system_progress.hpp

Refactor some recent code for progress dialog server. Terminate dialog condition is nullptr string.

Implement scoped_progress_dialog

---

rpcs3/main.cpp

This has been bugging me ever since I added the '-' before "always" messages

Move system info to extra line

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h

- Fixes the progress_dialog state reset

progress_dialog fixes

---

rpcs3/Crypto/unself.cpp
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h

fixes #10055
Also removed some unused functions

DRM: Search all user directories for rap files

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

sceNp: fix rap file regression

---

rpcs3/rpcs3qt/emu_settings_type.h

added `inline` suggestion to `settings_location` to prevent 
duplicate includes in `rpcs3/rpcs3qt/emu_settings_type.h`

[OPTIMISATION] added inline suggestion to settings_location to prevent duplicate includes

---

.gitignore

added pvs-studio to gitignore.

added pvs-studio artifacts to gitignore

---

rpcs3/Emu/RSX/VK/VKTexture.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/10106

vk: Fix mip level packed pitch calculation

---

Utilities/bin_patch.h

added `inline` suggestion to `patch_engine_version` to prevent
duplicate includes in `Utilities/bin_patch.h`

[OPTIMISATION] added inline suggestion to patch_engine_version to prevent duplicate includes

---

rpcs3/Emu/RSX/Common/GLSLCommon.cpp

Handles abs(position.w) = 0 case
Fixes https://github.com/RPCS3/rpcs3/issues/9572

rsx: Handle rare rounding issue where position.w is very close to zero

---

Utilities/Thread.cpp
rpcs3/Emu/RSX/RSXFragmentProgram.h
rpcs3/util/shared_ptr.hpp

a couple of small changes; syntax fixes & code cleanup.

small collection of fixes

---

rpcs3/Emu/Io/KeyboardHandler.cpp
rpcs3/Emu/Io/KeyboardHandler.h
rpcs3/Input/basic_keyboard_handler.cpp
rpcs3/Input/keyboard_pad_handler.cpp
rpcs3/Input/keyboard_pad_handler.h

Release all keys when leaving the game window

---

Utilities/bit_set.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
rpcs3/cmake_modules/ConfigureCompiler.cmake

Tried to use concept feature from C++20 (named requirements). In theory, it replaces std::enable_if and other forms of SFINAE while allowing to write more simple code which compiles faster and produces more readable errors. Compiler support is still incomplete though. I don't expect any regressions, but feel free to revert 1nd or 3rd commit if some problem occurs.

bs_t (bitset template) fixup + BitSetEnum concept (experiment)

---

Utilities/Thread.cpp
rpcs3/Emu/NP/fb_helpers.cpp
rpcs3/Emu/NP/np_handler.cpp
rpcs3/util/types.hpp

Made on Big Sur, removing few unnecessary old specifics.
Build with LLVM homebrew.

MacOs build fix proposal.

---

rpcs3/Emu/RSX/VK/VKDMA.cpp
rpcs3/rpcs3qt/debugger_frame.cpp

silence few build warnings, VKDMA: disable Intel chipset for host buffer as it requires root privilege.

FreeBSD/clang update proposal.

---

rpcs3/rpcs3qt/log_viewer.cpp
rpcs3/rpcs3qt/log_viewer.h
rpcs3/rpcs3qt/main_window.cpp

Qt: Speed up Log Viewer

---

rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellUserInfo.cpp
rpcs3/Emu/Cell/Modules/cellUserInfo.h
rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

- Implement most of cellUserInfo
fixes #8472

Ingame Native User Selection

---

rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/lv2/sys_time.cpp

Specialisation of llvm_value_t to allow build with LLVM this time.

Following up on MacOS build fix.

---

Utilities/StrFmt.cpp
Utilities/cfmt.h
rpcs3/Emu/Cell/Modules/cellSail.cpp
rpcs3/Emu/Cell/Modules/cellSail.h
rpcs3/Emu/System.cpp
rpcs3/util/shared_ptr.hpp
rpcs3/util/types.hpp

- Multiplication operator for u128
- Formatting support for u128 (decimal, octal, hex)
- Add invocation operator for shared_ptr
- Add new construction utilities for shared_ptr (copy/move by value)

Implement some missing features from TODO list

---

rpcs3/Emu/Cell/lv2/sys_time.cpp

Try to get system timezone automatically.
Used to be hardcoded to GMT+3.
Attempt to address #10195.

Implement sys_time_get_timezone syscall

---

rpcs3/rpcs3qt/pad_settings_dialog.cpp

Rename Rockband to Rock Band

---

Vulkan/CMakeLists.txt

Fixes current issues with CI on Linux Clang

glslang: Update to 11.4.0 and disable PCH

---

3rdparty/libcurl.vcxproj
3rdparty/libcurl.vcxproj.filters
3rdparty/stblib/stb_image.h
3rdparty/stblib/stb_truetype.h
rpcs3/stb_image.cpp

- pugixml: Update from v1.9-git to v1.11.4
- stblib: Update stb_image from v2.22 to v2.26
- stblib: Update stb_truetype from v1.21 to v1.24
- stblib: Ignore new 3rdparty warnings
- curl: Update from v7.72.0 to v7.76.1
- curl: fix visual studio build

3rdparty: Update dependencies

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/1-regression-report.md
.github/ISSUE_TEMPLATE/2-bug-report.md
.github/PR-BUILD.md
BUILDING.md

- .github: Update CONTRIBUTING.md 
- .github: Update PR-BUILD.md
- Update BUILDING.md
- .github: Update issue templates
Mention settings must be as close to defaults as possible and that game 
patches must be disabled when reporting issues

md: Update BUILDING, CONTRIBUTING, PR-BUILD, ISSUE_TEMPLATE

---

rpcs3/Emu/Cell/Modules/sys_spu_.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/Cell/lv2/sys_spu.h

Save only entry points instead of sys_spu_image structure.

SPU TG: Simplify state of saved SPU image data

---

Utilities/File.cpp
Utilities/File.h
rpcs3/Emu/Memory/vm.cpp

Trying to workaround issues with sparse files (#10231)

fs: implement fs::get_temp_dir() (Win32)

---

rpcs3/Emu/RSX/Common/TextureUtils.h
rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
rpcs3/Emu/RSX/GL/GLRenderTargets.h
rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
rpcs3/Emu/RSX/VK/VKRenderTargets.h

Fixes https://github.com/RPCS3/rpcs3/issues/10263

rsx: Fix transfer barriers not triggering resolve target initialization

---

rpcs3/util/vm_native.cpp

Another fixup

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/Cell/Modules/cellAudio.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Cell/lv2/sys_event.cpp
rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
rpcs3/Emu/Cell/lv2/sys_interrupt.h
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/Cell/lv2/sys_spu.h
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Emu/Cell/lv2/sys_timer.cpp
rpcs3/Emu/Cell/lv2/sys_timer.h
rpcs3/rpcs3qt/kernel_explorer.cpp

Take advantage of the new shared interface.

SPU: Optimize SPU ports/queues

---

README.md

Closing the loop on the license discussion.
Closes #10255

Make RPCS3 license explicit in README

---

rpcs3/util/vm_native.cpp

vm: disable sparse files on win7

---

Utilities/bit_set.h
rpcs3/Emu/Cell/ErrorCodes.h

Should fix #10301 
Adds some minor changes.

LLVM Update fixup (partial revert)

---

rpcs3/rpcs3qt/msg_dialog_frame.cpp

This shouldn't have any impact

Minor change in msg_dialog_frame

---

Utilities/Thread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/Emu/Cell/lv2/sys_rsx.cpp
rpcs3/Emu/GDB.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/System.cpp

Improve get_current_cpu_thread()

---

rpcs3/rpcs3qt/kernel_explorer.cpp

It used recursive search of nodes when there's 0 need in it, it alone took whole seconds to load/refresh the kernel-explorer before, now it's much shorter.

kernel-explorer: Fix horrible performance

---

rpcs3/Emu/RSX/Overlays/overlay_controls.h
rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.h
rpcs3/Emu/system_config.h
rpcs3/Emu/system_config_types.cpp
rpcs3/Emu/system_config_types.h
rpcs3/Input/hid_pad_handler.cpp
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/main_window.cpp

Performance overlay: add average and 1% low

---

rpcs3/Emu/RSX/VK/VKDMA.cpp

- While the vulkan spec explicitly allows destroying mapped blocks, GPUOpen vma_alloc does not.
- Strangely, this issue does not afflict linux users, only windows.

[Hotfix] vk: Forcefully unmap DMA blocks before destroying them

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/Modules/cellPad.cpp
rpcs3/Input/pad_thread.cpp
rpcs3/Input/pad_thread.h

Fix CELL reservations support by logs.
Fixes #10189 and maybe more stuff.

Fix reservations handling in logs 

---

rpcs3/Emu/Cell/SPURecompiler.cpp

expands the optimization from https://github.com/RPCS3/rpcs3/pull/10283 for the BIZ/BINZ/BIHZ/BIHNZ/BRHZ/BRHNZ instructions as well.

SPU LLVM: Expand branch optimizations for more instructions

---

rpcs3/rpcs3qt/main_window.cpp

Updates the latest FW version according to: https://www.playstation.com/en-us/support/hardware/ps3/system-software/
List of changes:
This system software update improves system performance.

Update FW 4.88 Latest Version

---

rpcs3/Emu/RSX/Common/TextureUtils.cpp

Attempt to fix possible regression from #10380 (#10385)

Fixup (span copy refactoring)

---

Utilities/Thread.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/IdManager.h
rpcs3/Emu/System.cpp
rpcs3/util/fixed_typemap.hpp

Split phases of signalling threads and joining them, i.e. signal all threads first only then join them.

Improve emulation stopping speed

---

Utilities/Thread.h

Should fix regressions reported at discord.

Hotfix #10411

---

rpcs3/Emu/System.cpp
rpcs3/util/fixed_typemap.hpp
rpcs3/util/types.hpp

Trying to fix regression #10424 after #10411 by the way.

fixed_typemap.hpp: add range iterator

---

rpcs3/rpcs3qt/game_list_frame.cpp

Fix gamelist filter

---

rpcs3/rpcs3qt/game_list_frame.cpp

This fixes a bug that occasionally shows an empty game list when opening RPCS3.

Qt: fix empty game list phenomenon

---

rpcs3/util/vm_native.cpp

Unfortunately, different systems need different approach here.

vm_native: bypass rpcs3_vm creation if overcommit is enabled (Linux)

---

rpcs3/Emu/RSX/rsx_methods.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/10454

rsx: Fixup for byte order when passing data via vertex registers that are not inline arrays (register vertex data and push buffers)

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp

Based on software test.
Test source and results: https://gist.github.com/Nekotekina/702c9333ec2b2c7b455a1f612b4eda99
Should fix #10460 
Supersedes and closes #10466

sys_fs: improve sys_fs_open accuracy for /dev_bdvd

---

rpcs3/Emu/RSX/rsx_cache.h
rpcs3/Emu/cache_utils.cpp

Similar to how PPU/SPU cache management does it.

rsx cache: Prevent crash on failure to obtain cache directory

---

rpcs3/rpcs3qt/emu_settings_type.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/tooltips.h

I've put warnings for dumb users to not mess with this setting as well.

GUI: Add PPU threads to debug tab [Experimental]

---

rpcs3/Emu/RSX/RSXThread.cpp

* Fixes GCM event queue blowing up from VBLANK events once emulation is paused. (it skipped Emu.IsPaused() check alot, now this check always happens in loop)
* Never sleep in arbitrary sleep periods (was 100us) always measure the precise time of sleep needed improving accuracy and performance.
* Let the vblank thread sleep more when it can.

rsx: Improve VBLANK accuracy

---

rpcs3/Emu/Cell/Modules/sceNpCommerce2.cpp

Fixes "Buzz! Quiz Player" and "Buzz!: Quiz Party" and "Buzz: Lío de concursantes" Offline Gameplay (They all seem to be the same game)

sceNp: fix invalid ctx dereference

---

rpcs3/rpcs3qt/kernel_explorer.cpp

- roughly 5-20 times faster update from scratch on average
- removed some unused function
- added fatals for unexpected node failure
@elad335 review and test please

Qt: kernel_explorer optimizations

---

rpcs3/rpcs3qt/save_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

This probably won't fix anything, but better be safe than sorry

Qt: add more Qt blockingMapped workarounds

---

rpcs3/Emu/Cell/Modules/sceNp2.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/10395.

Fix deref in sceNpMatching2CreateContext

---

Utilities/File.cpp

Fixes a bug encountered when testing savestates.

Win32 FS: Implement support for large reads/writes

---

rpcs3/Emu/Cell/lv2/sys_event.cpp

Hack around unknown behaviour by bypassing timeout for msmw2, preventing waiting for 2m for vsh to load.

Hack for msmw2.sprx timeout.

---

rpcs3/Emu/RSX/Common/surface_store.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTextureCache.cpp

Fixes some corner cases and restores some lost code related to the new memory manager.
Fixes https://github.com/RPCS3/rpcs3/issues/10553

rsx: Video memory manager improvements

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

Fixes #8708, regressed after https://github.com/RPCS3/rpcs3/pull/7623.

cellSaveData: Fixup funcDone result check

---

rpcs3/Emu/RSX/rsx_methods.h

Thanks to gamingrobot#6571 from discord!

rsx: Fix vertical windows' clip

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

Should fix #10573, please test.

cellSaveData/UNIX: Optimize IO

---

rpcs3/Emu/Cell/PPUModule.cpp

Due to a bug, a special debug setting was required to be toggled which has nothing to do with VSH, to run VSH. This is fixed with this PR.

vsh.self: Fix execution on default settings

---

rpcs3/rpcs3qt/gs_frame.cpp

If the screen was smaller than the game window, then the window would pop up top right offscreen.
The fix itself was really simple and obvious from the beginning, just some missing clamping.
But I figured it might be less confusing if I add some prosa.
Especially because it took me a couple of hours to figure out why I made it so complex in the first place.
Btw, there might still be some offset to the left occasionally, but that seems to be an upstream issue.

Qt: fix game window positions if the window is bigger than the screen

---

rpcs3/Emu/Cell/lv2/sys_prx.cpp

...Instead of TODO, also add prx name.

Make sys_prx_unload_module use success type logging

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/lv2/sys_hid.cpp
rpcs3/Emu/Cell/lv2/sys_ss.cpp
rpcs3/Emu/Cell/lv2/sys_storage.cpp
rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
rpcs3/Loader/TAR.cpp

Incorrectly tested exit flag after refactoring.

Fix CPU Profiler regression

---

rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKTexture.cpp
rpcs3/Emu/RSX/VK/VKTextureCache.cpp
rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
rpcs3/Emu/RSX/VK/vkutils/scratch.h

Fixes https://github.com/RPCS3/rpcs3/issues/10625
Fixes https://github.com/RPCS3/rpcs3/issues/10620

vk: Fix a few incorrectly calculated scratch buffer sizes

---

rpcs3/Emu/Cell/lv2/sys_storage.cpp

* Fix potential overflows with uint32_t.
* Fix reading on protected CELL memory.
* Implement incomplete reads.

Fix sys_storage_read

---

Utilities/Thread.cpp
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp

Few fixups

---

rpcs3/Emu/Cell/lv2/sys_spu.cpp

Continuation of #10582 with a proper and accurate implmentation.

SPU: Implement sys_spu_initialize and limit of physical SPU threads

---

rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
rpcs3/Emu/Cell/lv2/sys_lwmutex.h

Destroy syscall should not block lwmutex access if there are lwcond waiters, it shall wait patiently for them to quit/wake up.
Blocking lwmutex access also prevents proper lwcond signalling which what the syscall waits for, resulting in a deadlock.

Bugfix of sys_lwmutex_destroy

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/Modules/cellCamera.h
rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Emu/Cell/Modules/cellGem.h
rpcs3/Emu/Io/MouseHandler.h
rpcs3/Input/basic_mouse_handler.cpp

This may or may not have an impact on any PSMove game.
It fixes some calibration screens. For example "Fast Draw Showdown" and "Carnival Island"

[PS Move] cellGem updates

---

rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp
rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/Emu/Cell/lv2/sys_spu.cpp

Fixup HLE lwmutex

---

rpcs3/Emu/Cell/Modules/cellGem.cpp

Just something I forgot to push.

cellGem: use existing constant for sphere radius

---

rpcs3/Emu/Cell/lv2/sys_spu.cpp

Dunno if it's hw correct, hotfix for now.

Fix sys_spu_thread_group_create regression

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/signaling_handler.cpp
rpcs3/Emu/NP/signaling_handler.h
rpcs3/util/media_utils.cpp

Ensure some network thread dependencies

---

rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/NP/signaling_handler.cpp

When closing games, I often get a crash.
This adds a bandaid for now.
tagging @RipleyTom for review

sys_net: add missing range checks

---

rpcs3/Emu/Io/PadHandler.cpp
rpcs3/Input/ds3_pad_handler.cpp
rpcs3/Input/ds3_pad_handler.h
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/ds4_pad_handler.h
rpcs3/Input/dualsense_pad_handler.cpp
rpcs3/Input/dualsense_pad_handler.h
rpcs3/Input/evdev_joystick_handler.cpp
rpcs3/Input/evdev_joystick_handler.h
rpcs3/Input/keyboard_pad_handler.cpp
rpcs3/Input/mm_joystick_handler.cpp
rpcs3/Input/mm_joystick_handler.h
rpcs3/Input/xinput_pad_handler.cpp
rpcs3/Input/xinput_pad_handler.h

I noticed that evdev and mmjoy didn't really work at all.
Also all other handlers had issues when pressing the respective button with ID 0.

input: fix pressure sensitivity buttons

---

rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Emu/Cell/Modules/cellPad.cpp
rpcs3/Emu/Io/Buzz.cpp
rpcs3/Emu/Io/GHLtar.cpp
rpcs3/Emu/Io/Turntable.cpp
rpcs3/Input/pad_thread.cpp
rpcs3/Input/pad_thread.h

While usually not exposed to the user, there was a slight chance that user input was read in a dirty state.
This became apparent during usage of the new pressure sensitivity button

input: fix input "data race"

---

rpcs3/Input/evdev_joystick_handler.cpp
rpcs3/Input/evdev_joystick_handler.h
rpcs3/Input/keyboard_pad_handler.cpp
rpcs3/Input/keyboard_pad_handler.h

input: fix keyboard and evdev

---

Utilities/bin_patch.cpp

It mekes more sense that patches with specific game IDs will be preferred over global patches and not the opposite way arround like it was.
Memory contents works like LIFO: what's written last will be what will remain in memory.

patch_manager: Prefer specific patches over global patches

---

rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/rpcs3qt/main_window.cpp

It always auto-accepted the update

Qt: Fix update button in menu bar

---

rpcs3/Emu/RSX/VK/VKCompute.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.cpp
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/vkutils/chip_class.h
rpcs3/Emu/RSX/VK/vkutils/device.cpp
rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp

- Add workarounds to disable compression on mesa drivers
- Separate intel proprietary vs mesa into two enumerants
Partially addresses https://github.com/RPCS3/rpcs3/issues/10709

vk: Improve driver compatibility

---

rpcs3/Emu/RSX/rsx_methods.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/10720

[HOTFIX] rsx: Fixup image-in data length calculations

---

rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp

Rarely used register indexing mode observed in some titles.
I had done some hardware testing for this earlier but I misunderstood the results to mean clamping was disabled. Turns out, this is not what happens, we instead get TEX[A+N] where A = loop counter and N = index offset. I have yet to encounter this in use in an actual loop case, but it has been observed outside loops, in which case A=0 and N=TIU index (TEX0+N)
Fixes https://github.com/RPCS3/rpcs3/issues/2262
Relates to https://github.com/RPCS3/rpcs3/pull/6388

[TESTERS NEEDED] rsx/fp: Halfplement dynamic indexed TEX[n] loads

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp

Whitelist Kamen Rider Summonride Portal sys_usbd

---

rpcs3/Emu/RSX/VK/vkutils/chip_class.cpp

Required for GPU specific code

vk: Register newer Navi GPUs

---

Utilities/bin_patch.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp

Fix crash on startup.
Fix some warnings.

Hotfix for #10779

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp

Fixup No.2 for #10779

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp

Significantly reduces log spam in LBP2.

cellCamera/sys_net: Anti-Log spam enhancement

---

Utilities/Config.cpp
Utilities/Config.h
rpcs3/Emu/Io/pad_config.cpp
rpcs3/Input/pad_thread.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp

- Fixes loading global pad profiles other than Default.yml
- Fixes loading custom pad profiles
- Fixes saving custom pad profiles
- Fixes removing custom pad profiles
fixes #10819

Fix pad profiles

---

rpcs3/Emu/Cell/Modules/cellVdec.cpp

We already use newer avcodec code anyway.

remove deprecated avcodec_register_all

---

rpcs3/Emu/System.h

Maybe fixes #10862, please test.

Fixup default config-path

---

rpcs3/Emu/Cell/Modules/cellSearch.cpp

While I was doing other related work, I worked on cellSearch and added some stuff.

cellSearch: more stubs and implementations

---

rpcs3/Emu/RSX/RSXThread.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/10881

rsx: Fix stupid overflow

---

rpcs3/main.cpp

Windows/CLI: add "high-res-timer" argument (defaults to 1)

---

rpcs3/Input/keyboard_pad_handler.cpp

I forgot to re-implement this part for the keyboard pad handler after I refactored the pad sensitivity button.

Fix keyboard_pad_handler pressure sensitivity

---

rpcs3/Emu/CPU/CPUTranslator.h

SPU LLVM Fixup for VDBPSADBW

---

rpcs3/Crypto/unpkg.cpp
rpcs3/Crypto/unpkg.h

I keep the functions archive_read/seek because I want them to do another thing in the future.

PKG: Simplify files management

---

rpcs3/Crypto/unpkg.cpp

Forgot that m_file has been moved.

Fixup for multi-file PKG

---

rpcs3/Emu/Io/pad_config.h
rpcs3/Input/keyboard_pad_handler.cpp

Input: increase mouse acceleration maximum

---

rpcs3/Emu/RSX/Common/TextureUtils.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/8377

rsx: Configure pitch correctly for pitch-zero textures (1D)

---

rpcs3/Emu/RSX/VK/VKOverlays.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9251

vk: Do not clip region using renderpass renderarea, we have scissor for that

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

Fix npDrmIsAvailable Regression

---

rpcs3/Emu/CPU/CPUTranslator.cpp
rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/SPURecompiler.cpp

SPU LLVM: Hook up 128 bit spu verification and enable FMA for Sapphirerapids

---

rpcs3/Emu/RSX/RSXThread.cpp

Some games can load all textures before a draw sequence and then swap shaders for different draws. Optimizations in texture state streaming make it so that only referenced data is carried forward which can lead to 'holes' in the data stream when the original shader is loaded again.
Fixes https://github.com/RPCS3/rpcs3/issues/10796
Fixes https://github.com/RPCS3/rpcs3/issues/9590

rsx: Fix texture state propagation between unrelated draw calls

---

rpcs3/main.cpp
rpcs3/rpcs3qt/curl_handle.cpp
rpcs3/rpcs3qt/curl_handle.h
rpcs3/rpcs3qt/downloader.cpp
rpcs3/rpcs3qt/downloader.h

and really verbose logging i you use `--verbose-curl`

curl: add verbose logging

---

rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/pad_settings_dialog.h

Qt: fix initial pad settings dialog size and position

---

rpcs3/Emu/Cell/Modules/cellMsgDialog.h
rpcs3/Emu/system_progress.cpp
rpcs3/headless_application.cpp

Fix headless mode

---

rpcs3/Input/evdev_joystick_handler.cpp

Properly recognize triggers and axes for evdev pads.

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
rpcs3/headless_application.cpp
rpcs3/main_application.cpp
rpcs3/rpcs3qt/gui_application.cpp

cellSaveData:
- always log setList and setBuf (for debugging)
- show at least one error with CELL_SAVEDATA_ERRDIALOG_NOREPEAT
Other:
- Simplifies some GUI and overlays code
This PR consists of the low hanging fruits of #10622. 
I'll leave the other changes in the other one.

Improve CELL_SAVEDATA_ERRDIALOG_NOREPEAT + some refactoring 

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp

Stub UVC camera init

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp
rpcs3/Emu/Cell/lv2/sys_usbd.h
rpcs3/Emu/Io/Buzz.cpp
rpcs3/Emu/Io/Buzz.h
rpcs3/Emu/Io/GHLtar.cpp
rpcs3/Emu/Io/GHLtar.h
rpcs3/Emu/Io/Skylander.cpp
rpcs3/Emu/Io/Skylander.h
rpcs3/Emu/Io/Turntable.cpp
rpcs3/Emu/Io/Turntable.h
rpcs3/Emu/Io/usb_device.cpp
rpcs3/Emu/Io/usb_device.h
rpcs3/Emu/Io/usio.cpp
rpcs3/Emu/Io/usio.h

Also removed some redundant code that resulted in warnings.
Fixes https://github.com/RPCS3/rpcs3/issues/11174.

[Testing] Impl sys_usbd_get_device_location

---

rpcs3/Emu/RSX/Common/texture_cache_utils.h

Fixes https://github.com/RPCS3/rpcs3/issues/11136

rsx: Fix sloppy format matching test

---

rpcs3/Emu/RSX/VK/VKTexture.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/10936

vk: Fix incorrect mixed transfer modes for mipmapped VTC

---

rpcs3/Emu/Audio/AudioBackend.h
rpcs3/Emu/Audio/Cubeb/CubebBackend.h
rpcs3/Emu/Audio/FAudio/FAudioBackend.h
rpcs3/Emu/Audio/Null/NullAudioBackend.h
rpcs3/Emu/Audio/XAudio2/XAudio2Backend.h
rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/Cell/Modules/cellAudio.h

- Initialize thread state in its constructor
- Force disable buffering for null backend

CellAudio fixes

---

rpcs3/Emu/RSX/GL/GLPresent.cpp
rpcs3/Emu/RSX/VK/VKPresent.cpp
rpcs3/Emu/RSX/rsx_utils.cpp
rpcs3/Emu/RSX/rsx_utils.h

Fixes https://github.com/RPCS3/rpcs3/issues/11218
Fixes https://github.com/RPCS3/rpcs3/issues/11216

rsx: Add some sensible fallbacks

---

rpcs3/Emu/Cell/PPUTranslator.h

PPU LLVM: fix regression

---

rpcs3/rpcs3qt/gs_frame.cpp

Qt: fix screenshot path creation

---

rpcs3/Emu/Cell/SPURecompiler.cpp

🐛
I'll try to figure out what's wrong later
Fixes: https://github.com/RPCS3/rpcs3/issues/11246

 SPU LLVM: Disable affineqb shufb paths temporarilly 

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm_reservation.h

With this patch, RDR is able to start with default settings with TSX enabled.

Fix one TSX regression

---

rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9845

rsx: Fix excluded section overlap test

---

rpcs3/Emu/RSX/Program/GLSLCommon.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/11295

rsx: Fix zclip w scaling

---

Utilities/JIT.cpp

Not sure what else could cause a crash (#11302).

No name fixup

---

3rdparty/llvm.cmake

Fix builds on additional platforms

---

rpcs3/rpcs3_version.cpp

rpcs3_version: Bump to 0.0.20

---

rpcs3/Emu/RSX/GL/GLTexture.cpp

- This is just not part of spec, there is no enforcement for multiple of block size for width or height of s3tc compressed images.
- This restriction does indeed exist for ASTC and ETC but we're not using those formats.
Fixes broken textures in some games when using OpenGL backend. While it initially seemed to be a regression, its actually just a case of more correct code uncovering more unsightly hacks in other parts of the code.

gl: Fully drop alignment restriction for compressed textures

---

3rdparty/hidapi/CMakeLists.txt

- Updates hidapi to 0.11.0
- Updates ffmpeg to latest Vita3K commit

Update hidapi to 0.11.0

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_fs.h

Needed for S357 games.
Needs to be hooked up to a config.

Fcntl 0xc0000007, 0xc0000015, 0xc000001c

---

rpcs3/Emu/Cell/Modules/cellAudio.cpp

cellAudio: fix enqueued samples computation

---

rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/util/simd.hpp

Fix regression #11409

---

rpcs3/Emu/RSX/VK/VKRenderTargets.h

Fixes https://github.com/RPCS3/rpcs3/issues/11423

vk: Only enable DCC workaround if the format features allow it

---

rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/GL/GLDraw.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/VK/VKDraw.cpp

Do not allow dimensions of 0 to reach the backend APIs.
Fixes https://github.com/RPCS3/rpcs3/issues/11442

rsx: Validate requested images before attempting to upload them

---

rpcs3/rpcs3qt/downloader.cpp
rpcs3/rpcs3qt/downloader.h
rpcs3/rpcs3qt/game_compatibility.cpp
rpcs3/rpcs3qt/game_compatibility.h
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h

Update game list when the dialog is canceled. We used to show "Retrieving..." indefinitely.

Qt: fix compat download abort

---

rpcs3/rpcs3qt/about_dialog.cpp
rpcs3/rpcs3qt/about_dialog.ui
rpcs3/rpcs3qt/patch_manager_dialog.ui
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

I hope this works.
TODO:
fixes #7420

Qt: add scrollbar/resize to dialogs

---

rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp
rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h
rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_save_dialog.h
rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.h
rpcs3/Emu/system_progress.cpp

~~- [ ] sounds~~
~~- [ ] copy sounds to .config/rpcs3 / rpcs3.app~~

Add overlay animations

---

.gitmodules

Use RPCS3/asmjit fork

---

rpcs3/main.cpp

Terminate headless application if nothing was booted

---

rpcs3/Emu/System.cpp

RSX captures froze on stop, at least with Vulkan.

RSX: Fix rsx capture stop

---

rpcs3/Emu/system_utils.cpp
rpcs3/Emu/system_utils.hpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/CMakeLists.txt
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/qt_utils.cpp
rpcs3/rpcs3qt/qt_utils.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/shortcut_utils.cpp
rpcs3/rpcs3qt/shortcut_utils.h
rpcs3/rpcs3qt/update_manager.cpp

Add option to create rpcs3 shortcuts

---

rpcs3/Emu/Cell/Modules/cellSearch.cpp
rpcs3/rpcs3qt/update_manager.cpp
rpcs3/util/media_utils.h

Fixes BGM listing in Gundam.
The returned content was always empty.
Playback of the tracks will still require a MusicSelectionContext and cellMusic playback, which isn't implemented yet.
partially implements #10457

cellSearch: fix cellSearchStartListSearch

---

rpcs3/rpcs3qt/shortcut_utils.cpp

Fixes windows paths taken from env.
Fixes linux shortcut icon aspect ratio.
hopefully fixes #11562

Shortcut bugfixes

---

rpcs3/main.cpp
rpcs3/rpcs3qt/shortcut_utils.cpp
rpcs3/rpcs3qt/update_manager.cpp

shortcuts: add some logging, create shortcut path

---

rpcs3/Emu/RSX/rsx_methods.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/11571

Flush dma offloader on texture read sema

---

3rdparty/CMakeLists.txt
buildfiles/cmake/FindFFMPEG.cmake
rpcs3/Emu/Cell/Modules/cellMusicDecode.cpp
rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
rpcs3/util/media_utils.cpp
rpcs3/util/media_utils.h

Implements the basic functionality of cellMusicDecode.
Works with Space Invaders (if you add the list selection from the other PR).
Probably fixes SSX custom music.

cellMusicDecode: initial implementation

---

rpcs3/rpcs3qt/qt_music_handler.cpp

cellMusic: fix qt music handler resume

---

rpcs3/Emu/RSX/Common/surface_utils.h

Fixes https://github.com/RPCS3/rpcs3/issues/11640

rsx: Unconditionally set MSAA flags if MSAA is active

---

rpcs3/main.cpp

Don't allow running RPCS3 from temp dirs.
Abort if the folder has no write permissions.
Can be ignored for debugging with --allow-any-location
fixes #11236

Add rpcs3 location checks to main

---

rpcs3/main.cpp

This doesn't seem to work as intended

Revert writable folder check

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

Untested, but focus position is clamped anyway.

cellSaveData: handle focus position of new data in lists

---

rpcs3/CMakeLists.txt

This is based off of the instructions found here: https://riptutorial.com/qt/example/24133/integrating-with-cmake

Fix macdeployqt

---

Utilities/Thread.cpp
rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/system_config.h

PPU: adaptive fix for debugger

---

rpcs3/Emu/RSX/Common/surface_store.h

- Do not restrict range to the small region being sampled. Instead scan the entire range provided. This strategy is more successful at finding overlaps.
- Do bounds check for heading rows appearing outside the range. This really shouldn't happen with the full-range scanning.
Fixes https://github.com/RPCS3/rpcs3/issues/11544

rsx: Fix surface cache scanning and removal

---

rpcs3/rpcs3qt/log_viewer.cpp
rpcs3/rpcs3qt/log_viewer.h

Adds a simple filter to the log viewer that removes all lines that do not match the search.

Qt: Implement simple filter in log viewer

---

rpcs3/Emu/Cell/lv2/sys_net.cpp

I removed a `if (true)` thinking it was obsolete code but it was scoping a lock, readded the brackets for the scope.

re-add scope to sys_net_bnet_poll

---

rpcs3/Emu/Cell/lv2/sys_net.cpp

Better type casting depending on return value, it should get rid of "failed with 0x00000000" messages.

sys_net: Fix return values being tagged as errors

---

rpcs3/Emu/NP/np_requests.cpp

All kudos to Megamouse for noticing!

Fix get_roomdata_external_list callback event id

---

rpcs3/Emu/Cell/Modules/cellGameExec.cpp
rpcs3/Emu/Cell/Modules/sceNpPlus.cpp
rpcs3/Emu/Cell/Modules/sceNpPlus.h
rpcs3/Emu/Cell/PPUModule.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Add some HLE function stubs

---

rpcs3/rpcs3qt/log_viewer.cpp
rpcs3/rpcs3qt/log_viewer.h

- Adds the ability to filter the same file multiple times without having to reload it.
- Adds log level filters to the log viewer

Log viewer improvements

---

rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.h

From the results of additional hardware tests.

sys_net: bind & getsockname accuracy

---

Utilities/git-version-gen.cmd

windows: fix git version script release check

---

rpcs3/rpcs3qt/log_viewer.cpp
rpcs3/rpcs3qt/log_viewer.h

This is incredibly useful if you want to copy paste two logs into Meld for example

Qt: Add timestamp filter to log viewer

---

rpcs3/Emu/RSX/GL/GLHelpers.h

Fixes https://github.com/RPCS3/rpcs3/issues/11715

Fix compressed pitch calculation

---

rpcs3/rpcs3qt/main_window.cpp

Easy Decryption For Running Executable

---

rpcs3/Emu/Cell/Modules/cellAdec.cpp
rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/util/media_utils.cpp
rpcs3/util/media_utils.h

Might give more insight for #11726

libav: log more error codes as string

---

rpcs3/Emu/RSX/rsx_methods.cpp

rsx: Allow NV0039 0x2100

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellSearch.cpp
rpcs3/Emu/Cell/Modules/cellVdec.cpp

Allow reading more strings from patch SFO.
This is actually how it was before.
Should fix LBP

cellGameGetParamString: fix patch mode

---

rpcs3/Emu/Cell/Modules/sceNp2.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/11462
Fixes https://github.com/RPCS3/rpcs3/issues/9520

sceNpMatching2CreateContext checks psn state

---

Utilities/Thread.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/Cell/lv2/sys_rsx.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h
rpcs3/rpcs3qt/memory_string_searcher.cpp
rpcs3/rpcs3qt/memory_viewer_panel.cpp

The idea is simple, since g_mutex and g_range_lock usually go together, simplify locking mechanics and potentially make them more efficient.

[Need test] vm locking refactoring

---

rpcs3/Loader/ELF.h

Fixes regressions from #11892.
I do not know why these sections exist if they are unreadable but ok.

Tentative fix for unreadable ELF sections without flags

---

rpcs3/Emu/Cell/Modules/cellGameExec.cpp
rpcs3/Emu/Cell/Modules/cellRec.cpp
rpcs3/Emu/Cell/Modules/cellRec.h

cellRec: fix pOpt pointer type

---

rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_raw.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/11930

sys_net: ensures return from raw socket calls

---

rpcs3/rpcs3qt/pad_settings_dialog.cpp

Qt: disable mouse movement mode groupbox

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp

Closes https://github.com/RPCS3/rpcs3/issues/10298

Add Top Shot Elite controllers to whitelist

---

rpcs3/Emu/CPU/CPUThread.cpp

Hitherto the statistics have been exclusively thread-specific.
* Fixed container management so a collision of a new element with an older element of the record will become impossible.
* Added thread name to thread-specific information printing.
* Fixed condition to abort SPU block statistics collection, now matches SPU LLVM Profiler's.

Make CPU Profiler able to print stats which sum up the records of all SPU threads

---

Utilities/StrFmt.cpp
Utilities/StrFmt.h
Utilities/StrUtil.h

Needs testing by someone who can reproduce an error.

input: properly log hid_error

---

rpcs3/Loader/mself.cpp

MSELF extractor: Ensure the files' dwellings

---

rpcs3/Crypto/decrypt_binaries.cpp
rpcs3/Crypto/decrypt_binaries.h
rpcs3/Emu/CMakeLists.txt
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/main.cpp
rpcs3/rpcs3qt/main_window.cpp

CLI: add decrypt option

---

rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/NP/np_handler.h

This registers the custom menu, which can be used by games to add menu options to the friendlist or the profile in the home menu.
We don't support these features yet though :p

sceNp: register custom menu

---

rpcs3/Emu/Cell/Modules/cellAdec.cpp
rpcs3/util/media_utils.cpp

No idea if this fixes anything

cellAdec: fix uninitialized default size of AVPacketHolder

---

rpcs3/Emu/RSX/Overlays/overlay_message.cpp
rpcs3/Emu/RSX/Overlays/overlay_message.h
rpcs3/rpcs3qt/gs_frame.cpp

Overlays: Add screenshot message to queue

---

rpcs3/rpcs3qt/update_manager.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/7414

fix: unset APPDIR before launching new appimage

---

rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp

Documentation is hard
Fixes #12106

sys_rsxaudio: timer fix

---

rpcs3/Crypto/unpkg.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/12070

fix: parsing bug in read_metadata

---

rpcs3/Emu/Cell/PPUThread.cpp

Debugger: Show HEX view of floating-point PPU registers

---

rpcs3/rpcs3qt/main_window.cpp

Updated the warning message to fix the issue #12137.

Fix issue #12137

---

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
rpcs3/Emu/Cell/lv2/sys_rsx.cpp
rpcs3/Emu/RSX/GCM.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/rsx_methods.cpp

Make libgcm_sys.sprx HLE usable.

rsx: Resurgence of HLE GCM

---

rpcs3/Emu/Cell/Modules/cellGame.cpp

cellGame: Revert cellGameDataCheckCreate2 change for now

---

rpcs3/Crypto/utils.cpp
rpcs3/Crypto/utils.h
rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellGame.h
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/rpcs3qt/downloader.cpp
rpcs3/rpcs3qt/downloader.h
rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/update_manager.cpp

- Probably allows a theme installation through the game
- Files are copied to /dev_hdd0/theme with cellGameThemeInstall
- Files are written to /dev_hdd0/theme with cellGameThemeInstallFromBuffer
- The files should be moved, but I don't wanna break stuff (yet)

Initial cellGameThemeInstall and cellGameThemeInstallFromBuffer

---

rpcs3/Input/ds3_pad_handler.cpp

The Report size also seems to be generic here, so let's only check if anything got returned at all.
Also add missing logging for result < 0.
probably fixes #12207

DS3: fix other report size check.

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp

Adds AVX512 path for upload_untouched u16 with primitive restart, and AVX2 and AVX512 paths for upload_untouched without restart. I didn't touch the u32 paths in this PR because I couldn't find any games which used them.
The AVX512 paths handle the remainder in simd code with masking, which provided a large speedup. 
On my i5-1135G7 in demons souls benchmarking a scene in boletaria with a lot of geometry on screen via perf:
```
SSE4_1                      0.64%
AVX2                        0.59%
AVX512                      0.56%
AVX512 w/ remainder masking 0.51%
```
It's worth noting that the wider paths here are likely limited by the anemic memory bandwidth on my laptop, the gap between SSE4_1 and AVX2 is much larger on my desktop 7700K system:
```
SSE4_1 0.38%
AVX2   0.32%
```
So, the …

RSX: Add more wide paths for upload_untouched

---

rpcs3/rpcs3qt/downloader.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/update_manager.cpp

Qt: Also parse changelog with "Background" update

---

Utilities/JIT.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp

Fixup for #12115 
Should fix #12226

SPU/PPU LLVM: fix triple setup (regression fix)

---

rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/Modules/cellSysutil.h

- fixed potential out of bounds error in cellSysutilRegisterCallback
- added more error checks and stubs to cellSysutilGameDataExit functions
- added more error checks and stubs to cellSysutilBgmPlayback functions
- stub cellSysutilRegisterCallbackDispatcher

cellSysutil: more stubs and error checks

---

rpcs3/Emu/Cell/Modules/cellHttp.cpp
rpcs3/Emu/Cell/Modules/cellHttp.h
rpcs3/Emu/Cell/Modules/cellHttpUtil.cpp
rpcs3/Emu/Cell/Modules/cellHttpUtil.h
rpcs3/Emu/Cell/Modules/cellSsl.cpp
rpcs3/Emu/Cell/Modules/cellSsl.h

stub cellHttp

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/RSX/RSXDisAsm.cpp
rpcs3/rpcs3qt/breakpoint_list.cpp
rpcs3/rpcs3qt/breakpoint_list.h
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_frame.h
rpcs3/rpcs3qt/debugger_list.cpp
rpcs3/rpcs3qt/debugger_list.h
rpcs3/rpcs3qt/memory_viewer_panel.cpp

Allows to set breakpoints when using SPU interpreters.

Debugger: Implement SPU breakpoints

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp

Debugger: always print cpu_thread::dump_misc()

---

rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellGame.h
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/Emu/VFS.cpp
rpcs3/Emu/VFS.h
rpcs3/Loader/disc.cpp
rpcs3/Loader/disc.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/headless_application.cpp
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_application.h
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/qt_camera_handler.cpp

- Implements some basic HLE code for disc eject/insert
TODO:

cellGame: prepare disc change callbacks

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/System.cpp

sys_fs: Add mountpoint for /dev_ps2disc

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/headless_application.cpp
rpcs3/headless_application.h
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_application.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/qt_camera_handler.cpp
rpcs3/rpcs3qt/qt_music_handler.cpp
rpcs3/rpcs3qt/save_data_dialog.cpp

Reduces some copy-paste clutter throughout the project

Emu: Implement BlockingCallFromMainThread

---

rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h

Partial revert for cf0fcf5a2adf74cd56186ea4416b3ebac0a587a6

---

rpcs3/main.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/CMakeLists.txt
rpcs3/rpcs3qt/uuid.cpp
rpcs3/rpcs3qt/uuid.h

This creates and logs a unique identifier and saves it to a file.
The ID will be logged for statistical purposes and stay the same until recreated.

Qt: log uuid

---

rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/lv2/sys_config.h
rpcs3/Emu/Cell/lv2/sys_mmapper.h
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/IdManager.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXZCULL.cpp
rpcs3/Emu/System.cpp

[HOTFIX] Savestates: Rising fixes #savestates-invalidation

---

rpcs3/Emu/Cell/Modules/cellMusicDecode.cpp

cellMusicDecode: add more error checks and silence some log messages

---

Utilities/Thread.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_event.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_rsx.cpp
rpcs3/Emu/Cell/lv2/sys_timer.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/Emu/RSX/rsx_methods.h
rpcs3/Emu/System.cpp
rpcs3/util/serialization.hpp
rpcs3/util/types.hpp

To take advantage of this pr you have to resave and reload because it doesn't actually bump savestates version.

Savestates: More stability improvements

---

Utilities/sync.h
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/Common/texture_cache_helpers.h
rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
rpcs3/Emu/RSX/VK/vkutils/device.cpp
rpcs3/Emu/RSX/VK/vkutils/memory.cpp
rpcs3/Emu/cache_utils.cpp
rpcs3/util/atomic.cpp
rpcs3/util/logs.hpp
rpcs3/util/types.hpp
rpcs3/util/vm_native.cpp

Something similar existed earlier in RPCS3 repo but kinda different.

Implement lambda shortener

---

rpcs3/Emu/Cell/Modules/cellSearch.cpp

- Adds a bunch of error checks
- Resets some parameters by default
- Enables shuffle for music content (this is still just one track though)

cellSearch: more error checks and shuffle

---

.ci/build-linux.sh
.ci/deploy-linux.sh
.cirrus.yml

This:
- Bumps the clang compiler to 14.x
- Bumps ninja to 1.11.0
- Bumps SDL2 to 2.0.22
- Updates shellcheck to 0.8.0

Docker version bump

---

rpcs3/Emu/System.cpp

Disable Disc update redirection for manual ELF loader

---

.github/ISSUE_TEMPLATE/2-bug-report.yml
.github/ISSUE_TEMPLATE/3-feature-request.yml
.github/ISSUE_TEMPLATE/4-advanced.md
rpcs3/rpcs3qt/tooltips.h

* Bug report: Log file section is now mandatory, adjust the instructions a bit.
* Feature request: Move the explanation to end of the issue so that it doesn't feel like it is attached to the first input field. Also ask for log file when asking for features that games use + include log instructions.
* Advanced: Adjust the message slightly.
Also adjusts tooltip for Disable exclusive full screen mode.

Minor fixes to issue templates

---

rpcs3/Emu/Cell/Modules/cellMusic.cpp
rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp
rpcs3/Emu/Io/Null/null_music_handler.h
rpcs3/Emu/Io/music_handler_base.h
rpcs3/rpcs3qt/qt_music_error_handler.cpp
rpcs3/rpcs3qt/qt_music_error_handler.h
rpcs3/rpcs3qt/qt_music_handler.cpp
rpcs3/rpcs3qt/qt_music_handler.h

- Fixes some interactions with the media player in LBP2
- Sadly rewind does not work with the QMediaPlayer on windows

cellMusic: Improve resume, fast forward and rewind

---

rpcs3/Emu/Cell/Modules/cellPhotoDecode.cpp
rpcs3/Emu/Cell/Modules/cellPhotoImport.cpp
rpcs3/Emu/System.h
rpcs3/main_application.cpp

This lets me choose a picture in LBP.
One thing to note is that the foto dialog needs a couple of seconds to load larger foto collections, so there will be some awkward moments during interaction where the old dialog closes and a new one opens. Meanwhile you can play the game xD.
fixes #12386

Fix cellPhotoImport and implement cellPhotoDecode

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Ports the integer comparison optimization from FCGT to FCMGT.
This instruction is fairly rare, so don't expect any perceptible change in performance.

SPU LLVM: Add integer compare optimization for FCMGT

---

rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp
rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
rpcs3/main_application.cpp

Fixes access to files with characters like fullwidth colon in their filename.

HLE: fix file not found errors in media functions

---

rpcs3/Emu/RSX/rsx_methods.cpp

* Do not flush GPU-pending work when writing labels with the same value.

rsx: Trivial optimization

---

rpcs3/Emu/RSX/RSXThread.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/12455

Fix RSX capture playback

---

rpcs3/Emu/Cell/Modules/cellHttpUtil.cpp
rpcs3/Emu/Cell/Modules/cellPngEnc.cpp
rpcs3/Emu/Cell/Modules/cellPngEnc.h

This is LLE'd by default, so this is currently unused anyway

cellPngEnc: add some error checks

---

rpcs3/Emu/Memory/vm.cpp
rpcs3/util/vm.hpp
rpcs3/util/vm_native.cpp

This PR attempts to utilize sparse files feature existing on modern OSs to prevent allocation of unused memory if it's not already handled by overcommit feature.
Please compare memory usage and check for performance regression on Win32 hosts.

[Need test] Try to reduce memory usage (mainly Windows)

---

rpcs3/util/vm_native.cpp

Workaround sparse file bugs on windows

---

3rdparty/GPUOpen/include/ffx_fsr1.h

Updated from https://github.com/GPUOpen-Effects/FidelityFX-FSR/commit/a21ffb8f6c13233ba336352bdff293894c706575#diff-bd17f1803090744f3677d049566fe2138d8438df8259c65ca4d43345f56e7a37

vk: Update FSR from 1.0 to 1.0.2

---

rpcs3/Emu/Cell/SPUThread.cpp

Bugfix after #12523

---

Utilities/JIT.cpp
Utilities/JIT.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/RSX/Common/BufferUtils.cpp

Trying to de-duplicate code in buffer utilities and bring more AVX2/AVX-512 optimizations in.

Implement simd_builder for x86

---

Utilities/JIT.cpp
Utilities/JIT.h

simd_builder: fix constant locations

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp

BufferUtils: Fix regression in upload_untouched

---

rpcs3/Emu/Memory/vm.cpp

Also fix of page fault event address data reported.

vm.cpp: Fix emulation stopping on SPU access violation

---

rpcs3/Emu/RSX/RSXDisAsm.cpp
rpcs3/Emu/RSX/RSXFIFO.cpp
rpcs3/Emu/System.cpp

Fix it by initializing things by the GUI thread as done in game-boot. And make it use native UI because why not. (rsx is initialized now)
Fixes #12412

System.cpp: Fix Create PPU Cache regression

---

rpcs3/Emu/RSX/RSXZCULL.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/12635

rsx: Properly reset ZCULL stat counters

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/util/atomic.cpp

Fix missed notifications because of improper use of one-time callbacks in atomic waiting.

SPU: Regression fix after #12648

---

rpcs3/Emu/Io/usio.cpp

Keep the LastGameStatus memory so that the game's last status data can be preserved.
Already tested it and it worked well as expected.

USIO: Keep LastGameStatus Memory

---

rpcs3/rpcs3.plist.in

Test build for #12584 (maybe #11661 ?)

Request macOS 10.14.+ permissions

---

rpcs3/Emu/Cell/Modules/cellAudio.cpp

I sometimes use headphones with RPCS3 and I was surprised to see that when I disconnect them or test games without any audio devices attached lots of games either don't boot, enter ingame, or play FMVs. After some debugging, I found that it is because PS3 audio sampling events are not sent when audio devices are not attached, those events must be sent regardless of anything at a periodic rate and are not actually related to the current state of the host PC.
Always send those events to fix this.

Fix compatibility of games when running without audio output

---

rpcs3/Emu/Io/usio.cpp

Some old versions of the games adopting USIO use a smaller size for backup_memory.
This PR aims to provide compatibility to the games which use a smaller backup_memory.

Improved the compatibility of USIO for old versions of games

---

rpcs3/Emu/Io/PadHandler.cpp
rpcs3/Emu/Io/PadHandler.h
rpcs3/Emu/Io/pad_types.h
rpcs3/Input/ds3_pad_handler.cpp
rpcs3/Input/ds3_pad_handler.h
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/ds4_pad_handler.h
rpcs3/Input/dualsense_pad_handler.cpp
rpcs3/Input/dualsense_pad_handler.h
rpcs3/Input/evdev_joystick_handler.cpp
rpcs3/Input/evdev_joystick_handler.h
rpcs3/Input/hid_pad_handler.h
rpcs3/Input/mm_joystick_handler.cpp
rpcs3/Input/mm_joystick_handler.h
rpcs3/Input/pad_thread.cpp
rpcs3/Input/xinput_pad_handler.cpp
rpcs3/Input/xinput_pad_handler.h

- Fix axis identification MMJoy. Apparently I refactored it at some point but never adjusted a couple of functions.
- Fixes some type warnings regarding cellpad flags
- Simplify some input code

Input: Fix MMJOY axis identification and some minor refactoring

---

rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp

Attempt to unbreak a thing and improve another.
Fixes #12745.
Continues the bugfixes journy of #12678.

Continues the bugfixes journey of #12678

---

rpcs3/Emu/Io/usio.cpp
rpcs3/Emu/Io/usio.h

Suggestion for #12847
Original author: @EmiMidnight

USIO Input Enhancement

---

rpcs3/Emu/System.cpp

Multiplex and dire bugfix. (fixes savestate file extension after renaming)

Savestates: +1 Bug

---

rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp

Apparently fixes some issues on NVIDIA cards as well.
Reportedly fixes https://github.com/RPCS3/rpcs3/issues/8603

rsx: Force position invariance on GPUs where it matters

---

rpcs3/Emu/Cell/Modules/cellPad.cpp

cellPad: Noise-cancelling log changes

---

rpcs3/CMakeLists.txt
rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/system_config_types.cpp
rpcs3/Emu/system_config_types.h
rpcs3/Input/evdev_gun_handler.cpp
rpcs3/Input/evdev_gun_handler.h
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/gs_frame.cpp

supports guns via evdev. multiple guns.
extra buttons are configurable (guns can be configured for that).
Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>

evdev gun support

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp

Attempt to address #13009 (ENOTMOUNTED errors were inactive due to previous change)

sys_fs hotfix

---

rpcs3/rpcs3qt/skylander_dialog.h

Closes https://github.com/RPCS3/rpcs3/issues/13013.

Increase max number of skylanders to 8

---

rpcs3/module_verifier.hpp

Windows: Try to fix dll checks

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/main_window.cpp

Qt: Delete empty cache dirs after cache removal

---

rpcs3/Emu/System.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/main_window.cpp

Qt: simplify shortcut creation

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/rsx_debugger.cpp

Qt: don't show message if only the rpcs3 games dir shortcut was created

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp

Closes https://github.com/RPCS3/rpcs3/issues/13016

gl: Throw popup exception if we cannot initialize critical requirements

---

rpcs3/Loader/PSF.cpp
rpcs3/rpcs3qt/category.h
rpcs3/rpcs3qt/localized.h

Used for some PS3 Applications

PSF: Add AS as valid category

---

rpcs3/Emu/RSX/VK/vkutils/scratch.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/13087

vk: Add missing memory barrier

---

rpcs3/Emu/GameInfo.h
rpcs3/rpcs3qt/game_list.h
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/main_window.cpp

Qt: show item count in category filter

---

rpcs3/Emu/RSX/gcm_enums.h
rpcs3/Emu/RSX/rsx_decode.h
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/Emu/RSX/rsx_methods.h

Fixes https://github.com/RPCS3/rpcs3/issues/12987

rsx: Propagate surface format changes to shader ROP control

---

rpcs3/rpcs3qt/config_checker.cpp
rpcs3/rpcs3qt/main_window.cpp

Warn if the user selects a weird file.
Allow more file types and show them all by default.

Qt: Improve Check Config utility

---

rpcs3/Emu/GameInfo.h
rpcs3/rpcs3qt/game_list_frame.cpp

Maybe fixes some platform dependent exception

Qt: fix size_on_disk filetype

---

rpcs3/Emu/RSX/GL/GLDraw.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp

Ref: https://www.khronos.org/opengl/wiki/Logical_Operation
Fixes https://github.com/RPCS3/rpcs3/issues/9428

rsx: Fix logicOp interaction with blending

---

Utilities/File.cpp
Utilities/File.h
rpcs3/Crypto/unedat.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp

Reads from the given offset; does not seek; thread-safe.

fs: implement file::read_at

---

rpcs3/Crypto/unedat.cpp
rpcs3/Crypto/unpkg.cpp
rpcs3/Crypto/unpkg.h
rpcs3/rpcs3qt/main_window.cpp

* Fixes #13113 
* Improve PKG installation performance by using mutiple threads to decrypt and read data.

PKG Multi-threaded Installation

---

rpcs3/Crypto/unpkg.cpp

PKG: Hold the multi-threading until another PR is merged

---

rpcs3/Emu/System.cpp
rpcs3/Emu/system_utils.cpp
rpcs3/Emu/system_utils.hpp
rpcs3/rpcs3qt/category.h
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/localized.cpp
rpcs3/rpcs3qt/localized.h

* Custom VSH config.
* VSH shortcut creation.

VSH/UI: Add VSH to game grid

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_prx.h
rpcs3/Emu/Cell/lv2/sys_vm.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/VFS.cpp
rpcs3/Emu/savestate_utils.cpp
rpcs3/rpcs3qt/localized.cpp

* Fixes #13204.
* Fixes #11305.

PRX/savestates/VSH: Associate PRX with library, fix VSH browser

---

rpcs3/Emu/RSX/rsx_methods.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/13218

rsx: Fix some pipe state signal propagation routines

---

BUILDING.md

Typo occurred during glslang update to sdk-1.3.224.1

Fix BUILDING.md Vulkan SDK Version

---

rpcs3/emucore.vcxproj.filters

Thanks @kd-11 for pointing the fault out.

Fix emucore.vcxproj.filters

---

rpcs3/rpcs3qt/pad_settings_dialog.cpp

Allow unbinding pad buttons by right clicking

---

rpcs3/rpcs3qt/vfs_dialog.cpp

Qt: fix vfs dialog usb tab cast

---

rpcs3/Emu/Cell/lv2/lv2.cpp

Allows to view syscall usage more clearly and avoids spam especially after a soft freeze.

Print LV2 Syscall Usage only if increased since last print

---

rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Input/evdev_gun_handler.cpp
rpcs3/Input/evdev_gun_handler.h

- fix analog_t required for some games
- changing mapping to better fit to games (for example, select is rarely used)
Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>

guns fixes

---

3rdparty/CMakeLists.txt
BUILDING.md

- Update SDL download link
- Disable 3rdparty FAudio if the SDL version is not available
fixes #13351

FAudio maintenance

---

rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.h

Fixes https://github.com/RPCS3/rpcs3/issues/13292
Closes https://github.com/RPCS3/rpcs3/issues/11043
Closes https://github.com/RPCS3/rpcs3/issues/10880

rsx: Don't accept garbage shader input

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp

Improves stepping with syscalls/fw.

Debugger: Print error codes stored in GPR

---

rpcs3.sln
rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu.cpp
rpcs3/main.cpp
rpcs3/util/media_utils.cpp

- Fixes miniupnp visual studio dependency
- Fixes some localtime warnings

Fix Visual studio dependency

---

rpcs3/util/fixed_typemap.hpp

This allows to safely call is_init<T>() at any time.

fixed_typemap.hpp: static allocation for m_init

---

rpcs3/Emu/NP/np_handler.cpp

Forces local IP to bind address if set

---

Utilities/Config.cpp
Utilities/Config.h
Utilities/StrUtil.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/main.cpp
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/game_list_frame.cpp

Qt: try to fix locale nonsense on linux

---

rpcs3/Emu/Cell/PPUThread.cpp

Copying CIA instead of typing it in is easier for later use

Debugger: show CIA in register view

---

rpcs3/rpcs3qt/main_window.cpp

Updates the latest FW version according to: https://www.playstation.com/en-us/support/hardware/ps3/system-software/ List of changes:
This system software update improves system performance.

Update FW 4.90 Latest Version

---

rpcs3/Emu/Cell/Modules/cellMic.cpp
rpcs3/Emu/Cell/Modules/cellMic.h

- Adds more error checks
- Adds source to event queue
- Unifies/enables some functions based on assembly
One thing to mention is that I'm unsure about the changes to cellMicGetDeviceAttr

cellMic: random improvements

---

rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/np_handler.h
rpcs3/Emu/NP/np_requests.cpp
rpcs3/Emu/NP/rpcn_client.cpp
rpcs3/Emu/NP/rpcn_client.h
rpcs3/rpcs3qt/recvmessage_dialog_frame.cpp
rpcs3/rpcs3qt/sendmessage_dialog_frame.cpp

An exception is better than having a segfault.

rpcn: throw exception when using rpcn features without a proper config

---

rpcs3/Emu/NP/rpcn_client.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/12896

Fix wolfssl connect

---

Utilities/bin_patch.cpp
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/hid_pad_handler.cpp

- fixes move_file/hide_file
- log PID and VID in hid handlers

patches: fix move_file/hide_file error

---

rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp

cellVdec: use 128 line alignment in buffersize

---

rpcs3/Input/hid_pad_handler.cpp

hid: try to fix linux

---

rpcs3/Emu/Cell/SPURecompiler.cpp

SPU LLVM: fix regression from #13500

---

.gitmodules

Saved us from some connectivity issues on CIs in the past.

Use relative urls in .gitmodules

---

rpcs3/Loader/TRP.cpp

probably confirms user error in #13537

Trophies: log more specific errors on install failure

---

rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/Modules/sceNp2.cpp

Fixes Worms 2: Armageddon netplay.

Signaling: report status inactive on unknown connection

---

rpcs3/Emu/System.cpp

Fix an emulator crash in Emulator::SaveSettings

---

rpcs3/Emu/Io/GHLtar.cpp
rpcs3/Emu/Io/Turntable.cpp

Probably fixes https://github.com/RPCS3/rpcs3/issues/13504

Increase delay for GHL and TT int transfers

---

rpcs3/Emu/Cell/Modules/cellMic.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/13589

Fix mic thread usage

---

rpcs3/Emu/Cell/Modules/cellMusicExport.cpp
rpcs3/Emu/Cell/Modules/cellPhotoExport.cpp

- Implements cellMusicExport to the same extent as the other two export utilities
- Add missing funcFinish error check to cellPhotoExport

cellMusicExport: first implementation

---

rpcs3/Emu/RSX/RSXThread.cpp

It's still not clear what RSX does in this case, and it is very difficult to test because rendering succeeds. If the surface does not fit within the pitch, let's just force it to fit within the available memory. I'll need to prep some hw tests for this at some point to avoid all the heurestics.
Fixes https://github.com/RPCS3/rpcs3/issues/13581

rsx: Add a clip_width workaround for some buggy games

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/13645

Fix deref in cellSaveData

---

rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp

PPU LLVM: disable DSE pass

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Custom pass erasing unnecessary stores and sinking some of the stores out of the loop. May restore some of the recent performance loss.

SPU LLVM: optimize register stores

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h

- add game grid filters similar to game list filters
fixes #13580

Qt: add grid filters

---

rpcs3/util/sysinfo.cpp

Keep second 0 in firmware strings

---

rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/NP/np_requests.cpp
rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/VK/vkutils/device.cpp
rpcs3/Emu/System.cpp

Silence some warnings

---

rpcs3/Crypto/unself.cpp
rpcs3/Crypto/unself.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/lv2/sys_ss.cpp

Update Unself structs and documentation 

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Fixup for #13720

---

rpcs3/rpcs3qt/game_list_frame.cpp

- Fixes missing game size calculation when searching for a game

Qt: Set game size calculation function properly

---

rpcs3/Emu/CPU/CPUTranslator.h

SPU LLVM: fix bug for AMD FX processors

---

rpcs3/rpcs3qt/trophy_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.h

May improve loading time of the trophy manager for slow drives.

Qt: lazy load trophy icons

---

rpcs3/rpcs3qt/save_manager_dialog.cpp

Should fix:
https://forums.rpcs3.net/showthread.php?tid=206220

Qt: fix savedata dialog exception

---

rpcs3/Emu/RSX/RSXThread.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/13741

rsx: Fix up the framebuffer width if the pitch fits scissor but not the clip width

---

rpcs3/Emu/Cell/lv2/sys_spu.cpp

savestates:/sys_spu: Fix join saving

---

.ci/deploy-linux.sh

Fix the issue with not being able to render with mesa drivers reported
https://github.com/RPCS3/rpcs3/issues/13641#issuecomment-1528881975

Bring back removing the wayland-client lib

---

.ci/deploy-linux.sh
.ci/deploy-mac.sh
.ci/deploy-windows.sh
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/memory_string_searcher.cpp
rpcs3/rpcs3qt/rpcn_settings_dialog.cpp

- Remove git dir from all distributions
- Silence some warnings
- Ignore warnings from external sources when building the rcps3 project in Visual Studio. This silences Qt warning spam.

Don't ship git folder

---

3rdparty/llvm.cmake

Fixes building with BUILD_LLVM=ON

Force STATIC_LINK_LLVM on with BUILD_LLVM=ON

---

Utilities/Thread.cpp

BEXTR is emitted for znver CPUs in recent LLVM 16 update. Need to decode it in order to support SPU MMIO.

[LLVM Update bugfix] Add support for BEXTR instruction

---

.ci/deploy-linux.sh

Fixes https://github.com/RPCS3/rpcs3/issues/13795

Add linuxdeploy-plugin-checkrt for compatibility with older distros

---

rpcs3/main.cpp
rpcs3/util/media_utils.cpp
rpcs3/util/media_utils.h

I simply added this so I don't have to log this manually whenever I wonder about our codecs.

cli: add ability to log ffmpeg codecs

---

rpcs3/rpcs3qt/game_list.cpp
rpcs3/rpcs3qt/game_list.h
rpcs3/rpcs3qt/game_list_delegate.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_table.cpp
rpcs3/rpcs3qt/game_list_table.h
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/table_item_delegate.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.h

Qt: allow hiding trophy table columns

---

rpcs3/Emu/Io/Buzz.cpp
rpcs3/Emu/Io/Buzz.h
rpcs3/Emu/Io/GHLtar.cpp
rpcs3/Emu/Io/Skylander.cpp
rpcs3/Emu/Io/Turntable.cpp

input: add sanity checks for buf_size

---

rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_page.cpp
rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp

Overlays: align graph label width with graph width

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp

This should improve the performance of cellCamera and improve responsiveness of the UI while using a camera.

cellCamera: don't switch to main thread unless really necessary

---

rpcs3/Input/ds3_pad_handler.cpp
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/dualsense_pad_handler.cpp

- Adds some error logging if the initial hid_write fails
- Removes some outdated comments

Input/hid: add some more logging

---

rpcs3/Emu/RSX/Overlays/overlay_manager.cpp

Respect thread abort notification.

rsx/overlays: Fix crash on game exit

---

rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/main_application.cpp
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h

Qt/Loader: Let users choose which packages to install

---

.ci/install-freebsd.sh
.cirrus.yml

8551203ebc63 to be reverted around 2023-06-07

CI: upgrade FreeBSD and switch to /quarterly

---

Utilities/File.cpp
rpcs3/Emu/Cell/lv2/sys_usbd.cpp

[Hotfix] Fixed #13954 for macOS builds

---

rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp

PPU: Fix thread entry detection false positives

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/System.h
rpcs3/Emu/system_progress.cpp
rpcs3/Emu/system_progress.hpp

overlays: update progress dialog workaround

---

rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/dualsense_pad_handler.cpp
rpcs3/Input/dualsense_pad_handler.h
rpcs3/Input/hid_pad_handler.cpp

input: Add DualSense Edge to DualSense pad handler

---

rpcs3/Emu/Io/PadHandler.h
rpcs3/Input/sdl_pad_handler.cpp
rpcs3/Input/sdl_pad_handler.h

input: add controller index to SDL controllers

---

rpcs3/Emu/System.cpp

This code hasn't been touched in years. I don't know why it exists.

Loader: remove dead code

---

rpcs3/Emu/Io/PadHandler.cpp
rpcs3/Emu/Io/PadHandler.h
rpcs3/Emu/Io/pad_config.cpp
rpcs3/Emu/Io/pad_config.h
rpcs3/Emu/Io/pad_types.h
rpcs3/Input/evdev_joystick_handler.cpp
rpcs3/Input/evdev_joystick_handler.h
rpcs3/Input/keyboard_pad_handler.cpp
rpcs3/Input/keyboard_pad_handler.h
rpcs3/Input/mm_joystick_handler.cpp
rpcs3/Input/mm_joystick_handler.h
rpcs3/Input/pad_thread.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/pad_settings_dialog.h

- Allows you to assign multiple keys/buttons to the same virtual buttons by pressing shift while clicking on a PushButton.
- fixes #5192
TODO:

[TESTERS NEEDED] Input: allow multi-button assignment

---

rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/cache_utils.cpp

Fix Create PPU Cache

---

rpcs3/Emu/RSX/VK/vkutils/sync.cpp

Xcode is not yet c++20 compliant

Workaround for old compilers

---

rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureMSAAOpsInternal.glsl

Fixes https://github.com/RPCS3/rpcs3/issues/12426

rsx: Wrap MSAA coordinates before texelFetch

---

rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/Common/texture_cache_helpers.h

Fixes https://github.com/RPCS3/rpcs3/issues/14136

rsx: Subimage view fixups

---

rpcs3/Emu/Cell/PPUFunction.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/Cell/SPUThread.h
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/memory_string_searcher.cpp
rpcs3/rpcs3qt/memory_viewer_panel.cpp
rpcs3/rpcs3qt/memory_viewer_panel.h

* HLE/LV2 calls history. (need to enable PPU debug option and PPU Calling history)
* Add Regular Expressions instruction searching mode to the memory viewer.

Implement PPU LV2 debug

---

rpcs3/rpcs3qt/main_window.cpp

New:
Click "Show Details" to see the changelog
Old:
Couldn't scroll, message box was too large.

Qt: Use detailed text for changelog in install message box

---

rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureOps.glsl

Looks like I inadvertently killed the shader compilation on AMD cards.
Fixes https://github.com/RPCS3/rpcs3/issues/14166

[HOTFIX] rsx: Fix AMD shader codegen

---

rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/System.cpp
rpcs3/rpcs3qt/game_list_frame.cpp

Force inherit BDVD/PS3_GAME across game updates

---

rpcs3/Crypto/ec.cpp
rpcs3/Crypto/ec.h
rpcs3/Crypto/unedat.cpp
rpcs3/Crypto/unpkg.cpp

Improves #14161
```
Old: Package installation took 212.59543 seconds
New: Package installation took  ? seconds
```

Optimize ecdsa

---

rpcs3/Emu/System.cpp

Fix default renderer when creating a brand new config

---

Utilities/Thread.cpp
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/savestate_utils.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/main_window.cpp

Savestates should work now fully using ASMJIT.

Savestates Fixes (part 2 out of 3)

---

Utilities/bin_patch.cpp
rpcs3/Emu/Cell/PPUThread.cpp

Fixup SONIC patches

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/12609
Fixes https://github.com/RPCS3/rpcs3/issues/12862
Which is a regression caused by #11935
Also needs regression testing for:
#11914
#11319
I don't remember why I moved the trophy file checks down there and it isn't mentioned in the original PR, but checking the file beforehand does fix the issue.
Maybe Nekotekina still has the hw test and can test with the callback if that's the correct order.
The game opens a msg dialog for the file installation during the initial callback and never closes it because it keeps waiting for the remaining installation callbacks. On the first boot this miraculously works, but afterwards it doesn't anymore. So you ***might think*** since it works on the first boot, it should always work.
Here's the catch though: …

sceNpTrophy: Check if a trophy configuration file exists before starting the install process

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/MFC.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/Cell/lv2/sys_tty.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h

Known to improve performance in RDR on linux. Also persona 5 on Windiws.
Closes #8462

SPU/Non-TSX: Implement concurrent reservations optimization

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Help LLVM avoid emitting 2 subtract instructions due to type mismatch when the second source operand of ROTQMBY comes from SFI 0

SPU LLVM: Optimize common ROTQMBY pattern

---

rpcs3/Emu/Audio/AudioBackend.cpp
rpcs3/Emu/Audio/Cubeb/CubebBackend.cpp
rpcs3/Emu/Cell/Modules/cellHttpUtil.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/NP/rpcn_client.cpp
rpcs3/Emu/RSX/GL/glutils/capabilities.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/vkutils/device.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/savestate_utils.cpp
rpcs3/Input/hid_pad_handler.cpp
rpcs3/rpcs3qt/cheat_manager.cpp
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/localized_emu.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/midi_creator.cpp
rpcs3/rpcs3qt/rpcn_settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/tooltips.h

Fixes typos where spelling or grammar is objectively wrong. Changes wording and capitalization in some areas to be more consistent with other areas.

Fix typos, improve consistency

---

bin/GuiConfigs/Classic (Bright).qss
bin/GuiConfigs/Darker Style by TheMitoSan.qss
bin/GuiConfigs/Envy.qss
bin/GuiConfigs/Kuroi (Dark) by Ani.qss
bin/GuiConfigs/ModernBlue Theme by TheMitoSan.qss
bin/GuiConfigs/Skyline (Nightfall).qss
bin/GuiConfigs/Skyline.qss
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_frame.h
rpcs3/rpcs3qt/elf_memory_dumping_dialog.cpp
rpcs3/rpcs3qt/stylesheets.h

Maybe improves RSX debugger performance by using QPlainTextEdit. This is also technically a bugfix because rich text is not intended with the debugger registers panel.

Qt: Minor improvements

---

rpcs3/Emu/Cell/PPUThread.cpp

Should restore performance in MGS4 (~10% fps gain)
Addresses: https://github.com/RPCS3/rpcs3/issues/13638#issuecomment-1659201120

Direct return in ppu_check

---

Utilities/sync.h

Fixup futex_waitv redefinition

---

.ci/deploy-linux.sh
.ci/deploy-windows.sh
.ci/get_keys-windows.sh
.ci/github-upload.sh
.ci/setup-windows.sh

CI: Don't silence curl errors

---

rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/system_progress.cpp

Fixup SPU/PPU Cache Abortion, Fix VSH Regression

---

rpcs3/Emu/Cell/PPUAnalyser.cpp

[hotfix] PPU Analyzer: Fixup verify_func

---

rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Loader/ELF.h
rpcs3/util/fixed_typemap.hpp

Fixes #14450 
Fixes #14445 
Fixes segfault when pressing Ctrl+N on PPU debugger.

PPU: Fixup interpreter and analyzer

---

rpcs3/util/atomic.cpp

Fixup futex_waitv regressions

---

rpcs3/Emu/Cell/PPUModule.cpp

PPU Loader: Fixup stack alignment after envp fix

---

rpcs3/Emu/Cell/Modules/sys_io_.cpp

Probably fixes regressions from #14458

cellPad: Fixup sys_config management

---

rpcs3/Emu/Cell/Modules/cellRec.cpp

Adds h264, mjpeg, AAC and mp3 encoders.

cellRec: add more encoder options

---

rpcs3/Emu/Cell/Modules/cellPad.cpp
rpcs3/Emu/Cell/Modules/cellPad.h
rpcs3/Emu/NP/rpcn_client.cpp
rpcs3/Emu/NP/rpcn_client.h
rpcs3/Emu/RSX/RSXFIFO.cpp
rpcs3/rpcs3qt/rsx_debugger.cpp
rpcs3/rpcs3qt/skylander_dialog.cpp

May fix #14458. (notify if the issue still occurs)

Replace some utils::bless usages, Fixup cellPadPeriphGetInfo

---

rpcs3/rpcs3qt/main_window.cpp

CLI - install multiple pkgs from folder

---

rpcs3/rpcs3qt/game_list_frame.cpp

Game List: Add initials-only search

---

rpcs3/Emu/Io/ghltar_config.h

GHLtar: fix guitar tilt

---

rpcs3/Emu/Cell/PPUAnalyser.cpp

PPU Analyzer: Fix OPD section validation

---

rpcs3/Emu/Cell/lv2/sys_rsx.cpp

sys_rsx: Fix local memory size reported in driver info

---

rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h

SPU LLVM: Fill space between functions using targets (Precompilation)

---

rpcs3/Emu/system_progress.cpp

Progress dialog: show analysing... while no files or modules are known yet.

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/system_progress.cpp
rpcs3/Emu/system_progress.hpp

Add approximation to remaining compilation time

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_overlay.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/system_progress.cpp
rpcs3/Emu/system_progress.hpp
rpcs3/util/asm.hpp

Now based on file sizes instead of file count. This also means that the actual progress percentage should be much more consistent and not fluctuating much anymore even when new modules are discovered during compilation.

PPU/Progress Dialog: Improve remaining time approximation

---

Utilities/Thread.h
rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/lv2/sys_overlay.h
rpcs3/Emu/Memory/vm_ptr.h
rpcs3/Emu/System.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9694
Should improve MGS4 compilation time.
Fixed a regression from #14622.

PPU LLVM: Re-add multi-threaded (multi-files) overlay module compilation

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.h
rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp
rpcs3/Emu/Cell/lv2/sys_rsxaudio.h
rpcs3/Emu/IdManager.h
rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/util/serialization.hpp

* Fix file handles serialization regression.
* Serialize sockets for the first time. (was disabled unintentionally)
* Add sys_rsxaudio serialization.

Savestate fixes part 4 out of 3

---

azure-pipelines.yml

See docker commit for changes; https://github.com/RPCS3/rpcs3-docker/commit/5710de860ce901be898c96615783aa6b8150fbb1

Update Linux Docker to Qt 6.5.3

---

3rdparty/curl/CMakeLists.txt

CMake: fix curl build

---

rpcs3/rpcs3qt/main_window.cpp

- Allows you to analyze a .log.gz file in the "Check Config" tool in Utilities.

Qt: allow to use zipped logs in config checker

---

rpcs3/Emu/VFS.cpp

Seen the bug appear on discord.

VFS: fix rename

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

cellSaveData:
- The savedata parameter checks were missing conditions for SAVEDATA_OP_LIST_DELETE (and the unimplemented import/export functions)
- This caused the 'delete savedata' menu entry in Bonk's Adventure to be inaccessible since we always returned an error no matter the arguments.
- Additionally, the game uses an asterisk as prefix to load the savedata list, which is actually a valid thing to do based on the disassembly for this exact function (and maybe others?). I only report the savedata for the current title ID for now though, since I fear I'll accidentally delete some other savedata.

cellSaveData: some list delete fixes

---

rpcs3/Emu/Cell/Modules/cellPhotoDecode.cpp
rpcs3/Emu/Cell/Modules/cellPhotoImport.cpp
rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
rpcs3/Input/sdl_pad_handler.cpp

- Allows decoding images located in /dev_hdd1
- Fixes some comments and logging issues
Fixes #14744

cellPhotoDecodeFromFile: Allow decoding files located in /dev_hdd1

---

rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp
rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.h

sys_net: fix some warnings

---

azure-pipelines.yml

Should fix https://github.com/RPCS3/rpcs3/issues/14741

Switch official AppImage deployment to clang

---

rpcs3/Emu/Io/RB3MidiGuitar.cpp
rpcs3/Emu/Io/RB3MidiKeyboard.cpp
rpcs3/rpcs3qt/midi_creator.cpp

Midi: improve error handling

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/util/serialization.hpp

No longer a mysterious pause after "Linking PPU Modules", also allow to close the emulator quickly in this stage.

PPU Progress Dialog: Add "Applying PPU Code" stage

---

rpcs3/Emu/RSX/Core/RSXIOMap.hpp
rpcs3/Emu/RSX/Core/RSXReservationLock.hpp

Unnest some unnecessarily nested code. I rewrote these while working on a different issue where I wanted to add notification events to the RSX reservations but that experiment was not as successful as I had hoped. Instead, I'll commit the code quality improvements by themselves.

rsx: Minor code cleanup

---

.ci/deploy-windows.sh
.ci/setup-windows.sh
.cirrus.yml
3rdparty/glslang/glslang.vcxproj
BUILDING.md
azure-pipelines.yml
rpcs3/rpcs3qt/curl_handle.cpp

- Updates Vulkan to 1.3.268.0
- Updates FAudio to [23.12](https://github.com/FNA-XNA/FAudio/releases/tag/23.12)
- Updates curl to [8.5.0](https://github.com/curl/curl/releases/tag/curl-8_5_0)
- Windows: Use native CA store instead of deploying cacert.pem

Update Vulkan to 1.3.268.0

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

- Improve error handling of rap files. Maybe helps debugging #14899

sceNpDrm: improve error handling of rap files

---

BUILDING.md

Some information on which version of VS 2019 and above is required in order to successfully build the solution. I spent too long bashing my head and this should save some time for some people.

Docs: Add clarifications regarding Visual Studio 2019 version requirements.

---

.ci/deploy-mac.sh

macOS CI: fix missing libjxl_cms.0.9.dylib

---

rpcs3/Emu/Cell/Modules/cellPad.cpp

cellPad LDD fixup

---

.ci/build-mac.sh
.ci/deploy-mac.sh

macOS CI: downgrade ffmpeg

---

rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp

Related to: https://github.com/RPCS3/rpcs3/issues/14210

Warn on use of privileged port on Linux

---

rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/np_notifications.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/15013

Fix sceNpBasicSetPresence when data is nullptr and size is 0

---

rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/np_handler.h
rpcs3/Emu/NP/rpcn_client.cpp
rpcs3/Emu/NP/rpcn_client.h
rpcs3/rpcs3qt/sendmessage_dialog_frame.cpp

Also fixes a bug where the data associated with the message was never given out to the application.

Impl sceNpBasicSendMessage

---

rpcs3/Emu/Cell/Modules/sceNp2.cpp

- Adds missing argument check for roomSlotInfo
- Adds missing nullptr check for withPassword
- Removes the error checks for assignedReqId and uses simple nullptr checks instead

Improve SceNpMatching error checks

---

rpcs3/Emu/Cell/Modules/cellFont.cpp
rpcs3/Emu/Cell/Modules/cellFont.h
rpcs3/Emu/Cell/Modules/cellFontFT.cpp

- Stub cellFont
- Adds some more error handling and more insights to cellFont

cellFont: stubs

---

Utilities/File.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h

- Fixes a regression from the "portable" changes
Fixes #15071

Fix broken executable directory path

---

.ci/build-linux.sh
3rdparty/discord-rpc/CMakeLists.txt

Fixes https://github.com/RPCS3/rpcs3/issues/13519.

Enable Discord presence on Linux

---

rpcs3/Emu/Cell/Modules/sceNpCommerce2.cpp

Jojo ASB gets confused otherwise.

Mini sceNpCommerce2Init fix

---

rpcs3/Emu/Cell/Modules/sceNpTus.cpp
rpcs3/Emu/Cell/lv2/sys_usbd.cpp

Now that TUS is implemented some games waited forever to get a response to TSS apis. We now return that there is no file.
Fixes Jojo Eyes Of Heaven.

Return no file to TSS apis

---

rpcs3/util/asm.hpp

Fixes https://github.com/RPCS3/rpcs3/issues/15100

Fix Apple clang

---

rpcs3/Emu/Cell/Modules/sceNpCommerce2.cpp
rpcs3/Emu/Cell/Modules/sceNpCommerce2.h
rpcs3/Emu/NP/np_handler.h

- Add a bunch of error checks to sceNpCommerce2

sceNpCommerce2: add some error checks

---

rpcs3/Emu/Cell/Modules/sceNpCommerce2.cpp

Hopefully fixes https://github.com/RPCS3/rpcs3/issues/15113.

Fix sceNpCommerce2 init

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp

Some games attempt to create /dev_hdd0/cache.dat and /dev_hdd0/cache.idx (the paths are hardcoded in the executable). If this doesn't fail they use the file in an unthreaded unsynced manner between 2 threads which can lead to a corrupted cache.dat. On real hardware this file creation results in a CELL_EACCES error(tested through sys_fs_open syscall directly) and the file doesn't get created(and the games work fine). 
Affects(all using the same engine):
-Rampage World Tour(NPUB30003)
-Mortal Kombat 2(NPUB30004)
-Joust(NPUB30005)
-Gauntlet 2(NPUB30006)
-Championship sprint(NPUB30007)
-Rampart(NPUB30008)
Fixes https://github.com/RPCS3/rpcs3/issues/14860 and probably https://github.com/RPCS3/rpcs3/issues/15017.

Restrict file creation in /dev_hdd0

---

BUILDING.md

Update CMake requirements in BUILDING.md

---

rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/update_manager.cpp

It also disables the updater for ARM builds in general.
Fixes https://github.com/RPCS3/rpcs3/issues/15199.

Disable updates for local builds

---

rpcs3/Emu/Cell/SPULLVMRecompiler.cpp

- After some testing the full sequence on real ps3 it seems that frest => fi => fnms => fma sequence will differ from 1/x in 2 ways:
Infinite on x86 becomes NaN(with sign respected) on ps3
NaN on x86 becomes Zero(with no sign) on ps3
Fixed the code to reflect it.
- Added the 'one' value as a parameter to the intrinsic(might make it easier to add intrinsic for other special values if any is found.)
- fixed 2 messed up patterns(checked a for both fnms and frest, oops).
- Removed 2 useless if checks that predates the xfloat merging PR from ages ago.
- on re_accurate, erased all the stores(might lead to some regressions, I tried a bunch of games and they all seemed fine).
- Fixed full fm(a, re_accurate) pattern with the same pattern as 1/x(as 0 * value => 0 and nan * value => nan).
- Since …

Improve re_accurate

---

rpcs3/Emu/Cell/SPULLVMRecompiler.cpp

This shortcut creates issues in LBP 1, reverting for now.

[bugfix] Revert FM(a*re_accurate) shortcut to relaxed

---

rpcs3/Input/raw_mouse_handler.cpp
rpcs3/Input/raw_mouse_handler.h

- This should help keeping the relative mouse at the old position on window size change

raw_mouse: adjust relative mouse position if the window size changed

---

rpcs3/Emu/RSX/VK/vkutils/device.cpp

Ref: https://github.com/RPCS3/rpcs3/issues/15131

vk: Move driver properties to properties section from features section

---

rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/midi_creator.cpp
rpcs3/rpcs3qt/midi_creator.h
rpcs3/rpcs3qt/pad_device_info.h
rpcs3/rpcs3qt/pad_motion_settings_dialog.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/pad_settings_dialog.h

- Fix the localization of the midi_creator strings by adding the Q_OBJECT macro
- Localize the default pad names used in the conventional pad handlers
Fixes #15218

Fix some localization issues

---

rpcs3/rpcs3qt/main_window.cpp

Updates the latest FW version according to: [playstation.com/en-us/support/hardware/ps3/system-software](https://www.playstation.com/en-us/support/hardware/ps3/system-software/) List of changes:
This system software update improves system performance.

Misc: Update FW Latest Version

---

rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/rpcn_client.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/15253

Send initial presence for offline friends

---

rpcs3/util/init_mutex.hpp

init_mutex.hpp: Fixup

---

Utilities/Thread.cpp
rpcs3/main.cpp
rpcs3/util/init_mutex.hpp

* Fixes a segfault in init_mutex.hpp and add missing callback.
* Add more debug info for PPU hard crashes inside syscalls/HLE.

More fixes

---

rpcs3/Emu/Cell/lv2/lv2.cpp

Based on findings from @RipleyTom 
Would probably fix the issues for all CPUs.

LV2: Much longer thread creation delay for low prio threads

---

rpcs3/Emu/NP/np_handler.h
rpcs3/Emu/NP/np_requests.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/15191.

Fix sceNpScoreGetRankingByNpId

---

rpcs3/rpcs3qt/save_manager_dialog.cpp
rpcs3/rpcs3qt/save_manager_dialog.h

Qt: add search bar to save manager

---

rpcs3/Emu/Cell/Modules/cellMic.cpp
rpcs3/Emu/Cell/Modules/cellMic.h

- Add nullptr check for data ptr in cell_mic_read
- Also rename S to Size for readability
probably fixes #15336

cellMic: fix access violation in cellMicRead

---

rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp

Extremely important typo fix

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/main.cpp
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_settings.h

Make it more similar to how SPU does this. Hopefully it would improve performance.

PPU/reservations: send thread notification only if data changed

---

rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/system_config.cpp
rpcs3/Emu/system_config.h

- Displays a nice name in PlayLink Singstar Mic app:
| Before  | After |
| --- | --- |
|<img src="https://github.com/RPCS3/rpcs3/assets/2995486/260f8995-77cf-4f35-a33e-4879140d8d53" width="300"/>|<img src="https://github.com/RPCS3/rpcs3/assets/2995486/4f00c20a-b7d7-438a-a45d-37ce1a4435b2" width="300"/>|

Set a unique System Name

---

rpcs3/Emu/System.cpp

Fix typo in System.cpp

---

rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
rpcs3/Emu/savestate_utils.cpp

- various improvements in cellSysutilAvc2

cellSysutilAvc2: improve unload and some more stuff

---

rpcs3/Emu/CMakeLists.txt
rpcs3/main.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/util/console.cpp
rpcs3/util/console.h

Moves messy console attachment code to another file.

Move freopen to console.h

---

rpcs3/Emu/Cell/SPULLVMRecompiler.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/15178
Hopefully doesn't break anything :D.

Clamp spu_fi results

---

Utilities/File.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/savestate_utils.cpp
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/main_window.cpp

Fixes regressions from #15515 and #15549

Savestates: Fixup file write

---

rpcs3/Emu/RSX/GL/GLTexture.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/15588

gl: Handle GCM_FORMAT_G8B8 readback compatibility check

---

rpcs3/Emu/Io/GunCon3.cpp

Thanks @Florin9doi for pointing this out.
I hope it works again.

Fix GunCon3 encoding

---

3rdparty/curl/libcurl.vcxproj
3rdparty/curl/libcurl.vcxproj.filters

Update curl to [8.8.0](https://github.com/curl/curl/releases/tag/curl-8_8_0)

Update curl to 8.8.0

---

rpcs3/Emu/RSX/Common/buffer_stream.hpp
rpcs3/Emu/savestate_utils.cpp
rpcs3/rpcs3qt/main_window.cpp

Thanks to InsertJey from discord for reporting https://discord.com/channels/272035812277878785/861435507967262740/1246508314343510159

Unix/Savestates: Fix savestates destination

---

rpcs3/Emu/RSX/GL/GLProgramBuffer.h
rpcs3/Emu/RSX/Program/CgBinaryFragmentProgram.cpp
rpcs3/Emu/RSX/Program/CgBinaryProgram.h
rpcs3/Emu/RSX/Program/CgBinaryVertexProgram.cpp
rpcs3/Emu/RSX/Program/RSXFragmentProgram.h
rpcs3/Emu/RSX/Program/ShaderParam.h
rpcs3/Emu/RSX/Program/VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/Program/program_util.cpp
rpcs3/Emu/RSX/Program/program_util.h
rpcs3/Emu/system_progress.hpp

- Catch potential out of bounds in VertexProgram
- Fix some warnings
- Make some functions and params const

RSX: Fix some warnings

---

rpcs3/rpcs3qt/shortcut_utils.cpp

- Improve error logging when shortcut creation fails
Maybe helps to figure out #15631

Qt: log error cause on shortcut icon creation

---

rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/Modules/sceNp2.cpp
rpcs3/Emu/Cell/Modules/sceNpCommerce2.cpp
rpcs3/Emu/NP/np_cache.cpp
rpcs3/Emu/NP/np_structs_extra.cpp
rpcs3/Emu/NP/rpcn_client.cpp

- Don't print array elements if the array pointer is null
- Add some sceNp array pointer checks
- Add some rpcn array pointer checks (I get the feeling these should return an error instead)
Maybe fixes #15689

sceNp: add some array pointer checks

---

rpcs3/Emu/RSX/Common/simple_array.hpp

Oops.
Fixes https://github.com/RPCS3/rpcs3/issues/15412
Fixes https://github.com/RPCS3/rpcs3/issues/15682

rsx: Fix simple_array<T>::map

---

rpcs3/Emu/Memory/vm_ptr.h

- add nullptr deref audits for ->, * and [] operators

vm_ptr: add some nullptr deref audits

---

rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp

Potential fix for https://github.com/RPCS3/rpcs3/issues/15575

Fix race in sys_net select and poll

---

rpcs3/Input/sdl_pad_handler.cpp

- Only init and quit SDL once
maybe fixes #14753

input: try to fix macOS SDL crash

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

Seems like that is what matches with PS3 performance, hopefully SingStar still works.
Fixes #14571

Cut scenNpDrmIsAvailable time by half

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Io/RB3MidiDrums.cpp
rpcs3/Emu/Io/RB3MidiDrums.h
rpcs3/Emu/Io/mouse_config.cpp
rpcs3/Emu/Io/mouse_config.h
rpcs3/Emu/Io/rb3drums_config.cpp
rpcs3/Emu/Io/rb3drums_config.h
rpcs3/Input/basic_mouse_handler.cpp
rpcs3/Input/basic_mouse_handler.h
rpcs3/Input/raw_mouse_config.cpp
rpcs3/Input/raw_mouse_config.h
rpcs3/Input/raw_mouse_handler.cpp
rpcs3/Input/raw_mouse_handler.h
rpcs3/rpcs3qt/skylander_dialog.cpp

- allow to change midi drum combos and overrides during runtime (you probably have to open the config window and save it after manually changing them)
- allow to change basic mouse config during runtime
- allow to change raw mouse config during runtime
- actually check buttons 6, 7 and 8 in raw mouse handler

Allow to change more input configs during runtime

---

rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureMSAAOps.glsl
rpcs3/Emu/RSX/Program/GLSLSnippets/RSXProg/RSXFragmentTextureMSAAOpsInternal.glsl

Fixes crashing in some games using MSAA.
Closes https://github.com/RPCS3/rpcs3/issues/15751

rsx: Fix codegen when depth-conversion is enabled

---

rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Input/ds3_pad_handler.cpp
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/dualsense_pad_handler.cpp
rpcs3/Input/hid_pad_handler.cpp
rpcs3/Input/hid_pad_handler.h
rpcs3/Input/skateboard_pad_handler.cpp

- implement cellGemEnableMagnetometer2
- implement HidDevice::close for later usage

cellGem: implement cellGemEnableMagnetometer2

---

rpcs3/rpcs3.vcxproj

- Fix some visual studio filters for some debug moc files

Fix some visual studio filters

---

rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/rpcs3qt/qt_camera_video_sink.cpp

- Use interleaved RGBA format and get rid of BE/LE differences.
- Fixes CELL_CAMERA_RAW8 format conversion in cellGem (this fixes Beat Sketcher camera image colors)
- Refactor out cellGem conversion function for further usage
- Silences "cellGem: Converted video frame of format..." log message
This may be a bit slower by adding one QImage converion, but it ensures that all camera formats are converted properly.
Tested with camera formats JPG, NV12 and YUV and the target formats RAW8 and RGBA.

cellGem: fix camera format conversions

---

rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/NP/np_handler.cpp
rpcs3/Emu/NP/np_helpers.cpp
rpcs3/Emu/NP/np_helpers.h

There is no data associated with this event, `size` is not supposed to be set.
Makes the Asian version of  `Gran Turismo HD Concept` (`NPHA00001`) boot when RPCN connection is active.

Do not set the data size in sceNpBasicGetEvent for SCE_NP_BASIC_EVENT_OFFLINE

---

rpcs3/rpcs3qt/dimensions_dialog.cpp
rpcs3/rpcs3qt/dimensions_dialog.h
rpcs3/rpcs3qt/infinity_dialog.cpp
rpcs3/rpcs3qt/skylander_dialog.cpp

- Improve dimensions dialog layout and allow to make it smaller
- Sort figures in dropdown alphabetically
- Use std::move when filling the dropdowns (theoretically faster, but not noticeable)

Improve dimensions dialog

---

rpcs3/rpcs3qt/game_compatibility.h
rpcs3/rpcs3qt/game_list_base.cpp
rpcs3/rpcs3qt/gs_frame.cpp
rpcs3/rpcs3qt/pad_led_settings_dialog.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/qt_utils.h
rpcs3/rpcs3qt/richtext_item_delegate.h
rpcs3/rpcs3qt/rpcn_settings_dialog.cpp
rpcs3/rpcs3qt/rpcn_settings_dialog.h

Add icons to RPCN friend status circles
Fixes #15467

Add icons to RPCN friend status circles

---

rpcs3/Emu/RSX/VK/vkutils/device.cpp

Closes https://github.com/RPCS3/rpcs3/issues/15768

vk: Fix crash on VEGA M GH chips

---

Utilities/StrFmt.cpp
rpcs3/util/types.hpp

types.hpp: Add argument formatter to assert errors

---

rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/util/media_utils.cpp

- Fixes ticks_per_frame deprecation warning
- Fixes interlaced_frame deprecation warning
- Fixes frame_number deprecation warning

Fix ffmpeg deprecation warnings

---

rpcs3/CMakeLists.txt
rpcs3/main.cpp
rpcs3/module_verifier.cpp
rpcs3/module_verifier.hpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters

Run platform sanity checks after creating the log and log windows path.
Maybe helps to find the problem with #15846

Run platform sanity checks after creating the log and log windows path

---

rpcs3/CMakeLists.txt
rpcs3/Emu/RSX/VK/vkutils/instance.hpp
rpcs3/rpcs3qt/gs_frame.cpp

Always include native wayland support when possible.
Closes https://github.com/RPCS3/rpcs3/issues/15866

Improved wayland support

---

rpcs3/rpcs3qt/save_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

- Allows to delete a game's trophy directory in the context menu of the trophy manager
fixes #15840

Qt/trophies: allow to delete a game's trophy directory

---

rpcs3/module_verifier.cpp

Closes https://github.com/RPCS3/rpcs3/issues/15846

Case-insensitive path compare for module verifier

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp

- Fixes a new warning ('initializing': conversion from 'const u64' to 'const u32', possible loss of data)
- Refactor pad preview updates to reduce duplicate code

Fix warning / Refactor some UI code

---

rpcs3/Emu/RSX/NV47/HW/nv3089.cpp

Closes https://github.com/RPCS3/rpcs3/issues/13253

rsx: Fix crash when CPU blit is enabled

---

rpcs3/Input/keyboard_pad_handler.cpp
rpcs3/Input/keyboard_pad_handler.h
rpcs3/rpcs3qt/pad_settings_dialog.cpp

Key combos are not really supported at the moment.
Fixes #15817

keyboard: only map single buttons

---

rpcs3/Emu/Cell/Modules/cellPad.cpp
rpcs3/Emu/Cell/Modules/sys_io_.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/14695

Fix sys_io thread deadlock

---

rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/CMakeLists.txt
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/vfs_tool_dialog.cpp
rpcs3/rpcs3qt/vfs_tool_dialog.h
rpcs3/rpcs3qt/vfs_tool_dialog.ui

- Updates 7zip to [24.08](https://github.com/ip7z/7zip/releases/tag/24.08)
- Implements a basic VFS tool dialog
fixes #9552

VFS tool dialog + 7zip 24.08

---

rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/RawSPUThread.cpp
rpcs3/Emu/Cell/SPUCommonRecompiler.cpp
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_frame.h
rpcs3/rpcs3qt/debugger_list.cpp
rpcs3/rpcs3qt/debugger_list.h
rpcs3/util/vm_native.cpp

Implement a tool that can load SPU code from any PS3 address and disassemble it.

Debugger/SPU: Implement SPU Disassembler

---

3rdparty/CMakeLists.txt
CMakeLists.txt
rpcs3/CMakeLists.txt
rpcs3/Emu/CMakeLists.txt

fixes https://github.com/RPCS3/rpcs3/issues/15938

cmake: fix EGL and add USE_SYSTEM_CURL

---

Utilities/Thread.cpp
rpcs3/Emu/CPU/Backends/AArch64/AArch64Signal.cpp
rpcs3/Emu/CPU/Backends/AArch64/AArch64Signal.h
rpcs3/Emu/CPU/CPUTranslator.cpp
rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/SPULLVMRecompiler.cpp

REd from darwin/xnu sources. Untested.
Also adds some better pass management code to make sure the JIT cleans up after itself.

aarch64: Support for apple exceptions

---

rpcs3/Emu/System.cpp

RSX: Fix RSX Captures

---

Utilities/JITASM.cpp
rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/GL/glutils/state_tracker.hpp
rpcs3/util/vm_native.cpp

- Fix OGL bug caused by typo in tracker enums. Fixes flickering shadows in some games.
- Silence some compiler warnings emitted by clang when compiling some RSX headers.
- Fix crash when booting games on MacOS native.
Closes https://github.com/RPCS3/rpcs3/issues/16002

Misc fixes

---

rpcs3/rpcs3qt/breakpoint_list.cpp
rpcs3/rpcs3qt/breakpoint_list.h
rpcs3/rpcs3qt/call_stack_list.cpp
rpcs3/rpcs3qt/call_stack_list.h
rpcs3/rpcs3qt/flow_widget.cpp
rpcs3/rpcs3qt/flow_widget.h
rpcs3/rpcs3qt/game_list.cpp
rpcs3/rpcs3qt/game_list.h
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/save_data_list_dialog.cpp
rpcs3/rpcs3qt/save_data_list_dialog.h
rpcs3/rpcs3qt/user_manager_dialog.cpp
rpcs3/rpcs3qt/user_manager_dialog.h
rpcs3/rpcs3qt/vfs_dialog_usb_tab.cpp
rpcs3/rpcs3qt/vfs_dialog_usb_tab.h

Qt: ignore double clicks unless they are left clicks

---

Utilities/Thread.cpp
Utilities/Thread.h
Utilities/stack_trace.cpp
rpcs3/CMakeLists.txt
rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/CPU/Backends/AArch64/AArch64Signal.h
rpcs3/Emu/CPU/sse2neon.h
rpcs3/util/sysinfo.cpp

Untested as the build doesn't run, but an important step nonetheless.

aarch64: Fix compilation for windows-on-arm (msys2)

---

rpcs3/Input/skateboard_pad_handler.cpp

changed support from ride dongle to ride + shred dongle

Add support for Tony Hawk: SHRED dongle

---

rpcs3/Emu/Cell/SPUCommonRecompiler.cpp

* Use pointer to stop implicitly dereferencing freed memory.
* Fix typo in next_block()
Fixes #16043

SPU Analayzer: Fix dereferencing freed reference

---

rpcs3/Emu/Cell/Modules/cellAtracXdec.cpp

cellAtracXdec: fix FFmpeg warning

---

rpcs3/Emu/Cell/SPUCommonRecompiler.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/16091

SPU Analyzer Hotfix

---

rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_frame.h

* Fix randomly thread got deselected when using the debugger. (regression)
* Fox old bugs related to RSX handling of the debugger.

Debugger: Fix thread-selection and refactoring

---

rpcs3/Input/hid_pad_handler.cpp
rpcs3/Input/sdl_pad_handler.cpp
rpcs3/rpcs3qt/debugger_frame.cpp

- Use singleton for hidapi init and exit
- Use singleton for SDL init and exit
- Update curl to [8.10.1](https://github.com/curl/curl/releases/tag/curl-8_10_1)
maybe fixes #16085

Use singleton for hidapi init and exit

---

Utilities/JITLLVM.cpp

Fixes GOW3 boot on apple silicon.

aarch64: Correctly implement the null function trap

---

rpcs3/rpcs3qt/auto_pause_settings_dialog.cpp
rpcs3/rpcs3qt/breakpoint_list.cpp
rpcs3/rpcs3qt/call_stack_list.cpp
rpcs3/rpcs3qt/camera_settings_dialog.cpp
rpcs3/rpcs3qt/input_dialog.cpp
rpcs3/rpcs3qt/log_frame.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/osk_dialog_frame.cpp
rpcs3/rpcs3qt/patch_creator_dialog.cpp
rpcs3/rpcs3qt/qt_camera_handler.cpp
rpcs3/rpcs3qt/save_data_info_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

- Tiny improvements to Cam/Mic permissions
- Remove some string conversion bloat

Qt: Remove some string conversion bloat

---

rpcs3/Input/keyboard_pad_handler.cpp
rpcs3/rpcs3qt/gs_frame.cpp
rpcs3/rpcs3qt/gs_frame.h
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_application.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/shortcut_dialog.ui
rpcs3/rpcs3qt/shortcut_handler.cpp
rpcs3/rpcs3qt/shortcut_handler.h
rpcs3/rpcs3qt/shortcut_settings.cpp
rpcs3/rpcs3qt/stylesheets.h

- Enable game window shortcut manager
This is now possible with Qt 6.7.3.
fixes #5681

Qt: Enable game window shortcut manager

---

rpcs3/Emu/VFS.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/vfs_tool_dialog.cpp

Fix crash on VFS Tool + minor cleanup (on naming convention on my previous PR).
Bug and root cause of the bug found by @oltolm
fixes #16084

Fix crash on VFS Tool

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

Accidental leftover from before RE.

Fix scenp_score_record_score param check

---

rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_settings.cpp
rpcs3/Emu/RSX/Overlays/HomeMenu/overlay_home_menu_settings.h
rpcs3/Emu/system_config_types.cpp

- Fix 120 fps frame limit
- Remove 14 from anisotropic filter in home menu

Fix 120 fps frame limit, remove 14 from anisotropic filter in home menu

---

.ci/build-linux.sh
.ci/deploy-linux-legacy.sh
3rdparty/llvm/CMakeLists.txt

Fixes https://github.com/RPCS3/rpcs3/issues/16158

Move x64 appimage builder to its own legacy script

---

rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/Cell/Modules/cellAudio.h

This is not really a deep fix(as that'd require me understanding the logic behind the buffering floating period :D) but it fixes buffering here.
Needs testing on windows to make sure I didn't break anything.
Fixes https://github.com/RPCS3/rpcs3/issues/13310

Fixes audio buffering on non-windows platforms

---

rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/main.cpp
rpcs3/util/logs.cpp

- Improve log file creation error message
- Early out in file_writer ctor instead of large if else
- Fix some new warnings in sys_memory
Fixes #16203

Improve log file creation error message

---

rpcs3/Emu/Cell/SPUThread.cpp

* Release thread semaphore upon successful SPURS Idle state setting, wait for semaphore before supposed SPURS task acquire.

[TESTERS NEEDED] SPU: Reimplement SPURS limiter

---

rpcs3/util/sysinfo.cpp

All the error possibilities of the TSC calibration are caused by that the TSC read and the time read are not done atomically.
This can be solved easily by mimicking an atomic operation that restarts if values do not match what's expected before and after the operation.
Iterate a few times until TSC difference of the before timer value query is the smallest, instead of using many samples which may contain errors and averaging them out. (so basically, pick the best sample instead of doing an average of all)
Also fix a theoretical division by zero bug.

utils/sysinfo.cpp: New TSC calibration technique 

---

rpcs3/Emu/Cell/lv2/sys_event_flag.cpp

Atomic operation is a volatile function, the slightest change in atomic variable's value causes the entire operation to restart.
Therefore in most cases, atomic operations are implemented to be executed fast so other threads won't have time to change the value before the operation succeeds,
In sys_event_flag_set however, the operation was relatively long and bulky, other threads such as by calling flag_wait or flag_trywait, could have easily break the operation and causing it to restart unjust.
So, now only if the bits of waiters that were using AND mask were resetted, the operation would restart.
This is a tiny-optimization.

sys_event_flag_set: Break atomic operation dependencies

---

rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/pad_motion_settings_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

fix deprecation warnings in Qt 6.8

---

rpcs3/util/sysinfo.cpp

Seems to reduce significantly thread contention, even while launching from Visual Studio which adds much contention. Improving accuracy and reducing error range. We are in error range of few seconds per month now.

utils/sysinfo.cpp: Yield CPU time when measuring TSC freq

---

rpcs3/Emu/Cell/lv2/sys_event.cpp
rpcs3/Emu/Cell/lv2/sys_event.h

For a while I was not sure on what was purpose of the EBUSY, after all sending event is not expected to be a blocking call.
But, after looking at the disassembly it makes more sense, as this prevents port disconnection and destruction from being blocking calls, potentially waiting for a sleeping PPU thread with a low priority to release port handle reference after sending an event.
This only affects sending events from userbase PPU threads, as for RSX and SPU, system PPU threads with negative priority are used. 
This sort of optimization (thread-block avoidance) of the PS3 firmware is not implemented in other synchronization primitives, perhaps because event sending is done very frequantly as well as in LV1 and LV2 themselfs.

sys_event: Implement EBUSY for disconnection

---

BUILDING.md

Specify that Qt needs a "qtmultimedia" module and provide a link to an alternative download

Add more info about Qt in BUILDING.md

---

rpcs3/Emu/Cell/lv2/sys_event.cpp
rpcs3/Emu/Cell/lv2/sys_ss.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp

HLE GCM did not actually unmap memory.

RSX/GCM: Fix memory unmapping for HLE GCM

---

rpcs3/Emu/Cell/SPUCommonRecompiler.cpp

Was treating programs which are derivatives of others as equals.
Test with #16310

SPU Analyzer: Fix programs code caching

---

rpcs3/Emu/Cell/SPUCommonRecompiler.cpp

Will push more commits later. (std::basic_string_view was replaced with std::vector lol)

SPU: Fixup code comparison

---

3rdparty/curl/libcurl.vcxproj
3rdparty/curl/libcurl.vcxproj.filters
rpcs3/Emu/Memory/vm.cpp
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/dualsense_pad_handler.cpp
rpcs3/rpcs3qt/flow_layout.cpp
rpcs3/rpcs3qt/flow_layout.h
rpcs3/rpcs3qt/flow_widget.cpp
rpcs3/rpcs3qt/flow_widget.h
rpcs3/rpcs3qt/game_list_base.cpp
rpcs3/rpcs3qt/game_list_base.h
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/game_list_grid.cpp
rpcs3/rpcs3qt/game_list_grid.h
rpcs3/rpcs3qt/game_list_table.cpp
rpcs3/rpcs3qt/game_list_table.h
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/log_frame.cpp
rpcs3/rpcs3qt/log_frame.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.h
rpcs3/rpcs3qt/qt_utils.cpp
rpcs3/rpcs3qt/qt_utils.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.h
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

- Update curl to [8.11.0](https://github.com/curl/curl/releases/tag/curl-8_11_0)
- Replace some QMap with std::map

Update curl to 8.11.0

---

rpcs3/util/vm_native.cpp

It always inserted a new element each access.

util/vm_native.cpp: Fix memory leak

---

rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.cpp
rpcs3/Emu/Cell/lv2/sys_net/network_context.cpp
rpcs3/Emu/Cell/lv2/sys_net/network_context.h
rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp
rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.h

Fixes https://github.com/RPCS3/rpcs3/issues/16130

sys_net: Remove lingering ppu_to_awake from queue on timeout

---

rpcs3/Emu/CPU/CPUTranslator.cpp
rpcs3/Emu/Cell/SPULLVMRecompiler.cpp

LLVM: Implement Recursive Intrinsics

---

rpcs3/Emu/Cell/PPUModule.cpp

Some binaries have unset function addresses for exported functions. (perhaps defined but not declared in code)
This fixes YouTube [NPHB00509].

PRX: Do not check exported function code address

---

.ci/build-mac-arm64.sh
.ci/build-mac.sh
azure-pipelines.yml

Revert Qt to 6.7.3 for macOS

---

.ci/build-mac.sh

Forgot to comment out a line in the original Qt revert PR, silly me (the CI checks didn't catch it since there was a Qt cache hit).

Fixup Intel macOS builds

---

rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/16412

Fix unused p2p socket closing

---

rpcs3/rpcs3qt/flow_layout.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.h

Qt: fix flow_layout segfault and fix wrong settings dialog tab

---

rpcs3/Emu/Cell/Modules/cellGifDec.cpp
rpcs3/Emu/Cell/Modules/cellHttpUtil.cpp
rpcs3/Emu/Cell/Modules/cellJpgDec.cpp
rpcs3/Emu/Cell/lv2/sys_cond.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/IdManager.h
rpcs3/Input/ps_move_handler.h

Fix fs::file log formatting

---

rpcs3/Emu/IdManager.cpp
rpcs3/Emu/IdManager.h
rpcs3/rpcs3qt/category.h
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.ui

- Add Operating system category
- Fix some type warning

Qt: Add Operating system category

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/Cell/lv2/sys_sync.h

Implement operating system based LR memory signals, this should increase performance.
For testers: this pr is rebased before the build of #16466 at the moment, so use the build before for comparison.
Demon Souls (approx 16% FPS increase):
Without optimization (44.4 fps):
With optimization (51.6 fps):

[TESTERS NEEDED] SPU: Operating system LR memory signals

---

rpcs3/Emu/RSX/RSXThread.cpp

Closes https://github.com/RPCS3/rpcs3/issues/16443

rsx: Flush MM queue before memory is unmapped

---

rpcs3/Emu/Cell/lv2/sys_cond.cpp
rpcs3/Emu/Cell/lv2/sys_event.cpp
rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
rpcs3/Emu/Cell/lv2/sys_mutex.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_overlay.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Emu/IdManager.h

Fixes https://github.com/RPCS3/rpcs3/issues/16472
Makes savestates work.

Make IDM image serialization consistent

---

Utilities/Thread.h
rpcs3/Emu/Cell/lv2/sys_config.cpp
rpcs3/Emu/Cell/lv2/sys_config.h
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.cpp
rpcs3/Emu/IdManager.h
rpcs3/util/fixed_typemap.hpp
rpcs3/util/shared_ptr.hpp

Make good use of the incredible powers of `stx::shared_ptr`.
Fixes https://github.com/RPCS3/rpcs3/issues/16465

Fix sys_config_unregister_service

---

Utilities/cheat_info.h
rpcs3/rpcs3qt/cheat_manager.cpp

- Add float support to cheat manager (no idea if this works since I don't use it)
fixes #16204

cheats: add float32 gui support

---

Utilities/bin_patch.cpp
rpcs3/Emu/Cell/PPUThread.cpp

Fixes https://github.com/RPCS3/rpcs3/pull/16522#issuecomment-2575858929 (at least I believe so)

PPU LLVM: Fixup patches enlisting in analyzer

---

rpcs3/Emu/Cell/Modules/cellGem.cpp

- Add some (simplistic) camera image conversions:
RAW8 -> YUV444
RAW8 -> YUV422
RAW8 -> YUV411 (fixes camera image for "THE FIGHT: LIGHTS OUT™ - STRESSBUSTER DEMO")
RAW8 -> RGBA_320x240
RGBA -> YUV444
RGBA -> YUV422
RGBA -> YUV411
RGBA -> RGBA_320x240
One of those fixes camera input for "The Fight"

cellGem: Add more camera image conversions

---

rpcs3/Input/raw_mouse_config.cpp
rpcs3/Input/raw_mouse_config.h
rpcs3/Input/raw_mouse_handler.cpp
rpcs3/Input/raw_mouse_handler.h
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/raw_mouse_settings_dialog.cpp
rpcs3/rpcs3qt/raw_mouse_settings_dialog.h

- Allow to configure key presses in raw mouse handler

Qt/input: allow key presses in raw mouse handler

---

rpcs3/main.cpp

- Checks for OneDrive locations and shows an error if the emulator is installed there

windows: check for OneDrive paths

---

rpcs3/main.cpp

windows: Ignore OneDrive in PATH. It leads to false positives

---

rpcs3/Emu/Cell/Modules/cellGem.cpp

- This might fix the gun handler problems with savestates

cellGem: update gun handler connection periodically

---

rpcs3/Emu/System.cpp
rpcs3/Emu/savestate_utils.cpp
rpcs3/Emu/savestate_utils.hpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/main_window.ui
rpcs3/util/serialization_ext.hpp

- Adds a recent savestates menu similar to the recent games menu

Qt: Add Recent savestates menu

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/System.cpp

- don't close the game window on boot error before the rsx thread is finished
- fix some recently added warnings

Fix crash on missing fw

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/System.cpp

RSX was sending event too soon.

Fix Savestates recent regression

---

rpcs3/Emu/Cell/PPUThread.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/16646

arm64: Fix ppu_recompiler_fallback implementation for ARM processors

---

rpcs3/main.cpp
rpcs3/rpcs3qt/update_manager.cpp
rpcs3/util/cpu_stats.cpp
rpcs3/util/sysinfo.cpp
rpcs3/util/sysinfo.hpp

- Use v3 update api for all operating systems

update_manager: use v3 api for all OS

---

rpcs3/rpcs3qt/gs_frame.cpp

- ignore all game window hotkeys on "disable kb hotkeys"
I don't know why we had this on a per case basis.
Maybe someone remembers...

Qt: ignore all game window hotkeys on "disable kb hotkeys"

---

rpcs3/Emu/Cell/PPUAnalyser.cpp

Fix PRX block unfolding

---

3rdparty/curl/libcurl.vcxproj
3rdparty/curl/libcurl.vcxproj.filters

- Update curl to [8.12.0](https://github.com/curl/curl/releases/tag/curl-8_12_0)

Update curl to 8.12.0

---

rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/Modules/cellVdec.h

Fixes small game videos in VSH

cellVdec: implement cellVdecOpenExt

---

rpcs3/Emu/Cell/PPUAnalyser.cpp

Fixes https://github.com/RPCS3/rpcs3/pull/16644#issuecomment-2645480288

PPU Analyzer: Minor Fixup

---

rpcs3/rpcs3qt/main_window.cpp

linux/arm64: Enable auto-updater

---

rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/16705

Fix sendto for p2ps packets

---

rpcs3/Emu/Audio/XAudio2/XAudio2Backend.cpp
rpcs3/Emu/Audio/XAudio2/xaudio2_enumerator.cpp
rpcs3/Emu/CMakeLists.txt
rpcs3/Input/xinput_pad_handler.cpp
rpcs3/Input/xinput_pad_handler.h
rpcs3/rpcs3qt/shortcut_utils.cpp
rpcs3/util/dyn_lib.cpp
rpcs3/util/dyn_lib.hpp

I used Microsoft's smart pointer `ComPtr` where possible and I also used `dynamic_library` in XInput code. I also formatted XInput code and it's best to ignore white space when viewing the diff.

use Microsoft::WRL::ComPtr

---

.cirrus.yml
.github/workflows/rpcs3.yml
3rdparty/opencv/CMakeLists.txt
azure-pipelines.yml

Also updates the following linux packages:
ffmpeg 6.1.1->6.1.2
SDL 2.30.11->2.30.12
Qt 6.8.1->6.8.2
https://github.com/RPCS3/rpcs3-docker/commit/f63e7bee6a9238da70e2bdea2054faff8a4e2e37

Add opencv to linux CI and specify opencv modules

---

Utilities/cheat_info.cpp
Utilities/date_time.cpp
rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/RSX/GSFrameBase.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/display_sleep_control.cpp
rpcs3/display_sleep_control.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/headless_application.cpp
rpcs3/main.cpp
rpcs3/main_application.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/CMakeLists.txt
rpcs3/rpcs3qt/camera_settings_dialog.cpp
rpcs3/rpcs3qt/cheat_manager.cpp
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/gs_frame.cpp
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/permissions.cpp
rpcs3/rpcs3qt/permissions.h
rpcs3/rpcs3qt/qt_camera_handler.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/util/emu_utils.cpp

- Move cheat_type fmt to cheat_info.cpp
- Move check_microphone_permissions to emu callbacks
- Move display sleep functions to emu callbacks
- Move is_input_allowed to GSFrameBase
- Move sys_time fmt to date_time.cpp
- Move debugger functions to emu_utils.cpp

Move more code to emucore

---

.github/workflows/rpcs3.yml

github actions: rename jobs

---

rpcs3/Emu/Cell/Modules/cellMic.cpp
rpcs3/rpcs3qt/microphone_creator.cpp

- Fix potential division by 0 in cellMic
- Log all microphones in the settings dialog

Tiny microphone fix

---

rpcs3/rpcs3qt/main_window.cpp

Fixes: https://github.com/RPCS3/rpcs3/issues/16783

Qt: Fix boot failed dialog

---

rpcs3/Emu/RSX/Overlays/FriendsList/overlay_friends_list_dialog.cpp
rpcs3/Emu/RSX/Overlays/Trophies/overlay_trophy_list_dialog.cpp

- fix friends list input on paused emulation
- fix trophy list input on paused emulation

overlays: fix friends/trophy list input on paused emulation

---

CMakeLists.txt
rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/Emu/Memory/vm.h
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/CMakeLists.txt
rpcs3/rpcs3qt/breakpoint_handler.cpp
rpcs3/rpcs3qt/breakpoint_handler.h
rpcs3/rpcs3qt/breakpoint_list.cpp
rpcs3/rpcs3qt/breakpoint_list.h
rpcs3/rpcs3qt/debugger_add_bp_window.cpp
rpcs3/rpcs3qt/debugger_add_bp_window.h
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_frame.h
rpcs3/rpcs3qt/debugger_list.cpp
rpcs3/rpcs3qt/debugger_list.h

For hackers.
Edited, -DHAS_MEMORY_BREAKPOINTS=ON needs to be added for the option to be available within the UI.

Memory breakpoints

---

rpcs3/Emu/RSX/RSXFIFO.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/16831

rsx: Fix boundary seek logic for FIFO addresses

---

rpcs3/Emu/Cell/SPULLVMRecompiler.cpp
rpcs3/Emu/Cell/lv2/sys_time.cpp
rpcs3/Emu/Cell/lv2/sys_time.h

Fixes [#14923](https://github.com/RPCS3/rpcs3/issues/14923)

SPU LLVM: Subtract Timebase from decrementer

---

rpcs3/Emu/RSX/NV47/HW/nv308a.cpp
rpcs3/Emu/RSX/NV47/HW/nv4097.cpp
rpcs3/Emu/RSX/RSXFIFO.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/16839

rsx: Handle out-of-bounds read/writes from FIFO register IO

---

rpcs3/Emu/NP/rpcn_client.cpp
rpcs3/Input/gui_pad_thread.cpp
rpcs3/Input/gui_pad_thread.h
rpcs3/rpcs3qt/config_checker.cpp

- Use named_thread in gui_pad_thread (fixes some log error)

Use named_thread in gui_pad_thread

---

.github/workflows/rpcs3.yml
README.md

- Fix azure build tag link
- Use master branch for cirrus build tag
- Add GitHub Actions build tag
Fixes #16858

Readme: Improve build tags

---

rpcs3/rpcs3qt/about_dialog.cpp
rpcs3/rpcs3qt/about_dialog.ui
rpcs3/rpcs3qt/cheat_manager.cpp
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/dimensions_dialog.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/log_frame.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/memory_viewer_panel.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/pkg_install_dialog.cpp

- Fix "handler not found" issue in pad settings after changing language
- Fix multiple dialogs during batch shortcut creation
- Remove and fix some translations
- Removed supporters from translations
fixes #16893

Qt: Misc Fixes

---

buildfiles/msvc/rpcs3_release.props

- VS/MSVC: Enable LTCG and GL on release builds
No idea if this works.
May improve performance

VS/MSVC: Enable LTCG and GL on release builds ( LTO )

---

rpcs3/Emu/RSX/Overlays/FriendsList/overlay_friends_list_dialog.cpp

- overlays/rpcn: Create list even if rpcn connection failed
related to #16918

overlays: Fix some minor friend list issues

---

rpcs3/Emu/Cell/Modules/cellMic.cpp

- cellMic: log ALCenum error string

cellMic: log ALCenum error string

---

rpcs3/Emu/system_config.h

Hitting frame limits on certain test cases, need to raise this limit, 9800X3D go brr

config: Increase max vblank rate to 6000

---

rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/Emu/system_utils.cpp
rpcs3/Emu/system_utils.hpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/main_window.cpp

Loader: deny boot if the firmware is too old

---

.github/workflows/rpcs3.yml
azure-pipelines.yml

See https://github.com/RPCS3/rpcs3-docker/commit/0b55bbfa62ce9a59024e5653dafd708905ed6906 for details

Update Linux Qt to 6.8.3 and update clang compiler

---

Utilities/JITLLVM.cpp

While here, removed llvm::StringRef::data() as C string usages

LLVM JIT: do not produce broken binaries on crash

---

3rdparty/discord-rpc/CMakeLists.txt

Fix discord after #16885

---

rpcs3/rpcs3qt/update_manager.cpp

- Windows: fix updating with unicode user name (use InFile_OpenW)
- Use WRes_to_string function for logging
Fixes #16938

Windows: fix updating with unicode user name

---

rpcs3/Emu/Cell/PPUTranslator.cpp

ppu: Remove redundant checks on MTFSF

---

rpcs3/Input/evdev_joystick_handler.cpp
rpcs3/Input/evdev_joystick_handler.h

- Logs the evdev positive axis config
- May help with debugging

evdev: log positive axis config

---

rpcs3/Input/evdev_joystick_handler.h

Menu key is used by 8bitdo pro 2 controller.

Add Menu Key

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/VK/vkutils/device.cpp
rpcs3/util/types.hpp

Closes https://github.com/RPCS3/rpcs3/issues/17064
Closes https://github.com/RPCS3/rpcs3/issues/17067

vk: Forgotten improvements fixup

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

Demon's Souls trophy initialization shows progress correctly now.
Should fix #17055 too

Fix sceNpTrophyRegisterContext

---

Utilities/bin_patch.cpp
rpcs3/Emu/Cell/Modules/cellMusic.cpp
rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/CMakeLists.txt
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/music_player_dialog.cpp
rpcs3/rpcs3qt/music_player_dialog.h
rpcs3/rpcs3qt/music_player_dialog.ui
rpcs3/rpcs3qt/qt_music_handler.cpp
rpcs3/rpcs3qt/qt_music_handler.h

- Add more and improved logging to cellMusic
- Implement music player utility for testing
This reveals a bug in the QMediaPlayer.
When opening a mp3 file and pressing play, nothing happens.
The audio only starts playing when pressing stop first.
Sadly, this also happens in the Qt media player example.
We'll have to wait until they fix it properly.

Implement music player utility for testing

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/Modules/cellDaisy.cpp
rpcs3/Emu/Cell/Modules/cellGifDec.cpp
rpcs3/Emu/Cell/Modules/cellJpgDec.cpp
rpcs3/Emu/Cell/Modules/cellPngDec.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp
rpcs3/Emu/Cell/Modules/cellVideoOut.cpp
rpcs3/Emu/Cell/Modules/libsnd3.cpp
rpcs3/Emu/Cell/Modules/sys_lv2dbg.cpp
rpcs3/Emu/Cell/Modules/sys_net_.cpp
rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
rpcs3/Emu/Io/usb_device.cpp
rpcs3/Emu/RSX/Common/simple_array.hpp
rpcs3/Emu/RSX/VK/vkutils/commands.h
rpcs3/Emu/RSX/VK/vkutils/graphics_pipeline_state.hpp
rpcs3/Emu/RSX/VK/vkutils/shared.cpp
rpcs3/util/types.hpp

- Remove some obsolete warning pragmas

Remove some obsolete warning pragmas

---

rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Loader/ELF.h

SPU Image Finder Fixes

---

rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
rpcs3/Emu/Cell/Modules/cellVideoOut.cpp

- Fix error checks in cellVideoOutConvertCursorColor
- Implement the conversion
This doesn't do anything yet, since the rsx side of the cursor doesn't seem to be implemented

cellVideoOutConvertCursorColor: fix and implement

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/Common/simple_array.hpp
rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
rpcs3/Emu/RSX/VK/VKDraw.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp

https://godbolt.org/z/4745MGT6z

rsx: Misc fixes

---

rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
rpcs3/util/vm_native.cpp

Fix sys_mmapper_unmap_shared_memory

---

.ci/build-freebsd.sh
.ci/build-linux-aarch64.sh
.ci/build-linux.sh
.github/workflows/rpcs3.yml
buildfiles/msvc/rpcs3_default.props
rpcs3/VKGSRender.vcxproj
rpcs3/rpcs3.vcxproj

- Visual Studio: remove some outdated keywords
- Visual Studio: fix some relative 3rdparty paths
- Avoid checking out unused submodules
- Use existing env variables instead of hardcoded paths for mounting the docker artifacts dir

Build improvements (in preparation of unit tests)

---

.cirrus.yml
.github/workflows/rpcs3.yml
azure-pipelines.yml

Update linux docker to 1.6

---

rpcs3/Emu/Io/LogitechG27.cpp
rpcs3/Emu/Io/LogitechG27.h

- TODO note and adjust type for housing SDL_CreateHapticEffect return
- fix implementation of command 0x09 Set LED
- fix LED joystick changes handling

Logitech G27 touchups

---

rpcs3/Emu/RSX/VK/vkutils/device.cpp
rpcs3/Emu/RSX/VK/vkutils/device.h

Closes https://github.com/RPCS3/rpcs3/issues/17121

vk: Disable texel buffer update-after-bind on NVIDIA driver for pre-RTX cards

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h

Fixup SPU Interpreters

---

rpcs3/Emu/System.cpp

* lower timeout for waiting for sysutil callback to be read to 1 second.
* Each time some PPU threads exit during the termination process after sysutil signal was read, grant additional 250 milseconds for the termination process,
* Add check for sys_process_exit when tracking termination progress.

Emu: Track game termination progress better

---

rpcs3/Emu/System.cpp

It's not actually a bug, rather, a logging issue.

System: Fix Kill calling duplication

---

rpcs3/Input/sdl_pad_handler.cpp
rpcs3/Input/sdl_pad_handler.h

SDL/input: Log GUID

---

.gitmodules
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/RSX/VK/VKMemAlloc.cpp
rpcs3/Emu/RSX/VK/vkutils/device.cpp
rpcs3/Emu/RSX/VK/vkutils/memory.cpp
rpcs3/Emu/RSX/VK/vkutils/memory.h

- Updates VulkanMemoryAllocator to 3.3.0
closes #16923 with thanks to @Xphalnos 
Fixes #13045

Update VulkanMemoryAllocator to 3.3.0

---

rpcs3/Input/ds4_pad_handler.cpp

- Update hidapi to [0.15.0](https://github.com/libusb/hidapi/releases/tag/hidapi-0.15.0)
- Adds support for newer CMake versions.
- Adds some bugfixes (even one I submitted myself, but I don't remember what it actually fixed 🏋️ )
- Adds a bunch of new features that we probably don't need

Update hidapi to 0.15.0

---

rpcs3/Emu/NP/rpcn_client.cpp

WWE SmackDown vs. RAW 2009 was putting external bin attributes in the searchable bin attribute list resulting in validation errors on RPCN side. We now sort the bin attributes client side.

Sort bin attributes based on ID

---

.github/workflows/rpcs3.yml

Fix Mac upload hash

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

Minor change, we don't support entitlements atm.

Entitlements are never found

---

rpcs3/Input/hid_pad_handler.cpp

hid/input: fix enumerated device comparison

---

rpcs3/rpcs3.vcxproj

Fixes compilation with paths that contain spaces

VS: add quotes around paths

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_event.cpp

* Batch SPU thread notifications.

SPU/LV2: Notify SPU events after mutex guards' unlocking

---

rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/SPULLVMRecompiler.cpp

use `CreatePtrAdd` instead of `CreateGEP(get_type<u8>(), ...)` or `CreateIntToPtr(CreateAdd, CreatePtrToInt(...))`

llvm: use CreatePtrAdd

---

rpcs3/Emu/Cell/SPUThread.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/17428

SPU: Update RdEventStat Busy Wait detection to updated setting behavior

---

rpcs3/Emu/Io/pad_types.cpp
rpcs3/Emu/system_config.h
rpcs3/rpcs3qt/emu_settings_type.h
rpcs3/rpcs3qt/gs_frame.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/tooltips.h
rpcs3/util/video_provider.cpp

- Add setting to disable screenshot and recording overlay hints
fixes #17438

overlays: add setting for screenshot and recording hints

---

.ci/build-mac-arm64.sh
.ci/build-mac.sh
.github/workflows/rpcs3.yml
BUILDING.md

- Update Qt to [6.9.2](https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/6.9.2/release-note.md)

Update Qt to 6.9.2

---

rpcs3/Emu/Cell/SPUCommonRecompiler.cpp

Continuation of #17514 for SPU code.

Win32/SPU: Respect home space / shadow space on the stack frame

---

rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp

Fixes Sonic The Hedgehog missing graphics patch.
Fixes #16686
Maybe Fixes #17248

PPU LLVM: Filter out functions with patches

---

Utilities/Config.cpp
Utilities/Config.h
Utilities/StrUtil.h

Intended to be used for #17543

Config: Implement 128-bit setting entry type
