RPCS3/rpcs3

rpcs3/Emu/RSX/GL/GLGSRender.cpp
This fixes the opengl error 0x506 for some games like "Family Game Night 3"
=> RSX: create depth buffer only when required

rpcs3/Emu/RSX/RSXThread.cpp
Disabled as original , it somehow break The guided paradox in-game.
=> RSX disable front face

rpcs3/Emu/Cell/PPUDisAsm.h, rpcs3/Emu/Cell/PPUInstrTable.h, rpcs3/Emu/Cell/PPUInterpreter.h, rpcs3/Emu/Cell/PPULLVMRecompiler.cpp, rpcs3/Emu/Cell/PPULLVMRecompiler.h, rpcs3/Emu/Cell/PPUOpcodes.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h
These patches add all missing user-mode instructions to the PPU instruction decoder and interpreter, and fix various bugs in the existing instruction implementations. With these changes, the PPU interpreter passes all but 27 tests from http://achurch.org/cell-test/ppu.s (which has been validated against a real PS3); the failing tests require either floating-point inexact result detection or support for different floating-point rounding modes.
=> Implement missing and fix broken PPU instructions in the interpreter.

rpcs3/Emu/Cell/Common.h, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/SPUInterpreter.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h
These changes fix the SPU interpreter so it passes all tests from http://achurch.org/cell-test/spu.s (which has been validated against a real PS3). There may be more concise ways to write some of the floating-point logic, but there are just lots and lots of corner cases when handling SPU-style extended floating-point on an IEEE-compliant processor.
=> Fix SPU interpreter to match real hardware

Utilities/StrFmt.cpp, Utilities/StrFmt.h, rpcs3/Emu/SysCalls/Modules/cellGcmSys.cpp, rpcs3/Emu/SysCalls/lv2/cellFs.cpp
* replace_first and replace_all were in the wrong namespace, so they could not be linked
* replace_all did not work correctly (would loop indefinately)
* cellGcmUnmapIoAddress did not shif the size, so it would run past the end of the mmap array
* fsstat did use a 32-bit size on Windows, so files >4 gigs would return "stat failed"
=> Fix some small mistakes

rpcs3/Emu/CPU/CPUThreadManager.h, rpcs3/Gui/InterpreterDisAsm.cpp
This used to crash so it was removed. However I think this is a cruicial feature.
This is the only way to observe the stack-frames, registers and disasm around the PC
in a user friendly way.
The reason this caused crashes was that we got a reference to a std::vector and iterated
over it in one thread while another thread could modify it (and thereby invalidating the
iterators). The way I "fixed" it is to just copy the `std::vector<std::shared_ptr<...>>`
and iterate over the copy. This obviously has some overhead (locking the shared_ptr
counters and incrementing them). It also allows entities other than the Thread manager
to keep the Thread objects frome being deleted but that should not be a problem.
=> re-enable threadlist in GUI

rpcs3/CMakeLists.txt
This is needed by `shm_unlink` and similar functions. Fixes #997
=> Add librt to the list of linked libraries

rpcs3/Emu/SysCalls/lv2/sys_ppu_thread.cpp
I saw someone experience the issue of Assertion failed at `m_stack_size` in PPUThread.cpp which may be caused by the initial stack size or even the implementation of `sys_ppu_thread_create`. So i made it to round the requested size up to product of 4KB, even it was told to allocate 0B.
For the detailed issue and a test LLVM build of it, see [Here](http://www.emunewz.net/forum/showthread.php?tid=167481&pid=219885#pid219885). Hope this can solve the stack size problem.
*Note: If you want to test something, please take the file in the post and get the test.*
=> About ppu thread stacksize

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h
Intel HD graphics doesn't support EXT_depth_bounds_test .
=> Disable glDepthBoundsEXT for Intel HD graphics

rpcs3/Emu/SysCalls/lv2/sys_lwmutex.h
remove the publicly accessible version of the template parameter in lwmutex::const_be_u32_t because it's never used and causes linker errors in clang 3.4 (and allegedly gcc 4.8.4)
pertains to #1048 and #1050
=> remove lwmutex::const_be_u32_t::value

rpcs3/Emu/FS/VFS.cpp, rpcs3/Gui/MainFrame.cpp, rpcs3/Ini.h
Duang! OK the settings for EmulationDir has already done. Hope this solves #972.
`$(EmulationDir)` is where rpcs3 thinks `dev_hdd0`,`dev_flash` and others are, also it determines where the PKGs' content is installed. Though there is still somewhere to be improved, it works now.
To use the feature, you would have to make such changes:
* Make sure that the version you used have this feature. If not you may try build it yourself.
* Open Emulator Setting turn to System(Panel) there would be a `Checkbox` and a `TextCtrl`.
* Fill where you would like the `$(EmulationDir)` to be into the `TextCtrl`, and tick on the `Checkbox`.
* Close rpcs3 and open it again. It should take effects now.
If you assigned a path which it can not access, or path not exists, or is not a directory, **it would …
=> Custom EmulationDir

.travis.yml, README.md, Utilities/git-version-gen.cmd
Modified `.travis.yml` to ensure rpcs3 is built dueing the Travis build.
Fix the master git repo name in Github, also the one in `git-version-gen.cmd`.
Display Shell Export List to help debugging our Travis Build.
All the commits merged into one, original in #1051.
Since i know little about it, only `cpp-coverall` added which is useful for `coveralls.io`.
After open this pull i would close the old one and delete the old branch.
Github sometimes reject your push just cause you merged those. lol.
=> Travis Enabled.

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Gui/MainFrame.cpp, rpcs3/Ini.h
This is for rsx branch .Read/ write depth and color buffers are now always on and required to turn on for accuracy
=> Obsolete read/write depth and color buffers options

rpcs3/Emu/FS/VFS.cpp, rpcs3/Emu/System.cpp
For `GetDeviceLocal` only consider a device if the full path to the device
matches the first part of the path to match.
The issue was that putting in a file that was not in a sub-path of an existing
mounted device failed. So if the rpcs3 devices are in
D:\DEV\rpcs3\bin and you open D:\DEV\ps3autotests\tests\rsx\primitives\primitives.ppu.elf
it would return
/dev_usb000/ps3autotests\tests\rsx\primitives\primitives.ppu.elf
which resolves to
D:/DEV/rpcs3/bin/dev_usb000/ps3autotests/tests/rsx/primitives/primitives.ppu.elf
and is wrong.
Correct are either /dev_usb000/../../../ps3autotests\tests\rsx\primitives\primitives.ppu.elf
or /hostfs/D:\DEV\ps3autotests\tests\rsx\primitives\primitives.ppu.elf
I chose to resolve without the ".." beyond root, since that just seems wrong
(so it will now …
=> Change `GetDeviceLocal` device selection

rpcs3/Emu/SysCalls/Modules/cellGcmSys.cpp
We were sometimes using memory outside of buffer.
It fixes vertex attribute test.
=> sysGCM: Fix for getNextCommandBufferBeginEnd

.travis.yml
Due to this change: https://github.com/RPCS3/rpcs3/commit/de9a2fd556123a3bcde4752a9d419db045b10d00#commitcomment-12110160
=> Update travis to use gcc 4.9

.travis.yml
except ppu_recompiler (dead branch).
That way it's much easier to setup travis on forks without messing with master yml.
I see no reason to run travis on master only anyway.
Also enabled colorized output on gcc (like on travis). Should be easier to debug it now.
=> Enable travis-ci for all branches and colorize gcc output

.travis.yml, Utilities/StrFmt.h, rpcs3/Emu/Cell/PPUInterpreter.h, rpcs3/Emu/Cell/PPULLVMRecompiler.h, rpcs3/Emu/FS/vfsDevice.h, rpcs3/Emu/SysCalls/Modules/cellRtc.cpp, rpcs3/Emu/SysCalls/Modules/cellVpost.cpp, rpcs3/Emu/SysCalls/Modules/sceNpSns.cpp, rpcs3/Gui/KernelExplorer.cpp
I think that `StrFmt.h` didn't work because of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431
(though I'm not sure this is the one, I came across similar bugs that may be the cause).
Because of that I had to disable this warning for whole project. I'm not 100% sure that `CXXFLAGS` appends and not replaces but it seems to do so.
Anyway, this PR get rids of majority of errors so travis logs are again convenient to read and useful to debug, yay :cake: !
=> Travis warning fixes

rpcs3/Emu/Cell/PPULLVMRecompiler.cpp, rpcs3/Emu/Cell/PPULLVMRecompiler.h, rpcs3/Gui/MainFrame.cpp, rpcs3/Ini.h
I used binary search to find the compiled block that breaks the music in Sonic CD, I think having an option in the UI to make this easier may benefit everyone working on llvm recompiler.
=> Add debug options for llvm compiler

rpcs3/Emu/Audio/XAudio2/XAudio2Thread.h, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12Overlay.cpp, rpcs3/Gui/MainFrame.cpp, rpcs3/Ini.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
This PR drastically reduces draw call cost making possible to enjoy 60 fps in Arkedo 2 for instance. The guided fate paradox is also near 60 fps (the cost is now in cell emulation).
It also add a D2D overlay to print text on top of the framebuffer. The overlay can be modified to display any text with a nice antialiased font. I use it to track cost of draw calls but it can be used for virtually any time measurement.
=> D3d12: Increase perf and add a d2d overlay

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
Fix a crash in Disgaea 3 with debug output enabled.
=> d3d12: Fix wrong index being used for sampler descriptor heap

Utilities/VirtualMemory.cpp, Utilities/VirtualMemory.h, rpcs3/Emu/Cell/PPULLVMRecompiler.cpp, rpcs3/Emu/Cell/PPULLVMRecompiler.h, rpcs3/Emu/Cell/PPULLVMRecompilerCore.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
This PR makes some a little clearer and also make it more efficient by avoiding uneeded indirection and by adding a big table.
=> Llvm36: Code fix and perf improvement

appveyor.yml
clone depth isn't very reliable for submodules. Still waiting for appveyor to update to 2.5.0 git.
=> Small appveyor fix

rpcs3/Emu/Cell/PPULLVMRecompiler.cpp, rpcs3/Emu/Cell/PPULLVMRecompiler.h, rpcs3/Emu/Cell/PPULLVMRecompilerCore.cpp, rpcs3/Emu/Cell/PPUThread.h
The first commit fixes Retro City Rampage. It basically wrap exec_ppu_func_by_index inside a function that catches CPUThreadExit exception, and it propagates it through return values to Decode function which can safely crash since there is no llvm code.
I tried to do a catch-all code with exception_ptr but it didn't work, I suspect support in VS 2015 is still not mature enough atm...
The 2nd, 4th and 5th commit increase performance of llvm recompiler. It allows to reach 60 fps in Retro City Rampage and Metal Slug 3, as long as llvm threshold is set to 10 (and that recompiler thread has recompiled every necessary block).
=> Llvm36: Fix and performance improvement

rpcs3/Emu/Cell/PPULLVMRecompiler.cpp
Likely a rebase error, with this Metal Slug can run at 60 fps again.
=> PPU/LLVM: Remove useless call to NotifyBlockStart

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
These fixes make easier to debug d3d12 commands and fix harem tengoku except for colors.
Others games are likely to be impacted.
=> D3d12: Fix for harem tengoku game.

rpcs3/Emu/Cell/PPULLVMRecompiler.cpp, rpcs3/Emu/Cell/PPULLVMRecompilerCore.cpp
Proof of concept. Seems to work fine.
There is rare chance that rpcs3 will hang on game exit in cpu thread destructor (in a loop with g_thread_count or something) but I'm not sure it's related.
=> PPU/LLVM: Fix for most of the remaining crashes on exit with jit

rpcs3/Gui/GameViewer.cpp
Game Data is not on PS3_GAMES folder, it is obligatory in the 
e.g. :
>BLES01585/USRDIR 
is the same as for HDD Games.
This is the same as it is for the DLC and updated.
=> Little fix correct path for Game Data

.travis.yml, rpcs3/stdafx.h
About the bump (from the commit message):
As it has been a long time since the last version bump, it would make sense to bump the version. ~~0.0.6 more specifically, since Zangetsu already did that and it was tagged and has already been linked on quite a few websites.~~ It probably doesn't matter and 0.0.1 would make more sense.
I would like @DHrpcs3 to confirm if this is OK and if the version bump is problematic, then I can remove that commit, so only the Coverity Scan fix remains.
=> Fix Coverity and bump the version.

Utilities/StrFmt.cpp, Utilities/StrFmt.h, Utilities/config_context.cpp, Utilities/config_context.h, Utilities/convert.h, Utilities/event.h, rpcs3/CMakeLists.txt, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/events.cpp, rpcs3/Emu/events.h, rpcs3/Emu/state.cpp, rpcs3/Emu/state.h, rpcs3/Gui/SettingsDialog.cpp, rpcs3/Gui/SettingsDialog.h, rpcs3/Ini.h, rpcs3/config.cpp, rpcs3/config.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
New config system allow make config files for specific game
=> Implemented new config system. Minor improvements

rpcs3/Emu/SysCalls/Modules/cellSaveData.cpp
Fixes The Awakened Fate: Ultimatum and probably a couple other games, which were reported with save data problems on the forums.
Thanks to @B1ackDaemon for providing a lead necessary for developing the fix.
=> Fix a save data access violation

Utilities/types.h, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.h, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.h, rpcs3/Emu/RSX/RSXTexture.cpp, rpcs3/Emu/RSX/RSXTexture.h, rpcs3/Emu/RSX/RSXThread.h
This PR avoid an extra copy of index buffers. It also makes several fixes in Braid, which is still not playable but at least doesn't crash.
=> D3d12: Perf and compat improvements

.travis.yml
It should be at least 2.8.12
Fixes travis build errors on linux (it failed to manually install it from cmake.org).
Removed aria2 package since we don't need it anymore.
=> Install cmake from packages

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
This PR factorise the d3d12 code that write constants data to buffer into rsx::thread.
A future PR will make GL use these new members. It's a first step to get more code shared between backends, I intend to do that very slowly to ensure as little regression as possible.
=> Rsx: Factorise d3d12 constant loading code

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/D3D12/D3D12Utils.cpp, rpcs3/Emu/RSX/D3D12/D3D12Utils.h
This PR moves some code from D3D12GSRender.cpp to D3D12RenderTargets.cpp and do the usual cleaning there (a_b_c format, anonymous namespace...)
=> d3d12: Clean rtt related code

rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/GCM.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Gui/Debugger.cpp, rpcs3/Gui/RSXDebugger.cpp, rpcs3/Gui/RSXDebugger.h
This PR add a function that prints readable dump for commands.
It also adds infrastructure that records per frame (ie between 2 successive flip() calls) commands and for each clear and draw/drawindexed command, it stores the render targets, depth and stencil contents.
The command lists and command buffers can be displayed in RSXDebugger.
Currently only dx12 is supported, I will implement the GL part later as part of gl refactoring work.
To use it, run a game/app/.. and hit "capture frame" (the run/pause, stop, restart tab may need to be widened). The game will stop. Then go into RSXDebugger.
=> Rsx debug: Record per frame draw calls.

.gitignore, Utilities/File.cpp, Utilities/VirtualMemory.cpp, Utilities/VirtualMemory.h, Utilities/rPlatform.cpp, rpcs3/Crypto/lz.cpp, rpcs3/Crypto/unedat.cpp, rpcs3/Crypto/unpkg.cpp, rpcs3/Crypto/unself.cpp, rpcs3/Crypto/utils.cpp, rpcs3/Emu/HDD/HDD.cpp, rpcs3/Emu/HDD/HDD.h, rpcs3/Emu/Io/MouseHandler.h, rpcs3/Emu/Memory/MemoryBlock.h, rpcs3/Emu/RSX/CgBinaryVertexProgram.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/SysCalls/Modules/cellFs.cpp, rpcs3/Emu/SysCalls/Modules/cellNetCtl.cpp, rpcs3/Emu/SysCalls/Modules/cellResc.cpp, rpcs3/Emu/SysCalls/Modules/cellSail.cpp, rpcs3/Emu/SysCalls/Modules/cellSysutil.cpp, rpcs3/Emu/System.cpp, rpcs3/Gui/AutoPauseManager.cpp, rpcs3/Gui/GSFrame.h, rpcs3/Gui/MainFrame.cpp
Includes a few memory corruption bugs fixed, added initialization for a couple variables, fixed some flow control problems and added error checks and error logging to a lot of places.
HDD functions now also return a negative version, if they fail seeking. Didn't add any checks for when they're actually used, but if we'd want to be more or less correct, we should check for errors from those functions in the future.
=> Lots of defect fixes

rpcs3/Emu/Io/KeyboardHandler.h, rpcs3/Emu/Io/MouseHandler.h
It started occurring recently though the problem seems to be old.
Only KeyboardHandlerBase is the fix, the MouseHandler one is to be safe.
Emu crashed on exit on https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/System.cpp#L472 in dice elf test
=> Fix crash on exit in some tests

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12Overlay.cpp, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
This PR fixes coding style in D3D12GSRender.h (which hold all member declarations). It should make the D3D12GSRender code follows the code conventions adopted in rpcs3 (maybe some bits are still left there and there).
=> d3d12: Use a_b_c style for D3D12GSRender.h members

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h
This PR moves the parsing function outside of the Decompile() one which a bit more understandable.
It then adds the DIVSQ opcode to SCB which fixes a lot of glitches in SH3 HD.
=> Rsx: Fix fragment decompiler

README.md, rpcs3/CMakeLists.txt
And change coverity badge to shields.io since coverity uses insecure ssl certificate and because of that badge is not shown in newer browsers.
=> Some dependency info updated

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/SysCalls/Modules/cellUserInfo.cpp, rpcs3/Emu/SysCalls/Modules/cellUserInfo.h, rpcs3/Emu/SysCalls/lv2/sys_mmapper.cpp
This mainly should fix the nv3089_image_in regressions brought in by my last PR, which were reported in #1334 (Braid crash) and #1335 (Jet Set Radio textures)
This also adds a workaround fix for booting of Psl1ght v2 homebrew elf's, and a small fix for cellUserInfoGetStat
=> NV3089 and misc fixes

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
Fix intro cutscene in after burner climax (and likely in other places).
I tested OpenGL with the stencil reflect sample.
=> rsx/common/d3d12/gl: Use separate vertex array/vertex register states.

rpcs3/Emu/RSX/Common/ProgramStateCache.h
Comparaison was not taking the last instruction of shader into account.
Also remove "constant masking" since it wasn't actually usefull.
Fix DBZ: Burst Limits, SH3 and likely much more games.
=> rsx/common: Fix program state cache Shader program comparaison.

.gitmodules, .travis.yml, README.md, appveyor.yml, rpcs3-tests/rpcs3-tests.vcxproj, rpcs3/CMakeLists.txt, rpcs3/stdafx.h, rpcs3_default.props
See https://github.com/RPCS3/rpcs3/issues/1392 for more details.
The PR adds GSL project as a submodule and add it to stdafx.h for future use.
=> Add Guidelines Support Library

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp, rpcs3/Emu/RSX/D3D12/D3D12Formats.h, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/GCM.cpp, rpcs3/Emu/RSX/GCM.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/gl_helpers.cpp, rpcs3/Emu/RSX/GL/gl_helpers.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
Fix Wolf of the Battlefield 3.
Factor index handling code between GL and D3D12.
Both backend should behave moreless the same now when it comes to geometry.
Also improve code by using enum class and span to avoid overflow.
=> rsx/common/d3d12: Consider separate index range as a whole.

Utilities/GNU.h
Even non‐Apple platforms make malloc() available from stdlib.h, because that’s what the C standard requires.
=> By definition, malloc() is available in stdlib.h. malloc.h is deprecated.

rpcs3/Emu/RSX/D3D12/D3D12CommonDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
Fixes textureProj which fixes shadow in Naruto 2 (and probably in other games too).
Fix nullptr indirection detected by VS static analysis and dsv increment size which made Intel driver crash.
=> D3d12: Fixes

rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Gui/RSXDebugger.cpp, rpcs3/Gui/RSXDebugger.h
This PR improves reliability of rtt/ds capture. It supports all format and put code in the to-be-shared template struct.
Not all format can be displayed by RSXDebugger though.
=> rsx-debug/d3d12: Support all rtt formats.

rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
This PR forces depth output to use r1 register and not h2 even if "output from H0" flag is set.
(btw there's a typo in both backend, depth is never stored in h0, otherwise h0.z would be both a color and a depth).
In Naruto Shippuden 2 and in Resogun shader with depth outputs seems to use r1 and not h2 to export depth (the shader wouldn't make any sense otherwise). I don't rule out the possibility of h2 being used to export depth but at the moment I didn't spot any app/game that use such behavior.
=> d3d12/gl: Use r1 as depth output.

rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/RSXVertexProgram.h
This pr adds inputs and outputs for vertex program and take them into account when comparing them in program state cache. It shouldn't change anything but is necessary to support vertex attribute frequency.
=> rsx: Add vertex input and output in RSXVertexProgram.

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12MemoryHelpers.cpp, rpcs3/Emu/RSX/D3D12/D3D12MemoryHelpers.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.h, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.h
This PR uses IAInputLayout mechanism (GL's equivalent is VAO) and use vertex ID + texture1d holding vertex data in vertex shader instead.
This allows to support RSX instancing implementation which relies on vertex id arithmetic operation which is more flexible that GL/D3D instancing method.
This shouldn't bring any performance penalty however since under the hood modern GPU already load vertex data in vertex program this way.
Resogun menu is properly displayed with this PR.
=> D3d12: Drop IAInputLayout and use SV_VertexID + SRV instead

rpcs3/Emu/RSX/Common/BufferUtils.cpp
Outrun uses it and cars are correctly displayed.
=> rsx/common: Base offset is actually correctly supported.

rpcs3/Emu/RSX/CgBinaryProgram.h, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h
Currently RSXFragmentProgram hash/equality is based only on the fragment microcode. This means that ProgramStateCache ignores input changes. It mostly works since inputs (ie varying and texture) doesn't change that often but it's safer to check. Moreover the FragmentDecompiler can more safely rely on non microcode data like texture dimension or normalisation without relying on fits-them-all dynamic branched solution.
=> rsx/common: Make RSXFragmentProgram key and not just pointer.

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/RSXThread.cpp
This PR brings support for the shader window setting : now the "gl_Position" value will have correct vertical origin in d3d12 fragment shader. It fixes After Burner Climax heat effect but probably a lot more apps will benefit from the commit too.
The PR also uses "static" value in fragment shader for normalisation parameter, ie the backend won't fill a bool constant buffer to signal whether a sampler should read coordinate as texel value (instead of values between 0 and 1).
=> D3d12: Fix and improvement

rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp, rpcs3/Emu/RSX/GL/rsx_gl_texture.h
Implements swizzling for some texture formats. Fixes rendering glitches when using OGL backend in some games e.g Terraria. Removes references to malloc and free and replaces mem allocation with std::vector.
=> Rework OGL texture swizzles

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/gl_helpers.h
Fix for issue https://github.com/RPCS3/rpcs3/issues/1471
=> gl: Move program validation from link-time to draw-time to comply with spec

rpcs3/Emu/RSX/GL/GLGSRender.cpp
Fix build under Release-LLVM configuration where warnings are treated as errors
=> Fix LLVM build by changing variable to appropriate type

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp, rpcs3/Emu/RSX/GL/rsx_gl_texture.h
Emulate samplerRect in fragment shaders. Allows outrun to display correctly on screen.
Some glitches remain, but those are resolved by #1461
EDIT: I'm checking what fixes the odd view scaling. It works fine on one of my branches without #1461
=> gl: Support rectangle textures

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12CommonDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12CommonDecompiler.h, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLCommonDecompiler.cpp, rpcs3/Emu/RSX/GL/GLCommonDecompiler.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
This PR fixes lit and vertex shader rsq behavior with <= 0.0 inputs which fixes "blue gunfire" in After Burner Climax (I also added a max(, 1.E-10) for log2 as well just in case...).
It also add support for front face/back face color used by Outrun Online.
There's also a dirty bit added for every texture unit which is used to avoid rebinding unchanged textures. It increases performance but the real purpose is to avoid doing depth buffer conversion twice if unnecessary (will happen with a future d3d12 PR).
=> Rsx: HLSL/GLSL fixes and support two side color.

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp
References to gl_Position in fragment shaders is illegal. Use gl_FragCoord instead.
=> Fragment position is given as gl_FragCoord not gl_Position

rpcs3/Emu/RSX/RSXTexture.cpp
Texture pitch and depth are fetched from the registers without indexing, causing all texture layers to contain info for texture layer 0. Thanks to @jarveson for pointing out the problem.
Should fix issue https://github.com/RPCS3/rpcs3/issues/1495
=> Correctly fetch correct pitch and depth for textures from RSX

rpcs3/Emu/RSX/GL/GLGSRender.cpp
Program constants are quite small in size, generally less than 32k. Using glBufferSubData is faster by about an order of magnitude which is a significant speedup in games which issue a lot of draw calls.
=> gl: Speed up program constants upload by switching to glBufferSubData

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp, rpcs3/emucore.vcxproj
* get_placed_texture_storage_size returns more accurate result (fix crash in Outrun)
* Factors lot of code and use integer type more carrefully
* Treat warning as error in TextureUtils.cpp
=> rsx/common/d3d12/gl: Use gsl::span in TextureUtils.cpp

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.h, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/D3D12/D3D12Utils.h
Only small adjustement in this PR. I'm making some experiments with dx12 binding model and I found using a single "expanded" root signature is slightly more efficient.
=> D3d12: Tweak root signature and improves HRESULT message

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
This allows backend not to update transform constant buffers when unnecessary.
=> rsx/common: Track transform constant update.

rpcs3/Emu/RSX/Common/TextureUtils.cpp
Properly handle swizzled single-channel textures. Should fix instructions page for PixelJunk Eden as well as solving a crash when uploading swizzled B8 textures.
=> Handle swizzled CELL_GCM_B8 textures

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/D3D12/D3D12Utils.cpp
This PR adds some small improvement to the backend : The first commit avoid unnecessary vertex constant upload, the second use descriptor copies instead of recreating them each draw call, and the last remove a couple of unneeded processing which was almost never used.
I didn't notice performance improvement but adopting good practice doesn't hurt, especially since the descriptor tweak is a first step into caching descriptors as well as the texture they point to which could save ~0.8 ms in some demanding scenario.
=> D3d12: Tweaks

rpcs3-tests/ps3-rsx-common.cpp, rpcs3-tests/rpcs3-tests.vcxproj, rpcs3-tests/rpcs3-tests.vcxproj.filters, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/GCM.cpp, rpcs3/Emu/RSX/GCM.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXVertexProgram.h
This PR fixes integer format support for vertex attributes, namely ub256 and s32k.
It actually fixes the upload callback in rsx and types d3d12 vertex shader input (as it looks like Buffer<float4> is not reading integer value at all).
Not sure if gl requires a fix though since TextureBuffer are not typed.
SSA is fragment shader semantic for front facing boolean value and is also supported with this PR on both gl and dx12.
Burgertime World Tour should work up to the menu. It displays a black screen although the scene is rendered (but uncorrectly lit) according to RSXDebugger.
=> Rsx: Vertex attribute format fixes + ssa variable support

rpcs3/Emu/RSX/GL/GLCommonDecompiler.cpp
The lod parameter is a single float. Fixes resogun throwing an exception before going ingame.
=> gl: The lod parameter in textureLod is a single float value

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/gl_helpers.h, rpcs3/Emu/RSX/GL/gl_render_targets.cpp, rpcs3/Emu/RSX/GL/gl_render_targets.h, rpcs3/Emu/RSX/GL/gl_texture_cache.h, rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp, rpcs3/GLGSRender.vcxproj, rpcs3/GLGSRender.vcxproj.filters
Update surface cache optimization to master; minor fixes
This updates the original PR by vlj. It still gives precedence to data obtained through read/write buffers, but at least its not mandatory to force it. True frame-by-frame read/write buffers is broken right now on GL anyway, since buffers are not invalidated on read access just yet. I'll wait for a game that actually uses the feature so that I can work on it properly.
=> gl: Use shared surface store (updated)

rpcs3/Emu/RSX/Common/surface_store.h
Texture block size = pitch*height not pitch*width (unless I misunderstood the use here). Should fix crashing the rsx debugger when capturing frames that i noticed under opengl after the surface cache was added.
=> rsx: Properly compute texture size for download

rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/RSXThread.cpp
This PR fixes fog in After Burner Climax by setting linear mode as default ; it also split fog distance and fog fraction in the fog input declaration.
=> Rsx: Fix fog (Fixes #1535)

Utilities/File.cpp
Should fix instant crash on Linux systems.
Thanks @Ivonasek.
=> Fix directory opening on Linux systems (Fixes #1494)

rpcs3/Emu/RSX/Common/TextureUtils.cpp
Support DRGB formats that should be similar to their ARGB counterparts. Also added G8B8 format to the other 16-bit block formats. Should fix some issues with games that throw "wrong texture format"
=> rsx: support for more formats

rpcs3/Emu/RSX/VK/VKFormats.cpp, rpcs3/Emu/RSX/VK/VKFormats.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/VKGSRender.vcxproj, rpcs3/VKGSRender.vcxproj.filters
Radeon cards don't support d24_unorm_s8 format for depth stencil buffer.
With DX12/OGL the driver emulates with 2 buffers (a d32 for depth and a r8 for stencil) but on Vulkan it's up to the app to query for format support.
This commit makes Vulkan backend uses d24_u8 format if supported, otherwise it uses d32_u8.
Unfortunatly the later case is less accurate wrt RSX emulation but hopefully it won't matter in practice.
There's also a commit that make debug output option respect the setting in the settings menu.
=> Vulkan: Uses d24_s8 or d32_s8 depending on availability.

rpcs3/config.h
Sets the value for W/R C/D buffers in the config to false by default as they aren't needed for any game the emulator currently runs and they seem to be broken afaik
=> Set Write/Read Color/Depth Buffers to false by default

rpcs3/Emu/RSX/VK/VKGSRender.cpp
Fog is enabled in the fragment shaders. Failing to set fog params properly causes severe graphics corruption in some games. Should fix hitman 2 rendering in vulkan.
=> vk: Re-enable fog parameters for vulkan

rpcs3/Gui/GLGSFrame.cpp
Should fix issue #1567 when using updated wxwidgets codebase.
=> gl: Explicitly declare context attributes for GL canvas

rpcs3/Gui/SettingsDialog.cpp, rpcs3/config.h
Hotfix for #1584
In the settings window, if another value isn't appended before Vulkan, the emulator will try to use DX12 when set to Vulkan in the Settings window
In W10: Null, OpenGL, DirectX 12, Vulkan
Not in W10: Null, OpenGL, Vulkan
When DirectX 12 is missing and Vulkan is set, the emulator tries to run DirectX 12. As is isn't compatible with the host OS, it crashed the emulator with an unhandled exception.
=> Fixes #1584 (Vulkan not being usable in non-w10 systems)

rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp
Should fix shader generation on vulkan for textureLod calls. This was fixed previously on GL.
=> vk: Indexing into mipmap lod is scalar not vector

rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
This PR uses a common descriptor layout for all shader.
Binding 0 is for scale offset buffer, 1 for vertex constant buffer, 2 for fragment constant buffer,
3 to 18 for vertex buffer, and 19 to 34 to texture buffer.
A common descriptor allow to avoid rebinding descriptors when not necessary. It's also closer to these low level APIs philosophy too.
=> Vulkan: Use a common descriptor layout for all program

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
This PR creates all possible render pass combinaison (it sounds like a lot but there's actually 120 combinaisons possible : there's 2 (+ 1 for disabled) depth format and 8 color format, and there can be between 0 and 4 color format enabled.
It also moves descriptor set storage/creation/... in VKGSRender instead of program which avoid recreating them each time a program is used.
As a side effect https://github.com/RPCS3/rpcs3/issues/1581 seems to be fixed although I need confirmation.
=> Vulkan: Avoid recreating render pass and descriptor set

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
The null_buffer and null_buffer view are kept.
Also added a alloc_and_copy to replace sub_data call.
=> vulkan: Remove buffer_deprecated completly.

README.md
* CMakeLists errors finding zlib library
* build-essential does not include clang or cmake, added (gcc is of course)
=> Add missing build deps to readme

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/surface_store.h
This PR changes some private into protected and make TextureUtils interpret dst_pitch as a multiplicity constraints instead of an alignment one (which is stricter).
=> Rsx: Slight interface changes.

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/gl_helpers.cpp
This PR makes gl uses the same codepath as DX12 and Vulkan renderer for indexing.
Indexing doesn't use deprecated QUADS or POLYGON mode.
This should allow the backend to use core context.
=> gl: Expand index for quads/quad_strip/triangle_fan

rpcs3/Emu/RSX/VK/VKFormats.cpp, rpcs3/Emu/RSX/VK/VKFormats.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
This PR uses a new struct, image, holding texture data.
It may fix https://github.com/RPCS3/rpcs3/issues/1597 (on my computer it does). The backend uses a staging texture everytime so the limitation on linear tiling are less important.
It fixes the green hue in Hitman 2 opening credits too.
=> vulkan: Use simpler image object

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/GL/gl_render_targets.h
Fix repeating shadows due to incorrect sampling mode. https://github.com/RPCS3/rpcs3/issues/1568
Index winding for quad strips was broken, but somehow worked on NV (DX12) for some reason. Should fix quad strip emulation for AMD gpus, both AMD and NVIDIA. Vulkan did not enable culling, hence verts are rendered even with incorrect winding.
=> gl: Fix RTT clamp mode; Fix vertex winding for emulated QUAD_STRIP triangles

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
This PR clean framebuffer after flip (the change slipped from a previous PR) and flush texture cache only at flip, not inside a draw call.
=> Vulkan: Fix some cleaning behavior.

rpcs3.sln, zlib.props
Cherry-picked from @DHrpcs3  branch. Fixed build for me.
=> Fixed build for MSVC (DH)

.gitmodules, 3rdparty/XAudio2_7/XAudio2.h, 3rdparty/XAudio2_7/audiodefs.h, 3rdparty/XAudio2_7/comdecl.h, 3rdparty/XAudio2_7/dxsdkver.h, 3rdparty/XAudio2_7/xma2defs.h, appveyor.yml, rpcs3/CMakeLists.txt, rpcs3/Emu/Audio/XAudio2/XAudio2Thread.h, rpcs3/XAudio.vcxproj, rpcs3/rpcs3.vcxproj
Removes minidx9 as a submodule
Slims down minidx9 in order to only keep the files XAudio2 (2.7) needs. The other dx9 related files weren't being used.
~~Don't merge yet as requested by Nekotekina.~~
=> Slims down minidx9 to keep XAudio2_7 files only

.travis.yml
To cut down on warning noise (6500+ -> ~1800 lines in travis clang build). We don't use it anywhere afaik (and newer sha with fixed warnings has conflicts with rpcs3).
=> Don't build rsx_program_decompiler

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
Avoid sampler descriptor being stored on 2 heaps inside a single draw
call. Fix somes crashes.
=> d3d12: Move sampler DescriptorHeap selection in D3D12GSRender

rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
This PR adds cube and 1D/3D texture support. Also a small fix to avoid mapping empty buffer (which makes debug output less verbose).
This makes After Burner Climax and Silent Hill 3 playable.
=> Vulkan: Supports cubemap and 1D/3D texture.

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/gl_helpers.cpp, rpcs3/Emu/RSX/GL/gl_helpers.h, rpcs3/Emu/RSX/GL/gl_render_targets.cpp, rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp
glBlitFramebuffer needs to be directed to the right buffer to read pixels from in case we arent drawing to the first attachment (COLOR_ATTACHMENT0).
Should fix black screens when using OpenGL https://github.com/RPCS3/rpcs3/issues/1658
glShadeModel and GL_CLAMP are deprecated in core.
The index used to enable MRT blending is zero based in core according to debug validation for both AMD and NVIDIA
=> gl: Specify buffer to read for blitting during flip; Remove some deprecated gl from core

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/ring_buffer_helper.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12MemoryHelpers.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/GL/vertex_buffer.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
This PR is mostly cleaning and refactoring code.
It factorizes data_heap which was used in both d3d12 and vulkan and modifies some utility function prototype in order to allow an upcoming PR to share vertex upload code between backends.
=> Rsx/common: Some factorisation

Utilities/rXml.cpp, Utilities/rXml.h, rpcs3/CMakeLists.txt
=> rXml: use pugixml in header-only mode

rpcs3/Emu/RSX/GL/vertex_buffer.cpp
Looks like a typo from https://github.com/RPCS3/rpcs3/commit/3a3d264cb506febff60409ed5176207e8cb6f856 was causing the crash.
I'm currently unable to compile due to master build being broken with VS, but this should fix #1667 (and #1666).
=> Speculative fix for OpenGL crash

rpcs3/Emu/Cell/Modules/libmixer.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/RSX/rsx_utils.h
…library header of the same name. This replaces the old macros by function calls when building with GCC 6 or greater.
If this is not the proper coding style I am happy to change it accordingly.
=> Replace math macros by function calls from cmath.

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
Those functions only supports GLSL but not DX12 and Vulkan
target fix : https://github.com/RPCS3/rpcs3/issues/1422
=> Use native function for OP_CODE_PK2 and UP2

rpcs3/Emu/RSX/GL/GLProgramBuffer.h, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
Just keep it simple instead of just writing them as .txt or .vert/frag which difficult to identify from renderer.
=> GL/Vulkan: write shader program log as .glsl and .spirv

.travis.yml
Trusty has good enough clang (3.5) to build rpcs3, as fo llvm:
we don't use it currently and travis fails due to: http://lists.llvm.org/pipermail/llvm-dev/2016-May/100303.html so just remove it for now.
=> Remove some llvm packages from travis CI and switch to ubuntu 14.04

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
Enable software alpha testing in shaders for both opengl and vulkan. Should fix some opengl regressions since the fixed function pipeline was removed including the glEnable(GL_ALPHA_TEST) calls.
=> vk/gl: Enable alpha test in shaders

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12CommonDecompiler.cpp
Properly implements PK and UP operations for program decompilers.
I'm assuming that PKB operates on values between 0-255 unnormalized hence the divide and multiply.
For DX12, PK16 is definately not conformant, but should work fine if the corresponding unpack is used. For the others, the pack/unpack functions are part of the glsl spec.
=> gl/vk/dx12: re-implement pack/unpack operations

rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp
Please see the inline comment . This make some games (like Outrun Arcade) go more further when hits {rsx::thread} Exception: Invalid or unsupported blend alpha factor (0x8001)
=> DX12 : add remaining constant color/alpha blending

CMakeLists.txt, README.md, rpcs3/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellPngDec.cpp
Provides two options when building RPCS3
- **USE_SYSTEM_FFMPEG** BOOL (default: OFF)
- **USE_SYSTEM_LIBPNG** BOOL (default: OFF)
These options lets the user select between the system provided and builtin libraries of ffmpeg and libpng to overcome possible system issues.
Also adds support for older libpng releases if the user doesn't have libpng 1.5 or higher when building with ```USE_SYSTEM_LIBPNG```.
---
This PR continues #1825 and has some minor improvements.
=> Add optimal build options to CMakeLists

rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp
This fixes the Disgaea 3 startup error in D3D12
=> DX12: depth buffer compare perform only if depth testing is enabled

rpcs3/Gui/MainFrame.cpp, rpcs3/Gui/MainFrame.h
Adds a new menu to **Tools** called **Decrypt &LLE modules** which opens a dialog to select multiple ```*.sprx``` files, which are than decrypted all at once.
This speeds up the LLE module decryption and saves users a lot of time and headache :smile: 
--
=> GUI: Add bulk decryption of LLE modules

rpcs3/Gui/SettingsDialog.cpp, rpcs3/Gui/SettingsDialog.h
Sorts the libraries in the settings dialog alphabetically, so they are easier to find.
Sorts selected and unselected modules alphabetically seperatly.
Also adds a search box, finally. :smile: 
EDIT: The per game config was removed from this PR.
--
This code makes sure that all the libraries are always sorted in alphabetically order on all operating systems and filesystems.
--
=> GUI: improve prx library selection

rpcs3/CMakeLists.txt, rpcs3/cmake_modules/ConfigureCompiler.cmake
Moves the compiler check out of ```rpcs3/CMakeLists.txt``` and adds them into ```rpcs3/cmake_modules/CheckCompiler.cmake```
Add better compiler checks and eliminate a TODO
Also fixes #1802 by telling the user GCC 6.1 is insufficient to build RPCS3.
=> CMake: improve compiler checks

rpcs3/Emu/RSX/GL/gl_helpers.h
Dump glsl source for shaders. All generated shaders are dumped to separate files in shaderlog directory. Should make it easier to debug broken shaders.
=> gl: dump shaderlog

rpcs3/Emu/RSX/GL/rsx_gl_cache.cpp
Some shaders only write to gl_FragDepth, and the write to col0 fails since its temp register is missing
=> glsl: not all shaders write to col0

rpcs3/Emu/RSX/RSXThread.cpp
Fix for shader access to variables stored in registers.
Fixes https://github.com/RPCS3/rpcs3/issues/1887
This implementation is hacky but I don't want to have to submit changes to the rsx_program_decompiler subproject just to fix a simple flag. It would be better to just have a separate flag that shows a variable is a register value and not an array.
=> gl: Fix register attribute access

rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
It somehow get removed for DX12 only (GL is okay) during rsx refactor . Now re-added back.
=> Ignore clear if surface target is set to CELL_GCM_SURFACE_TARGET_NONE

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/gl_helpers.cpp, rpcs3/Emu/RSX/GL/gl_helpers.h, rpcs3/Emu/RSX/GL/vertex_buffer.cpp
Fixes a few bugs
* Fix face winding when shader origin is flipped (thanks to DHRpcs3 for pointing this out)
* Reset texture coordinate scale in case the same shader was used with a different configuration before
* Native primitive formats vary between backends. (GL and vulkan support triangle fan in the driver while DX12 does not, vulkan does not support line loop)
=> gl: bug fixes

rpcs3/Emu/RSX/GL/GLGSRender.cpp
~~Fragment program constants are set in the shader code (from what I can gather) and are supposed to be true constants (unlike vertex shader constants which seem to change at times). When investigating issue https://github.com/RPCS3/rpcs3/issues/1906, I realized that the contents at the decompiled ucode_ptr address can change at runtime. I'm not sure why since I haven't had time to properly go through the new rsx cache and decompiler, but It becomes quite obvious that this is not supposed to be happening.~~
~~TL;DR This changeset only sets the fragment shader constants once when the program is first created and uses the data with subsequent use. I'll need advice here from members who have better understanding of the rsx internals.~~
This PR now sets the ucode_ptr to the correct location.
=> gl: Fix fragment constants streaming

rpcs3/Emu/Cell/Modules/cellGame.cpp
All the games I've been trying to load from outside RPCS3's bin directory are returning me empty categories
```
{PPU[0x3] Thread (main_thread) [0x011223d8]} class fmt::exception thrown: cellGameBootCheck(): Unknown CATEGORY: 
```
This is a hack for when the category is empty or unknown. 
We assume it's a disk game and proceed with the emulation, instead of throwing an exception.
=> cellGame: unknown category temporary fix (hack)

rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp
This PR introduces simple heuristics to try and get color blending working on d3d12. The idea is basic, but I'm making several assumptions here:
My assumption is that if a stage has its factor set to D3D12_BLEND_BLEND_FACTOR
1. The alpha component will be multiplied only by the alpha component of the blend factor
2. RGB components are only multiplied by the RGB components of the blend factor
3. The blend_blend_factor is in RGBA (0-1-2-3) format
I haven't coded for d3d in years, so if i'm wrong please feel free to correct me. Also, I may have messed up the heuristics so please double-check it if you understand it. Basically, it separates the blend factor (treated as RGBA) into the RGB and A components and replaces the components if required.
=> dx12: Constant color/alpha blending

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/GL/vertex_buffer.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_vertex_data.h
vertex attributes were already handled with specific functions, this PR just moves these functions inside rsx::register_decoders.
=> rsx: Use register_decoder for vertex attributes.

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
Looks like it breaks lots of games that leads to "Working buffer not enough" .Revert it back the original and find out better solution.
=> D3D12: revert heap size back to 896M

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/gl_render_targets.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h
Fixes https://github.com/RPCS3/rpcs3/issues/1954 for opengl by clearing new depth surfaces. Also cleans up some vulkan files.
~~It may be necessary to clear surfaces during prepare_ds_for_drawing as well, but I haven't seen any point in doing so yet.~~
=> gl: Clear depth surfaces before use; Vulkan cleanup

rpcs3/Emu/RSX/RSXThread.cpp
Partial revert of 6ae54ae27b048ce260d9067b09d08bcbbfdf1a68;
Should fix #1932, needs testing.
=> Partial revert of #1828

rpcs3/Gui/GameViewer.cpp
Fix compilation on linux when using clang-3.5 and libpng12-0.
When using a system-supplied wxWidgets library and the PNG library that comes with the project, there can be a version mismatch that causes a runtime error.
There was a small API change in libpng12-5 so the changes also deal with that.
=> Fix build on linux

rpcs3/Emu/RSX/GCM.cpp, rpcs3/Emu/RSX/RSXTexture.cpp, rpcs3/Emu/RSX/RSXTexture.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_vertex_data.h
This PR reverts the explicit assignment of member in rsx_state. It uses bitfield class instead of explicit << and &.
=> rsx: Use bitfield template to decode values.

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_trace.h, rpcs3/Gui/RSXDebugger.cpp, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
This PR copies rsx::methode_register in frame_debug to allow better state inspection in debug tools.
=> rsx: Copy state in capture frame call

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
A cosmetic fix for vulkan; centers the frame output when blitting to the swapchain surface.
=> vk: Center final on-screen image

.gitmodules, .travis.yml, appveyor.yml, rpcs3/CMakeLists.txt, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_trace.h, rpcs3_default.props
This PR adds cereal dependency and use it to serialize part of frame debug structure. Frame debug are now dumped on disk when a capture is occuring. While I use json the generated file is not intended to be readable atm.
=> Rsx refactor: Implement serialisation of debug data

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h
1) `std::unordered_map` is slower than lookup table but this is not the main problem. Changing it back to `std::array` fixed extreme memory consumption and compilation time for clang-3.8. Could be affecting Travis too, but this is speculation. This is only the simplest fix.
2) Fixed comment style, `std::for_each` usage seems unjustified.
3) `rsx_method_t` extended to accept `reg` argument, all methods also modified to use function type `rsx_method_t`. All methods are bound directly to method table.
4) Compilation time of rsx_methods.cpp significantly improved for both MSVC and Clang.
=> RSX: minor refactoring

.gitmodules
This commit adds a qml app that display rsx trace content in a more friendly maneer.
It's aimed at replacing the built-in rsx-debugger however at the moment it shows neither saved surface content nor command dump.
In the future I'd like to make this app able to regenerate more and more info from captured data by using the method in RSX/Commons and backends code. For instance instead of saving transform and shader programs code as string, I'd like the app to be able to query backend for translated shader dump when passed native rsx opcodes.
The longterm goal is to capture enough data to be able to "replay" a trace outside of rpcs3 by using as much code from rpcs3 as possible (like FIFO Log/FIFOCI in Dolphin). By using rsx-debugger to display rsx state and another gfx debugger like …
=> rsx-debug: Add a separate qt app

rpcs3/Emu/Cell/Modules/cellAdec.cpp, rpcs3/Emu/Cell/Modules/cellDmux.cpp, rpcs3/Emu/Cell/Modules/cellFs.cpp, rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/Modules/libmixer.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/IdManager.cpp, rpcs3/Emu/IdManager.h, rpcs3/emucore.vcxproj
Objects in IdManager can have slightly different (derived) type. Now it's possible to explicitly check this type with low overhead, just like `dynamic_cast<T*>` would do, but without using C++ RTTI. This is less powerful than true RTTI: only type equality can be checked.
=> IdManager improved

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/GL/vertex_buffer.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
This PR removes references to rsx::method_registers related to index buffer generation. It also unifies API for expanded and non expanded case so that the same function could be used by backend (which sometimes needs to expand indexes) and by rsx-debugger.
Since it's a rather invasive change I'd like some testing for regression, that's why I'm opening a PR before implementing complete support from rsx-debugger side.
=> rsx: Move index pointer generation in rsx::thread 

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/vertex_buffer.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h
This PR moves draw_command and first_command_count in a separate structure.
It's a rather simple change so there shouldn't be regression.
=> rsx: Use a "draw clause" object in rsx_state.

rpcs3/Emu/Audio/XAudio2/XAudio2Thread.cpp
Having distributed for wider testing in other forums and confirmed it did resolve the audio device switching issue on windows 10 platform specifially . 
Windows 7/8/8.1 should remain unchanged that load up 2.7 as usual .
=> XAudio : reorder versioning 2.9>2.7>2.8

rpcs3/Emu/RSX/VK/VKGSRender.cpp
=> Vk : Ignore clear if surface  is set to CELL_GCM_SURFACE_TARGET_NONE

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKProgramBuffer.h
We have colorblendstate used in LogicOp
if (rsx::method_registers.logic_op_enabled())
{
properties.cs.logicOpEnable = true;
properties.cs.logicOp = vk::get_logic_op(rsx::method_registers.logic_operation());
}
=> Vulkan: set ColorBlendState info (used by logicOp)

rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
fix https://github.com/RPCS3/rpcs3/issues/2061  https://github.com/RPCS3/rpcs3/issues/2057
All the following games regressed previously should be fixed with this PR.
1. 1942 Joint Strike
2. Castle Crashers
3. Marvel Vs Capcom 2 and 
4. Super Street Fighter II HD Remix 
5. Blade Arcus From Shining EX
6. Saint Seiya Brave Soldiers
7. Braid
8. 4 Elements HD
=> Vulkan : refine 2-sided lighting approach

rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
Inline with Vulkan fix previously which image size return invalid dimension .
Fix 4 elements HD for DX12 backend.
=> DX12: workaround invalid texture dimension

rpcs3/Emu/RSX/Common/TextureUtils.cpp
F {rsx::thread} class std::runtime_error thrown: Wrong format 0x9c
(in file Emu\RSX\Common\TextureUtils.cpp:275)
=> RSX: fix wrong format 0x9c

rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp
F {rsx::thread} class std::runtime_error thrown: Invalid format (0x1)
(in file Emu\RSX\D3D12\D3D12Formats.cpp:320)
=> D3D12: fix invalid format (0x1)

rpcs3/Emu/RSX/GL/gl_helpers.h
For release builds, debug error reporting by the driver makes more sense since developers don't always have access to the games that trigger these errors. Driver report gives more information about why an error is being raised than a line number and file.
=> gl: Use driver error reporting, not crash report with release build

Utilities/recursive_wrapper.hpp, Utilities/variant.hpp, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/vertex_buffer.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Gui/SettingsDialog.cpp
This removes the logic of selecting between buffer array or register outside of backends.
=> RSX: Puts vertex buffer in array and in register in a variant type.

rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/vertex_buffer.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
This PR is to revert back to use the common vp/fp decompiler which currently used by DX12/Vulkan backend. Having chat with DH and he told he will no longer work on the new decompiler , that should make our life easier to fix one bug in common decompiler for all backends going forward.
fix #1970 #1862 #1969 #2047 
(New GL stuffs like rsx_program_decompiler, rsx_gl_cache etc will remove in another PR)
=> GL: re-use common fp/vp decompiler

.clang-format
I didn't ask to break this, especially BreakConstructorInitializersBeforeComma and AlignConsecutiveAssignments are usually good options.
=> Revert "Add a git pre-commit hook running clang-format"

rpcs3/Emu/RSX/Common/TextureUtils.cpp
=> RSX: fix wrong format 0x9b

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
Temporary disable this vertex base index checking that exists for DX12 backend only.
fix https://github.com/RPCS3/rpcs3/issues/2126
=> DX12: temporary disable vertex base index check

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKProgramBuffer.h
Clean up code and fix bugs in several areas.
Also adds alphakill for vulkan as well as fixing region selection during surface clear
Additionally should fix some shader selection bugs related to render pass information
=> GL/Vulkan: Bug fixes and improvements; alphakill for vulkan

rpcs3/Emu/RSX/VK/VKGSRender.cpp
Properly compute descriptor heap size since vertex textures were added. Should stop vulkan from crashing with VkResult = FFFFFFFD error when running scenes with greater than 1024 draw calls per frame.
=> vk: Properly compute descriptor pool size

rpcs3/Emu/RSX/GL/GLGSRender.cpp
Should fix broken face cull direction in games using top window origin. Tested with prince of persia: the sands of time.
=> gl: Reverse cull face when origin == top

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
There are numerous games with this issue, most notably naruto titles and afterburner climax. Usually characterized by an upside-down "mirror" effect showing up usually during a post-process pass.
https://github.com/RPCS3/rpcs3/issues/2149
https://github.com/RPCS3/rpcs3/issues/1631
=> gl/vk: Mirror wpos based on window origin

rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
https://github.com/RPCS3/rpcs3/issues/2178
https://github.com/RPCS3/rpcs3/issues/2093
- Fixes broken sampling redirection when resampling a DSV as RGBA8.
- Disables all mipmapping parameters when a texture has 1 only mipmap level for GL and Vulkan
=> gl/vk/dx12: Fix depth reconstruction bug; Fix sampler parameters

rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLTexture.cpp
- Fixes broken vertex shader generation code for all backends in cases where a branch instruction is dual-issued with a vec op. https://github.com/RPCS3/rpcs3/issues/2218
- Fix mismatched texel block alignment when uploading dxt mipmaps. https://github.com/RPCS3/rpcs3/issues/2208
The first issue is guaranteed to have a major impact on a large number of games. I've tested a few with no regressions, but several minor bugs seem to have been fixed on several of them.
=> RSX/GL: Fix common vertex program decompiler bug; fix broken dxt mipmaps on openGL

CMakeLists.txt
Outputs a fatal_error if a version of gcc below 5.1 or 6.1 is being used.
#2236
=> Check if gcc version is below 5.1 or equal to 6.1

.travis.yml
Should fix the issue with Travis (No available formula with the name "llvm36") on OSX.
We're using 3.8 so there's no reason for Travis to use 3.6.
If this doesn't work we can just remove LLVM from the OSX part and it will compile without LLVM like it did before.
=> Update LLVM on Travis

rpcs3/Emu/RSX/rsx_methods.cpp
Causes MGS4 to boot a little bit further.
MGS4 now actually does some stuff, mostly filesystem related, and then softlocks(progress! :P). No display output on any backend unfortunately. Doesn't seem to respond to inputs either.
The information was gotten from the MESA implementation of nv30/40.
Sorry for the small commit, I am still learning the architecture of both the PS3 and the emulator.
Am I correct in using bind_array here instead of bind_range? Can anyone explain the difference?
=> Bind SET_POLYGON_STIPPLE_PATTERN

rpcs3/Emu/RSX/VK/VKGSRender.cpp
I'm not sure if there was a reason behind this, but at a cursory glance, it just looked like a mistake.
=> Add logic_set support to VKGSRender

.travis.yml, README.md, appveyor.yml, rpcs3/Emu/Cell/Modules/sceNp2.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Gui/AboutDialog.h
AppVeyor: Improve artifact name
Travis: Update notification email
Readme: Fix forum link and remove coveralls
sceNp2: Use UNIMPLEMENTED_FUNC macro instead of fmt::throw_exception
VK: Fix pathing for linux
AboutDialog: Fix forum link
=> Misc changes

rpcs3/rpcs3qt/glviewer.cpp, rpcs3/rpcs3qt/glviewer.h, rpcs3/rpcs3qt/main.cpp, rpcs3/rpcs3qt/qml/main.qml, rpcs3/rpcs3qt/rpcs3qt.pro
Chnges from #2330 breaks rpcs3qt's compilation on any non-Windows platform b/c they doesnt have `opengl32.lib` library.
This PR fix this issue by passing `opengl32.lib` into LIBS only for win32 targets. Also this PR contains some code cleanups like indentation and some code formatting.
=> Fix RPCS3's Qt App Compilation

rpcs3/Emu/Cell/Modules/cellMusic.cpp
Also return CELL_OK in function until the it become properly developed.
=> cellMusic.cpp Change Throw Exception into UNIMPLEMENTED_FUNC

rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp
cellSysutilAvc2: Use UNIMPLEMENTED_FUNC macro instead of fmt::throw_exception.
```
[NPJB90576]
E {PPU[0x1000000] Thread (main_thread) [0x002dfd80]} cellSysutilAvc2: Unknown media type 0x0
E {PPU[0x1000000] Thread (main_thread) [0x002dfd20]} PPU: 'cellSysutilAvc2EstimateMemoryContainerSize' aborted
F {PPU[0x1000000] Thread (main_thread) [0x002dfd20]} class std::runtime_error thrown: Unimplemented
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellSysutilAvc2.cpp:92)
```
```
[BLAS50770]
E {PPU[0x1000000] Thread (main_thread) [0x00a09a68]} PPU: 'cellSysutilAvc2GetVoiceMuting' aborted
F {PPU[0x1000000] Thread (main_thread) [0x00a09a68]} class std::runtime_error thrown: Unimplemented
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellSysutilAvc2.cpp:307)
```
=> Some changes

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp
Thx @kd-11 for verifying fix.
d3d12: add x1r5g5b5_z1r5g5b5 for fix in-game SplatterHouse in DirectX 12.
d3d12: Little Cleanup old code forgotten removed.
Add info in BufferUtils for log for find and add draw mode Unknown, actually found with this Kung Fuu Rider value missing added later by @kd-11 
Tell me if I need to change something.
=> d3d12: add x1r5g5b5_z1r5g5b5 for fix Splatterhouse

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp, rpcs3/Emu/RSX/D3D12/D3D12Formats.h, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
While implementing R/W buffers, I noticed something about how the RSX seems to be setting up its render buffers, which was confirmed by the bug affecting Catherine https://github.com/RPCS3/rpcs3/issues/2241. Looks like the buffer dimensions are not the same as the resolution, which means some scaling of the output is expected. I've only noticed scaling in the X dimension so far by manipulating the pitch parameter of the memory buffer.
This fix adds a texture parameters field to the FS state, allowing for scaling and possibly sampling offsets (currently unused).
TODOs:
=> RTT shader access fix (Catherine)

rpcs3/Emu/RSX/GL/OpenGL.cpp
#2399
Defaults dGPU on NVIDIA Optimus systems and requests High Performance mode on AMD systems.
=> Fixes #2399

rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
The main changes are:
- To restrict the clip y/x to `(in_x/y + in_w - 1)` as per docs
- Remove double addition of out_offset when clipping/converting
Also rearranged a bit to get some things as const to make the function a bit easier to work with. 
This makes #2166 create the correct shaders now and looks a bit better, as cg loader uses image_in to blit the shaders to rsx memory, and gave some invalid clip values
=> Fix nv3089_image_in

rpcs3/Emu/Cell/Modules/cellPngDec.cpp, rpcs3/Emu/Cell/Modules/cellPngDec.h
- ReadHeader and SetParam corrected
- Partial loading Implemented
- Interlace Support added
- Improve error handling
This fixes #2028 and now should report back correct sizes from their respective calls.
Tested with Sonic CD and Arkedo
Partial and interlace tested with pngdec_ppu*.elfs
It *should* take care of #1871, but nothing is displayed with LLE pngdec also, so its unknown
=> Improve cellPngDec

rpcs3/Emu/Cell/Modules/sys_net.cpp
Prevents emulator crash when invalid socket is provided to the function
Fixes crash on One Piece Pirate Warriors Menu
=> libnet: recvfrom() fix

rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/Modules/sceNp.h
Fixes sceNpDrmProcessExitSpawn and sceNpDrmProcessExitSpawn2 functions
The problem was that first argument klicensee was missing, therefore shifting every other argument out of place and throwing an access violation at the end.
Before:
path: !AjɨΰｘƵ6
argv: 0xd000fc48
envp: 0xabc000
data: 0x0
data_size: 0x0
prio: 0
flags: 1001
After:
klicensee: 0x18978
path: /dev_hdd0/game/NPUB31430/USRDIR/reboot.self
argv: 0x278000
envp: 0x0
data: 0x0
data_size: 0x0
prio: 1001
flags: 4611686018427387936
Tested with Child of Light Trial [NPUB31430]
=> sceNp: Fix ExitSpawn, Implement VerifyUpgradeLicense

rpcs3/Emu/RSX/rsx_methods.cpp
This seems to be closer to the correct functionality for image_in, which is ignore the given clip x/y value if it would push the clip'd region outside the source region.
This takes care of #2165 and #2166 and also fixes the intro/menu images in spyro-bles00382
=> rsx: image_in fix for clipx/y

rpcs3/Emu/Cell/Modules/cellGame.cpp
cellDiscGameGetBootDiscInfo is called by non-disc games for some reason.
That wasn't accounted for and therefore it would try to read PARAM.SFO from an unmounted path and throw an access violation.
Tested with NBA Live 08 Demo [NPUB90029] which now shows Intros, should fix similar games as well.
=> cellGame: Fix cellDiscGameGetBootDiscInfo

rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_cache.h
All backends have a problem properly handling textures that are not at 4k aligned addresses. Its much worse with smaller textures (like 1D color index lookups).
This should fix flickering in 1942: Joint Strike and many other games where malformed textures are read from the cache while they have actually been invalidated.
=> gl/vk/cache: Fix invalidating intersecting and overlapping memory regions

rpcs3/Crypto/lz.cpp, rpcs3/Crypto/unedat.cpp, rpcs3/Crypto/unedat.h, rpcs3/Crypto/utils.cpp, rpcs3/Crypto/utils.h, rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_fs.h
This implements mself / sdata support
- 'on the fly', meaning it doesn't create any temporary files,
- it also only decrypts requested data rather than the whole file.
I realizes theres a lot of changes in unedat.cpp. I've tried to 'clean/ update ' it a bit, killing malloc/new a bit and using u8/u32/etc types instead. The main change is splitting it up to support random block decryption of a file.
Tested w/ [BLUS31212] KH 1.5 for mself, [NPUB30062] Astro tripper for sdata
=> Mself / Sdata: on the fly decoding support

rpcs3/Crypto/unedat.cpp, rpcs3/Crypto/unedat.h, rpcs3/Crypto/utils.cpp, rpcs3/Crypto/utils.h, rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp, rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/Modules/sceNp.h, rpcs3/Emu/Cell/lv2/sys_fs.cpp
- This adds support for 'on the fly' decryption of edat files, like the previous sdata/mself implementation
- It also fixes the decryption error that happened with some sdata/edat files
- cellPad fix per docs, allows prince of persia to progress past first menu
- cellMsgDialog arg check to allow crazy taxi to boot and play
=> Edat / Sdata: On the fly decryption for edat + misc fixes

rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
Changed "fmt::throw_exception("Unimplemented" HERE); "
into:
"UNIMPLEMENTED_FUNC(cellAvconfExt); "
"return CELL_OK;"
Allow NPEB01283 to get ingame...
=> Stub cellAvconfExt

rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
Looks like some titles actually hit this assertion. If it is a misconfiguration issue, the next check shall log information and disable sync at the address anyway.
=> gl: Lower restriction on render target pitch

rpcs3/Emu/Cell/PPUFunction.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/Cell/lv2/sys_vm.h
for different memory map(unconfirmed).
Adds default flag value for sys_allocate_memory
Fixes unknown syscall 313 error
Issue #2510
=> Use sys_vm_memory_map plus add default value for sys_allocate_memory

rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp
- Fix an old bug with shared surface store where RTTs were relocated when any individual buffer was changed.
- Actually bind a stencil attachment on fbo creation for ogl
=> gl/vk: Stencil fixes

rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_vertex_data.h
Adds in support for immediate mode rendering between begin/end command pairs
Fixes missing draw calls in most homebew games
Tested games
- Sketch fight
- Hero city
- Super pixel jumper
- Dont get crushed
Also fixes gsl::span errors with vulkan as well as not throwing an exception if an attribute/texture is enabled, but not active in the shader.
=> rsx: Add support for immediate mode rendering

rpcs3/Emu/RSX/GL/GLTexture.cpp
The meaning of texture border has changed starting with GL 3+ due to the resulting confusion from broken and incomplete implementations on hardware of the GL 1.x era. As such, legacy clamp is closer to the modern edge clamp than border clamp as it once was.
Border pixels in textures are not supported on newer hardware and never truly worked in the past either, especially on NV cards.
Should hopefully fix any games showing visible grid lines in OpenGL
=> gl: Fix legacy clamp mode

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
I assume that the intention of the exisiting code was to do exactly what the title says. But it also replaced all negative input values with the "not 0" value. Now negative values are allowed but inverted.
Existing code caused some pixels to have saturated color components (brightly colored spots of one pure color) in Metro Last Light:
Maybe this is also what causes the colored spots in Resident Evil 5. I cannot verify because I don't have the game.
=> Only pass absolute values to sqrt and log2 in the fragment program.

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/gcm_enums.h
Image layout transitions were disabled at some point during code refactoring. The impact on Nvidia drivers is not too bad, but horrible moire artefacts appear on AMD, especially newer cards.
Also includes a fix for https://github.com/RPCS3/rpcs3/issues/2628
Added a fix for LINE_LOOP rendering using vulkan (fixes Tetris).
NOTE: DX12 removed the LINE_LIST topology from D3D11 meaning DX12 does not support line_strip or line_loop. Line rendering with DX12 will have to use a different path than the others.
=> rsx/vk: Re-enable layout transitions in vulkan, Other minor fixes

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/Modules/sys_net.cpp, rpcs3/Emu/Memory/vm.cpp
allows allocation of last byte in memory block
prevents rpcs3 from crashing when closing non existent socket
=> cellSave fix plus bugfixes

rpcs3/Emu/Cell/SPUInterpreter.cpp
On MS VC the isdenormal() function in the PSU interpreter is broken because it always returns true (value for "normal" is -1, so the bitcheck always evaluates true). I don't know what kind of compiler needs the #else path, so I just extended the #ifdef.
Observable improvements fromt this are: Wolfenstein goes ingame without destroying the physics objects and the Trine Demo has working collision/physics and plays sound (before the precise interpreter would play no sound but go ingame with broken collision and the fast interprester plays sound but crashes before going ingame).
=> Precise SPU intepreter: Fix isdenormal() on Windows

rpcs3/Emu/Cell/Modules/cellSsl.cpp
! LDR: **** cellSsl export: [0x005D0928] at 0x1f5390
! LDR: **** cellSsl export: [0x01D5F161] at 0x1f5050
! LDR: **** cellSsl export: [0x0266A34C] at 0x1f50e0
! LDR: **** cellSsl export: [0x02C73EB6] at 0x1f4560
! LDR: **** cellSsl export: [0x05319303] at 0x1f4e90
! LDR: **** cellSsl export: [0x06BCC1DA] at 0x1f4788
! LDR: **** cellSsl export: [0x06ECEF1C] at 0x1f5450
! LDR: **** cellSsl export: [0x07296D93] at 0x1f4fd0
! LDR: **** cellSsl export: [0x074CD5B5] at 0x1f4d80
! LDR: **** cellSsl export: [0x0D38E130] at 0x1f4da8
! LDR: **** cellSsl export: [0x0DBB3F51] at 0x1f50e8
! LDR: **** cellSsl export: [SSLCERT_check_private_key] at 0x1f5390
! LDR: **** cellSsl export: [SSL_set_session] at 0x1f5050
! LDR: **** cellSsl export: [SSL_set_connect_state] at 0x1f50e0
! LDR: **** cellSsl …
=> Add functions to cellSsl

rpcs3/Emu/RSX/GL/GLGSRender.cpp
I don't think we need this obsolete function that do the anti-aliasing.
fix https://github.com/RPCS3/rpcs3/issues/2241
=> GL: fix wireframe in Catherine

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp
Throw a fatal error instead of hanging the Emu or crashing due to nullptr access.
=> rsx: Throw if user attempts to use Vulkan/DX12 without driver support

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp
This PR modifies the result of SPU FMA if exponents in a or b are at max and discards the value. This is by no means even close to accurate handling of corner cases in the SPU, but rather a fast workaround.
Discards the result of (a * b) if either a or b has extended exp bits (usually inf) without degrading performance too much.
Should fix some cases reported in https://github.com/RPCS3/rpcs3/issues/2670
=> spu: Check exponent bits in FMA ops

rpcs3/Gui/SettingsDialog.cpp
D3D12 is not in the list of supported renderers on platforms other than windows.
Deleting an item, that can't be found, triggers an assert in debug builds, so let's
avoid that.
Fix #2662
=> Fix crash on linux when opening the settings dialog in debug mode

rpcs3/Emu/Cell/Modules/cellRtcAlarm.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUModule.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
! LDR: ** Exported module 'cellRtcAlarm' (0x0, 0x0, 0x2c000001, 0x20090018)
! LDR: **** cellRtcAlarm export: [0x122D3DB1] at 0x1a1c10c
! LDR: **** cellRtcAlarm export: [0x559234A3] at 0x1a1c0f4
! LDR: **** cellRtcAlarm export: [0xAD8D9839] at 0x1a1c104
! LDR: **** cellRtcAlarm export: [0xB287748C] at 0x1a1c0ec
! LDR: **** cellRtcAlarm export: [0xDB215455] at 0x1a1c0fc
! LDR: ** Exported module 'cellRtcAlarm' (0x0, 0x0, 0x2c000001, 0x20090018)
! LDR: **** cellRtcAlarm export: [cellRtcAlarmRegister] at 0x1a1c10c
! LDR: **** cellRtcAlarm export: [cellRtcAlarmUnregister] at 0x1a1c0f4
! LDR: **** cellRtcAlarm export: [cellRtcAlarm_AD8D9839] at 0x1a1c104
! LDR: **** cellRtcAlarm export: [cellRtcAlarm_B287748C] at 0x1a1c0ec
! LDR: **** cellRtcAlarm export: [cellRtcAlarmGetStatus] at 0x1a1c0fc
=> Add cellRtcAlarm module

Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/CPU/CPUThread.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_utils.cpp, rpcs3/Emu/RSX/rsx_utils.h, rpcs3/Gui/SettingsDialog.cpp
- Implements synchronized framebuffer r/w for vulkan. Still missing some important pieces such as hw accelerated image_in, but that will get merged in later.
- Adds a simple hack for SPU priority and ideal core binding (only works on windows for now)
Alot more remains, from vertex fetch rewrites, sync fixes for ogl and dx12, GPU acceleration for image_in on all backends, etc. Most of it is partially done with the remaining pieces to come later.
=> vulkan/cell: Implement synchronized buffers for vulkan; SPU speed hacks

rpcs3/Emu/RSX/Common/ShaderParam.h, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
Reimplements vertex shader output control; adding in options for more complex conditions.
Should fix remaining user clipping
- Note: OpenGL requires all clip planes that may be enabled via glEnable be defined otherwise risk undefined results. This is the only case where it seems necessary to enable more than one plane even when not needed.
- A value of 0.5 seems to work well as a default value. 1.0 does not, probably because it would be clipped as falling on the edge of typical clip volumes [-1, 1]
- Include strict vertex shader output declaration for compatibility with mesa drivers which are very strict
- Added a workaround for intel drivers which don't report their capabilities via extensions for some reason
=> rsx: Vertex program output fixes

rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
Another fix for the mix-and-match nature of ps3 shaders causing issues with mesa's linker.
Should fix demon's souls "load profile" crash on linux+mesa
=> gl: Strict export of diff_color and spec_color for mesa compatibility

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
Rewrites vertex upload, removing the slower methods used before. The old code is improved as well and kept around for debugging until its state is known to be mature enough.
Also lifts some restrictions on vertex register formats and adds a fix for register type data uploads when using a vertex buffer stream.
Overall, performance is up anywhere from 10-300% for geometry heavy scenes.
=> rsx: Performance improvements and bug fixes

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/System.h, rpcs3/Gui/SettingsDialog.cpp
I have both an Nvidia card and an AMD card in my PC, and regardless of which display is currently active, Vulkan defaults to the Nvidia card.
This commit allows the user to select the Vulkan device similar to selecting the Direct3D12 device.
This may make the configuration dialog slightly slower when opening.
=> Add option to select Vulkan device

rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Cell/Modules/cellPad.h
- Initial implement of cellPadPeriphGetData. should take care of games listed in #2820, note that everything is still just reported as a regular controller, so the games may complain about connected controller.
- Clear out info structs before setting, fixes scott pilgrim booting, it seems to ignore the now_connect variable and runs through the full struct regardless
=> CellPad Fixes

rpcs3/rpcs3qt/emu_settings.cpp
this was missing as a result to the previous fix of the game configs
=> use global config as default for game config again

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h
adds a submenu to boot "Boot Recent"
- submenu contains functions "clear list" and "freeze list"
- activated "freeze list" will prevent changes to the list
- successfull boots will be added to the top of the list
- when the list contains 9 items the last will be removed on new addition
- every item has a boot shortcut from Ctrl+1 to Ctrl+9
- games can only be bootet from mainwindow and if emu is not running
- if names are too long they will be shortened like this "This name is waaa(....)aaaay to long"
- on mouse hover you will see a tooltip with the full name
- if the game title is a path it will be shown only as filename while the tooltip remains the path
- remove invalid paths from list on start or boot
=> GUI: Add recent games menu

rpcs3/Emu/RSX/Common/ring_buffer_helper.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_utils.h
List of fixes
- Monitor buffer usage to prevent running out of working space on vulkan. Also reorganizes some of the buffer init process on vulkan
- Image clipping fixes. Fixes software mode clipping in nv3089::image_in. Fixes cropped graphics in some games.
=> rsx/vk: Bug fixes

rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/main_window.cpp
This should hopefully fix the crash that was happening with fermi / nvidia cards.
I think the main issue was the vulkan throw happening in enumerateDevices, but ive also rewrote the dx12 check code slightly as well to hopefully be a bit 'safer'
=> Dx12/Vulk: Fix KernelBase.dll crash

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/graphics_tab.cpp
On current builds the selected item jumps randomly on any kind of list refresh.
Now the selection will stay on the same game, even when switching list/grid mode.
The view will scroll to the selection and not to some other place anymore.
This PR also exchanges the mysterious and rare missingno for something more suitable
- fix adapter saving to config
=> Fix inconsistent selection in gamelist/grid

rpcs3/rpcs3qt/cg_disasm_window.cpp, rpcs3/rpcs3qt/cg_disasm_window.h, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_frame.h, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp
Debugger:
- add splitter to resize address list vs. Regs
- resize now adjusts listsize again
- fix interrupt on select
- prevent setting breakpoints on invalid addresses
CgDisasm:
- use side by side instead of tabs
- add splitter similar as in Debugger
- add drag & drop to cg_disasm for fpo and vpo files
=> Reimplement debugger resize & disassembly

rpcs3/rpcs3qt/core_tab.cpp
Excludes .prx modules from being listed, which prevents users from downloading random folders from the web that only have .prx modules and break auto library load.
In the future it's probably a good idea to let users have the ability to list and load custom .prx files, but even in that case they shouldn't be inside dev_flash/sys/externals anyways. 
_(You can still load custom .prx files if you manually edit the config file, but this shouldn't be needed unless you're modding the game or something along those lines. All firmware modules are .sprx, and game specific .prx get loaded automatically using liblv2 option)._
=> GUI: List SPRX modules only

rpcs3/Emu/Cell/Modules/cellVideoOut.cpp, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/BufferUtils.h, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12Overlay.cpp, rpcs3/Emu/RSX/D3D12/D3D12Utils.h, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp, rpcs3/Emu/RSX/rsx_cache.h
- Fix a regression when emulating index buffers for generated primitives. Removes the 'first' parameter since rpcs3 does not support disjoint vertex ranges at the moment anyway. https://github.com/RPCS3/rpcs3/issues/2917
- Adds in a very old bugfix that makes DX12 crash properly instead of throwing a cryptic range error. This DOES NOT fix DX12 crashing, merely generates a more useful fatal error message.
- Includes fixes for some 'blue' games
- Added a 'speed hack' - not really a hack - for games that share memory regions between textures and other GPU resources such as shaders. Significantly boosts perf in games where the cache is invalidated often. Can be disabled by setting 'Strict Rendering Mode' to true.
- Add 59.94 Hz support required by some games
- Fix a rare vulkan shader …
=> rsx: Bug fixes

README.md, rpcs3/CMakeLists.txt
First off, great work with the transition to qt!
It seems the project doesn't use any qt 5.8 specific features, and relaxing the check some would make the project more approachable.
With this change, I successfully compiled rpcs3 on Fedora 25, which is on qt 5.7.1
=> Relax qt dependency to qt 5.7

README.md
@martinlindhe Not sure why this was changed, but otherwise CMake complains that you need to specify a source directory, and it won't build.
Please merge this ASAP.
=> Fix CMake build instructions on Linux

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/rpcs3qt/save_data_utility.cpp
Some games like Akiba throw an error if you return cell_ok when loading but no data is selected.  Others, like Miku will start a new game.
Returning cell_cancel fixes this.
=> Small Save Manager Patch

.travis.yml, rpcs3/CMakeLists.txt
After discussing this on Discord we've decided that we're going to provide two Linux AppImage builds.
**Linux Build without LLVM**
This is for users that use mesa for their graphics drivers, and the llvm version that mesa is linked to is not the same as the one RPCS3 uses.
**Linux builds with LLVM**
This is for users that have their mesa driver built with LLVM 4.0 **OR** use binary drivers, ie NVIDIA.
---
All of the AppImage builds now use clang, as it seems to be able to work around issue #2516 the most frequently.
In addition, the clang builds now use clang 4.0, they were previously using 3.5.
=> Finalize Linux AppImage build

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GSRender.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_vertex_data.h, rpcs3/Emu/System.h, rpcs3/rpcs3qt/gl_gs_frame.cpp, rpcs3/rpcs3qt/gl_gs_frame.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
- Implement frame skipping (config file option only for now)
- WIP: Batch together draw calls using the same geometry with different translation matrices
- Allow multithreaded vertex processing
- Fix some fragment shader instructions
- Implement rsx framebuffer memory persistence
- Fix vulkan layout transitions
- Properly implement FCGT and FCMGT SPU opcodes
- Minor tweaks to SPU wait loops and DMA transfers to improve stalling behaviour
Major highlights
- Fixes persona 5 and many other games with blue output and 'overbloom'
- Fixes missing characters in Red Dead Redemption
- Fixes most of the missing graphics is Tales of Vesperia
- Fixes flickering graphics when using vulkan in some games
=> cell/rsx: Bug Fixes

rpcs3/Crypto/unpkg.cpp
Fixes pkg overwriting files without the PKG_FILE_ENTRY_OVERWRITE flag
=> Pkg installation fix

rpcs3/Emu/Cell/Modules/cellHttp.cpp, rpcs3/Emu/Cell/Modules/sceNp.cpp, rpcs3/Emu/Cell/Modules/sceNp2.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.cpp
**Before**
! LDR: **** cellHttp export: [0x431E1407] at 0x167808
! LDR: **** cellHttp export: [0xB7CB7D05] at 0x167858
! LDR: **** cellHttp export: [0x1249C1D1] at 0x167830
! LDR: **** cellHttp export: [0xE6C7D333] at 0x1678e0
! LDR: **** cellHttp export: [0x98CE061C] at 0x1678d0
! LDR: **** sceNp export: [0x91840669] at 0x40c100
! LDR: **** sceNp export: [0xBE3AF96E] at 0x40c0f8
! LDR: **** sceNp2 export: [0x944B28E8] at 0x40d120
! LDR: **** sceNp2 export: [0x98F74C9A] at 0x40d158
! LDR: **** sceNp2 export: [0xDBE84071] at 0x40d178
! LDR: **** sceNp2 export: [0x2E42F94A] at 0x40d150
**After**
! LDR: **** cellHttp export: [cellHttpClientGetConnectionWaitStatus] at 0x167808
! LDR: **** cellHttp export: [cellHttpClientSetConnectionWaitTimeout] at 0x167858
! LDR: **** cellHttp export: …
=> Remove compiler warning & stub module functions

rpcs3/Emu/Cell/Modules/sceNp.cpp
Fix for sceNpBasicGetEvent which should return SCE_NP_BASIC_ERROR_NO_EVENT without a connection.
=> Minor sceNpBasicGetEvent Fix

rpcs3/rpcs3qt/settings_dialog.ui
No classes or names or any of that poop are being changed here, only a text string.
=> Correct typo in viewport settings

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
- Fix vertex buffer binding for vulkan. The key is to avoid 'stale' descriptors getting to the driver since the referenced buffer views are likely to have been destroyed, resulting in a use-after-free promptly followed by a segfault
=> vulkan hotfix

rpcs3/Emu/Cell/lv2/sys_timer.h, rpcs3/Emu/RSX/CgBinaryVertexProgram.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
sys_timer: Fix initial set state. Fixes KH2 ( and rest of kh series) booting up
vertex decompiler: fixes weird oddity of rsx which allows double destination registers set. Fixes roxas render and cutscene rendering in kh
edit: this *may* also require lle-gcm, didnt test without
=> KH2/Roxas Fix

rpcs3/rpcs3qt/gs_frame.cpp
Adds the ability to force a log comment while a game is running. I used it to pinpoint when game events happened in the log recently for debugging.  Figured it may help others too. Maybe use LOG_NOTICE instead of LOG_SUCCESS?
=> Log marking.  Alt+L

rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/System.h
Minor tweaks for performance and improved stability
- Fix buffer overrun crash (LBP Karting, Ridge Racer 7)
- Fix opengl bug when initializing framebuffers (Removes the 'fbo check failed' spam)
- Vulkan: improvements to multithreaded vertex processing
- Vulkan: volatile vertex cache implemented to help performance in geometry heavy scenes
- Vulkan: pre-emptive framebuffer flushing to lower the penalty of a cache miss
=> rsx: Improvements

rpcs3/rpcs3qt/gs_frame.cpp
Deduced from booting BCES01584 - the last of us and analysing RSX memory mapping pattern. 
This prevent the trap instruction at boot but the game still freeze almost right after. 
Might need to reconsider/tweak the change if VirtualMemoryBlock is used for something else than the RSX one day.
=> Allow overlapping ranges in cellGcmMapEaIoAdress with coherency check

rpcs3/CMakeLists.txt, rpcs3/Emu/Audio/ALSA/ALSAThread.cpp, rpcs3/Emu/Audio/ALSA/ALSAThread.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3_app.cpp
DragonFly, FreeBSD and NetBSD support ALSA (via OSS plugin). ALSA, unlike OpenAL, doesn't suffer from audio crackling/noise in some games e.g., Persona 5.
Example build log: http://sprunge.us/KiAM
=> Allow building with ALSA on BSDs

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
- Fixes a situation where a query readback is requested while zcull render is still active
=> rsx/gl: Fix zcull queries and log conditional render modes

rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp, rpcs3/Emu/Cell/Modules/cellSearch.cpp, rpcs3/Emu/Cell/Modules/cellSysutilAvc2.cpp, rpcs3/Emu/Cell/Modules/cellSysutilAvc2.h, rpcs3/Emu/Cell/Modules/cellUsbd.cpp, rpcs3/Emu/Cell/Modules/sceNpTus.cpp, rpcs3/Emu/Cell/Modules/sys_net.cpp
- Diablo III (BLES01921) and Diablo III: Reaper of Souls - Ultimate Evil Edition (BLUS31437)
`F {PPU[0x1000000] Thread (main_thread) [0x00e65508]} class std::runtime_error thrown: Unimplemented
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellSysutilAvc2.cpp:78)`
- Hard Corps Uprising (NPEB00332)
`F {PPU[0x100000b] Thread (mnp Session Procedure) [0x0126e540]} class std::runtime_error thrown: Unimplemented
(in file C:\rpcs3\rpcs3\Emu\Cell\Modules\cellSysutilAvc2.cpp:114)`
**Before**
! LDR: **** cellSysutilAvconfExt export: [0x1A324E03] at 0xb71158
! LDR: **** cellSearchUtility export: [0x1E989496] at 0xb76134
! LDR: **** cellUsbd export: [0x5AB62AF9] at 0xb81080
! LDR: **** cellUsbd export: [0xA4088179] at 0xb81088
! LDR: **** cellUsbd export: [0xD87D972D] at 0xb81158
! LDR: **** sys_net …
=> Stub cellSysutilAvc2, cellAvconfExt and add misc HLE functions

rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h
Fixes #3179 and removes the now-unnecessary *Axis scaling* option. @HollowSoldier Try this one to see if it fixes your problems.
=> Better evdev joystick axis scaling

.travis.yml, rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h, rpcs3/rpcs3qt/main_window.cpp
This PR includes
- Improved evdev controller detection, this fixes detection of the Steam Controller when used with [sc-controller](https://github.com/kozec/sc-controller)
- Adds joystick squircling, which makes running in Persona 5 nicer, same implementation as xinput and dualshock 4 backends.
- Adds a quick fix for developer builds and standard linux builds (for example, the Arch AUR), to no longer give experimental build warning.
- Updates ffmpeg again, to fix the issue here: http://www.emunewz.net/forum/showthread.php?tid=174368&pid=285178#pid285178 again.
Requesting review from @kirbyfan64 @kozek
Requesting testing from @gasinvein @gadzook @ghost and @toccata10
---
pre-compiled AppImage link for testing: https://transfer.sh/pwI71/eb22e4e-178_linux64
(will expire in 14 days)
To run …
=> Linux evdev controller backend fixes (and misc linux fixes)

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12CommonDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12CommonDecompiler.h, rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLHelpers.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_methods.cpp
- Fix a zcull corner case (openGL)
- Minor improvements to shader cache to reduce first time compile stutter and number of pipeline objects (WIP)
- Fix VP ARL opcode: Respect the vector write mask
- Implement QUAD_STRIP by redirecting to TRIANGLE_STRIP. This can fail in some rare cases, but that's not something that can be fixed with indexing anyway. Quads are planar, but adjacent triangles need not be.
=> rsx: Minor fixes

Utilities/LUrlParser.cpp, Utilities/LUrlParser.h, rpcs3/Emu/Cell/Modules/cellHttpUtil.cpp, rpcs3/Emu/Cell/Modules/cellSsl.cpp, rpcs3/emucore.vcxproj
When Neko changed cellSsl + cellHttp to use hle, not lle, it broke some games loading because of the stubbed cellSslCertificateLoader. By implementing this, it fixed a regression in MotorStorm Apocalypse, and probably fixed bug #3110 .
Also, the windows-only implementation of cellHttpUtilParseUri was bugging me, so I added https://github.com/corporateshark/LUrlParser, and made a cross-platform one. 
**EDIT:** Apparently fixes a regression in Final Fantasy X-2?
=> Implement cellSslCertificateLoader + cellHttpUtilParseUri

rpcs3/rpcs3qt/game_list_frame.cpp
I hope this doesn't create a regression, but I couldn't find any place where the itemText was actually used. Afaikt only the m_game_data.info.name is used for any real operations
=> game_list_frame: force single line text for out of bounds issue

rpcs3/Emu/Cell/Modules/sys_net.cpp, rpcs3/Emu/Cell/lv2/sys_tty.cpp
- Fix crash in sys_tty_write() if the return buffer for the written length is NULL. Resident Evil 5 demo does this.
- ~~On Windows, pass the given file access modifiers like the Linux code. Dark Souls II creates a temporary file with write and append modifier, then tries to truncate the file. This needs GENERIC_WRITE.~~ Obsoleted by #3391.
- Endianess for the parameter buffer in setsockopt was not converted before passing the value on to the native function. Actually I don't know if converting the endianess is really necessary or if a true/false check with conversion to 1/0 would be enough or better. The value of these parameters can only be 0 or 1. This might break some games not because it is wrong but because they might not error out of the net code as early as now.
=> Various fixes

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp
use single line titles in gamelist and recent games menu
before:
after:
=> GUI: Fix "recent games" layout bug

rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Io/Null/NullPadHandler.h, rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/System.h, rpcs3/Emu/VFS.h, rpcs3/ds4_pad_handler.cpp, rpcs3/ds4_pad_handler.h, rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h, rpcs3/keyboard_pad_handler.cpp, rpcs3/keyboard_pad_handler.h, rpcs3/mm_joystick_handler.cpp, rpcs3/mm_joystick_handler.h, rpcs3/pad_thread.cpp, rpcs3/pad_thread.h, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/gamepads_settings_dialog.cpp, rpcs3/rpcs3qt/gamepads_settings_dialog.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/xinput_pad_handler.cpp, rpcs3/xinput_pad_handler.h
Adds a window to setup multiple input types as once
All controllers are now handled by a single thread
[hcorion] evdev refactor
=> Pad Refactoring

rpcs3/keyboard_pad_handler.cpp, rpcs3/rpcs3qt/gamepads_settings_dialog.cpp, rpcs3/rpcs3qt/gamepads_settings_dialog.h, rpcs3/rpcs3qt/gl_gs_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h
should fix this:
It cuts off the last part though. I hope it is okay. (as in: DragonRise Inc. Gene...)
=> [Qt/OpenGL/AMD]: fix gamepad settings layout issue, add refresh button / fix amd openGL Emu stop bug

rpcs3/rpcs3.vcxproj
When building RPCS3 on Visual Studio, there's some DLLs that are copied
from the local QT installation to the RPCS3's output directory using a
post-build script. However, one of these DLL was missing, which is
required for running the program on debug mode (for release versions,
the file is already present on git).
This commit just add the additional command that is needed to copy the
file.
=> VS build: copy Qt5WinExtras.dll to bin directory

rpcs3/Emu/Cell/PPUThread.cpp
I'm not sure if it's correct to surround the ->fin call with an if block, or to do as I done.
But, this should prevent the crashes that happens with many games with LLVM.
=> LLVM:: If the loop is never entered, then the JIT is null.

README.md, rpcs3/CMakeLists.txt, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/cmake_modules/FindVulkan.cmake, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/emu_settings.cpp
Makes Vulkan optional on Linux / makes it possible on FreeBSD. When the `USE_VULKAN` flag is on, finds the Vulkan loader using pkg-config, and uses it if it's been found.
Also `libX11` is now linked on any non-Apple Unix. It was necessary on FreeBSD.
^^^ my FreeBSD desktop running Crazy Taxi, with RADV/amdgpu. ([drm-next-kmod](https://www.freshports.org/graphics/drm-next-kmod), ports patches: [Vulkan Mesa drivers](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221540) + [Vulkan loader](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222175), hopefully will be merged soon :D)
=> Vulkan: use pkg-config instead of checking for Linux

rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
should fix #3453
also prevents some minor layout glitch:
=> [Qt] fix settings dialog layout shenanigans

rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.h
kd-11 noticed some strange behaviour with vulkan adapters not saving.
As I looked into it I found that oldRender was initiated instead of m_oldRender before the first render switch and then never used. So m_oldRender was only ever set after two render switches which also meant saving worked only then.
Then I was annoyed by having to check for every renderer manually so I just went and made it more generalized for any renderers to come (may there ever be more than those we currently have)
I hope I didn't miss anything in the procedure since I'm so tired xD
=> [Qt] graphixes

rpcs3/Emu/Cell/lv2/sys_rsx.cpp
This game calls sys_rsx_context_attribute before sys_rsx_memory_allocate.  This inevitably causes a crash.  So, I return that the resource doesn't exist.  Doesn't seem like a race condition because the main thread asks for the context before the rendering thread is even created. Could be wrong though so I left that in as a comment.
=> Fix Hamilton's Great Adventure

rpcs3/Emu/RSX/Common/ring_buffer_helper.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Fixes a crash in some games when using GPU texture scaling (Torque Engine)
- Mark cube map and 3D textures as separate from 2D surfaces in the cache. Also adds an error if a type mismatch is detected.
- Optimize frame storage and minimize hard sync point occurrence (vulkan). Improves framerates and makes frametimes alot more consistent.
- (Vulkan) Mark resources with frameIDs to keep drivers that buffer up frames from crashing (Mostly Nvidia)
=> rsx: More Fixes

rpcs3/rpcs3qt/gs_frame.cpp
This fixes the annoying `HEAD` git branch in master AppVeyor builds.
=> AppVeyor git branch in title fix #2

rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Cell/Modules/cellPad.h
I did some tests on a PS3 regarding the behaviour of cellPadGetData. Depending on the setting, more or less data is returned as indicated in the "length" field. If there is no change, 0 is returned as length. Enabling the motion control seems to disable this mechanism and always returns the whole buffer. I don't know if this is because the motion input alway jitters in the LSB (and therefore always changes) or if this is by design. I guess the latter because the analog inputs also jitter but have a deadzone and don't trigger a continous update.
This fixes issue #1280 (input problem in the Silent Hill HD collection).
=> Respect the controller setting when returning data from cellPadGetData.

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp
- Implement FM for interpreter fast and asmjit
- Fixes a bug in FMA/FMS/FNMS where cmpunord was used as an optimization but inadvertently broke some corner cases :p
=> spu: Fixes

rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h
This is for the linux evdev gamepads. I had to deal with gamepads sending -32767 to 32767 or 0 to 255. So, Deadzone is in the 0-128 range (default is 10). There’s a new parameter in the config_linuxjoystick.yml file, which is : Deadzone: 20. About the code : I wanted to discover cpp programming while doing something useful and easy. Feel free to critize. The conversion between int and float feels dirty, but my 2 test gamepads (xbox360 and a DragonRise custom stick) have different behaviours (ranges). Maybe someone will come with a cleaner code. Tested with a xbox360 and a custom stick on ArchLinux.
=> Add Deadzones for evdev gamepads

rpcs3/rpcs3qt/game_list.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/game_list_grid.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/welcome_dialog.ui
The layout was squished with windows scaling.
Let me know if it looks fine.
Scrolling on the gamelist (horizontally and vertically) resulted in very annoying jumps, so I set a specific value that seemed fine on my machine. Please let me know how you feel about it.
FYI you can always increase the scroll speed by holding down the ctrl button.
especially ***LINUX*** users are asked to test these things
now shows all bootable categories in gamegrid, since networking is being added
=> [Qt] fix experimental build warning layout and smoothen gamelist scrolling

rpcs3/Json/tooltips.json
Updates some outdated tooltips to better fit the most recent version of RPCS3.
Replaces some Engrish with English.
Implements full cell_ugh compatibility.
=> implement cell_ugh

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_cache.h
- Improve memory protection behavior when strict mode is off. Use full range protection without trampling shared pages instead of only checking a single page. This fixes some missing graphics in some games without requiring strict mode (id tech 5)
- Remove the broken strict mode behavior of depth range using GL
- Improve error handling, recovery and display when running vulkan (nvidia fullscreen & window resize woes)
=> rsx: Fixes

rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
Use mapped variable name, even if the register is declared as output and nothing is written to it.
(#3569)
=> RSX GLVertexDecompiler: fix undeclared diff_color and spec_color

rpcs3/Emu/RSX/VK/VKHelpers.h
- Tightens vsync control to not accept any modes that would allow tearing - including adaptive vsync.
The reason for this is that gcm is timed to control the virtual graphics controller instead of running uncapped and letting the display limit the framerate. This causes slight judder where the overhead of threads getting scheduled around means we might miss a present window. While the adaptive vsync does a good job allowing consistent frametimes, it does allow tearing to prevent judder. This PR forces true vsync. If you experience frame judder, disable the vsync option.
=> vulkan: Fix vsync

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GSRender.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
- Implements notifications from the GSFrame QWindow to the vulkan renderer thread. It is important as the renderer should pause until resizing is complete to keep some drivers from crashing when the native window suddenly changes size in the middle of drawing/presenting
- When encountering corrupt put/get registers do not discard entire commandbuffers in case there are semaphores held
=> Qt/ui/vk: Fixes

.travis.yml, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Fix src/dst framebuffer detection
- Silence some warnings
- Fix travis trying to upload appimage from private forks. Always fails if not from upstream repo anyway and detects as an error
=> rsx: Texture cache fixes

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h
- Invalidate surface store address when tile unbound
Fixes #3134 and LBP karting
- Implement readch(mfc_cmd) 
Fixes #2819
- Make dmactrl get 'readonly' 
rsx accuracy change, currently its possible to edit the get ptr from the game side and cause the rsxthread to freak out. It should only be able to be changed from the syscall, so we use an internal variable to keep track of command buffer position and write it to get ptr now
- Save and restore mfc cmd
spu accuracy change, docs state registers are in an 'undefined state' after writing to mfc_cmd, but in practice though, they are just left alone
=> Small rsx/spu fixes

rpcs3/rpcs3qt/game_list_frame.cpp
The first call to the function `SortGameList` is done before the first call of `LoadSettings` or `OnColClicked` which set values for `m_sortColumn` and `m_colSortOrder`. As such, these variables are undefined and the execution of `m_gameList->sortByColumn(m_sortColumn, m_colSortOrder);` inside the `SortGameList` function uses uninitialised values.
The solution I am offering in this PR is to initialise the member variables `m_sortColumn` and `m_colSortOrder` in the constructor, before any method is called.
=> [Qt] Fix uninitialised values before usage

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/GSRender.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
- Identify minimize/restore events as separate from regular resize and do not react to them
- Enable message queue consumption after loading the shaders cache. Also hides the frame during this step. This fixes the 'start fullscreen' bug when running vulkan
- Prevent recursive access violations that cause hanging when WCB is enabled
- Partially reverts Jarves' invalidate unbound tiled regions as it causes driver crashes and hanging in corner cases. I'll submit a more complete version soon.
Fixes https://github.com/RPCS3/rpcs3/issues/3613 and https://github.com/RPCS3/rpcs3/issues/3641
=> rsx/qt: Fixes

rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/debugger_frame.h
First pull request and first time using github so rip me if I did it wrong.
I repositioned the debugger's current instruction to be in the middle. It used to be at the top so u always had to scroll to see what came before it. Now it's smack dab in the middle.
Added a breakpoints list so you can see all the current breakpoints. That way you can navigate away from them and you dont need to remember them to remove them. Double clicking on a breakpoint entry in the list will automatically load that breakpoint address. You can remove them in bulk by selecting them and pressing Delete. Or you can right click the selection and remove them that way. You can also rename each breakpoint entry for convenience.
=> Debugger improvements

Utilities/File.cpp
Fixes issue where having paths on games.yml that point to NOT_READY drives such as empty physical/virtual disc drives returns ERROR_NOT_READY (Win32 error code 21) which was not handled in fs::error, therefore throwing an exception and crashing RPCS3.
Solves #3592
=> Handle device not ready in fs::error. Solves #3592

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/trophy_manager_dialog.cpp, rpcs3/rpcs3qt/trophy_manager_dialog.h, rpcs3/rpcs3qt/trophy_tree_widget_item.h
This PR adds the ability to easily view all trophies that you earned.
Here's a screenshot to give a better idea.
Some stuff you can do.
1. Double clicking on the columns will change how the list is sorted.  Clicking on the "Icon" will sort by game instead.
2. See trophies earned/left fast per game.
3. Change icon size (currently not saved to guisettings) to make viewing better on various DPI screens.
4. Toggle what trophies are viewed, including hidden ones, to see what you have left to earn.
5. Open the corresponding trophy directory by right clicking and selecting the dropdown option.
I'd appreciate testing, suggestions for improvements, and in general, feedback.
Please note that due to how trophies work, you can't get around the "show in manager without running" restriction.  It's …
=> Trophy Manager

README.md, rpcs3/CMakeLists.txt
- Partially revert dbf1573e890d5d0ae18ecda7e5cdc81e4dcefaa7 to bring back Qt 5.7 as the minimum requirement for Linux in the README.md file
- Update the PPA urls displayed by CMake when Qt is missing
=> Revert Qt requirements to version 5.7 on Linux in the README.md file

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_methods.cpp
This is a partial set from my rsx_volatile branch where the reorganizing of the renderers is taking too long. These are interim fixes to counter minor performance regressions and broken strict mode behaviour in rare cases before the full set is ready. Other changes include:
- Fix vulkan swap bytes behaviour (still under investigation for corner cases). Should fix the yellow/blue colors when WCB is in use
- Try to determine pixel offsets when nv308a::color is indexed with a non-zero y coordinate. Hopefully fixes bugs where shader ucode is not properly written to rsx mem leading to failing to compile shaders
=> rsx: Fixups

rpcs3/Emu/Cell/lv2/sys_ss.cpp
fixes issues with sys_ss_random_number_generator failing
=> change CryptAcquireContextW to try CRYPT_NEWKEYSET flag if key container doesnt exist already

rpcs3/Emu/RSX/Common/texture_cache.h
- Only reject framebuffer memory if it appears inside an actual texture. Ideally should destroy such textures if they exist since the framebuffer will replace the data as it is rendered to, but such a case may not even exist in practice
https://github.com/RPCS3/rpcs3/issues/3681
=> rsx: Fix for framebuffer validation

rpcs3/Emu/RSX/Common/texture_cache.h
The member `cache_tag` from the `cached_texture_section` structure is currently used at two different places:
- https://github.com/RPCS3/rpcs3/blob/4aa89132d7cf19ce486c9b36c65a82b45fc234d1/rpcs3/Emu/RSX/Common/texture_cache.h#L278 The first time, the value of  `tex.cache_tag` is uninitialized and used to do a comparison.
- https://github.com/RPCS3/rpcs3/blob/4aa89132d7cf19ce486c9b36c65a82b45fc234d1/rpcs3/Emu/RSX/Common/texture_cache.h#L294 Later, the variable `tex.cache_tag` is set, no problem for the next comparisons.
In this PR, I set a default value (`0`) to the member `cache_tag` of the `cached_texture_section` structure so it will fix the uninitialized value before to do the first comparison.
=> [RSX] Fix uninitialized value before usage

rpcs3/Emu/Cell/PPUTranslator.cpp
Minor changes which include:
- Usage of `arg_begin()` instead of `getArgumentList().begin()`. As it can be seen [here](https://github.com/llvm-mirror/llvm/blob/release_40/include/llvm/IR/Function.h#L550), the difference between these two calls is very small in LLVM 4. However, this change will help for the move to LLVM 5+ because the function `getArgumentList()` will not be here anymore (see https://reviews.llvm.org/rL298010 for more details). Also, this change was originally included in the LLVM 5 PR (#3410)  by @hcorion
- Add consistency for the following lines
https://github.com/RPCS3/rpcs3/blob/6782b2263785bc50ca175cc8afdd7896e7384e5f/rpcs3/Emu/Cell/PPUTranslator.cpp#L278
https://github.com/RPCS3/rpcs3/blob/6782b2263785bc50ca175cc8afdd7896e7384e5f/rpcs3/Emu/Cell/PPUTranslator.cpp#L293 …
=> PPUTranslator minor changes

rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/pad_settings_dialog.ui
"Significantly" was misspelled as "Significatly" in the debug tab.
"Sixaxis" was misspelled as "Sixaixs" in the pad settings.
Changed "cpu" to "CPU" because it is an acronym and should be capitalised.
Changed "keyboard" to "Keyboard" to match other window titles in RPCS3.
=> Correct two typos and a couple of other nitpicky things

rpcs3/Emu/Cell/Modules/sceNpSns.cpp
Allows Dead Island to progress further, and potentially any other games that get stuck on this.
Dead Island now no longer dies during the intro. However, for some reason, it doesn't respond to controller inputs on the gamma slider screen, so it never gets past this point.
=> Stub sceNpSnsFbCheckConfig

Utilities/git-version-gen.cmd, appveyor.yml, bin/GuiConfigs/Kuroi (Dark) by Ani.qss, rpcs3/rpcs3_version.cpp
If we're in AppVeyor and building for master:
- Fetches commit count from unshallowed upstream instead of fetching from HEAD (will always be 3 since we clone with depth of 3)
Solves #3693
=> Fixes commit count on GIT-VERSION | RPCS3 v0.0.4

CMakeLists.txt, rpcs3/CMakeLists.txt
In the file `rpcs3/CMakeLists.txt`, the variable `CMAKE_CXX_STANDARD` is used:
https://github.com/RPCS3/rpcs3/blob/c435b328c7349b7f353ec10b247eb1c45311d460/rpcs3/CMakeLists.txt#L5
This variable was introduced by CMake 3.1.0 (https://cmake.org/cmake/help/v3.1/release/3.1.0.html#properties).
The file `CMakeLists.txt` is also updated to keep the same requirement.
=> Bump CMake requirement

.gitmodules
Changelog: https://github.com/zeux/pugixml/compare/f205aaf6e1c90f1dda943edd4f82922118a85648...257fbb4e1b09b0f1a6b2020ae2db190b87c8f9c7
=> Map and update pugixml with the upstream repository instead of the one from RPCS3

rpcs3/Emu/Cell/Modules/cellGame.cpp
Ben 10 Ultimate Alien: Cosmic Destruction AVs during cellGameBootCheck, as data is written to read only memory (dirName), which contains the string "app_home".
The functionality isn't known yet, AFAIK, so this is a temp fix for the game, as data definitely shouldn't be written to that pointer
Thanks to emulator team for the report
=> cellGameBootCheck temp fix

README.md
Related #3779, Fedora needs this package to build RPCS3 correctly. I reordered the names by alphabetical order.
=> Update Fedora packages in the README file

.travis.yml, qt-installer-noninteractive.qs, rpcs3/CMakeLists.txt
- Travis will now use Qt 5.9.3 when building
- AppVeyor will switch automatically on this release when available on their servers
- Update CMake comment to recommend the Qt 5.9.3 PPA 
For more information about Qt 5.9.3: https://blog.qt.io/blog/2017/11/22/qt-5-9-3-released/
=> Update Qt to 5.9.3

.travis.yml
Should probably cache the download, but I haven't bothered yet
=> Quick fix to prevent Qt download timeout

Utilities/Config.cpp, Utilities/Log.cpp, Utilities/Thread.cpp, rpcs3/Emu/Cell/MFC.cpp, rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_event_flag.h, rpcs3/Emu/PSP2/ARMv7DisAsm.cpp, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLHelpers.cpp, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/basic_mouse_handler.cpp
=> Rebase #3692

rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/ds4_pad_handler.cpp
- Fixes potential crash in image_in when using cpu blit, or when unable to gpu scale the texture, found in #3905 
Also fixes phantom breaker: extra
- Also fixes led for ds4 when connected by bluetooth
=> rsx: image_in swizzle crash fix

.travis.yml, Utilities/git-version-gen.cmd, appveyor.yml, rpcs3/git-version.cmake
Addendum to #3728 
- Removes GIT_VERSION's incorrect commit count on non-master Pull Request builds - make GIT_VERSION only be the Commit ID in those cases (e.g: 0.0.4-abcdefgh instead of 0.0.4-3-abcdefgh)
- Unshallows AppVeyor (current depth: 3) and TravisCI clones (current depth: 50) in order to obtain proper GIT_VERSION
» Replaces previous approach of fetching upstream and obtaining its commit count on AppVeyor builds
» Fixes commit count on AppImage (TravisCI) builds
- Comment out unused unreachable code (AppVeyor) in git-version.cmake, as we build with MSVC on AppVeyor instead of CMake currently
**TravisCI clone time comparison** 
Before: ~2s  (w/ depth=50)
After: ~5.5s  (w/o depth)
=> Misc: Version adjustments

Utilities/git-version-gen.cmd, rpcs3/git-version.cmake
- Restore GIT_BRANCH removed by mistake from git-version.cmake (for AppImage builds)
- Fix commit count on Windows builds
=> Hotfix #3919

rpcs3/Emu/Cell/lv2/sys_fs.cpp
fs_open on mself files would move the file pointer, but not reset it.
Should fix some games using mself files, fixed access violation on NPEB01152
=> Fix MSELF files

rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/ds4_pad_handler.cpp
and fix DS4 error message
This should fix a bug where Catherine and other games don't receive some buttons' input.
The bug was introduced when changing the initial connection count in PadThread.cpp.
Catherine sets the port setting on boot. but because no controller was connected this was actually skipped
Here you can see that it is called once before we connect the pads
=> improve cellPadSetPortSetting

rpcs3/Emu/Cell/lv2/sys_net.h
Another tiny PR. Apparently, a socket with fd == 0 is invalid, at least according to Rage (NPEB90391).
Rage now goes ingame (from intro).
=> Set lv2_socket id_base

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
- Track last working state and reset to it if RSX starts to desync.
This is especially useful when running vulkan since the renderer will easily outpace the rest of the system when merely recording draw commands
- Ignore empty index buffer sets.
Mark empty/invalid IB sets as having 0 element counts.
This should allow RSX state to recover if invalid FIFO state is encountered. If the state causes the backend to crash this will still not catch it, but at least should help make it less common. Alot of these issues happen when RSX runs "too fast" because rpcs3 is not cycle accurate and the game isn't properly synchronized.
=> rsx: Robustness fixes

.travis.yml
We can now use
```
git:
depth: false
```
instead of
```
git:
depth: 100000
```
for an unshallow clone.
Official documentation: https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
=> .travis.yml: set git depth to false

rpcs3/Emu/Io/Null/NullPadHandler.h, rpcs3/Emu/Io/PadHandler.cpp, rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/System.cpp, rpcs3/ds4_pad_handler.cpp, rpcs3/ds4_pad_handler.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h, rpcs3/keyboard_pad_handler.cpp, rpcs3/keyboard_pad_handler.h, rpcs3/mm_joystick_handler.cpp, rpcs3/mm_joystick_handler.h, rpcs3/pad_thread.cpp, rpcs3/pad_thread.h, rpcs3/rpcs3qt/gamepads_settings_dialog.cpp, rpcs3/rpcs3qt/gamepads_settings_dialog.h, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/xinput_pad_handler.cpp, rpcs3/xinput_pad_handler.h
This also fixes a XInput connection issue, where a disconnected device would incapacitate all following devices.
You can now add profiles by just putting them into the correct folder or creating them yourselves with the corresponding button.
please test this like bosses minna
confirmations:
=> Qt/Input: Introduce profiles

bin/GuiConfigs/Darker Style by TheMitoSan.qss, bin/GuiConfigs/Kuroi (Dark) by Ani.qss, bin/GuiConfigs/ModernBlue Theme by TheMitoSan.qss
Current approach was incorrectly using the background-color property instead of color.
Using transparent color, allowing for the icon's background to be the theme's background works with darker colors, as PS3 game icons are generally made for these kind of backgrounds.
_Applies to: Kuroi, Darker Style, ModernBlue_
Before
After
=> GUI/Themes: Fix GameList Icon Backgrounds + Toolbar Icon Color

rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
Added a config option to disable shader preloading, useful for debugging/testing purposes.
Initially tried to make a 'null' shader cache but templates and inheritance don't like each very much so I gave up. 🐱
=> None shader preloading

rpcs3/rpcs3qt/main_window.cpp
According to https://www.playstation.com/en-us/support/system-updates/ps3/, the current firmware version is 4.82.
=> Update current firmware version

rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
Some games do not set mixer event queue name, which causes RPCS3 to get stuck indefinitely when creating mixer thread.
Contains magic event queue key, which at this point seems to be constant.
=> Improved check for cellsurmixer event queue

rpcs3/Emu/RSX/GSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_utils.h
- Fixes typo in emulated primitive restart, fixing graphics with some amd cards
- Fixes emu hang that could happen when rsx thread crashes/throws/exits, making sure the event queue is cleared and disabled and the vblank thread is shut down
=> Rsx: fix emulated primitive restart and hang on crash

.travis.yml
Turns out the latest version of travis now has clang 5.0 builtin, so let's use that instead for AppImages and such.
=> Use clang 5.0 in travis

rpcs3/Emu/Cell/Modules/cellWebBrowser.cpp, rpcs3/Emu/Cell/Modules/cellWebBrowser.h
Stubs some functions in cellWebBrowser and adds the init and shutdown callback. This fixes Ratchet & Clank Quest For Booty [BCES00301] which was previously stuck before the menus. Now it gets past the menus to some weird limbo ingame state, but only if you create a new game.
Thanks to @elad335 for git counselling :)
=> Stub some functions in cellWebBrowser

rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
B8 render targets were not swizzled. Those fixes address it.
RRR1 (VK) and 1RRR (OGL) at the recommendation of KD-11. This is now consistent with B8 textures swizzling, since RRRR created alpha issues in Persona.
Image with fix
Image without fix
=> Fix to B8 format render target swizzling. Fixes VF5 red objects.

rpcs3/Emu/RSX/overlay_controls.h, rpcs3/Emu/RSX/overlays.h
Disallow you from selecting a save to load when there are no saves. This is more in line with how the QT save dialog works and fixes fatal access violation in Ratchet & Clank 3 (and probably in more games).
=> Fix native UI save_dialog when there are no saves

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h, rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/GL/OpenGL.cpp, rpcs3/Emu/RSX/GL/OpenGL.h, rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp, rpcs3/Emu/RSX/rsx_cache.h
- Implements swap control on linux when using openGL
- Fixes the epsilon value that was replaced with decimal to fix nvidia issues back to the old value. It has to be very very small, 1.E-5 is not small enough, but 1.E-10 works well enough.
- Fix a race condition during startup using qt dialogs
- Clean up shaders by removing as much clutter as possible and only compiling subroutines actually used by the program. Makes decompiled spirv easier to read and should hopefully mean less work for the drivers as well.
- Reuse sampler objects (vulkan) to avoid too many create/delete cycles. Wont do much for performance but its the right thing to do and it makes debugging alot easier.
- Removes subpass dependencies on vulkan. They have a very high cost on AMD GPUs especially older GCN1 and maybe …
=> [Needs testing on GCN3+] Minor Fixes

rpcs3/Emu/Cell/Modules/cellRec.cpp, rpcs3/Emu/Cell/Modules/cellVideoExport.cpp, rpcs3/Emu/Cell/Modules/cellVideoUpload.cpp, rpcs3/Emu/Cell/Modules/cellVideoUpload.h
Improved games in specific cases like video recording, exporting or uploading. Please note this pull request doesn't add any of these features but instead reduce possibilities of crash or freeze when using the related functions.
Sample games tested:
=> [HLE] Add callbacks for cellRec, cellVideoExport and cellVideoUpload

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/GL/GLTexture.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- gl: Use correct target for type when creating new textures. They are not always 2D
- gl: Track stale cache entries for deleted textures. Avoids invalid texture getting bound to the pipeline when wcb is enabled
- vk: Implement texture barrier for framebuffer feedback situations if strict mode is disabled. Strict mode bypasses all of this and just makes a duplicate copy which is the safest way to avoid the memory access hazard.
- rsx: Improve framebuffer setup code. If pitch is 64, check the log2 dimension bits instead to determine size.
https://github.com/RPCS3/rpcs3/issues/4132
=> Compatiblity fixes

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
msgString would be dereferenced even when it is null because the rsx overlay code was put in before the argument checks.
Fixes Sonic Adventure regression.
=> Hotfix: core/HLE: Fix cellMsgDialog null pointer dereference

appveyor.yml
* Various formatting and changes to the file structure (mainly `cmd -> powershell` for better readability).
* Updated versioning - rpcs3 latest release tag is now fetched using `git describe`, no need to manually update `appveyor.yaml` for each release or milestone.
* Updated Qt to version 5.10.0.
* Added a __separate__ OpenSSL artifact containing the required libs to make compat DB fetching work. These binaries are distributed by AppVeyor as part of the build env. Users can be directed to download and extract the binaries to their local rpcs3 dir (e.g. in the quickstart guide). A warning can also be included regarding legal issues pertaining to using OpenSSL, if any.
* Package artifacts using `7z` format, reduces rpcs3 artifact size from ~20MB to ~14MB.
* Compat DB is fetched and …
=> AppVeyor Overhaul

rpcs3/Emu/Cell/Modules/cellPhotoExport.cpp
Reduce crashs or freezes when calling photo exporting functions.
Sample games tested:
=> Add callbacks for cellPhotoExport

rpcs3/Emu/Cell/Modules/sceNpMatchingInt.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUModule.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
Manually load _libsysutil_np.sprx_ in the cpu settings then boot a game and check logs using trace level.
**Master**
! LDR: **** sceNpMatchingInt export: [0x170829D3] at 0x84d9f8
! LDR: **** sceNpMatchingInt export: [0x474B7B13] at 0x84da80
! LDR: **** sceNpMatchingInt export: [0xB00F408A] at 0x84dab0
! LDR: **** sceNpMatchingInt export: [0xE61F7EE9] at 0x84da08
**With this PR**
! LDR: **** sceNpMatchingInt export: [sceNpMatchingGetRoomMemberList] at 0x84d9f8
! LDR: **** sceNpMatchingInt export: [sceNpMatchingJoinRoomGUI] at 0x84da80
! LDR: **** sceNpMatchingInt export: [sceNpMatchingGetRoomListGUI] at 0x84dab0
! LDR: **** sceNpMatchingInt export: [sceNpMatchingSendRoomMessage] at 0x84da08
=> Add sceNpMatchingInt

Utilities/File.cpp
I have a bunch of symlinks in `$rpcs3/dev_hdd0/disc` to my network drive. If I don't have that drive mounted, I get:
```
$ ./bin/rpcs3
terminate called after throwing an instance of 'std::runtime_error'
what():  Verification failed (e=2): dir::read
(in file /home/zekesonxx/bullshit/rpcs3/Utilities/File.cpp:1261)
[1]    14339 abort (core dumped)  ./bin/rpcs3
```
which is less than pleasant.
Now rpcs3 will fail gracefully on broken symlinks.
Q. Why doesn't this log or something when it fails to get metadata?
1. File.cpp doesn't have Log.h included, feels like a waste just for this
2. It already doesn't log if it fails to readdir
3. If `fs::dir::open` fails, and it matters, whatever is calling it will log a more useful error anyways.
4. `[8:11 PM] Megamouse: then just ignore it.`
addendum: …
=> Make fs::dir::open return false on failed metadata instead of crashing

rpcs3/Emu/Cell/MFC.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
- remove redundent and harming check from tag update completion type 2 condition
- implement stop code 0x100 , fixes #2456 
- add a missing check in sys_spu
=> [spu] random fixes

rpcs3/rpcs3qt/game_list_frame.cpp
scrollafter is useless in gamegrid, because the currentIndex was reset after PopulateGameGrid, so just ignore it.
should fix #4180
=> Qt: fix gamegrid scroll

rpcs3/rpcs3qt/debugger_frame.cpp
this allows the spu disassembler to nicely wrap around addresses instead of reporting "illegal address" on addresses outside of LS and resolves potential memory conflicts with main storage memory in the debugger.
=> Clamp spu address [disasm]

.travis.yml, appveyor.yml, rpcs3/rpcs3_version.cpp
* Make Travis upload appimages for real this time. Hopefully.
* Expose AppVeyor versioning env vars, these can be retrieved via API or deployment.
* Update AppVeyor build version to (almost) match artifact versions.
* Version bump.
=> RPCS3 0.0.5: Versioning Changes (Hotfix)

rpcs3/Emu/Cell/SPUInterpreter.cpp
- Optimize floating point exception checking : 
read once the MXCSR register and use his value to check for all exceptions.
- Optimize setting the floating point's rounding mode with constant values ( also the first commit ) ,cause the compiler won't do it on his own ,as tested in [godbolt](https://godbolt.org/g/Ao7Wmt) .
=> [spu] random optimizations

rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/Modules/cellGame.h
fixes psn rac quest for booty to actually boot, thanks to @hcorion for finding it
The mentioned game ('NBA 08 Live Demo') in the comment of the function was tested, and still works the same
=> cellgame: Fix cellDiscGameGetBootDiscInfo return values

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
Moving alpha test outside of fp_main. 
This enforces alpha test is still done even if shader asm has early return
Fixes kh2 timeless river world transparency
=> rsx: Fix alpha test on VK/GL

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
The stack wasn't getting reset between interrupt calls with raw spu's, leading to a stack overflow in some cases. Fixes vancouver booting, now gets to at least main menu
Test is here for those curious https://github.com/jarveson/rpcs3elfs/tree/master/raw_spu_test/stack_addr 
I added the reset as a 'ppu_cmd' as it seems like a kinda one-off, I didn't see any other places the stack should also be reset
=> Fix raw spu interrupt thread overflowing

Utilities/Thread.cpp
#4268 followup.
```
Utilities/Thread.cpp:1644:2: error: use of undeclared identifier 'pthread_setname_np'; did you mean 'pthread_set_name_np'?
pthread_setname_np(pthread_self(), m_name.substr(0, 15).c_str());
^~~~~~~~~~~~~~~~~~
pthread_set_name_np
/usr/include/pthread_np.h:58:6: note: 'pthread_set_name_np' declared here
void pthread_set_name_np(pthread_t, const char *);
^
=> Unbreak build on BSDs

rpcs3/Emu/RSX/GL/GLHelpers.h
Fixes #4307 
> So, about GL_CLIENT_STORAGE_BIT:
> - On NVIDIA, DMA CACHED memory is used when this flag is set. SYSTEM HEAP
>   memory is used without it, which (in my testing) is much faster.
> - On Mesa, GTT is used when this flag is set. This is what we want- we
>   upload to VRAM occur otherwise, which is unusably slow (on radeon).
Source: https://github.com/acomminos/wine-pba/commit/87307b1b9093c769d21d0803bb122b9866bb887c
> 22:10 gregory38: hum it seems AMD use GTT when GL_CLIENT_STORAGE_BIT is set (for write)
> 22:10 gregory38: otherwise VRAM
> 22:11 gregory38: with extra flags for write-combining and cpu access 
Source: https://people.freedesktop.org/~cbrill/dri-log/index.php?channel=nouveau&date=2017-02-03
=> Restore performance for some of the radeon with Mesa

rpcs3/Emu/RSX/RSXTexture.cpp
Original fix by pauls-gh.
Fixes black characters in Tales of Vesperia. It doesn't fix the text as he initially thought, unfortunately.
May fix or break other games, testers welcome.
=> rsx: Typo fix

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/game_list_grid.cpp, rpcs3/rpcs3qt/gamepads_settings_dialog.cpp, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/log_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/qt_utils.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.h, rpcs3/rpcs3qt/settings_dialog.ui
- add possibility to hide/unhide apps by serial (Rightclick on entry -> Hide From Game List)
- add possibility to show hidden apps (View -> Show Hidden Entries)
- clean the hidden entry list from garbage serials on full refresh
- optimize the gamelist/grid entry filter (I hope it is faster like that)
- remove some spaces in guisettings
- add missing visual studio filters for some module headers
- clean up gui_settings.h: move the compat_status struct to game_compatibility.h
- clean up gui_settings.h: move general functions to qt_utils.h
- replace get_single_line workaround with QString::simplified() - I hope this does not create unexpected titles
- initially sort gamelist case insensitive. should fix #4306 
- add option "Show shader compilation hint" to Settings->Emulator. should fix …
=> rsx/Qt: add option to hide shader compilation hints + add option to hide game list entries + misc

rpcs3/Emu/Cell/lv2/sys_fs.cpp
- Fixes #4275 (E.X. Troopers regression)
- Fixes #3327 ~@jjsat can you confirm please ?~
=> sys_fs: returns the correct error value when the path is 0 or an empty string

rpcs3/git-version.cmake
Use STREQUAL to check ${match} to be empty string, instead of using EQUAL to compare by value.
=> Fix git-version.h not correctly updating.

Utilities/sysinfo.cpp, Utilities/sysinfo.h
A Fix for Issue #4323, where now in addition to the CPU Capabilities, the OS Support is also queried when checking for AVX/AVX2/AVX512 availability.
This is done by an additional check to the XCR_XFEATURE Register using the xgetbv instruction. Since this is not present on some older CPU's, we first need to check for it's availability with CPUID EAX=1 for bits 26 and 27 in ECX.
Tested on my System with an i7 7800X and Win8.1 (with support for AVX/AVX2 but not for AVX512), where avx/avx2 are still enabled, but avx-512 is now correctly disabled. Might require further testing on machines where AVX512 is confirmed to work as well as on linux.
=> Fix missing Detection for AVX OS Support

rpcs3/CMakeLists.txt, rpcs3/Emu/RSX/GL/OpenGL.cpp
- `LOG_UNIMPLEMENTED` does not exist, replaced by `LOG_ERROR`
- Add X11 as a required package for UNIX system in cmake and include necessary files for compilation
With these changes, it is possible to build RPCS3 without LLVM support on OSX.
=> Partial compilation fixes for osx

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp
- Check get start type proxy mfc commands :
crysis 1 (**nothing => Intro**)
crysis 2 (**nothing => Inagme**)
- Dont check prio if spu group type is 0x20 in sys_spu_thread_group_create
far cry 4 (**loadable => Intro**)
F1 race stars (**nothing => Intro**)
- Fix spu image loading address calculation
harry potter 7 part 1 (**nothing => Intro/Loadable** (depends on luck lol))
fixes #3834
Originated from raw fixes pr but neko wants a quike review and merge.. 😂
=> spu: quike fixes

Vulkan/Vulkan-build/pre-build.bat, rpcs3/Emu/RSX/Common/GLSLCommon.h
- Noticed while looking through ngs1 traces that the fog distance was negative due to `(scale * coord)` being less than the bias variable (equation is generally `scale * coord + bias` and bias can be negative with some equations). Opened as a separate PR to make testing easier.
=> rsx: Clamp negative fog distance

rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
Some users were repeatedly using Interpreter (fast) simply because of it having (fast) in the name, Hopefully this won't bring too much discussion about the best wording. Even though it is faster than the precise interpreter I don't think further clarification on speed is needed.
=> Update settings to indicate speed differences between Interpreters and Recompilers for less confusion

rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Disable fence reset on gcn1 - gcn3
- Enable polaris+ workarounds on linux if proprietary driver is used
External issue report https://community.amd.com/thread/227036
On older GCN, calling vkResetFence can randomly hang the GPU causing a full driver crash and a TDR reset. A workaround is to just discard the fence and create a new one from scratch every time we're done using it.
=> AMD vulkan workarounds improved

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/settings_dialog.ui
- fixes small regression where icons would not show in the gamelist
- small layout adjustments and renames
- remove some redundant code
=> Qt: minor fixes

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
Fixes the following issues on Tales of Vesperia which requires SRM.
- Blacked out scene after the sleeping dog now renders correctly
- Ghosting effect. The ghosting was most noticeable as a delay between the character rendering and the cell shading around the character. This appears to be gone with this change.
=> Strict Rendering Mode (SRM) fix for Tales of Vesperia. Move old surface copy before texture upload.

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/RSXTexture.cpp, rpcs3/Emu/RSX/RSXThread.cpp
- Disable gamma control on depth and the special non-rgb texture formats
- Implement B8 remap override (HW tests pending)
- Fix some copypastas in glsl emitter
Fixes https://github.com/RPCS3/rpcs3/issues/4351
=> rsx: Minor format fixes

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.h, rpcs3/Emu/RSX/overlays.h
Don't display new data when unnecessary (bug fix)
Use new data icon/title if provided by the game
Minor cellSaveData cleanup
=> Improve save data dialog

rpcs3/CMakeLists.txt, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/gui_settings.cpp
`-Wno-invalid-pch`
was added because it was spammed constantly by gcc on Arch Linux.
`-Wno-unused-command-line-argument`
was added because it was occasionally spammed, during the build.
=> Load stylesheets properly when in AppImage or make install

rpcs3/Emu/Cell/Modules/cellVdec.cpp
Fixes issue #2930, only tested on the intro cutscene.
=> cellVdec: Do not decode next frame during end_sequence

rpcs3/Emu/RSX/overlays.h
Fixes issue #4420 
It looks like some games may provide an icon resource, but they don't always provide a save title for creating a new save. Odd behavior, but it is what it is. on Uncharted, it looks like the data gets overwritten afterwards by the game, cause if I load a newly created save made with this pr it has all the names and metadata.
I'm open to suggestions as to the correctness of my implementation.
=> Minor bugfix

rpcs3/CMakeLists.txt, rpcs3/rpcs3.appdata.xml
Description was copied from https://rpcs3.net and https://rpcs3.net/about
See: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html
for more information about AppStream metadata.
The main motivation for this was so that we can get a nice description on https://appimage.github.io/RPCS3/
=> Add AppStream metadata for linux

.travis.yml
Fixes #4414 and possible also 4427, though I think that's a different issue.
Basically, this makes libstdc++6 load only ubuntu 14.04, and uses the distros's lib otherwise.
If you want more details on the actual implementation, check out:
https://github.com/darealshinji/AppImageKit-checkrt/compare/master...RPCS3:master
=> Fix AppImages for distros that are not ubuntu 14.04

rpcs3/Emu/Cell/Modules/cellGame.cpp
The CellGameDataStatCallback in Cross Edge expects setParam to be initialized and thus died on null dereference. Initializing it fixes Cross Edge [BLUS30348] and probably the Korean version [BLKS20112] as well.
=> Fix Cross Edge

rpcs3/Emu/Cell/Modules/cellAdec.cpp
Compatibility with the new ffmpeg version 4.0. See e.g. https://github.com/twitter/vireo/issues/11
Also `av_register_all`, `avcodec_register_all`, `frame->pkt_pts`, `avcodec_decode_video2` are marked as deprecated, but they still work.
=> Fix build with ffmpeg 4.0

rpcs3/Json/tooltips.json, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
Added an option to disable Discord Rich Presence. I found this way of doing it to be the most compatible with the current code. You could also move the initialization to the Boot function, and then terminate it after you close the game. That way it's never even initialized if the option is off. Also does anyone know why the tooltip isn't working?
=> Add Rich Presence option

rpcs3/Emu/Cell/Modules/cellSubDisplay.cpp
It simulates the fact we don't have a remote play device registered.
Affected Games:
Screenshots:
=> hle: make cellSubDisplayInit returns CELL_SUBDISPLAY_ERROR_ZERO_REGISTERED

rpcs3/rpcs3qt/settings_dialog.ui
All of the other PPU and SPU Decoders have something in parentheses next to them, so I added 
"(experimental)" next to the SPU LLVM Recompiler so it doesn't look weird.
=> Added "(experimental)" next to the SPU LLVM Recompiler

Utilities/JIT.h
Regressed by #4580. See [error log](https://ptpb.pw/yCeF). GCC/libstdc++ probably bootlegs `<array>` via another header unlike clang/libc++.
=> Unbreak build on FreeBSD

rpcs3.sln
Previously needed to manually build the `xxhash` project before emucore (linker error).
=> Fix Windows build

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/RSXThread.cpp
- Memory protection fixup. Fixes flickering and missing stuff in some games especially if wcb is enabled.
- Optimize a check in main rsx loop to restore performance lost in https://github.com/RPCS3/rpcs3/pull/4611
- Fix openGL wcb regression ('unreachable' assert)
=> rsx: Fixup

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/Modules/cellGcmSys.h, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/Memory/Memory.cpp, rpcs3/Emu/Memory/MemoryBlock.h, rpcs3/Emu/RSX/RSXThread.cpp
Allow sys_mmapper to unmap rsx mapped memory - a little background
from hw testing, when `sys_mmapper` unmaps memory that was mapped to rsx memory, it notifies the kernel that this memory can be remapped for rsx later on, doing that fixes `cellGcmMapMainMemory` offset return values.
the fix for this was different in hle and lle `cellgcm`
`cellgcm` hle fix- set memory "unmapped" status values in the rsx offset table in `sys_mmapper` and check them later in `cellGcmMapMainMemory`.
`cellgcm` lle fix- notify the gcm interrupt thread about freeing rsx mappped memory in sys_mmapper
(credit to @jarveson for figuring out how sys_mmapper communicates with cellgcm, I figured the data's encryption in the notification event and how the gcm knows the address and the size of the memory that was …
=> Rsx: Naughty fixes

rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
it seems like `sys_mmapper_map_shared_memory` checks address alignment not based on the alignment specified by mem_id, but from it's address region's. (that is specified with `sys_mmapper_allocate_address`).
quite a few games are in the nothing catagory because of it ha.
testcase : https://github.com/elad335/myps3tests/tree/master/ppu_tests/sys_mmapper
example games : PES 2016, 2017, 2018
=> fix memory mapping alignment

Utilities/CPUStats.h, Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/Emu/RSX/GL/GLOverlays.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
This is meant to be a **user-oriented overlay** for getting **real-time performance metrics.**
See discussion in #4500 if you want to see how the design progressed.
* Other than **FPS**, **frametime** and **RSX Load**, it includes new stats:
* **How much the PPU, SPU or RSX emulation takes a toll on your CPU.**
* **How many thread there are, for each of the above.**
* **Total (process) CPU usage.**
* It makes use of kd's native overlay system so can look much better than the debug overlay.
* I've made 5 "presets", each one with with different levels of detail.
* The following are configurable via the config file as of now:
* Detail level (preset)
* Update interval of the metrics
* Size (dictated by font size)
These will soon(tm) be configurable via GUI (in another PR), for now they're …
=> Performance Overlay

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/rsx_methods.cpp
- Evade semaphore acquire deadlock by constantly pinging rsx thread during spinwait to check for cyclic dependencies. Sometimes, the very thread that is supposed to wake rsx is stuck waiting for rsx to consume an event.
- Simplify task queue management and use yield instead of busy_wait to hopefully reduce audio stutter on i5s.
- Fix silly bug causing native UI crashes when trophy popup closes.
=> More stuff

rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
This is mainly to make space in the emulator tab for overlay stuff
=> Qt: Add a gui tab and performance overlay options to the settings dialog

rpcs3/Emu/Cell/Modules/cellMsgDialog.h, rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLProgramBuffer.h, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKProgramBuffer.h, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/rpcs3qt/msg_dialog_frame.cpp, rpcs3/rpcs3qt/msg_dialog_frame.h
Use all available threads during the initial shader compilation process in hopes of speeding it up.
The code is mostly unchanged and has multi-threading essentially hammered into it. The result isn't exactly pretty but hey, it works.
Multi-threaded path in Vulkan only, at least for now.
=> Parallel shader cache loading

README.md
Addresses #4695 
@hcorion Double check pls thx
=> Update Arch install directions, and other touchups

README.md
Needed for evdev and ALSA support when building on recent Fedora releases.
=> Add additional Fedora dependencies

rpcs3/Emu/Cell/Modules/cellGame.cpp
The disc versions of Aliens: Colonial Marines [BLES01455], [BLUS30862] needs the temporary game directory returned from cellGameCreateGameData to be on `dev_hdd0` because of async cellfs stuff. So I [tested](https://github.com/isJuhn/ps3tests/blob/master/cellGameCreateGameData/expected.txt) what the path was on a real ps3. It turns out the temporary path is in fact on `dev_hdd0`. 
I tried for a bit to replicate the directory name but got tired of how time is handled in C++. If anyone knows how to get a `yyyymmddhhmmss00usec` string then I'll be sure to modify the PR. But as long as the path is unique, which it will be with this PR, it should be good.
Loadable -> Ingame
=> Fix cellGameCreateGameData temporary directory path

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_utils.h
_**Ugh. MSAA needs another rewrite**_
- Performs MSAA resolve during framebuffer persistence transfer (strict mode) allowing the samples to live on correctly in their descendants.
- Perserve MSAA fetch state separate from write state to preserve the AA flag across memory respecifications. Some applications use evil hacks to play around with AA memory.
Other fixes
- amdvlk: Avoid use after free (vkFence)
- Reimplement depth texture scaling using vulkan. Allows proper MSAA resolve by preserving stencil contents.
- Fix a rendering bug when FIFO reordering is disabled
- Allow overlays to accept multiple image inputs
See https://github.com/RPCS3/rpcs3/pull/4692
=> "Simple" fix

rpcs3/Emu/Cell/Modules/cellMsgDialog.h, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/System.h, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h, rpcs3/rpcs3qt/msg_dialog_frame.cpp, rpcs3/rpcs3qt/msg_dialog_frame.h
Fixes Qt Dialog progress bars never reaching 100%.
Switches weird progressvalue int pointer to int.
Handle file access error in cellSaveData by returning an error.
Remove old code for the ppu compile wall of dialogs.
Add taskbar progress to all progressbar dialogs (Qt dialog AND native UI).
=> minor dialog fixes

3rdparty/stblib/stb_image.h, 3rdparty/stblib/stb_truetype.h
**3rdparty**
- Update stb_image.h
> 2.19  (2018-02-11) fix warning
> 2.18  (2018-01-30) fix warnings
> 2.17  (2018-01-29) bugfix, 1-bit BMP, 16-bitness query, fix warnings
> 2.16  (2017-07-23) all functions have 16-bit variants; optimizations; bugfixes
> 2.15  (2017-03-18) fix png-1,2,4; all Imagenet JPGs; no runtime SSE detection on GCC
> 2.14  (2017-03-03) remove deprecated STBI_JPEG_OLD; fixes for Imagenet JPGs
> 2.13  (2016-12-04) experimental 16-bit API, only for PNG so far; fixes
> 2.12  (2016-04-02) fix typo in 2.11 PSD fix that caused crashes
> 2.11  (2016-04-02) 16-bit PNGS; enable SSE2 in non-gcc x64
RGB-format JPEG; remove white matting in PSD;
allocate large structures on the stack;
correct channel count for PNG & BMP
- Update stb_truetype.h
> 1.19 (2018-02-11) GPOS kerning, …
=> 3rdparty: update stb_image.h and stb_truetype.h

rpcs3/Emu/Cell/PPUTranslator.cpp
The amount to shift was wrongly extracted from the opcode. The amount to shift in bytes is stored in 121-124, which means the amount in bits (which we need) is in bits 121-127. The lowest 3 bits just have to be masked out.
Unbreaks the vertices in Deus Ex Human Revolution and Batman Arkham Asylum (checked with the demo) from #2909.
=> Fix VSLO and VSRO in the LLVM PPU recompiler

rpcs3/Emu/Cell/Modules/cellGame.cpp
The disc version of Game of Thrones: A Telltale Games Series [BLES02215] is dumb and calls `cellGameContentPermit` on gamedata without calling `cellGameCreateGameData` first. We used to return the path to a non-existing gamedata folder which made the game think everything was fine and it dies. I made a [test](https://github.com/isJuhn/ps3tests/blob/master/cellGameContentPermit/expected.txt) and as expected we shouldn't set the path in such cases, just remove the `content_permission`.
Loadable -> Ingame (maybe playable?)
Thanks to Deminating for testing and the screenshot.
=> Fix dumb games

rpcs3/Emu/System.h
As requested by Asinine. Breaks several games (Kingdom Hearts, Top Spin 4, several other 2D games) and generally hurts more often than it helps.
=> Disable GPU Texture Scaling by default

rpcs3/Emu/Cell/lv2/sys_spu.cpp
Not all function should checks for the type - sys_spu_thread_connect_event would fail valid queues.
Fixes [Dynasty Warriors: Gundam [NPUB90025]](https://forums.rpcs3.net/thread-178927.html)
=> Fix sys_spu_thread_connect_event

Utilities/sysinfo.cpp, Utilities/sysinfo.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
thanks @NeoRetro
I'll open this PR so we can get this finally merged.
=> implement "Enable TSX" combobox

rpcs3/Emu/Cell/SPUThread.cpp
fixes #4614 
only the first 15 bits of the list transfer size are being used.
I also tested if the mfc stalls when turning on one of the reserved bits on the list element, it doesn't.
this allows to pass the cutscene on hitman sniper challenge.
[testcase](https://github.com/elad335/myps3tests/blob/master/spu_tests/list%20transfer%20size%20(LTS)%20bits/expected.txt)
=> mfc: clamp list transfer size

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp, rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp, rpcs3/Emu/RSX/VK/VKTextOut.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.h, rpcs3/VKGSRender.vcxproj, rpcs3/VKGSRender.vcxproj.filters
- vk: Implement type-agnostic transfer (e.g rgba16f to rgba8 memory). Fixes lighting in some situations
- vk: Introduce compute transactions to offload some calculations from the cpu. This is still very barebones and integration is not finalized.
- Minor theoretical fixup for texture cache
- rsx: Improve read prediction for synchronized resources (wcb or blit engine). Significantly reduces the number of hard faults and lowers latency by eliminating unexpected readback
- vk: Fixup for RADV driver
=> rsx: stuff

rpcs3/rpcs3qt/game_list_frame.cpp
fixes https://github.com/RPCS3/rpcs3/issues/4776
=> Qt: add boot by pressing enter or return while having an item selected

rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
I forgot that the gs_frame's taskbar progress will stay unchanged due to its persistence, unlike the msgdialog.
requesting review from @KD-11
=> Qt/RSX: reset gs_frame taskbar progr. when closing native progr. dialogs

Utilities/JIT.cpp, rpcs3/Emu/Cell/Modules/cellSsl.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/vfs_dialog.cpp
Detailed description is under construction.
=> SPU: improve analyser [WIP]

rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/System.cpp
Needs lib loading mode set to none.
=> PS1 Classics

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
The RSX context allocation address isnt constant, it changes based on what address range is available at the time of the RSX device map, starting at address `0x40000000`.
this fixes vsh assuming the RSX base context address is `0x60000000` and crash because we only take care of `0x40000000` base.
[testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/RSX%20base%20context%20address) tries to allocate address using `sys_mmapper_allocate_address` and *then* calls `sys_rsx_device_map`, returned context address is `0x50000000`.
=> Rsx: fix hardcoded rsx allocation address

rpcs3/Emu/RSX/RSXThread.cpp
The command's io address was translated and validated twice.
Once in `ReadIO32(internal_get);` , the other in `RSXIOMem.RealAddr(internal_get);`.
=> Rsx: more efficient command reading

llvm_build/make_paths_relative.py
This is a simple PR that just cleans up some python code.   
I noticed git-clang-format was python2 only.   I can get that working with Py3 if that is desired.
=> White space and switch to .format() strings

.travis.yml
Not sure why the AppImages are bundling xcb stuff, but this removes them, and as a bonus decreases AppImage size.
=> Fix issues with AppImages and Mesa 18.1.1 and greater. Fixes #4509

rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- dont remove cache directory after clear, only clear cache dir's content.
- Fix cache dir path returned 
- Fix 'error' code returned in cellSysCacheMount
the [testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/Cellsyscache) I created tries to create cache dir twice, first error code is `CELL_SYSCACHE_RET_OK_CLEARED` (0), second is `CELL_SYSCACHE_RET_OK_RELAYED` (1)
then tries to create file.txt inside the folder cache, clear cache, and trying to get that file again, this fails with `CELL_ENOENT`, indicating the deletion of the file.
but recreating the file works and returned `CELL_OK`, indicating that the cache dir is NOT removed and is still usable.
fixes #4470
pinging @Kravickas to retest
=>  Fix cellSysCacheClear

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/Common/ShaderParam.h, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h, rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/RSXVertexProgram.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.h, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_utils.h
**Details**
- Fix nv308a::color implementation
- Vertex program decompiler : Fix branch target extraction
- Vertex program decompiler : Fix double destination writes
- Vertex program decompiler : More human-readable code generated from masked writes
- Vertex program analyser rewritten [WIP]
- Silence unnecessary log spam (https://github.com/RPCS3/rpcs3/issues/4398)
**Results**
- Fixes https://github.com/RPCS3/rpcs3/issues/3323
- Largely reduces number of generated shaders in some titles with infinite compilation. Corner cases exist so some titles still try to generate new shaders but they are actually false positives (they are not actually saved to the cache at all). This will be fixed before merge.
~~NOTE: Contains the patch from https://github.com/RPCS3/rpcs3/pull/4830. This is not a …
=> rsx: Program Fixes

rpcs3/CMakeLists.txt, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
Tests from https://github.com/RPCS3/ps3autotests/
**fnmsub (ppu)**
|   | Success  | Total  | Accuracy  |  
|---|---|---|---|
| Master LLVM  | 8549 | 10648 | 80.29%  |  
| PR LLVM  | 10301 | 10648 | 96.74% | 
| Master Fast  | 8897 | 10648 | 83.56%  |  
| PR Fast | 10648 | 10648 | 100% | 
**fnmsubs (ppu)**
|   | Success  | Total  | Accuracy  |  
|---|---|---|---|
| Master LLVM  | 8893 | 10648 | 83.52%  |  
| PR LLVM  | 10646 | 10648 | 99.98% | 
| Master Fast  | 8893 | 10648 | 83.52%  |  
| PR Fast | 10646 | 10648 | 99.98% | 
**vnmsubfp (ppu)**
|   | Success  | Total  | Accuracy  |  
|---|---|---|---|
| Master LLVM  | 2857 | 10648 | 26.83%  |  
| PR LLVM  | 10354 | 10648 | 97.24% | 
| Master Fast  | 2983 | 10648 | 28.01%  |  
| PR Fast | 10641 | 10648 | 99.93% | 
**dfnma (spu)**
|   | …
=> ppu/spu: improve accuray of some instructions

rpcs3/Emu/Cell/SPUThread.cpp
this add a missing check for barrier type transfers when processing the command queue, making these commands wait until the previously issued commands from the same tag group complete.
[testcase](https://github.com/elad335/myps3tests/blob/master/spu_tests/barrier%20commands/)
=> fix barrier type mfc transfers

rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Errors were caused by game developers multiplying amount of free kilobytes by 1024 to reach amount of free bytes in hard drive.
Because RPCS would fake exactly 40GB this would result with an overflow, returning a size of 0:
(40 * 1024 * 1024) * 1024 & 0xffffffff == 0
By reducing it to 40GB-1 kilobyte, the overflow result would be very large, and checks won't fail.
=> Fix "Not enough space in hard drive" errors

Utilities/JIT.cpp, rpcs3/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/RSX/Common/ShaderParam.h, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
Compilation fixes for old versions of Clang, still supported by RPCS3.
- Error on 3.8: 
```
../Utilities/JIT.cpp:472:11: error: no viable conversion from returned value of type 'unique_ptr<llvm::WritableMemoryBuffer, default_delete<llvm::WritableMemoryBuffer>>' to function return type 'unique_ptr<llvm::MemoryBuffer, default_delete<llvm::MemoryBuffer>>'
return buf;
```
- Error on 3.7:
```
../Utilities/JIT.cpp:16:19: error: use of undeclared identifier '_XABORT_RETRY'
c.test(x86::eax, _XABORT_RETRY);
```
- Error on 3.6:
```
../rpcs3/Emu/Cell/Modules/cellGcmSys.cpp:31:41: error: no matching constructor for initialization of 'vm::ptr<CellGcmDisplayInfo>' (aka 'vm::_ptr_base<CellGcmDisplayInfo, unsigned int>')
vm::ptr<CellGcmDisplayInfo> gcm_buffers{ vm::null };
```
About the cmake change, …
=> Clang compilation fixes

rpcs3/CMakeLists.txt, rpcs3/rpcs3.vcxproj
This fixes VS builds when the path to the project contains spaces.
=> VS: Fix QT deploy for paths with spaces

rpcs3/Emu/Cell/lv2/sys_time.cpp
add EFAULT checks for sys_time_get_current_time, the order of the checks is based on the firmware.
fixes #4901 , gets this game from loadable into intro.
=> Fix sys_time_get_current_time

rpcs3/Emu/Audio/Pulse/PulseThread.cpp
Hello,
per https://github.com/RPCS3/rpcs3/issues/4909 I've been having issues with PA when not using downsampling, PA would simply not connect.
This patch makes it work for both downsampling and standard surround. The map is currently taken from channelmap.c from PA, in the PA_CHANNEL_MAP_ALSA case but that may be wrong. If someone knows the correct PS3 surround mapping or where to find it, please tell me. If not, a homebrew that tells the channels would be great too.
This is what I found without the patch/without a map:
- PulseThread::Open calls pa_simple_new
- pa_simple_new calls pa_stream_new
- pa_stream_new calls pa_stream_new_with_proplist
- pa_stream_new_with_proplist calls pa_channel_map_init_auto
- in pa_channel_map_init_auto def is PA_CHANNEL_MAP_AIFF, the default for …
=> Add a channel map to the PA backend to fix surround sound

rpcs3/Emu/RSX/Common/ProgramStateCache.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLHelpers.h, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/GL/GLTexture.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h
- Remove static image-view pairings for regular texture uploads. Transition to a multiview format like already existing for rendertargets.
- Minor cleanup and optimization in preparation for some upcoming changes.
This PR restores OpenGL performance largely lost in the Async PR that adds async recompiler. Also fixes the black ground textures in some Atelier games.
=> rsx: Fix multi-remapped textures, Restore OGL performance, OGL cleanup and FIFO optimizations

rpcs3/Emu/Cell/PPUInterpreter.cpp
Results based on this test: https://github.com/RPCS3/ps3autotests/blob/master/tests/cpu/ppu_vpu/ppu_vpu.cpp
```
vec_vaddsws (441 tests):
[master-precise] Matches: 372 (84.35%)
[pr-precise] Matches: 441 (100.00%)
vec_vadduws (441 tests):
[master-precise] Matches: 294 (66.67%)
[pr-precise] Matches: 441 (100.00%)
```
=> ppu-precise: improve vaddsws and vadduws instructions

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/rsx_debugger.cpp, rpcs3/rpcs3qt/table_item_delegate.h, rpcs3/rpcs3qt/trophy_manager_dialog.cpp, rpcs3/rpcs3qt/user_account.cpp, rpcs3/rpcs3qt/user_manager_dialog.cpp, rpcs3/rpcs3qt/user_manager_dialog.h
- improves user manager style.
- improves user manager button behavior.
- fixes scanning the home directory. It was able to show users with ids <= 0
- fixes usernames always having 16 characters
- add initial marked old usernames to the rename dialog
- add some hotkeys (F2, Delete, Enter, Return)
=> Qt: User Manager Improvements

rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h
- fixes keyboard input with focus policies
- fixes initial dead zone preview label sizes
=> Qt: Fix pad settings dialog shenanigans

rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- fix trophy table drag selection. It was always displaying the last selected game
- fix RSX capture boot on drag and drop
=> Qt: minor trophy manager fixes and RSX Capture boot fix

rpcs3/Emu/RSX/Overlays/overlays.h
Should fix the title of the native save dialog
should fix #4945
=> RSX Overlay: fix save dialog text

rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/Modules/cellCamera.h
Fix for regression with Fake camera handler introduced in #4676.
Also some other accuracy fixes, and refactoring of queue management functions.
=> cellCamera: Fix #4676 regression

README.md
- Added wiki link
- Remove "required" from dependency list. The word "dependency" implies requirement, therefore only optionality is notable.
- Update Vulkan links to point to latest always
- Added link to Vulkan config instructions, which describes how to ensure environment vars are set correctly (some people have had trouble with this)
- Remove redundant Qt config info, as it's already in the dependency list
- Various minor typo fixes
=> Readme dependency cleanup

Utilities/File.cpp, Utilities/File.h, rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/System.cpp, rpcs3/rpcs3qt/kernel_explorer.cpp
Should automatically try to read split files with extensions 66600, 66601 in the case the original file is not found.
=> Split fixes

rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/RSX/Capture/rsx_replay.cpp
- Fix rsx capture's user mem base allocation by moving it before `sys_rsx_device_map`. fixes the regression caused by #4975 
- sys_memory: Fix default alignment if no page flags are specified. [testcase](https://github.com/elad335/myps3tests/blob/master/ppu_tests/default%20memory%20alignment/expected.txt)
=> rsx-capture: unbreak

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/rsx_cache.h
While investigating the P5 texture swap issues, I stumbled into two different bugs in the texture cache, specifically in the `overlaps_page` and `get_intersecting_set` methods.
This pull request fixes these two bugs:
- In `overlaps_page`, if `address` is not page-aligned, the calculated end address for the corresponding page is incorrect which can lead to false positives, causing some textures to be re-uploaded unnecessarily.
- When the trampled range changes, `get_intersecting_set` restarts the outer loop. However, due to an off-by-one error, it skips the first cache entry when doing so. This can cause a texture to not be correctly unlocked, which could lead to issues such as texture corruption or even deadlocks.
I have ran these through @kd-11 and he has confirmed these are actual bugs. …
=> Texture cache fixes

rpcs3/Emu/RSX/VK/VKHelpers.h
Newer nvidia drivers are not exposing IMMEDIATE present mode unless you change options in nvidia control panel. This can cause severe performance degradation unless the vsync option is set to "off" in control panel.
This commit prefers MAILBOX mode over FIFO_RELAXED which seems to be just as slow as FIFO and allows performance closer to the true IMMEDIATE mode. Note that vsync on nvidia cards is broken under vulkan, but this is not an rpcs3 bug.
=> Fixup for nvidia vulkan performance problems

rpcs3/basic_mouse_handler.cpp
Fixes mouse shenanigans on Alt-Tabbing out of fullscreen when using the basic mouse handler
=> Qt: only center basic mouse input on active fullscreens

Utilities/git-version-gen.cmd, appveyor.yml, rpcs3/git-version.cmake
The git revision in the rpcs3 version string doesn't match the AppVeyor revision (sometimes), this PR should hopefully fix that.
The new revision will always be trimmed (or extended) to exactly 8 chars.
This however doesn't match the GitHub trimmed hash (7 chars).
=> Git Revision Fix

rpcs3/Emu/RSX/gcm_enums.cpp, rpcs3/Emu/RSX/gcm_enums.h, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h
- Add default vertex shader attributes values in `rsx_state::reset()`
- Fix method registers reset, move it to flip command instead of a driver flip. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/driver%20flip)
testcase is writing a non-initial value into `NV4097_SET_CULL_FACE`, does a driver flip on head 0 and head 1, and emits a crash dump. the value written remained.
- Ignore unknown culll face modes. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/unknown%20cull%20face)
testcase is writing a non-initial mode `CELL_GCM_FRONT` into `NV4097_SET_CULL_FACE`, then writes -1, and emits a crash dump, regiser's value is `CELL_GCM_FRONT`.
fixes #2444 , enables [Monster Jam: Path of Destruction](https://forums.rpcs3.net/thread-188969.html) to go …
=> Rsx: fix unknown cull faces

README.md
`The world's first open-source PlayStation 3 emulator/debugger written in C++ for Windows and Linux.`
=>
`The world's first open-source PlayStation 3 emulator/debugger, written in C++ for Windows and Linux.`
Otherwise it would mean that there might be another emulator that might be written C++ but may only target Windows.
This fixes #5042
=> add comma to readme

.gitmodules, .travis.yml, appveyor.yml, rpcs3/CMakeLists.txt, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/cmake_modules/ConfigureCompiler.cmake
With C++17, the optional submodule is not necessary anymore.
=> 3rdparty: remove optional submodule + misc

rpcs3/Emu/Cell/Modules/cellMic.cpp
`cellMicEnd` would get stuck waiting for the cellMic thread to finish, but it never does because `micInited` is still true.
Fixes Resistance: Fall of Mankind getting stuck after the menu.
=> Fix cellMic regression from #4467

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h
Credit to @elad335 for help isolating the issue.
- Fixes a buffer overflow in FP decompiler and adds an assert to keep this from happening again. Fixes some rare segfaults when a shader consumes more than 24 temp registers (using R25+ would corrupt the heap).
=> rsx: Fix FP temp register count

rpcs3/Emu/RSX/VK/VKFormats.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
The result of `upload_image_simple` is used as a blit source, so we need to make sure it's possible.
=> [vk] Check for BGRA8 linear image to support blitting

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLTextureCache.h
- Retag resources reprotected under flush_always rules.
- Properly check for blit resource fitting taking into account format
mismatch.
Fixes some problems encountered by @ruipin during validation of the texture cache routines.
=> rsx: Minor texture cache fixes

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKProgramBuffer.h, rpcs3/Emu/RSX/VK/VKTextOut.h
Fixes #5108
Ideally, the `gpu_formats_support` struct would know which of the formats we can use as render targets. However, it was tempting enough to performs the checks in-place (at `get_precomputed_render_passes`) as opposed to having a field per format in the support struct. So I went the easier route. Let me know if you'd like the support struct to do the queries instead.
=> [vk] check for attachment format properties before pre-creating render passes

rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/rsx_methods.cpp
Real hardware doesnt ignore draw calls when the program address is 0. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/Fragment%20program%20address%200)
This hack was probably there as a workaround for `rsx_state::reset()` resets the program address when it shouldn't. now that the reset is fixed, this hack can be happily removed.
=> rsx: remove shader address check hack

rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h
This corner case happens when the ppu executes an atomic loop with `ldarx` and `stwcx` instructions.
Brings [Blade kitten](https://forums.rpcs3.net/thread-178199.html) from loadable straight into ingame.
=> ppu: Fix extreme reservation corner case

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp
~~Should boost the performance on heavy zcull games.~~
=> rsx: tiny zcull optimizations

rpcs3/Emu/RSX/VK/VKGSRender.cpp
This is a follow-up to #5109
Asking a Vulkan driver for UNDEFINED support is not legal. Apologies for not fixing this in the original PR.
=> [vk] don't ask for VK_FORMAT_UNDEFINED support

rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h
Fixes use of address registers in VP. Should fix broken animations in applications that use the vertex pipeline for effects like skinning e.g https://github.com/RPCS3/rpcs3/issues/5044
=> rsx/vp: Fix ARL opcode

rpcs3/Emu/RSX/RSXTexture.cpp
It seems like the highest bit of fragment texture offset is ignored by real hardware, and only that bit alone. This feature is used in a few insomniac games and caused a translation exception anytime it was used. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/TEXTURE_OFFSET)
Also remove texture location check as it seems to be incorrect as the usage of invalid locations throw an exception on realhw. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/TEXTURE_LOCATION)
=> rsx: Clamp texture offsets

rpcs3/CMakeLists.txt, rpcs3/Emu/CMakeLists.txt, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/main_window.cpp
- Fixes LLVM recompiler options being disabled in the UI and Qt resource files not being properly included in the build
=> CMake refactor fixup (LLVM disabled in UI and Qt resources missing)

Utilities/JIT.cpp
- _XABORT_RETRY is defined in immintrin.h which wasn't included explicitly and asmjit doesn't happen to include it on Linux
=> Fix Linux WITHOUT_LLVM build

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_utils.h
Follow-up to https://github.com/RPCS3/rpcs3/pull/4914 by Jarves
=> rsx: Flip changes

rpcs3/Emu/RSX/Common/texture_cache.h
- This happens often in loading screens where the memory usage pattern is often randomized by loading in of assets.
Fixes https://github.com/RPCS3/rpcs3/issues/5105
Fixes https://github.com/RPCS3/rpcs3/issues/4924
=> rsx: Temporarily disable readback predictions if failure rate exceeds 50%

rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.h
Fixes FIFO mapping when `fifo_start_addr` is not aligned, a regression from #4966 .
=> rsx-capture: Rewrite FIFO commands allocation 

rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.h
Use offset and location instead of using hardcoded addresses from the game.
Fixes access violations when injecting data into main memory, such as in games affected by #5174 and probably many more. This is caused by the fact that the memory pointed by the game has no relation to the buffer we allocate to map main rsx memory on.
Disclaimer : since this changes the structure of the capture, it has to bump the capture version! older captures wont work anymore.
=> rsx-capture: Map dynamically rsx data injection addresses

rpcs3/Emu/RSX/RSXThread.cpp
- Any command with zero count that aint a branch instruction is a nop. [testcase](https://github.com/elad335/myps3tests/blob/master/rsx_tests/cmds%20with%20count%200/mainrsxcrap.cpp)
- Return command opcode ignores the method offset part of the opcode. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/RET%20command%20opcode)
=> rsx: Minor pfifo opcode fixes

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/RSXTexture.cpp, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_utils.h
- Mipmap, height and width arent allowed to be zero, those throw at register write time. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/TEXTURE_SIZE)
- Depth param is ignored and doesnt throw if the texture type is non-3d even when set to silly values such as 0 or 513, only throws when its 3d. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/TEXTURE_DEPTH)
- Since realhw doesnt throw when using height above 1 with 1d textures, read it as 1. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/TEXTURE_HEIGHT)
=> rsx: Remove a few texture params hacks

rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
- Force u32 destination index arrays when an overflow occurs while adding the vertex base index.
- Dont ignore the upper 16-bits of the restart index if u16 array is specified.
Fixes yakuza series' exploding vertices.
**before**
**after**
=> rsx: Fix u16 index arrays overflow 

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp
- bit-63 of arg4 signifyies location, so ignore that while reading the offset.
- Fix the binding of unbound tiles and zculls in rsx replay.
=> rsx_capture/gcm: Fix tile binding

rpcs3/Emu/Cell/PPUInterpreter.cpp
Results based on this test: https://github.com/RPCS3/ps3autotests/blob/master/tests/cpu/ppu_vpu/ppu_vpu.cpp
```
vec_vmaxfp (484 tests):
[master-fast] Matches: 440 (90.91%)
[master-llvm] Matches: 440 (90.91%)
[pr-fast] Matches: 441 (91.12%)
[pr-llvm] Matches: 420 (86.78%) (with the commented code)
vec_vminfp (484 tests):
[master-fast] Matches: 420 (86.78%)
[master-llvm] Matches: 420 (86.78%)
[pr-fast] Matches: 441 (91.12%)
[pr-llvm] Matches: 440 (90.91%)
```
Notes:
- The maximum of +0 and -0 is +0
- The minimum of + 0.0 and - 0.0 is - 0.0
=> ppu-interpreter: improve vminfp instruction

.gitignore, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui
Adds an option in view menu for showing compatibility status in grid view. Does not affect list view.
Example:
The reasoning behind this PR is to add more information to the grid view so that users woudn't need to switch back and forth between the two modes. It's set to off by default and thus needs to be manually enabled for those who wish for it to be shown.
Notes:
- Also adds support for CLion IDE; ignores `.idea/` for settings and `cmake-build-*/` for the default build directories.
- I haven't written a line of C++ before this, so I apoligize if I've made a mistake somewhere.
- Colors for Intro and Ingame are very close to each other and can thus be hard to distinquish. I haven't touched this myself as it's out of scope for this PR, but it could be worth it to consider adjusting them. …
=> Add option for showing compatibility status in grid view

rpcs3/rpcs3qt/game_list_frame.cpp
Saves the setting introduced in #5247.
Sorry.
=> Save compatibility draw state

rpcs3/Emu/Cell/Modules/cellAudio.cpp, rpcs3/Emu/System.h
The idea with this PR is to allow users to modify the loudness of game sounds without having to tinker with OS settings, and add the possibility of having game-specific volume settings.
Notes:
* Does not include any changes for the settings menu, and thus the setting has to be modified by altering `config.yml` manually.
If someone wants to do GUI support ~~(@Megamouse perhaps?)~~ for this setting then I could cherrypick your commits into this PR, or those can be submitted as separate PR's after this one has been merged.
=> Support for Master volume level setting

rpcs3/rpcs3qt/gs_frame.cpp
This is needed for MoltenVK on MacOS, however the Vulkan->MoltenVK correlation was only established in Qt 5.12, so if you want to test MoltenVK (hint: it doesn't work nearly as well as gfx-rs/portability) you'll need to use the Qt 5.12 Beta as of right now.
Requesting review from @Megamouse
=> Qt: set Vulkan surface in gs_frame

rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h
todo: fix order of events -> names
for #4116 and #5226
=> Linux/Input: fix evdev device list

rpcs3/Emu/RSX/RSXThread.cpp
if the array fetch is disabled, register is not specified while its input mask is enabled, the validation would consider this a valid array.  Fixes TDU2 regression from #5248.
=> rsx: Fix inlined vertex array validation regression

rpcs3/rpcs3qt/emu_settings.cpp
It was incorrectly trying to get the previous setting value after updating the setting
---
Tested before & after, working as intended now
=> gui: Fix OpenCorrectionDialog message

rpcs3/Emu/Cell/Modules/cellPad.cpp
Dont write to press data buffer if CELL_PAD_SETTING_PRESS_ON option was not specified. For now remove clear for other unused parts of the buffer, if a testcase is needed I can write it but I know testing this kinda stuff is a little tricky. Fixes dead island (#5215)
=> Fix cellPadGetData

rpcs3/Loader/PUP.cpp, rpcs3/rpcs3qt/main_window.cpp
Adds an extra check to avoid "fs::file is null" exception in the event that the pup file couldn't be opened.
=> Extra check when opening pup file

rpcs3/Emu/Cell/lv2/sys_fs.cpp
create_path doesnt check for EEXIST and ENOENT.
=> Fix typo in sys_fs_mkdir

rpcs3/Emu/Cell/PPUCallback.h
This change moves "Afrika" a bit further ingame.
Before it died because a callback stores a value at r1[0x30]
seg001:002604A8                 stdu      r1, -0x40(r1)
seg001:002604AC                 std       r31, 0x38(r1)
seg001:002604B0                 mr        r31, r1
seg001:002604B4                 std       r3, 0x70(r31)  <- stores a value at +0x30 over the previous stack value
With previous stack allocation r1[0x30] was the r1[0] for the previous caller which is where is stored the saved stack.
=> Increases default stack allocation for callbacks

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h
Only sets status to SPU_STATUS_STOPPED_BY_STOP when the thread is actually stopping(end of cpu_task).
sys_spu_thread_group_join will only finish when all threads have actually stopped.
Thanks whym for the logs and elad for helping me figure out the correct way to fix this.
=> Ensures threads are stopped in sys_spu_thread_group_join

rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/Modules/cellVdec.h
Value of format->colorMatrixType is only checked for certain formats.
Fixes an issue with Ridge Racer 7 3D.
=> cellVdecGetPicture accurate error checking

rpcs3/Emu/Cell/lv2/sys_memory.cpp
Add null alloc_addr checks to sys_memory_allocate and sys_memory_allocate_from_container.
[testcase](https://github.com/isJuhn/ps3tests/blob/master/sys_memory_allocate/expected.txt)
Some game was doing this according to ani.
=> sys_memery fix

rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
Dynamically check the loaded QT library version in case of mismatch.
Fixes using 5.11.1 builds with non-buggy libraries and vice versa.
Likely fixes https://github.com/RPCS3/rpcs3/issues/5351
=> qt/gs_frame: Hotfix

rpcs3/Emu/Cell/lv2/sys_fs.cpp
`CELL_FS_O_EXCL` has no effect without `CELL_FS_O_CREAT`. [testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellFsOpen%20flags)
The testcase tries to open a non-existent file with EXCL with a few combinations of flags, error code is ENOENT.
Then creates the file and tries to open it again with the same flags, CELL_OK is returned.
Fixes an issue when trying to install game data with the updated version of Gran Turismo 6.
=> cellFsOpen flag fix

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/Common/BufferUtils.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/Null/NullGSRender.cpp, rpcs3/Emu/RSX/Null/NullGSRender.h, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_utils.h
Fixes some regressions from the FIFO PR. See https://github.com/RPCS3/rpcs3/issues/5380
- Restore Null renderer to working condition (debugging only)
- Fix the flattener to avoid getting "Unreachable" assert in R&C 1
- Silence unnecessary log spam in vulkan
- Minor code cleanup
=> Fifo fixups

.gitmodules
What: ignore submodules to make git operations faster.
Why: git operations were very slow
How: added `ignore = dirty` to all submodules in `.gitmodules`
Testing: I can confirm that `git status` is now substantially faster, down from 3.5 seconds to 0.15 seconds 
Assumptions: 
- I'm assuming that changes to submodules will be so rare that it's not worth having git check them for changes.
- I tested this on windows 10, it is possilble that other OSs will not see the same speedup
Source of info: https://stackoverflow.com/questions/4994772/ways-to-improve-git-status-performance
=> Added ignore = dirty to all submodules to make git operations faster

rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Capture/rsx_capture.h, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GCM.h, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_utils.cpp, rpcs3/Emu/RSX/rsx_utils.h
* Reduce capture size.
* ignore image_in transfers with empty clip region. its not executed at all according to hw tests.
* Dont "fix" in_pitch and out_pitch when 0 (image_in and buffer notify)
e.g when src pitch is 0, the same line is copied to the destination.
[testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/image%20in) used
original [texture](https://imgur.com/k43HvCX).
[result](https://imgur.com/dkNa1ym) using image_in with zero src pitch.
[result](https://imgur.com/T2CQj9o) using buffer_notify with zero dst pitch;
[result](https://imgur.com/dkNa1ym) using buffer_notify with zero src pitch.
* Minor size of rect fixes.
* Add rsx lv2 defaults for sempahore context, cus vsh.
* Implement backwards source image reading in image_in. Fixes #4747.
=> rsx: Reduce capture size + image_in fixes

rpcs3/Emu/Cell/SPUThread.cpp
Fixes double transfer of 128-byte data from spu local storage. (perf fix)
**Before** (both):
**After** (non-TSX):
**After** (TSX): none, `to_write` was removed completely in tsx path.
Keep in mind that this was tested in MSVC only.
=> avoid double transfers in putllc

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
The funcStat callback is called even if the directory doesn't exist.
Its returning statSet->reCreateMode doesn't seem to change the resulting behaviour as per my testing on real HW.
REd library:
CELL_SAVEDATA_CBRESULT_OK_LAST_NOCONFIRM returns CELL_SAVEDATA_ERROR_PARAM
CELL_SAVEDATA_CBRESULT_OK_LAST returns CELL_OK
Both instantly terminate after calling funcStat.
=> Extra result handling from funcStat CB in savedata_op

rpcs3/Emu/Cell/lv2/sys_fs.cpp
sys_fs_fcntl with parameter 0xC0000002 should extract device path from the given path and use that to gather free space information.
I'm open to better implementations :p.
=> sys_fs_fcntl with parameter 0xC0000002 fix

rpcs3/Emu/Cell/Modules/cellCamera.cpp
Added init check when using no camera input setting to perfect its error checking. 
by moving camera input setting check below init.
=> Added CAMERA_NOT_INIT checks for no camera setting

README.md
>why
The readme was getting really noisy. It may not seem super important, but a well written readme is always inviting to devs and users alike.
With that said, there are a couple of things that should probably be discussed. This project is used, built, and developed on a wide range of platforms, with a far wider set of tools and build chains. I do not think it makes sense, however, to have build and configuration info clogging the readme.
Therefore, I think there should simply be either:
1) Soft support for other platforms, hard support for Windows and Linux. By that I mean that build-fix prs and patches, or anything else relating to "oddball" platforms should be accepted by the project, as they already are, but not significantly maintained, or even acknowledged. This is essentially what …
=> Readme cleaning

rpcs3/main.cpp, rpcs3/rpcs3qt/gs_frame.cpp
This should work as before now, even on window's high dpi settings.
The main reason for this PR was to use Qt's frontend highdpi stuff instead of using SetProcessDPIAware.
Also fixes a crash on Vulkan when resizing the window to a small height (by setting a min height on Qt side XD).
~~There is a bug still present in the gs-frame that causes a swapchain error. The max is 1 less than the calculated size on eg. pixelratios of 2~~
~~E {rsx::thread} RSX: Swapchain: Swapchain creation failed because dimensions cannot fit. Max = 993, 604, Requested = 994, 604~~
=> Qt/windows: use Qt's high dpi scaling

rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/System.h, rpcs3/ds4_pad_handler.cpp, rpcs3/ds4_pad_handler.h, rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h, rpcs3/mm_joystick_handler.cpp, rpcs3/mm_joystick_handler.h, rpcs3/pad_thread.cpp, rpcs3/pad_thread.h, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/pad_settings_dialog.ui, rpcs3/xinput_pad_handler.cpp, rpcs3/xinput_pad_handler.h
1.
Please test with one or multiple ds4 controllers.
I changed the way ds4 controllers are handled. We now treat them as one of 7 controllers. the internal logic remembers the order.
Please investigate what happens if you connect or disconnect one or multiple new ds4 controllers ingame.
Possible crash: during saving of ds4 settings ingame.
2.
All pad settings (handlers) need testing.
The pad settings dialog remapping should now be mostly disabled when a controller is not detected.
Please test if the buttons enable/disable correctly when you plug/unplug controllers
**UPDATE:** 
Okay with the latest changes I
1. changed the index to 1-n instead of 0-n,
2. also made it possible to reconnect DS4 controllers without pressing the Refresh button,
3. added connection status to the device name in …
=> [Testers needed] DS4 fixes and pad settings improvements

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
The folder dev_hdd1/cache is a temporary folder and is used by games to temporarily store data outside of main memory. On PS3, this folder limited to 1 GB (afaik) and the console will automatically delete ~~files out of it to keep it under that treshold~~ everything inside it when switching games.
However, on this emulator the folder is never cleared and thus can grow to tens of gigabytes over time. While it is not a huge issue, I still believe that the emulator should keep the size of this folder in check so that it woudn't rob too much disc space. After all, these are just temporary files and thus aren't interesting enough to store permanently.
This PR checks the cache size and deletes olderst folders from it untill it's less than the treshold. Users can disable the feature and …
=> Clear disk cache if it grows too large (dev_hdd1/cache)

.travis/deploy-linux.bash
This fixes #5362 and all similar issues in a distro-agnostic way.
For those interested in the AppImageKit-checkrt side of things see this commit: https://github.com/RPCS3/AppImageKit-checkrt/commit/e4343b957f54c0089afe4f214478da068b318791
=> Remove distro whitelist and use the new automated stdc++ checker

Utilities/Thread.cpp
This should set core arrangement to intel_ht if Intel processor is used and Windows detects multiple logical processors in any core. I won't be providing any linux/mac/BSD/solaris implementation, those can be submitted in a separate PR if someone feels like doing that.
=> Thread scheduler: Detect Intel hyperthreading on Windows

rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
count = 0 is invalid, info was taken from an internal function in sys_semaphore_post.
the function executes after object id lookup meaning ESRCH is being checked first.
https://user-images.githubusercontent.com/18193363/50449210-735b0000-092e-11e9-8101-724e6d494ff6.png
=> Fix sys_semaphore_post count check

rpcs3/rpcs3qt/game_list_frame.cpp
This was sorely needed when the app crashed after resizing icons
=> Micro Contribution: Fix cut off Icons after emu crash

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXThread.cpp
* Break down capture of commands with count greater than 1 into single commands with value.
allows to capture image_in when the same command previously writes to image_in source offset, so it will capture correctly the source. (ie when we rely on register value written previously in the command).
Also fixes issues with memory state with put pause in the middle of the command (by capturing with the check).
* Fix a few hle gcm functions. description in the commit.
* Evaluate cond rendering test at the set_render_enable. [testcase](https://github.com/elad335/myps3tests/tree/master/rsx_tests/conditional%20rendering%20tests)
Testcase sets conditional rendering mode, writer 1 to the report value, wait for rsx to finnish, clears report manualy (writes 0), sets draw call and kicks command buffer. …
=> rsx capture foxxo

rpcs3/Emu/Cell/Modules/cellVideoOut.cpp
The mapping of resolutionId to video_resolution was wrong.
Checked on decr and res 0 is considered invalid.
Makes karaoke revolution work again 🛠.
=> cellVideoOutConfigure minor fix

rpcs3/Emu/Cell/Modules/cellCamera.h, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Cell/lv2/sys_memory.h, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_tty.cpp, rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/kernel_explorer.cpp
* Add missing 0 cases allocation granularity size flag for `sys_mmapper_allocate_shared_memory_x`, treat them as 1m (like sys_memory_allocate) . [testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/sys_mmapper%20case%200%20alloc%20flag), the testcase tries 0 flag on shared memory allocation, tries to map it with an area with 1m page flags, returns CELL_OK.
* Fix sys_vm_memory_map address base when vsize is less than 256mb, allocate the block as 256mb in size. [testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/sys_vm%2032%20mb), the testcase tries to call sys_vm_memory_map twice with 32 mb vsize, the address returned of the second map is 0x40000000. (0x32000000 on master)
* Change total amount of memory returned with sdk version:
I've tested this using …
=> Debug console emulation

rpcs3/Emu/Cell/lv2/sys_mutex.cpp
Should fix 4C4T issues(including DeS).
Problem I think is specifically when a mutex unlock awake a thread that then destroy the mutex, when unlock thread runs again the lock_guard destructor fails because mutex->mutex doesn't exist(either crashes or unlock gets stuck).
I think the lock guard might actually be ok because that destroy should succeed on a ps3 so it'll wait until the unlock ends and destroy it.
=> Fixes issues where the mutex is destroyed while an unlock is happening

.travis.yml, .travis/build-linux.bash, .travis/deploy-linux.bash, .travis/travis.env
This PR makes the Linux AppImages get pushed to RPCS3/rpcs3-binaries-linux instead of hosting it ourselves. It is setup the exact same as RPCS3/rpcs3-binaries-windows. MacOS deployment will be submitted later, but this PR makes for an easy reference for setting up Mac deployment, if anybody else wants to tackle it.
This allows for the project to provide an easy way to test various RPCS3 builds on Linux.
Requesting review from @AniLeo
=> Deploy Linux binaries to GitHub Releases

rpcs3/Emu/Cell/Modules/cellSysutil.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
sceNpTrophyCreateContext calls cellSysutilPacketRead which would yield the thread while waiting for a cond.
Also ensures status messages granularity through changes made by neko to Sysutil cb handling.
This should fix the last issues with trophies hopefully.
=> sceNpTrophyCreateContext yielding

rpcs3/Json/tooltips.json, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/gl_gs_frame.cpp, rpcs3/rpcs3qt/gl_gs_frame.h, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h, rpcs3/rpcs3qt/gui_settings.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
Since some users requested this I implemented a "Exit game?" dialog that lets you abort the exit process and also warns about loss of progress. A similar Dialog will be spawned when you boot a game while another is running.
The dialog can be disabled via "Don't show again" checkbox and reenabled in the gui settings. I also added the other forgotten remaining info dialog settings to the same location.
This dialog is pure Qt btw, because once you close the window you will have most likely used mouse and keyboard anyway.
fixes #5107
=> Spawn Exit Game Confirmation when closing the game window

rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h
Spec cleanups
- Forgot to update descriptor pool init sizes over time. Updated sizes should fix descriptor pools running out of resources with only 25% occupancy.
- Do not use VK_WHOLE_SIZE for the null resource bind since most drivers have uniformBufferRange limits much much smaller.
- Also clamp swapchain resources to allowable surface extents.
Should fix the following:
- https://github.com/RPCS3/rpcs3/issues/5424
- https://github.com/RPCS3/rpcs3/issues/5351
=> [Hotfix] vk: Spec fixups

rpcs3/Emu/Cell/Modules/cellGame.cpp
HAWX2 wouldn't get past cellGameGetSizeKb because the dir was not existant.
I don't really know if this approach is correct but it led to a proper installation into said dir.
Sadly the game immediately crashes on the first logo.
=> cellGame: fix some installation issues

rpcs3/Emu/RSX/rsx_methods.cpp
fixes #5538 , invalid context is set at startup pointing into system reserved area. simply ignore it instead of throwing an exception.
old HW tests showed that even context = 0 is passable in this method.
=> Implement invalid NV4097_NOTIFY context handling

rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/System.h
This is based on the results from https://github.com/elad335/myps3tests/tree/master/spu_tests/atomic%20reservations%20tests
* getllar doesnt trigger LR event when replacing the current reservation with a different one, despite the docs.
* putlluc doesnt trigger LR venet when executing on the same address as the current reservation.
* putllc doesnt trigger LR event when executing on a different address from the current reservation.
Whats common behind all of those is that the SPU never triggeres LR event by itself, the event can only be triggered by external writes.
The idea behind "last check for event" is to ensure we did not miss out on events that occured in the past before we get rid of the old reservation.
results on realhw:
```
events after GETLLAR: 0x00000000
events after PUTLLC: …
```
=> SPU/PPU LR performance and event fixes

rpcs3/rpcs3qt/game_list_frame.cpp
Adjusts RemoveShadersCache, RemovePPUCache and RemoveSPUCache to use the new cache location and thus makes these functions work again when rightclicking items in game list.
Fixes #5557
=> Fix cache removal options

rpcs3/rpcs3qt/osk_dialog_frame.cpp
Fixes my facepalm mistake that leads to osk dialogs only taking S as input when they should just prevent whitespace.
This should fix the issue with H.A.W.X.2 for example.
=> cellOskDialog/osk_dialog_frame: fix regexp for CELL_OSKDIALOG_NO_SPACE

rpcs3/Emu/Cell/PPUModule.cpp
Use a default of 1001 prio when the main thread priority specified by the executable image is invalid.
Fixes the weeb and loadable game White Album 2, which reuses main thread prio for creating other threads.
The main is invalid, making ppu thread creations fail as well.
testcase : https://github.com/elad335/myps3tests/tree/master/ppu_tests/default%20main%20prio
=> Patch ppu main thread prio

rpcs3/Emu/Cell/Modules/cellAudio.cpp, rpcs3/Emu/RSX/rsx_cache.h
I suddenly noticed some strange behavior with my shader compilation dialog.
At first I thought it was my build but then it also happened on master.
After some investigation I found out that the values passed to the CallAfters weren't the same as those that were actually used inside the lamda.
So I hope this is the correct fix.
Also use log level warning instead of error for the notorious underrun message.
=> Fix some minor shenanigans

rpcs3/Emu/Cell/lv2/sys_rwlock.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
Do not abort prematurely on failed cmpxchg, restart the atomic loop and wait for condition confirmation instead.
Example: two threads are executing semaphore trywait at the same time on semaphore with an initial value of 2.
Ideally, both should succeed and return CELL_OK.
On the current method, when the first thread decreements the sema's value while the second thread is in the middle of trywait operation, the second thread will fail to store due to failed cmpxchg. (EBUSY is returned)
With an atomic loop restart the second thread will restart the atomic loop and reload the semaphore value, check it and decrement its value, both operations return CELL_OK.
Condition confirmation is important in try once methods.
=> Wait until condition confirmation in atomic operations (try once methods)

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.h
* Make main thread unjoinable.
* Return error code in sys_ppu_thread_get_join_state. (the library ignores it by default)
Testcase : https://github.com/elad335/myps3tests/tree/master/ppu_tests/Main%20thread%20joinability
The testcase tests the main thread's joinability using sys_ppu_thread_get_join_state and a join from a different thread.
This also tests the error code returned when passing invalid ptr to sys_ppu_thread_get_join_state. (EFAULT is returned in this case, otherwise CELL_OK is returned)
get_join_state call was designed using a direct lv2 call to get the error code.
=> Make main_thread unjoinable

Utilities/Thread.cpp, rpcs3/Emu/RSX/RSXThread.cpp
If the emu is stopped while in allocate_new_query(), m_current_task will not be set and remain as nullptr in ZCULL_control::set_active().
The pointer is later on dereferenced in begin_occlusion_query().
=> Fix potential crash in begin_occlusion_query() while closing the Emu

rpcs3/Emu/RSX/VK/VKGSRender.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/5617
=> vk: Hotfix for fullscreen not working on non-windows platforms

rpcs3/Emu/Cell/Modules/cellOskDialog.cpp, rpcs3/Emu/Cell/Modules/cellOskDialog.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLOverlays.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/Overlays/overlay_osk.cpp, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/osk_dialog_frame.cpp
- Implements a native osk input interface for use with a controller. Only ascii input in supported at the moment.
- Fixes a few bugs with the backend rendering of some native elements
- Improves font and text rendering system to support more glyphs and support more languages
=> Native OSK

rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h
This makes the amount of times sys_spu_thread_group_join returned always be equal to the amount of times sys_spu_thread_group_start was called, and the amount of times a termination signal was signaled.
This also means that when executing a second sys_spu_thread_group_join, it waits until another signal will be received.
In theory, to exit from this situation another thread has to call sys_spu_thread_group_start, and waiting until the SPUs will signal termination again.
Source for this:
https://user-images.githubusercontent.com/18193363/52517440-0bdde300-2c44-11e9-8c52-773a9de5a233.png
Past tests hinted this behavior, although it was unclear if an absolute deadlock will occur on the second sys_spu_thread_group_join execution, or how to exit from this situation.
=> Make sys_spu_thread_group_join return once per termination

rpcs3/Emu/Cell/lv2/sys_spu.cpp
join_state can be set before all threads are terminated, check run_state as well to ensure completion.
=> Fix a regression in sys_spu_thread_group_join

rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
in `sys_lwcond_signal`:
* Check for EPERM in mode 2 if a specific ppu thread id was specified.
* Move ENOENT check of mode 3 to unspecific ppu thread id handling.
* If the ppu thread id target does not belong to a thread, return ESRCH.
both:
* Mode 2 doesnt use the lwmutex, therefore ESRCH check for lwmutex id doesnt occur.
[testcase](https://github.com/elad335/myps3tests/tree/master/ppu_tests/sys_lwcond_signal%20error%20code%20test), results:
master:
```
lwcond_signal(null id, mode 1) returned 0x80010009
lwcond_signal(main_thread, mode 2) returned 0x0
lwcond_signal(-1 id, mode 2) returned 0x0
lwcond_signal(main_thread, mode 3) returned 0x80010006
lwcond_signal(-1 id, mode 3) returned 0x80010009
lwcond_signal_all(invalid mtx, mode 2) returned 0x80010005
```
realhw:
```
lwcond_signal(null …
```
=> Fixup for sys_lwcond_signal_x error checking

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/settings_dialog.cpp
Doesn't work with game data and probably also not with ps1 or ps2 classics
=> Qt: only show supported resolutions in custom configs

rpcs3/rpcs3.appdata.xml
0b7f46d removes zero-width spaces, which somehow got into the file, and 5763e80 adds a screenshot, help and bugtracker urls.
The appdata file now passes `appstream-util` validation.
=> Fix and improve appdata.xml file

rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
Fix random discard of EBUSY set by sys_lwcond_signal.
May be able to address #5654 .
=> Fix race in sys_lwcond_wait on error code

README.md
I wouldn't think it matters, but it seems that it does.
=> readme - direct qt link to avoid confused kot noises

rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.h
Implement syscall 117, used by liblv2 lwmutex when using protocol SYS_SYNC_RETRY
~on unlock, this mode unlocks the lwmutex, and awakes a waiter with EBUSY error code.~
~in this case the waiter in liblv2 lwmutex_lock retries to lock and call the syscall again.~
Fixes OG Infinite Battle when using load liblv2 only option, allows it to go ingame.  (ingame in auto lib loading)
=> Implement _sys_lwmutex_unlock SYS_SYNC_RETRY mode

rpcs3/Emu/Cell/Modules/StaticHLE.cpp, rpcs3/Emu/Cell/Modules/StaticHLE.h, rpcs3/Emu/Cell/Modules/sys_libc.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUModule.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
This is a basic implementation of static function hooking.
The functions implemented are:
-memcpy
-memset
-memmove
-memcmp
and the wchar_t variants of those functions(wmemcpy, etc).
To be active the hook static functions has to be checked in debug tab.
I've not noticed any performance gain from it on the few games I've tested it on but since it's done, here it is.
=> Static HLE implementation

rpcs3/git-version.cmake
Regressed by #5657. Downstream may build outside of build directory, sometimes patching out `unknown` from existing version information.
```c++
$ cat rpcs3/git-version.h
// This is a generated file.
#define RPCS3_GIT_VERSION ""
#define RPCS3_GIT_BRANCH ""
// If you don't want this file to update/recompile, change to 1.
#define RPCS3_GIT_VERSION_NO_UPDATE 0
```
=> Fix version when building from source archive

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.h, rpcs3/Emu/System.cpp
* Use sys_memory_allocater in rsx capture replay to fix missing memory block in allocations.
* Fix 0 vm page flags in all cases. use 1m page flags in that case.
* Make vm::alloc register page flags based on area's flags instead of raw alignment passed.
* Ensure memory mapped by sys_rsx_context_iomap is valid.
Fixes rsx replayer regression after #5502.
=> Fix RSX replayer using sys_memory_allocate, Ensure rsxio memory is valid

rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/gcm_enums.h, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_utils.cpp, rpcs3/Emu/RSX/rsx_utils.h
Improves texture search logic by attempting to 'merge' the surface store data and the texture cache data whenever overlaps are encountered. A full data collapse would be infeasible due to performance concerns, but since the two sources are optionally data locked, this should almost always resolve correctly especially when WCB is enabled.
This PR is still very WIP and has been made available for testing. Please look out for significant graphical or performance regressions. Optimizations are still ongoing.
Glitched:
=> rsx: Texturing improvements

Utilities/Thread.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.h, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h
* Implement SPU page fault notifications
* Fixes related to page faults are described in the commit.
Fixes saving issues in Grand Turismo 5 and Grand Turismo 6.
Allows Gran Turismo 6 to go ingame.
Fixes #5350
=> Implement SPU page faults, Synchronization fixes

rpcs3/rpcs3qt/main_window.cpp
Avoid throwing fatal error when installing firmware without a \n character on the version string
Fixes #5646
=> InstallPup: Fix exception on newline trim

rpcs3/Emu/Cell/SPURecompiler.cpp
@elad335 reminded me about this problem. Second commit is an attempt to compensate for possible performance hit.
=> SPU LLVM: fix SPU MMIO in TSX mode

Utilities/geometry.h, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLHelpers.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_methods.cpp
A follow-up to the last PR addressing a few issues
- Tons of accuracy and stability/crash fixes in texture cache and blit engine
- Vastly improved synchronization mechanism (DMA flush)
- Implemented blit engine rotations on the GPU
- Lays groundwork for the next task (variable sized framebuffers to preserve memory contents)
Tracker: https://github.com/RPCS3/rpcs3/issues/5708
=> rsx: Texturing improvements followup

rpcs3/rpcs3qt/pad_settings_dialog.ui
Now that DS3 support is implemented, that text is no longer accurate.
I updated it to mention the need for a driver like WinUSB (mentioned on the PR) that I assume is only needed on Windows, and the need for pressing the PS button to wake the controller up. Tell me if I missed anything or if I should change something (or if I should just close this and stop trying to get my 5 seconds of fame :D)
=> Update DualShock 3 warning

rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/rpcs3qt/settings_dialog.cpp
LLVM-based. Xfloat accuracy settings are respected as well.
=> [WIP] New SPU interpreter (SPU fast)

rpcs3/Emu/Cell/Modules/libad_async.cpp, rpcs3/Emu/Cell/Modules/libad_core.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUModule.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
Not sure if these functions are really useful but at least, for the sake of completeness, we now have them.
**libad_async**
0x833F4516 => sceAdAsyncSpaceOpen
0xC2DB09C5 => sceAdAsyncSpaceClose
**libad_core**
0xAC495EB8 => sceAdGetAssetInfo
0xDFA9D08D => sceAdGetSpaceInfo
=> hle: Add libad_async and libad_core modules

rpcs3/Emu/Cell/Modules/cellFontFT.cpp, rpcs3/Emu/Cell/Modules/cellSysmodule.cpp, rpcs3/Emu/Cell/Modules/cell_FreeType2.cpp
Source for `cellFontInitLibraryFreeType`: https://www.psdevwiki.com/ps3/Talk:VSH_Exports
**Before:**
```
! LDR: **** cell_FreeType2 export: [0xA29CA82E] at 0x903474
```
```
! LDR: **** cellFontFT export: [0xF9677A46] at 0x870180
```
**After:**
```
! LDR: **** cell_FreeType2 export: [FT_Get_X11_Font_Format] at 0x903474
```
```
! LDR: **** cellFontFT export: [cellFontInitLibraryFreeType] at 0x870180
```
=> hle: Add miscellaneous functions

Utilities/Thread.cpp, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/lv2/sys_timer.cpp, rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/Cell/lv2/sys_vm.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/pad_thread.cpp, rpcs3/pad_thread.h
* Fix passing ASSIGN_CHANGES flag in cellPadGetInfor since its not supported by this function.
* Minor optimizations in pad_thread, use raw ptr when possible and replace std::vector with std::array in m_pads container.
* Fix segfault when reading stack memory in the debugger.
* Remove handle in cellVdecClose.
* Fix page fault range check. (old bug)
* Allow recieving frame information only once in cellVdecGetPicItem, fixes Toy Home. (used to iterate this func infinitely)
* Fix Emulator crash after SPU access violation.
* Fix sys_process_exit2 when waiting for SPUs at av handler to terminate. Fixes #5713 
* Improve vblank timing, fixing potential stutter and micro frame rate spikes.
* Fix timer (sys_timer) state after event queue destruction. …
=> cellPad, cellVdec and sys_process fixes

README.md
if not installed, cmake fail on -> '/usr/lib/x86_64-linux-gnu/cmake/Qt5Qml/Qt5QmlConfig.cmake'
=> add qtdeclarative5-dev for debian/ubuntu

appveyor.yml
obk.ee expired the new domain is nkmk.ch, renewing a .ee domain is expensive and annoying so i moved to a new tld.
this .ch domain will not expire for around 3 years normally.
=> updated domain name for vulkan mirror

rpcs3/Emu/CMakeLists.txt
This is needed for GL/glew.h to be found.
=> Fix macOS compilation

Utilities/File.cpp, Utilities/File.h, Utilities/Log.cpp, rpcs3/Emu/Cell/Modules/cellGame.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/VFS.cpp, rpcs3/Emu/VFS.h
@ruipin reported that removing this code (touching memory) improves performance in some cases. It can't be simply removed, but there is a workaround to try.
=> Ease cache line interference on TSX path

rpcs3/Emu/Cell/PPUAnalyser.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.h, rpcs3/Emu/Cell/lv2/sys_process.cpp, rpcs3/Emu/Cell/lv2/sys_process.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/rpcs3qt/kernel_explorer.cpp
Most likely needs a lot more changes, but i don't know where to look for more answers.
I suggest not merging it yet.
=> Initial sys_overlay

3rdparty/CMakeLists.txt
Libusb wants to be a special snowflake and use timespec without including time.h, so it defines it as follows:
```c++
// We *were* getting timespec from pthread.h:
#if (!defined(HAVE_STRUCT_TIMESPEC) && !defined(_TIMESPEC_DEFINED))
#define HAVE_STRUCT_TIMESPEC 1
#define _TIMESPEC_DEFINED 1
struct timespec {
long tv_sec;
long tv_nsec;
};
#endif /* HAVE_STRUCT_TIMESPEC | _TIMESPEC_DEFINED */
```
However, the windows version of time.h doesn't define HAVE_STRUCT_TIMESPEC or _TIMESPEC_DEFINED even though it defines the timespec struct. Because neither of these flags is set libusb tries to define the struct again which then causes compiling to fail.
My proposal is to define HAVE_STRUCT_TIMESPEC for MSVC, which causes the `#if` to be false and thus make libusb skip the definition. This should …
=> Fix compiling for MSVC + CMake

rpcs3/Emu/Cell/PPUFunction.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/Cell/lv2/sys_prx.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/rpcs3qt/register_editor_dialog.cpp
* Fix a few SIMD with saturation instructions on ppu Fast and Precise decoders: Properly handle cases where destination reg is also one of the source registers. Fixes loading icon in Beyond Two Souls with ppu precise. Fixes #2827
* Improve FPCC handling in ppu interpreter to be closer to LLVM implementation, fixing part of #3516
* Rewrite VPKSHUS in ppu precise decoder to be almost as fast as its "fast" counterpart.
* Fix default non-java mode reported.
* Status check added to sys_prx_start/stop_module.
* like ppu interpreters, if the instruction/function is not found fallback to decoding single instructions in PPU LLVM recompiler, fixes part of #2909 . 
* Fix STSWI and LWSI instructions in ppu llvm when number of bytes isnt 32bit aligned.
* Increment cia manually in unregistered hle func …
=> PPU/SPU Interpreter + Recompiler instruction fixes and improvements

rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
* Add extra argument checks for _sys_ppu_thread_create & sys_ppu_thread_rename
* Pause thread instead of throwing exception on trap instruction (for debugging)
=> lv2/ppu: Minor PPU fixes

rpcs3/Emu/System.h
Because RSX Guest utilization confuses people and is mostly only meaningful for debugging.
=> misc: Lower default perf overlay detail

rpcs3/Emu/Cell/Modules/cellPad.cpp
- Used IDs were not from the Guitar Hero instruments but in fact from the Rock Band ones. Sets the correct Guitar Hero IDs and adds the Rock Band ones on comments. TODO: Allow selecting the specific devices on the PAD Settings.
- Adds DJ Hero Turntable VID/PID.
- Adds Dance Dance Revolution Mat VID/PID.
--- 
Documentation:
- [USB vendor list](https://usb-ids.gowdy.us/read/UD/12ba) shows 0x12BA is Sony Computer Entertainment America and contains the list of known devices
- HIDRAW contains the Vendor and Product IDs for the Dance Dance Revolution Mat on
https://github.com/Orochimarufan/HIDRAW/blob/master/usb_ddrpad/Devices/konami_ps3.h#L26
- Turntable IDs were checked on the turntable itself
=> cellPad: Update vendor and product IDs

Utilities/Log.cpp, Utilities/sysinfo.cpp, Utilities/sysinfo.h
The idea behind this is to get some more data about the operating system RPCS3 is ran on, so that issues like #5621 and #5799 we could potentially determine which system updates are causing issues. I also added an implementation for Linux/BSD/Mac, maybe that will prove useful some day. Also includes a check for compatibility modes, in case someone decides to use one for any reason.
=> Print Operating System version to log

bin/GuiConfigs/Envy.qss, bin/GuiConfigs/Skyline (Nightfall).qss, bin/GuiConfigs/Skyline.qss
Please consider merging these changes: 
* Rework checkboxes on Skyline & Nightfall
* Add gradient to header border on Skyline and Nightfall
* Specify tab alignment
* Add styling to disabled sliders
* Correct spinbox text color on Envy
* Improve styling of firmware libraries list
* Inherit debugger and memory viewer styling from main on Envy
* Fix disabled Firmware Library hover effects on Windows
...and some other small fixes here and there.
The most noticeable changes are the checkbox re-work...
... and the styling for disabled sliders:
=> Touch-ups to Skyline and Envy

rpcs3/Emu/Cell/PPUFunction.cpp, rpcs3/Emu/Cell/PPUThread.cpp
Do not continue to BLR in unknown HLE function access in PPU LLVM, opcode was unregistered, Fixes MGS Peace Walker with PPU LLVM.
Fixes segfaults with PPU interpreter breakpoints after #5749.
=> Fix unregistered HLE function access on PPU LLVM, Fix PPU breakpoints

README.md
Add qtbase5-private-dev for Debian as dependency to the README.md since it is needed, probably due to qt5.11.3+.
=> Update to README.md due to dependency

rpcs3/ds3_pad_handler.cpp, rpcs3/ds4_pad_handler.cpp
The instructions for letting emulator access DS3 and DS4 have been added to the [RPCS3 wiki](https://wiki.rpcs3.net/index.php?title=Help:Controller_Configuration). I think we should link to that page instead of printing instructions to log since wiki pages are easier to both read and maintain.
=> Use wiki for DS3/DS4 troubleshoot instructions

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.h
Follows #5882 and also fixes some unnecessary SPU cache writes.
Does not require removing SPU cache.
=> SPU LLVM: Fix some regressions

rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h
- Allow some drivers to bypass the window state polling if they properly handle OUT_OF_DATE and/or SUBOPTIMAL return codes to signal that the window surface has changed. This should offset the surprisingly large penalty of polling the window size from Qt on some linux window managers.
- Fix a typo in OpenGL code.
Fixes https://github.com/RPCS3/rpcs3/issues/5921 and also fixes https://github.com/RPCS3/rpcs3/issues/5913
=> rsx: Minor tweaks

rpcs3/Emu/Cell/Modules/cellMsgDialog.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/msg_dialog_frame.cpp, rpcs3/rpcs3qt/msg_dialog_frame.h, rpcs3/rpcs3qt/progress_dialog.cpp, rpcs3/rpcs3qt/progress_dialog.h
***Fixes:***
- Fixes wrong module count in Qt Compilation Dialogs
- Fixes a glitch that stacks Qt Compilation Dialogs
- Don't add games to the Recent Games List when the add_only option is used
- Ignore operations other than boot when rebooting the last game from the GUI
- Show all unique game data entries instead of only the first
***New Features:***
- Batch Create PPU Cache
- Batch Remove PPU Cache
- Batch Remove SPU Cache
- Batch Remove Shader Cache
- Batch Remove Custom Configurations
This will attend to #5407
=> Add Batch Operations and fix some Loader issues

rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_grid.cpp
Improves Game Icon quality when using a higher device pixel ratio.
Improves the game compatibility circle icon quality.
fixes #5885
Please test on different monitors (especially on 4K devices) with different window and/or icon scaling.
Thank you @drysalter for the circle idea and Daginatsuko for showing me how bad the game icons actually look on her monitor.
**My results on a 4K Screen with 200% window scaling:**
List Circles:
Grid Circles:
List Icons (Smallest icon scale):
Grid Icons (Smallest icon scale):
Grid Custom config icons:
=> High DPI Icons

rpcs3/Emu/RSX/Overlays/overlays.cpp
This was a bit of a bother to me when I was testing https://github.com/RPCS3/rpcs3/issues/5913
It took about 8 seconds for me to scroll down to the old save that I was using to test changes. If I mashed I could scroll down in about 3 seconds, but I'd rather not injure my hand over something as trivial as scrolling through saves.
This seems like a fair balance between speed and controllability to me.
=> overlays: Double dpad repeat rate

rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
Both regarding readers blocked because theres a writer on the sleep queue.
First fix: fix signaling bit when ownership passed to a writer, yet there are still readers waiting on the sleep queue.
Second fix: Do not signal readers while the lock is *still* acquired by a writer when the last writer on the sleep queue quits.
=> Two fixes for sys_rwlock

Utilities/JIT.cpp, Utilities/JIT.h, Utilities/types.h, rpcs3/Emu/CPU/CPUTranslator.cpp, rpcs3/Emu/CPU/CPUTranslator.h, rpcs3/Emu/Cell/Common.h, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/PPUTranslator.h, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUAnalyser.h, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.h, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/cmake_modules/ConfigureCompiler.cmake
These changes are supposed to be tested with the following settings:
* SPU LLVM
* Giga block size
This is literally first working version from 10 min ago so don't expect much.
=> SPU Analyser improvements ("Giga")

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
Or could it be a duplicate bit?
=> gl/vk: clear scissor_setup_invalid bit along with scissor_config_state_dirty bit

rpcs3/Emu/Cell/SPURecompiler.cpp
Should fix #5950 and other assorted crashes when using SPU LLVM Mega since #5923
Tested RDR and TLOU with SPU LLVM Mega and they no longer crash (TLOU still has significant issues with race-conditions, but I managed to get in-game after enough tries).
Thanks to @Nekotekina for his help figuring this one out, he did basically all the work, I just tested 👍
=> SPU LLVM: Fix "Mega" regression

bin/GuiConfigs/Envy.qss, bin/GuiConfigs/Skyline (Nightfall).qss, bin/GuiConfigs/Skyline.qss
* Add gradient to gamelist title bar
* Change radio button color on Skyline
* Add hover effect to checked radio buttons
* Hide log text from dock on all themes (it is redundant due to the "Log" tab)
* Change text color for game table selections on Nightfall
Most noticeable change below:
=> Further improvements to Skyline and Envy

rpcs3/main.cpp
RPCS3 is hardcoded to set this environment variable.
A user on Discord reported they had issues with Qt's hidpi scaling with RPCS3 on Linux. They could not disable it by setting this environment variable to 0, because qputenv inside RPCS3 is hardcoded to overwrite it, setenv with 0 as third arg won't ovewrite already set environment variables.
=> Use setenv instead of qputenv for QT_AUTO_SCREEN_SCALE_FACTOR

rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_utils.h
Variable-sized framebuffers idea turned out to be a disaster, so I had to go back to the drawing board. Perform surface cache intersection resolve for surfaces to allow propagation of old data through most cases. Essentially guarantees that previous ROP writes to an arbitrary memory range are present if any render-target is created from the same range. Removes need for the memory hierachy invalidation hack needed for RDR to render accurate shadows.
- Allows render targets to behave like stacked 3D views same as shader inputs are resolved
- Basically implements most of 'Read Color/Depth Buffers" option for 'free'.
- Allows splitting RTV/DSV resources if they are superceded by a partial surface
- Also allows intersecting new resources through the surface cache for proper inheritance from …
=> rsx: Surface cache improvements

rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h
- Transition attachments to LAYOUT_GENERAL in case of a feedback loop. Fixes appearance of garbage along polygon edges in some post-processing passes.
- Also reverse this transition when rendering goes back to normal
- Optimize transitions from LAYOUT_GENERAL to some common read/write layouts.
Retry of https://github.com/RPCS3/rpcs3/pull/5973
=> vk: Workaround for cyclic feedback loops

rpcs3/Emu/RSX/VK/VKHelpers.h
I've installed all 3 amd drivers on linux along with anv and found some things that need changing.
I've verified that ANV works well and doesn't require any workaround for window resizing.
AMDVLK and the proprietary amd driver both require workarounds to enable window resizing on linux unfortunately. However, most users are already using RADV, and we can recommend those who aren't to switch. (The userbase of these drivers is so small that no one reported window resizing being broken until I bothered to install them myself) 
I've also added a second commit that prints a recommendation to install RADV if you use amdvlk or the prop driver on linux. It's using LOG_SUCCESS because WARNING isn't visible by default. I'm not sure if that's the best way to notify users. 
The log commit is separate …
=> vk: check_window_status fixes for linux

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKProgramBuffer.h, rpcs3/Emu/RSX/VK/VKRenderPass.cpp, rpcs3/Emu/RSX/VK/VKRenderPass.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTextOut.h, rpcs3/VKGSRender.vcxproj, rpcs3/VKGSRender.vcxproj.filters
Do not rely on a precomputed renderpass array and instead generate a proper cache to manage these resources.
- Ensures the current renderpass matches the image properties even when a cyclic reference is detected
- Solves problems due to mismatching layouts and renderpasses
=> vk: Refactor renderpass management

rpcs3/Emu/RSX/VK/VKFramebuffer.cpp, rpcs3/Emu/RSX/VK/VKFramebuffer.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/VKGSRender.vcxproj, rpcs3/VKGSRender.vcxproj.filters
- Refactor out framebuffers from the renderer core.
- Use a proper cache with sorted queues for faster searching.
- Bump shader cache version which I forgot to do with the last refactor.
=> vk: Refactor framebuffers

rpcs3/Emu/Cell/Modules/cellOskDialog.cpp, rpcs3/Emu/Cell/Modules/cellOskDialog.h, rpcs3/Emu/GameInfo.h, rpcs3/Emu/Io/PadHandler.cpp, rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp, rpcs3/Loader/PSF.cpp, rpcs3/ds3_pad_handler.cpp, rpcs3/ds3_pad_handler.h, rpcs3/ds4_pad_handler.cpp, rpcs3/ds4_pad_handler.h, rpcs3/evdev_joystick_handler.cpp, rpcs3/evdev_joystick_handler.h, rpcs3/mm_joystick_handler.cpp, rpcs3/rpcs3_app.h, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/game_compatibility.cpp, rpcs3/rpcs3qt/game_compatibility.h, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/osk_dialog_frame.cpp, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/rsx_debugger.cpp, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/save_manager_dialog.h, rpcs3/xinput_pad_handler.cpp, rpcs3/xinput_pad_handler.h
This adds simple multipliers for left and right sticks to the input config files.
They range from 0-200 (0.0 - 2.0) and the default is 100 (1.0).
I will try to add an input field to the pad settings dialog as well.
This also fixes a crash in the pad settings dialog that was caused when clicking "Filter Noise" while the current pad was disabled. The button will now only be activated when there is a pad connected.
Fixes a bug that shows the wrong color when selecting led colors.
Fixes a bug that resets the led colors when clicking the vibration checkboxes.
Fixes a crash when downloading the compatibility database twice in a row.
Also fixes a crash when trying to load empty param.sfo s.
Also gets rid of some warnings.
fixes #6001
=> Input: add a stick multiplier for better game pad support

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/Common/GLSLTypes.h, rpcs3/Emu/RSX/VK/VKCommonDecompiler.h, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
- Fix aux context usage when handling swap queues. The aux context does not have its own descriptor pool and borrows from the laggy frame context which has a pool that is still in use.
- Refactor out GLSLCommon from VKHelpers since VKHelpers is included in GUI code to assist with context intialization. This should remove a lot of compiler warning spam about unused static functions declared in the header.
Fixes https://github.com/RPCS3/rpcs3/issues/5999
=> vk: Fixups

Vulkan/CMakeLists.txt, rpcs3/Emu/RSX/VK/VKProgramBuffer.h
I can also replace
```
if (num_targets != other.num_targets)
return false;
return num_targets == other.num_targets;
```
by
```
if (num_targets != other.num_targets)
return false;
return true;
```
if preferred
=>  vk: remove duplicate condition in pipeline_props struct equal operator 

rpcs3/Emu/Cell/lv2/sys_process.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/main.cpp, rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h
Hereby I attempt to enable the usage of PS3_GM01, PS3_GM02 etc in the gamelist, by adding a new emu member m_game_dir and using this instead of PS3_GAME.
The granularity of games.yml had to be increased.
Also the addition of games to the games.yml by BootGame(add_only) was extended.
aims to fix #4448
=> Better Support For Game Collections

Utilities/sysinfo.cpp, Utilities/sysinfo.h
This way we can see if people have the TSX eratta fix without asking them to look up their microcode, and then referencing with several old tables. 
We're not actually interested in the capabilities of TSX_Force_Abort itself, but the presence of it should confirm that the eratta fix is present. 
I used https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/x86/include/asm/cpufeatures.h as reference.
=> Util: Detect presence of TSX_Force_Abort and print to log if detected

BUILDING.md, README.md, rpcs3/Emu/CMakeLists.txt, rpcs3/cmake_modules/ConfigureCompiler.cmake
And update the documentation accordingly. Building instructions are moved to the `BUILDING.md` file with explanation about how to install gcc-8 on Ubuntu systems.
Close #6070
=> Set minimum supported version of GCC to 8.x

Utilities/Atomic.h
_ReadWriteBarrier() is a deprecated function, see https://docs.microsoft.com/en-us/cpp/intrinsics/readwritebarrier?view=vs-2019.
=> misc atomics: Use std::atomic_thread_fence (MSVC)

Utilities/dynamic_library.cpp
The class dynamic_library doesn't seem to be used anywhere, but the implementation of `loaded()` is incorrect, and returning the wrong value. This commit fixes that, in case anyone decides to use this class in the future.
=> Fix dynamic_library::loaded

rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp
- Remove unused variables
- Prefer emplace_back instead of push_back when possible (https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html)
=> rsx: Minor cleanup after #6055

rpcs3/Emu/Cell/PPUThread.cpp
Try to obey strict type aliasing rule in `ppu_ref` cache access.
=> minor UB fix

Utilities/BEType.h, rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/CgBinaryFragmentProgram.cpp, rpcs3/Emu/RSX/CgBinaryProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
=> Future fix for semaphore_406e

rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui
Currently you can only decrypt .sprx files with the GUI.
This adds the following filters to the decryption file dialog:
- .bin
- .self
- All binaries (.bin, .self, .sprx)
- All files
This PR also changes the file endings of the decrypted files to .elf in case of .bin or .self.
=> Improve file decryption

Utilities/Atomic.h, Utilities/types.h, rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm_reservation.h, rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_utils.h, rpcs3/rpcs3qt/breakpoint_list.cpp, rpcs3/rpcs3qt/rsx_debugger.cpp
- Prefer `vm::ptr<>::ptr` over `vm::get_addr`.
- Prefer `vm::_ptr`/`base` over `vm::g_base_addr` with offset. 
- Added methods `atomic_t<>::bts` and `atomic_t<>::btr` .
- Removed obsolute `rsx::thread::Read`/`WriteIO32` methods.
- Removed wrong check in `semaphore_release`.
- Added handling for PUTRx commands for RawSPU MFC proxy.
- Prefer overloaded methods of v128 instead of `_mm_...` in VPKSHUS ppu interpreter precise.
- Fixed more potential overflows that may result in wrong behaviour.
- Added `io`/`size` alignment check for `sys_rsx_context_iounmap`.
- Added `rsx::constants::local_mem_base` which represents RSX local memory base address.
- Removed obsolute `rsx::thread::main_mem_addr`/`ioSize`/`ioAddress` members.
=> Tiny Refactoring

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/Modules/cellSync.cpp, rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/RawSPUThread.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/RSXOffload.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/rsx_methods.cpp
* vm::spu max address was overflowing resulting in issues, so cast to u64 where needed. Fixes #6145.
* Use `vm::get_addr` instead of manually substructing `vm::base(0)` from pointer in texture cache code.
* Prefer `std::atomic_thread_fence` over `_mm_?fence()`, adjust usage to be more correct.
* Used sequantially consistent ordering in `semaphore_release` for TSX path as well.
* Improved memory ordering for `sys_rsx_context_iounmap`/`map`.
* Fixed sync bugs in HLE gcm because of not using atomic instructions.
* Use release memory barrier in `lwsync` for PPU LLVM, according to [this](https://docs.microsoft.com/he-il/windows/desktop/DxTechArts/lockless-programming) xbox360 programming guide `lwsync` is a hw release memory barrier.
Also use release barrier where lwsync was originally used in …
=> Fixup after #6143

rpcs3/Emu/RSX/GL/GLTexture.cpp
This is a partial workaround for slow PBO performance with mesa. In Mesa PBO unpacking is currently done on the CPU which makes GL_STATIC_COPY painfully slow, even though our usage is best suited for GL_STATIC_COPY. Instead we will use GL_STREAM_COPY for Mesa which performs somewhat better, but it's still not ideal. To get full performance we will need a fix to come from Mesa. 
See:
https://gitlab.freedesktop.org/mesa/mesa/commit/a338dc01866ce50bf7555ee8dc08491c7f63b585
https://gitlab.freedesktop.org/mesa/mesa/blob/master/src/mesa/state_tracker/st_cb_bufferobjects.c#L250
<details>
<summary> NGS2 Comparison </summary>
</details>
While this game has gone from 20 up to 60 fps, other games require a driver fix to get anything close to playable. Ninja gaiden 3 has a scene which has improved …
=> gl: Workaround slow PBO usage with Mesa

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKResourceManager.cpp, rpcs3/Emu/RSX/VK/VKResourceManager.h, rpcs3/Emu/RSX/VK/VKTextureCache.h, rpcs3/VKGSRender.vcxproj, rpcs3/VKGSRender.vcxproj.filters
- Fixes some old issues with resource management in violation handlers and the texture cache. Freeing buffers and event handles still queued for processing would cause drivers to re-issue them and cause strange results such as premature signaling and deadlocks due to use-after-free situations in the driver.
- Handle dangling queries when doing an emergency commandlist close/submit. See https://github.com/RPCS3/rpcs3/issues/6135.
- Minor optimization by reusing temporary objects in the discard pile instead of allocating new ones. Should help lower memory utilization and may improve performance since allocations are quite expensive. The nature of identical frame-to-frame operation in games means that it is almost never required to invoke allocations unless the scene suddenly changes.
Fixes …
=> rsx: Improve object reuse and lifetime management

rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Memory/vm.cpp
* ..Regarding sys_memory containers destroy/create.
* Fix tiny race on page flags in sys_memory_get_page_attribute.
=> Fix possible inconsistencies for sys_memory mem stats report

rpcs3/Emu/RSX/rsx_decode.h
Fixes part of #6165, from past events it seems like the correct solution continueing #5137 (see description for details).
=> rsx: Clamp fragment shaders address

CMakeLists.txt
Without this patch, build fails when using
cotire, because pch headers are missing
the pthread flag when using Clang
=> Fix build with cotire and clang-8.0 branch

Utilities/BitField.h, Utilities/StrFmt.h, Utilities/cfmt.h, Utilities/types.h, rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/lv2/sys_cond.h, rpcs3/Emu/Cell/lv2/sys_event.h, rpcs3/Emu/Cell/lv2/sys_event_flag.h, rpcs3/Emu/Cell/lv2/sys_lwcond.h, rpcs3/Emu/Cell/lv2/sys_lwmutex.h, rpcs3/Emu/Cell/lv2/sys_mutex.h, rpcs3/Emu/Cell/lv2/sys_rwlock.h, rpcs3/Emu/Cell/lv2/sys_semaphore.h, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.h
* Explicitly truncate bitfields to the destination type (new `bf_decoder` resolves smallest type possible at compile time and truncates the result).
* Fix `NV4097_SET_BLEND_COLOR::green16`/`red16()`, typo led to loss of 8 upper bits (using u8 instead of u16).
* Same with `NV4097_SET_BLEND_COLOR2::alpha`/`blue()`.
* Simplified structures (`decode_type` is the only one used).
* New methods added to types.h such as `get_int_t` (gets integral type from type size), I'm sure they will be useful in the future as well as for this pr.
=> rsx: Refactor rsx_decode.h and bugfixes

rpcs3/rpcs3qt/find_dialog.cpp, rpcs3/rpcs3qt/instruction_editor_dialog.cpp, rpcs3/rpcs3qt/register_editor_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/vfs_dialog.cpp, rpcs3/rpcs3qt/welcome_dialog.cpp
This PR fixes a few UI buttons reacting to incorrect signals. Previously, a few buttons did not follow the standard UI behaviour and instead of reacting to button **click** (press & release), they executed their actions on **press**. This led to a bit inconsistent experience and, in some cases, difficulties navigating (I found it the most annoying in _Virtual File System_ dialogs).
Affected dialogs:
- Welcome
- Find
- Instruction Editor
- Register Editor
- Settings (radio buttons)
- Virtual File System
While this may look like a mass Find & Replace, each case has been analyzed separately and tested for regressions.
To observe the changes easiest, do the following:
0. Ensure Welcome screen will show on startup (`Settings -> GUI -> Show Welcome Screen` should be set).
1. Launch RPCS3.
2. …
=> Fixed behaviour of some UI buttons

Utilities/Thread.cpp, rpcs3/Emu/CPU/CPUThread.cpp, rpcs3/Emu/CPU/CPUThread.h, rpcs3/Emu/Cell/PPUFunction.h, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/System.cpp
* Also fix MFC tag status report for explicit mfc barriers commands, affects only status report because it is already blocking all tags.
* Improve memory ordering of `cpu_init()` a little.
=> Log last PPU HLE function executed after access violation

rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp, rpcs3/Emu/Cell/Modules/cellMic.cpp, rpcs3/Emu/Cell/Modules/cellMic.h, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.h, rpcs3/rpcs3qt/settings_dialog.ui
Supports 4 microphone types:
-Standard: your basic microphone
-Singstar: fakes a singstar microphone device
-Real Singstar: if you want to use your real singstar microphones
-Rocksmith: to use with rocksmith games and your rocksmith dongle( thanks @jjsat )
Configuration is under the Audio tab.
=> Microphone emulation

rpcs3/Emu/RSX/rsx_decode.h
**HARDWARE TESTS PENDING: @kd-11 mentioned he'll test it relatively soon.**
This PR corrects decoding of `SET_BLEND_COLOR` RSX commands. Previously colour would be interpreted as RGBA, whereas it appears like it should have been treated as BGRA.
It's assumed this feature is not used by many games, and even the ones using it do not use it consistently.
Afftected games:
* **Gran Turismo HD Concept** - fixes blue tail lights in *some* vehicles. Oddly enough, most cars looked just fine (and they still do), which hints blend color is not used to achieve red material color often.
* **Gran Turismo 5** - possibly affected. Untested, but screenshots from current RPCS3 builds show the same bug as in GTHD.
The most prominent example in GTHD is Infiniti G35, clearly showing what was wrong. Notice …
=> rsx: Treat blend colour as BGRA

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/System.h
Laying the groundwork for emulation speed modifiers.
* Fixed an accuracy regression from #5719 (b8fb83c4483d). (recheck period before sleeping)
=> rsx: Allow to configure vblank rate

rpcs3/Emu/System.h, rpcs3/rpcs3qt/settings_dialog.ui
I've noticed that there's a lot of people using ASMJIT nowadays even after the approximate float being a thing thinking that it's the best and fastest option to all the games, which leads to people complaining that the performance they've been getting isn't nowhere near what it should be since asmjit says (faster) and 
because its the default option. This PR changes the default SPU decoder to LLVM and renames SPU LLVM (experimental) to SPU LLVM (fastest).
=> Set the default SPU Decoder to LLVM and rename SPU LLVM from "experimental" to "fastest"

rpcs3/Emu/RSX/VK/VKHelpers.h
It was accidentally disabling float16_t for non Vega cards.
=> vk: Fix Linux Vega float16_t workaround

rpcs3/rpcs3qt/game_list_frame.cpp
I just removed a game update from the game list and the game itself still showed the old version.
I fixed this by properly updating the game list instead of using the old way of simply removing the list entry after the files were removed.
=> Qt: fix app versions after a patch was removed from the game list 

rpcs3/rpcs3qt/pad_settings_dialog.cpp
This should (hopefully) fix the small controller icon in the pad settings dialog.
Please test this on both normal screens and window scaling.
Before:
After:
=> Qt: Fix small controller icon in pad settings for high dpi modes

rpcs3/Emu/Cell/SPURecompiler.cpp
Fixup for SPU Recompilers, regression after #6210.
On The Next Episode: Fixup for "Fixup for Fixup"
=> Fixup for Fixup

rpcs3/rpcs3qt/game_list_frame.cpp
=> Qt/game_list_frame: Ignore file entries when adding disc/game directories

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/rsx_utils.h
- Allow surfaces to inherit from multiple surfaces
- Fixes a possible reference leak when cloning surfaces
- Fixes data loss due to memory splitting
Reimplementation of https://github.com/RPCS3/rpcs3/pull/6205
Should fix some of the regressions in https://github.com/RPCS3/rpcs3/issues/5983
=> rsx: Surface cache fixes

rpcs3/rpcs3qt/emu_settings.cpp, rpcs3/rpcs3qt/game_list_frame.cpp
Previously, a game would revert to its original name when adding a custom config in grid mode or removing one in grid or list mode.
Also fixes removal of custom pad configs in general.
=> Game List: Keep custom name when adding/removing game-specific config

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/rsx_methods.cpp
- Merge viewport raster window and scissor into one clipping region
- Viewport raster clip is different from viewport geometry clipping in
hardware as the latter is configurable separately
Fixes rendering outside the active viewport window in games like hotline miami and deadly premonition.
=> rsx: Implement separate viewport raster clipping

rpcs3/rpcs3qt/main_window.cpp
Über minor fix, .BIN files weren't being filtered correctly on Linux.
=> Fix .BIN decryption filtering for case sensitive platforms

rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp
It seems that much like vulkan, coverage sample logic is always enabled in GPUs, including the PS3. This means that a2c can be used even without multisampling, at which point it works like an alpha test. For now we keep the shader a2c emulation when AA is set to disabled.
- FIxes broken foliage in GT6 and GT academy.
=> rsx: Support CSAA transparency without multiple rasterization samples

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h
Fixes a bug introduced by https://github.com/RPCS3/rpcs3/pull/6224 where buffer clears were clipped to viewport. This is not correct since the viewport only clips during rendering, not during clear operations.
Fixes https://github.com/RPCS3/rpcs3/issues/6232
=> rsx: Do not clip scissor to viewport when doing buffer clear

rpcs3/pad_thread.cpp, rpcs3/pad_thread.h
The PS3 hides button presses from the game during dialogs.
This is done because the game would perceive unwanted input while the user is occupied with the dialog itself.
In order to achieve that a so called "pad interception flag" is activated and passed to the game whenever it polls pad information. On top of that the pad data that is passed to the game is basically empty.
I implemented all of this in rpcs3 already and it ***just works***.
But there is one little thing we missed.
The game Hotline Miami 2 (and maybe others) immediately activates a menu option after the prior overlay dialog was accepted. This is obviously not how it works on the console.
As it turns out - thanks to @CookiePLMonster, who noticed and tested this on the PS3 - the game didn't receive any new input after a …
=> input:  keep pads intercepted while regular buttons are still pressed

rpcs3/rpcs3qt/vfs_dialog.cpp, rpcs3/rpcs3qt/vfs_dialog_tab.cpp, rpcs3/rpcs3qt/vfs_dialog_tab.h
This PR brings several improvements to Virtual File System dialog, both visual and technical:
- Move semantics are now used in dialog constructors, cutting down on needless copying of shared pointers passed to those.
- "Add New Directory" and "Reset" buttons have been replaced with "+" and "-" buttons. Previously, it was not possible to delete a single item from the list without resetting it.
- "Reset All" has been renamed to "Reset Directories" and a confirmation message has been added to it, so now you can't missclick and lose your settings by accident.
- "Okay" button has been renamed to "Save" to be in line with the rest of RPCS3's UI. "Close" button was also added, allowing to quit without saving settings.
Dialog before my changes:
Dialog after my changes:
=> Improvements to Virtual File System dialog

rpcs3/rpcs3qt/about_dialog.ui
Makes all labels in the "About RPCS3" window selectable by mouse and keyboard.
Also lets you open links in that window by keyboard.
fixes #6244
=> Qt: make text labels in about dialog selectable

Utilities/Thread.cpp
I create PR with refactoring thread sheduler for Add 3600(X)/3700X/3800X/3900X/3950X
Refactor other Threadriper on zen(+), very bad before for all cpu with ccx 3+3 like 3900 
- Need enable Thread sheduler and using P5 for best testing, here
- 60 fps patch is needed and need set vblank to 120
- Share your 2 screen with Master and this pr with TS enable on both, on same place in my screen
=> update thread sheduler for zen2 and refactor for zen(+)

rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_config.cpp, rpcs3/Emu/Cell/lv2/sys_config.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters
This PR contains a mostly-complete implementation of the sys_config syscalls, which is one of the many things required for RPCS3 to be able to boot vsh standalone. In particular, without sys_config, vsh believes no controllers are connected, and as such does not recognize any input.
Below I have copied in an explanation of how sys_config works (also included at the top of sys_config.h):
```
sys_config is a "subscription-based data storage API"
It has the concept of services and listeners. Services provide data, listeners subscribe to registration/unregistration events from specific services.
Services are divided into two classes: LV2 services (positive service IDs) and User services (negative service IDs).
LV2 services seem to be implictly "available", probably constructed on-demand with …
```
=> Initial sys_config implementation

rpcs3/Emu/Cell/lv2/sys_rsx.cpp
This fixes entry indexing when part of the targeted unmap area has already been unmapped or mapped into non-continues ea addresses (overlapping fixed address io mappings and unmappings).
I'll investigate HLE gcm fix as well in a later pr.
=> Fix sys_rsx_context_iounmap partial unmapping

rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/Modules/cellMic.cpp, rpcs3/Emu/Cell/Modules/cellMic.h, rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp, rpcs3/Emu/Cell/Modules/cellVpost.cpp, rpcs3/Emu/Cell/Modules/libmixer.cpp, rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp, rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp, rpcs3/Emu/Cell/Modules/sys_spu_.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_event.cpp, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_mutex.cpp, rpcs3/Emu/Cell/lv2/sys_net.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/Emu/Cell/lv2/sys_time.cpp, rpcs3/Emu/Cell/lv2/sys_timer.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h
This pull requests allows for the first time to modify time scaling of all LV2/PPU/SPU/RSX timers including syscalls' sleep time, units are in percentage.
This also adds three new accuracy modes for LV2 sleep:
- `Host` accuracy: does not attempt to fix host operating system's sleep accuracy.
This is theoretically the fastest setting, some users reported performance increase from reverting `sys_timer_usleep` accuracy such as in Red Dead Redemption. (the new default)
- `Usleep`: Attempts to corrects the sleep time for `sys_timer_usleep` syscall, this was the default behaviour on current master, fixes stutter and inaccurate frame rate capping in some games such as Nier.
- `All`: Attempts to correct the sleep time for all syscalls with timeout, this is the most accurate setting of them all …
=> It's About Time

rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/gs_frame.cpp
fixes #6217
**Background Icons**
This fixes the background icons during shader compilations.
The path defaulted to the directory of the PARAM.SFO that was used to boot the game. In case of updated disc games this will point to the update directory in "dev_hdd0/game" instead of the actual disc directory. This is not wrong in itself, but since we preferably load the PIC1.PNG which isn't always present in that directory, we ended up loading the ICON0.PNG with (mostly) lower resolution that was supposed to be used as a fallback.
For hdd games and others nothing changed. But for disc games we now do the following:
We still default to the PIC1.PNG in the update directory as before, but instead of choosing the ICON0.PNG in the same location as a fallback we now look for the PIC1.PNG in the …
=> Fix background icons in shader loading screen / Fix disc game titles

rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/RSX/GCM.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
Reversed from cellGcm gcm interrupts thread code:
* Fixed unmap key value: Unmap key has been thought to be made by `(1ull << (dealloc_size >> 20)) - 1) << (io & 63)`, but this fails to handle non-contiguous unmappings as each bit actually representing an io entry.
Now non-continues unmappings are handled correctly.
Fixed missing events in those case:
* First IO entry to be unpped is not found on the first megabyte of memory deallocated.
* Not all IO entries to be unmapped are found on the same 64 bits area, such as simply by unmapping contiguous memory mapping when `(io & 63) + (size >> 20) > 64`. 
Fixed redundent events in this case:
* After allocation and deallocation on memory which has already been unmapped, the event is sent again. (fixed by clearing `RSXIOMem.io`'s entries)
Other …
=> rsx: Fix gcm unmap events

rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/save_manager_dialog.h
* Display icons.
* Show details in the main UI instead of popup dialog.
* Various smaller tweaks to interface and codebase.
I had to combine title and subtitle into one field because the interface would've been too wide with them as separate fields, hopefully this doesn't upset anyone.
=> Save manager improvements

rpcs3/Emu/RSX/Common/surface_store.h
- Fixes aliased memory surface loss when doing intersection tests. When doing memory inheritance across the DEPTH<->COLOR barrier, it was possible for data to be lost due to incomplete succession.
This was intended to be part of a larger changeset but some other investigations are holding things back a bit so I decided to go ahead and submit this as a astandalone. Continuation of work on https://github.com/RPCS3/rpcs3/issues/5983
=> rsx: Surface cache fixups (part 1)

rpcs3/rpcs3qt/game_list_frame.cpp, rpcs3/rpcs3qt/game_list_frame.h, rpcs3/rpcs3qt/trophy_manager_dialog.cpp
Added a small simplification to the game list icon logic. I hope this will be slightly faster. If it is slower for some reason then I will revert this commit.
So please test the icon resize in the game list if you have a huge amount of games (normal screen OR high dpi screen).
Added the high dpi improvements that can already be seen in the game list and in the save data manager to the trophy manager.
Added the background icon color that is already used for the game icons to the trophy icons.
Comparison: (Note my custom black background color on the trophy icons)
=> Qt: improve trophy manager icons for high dpi setups

Utilities/Thread.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.h, rpcs3/Emu/Cell/lv2/sys_process.cpp, rpcs3/Emu/Cell/lv2/sys_process.h, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/Cell/lv2/sys_prx.h, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h
- Implement sys_overlay_load_module_by_fd.
- Implement special segment allocation when ppc_seg flag is specified.
=> vm/sys_overlay Improvements

rpcs3/Emu/Cell/PPUDisAsm.cpp
* Show destination register first, then source.
* Add `mr` mnemonic for `ORI ra, 0(rs)`, this matches with IDA.
=> ppu disasm: Improve ORI and ORIS disassembly

rpcs3/Emu/RSX/VK/VKHelpers.h
The "black screen" issue that RADV users experienced with LLVM 8.0.0 was resolved in LLVM 8.0.1
So let's not warn users that have 8.0.1 installed.
=> vk: Clarify RADV llvm 8.0.0 warning 

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/rsx_methods.cpp
ZCULL queue was updated to one-per-cb but the conditional render sync hint was not updated.
Changes:
- Do not unconditionally flush the queue unless the upcoming ref is contained in the active CB. This avoids spamming queue flush, which frees up resources and improves performance by evading a GPU hard sync.
=> rsx: Conditional render sync optimization

rpcs3/Emu/Cell/lv2/sys_vm.cpp
Do not zero-out contents of targeted memory.
Heres the testcase https://github.com/elad335/myps3tests/blob/master/ppu_tests/sys_vm_invalidate/ppumain.cpp.
Testing contents of sys_vm memory after first run, after a second sys_vm_touch and after sys_vm_invalidate by reading 4 bytes from different places.
Results: sys_vm_invalidate does not clear memory contents.
=> sys_vm: Fix sys_vm_invalidate

rpcs3/rpcs3qt/game_list_frame.cpp
Instead of simply opening the directory when using "Open Custom Config Folder" in the game list this should now also select the proper file in the explorer on windows and in the finder on macos respectively.
On other operating systems this will fallback to opening the parent directory as before.
=> Qt: select custom configs when opening the custom config folder

rpcs3/Emu/CPU/CPUThread.cpp
Spu threads were getting stuck after sys_spu_group_suspend and sys_spu_group_terminate.
Fixes The Sly Trilogy( https://github.com/RPCS3/rpcs3/issues/6300 ).
=> Fixes suspend+stop threads not stopping

rpcs3/Emu/RSX/rsx_methods.cpp
- Fix typo (scale_x->scale_y)
- Remove convoluted temp buffer creation and just use vector allocator instead
=> rsx: Minor fixup for image_in

appveyor.yml, rpcs3/ds3_pad_handler.cpp, rpcs3/ds4_pad_handler.cpp, rpcs3/rpcs3qt/game_list_grid_delegate.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/xinput_pad_handler.cpp
This bumps the Qt version of Appveyor builds to 5.13.
This might include some relevant internal bugfixes and improvements in High Dpi scaling.
Keeping the Qt version up to date will prevent inconsistencies between up-to-date local development and the expected outcome in official builds.
=> Update Appveyor to Qt 5.13

rpcs3/ds3_pad_handler.cpp, rpcs3/ds3_pad_handler.h, rpcs3/rpcs3_app.cpp, rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/save_data_dialog.cpp, rpcs3/rpcs3qt/save_data_dialog.h, rpcs3/rpcs3qt/save_data_list_dialog.cpp, rpcs3/rpcs3qt/save_data_list_dialog.h, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/save_manager_dialog.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/rpcs3qt/trophy_manager_dialog.cpp, rpcs3/rpcs3qt/trophy_manager_dialog.h, rpcs3/xinput_pad_handler.h
Changes the default icon background color to something brighter.
This also adds 2 more gui settings for icon colors: trophy manager icon color and save manager icon color.
You can set these in the gui settings just like the gamelist icon color.
Fixes wrong icon height in the save manager if no icon was found.
Fixes some possible nullpointer exceptions in the save manager and the trophy manager.
Handles some warnings.
=> Add settings for trophy and save manager icon background colors

rpcs3/rpcs3qt/breakpoint_list.cpp, rpcs3/rpcs3qt/debugger_list.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/save_data_list_dialog.cpp, rpcs3/rpcs3qt/save_manager_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/trophy_manager_dialog.cpp, rpcs3/rpcs3qt/user_manager_dialog.cpp
Silences the following warnings:
```
warning C4996: 'QDesktopWidget::availableGeometry': Use QGuiApplication::screens()
warning C4996: 'QDesktopWidget::screenGeometry': Use QGuiApplication::screens()
warning C4996: 'QListWidgetItem::setTextColor': Use QListWidgetItem::setForeground() instead
warning C4996: 'QListWidgetItem::setBackgroundColor': Use QListWidgetItem::setBackground() instead
warning C4996: 'qSort': Use std::sort
warning C4996: 'qGreater<QModelIndex>::operator ()': Use std::greater
```
=> Qt: Clean up depracation warnings

Utilities/GDBDebugServer.cpp, rpcs3/Emu/Cell/lv2/sys_memory.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Memory/vm.h
Fix stack memory state checking, boundaries may be "allocated" but not mapped (guard pages).
=> Tiny fix of vm::check_addr

rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_overlay.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/rpcs3qt/breakpoint_list.cpp
Fixes segfaults when attenpting to set segfaults on non-executable memory.
Also implements vm::page_executable which may be useful in the future.
=> debugger: Fix potential segfaults when setting ppu breakpoints

rpcs3/Emu/Cell/Modules/cellCamera.cpp, rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/Modules/sys_mempool.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/lv2/sys_memory.h, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_vm.cpp, rpcs3/Emu/Cell/lv2/sys_vm.h, rpcs3/Emu/IdManager.h, rpcs3/Emu/Memory/vm.cpp
For `sys_ppu_thread_create`:
* Remove 1m limit for stack size, see #4517.
* Treat 0 stack size arg as 4k instead of 16k, [source](https://user-images.githubusercontent.com/18193363/61990279-13544580-b046-11e9-87d9-a97c26b6f879.png) from kernel.
* Return  `CELL_ENOMEM` for `0xffff'ffff >= stack_size > 0xffff'd000`, it could have overflowed in vm due to the addition of 2 guard pages and the alignment up, matches with the kernel as it uses u64 all the way even when adding the pages. (for the 1m limit removal)
For main thread's stack:
* Min stack size bumped to 64k.
Additional fixes:
* Fix max allocations count for debug console mode, now allowing up to 512mb / 64k allocations.
* Improved idm's ID validation checking to check `id % step`.
* idm now allows to use `UINT32_MAX` as an id (as long …
=> ppu: Stack size allocation improvements

Utilities/File.cpp, Utilities/File.h
If one remove_file/all fails inside directory entries iterations, we can't recover from it. So add verifications for it.
=> Reflect proper error code in fs::remove_all on entries removal failures

Utilities/Config.h, Utilities/File.cpp, rpcs3/Emu/Cell/Modules/cellSpurs.cpp, rpcs3/Emu/Cell/Modules/cellSync.cpp, rpcs3/Emu/Cell/Modules/cellVdec.cpp, rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/PPUTranslator.cpp, rpcs3/Emu/Cell/lv2/sys_interrupt.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.cpp, rpcs3/Emu/Cell/lv2/sys_mmapper.h, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/Emu/Cell/lv2/sys_time.cpp, rpcs3/Emu/Memory/vm.cpp
* Fix FCTIW, FCTIWZ, FCTID and FCTIDZ instructions handling when float rounds to an integer bigger than INT(dest type)_MAX.
* Fix shift count in SRD and SLD instruction's ppu interpreter implementation by masking the shift count with 127 (UB fix).
* Make sys_get_current_time() scale time relatively to emulator startup instead of Epoch.
* Cleanup error_code conversations in mmapper_thread_recover_page_fault's usage.
* Fix an infinite loop when vm::find_map fails to find a location after the first try with alignment 0x8000'0000.
* Expose range of min/max integral settings for constexpr context usage, such as for size of array or static_assert.
* Remove an obsolete SSSE3 check from ppu interpreter main loop.
* Block reoredering of load after load in LWSYNC and places in hle code where its …
=> Accuracy improvements and some bugfixes

rpcs3/Emu/RSX/rsx_methods.cpp, rpcs3/Emu/RSX/rsx_utils.cpp, rpcs3/Emu/RSX/rsx_utils.h
* Fix for nv0039::buffer_notify when encountering overlapping memory at all cases.
* Fix overlapping transfers of nv3089::image_in and nv0039::buffer_notify when `out_pitch != in_pitch || out_pitch != out_bpp * out_w` and memory dest and source is overlapping.
* Fix a UB in image_in when using negative scaling.
=> rsx: Fix overlapping transfers of nv3089::image_in/nv0039::buffer_notify and when out_pitch != in_pitch || out_pitch != out_bpp * out_w

rpcs3/Json/tooltips.json
Since the merge of native OSK, back in February 2019, RPCS3 is able to support more languages with native UI. However, the description hasn't been updated since then. 
As far as I know, the languages that are now supported are: English, French, German, Italian and Spanish (referred as _Latin characters_). 
Both Greek and Russian use different alphabets from Latin, therefore they aren't supported. Polish or Norwegian, for example, use special Latin characters that aren't covered in extended ASCII character set. 
Chinese, Japanese and Korean aren't also supported, since they use a different character set.
=> Update "Enable native user interface" description

Utilities/date_time.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GSRender.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
Press F12 to take a screenshot.
Screenshots get saved to /screenshots/ directory.
Note that the screenshot is taken directly from buffer so you can actually take 10K screenshots if that is your upscaled resolution.
Thanks to KD-11 for guiding me through the VK labyrinth :D.
=> Screenshot function

Utilities/GDBDebugServer.cpp, Utilities/Thread.cpp, Utilities/lockless.h, Utilities/typemap.h, rpcs3/Emu/Cell/Modules/cellSync.cpp, rpcs3/Emu/Cell/PPUModule.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_gpio.cpp, rpcs3/Emu/Cell/lv2/sys_prx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui, rpcs3/util/atomic.hpp, rpcs3/util/typeindices.hpp
Load liblv2.sprx and manual selection. Similar to loading liblv2.sprx, but allows to specify libraries to LLE, like libvdec.sprx.
Load liblv2.sprx and strict selection. Only loads liblv2.sprx and libmodule.sprx, and nothing else unless specified on list.
=> Add new library loading modes

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/rpcs3qt/emu_settings.cpp
Bonus: old configs will be updated to use Usleep setting.
Fixes #6337.
=> Change default Sleep Timers Accuracy setting's value to "Usleep Only"

rpcs3/Emu/Cell/lv2/sys_process.cpp, rpcs3/Emu/Cell/lv2/sys_spu.cpp, rpcs3/Emu/Cell/lv2/sys_spu.h, rpcs3/Emu/Cell/lv2/sys_trace.cpp
Seeing in Modnation Racers. (iterates through all object types)
=> Improve sys_process_get_number_of_object, lv2_spu_image implemented

rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/System.h
What the new accuracy control offers: ensures no fragmentation when using GET commands and a simultaneous lock line atomic store is happening on another thread.
Fixed a very rare race condition resulting in a segfault after ppu thread deletion on non-tsx path at vm::writer_lock.
The segfault fix is very obvious if you add a sleep to https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Memory/vm.cpp#L247
such as 
```
for (auto& lock : g_locks)
{
if (cpu_thread* ptr = lock)
{
thread_ctrl::wait_for(1000);
ptr->state.test_and_set(cpu_flag::memory);
}
}
```
knowing a ppu thread could have been destroyed by the time its been dereferenced.
=> Add new accuracy control for PUTLLUC accuracy setting (non-TSX)

bin/GuiConfigs/YoRHa by Ani.qss
Starting with QT 5.13, having both fonts causes stylesheets to use the fallback font even if the first font is present, but uses the first font when there's no fallback font.
The fallback font (Arial) can safely be removed as the default one is 'good enough' for the intended purpose of having a fallback.
Thanks to @Megamouse for investigating and figuring out this quirk
=> gui: Remove fallback font from YoRHa theme

rpcs3/Emu/RSX/RSXFIFO.cpp
Fixed out of range methods execution as command register progresses above limit.
=> rsx: Fix possible out of range methods execution

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp, rpcs3/Emu/Cell/PPUThread.cpp, rpcs3/Emu/Cell/lv2/lv2.cpp, rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_event.cpp, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_mutex.cpp, rpcs3/Emu/Cell/lv2/sys_net.cpp, rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp, rpcs3/Emu/Cell/lv2/sys_sync.h
Fixes temporary awakening wrong threads with awake threads-list with FIFO protocol (because it doesn't match with the native priority protocol of the scheduler).
Fixes state fragmentation of running threads queue state at the time of beginning to end of thread list wakeup.
Matches with the kernel.
=> PPU/LV2: Make thread-lists scheduling atomic

rpcs3/Emu/Cell/lv2/sys_mutex.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
This protocol isn't implemented on real ps3 and is the same as SYS_SYNC_PRIORITY which is implemented and working.
=> lv2: Allow sys_sync_priority_inherit

Utilities/GDBDebugServer.cpp, rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUInterpreter.h, rpcs3/Emu/Cell/PPUThread.h, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
This adds missing FPCC tests on floting-point ops for ppu precise, and optimizes existing tests for ppu interpreters.
Also improve error checking of sys_semaphore_create: Return EINVAL on SYS_SYNC_PRIORITY_INHERIT protocol.
=> PPU Precise: FPCC handling on float ops implemented

rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellKb.cpp, rpcs3/Emu/Cell/Modules/cellKb.h, rpcs3/Emu/Cell/Modules/cellSysutil.cpp, rpcs3/Emu/Cell/Modules/cellSysutil.h, rpcs3/Emu/Io/Keyboard.h, rpcs3/Emu/Io/KeyboardHandler.cpp, rpcs3/Emu/Io/KeyboardHandler.h, rpcs3/Emu/System.h, rpcs3/Json/tooltips.json, rpcs3/basic_keyboard_handler.cpp, rpcs3/basic_keyboard_handler.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/main.cpp, rpcs3/rpcs3qt/emu_settings.h, rpcs3/rpcs3qt/settings_dialog.cpp, rpcs3/rpcs3qt/settings_dialog.ui
General:
Improved the number of supported keys for US and German keyboards and added an option to the system tab that controls the keyboard type.
Support for most of these specific layouts can be added quite easily in the future.
Windows only:
This should fix most issues with shifted keys (or any modified keys) when using the basic keyboard handler.
A game does not actually want us to tell it "_ was pressed". It wants us to pass "shift+-".
Before there was no easy way of knowing that '-' was pressed in 'SHIFT+-' in order to get '\_' in the game, because Qt would skip that step and tell the emulator "_ was pressed after shift". 
The same logic was added for alt.
=> Fix shifted keys on the basic keyboard handler (windows only)

rpcs3/Emu/Cell/lv2/sys_config.cpp
The enum fed into the template did not match the enum values used in the switch. It was discovered through warnings. Do we need to implement a string formatter for the third enum type?
=> Fix mismatched enum string formats in sys_config

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
- Further improves surface cache hierarchy and data tracking. Preserves data more strictly by ensuring everything generated on the GPU is visible to other surfaces.
- Implements Read Color Buffers and Read Depth Buffer for Vulkan. Fixes missing data when Cell and RSX work together to render a scene.
- Adds a workaround to prevent race conditions between Cell and RSX in the middle of a transfer operation. This is superceded by later works, but as they are still incomplete, this can serve as a stop-gap measure.
=> rsx: Surface cache improvements 2 [part 2 of 3]

rpcs3/Crypto/aes.cpp, rpcs3/Crypto/aesni.cpp, rpcs3/Crypto/aesni.h, rpcs3/Emu/CMakeLists.txt, rpcs3/emucore.vcxproj
This is based off the upstream implementation in mbedTLS as well as [an external pull request for MSVC support](https://github.com/ARMmbed/mbedtls/pull/1355).
Tested on Windows and Linux; please test for any regressions.
=> crypto: implement AES-NI acceleration

rpcs3/Emu/GameInfo.h, rpcs3/rpcs3qt/game_list_frame.cpp
Older games do not seem to have an APP_VERSION set in their PARAM.SFO which led to "Unknown" in the game list.
We now fall back to the VERSION in these cases.
It would be interesting to know the relationship between VERSION and APP_VERSION and if there is some deeper logic behind them.
=> Qt: Fall back to VERSION in game list

rpcs3/Emu/Memory/vm.cpp
Fixes mapping on vm::null (0x0) address (used in  recovering from SPU access violations after emulation stop by allocating the unmapped memory, now working on any address from 0x0 to 0xffff).
=> Fix vm::reserve_map logic

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp, rpcs3/Emu/Cell/Modules/cellMsgDialog.h, rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/Modules/cellSaveData.h, rpcs3/Emu/RSX/Overlays/overlay_controls.h, rpcs3/Emu/RSX/Overlays/overlay_list_view.cpp, rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/Emu/RSX/Overlays/overlays.h, rpcs3/rpcs3qt/msg_dialog_frame.cpp, rpcs3/rpcs3qt/save_data_dialog.cpp, rpcs3/rpcs3qt/save_data_list_dialog.cpp
I noticed a change for one of my games today:
Elad - knowingly or not - fixed input for Blazing Angels 2 a whopping 104 days ago. 🙇🙇🙇
So the first thing I did today was to play it for a few minutes.
At first I simply created a new profile and started a game, but when I came back half an hour later I noticed that the game wouldn't let me load my profile. This made me a bit sad, but I knew I had no chance at fixing it at all, so I just ignored it.
I then tried to delete the profile and was immediately greeted with an error message.
Deletion of files? That's something even I could do.
So I implemented both cellSaveDataDelete functions!
1. They open a save data list where all the entries for the current title are listed.
2. Upon selecting an entry a dialog will spawn, asking for user …
=> Implement cellSaveData List Deletion

appveyor.yml
- QT 5.13 requires 1.1.1, default "OpenSSL-Win64" folder on AppVeyor currently points to 1.0.2s
Fixes #6404
=> appveyor: Update OpenSSL DLLs to 1.1.1

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h, rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/Common/ProgramStateCache.cpp, rpcs3/Emu/RSX/Common/ShaderParam.h, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/GL/GLCommonDecompiler.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLRenderTargets.cpp, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/RSXFragmentProgram.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKVertexProgram.cpp, rpcs3/Emu/RSX/rsx_cache.h, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_methods.h, rpcs3/Emu/RSX/rsx_utils.h
- Implement 24-bit floats in depth texture decode step [D24S8->ARGB8]
- Fix some shader decompiler bugs
- Fix behavior of varying registers. Not all registers are created equal. Some have in-built saturate modifiers and texN registers can have their behavior altered through other registers. All tests confirmed on real hardware.
=> rsx: MGS4 fixes

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/RSX/Overlays/overlay_list_view.cpp, rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
Fixes a crash when the save data list overlay was loaded with focus on an element that didn't exist.
=> Fix crash when no entry is left during save data deletion

rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp
- Add pending flip requests as a reason to invoke the RSX local task handler and release the vblank semaphore.
Fixes https://github.com/RPCS3/rpcs3/issues/6413
=> rsx: Hotfix for semaphore timeout bug

rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Emu/Cell/lv2/sys_event.cpp, rpcs3/Emu/Cell/lv2/sys_event_flag.cpp, rpcs3/Emu/Cell/lv2/sys_lwcond.cpp, rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp, rpcs3/Emu/Cell/lv2/sys_mutex.cpp, rpcs3/Emu/Cell/lv2/sys_rwlock.cpp, rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
Wait for the thread to be scheduled before relocking the mutex, this matches with the kernel because it needs to be reschedulef before taking any action.
Can solve potential deadlocks whenever the waiting thread is still waiting for the scheduler yet other threads attempting to acquire the mutex.
Edit: it is also required for accurate ETIMEOUT checking, as on ps3 kernel the waiting thread needs to confirm condition not met after the amount of time specified, which means it needs to be scheduled beforehead.
=> sys_cond_wait: Wait for rescheduling before relocking

rpcs3/Emu/RSX/rsx_decode.h
=> Fix improper string concatenation in rsx_decode.

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLRenderTargets.h, rpcs3/Emu/RSX/VK/VKRenderTargets.h
Fixes several facepalm-worthy bugs found when investigating castlevania.
- Avoid silly broken tests due to queue_tag being called before pitch is initialized.
- Return actual memory range covered and exclude trailing padding in surface->get_memory_range().
- Coordinates in src are to be calculated with src_pitch, not required_pitch.
Fixes https://github.com/RPCS3/rpcs3/issues/6259
=> rsx: Fix surface cache hit tests

rpcs3/Emu/RSX/RSXThread.cpp
Followup to https://github.com/RPCS3/rpcs3/pull/6415. I forgot to update the mask lookup to account for the oddity that is surface_target_a.
=> rsx: Fixup for MRT color write lookup and surface_target_a

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/TextureUtils.h, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp, rpcs3/Emu/RSX/GL/GLTexture.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKCompute.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
bswap operations are rather slow (especially on ryzen) and this causes a huge performance drop in some games that have a small texture memory pool and reuse textures a lot. Nier is a good example of this where performance recently dropped by more than half when I forced texture decode to behave consistently and avoiding swizzle hacks. Instead, its faster to upload the raw pool to GPU and use pre-existing compute kernels to generate proper data for the textures needed.
~~While this recovers all the lost performance on AMD systems, I'm still tuning for NVIDIA cards where there still exists a slight performance loss vs the old hacky method.~~
=> rsx: GPU-accelerated texture decoding

rpcs3/Emu/System.cpp, rpcs3/Emu/System.h, rpcs3/headless_application.cpp, rpcs3/headless_application.h, rpcs3/main.cpp, rpcs3/main_application.h, rpcs3/rpcs3qt/gui_application.cpp, rpcs3/rpcs3qt/gui_application.h, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/msg_dialog_frame.cpp, rpcs3/rpcs3qt/msg_dialog_frame.h, rpcs3/rpcs3qt/qt_utils.cpp, rpcs3/rpcs3qt/qt_utils.h
Fix app version number and name when using --version or -v.
Use --headless instead of no-gui.
Add --no-gui param in order to load a game in its game window only.
Fixes #6402
Fixes #6397
=> Add --no-gui parameter. Fix cli args and app version/name

Utilities/File.h
Fixes building on linux with gcc ( https://github.com/RPCS3/rpcs3/issues/6474 ).
I don't know why but it leads to double inclusion of File.h otherwise:
> In file included from /home/tomripley/Repos/rpcs3/rpcs3/stdafx.h:31,
>                  from /home/tomripley/Repos/rpcs3/Utilities/dynamic_library.cpp:1:
> /home/tomripley/Repos/rpcs3/Utilities/File.h:20:13: error: multiple definition of ‘enum class fs::open_mode’
>   enum class open_mode : u32
>              ^~~~~~~~~
> In file included from /home/tomripley/Repos/rpcs3/rpcs3/stdafx.h:31,
>                  from /home/tomripley/Repos/rpcs3_build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.cxx:4,
>                  from /home/tomripley/Repos/rpcs3_build/rpcs3/Emu/cotire/rpcs3_emu_CXX_prefix.hxx:4:
> …
=> Revert File.h encoding

rpcs3/Emu/Cell/PPUInterpreter.cpp
Some SSE4.1 code was introduced with https://github.com/RPCS3/rpcs3/commit/a560498cd4d18b4dff820c35f9cb3a5f00fbf630 without updating the build flags thus resulting in #6479.
The `_mm_extract_epi` calls which is the SSE4.1 code in question can easily be replace with a single `_mm_cvtsi128_si` call each since we only access the lower integer. This generates identical code and removes the SSE4.1 requirement. Fixes #6479
=> Remove SSE4.1 requirement

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Tested on decr and files are always presented in savedata_op buffer in creation order(oldest created first), with deleted files leaving an empty space for future files.
This is presumably a result of BSD filesystem on the ps3(thanks to Neko for pointing it out).
It adds RPCS3_BLIST section to PARAM.SFO which maintains a list of the files as they would be on bsd.
=> Simulate BSD FS for savedata file presentation order

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Fixes "Entry value shrinkage" error.
Provide additional byte for null terminator. Also align to 4 since records are usually aligned like this.
=> cellSaveData fixup (#6393)

rpcs3/Emu/RSX/VK/VKGSRender.cpp
Defers renderpass open to allow recovery after fault in the middle of vertex upload. This fixes problem where flushing during draw calls would lead to inconsistent object state and upon "recovery" draw calls would be guaranteed to fail or crash the driver. Seemingly not a big problem for NV but should reduce chances of flickering when WCB is enabled.
Also adds a missing texel buffer entry in the descriptor pool allocation.
=> vk: Restructure commandbuffer scoping to allow faults in vertex upload

Utilities/File.cpp, Utilities/File.h
Convert EROFS error to avoid crashing on a read-only filesystem
=> Convert EROFS error

rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
- Allow fast upload of data by looking for opportunities to upload the full data block in one go.
Minor performance improvement noted when profiling a particularly problematic game (Split Second)
- Allow for auto-matching of pitch dimensions. Dumping statistics from games shows most use pitch alignment of 1 and there is no reason to force 256-byte alignment when uploading. Allows fast-copy to work which should make it easier on the GPU and CPU to handle. Also drastically lowers memory footprint of smaller textures.
- Batch compute and transfer operations when decoding texture data. Lowers overall number of compute invocations by an order of magnitude.
=> rsx: Minor texture optimizations

rpcs3/Emu/CPU/CPUThread.cpp
Fixes threads not leaving their passive vm lock after exiting by dbg_global_stop.
=> Fix passive reservation locks checking at Emu.Stop() (non-TSX)

rpcs3/Emu/System.h, rpcs3/rpcs3qt/debugger_frame.cpp, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.h, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/qt_utils.h
Adds a more convinient and user-friendly way of removing disk cache; by just clicking on `File > All Games > Remove Disc Cache`.
=> Add disk cache removal to UI

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTexture.cpp, rpcs3/Emu/RSX/VK/VKTextureCache.h
- Fix OGL decode description for uint_24_8. (https://github.com/RPCS3/rpcs3/issues/6433)
- Fix broken source reference when doing Z scaling (https://github.com/RPCS3/rpcs3/issues/6434)
- Fix missing target when using vulkan surface transforms without scaling. (https://github.com/RPCS3/rpcs3/issues/6434)
- Remove unused surface transform argb_to_bgra. Vulkan now has proper texture decoding so this just jumbles the data even more. (https://github.com/RPCS3/rpcs3/issues/6434)
Fixes https://github.com/RPCS3/rpcs3/issues/6433
Fixes https://github.com/RPCS3/rpcs3/issues/6434
=> rsx: Misc fixes

rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/Common/texture_cache_utils.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
- gl/vk: Check if a region matches the requested format before assuming it is a match. Fixes some instances of assert(!region.is_locked())
- rsx: Unify upload contexts. Hacks used to process types like ARGB8 were previously removed making data from blit_src, blit_src and shader_read map to the same memory layout in VRAM for a given memory input. This greatly simplifies the lookup methods when doing blit operations and should clear up the remaining crashes due to blit_src creation overlapping pre-existing shader_read data.
Fixes https://github.com/RPCS3/rpcs3/issues/6456
Fixes https://github.com/RPCS3/rpcs3/issues/6098
Fixes https://github.com/RPCS3/rpcs3/issues/6509
=> rsx: Texture cache fixups

Utilities/Thread.cpp
Less platform-specific code to worry about when porting.
=> Drop unused is_leaf_function

rpcs3/rpcs3qt/game_list_frame.cpp
This PR unifies behaviour of "Clear shaders cache" with the other two cache clears (PPU/SPU). 
Previously, if game's cache directory contained more than one subdirectory (due to either having multiple executables or having been used with different patches), only the first one was cleared. This has been changed to be same as with SPU/PPU caches, and so all shader caches are cleared.
This allows Gran Turismo 5 (and probably 6) to have its shader cache cleared properly on the first sweep. I believe previously shader cache clear had to be re-run multiple times to clear all caches.
=> Make "Clear shader cache" clear all caches, not just the first

BUILDING.md
Encountered a build error when building on windows recently:
CMake Error: Could not create named generator Visual Studio 16 2019
This generator is only implemented in CMake 3.14.1+.
=> Update CMake version in BUILDING.md

rpcs3/Json/pad_settings.json, rpcs3/resources.qrc, rpcs3/rpcs3qt/pad_settings_dialog.cpp, rpcs3/rpcs3qt/pad_settings_dialog.h, rpcs3/rpcs3qt/pad_settings_dialog.ui
This PR adds a feature that changes the description text in pad configuration screen to provide useful information about the currently selected handler. Some of the descriptions contain links to wiki for most common issues. Hopefully this will reduce confusion and let users know about some obscure features.
I'm not a native speaker, so feel free to suggest improvements to the texts if you have any.
=> Add handler descriptions to pad settings

rpcs3/rpcs3qt/gui_settings.h, rpcs3/rpcs3qt/log_frame.cpp, rpcs3/rpcs3qt/log_frame.h
Adds the ability to activate "stack mode" in the TTY viewer. Much like its counterpart in the Log, it can help increase readability by reducing repeated messages to a counter. it is off by default and can be toggled separately from the stack mode in the log by a checkbox in the TTY context menu.
=> Add a "stack mode" to the TTY.

rpcs3/rpcs3qt/settings_dialog.cpp
Should be `CPU` instead of `cpu`
=> TSX instruction tooltip typo fix

rpcs3/Crypto/md5.cpp, rpcs3/Crypto/md5.h, rpcs3/Emu/CMakeLists.txt, rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Cell/lv2/sys_usbd.cpp, rpcs3/Emu/Cell/lv2/sys_usbd.h, rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/Io/Skylander.cpp, rpcs3/Emu/Io/Skylander.h, rpcs3/Emu/Io/usb_device.cpp, rpcs3/Emu/Io/usb_device.h, rpcs3/emucore.vcxproj, rpcs3/emucore.vcxproj.filters, rpcs3/pad_thread.cpp, rpcs3/pad_thread.h, rpcs3/rpcs3.vcxproj, rpcs3/rpcs3.vcxproj.filters, rpcs3/rpcs3qt/CMakeLists.txt, rpcs3/rpcs3qt/main_window.cpp, rpcs3/rpcs3qt/main_window.ui, rpcs3/rpcs3qt/skylander_dialog.cpp, rpcs3/rpcs3qt/skylander_dialog.h
sys_usbd implementation with:
-Passthrough implementation for
*Guitar Hero/Harmonix Guitars/Drums(untested)
*DJ Hero Turntable(Both DJ Hero 1&2 work perfectly)
*Skylander Portal(working)
*Singstar Microphone(untested and probably broken)
*Various wheels supported by GT5/GT6(G27 tested working on GT5/GT6)
-Framework for USB device emulation with:
*Fake Skylanders Portal basic implementation(Manager=>Skylanders Portal to config, each file represent a figure). Tested only with Skylanders SWAP Team.
To make it work on linux:
You need to add:
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", MODE="0666"
To a rule file in /etc/udev/rules.d/
Note that this give r/w access to all usb devices by default, if you want to specify a specific device you can use:
SUBSYSTEM=="usb", ATTRS{idVendor}=="ABCD", …
=> sys_usbd implementation

rpcs3/Emu/RSX/VK/VKProgramBuffer.h
- It is possible (albeit rare) for an application to change the sample mask when rendering. This means not only the rendertarget configuration is important (with its RP key) but also the active sample mask.
Discovered when running hw tests for https://github.com/RPCS3/rpcs3/issues/6403.
=> vk: Fix pipeline search when using MSAA

rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp, rpcs3/Emu/RSX/D3D12/D3D12GSRender.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLGSRender.h, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/GSRender.cpp, rpcs3/Emu/RSX/GSRender.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKGSRender.h
Add an explicit frame scope marker tied in with the queue_prepare command. Since queue_prepare is emitted at the end of a frame, it can be used as end-of-frame in games that emit this. If this command is not emitted, fifo flatenner and frameskip will not work.
- Improves compatibility of games with frameskipping and FIFO flattener optimizations.
- Fixes malformed RSX captures due to asynchronous flip handling in many games. Captures should now be frame-complete and render properly instead of the common black screen.
=> rsx: Restructure flip code and frame scoping

rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
The overlay controls as well as the native on-screen keyboard both checked for enter button assignment.
This effectively rendered the option for the osk useless by switching the buttons twice.
should fix #6518
=> Fix enter button assignment in the native On-Screen Keyboard

rpcs3/headless_application.cpp, rpcs3/rpcs3qt/gui_application.cpp
Forces numeric locale to "C" for standard behaviour for posix function.
See https://doc.qt.io/qt-5/qcoreapplication.html#locale-settings
This fixes https://github.com/RPCS3/rpcs3/issues/6506 .
=> Forces numeric locale to default

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
Fixes https://github.com/RPCS3/rpcs3/issues/6540
Chain of events:
- Offloader thread is working slower than main renderer. Main renderer starts preparing a display flip.
- Renderer waits for offloader, but offloader faults and signals the renderer to wake it,
- Renderer enters the recovery handler. The recovery handler calls the cleanup code which noitces a pending flip request in the queue and issues another flip request while the original one is still being processed.
- We have 2 flip requests being processed recursively, and the assertion fires.
=> rsx: Avoid recursion in flip handler

rpcs3/Emu/Cell/Modules/cellGem.cpp, rpcs3/Emu/Cell/Modules/cellPad.cpp, rpcs3/Emu/Io/PadHandler.h, rpcs3/Emu/RSX/Overlays/overlays.cpp, rpcs3/ds3_pad_handler.cpp, rpcs3/ds4_pad_handler.cpp, rpcs3/evdev_joystick_handler.cpp, rpcs3/keyboard_pad_handler.cpp, rpcs3/mm_joystick_handler.cpp, rpcs3/pad_thread.cpp, rpcs3/pad_thread.h, rpcs3/xinput_pad_handler.cpp
The prior fix for Hotline Miami was a bit overkill apparently, as Ninja Gaiden Sigma now freaks out if you hold any button too long after dialogs and opens the menu in defense.
We now don't keep the pads intercepted anymore but simply don't give the game any input while buttons are kept pressed when closing dialogs.
This should work with Hotline Miami and Ninja Gaiden Sigma.
Also removes some unused code.
This should fix #6387
=> Fix pad interception (again)

rpcs3/Emu/CPU/CPUThread.cpp
Fixed a situation where: Theres an ETIMEDOUT in sys_cond_wait.
check_state() tries to awake ppu, didnt succeed.
fallbacks to thread_ctrl::wait(), later wakes up spuriously.
then checks cpu_flag::signal but it is not there.
a little after the thread is awaken externally.
the thead checks cpu_flag::suspend, but it is not there so it returns, but cpu_flag::signal is still set.
what causes the mess in lv2_obj::sleep when trying to wait on mutex owner.
Seen in Demon Souls as a regression because of recent sys_cond changes.
=> dont escape from check_state() before ensuring signal is resetted.

rpcs3/Emu/Cell/Modules/sceNpSns.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.h
Adds some checks by partly reversing the functions. (not just guesswork)
Init checks are part of the unknown context check, that's why they are preceeding those.
=> sceNpTrophy: add more error checks

rpcs3/Json/pad_settings.json, rpcs3/xinput_pad_handler.cpp, rpcs3/xinput_pad_handler.h
This is a second, **mutually exclusive** take on #6208.
I took another shot at it because looks like new SCP is not really... reliable. It seems to make much more sense to make SCP extension support totally optional and implicit, without requiring the user to reconfigure anything to use it, except for putting `xinput1_3.dll` from SCP in RPCS3 directory.
Unlike #6208, this PR does not expose a new handler, everything is transparent to the user. RPCS3 will **try** to use SCP extension and if it's either not present or not supported by the used pad, it falls back to base XInput implementation.
While this does not solve the issue of SCP being spotty, it should make it less confusing for the user.
FYI this approach is also used by PCSX2 successfully.
=> Add SCP extension support to XInput pad handler

rpcs3/Emu/RSX/GL/GLGSRender.h
Regressed by https://github.com/llvm/llvm-project/commit/1d16515fb407. Found via [freebsd#240629](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=240629).
```
$ c++ --version
FreeBSD clang version 9.0.0 (tags/RELEASE_900/final 372316) (based on LLVM 9.0.0)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
$ c++ -Wl,--version
LLD 9.0.0 (FreeBSD 372316-1300004) (compatible with GNU linkers)
$ git describe --tags --always
v0.0.7-144-g40fcd457b
$ git rev-list --count HEAD
8759
$ cmake -DUSE_SYSTEM_FFMPEG=ON -DUSE_SYSTEM_LIBPNG=ON -GNinja /path/to/rpcs3
$ ninja
[...]
c++: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
ld: error: rpcs3/CMakeFiles/rpcs3.dir/main_application.cpp.o: unable to find library from dependent library …
```
=> Unbreak with Clang/LLD 9

rpcs3/Emu/Cell/Modules/cellSaveData.cpp, rpcs3/Emu/Cell/lv2/sys_fs.cpp, rpcs3/Emu/System.cpp, rpcs3/Emu/VFS.cpp, rpcs3/Emu/VFS.h
Add savedata maintenance routine:
1) Removes junk backup directories
2) Fixes interrupted save data process in edge case
This case can happen if emu terminates between two atomic renames.
Also use directory renaming technique for delete op.
Improve sys_fs_unlink and sys_fs_rmdir behaviour on Windows.
=> cellSaveData improvements

rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKTexture.cpp
- Adds chip family detection. Not all cards from one vendor will behave the exact same; it is useful to detect the proper class.
- Adds a fix for turing crash when doing depth_stencil scaling.
Turing cards will throw VK_ERROR_DEVICE_LOST if you try to use the depth blitting hack like rpcs3. NV cards do not export BLIT_DST feature for any of the depth-stencil formats which means to scale these, we need to transfer into a color image first, then scale and copy back. This is already supported but was only enabled for the D32S8 format which is used by all non-nvidia GPUs. The primary reason for the hacky workaround is performance; hopefully turing handles this without much performance lost.
=> vk: Fix DEVICE_LOST for turing cards

rpcs3/Emu/System.cpp
Prints the game version to log when booting. Might be useful for debugging.
=> Log game version

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp
LLVM:
* Now loads (or computes) less immediate values. (shift count is hardcoded to the instruction, it comes as free to use it)
* BGX's comparisons optimized (removed one comparison, replaced non-native "Lower/Equal" comparison with native "Greater" comparison, unfortunatly still suffers from unsigned problem).
ASMJIT:
* The instructions are now vectorized.
=> SPU: Rewrite CGX/BGX

Utilities/geometry.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLOverlays.h, rpcs3/Emu/RSX/GL/GLVertexProgram.cpp, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKOverlays.h, rpcs3/Emu/RSX/VK/VKResolveHelper.h
- Properly fit overlays to drawable area to match game visuals.
- Remove a debug print forgotten in the code.
Fixes https://github.com/RPCS3/rpcs3/issues/6648
=> rsx: Fix overlay scaling

rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h
- Allows frameskipping to occur naturally if RSX thread is bombarded with flip requests but just jumping to the last one if possible. (See request_emu_flip() for async frame submission and implicit skipping)
- Also allows display queue to fill faster than the flip thread can drain the queue.
Fixes https://github.com/RPCS3/rpcs3/issues/6662
=> rsx: Restructure deferred flip queue handling

rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h
- Handle descriptor reset in thread::end to allow asynchronous flips to safely occur in a begin-end cycle without crashing the drivers.
- Align width up from surface cache before bpp normalization to avoid a result of 0 width.
- Increase fence/event timeout to multiple seconds.  It is possible for the driver thread to "starve" if the emulator is compiling LLVM modules with all threads, causing a small timeout to fail.
Fixes https://github.com/RPCS3/rpcs3/issues/6597
Also fixes a spurious crash in GT6 after the attract video
=> vk: Stability fixes

rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/gcm_enums.h
Testcase: https://github.com/elad335/myps3tests/tree/master/rsx_tests/FIFO%20PUT%20masking
Results: When the rsx reads from PUT: it masks down the value to 4 bytes alignment and writes back the value.
This process doesnt occur immediatly after write, only when the rsx sees the update.
How the testcase works:
- Sets an unaligned value for PUT with invalid command at the end of FIFO range, waits for possible crash.
- Crash doesnt occur.
- Reads from current value of PUT for logging.
- Spins on a loop which checks if PUT writes are modified by rsx at some point, also saved the "modified value".
- Spins on a loop which checks if the process of modifying PUT occurs immediatly.
- Prints both PUT values which we saved.
realhw:
`sample finished. PUT=0x10003c, PUT1=0x10003d`
rpcs3 master:
`E {RSX …
=>  rsx: Mask FIFO PUT on rsx execution

rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
* Update GET value as it reaches semaphore_acquire -
Since the command progrerssed to the first or more argument of the command, it incremented GET.
This can techincally be used to locate if RSX is acquiring a semaphore by reading GET's value.
* Remove redundent PUT masking operations, reduce to a single one at command start.
=> rsx: Optimize FIFO PUT masking, Flush GET before semaphore_acquire

rpcs3/util/endian.hpp
They were removed approximately 3 years ago due to their rarity.
=> Restore experimental optimized operators &= |= ^= for se_t

Utilities/geometry.h, rpcs3/Emu/RSX/Common/surface_store.h, rpcs3/Emu/RSX/Common/surface_utils.h, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
Due to historical design decisions, transfer descriptors had to be based on one of the two surfaces, source or destination, even in cases where it made no sense to do so. When adding in some new functionality, this problem became very obvious as the descriptors are clearly rebased inconsistently. This commit explicitly defines two separate regions for the incoming and outgoing surfaces, making things much easier to work with. An optional transform descriptor is included to make porting old logic easier.
Some incoming new functionality relies on this working correctly, so I'd like to get it set up for extensive regression testing. Might also fix some strange texture cache bugs introduced in the new texture cache.
=> rsx: Explicity describe transfer regions for both source and destination blocks

rpcs3/evdev_joystick_handler.h, rpcs3/mm_joystick_handler.cpp, rpcs3/mm_joystick_handler.h
Fixes the constant mmjoystick log spam that was accidentally introduced with the pad handler refactoring a few weeks ago.
Due to a faulty function call the joysticks were constantly reconnecting during gameplay, which is only supposed happen if the controller was disconnected before.
=> Fix mmjoystick log spam

Utilities/File.cpp
There's no reason these two functions should return different mtime on windows, and also ChangeTime cannot be influenced by fs_utime, only LastWriteTime can.
This fixes MGS4 disc versions always deleting stage dat files on boot because mtime doesnt match expected (set by fs_utime) on windows, forcing a chapter reinstall every boot.
=> Make windows_file::stat return the same mtime as fs::stat

rpcs3/Emu/Cell/lv2/sys_rsx.cpp
[Testcase](https://github.com/elad335/myps3tests/blob/master/rsx_tests/Zcull%20report%20area%20default%20padding%20value/expected.txt)
=> rsx: Default initailize zcull reports padding

rpcs3/Crypto/unpkg.cpp, rpcs3/rpcs3qt/vfs_dialog.cpp
Corrects the case where it was (usually) not possible to install games/firmware after changing path dev_hdd0 (and potentially others) in settings, and required a restart instead.
1. Launch RPCS3 with `$(EmulatorDir) set to eg. `D\RPCS3`.
2. Open Virtual File System settings.
3. Change `$(EmulatorDir)` to any new empty folder, eg. `D:\RPCS3\NewDirForFiles` and click Save.
4. Attempt to install any game.
Installation fails, because directories are not created recursively and a parent directory does not exist.
Installation proceeds as normal.
=> Create emulator directories after changing dev_*** directories

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUInterpreter.cpp, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/lv2/sys_gpio.cpp, rpcs3/Emu/Cell/lv2/sys_gpio.h
testcase : https://github.com/elad335/myps3tests/tree/master/spu_tests/SRR0%20masking
Testcase write -1 to srr0, read value is 0x3fffc.
=> SPU: Mask SRR0 at write

rpcs3/Emu/Cell/Modules/cellGem.cpp, rpcs3/Emu/Cell/lv2/sys_cond.cpp
* camera_frame = NULL is now checked for CELL_GEM_NO_VIDEO (applied both on start and finish)
* camera_frame = NULL on Start() still starts the update.
* Implemented NOT_FINISHED/STARTED checks.
All of those were reversed and hw tested.
* Fixed a verification failure when stopping the emulation regarding cond variable's mutex ownership.
=> cellGemUpdateStart/Finish error checking improved 

rpcs3/Emu/GDB.cpp
This PR enables 'GDB Server' config string as following:
* Empty string or a string starting with null character will disable GDB server.
* IPv4 ip:port format such as  `127.0.0.1:2345` will create AF_INET socket and bind it on specified address and port.
* Fallback will use AF_UNIX socket on all platforms. May actually work on newer win 10.
=> GDB Server: fix config and add Unix socket support

Utilities/Thread.cpp, Utilities/Thread.h, rpcs3/Emu/Cell/lv2/sys_sync.h
This patch is for review/discussion. I do not know if I got everything in the
right place.
The current sleep timer implementation basically offers two variants. Either
wait the specified time exactly with a condition variable (as host) or use a
combination of it with a thread yielding busy loop afterwards (usleep timer).
While the second one is very precise it consumes CPU loops for each wait call
below 50us. Games like Bomberman Ultra spam 30us waits and the emulator hogs
low power CPUs. Switching to host mode reduces CPU consumption but gives a
~50us penalty for each wait call. Thus extending all sleeps by a factor of
more than two.
The following bugfix tries to improve the system timer for Linux by using
Linux native timers for small wait calls below 1ms. This has two effects.
- Host …
=> Use Linux timers for sleeps up to 1ms

rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/gcm_enums.cpp, rpcs3/Emu/RSX/gcm_enums.h, rpcs3/Emu/RSX/rsx_methods.cpp
Hw tests reveal that any write with a bit set to 1 which are not bits 0 or 3 to register CELL_GCM_NV4097_SET_INDEX_ARRAY_DMA, results in an exception being raised at the write command.
Because the exception is raised at command write, that's where I decided to put the validation check.
This improves stability in Metal Gear Solid 4, allowing the renderer to continue after such crash.
Second commit improves FIFO recovery when the last semaphore came from a flip, allowing to reset registers using gcm's reset by ignoring the last semaphore_release (recovering from the first semaphore_acquire instead). Inspired by [flip commands sequence dump](https://github.com/elad335/myps3tests/blob/master/rsx_tests/cellGcmSetFlip%20internals/RPCS3.log)
=> rsx: Recover from invalid writes to CELL_GCM_NV4097_SET_INDEX_ARRAY_DMA

rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/PPUDisAsm.h
* Fix address view of BC AA in ppu disasm.
* Implement extended mnemonics of BCLR and BCCTR as ida.
* BCCTR cr bit is now shown as cr(bit/4)[bit % 4].
* BLRL is now shown properly.
* `BDN?Z[TF](LR?)L?A?` branch mnemonics are now implemented.
=> PPU Disassembly Improvements Part 2

.travis/deploy-linux.bash, appveyor.yml, rpcs3/git-version.cmake, rpcs3/rpcs3_version.cpp
Follow up to #6555 , still missing most things but opened for discussion
---
Issues with tag usage were already discussed too, but tag usage is working differently on packaging and on the emulator itself (see, for example, [this build](https://ci.appveyor.com/project/kd-11/rpcs3/builds/27467065/artifacts) which has v0.0.0.6 on package name but v0.0.7 as internal name), and it was left as it is currently pending future updates. It's probably a good idea to either:
- Use only the git describe tags and drop all other tag usages (rpcs3_version). We can use the values in git-version.h and avoid having to go through the git commands and checks again on the CI scripts.
I suggest going for the first option, this way we can end the issue of forks having different tags on package names than the …
=> Update git-version generation

rpcs3/Emu/RSX/RSXFIFO.cpp
FIFO_control::read() always starts with a read_put() statement that tries
to reset the two lower bits of m_ctrl->put. That is useless most of the
time. So just use it when really needed.
Bomberman Ultra gameplay before:
```
16,40%     0,00%  rsx::thread  [unknown]  [.] 0000000000000000
11,57%    10,47%  rsx::thread  rpcs3      [.] rsx::thread::run_FIFO
9,89%     0,00%  rsx::thread  [unknown]  [.] 0x00401f0fffc832d4
9,89%     0,00%  rsx::thread  rpcs3      [.] named_thread<VKGSRender>::~named_thread
8,38%     8,23%  rsx::thread  rpcs3      [.] rsx::FIFO::FIFO_control::read
```
Bomberman Ultra gameplay after:
```
17,03%     0,01%  rsx::thread  [unknown]  [k] 0000000000000000
12,31%    11,20%  rsx::thread  rpcs3      [.] rsx::thread::run_FIFO
11,04%     0,00%  rsx::thread  [unknown]  [.] …
```
=> mitigate use of cmpxchg() in FIFO_control::read_put()

rpcs3/Emu/Cell/lv2/sys_sync.h, rpcs3/Emu/System.h
The previous worst case for the host setting (Nier) now performs the same on both the host and the usleep setting, so let's just make host the default.
A few games are faster with host that previously required usleep (Journey)
This won't change existing configs.
Also sets the host_min_quantum to the true value and restores a lost `TODO:` comment
=> Linux: Change default Sleep Timers accuracy to host

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp, rpcs3/Emu/Cell/Modules/sceNpTrophy.h, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/Emu/Cell/SPUOpcodes.h, rpcs3/Emu/Cell/lv2/sys_cond.cpp, rpcs3/Loader/TRP.cpp
* Logging improvements for failed sceNpTrophyRegisterContext call with ILLEGAL_TROPHY error.
* interrupts disable/enable SPU bits status is now shown on instruction name.
* Wait a little longer for possible sys_mutex_unlock() after confirming signal by checking cond.sq, yet the owner ship has yet to pass.
=> spu-disasm Improvement, sys_cond Fix, More verbose logging for TrophyRegisterContext

rpcs3/Emu/Cell/Modules/cellUserInfo.cpp, rpcs3/Emu/Cell/PPUDisAsm.cpp, rpcs3/Emu/Cell/SPUDisAsm.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3/Emu/Cell/lv2/sys_spu.cpp
Also contains two more commits:
**cellUserInfoGetList changes**: 
- logically if we report only one user in user list, it must be the current user.
- Set unwritten entries to zero.
- Do not allow all args to be nullptr at once.
Restores lost commit from pr #5346, the point is to not reset spu signotify config in gropu_start(), error checking ordering fix. (the pr includes the testcases)
=> Fixup for spu/ppu disasm prs

rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKResolveHelper.cpp, rpcs3/Emu/RSX/VK/VKResolveHelper.h
- Properly detect kepler GPUs and add a workaround for them.
- Use chip class testing instead of GPU name to detect AMD Vega and apply the fp16 workaround.
=> vk: More chip-specific workarounds

rpcs3/rpcs3qt/gs_frame.cpp, rpcs3/rpcs3qt/gs_frame.h
only update the window title if user really wants to display the FPS during gameplay. Additionally wait some frames for better low FPS averages.
=> avoid update of window title

rpcs3/Emu/Cell/Modules/cellPad.h, rpcs3/Emu/Cell/Modules/cellScreenshot.cpp, rpcs3/Emu/Cell/Modules/cellScreenshot.h, rpcs3/rpcs3qt/gs_frame.cpp
Implements the basic setup of the cellScreenshot utility.
This includes enabling/disabling screenshots, getting the desired screenshot name and metadata, as well as receiving the optional overlay image information.
This is connected to the existing rpcs3 screenshot shortcut and creates a second screenshot in "/screenshots/cell/".
It will only create the second screenshot if the game enabled it.
TODOs:
The overlay is not yet added to the screenshot (if one was specified).
The filenames are not incrementing yet.
=> cellScreenshot: initial implementation

rpcs3/Emu/Io/MouseHandler.h, rpcs3/Emu/Io/Null/NullKeyboardHandler.h, rpcs3/Emu/Io/Null/NullMouseHandler.h, rpcs3/Emu/Io/Null/NullPadHandler.h, rpcs3/basic_keyboard_handler.cpp, rpcs3/rpcs3qt/gs_frame.h
Ignore keyboard events in the basic keyboard handler while no keyboards are registered.
may improve #6781
=> Input: avoid exception while no keyboard is registered

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/GL/GLTextureCache.h, rpcs3/Emu/RSX/VK/VKFormats.cpp, rpcs3/Emu/RSX/VK/VKFormats.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp, rpcs3/Emu/RSX/VK/VKHelpers.h, rpcs3/Emu/RSX/VK/VKResourceManager.cpp, rpcs3/Emu/RSX/VK/VKResourceManager.h, rpcs3/Emu/RSX/VK/VKTextureCache.h
A collection of small fixes to the texture cache to improve memory usage and other miscellaneous bugs.
- Adds a video memory manager to vulkan. Doesn't do much by itself but is useful for debugging and logs suspiciously large allocations.
- Improve surface reuse in the texture cache when a subresource cache entry is available and when its not. The old way of waiting at least one whole frame before reusing memory could lead to quasi-leaks.
- Vulkan improvement to renderpass management by detecting uncacheable resources.
- Fix a minor regression from the mipmaps PR causing mismatched texture layouts in vulkan.
- Force compressed textures to be 2D or higher and force 4-texel alignment. While 1D textures are used on PS3, they are not allowed by all desktop implementations. Upload as 2D image …
=> rsx: Minor texture cache improvements

rpcs3/Emu/RSX/RSXTexture.cpp, rpcs3/Emu/RSX/rsx_decode.h, rpcs3/Emu/RSX/rsx_utils.h
* Fix -2048.0 scaling in image_in, was treated as invalid input.
* Unify fixed-point decoding.
=> rsx util: Implement decode_fxp<>

rpcs3/Emu/Cell/lv2/sys_usbd.cpp
* Do not unconditionally call lv2_obj::sleep in sys_usbd_receive_event.
* Because sys_usbd uses sys_event internally it allows u64 arguments, as opposed to u32 previously. (although it does not matter from cellUsbd side)
* Use SYS_SYNC_PRIORITY porotocol in receiveing/signaling events syscalls.
* Forcefully awake threads in sys_usbd_finalize. (although it does not matter from cellUsbd side, because it also happens manually in cellUsbdEnd)
* Throw if sys_usbd_initialize was called twice.
=> sys_usbd Update

rpcs3/util/atomic.cpp
Before, hashtable collision would result in the slow fallback path. Now this slow path is removed and new tree-based approach is used. Also reduced total memory usage.
=> atomic.hpp: rewrite collision handling

rpcs3/Emu/Cell/PPUInterpreter.cpp, rpcs3/Emu/Cell/PPUInterpreter.h, rpcs3/Emu/Cell/PPUThread.cpp
Also cleanup add64_flags, remove redundent copy of s_ppu_itype.
Fixes access violation at loading new game with Far Cry 3 (the fix currently available only on ppu precise interpreter).
=> PPU Precise: Fix fused float ops misaccuracy by using fma 

rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKFormats.cpp
Companion PR to https://github.com/RPCS3/rpcs3/pull/6774
This PR aims to keep images scaled via blit engine visible to the texture cache lookup routines. This allows mipmaps generated through method 2 detailed in the last PR to be properly gathered.
- Adds a fix to avoid deleting blit engine generated data inadvertently when it shares pages with a framebuffer.
- Tries to improve heurestics with the behavior of RSX if "use GPU texture scaling" is set to off. If scaling or format conversion is being done, just use the GPU. Its much faster and there is little reason to force the CPU fallback in these situations. Moving the data to the GPU side also makes it visible to the texture cache when gathering mipmap levels.
With this fix, some games like The Evil Within show correct visuals when …
=> rsx: Preserve visibility of scaled blit targets [ 2 of 3]

Utilities/JIT.cpp
Check LLVM ObjectFile state before access to avoid llvm assertion failure.
Expected<T> must be checked before access or destruction.
Expected<T> value was in success state. (Note: Expected<T> values in success mode must still be checked prior to being destroyed).
=> Debug build : Check ObjectFile before reading.

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/Memory/vm.cpp, rpcs3/Emu/Memory/vm.h, rpcs3/Emu/RSX/RSXFIFO.cpp, rpcs3/Emu/RSX/RSXFIFO.h, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/rsx_methods.cpp
* sys_rsx commit restores improved internal error checks and behaviour from #5297. (the pr includes the testcase)
* Fix local_size reported in LLE cellGcmGetConfiguartion, testcase is the same as the one mentioned above.
* Log more info about invalid methods execution and FIFO desync, including  description of starting command and methods range of it.
* Fix vblank signals flood after emulator has resumed from pausing.
=> rsx: sys_rsx Fixes, FIFO desync logging improved, cellGcmGetConfiguration fix, vblank signaling fix

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp, rpcs3/Emu/Cell/SPUASMJITRecompiler.h, rpcs3/Emu/Cell/SPURecompiler.cpp, rpcs3/Emu/Cell/SPURecompiler.h, rpcs3/Emu/Cell/SPUThread.cpp, rpcs3/Emu/Cell/SPUThread.h, rpcs3_default.props
Should improve SPU LLVM in cases of stuttering or bugs caused by interrupting SPU threads with compilation. Compilation in SPU LLVM is now offloaded to separate thread.
=> SPU LLVM: asynchronous compilation

rpcs3/rpcs3_version.cpp
It's sometimes hard to see an obvious bug until the code is in production.
=> Fix for auto updater

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp, rpcs3/Emu/RSX/Common/GLSLCommon.h, rpcs3/Emu/RSX/Common/GLSLTypes.h, rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp, rpcs3/Emu/RSX/GL/GLFragmentProgram.h, rpcs3/Emu/RSX/GL/GLGSRender.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/RSXThread.h, rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp, rpcs3/Emu/RSX/VK/VKFragmentProgram.h, rpcs3/Emu/RSX/VK/VKGSRender.cpp, rpcs3/Emu/RSX/VK/VKHelpers.cpp
- Implements integer renormalization at 8 bits to mimic NVIDIA hardware implementation. All NVIDIA cards seem to normalize small-width integers smaller than 8 bits to 8 bits internally which causes an arithmetic error of around 1 part in 255. This error is small, but when used as for texture lookups, the error can be magnified greatly due to the relatively large texture sizes, causing unexpected errors. This option is enabled for AMD (which is too precise) and Intel (which is untested but expected to not follow NVIDIA's unorthodox implementation).
- Refactors fragment shaders a bit to make debugging easier. Declares a useful struct to hold texture parameters and also the explicit types avoid senseless OpBitCast that were emitted all over the place.
- Implement optional delayed discard. On …
=> rsx: Shader emitter fixups [ 3 of 3]

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp, rpcs3/Emu/Cell/lv2/sys_rsx.h, rpcs3/Emu/RSX/Capture/rsx_capture.cpp, rpcs3/Emu/RSX/Capture/rsx_replay.cpp, rpcs3/Emu/RSX/Common/TextureUtils.cpp, rpcs3/Emu/RSX/Common/texture_cache.h, rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp, rpcs3/Emu/RSX/RSXThread.cpp, rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
[testcase](https://github.com/elad335/myps3tests/blob/master/rsx_tests/Index%20array's%20indices%20alignment/mainrsxcrap.cpp#L282): it's testing two "unaligned" (one byte aligned) index array offests, one for u16 index type (0xc4900001) and the other for u32 index type (0xc4900003, both produce the same graphical output as aligned down versions. (more specifically offset 0xc4900000). rpcs3 master doesn't produce an image on both unaligned versions.
Also fixes HLE gcm regression after #6810 (pass context_id).
=> rsx: Align down index array offset

Utilities/StrFmt.cpp, rpcs3/Emu/Cell/lv2/sys_config.h, rpcs3/Emu/RSX/GSRender.h, rpcs3/evdev_joystick_handler.cpp
`std::move()` should be avoided when returning a stack object as it prevents [copy elision](https://en.cppreference.com/w/cpp/language/copy_elision).
The indent fix was pointed out by gcc 9 as potentially misleading.
=> Fix some indent mistake and unneeded std::move

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
- r1 is always float4 never half4. Its a full-width register unlike the
other outputs which are optionally half-width.
Fixes a problem where native fp16 support would break rendering in some titles because depth export was not working.
=> rsx: Copypasta fix

rpcs3/Emu/RSX/VK/VKHelpers.h
The current behaviour when going fullscreen from windowed was to keep
the previous size of the swapchain, with black borders on all sides,
which looks quite ugly.
The root of this issue is that rpcs3 only checks for frame resize if
`vkQueuePresent()` returns `VK_SUBOPTIMAL_KHR`, which anv doesn’t do on
Wayland currently, an issue has been opened against it, see
https://gitlab.freedesktop.org/mesa/mesa/issues/1979
It would make sense to stop checking for that altogether, because it
introduces a delay of one frame during which the previous swapchain will
be used, even though the `GSFrameBase` implementation already knows the
buffer size should have changed.
Another alternative solution would be to change the relation between the
`GSFrameBase` implementation and the `GSRender`, and make the …
=> Allow window resizing on Wayland, including fullscreen
