rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLFragmentProgram.h
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/GL/GLProgramBuffer.cpp
rpcs3/Emu/RSX/GL/GLProgramBuffer.h
rpcs3/Emu/RSX/RSXFragmentProgram.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h

No functional changes , only renaming.

RSX : inline fragment naming & structure as vertex shader one

---

.gitmodules
rpcs3/Emu/Audio/AL/OpenALThread.cpp
rpcs3/Emu/Audio/AL/OpenALThread.h
rpcs3/Emu/Audio/AudioManager.cpp
rpcs3/Emu/Audio/AudioManager.h
rpcs3/Emu/Audio/AudioThread.h
rpcs3/Emu/Audio/Null/NullAudioThread.h
rpcs3/Emu/Audio/XAudio2/XAudio2Thread.cpp
rpcs3/Emu/Audio/XAudio2/XAudio2Thread.h
rpcs3/Emu/SysCalls/Modules/cellAudio.cpp
rpcs3/Gui/MainFrame.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Added AudioThread interface.
Implemented simple XAudio2 audio output (used minidx9 sdk from hrydgard repository (thanks), needed for using XAudio2 2.7).

AudioThread improvements

---

rpcs3/CMakeLists.txt
rpcs3/Gui/AboutDialog.h
rpcs3/Gui/MainFrame.cpp
rpcs3/emucore.vcxproj
rpcs3/git-version.cmake
rpcs3/git-version.h
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters

Rpcs3 So now displays the git revision number, I also remove all win32 platform emucore that are useless now.

Fix Git version and Remove old Platform on emucore.vcxproj

---

rpcs3/Emu/Cell/PPUInterpreter.h

I forgot about C99 &lt;fenv.h&gt; earlier. With these changes, the PPU interpreter passes all tests from http://achurch.org/cell-test/ppu.s

Implement FPU rounding mode and exception checking in the PPU interpreter.

---

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp

Required by packSnorm2x16 , packSnorm4x8 etc

FP: switch to version 420

---

rpcs3/Loader/Loader.cpp

i->get_error_code() would have been changed in the if brace

small fix on loader::load(vfsStream& stream)

---

rpcs3/Emu/SysCalls/lv2/cellFs.cpp

no clue what I was thinking there

fix #elif with no condition

---

Utilities/StrFmt.h
Utilities/Thread.cpp
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/FS/VFS.h
rpcs3/Emu/IdManager.h
rpcs3/Emu/Memory/vm.h

This at least gets it working for me on Yosemite. Unfortunately, it crashes upon closing, and then the shm_open("/rpcs3_vm") call will fail until the next reboot or if you unlink it as root because the app failed to unlink it before crashing.

Fix building on OS X 10.10

---

rpcs3/CMakeLists.txt

The library is not needed on OSX and does not seem to exists there.
Wait for travis to build, haven't tested this. Regarding #994

Only link to librt on Linux

---

rpcs3/Emu/Cell/RawSPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/SysCalls/Modules/cellAudio.cpp
rpcs3/Emu/SysCalls/lv2/sys_event.cpp
rpcs3/Emu/SysCalls/lv2/sys_event.h
rpcs3/Emu/SysCalls/lv2/sys_event_flag.cpp
rpcs3/Emu/SysCalls/lv2/sys_event_flag.h
rpcs3/Emu/SysCalls/lv2/sys_spu.cpp
rpcs3/Emu/SysCalls/lv2/sys_spu.h

sys_spu_thread_group_connect_event implemented

Event Flag rewritten, bugfixes

---

rpcs3/CMakeLists.txt

Stop overwriting the ADDITIONAL_LIBS setting for CMake.

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/RSXThread.cpp

This fixes the fw_dice.ppu.elf

Fix vertex data

---

.travis.yml

use clang 3.6 for travis

---

rpcs3/Crypto/lz.cpp
rpcs3/Crypto/sha1.cpp
rpcs3/Emu/ARMv7/Modules/sceLibc.cpp
rpcs3/Emu/Cell/PPULLVMRecompiler.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/FS/vfsStreamMemory.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/SysCalls/Modules/cellAdec.cpp
rpcs3/Emu/SysCalls/Modules/cellCamera.h
rpcs3/Emu/SysCalls/Modules/cellDmux.cpp
rpcs3/Emu/SysCalls/Modules/cellSpurs.cpp
rpcs3/Emu/SysCalls/Modules/cellVdec.cpp
rpcs3/Emu/SysCalls/lv2/sys_spu.cpp
rpcs3/Gui/InterpreterDisAsm.cpp

Seen @raven02 's recent work, i tried CppCheck to find some defects. I tried to fix some severe problems and marked those i don't know how to deal. Below is what i looked with care, and those with (mark) are just marked but not dealt. Used rules (not exactly as what it reported):
* out-of-bound reference
* statements should return but without return
* missing breaks in cases (mark)
* assert with requested effect (mark)
* `std::remove_if` (mark)
* if (unsigned_var < 0) (mark)
* never executed else-if conditions due to same condition above (mark)
* some quite weird/strange line i can not understand, dealt.
* Object would be immediately destroyed (mark)
* remove same value aside the `||`
Even i've already built one for these commits succussfully, please review with care.
**Still trying to …

(Please review carefully first) CppCheck Patch Bundle for master branch

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/RSXThread.cpp

Hope this time can successfully merge with rsx branch

Fixed vertex data

---

Utilities/AutoPause.cpp
Utilities/File.cpp
rpcs3/Emu/ARMv7/ARMv7Thread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/RSX/CgBinaryFragmentProgram.cpp
rpcs3/Emu/RSX/CgBinaryVertexProgram.cpp
rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/SysCalls/Modules/cellFs.cpp
rpcs3/Emu/SysCalls/Modules/cellSaveData.cpp
rpcs3/Emu/SysCalls/Modules/cellSync.cpp
rpcs3/Emu/SysCalls/lv2/sys_cond.cpp
rpcs3/Emu/SysCalls/lv2/sys_fs.h
rpcs3/Emu/SysCalls/lv2/sys_lwcond.cpp
rpcs3/Loader/ELF64.cpp

1) Excessive use of vm::cast moderated (could fix #1072)
2) std::bind replaced with lambdas (related with VS 2015 RC compilation)
3) ConvertWCharToUTF8() bug fixed

Some fixes

---

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/RSXThread.cpp

This fixes the Disgaea 3 with invalid glfrontface and rsx_fp_static_test5.ppu.elf

Minor fixes

---

rpcs3/Emu/RSX/GL/GLVertexProgram.cpp

Fixed SEQ/SGT/STR/SSG instructions

---

rpcs3/Emu/RSX/GL/GLVertexProgram.cpp

GL: Fix output swizzling for fog and clip distance

---

rpcs3/Emu/RSX/RSXThread.cpp

It fixes alpha_kill.ppu.elf test and improve the vertex_attribute ones (but not completly fixed)

RSX: Fix index gathering

---

rpcs3/Gui/MainFrame.cpp

Fix size Windows setting for this news paramater https://github.com/RPCS3/rpcs3/commit/1c0c4cc252e61c60de8c1f8f40434db187af6ebf

Fix windows size

---

rpcs3/Emu/Cell/PPULLVMRecompilerTests.cpp

Hides unneeded info for passed tests. Adds diff for failed tests (easier to see what is wrong).
6 KB log file -> ~800 KB.
Example output: http://paste2.org/9gCvkW9O
Tests are disabled by default.

Make ppuJIT test log more compact and easier to read

---

GL/glext.h
rpcs3/Gui/GameViewer.h

Update glext.h on version 31191
Fix correct size icon with correct proportion

Update glext.h on version 31191

---

rpcs3/Gui/RSXDebugger.cpp

Disasm more commands and increase size of debugger window.

Rsx: Improve debugger

---

rpcs3/Emu/SysCalls/Modules/cellGcmSys.cpp

This commit fixes dynamic tests from rpcs3 autotest repo. It doesn't break Arkedo 2, Voodoo Chronicles, Sonic CD, the guided fate paradox, puzzle quest ; it doesn't fix them either, although flickering is a lot less present in Voodoo Chronicles and puzzle quest loading screen.
Unfortunatly it looks like there is more PPU Thread failure when dealing with syscall and I have no idea why. Not sure if it's a bug of the commit or if it uncovered one.

SysGCM: Split default command buffer into 32kb big fragments and swap between them

---

rpcs3/rpcs3.vcxproj

Given that there are only the x64, it is needless to say now. Thx @vlj for Help :)

Remove -x64 on exe because now it is useless

---

rpcs3/emucore.vcxproj

Remove win32 Debug - MemLeak

---

.gitmodules

Update Submpodule asmjit

---

Utilities/Thread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/Null/NullGSRender.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h

This updates doesn't add or fix anything (except a virtual protect issue), it just move some functionnalities to GSRender backend to make them customisable. Such customisation are used by upcoming D3D12 backend.

Rsx: Some interface changes

---

rpcs3/Emu/SysCalls/ModuleManager.cpp
rpcs3/Emu/SysCalls/Modules/cellFont.cpp
rpcs3/Emu/SysCalls/Modules/cellNetCtl.cpp
rpcs3/Emu/SysCalls/Modules/cellRudp.cpp
rpcs3/Emu/SysCalls/Modules/cellRudp.h
rpcs3/Emu/SysCalls/Modules/cellSail.cpp
rpcs3/Emu/SysCalls/Modules/cellSail.h
rpcs3/Emu/SysCalls/Modules/cellSaveData.cpp
rpcs3/Emu/SysCalls/Modules/sceNpTrophy.cpp
rpcs3/Emu/SysCalls/Modules/sys_net.cpp
rpcs3/Emu/SysCalls/Modules/sys_net.h
rpcs3/Gui/MainFrame.cpp
rpcs3/Ini.h
rpcs3/Loader/TRP.cpp

:apple: 
In options I merged the camera and the input/output tab.
Added networking tab with the options to choose the connection state and the network adapter to be used for, well.... networking.
There's also a rough draft of socketselect function, which doesn't work properly, but I couldn't figure out why it wasn't working, so if somebody knows what's wrong, they're welcome to help fix that.
Savedata received a couple more fixes and should now work as intended - huge thanks for that @Nekotekina. I also made a couple improvements to cellRudp, besides it now being actually loaded.
As for games, Terraria trial version goes to main menu and Shin Hayarigami seems to progress further.
:apple:

cellNetCtlGetInfo, sys_net, cellRudp and minor options dialog improvements

---

rpcs3/Gui/MainFrame.cpp
rpcs3/Loader/PKG.cpp

This is my first PR on github, hope everything's all right :)

Install PKGs into custom folder

---

rpcs3/rpcs3.vcxproj.user

(Some modules like llvm can repport errors to stderr).

Log stdout and stderr on windows

---

README.md
appveyor.yml

Could be merged. I'll try to speed it up in a separate branch.

Add appveyor.yml

---

rpcs3/Emu/Cell/PPULLVMRecompiler.cpp
rpcs3/Emu/Cell/PPULLVMRecompiler.h

Should fix remaining crash with llvm in sonic cd.

PPU/LLVM: Fix recursive call crashing llvm backend

---

rpcs3/Emu/SysCalls/Modules/cellGame.cpp

Replaced a sprintf with fmt::format.

Replace sprintf with fmt::format

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.h
rpcs3/Emu/Cell/SPUAnalyser.cpp
rpcs3/Emu/Cell/SPUAnalyser.h
rpcs3/Emu/Cell/SPUInterpreter.cpp
rpcs3/Emu/Cell/SPUOpcodes.h
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h

SPU Recompiler fixed

---

.gitmodules

main changes from #1220 
make sure to do the "git sync" thing if you have trouble updating the changed ffmpeg submodule

Update submodule ffmpeg and wxWidgets.

---

rpcs3/Emu/RSX/D3D12/D3D12.h
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
rpcs3/Emu/RSX/D3D12/D3D12Overlay.cpp
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
rpcs3/Emu/RSX/D3D12/D3D12Utils.cpp
rpcs3/Emu/RSX/D3D12/d3dx12.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

This PR adds official  d3dx12.h file from MS github repo and makes use of it.
It also adds some tweaks to backend dtor and buffer management that increases reliability and performance.

D3d12: Code cleaning and minor fixes

---

rpcs3/Gui/D3DGSFrame.cpp
rpcs3/Gui/GLGSFrame.cpp
rpcs3/Gui/MainFrame.cpp
rpcs3/Gui/SettingsDialog.h

Adding the icon on window GL and DX12

---

README.md
Utilities/git-version-gen.cmd
rpcs3/Gui/AboutDialog.h
rpcs3/Gui/MainFrame.cpp
rpcs3/stdafx.h

Fix double version in Gui
Update to version 0.0.6
Adding a developer.
Add version for Python.

Adding Git in README and some little change

---

Utilities/config_context.h
rpcs3/CMakeLists.txt

Fix clang compiling

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/GL/gl_helpers.h
rpcs3/Emu/RSX/RSXThread.cpp

rsx::thread: disable all vertex data at end command
Fixed OpenGL program attributes cache flush

rsx thread & OpenGL renderer fixes

---

Utilities/File.cpp
Utilities/File.h
rpcs3/Emu/RSX/Common/ProgramStateCache.h
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/GL/gl_helpers.h
rpcs3/Emu/RSX/RSXThread.cpp

Flush program cache at thread exit
Use cached locations

OpenGL renderer improvements

---

.travis.yml

Coverity should be hopefully fixed. Also quite a bit of progress on moving to container builds. Only hurdle now is https://github.com/travis-ci/apt-package-whitelist/issues/417. Builds with the removal of most sudo commands have received a somewhat noticeable speedup - ~30seconds.

Try to really fix Coverity and progress on moving to container builds

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/Common/BufferUtils.h
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
rpcs3/Emu/RSX/D3D12/D3D12PipelineState.h
rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.h
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h

This PR fixes shader miscompilation with Machinarium. It should also fix Disgaea 3 crash.
There are also some speed improvements by reducing API calls and avoiding copies.

D3d12: Fixes and speed improvements.

---

rpcs3/Gui/GSFrame.cpp

Fix window Full Screen With Double Left Click on DX12, same before, and same OpenGL.
PR Originel https://github.com/RPCS3/rpcs3/pull/1242

Fix Full screen in DX12

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp
rpcs3/Emu/RSX/D3D12/D3D12Formats.h
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12MemoryHelpers.cpp
rpcs3/Emu/RSX/D3D12/D3D12MemoryHelpers.h
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h

This PR fixes some defects found by investigating SH3. Game shouldn't lack geometry.
The alpha test sample background is also correctly displayed and some Braid glitches (cloud overlapping geometry) are fixed.

D3d12: Fixes

---

rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/SysCalls/Modules/cellResc.cpp

This PR fixes some defect of RSX/cellResc found while investigating SH3.
It fixes character rendering and flickering screen. I suspect more games can be impacted too.

Rsx: Fixes

---

rpcs3/Emu/RSX/Common/ProgramStateCache.h
rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp
rpcs3/Emu/RSX/D3D12/D3D12PipelineState.h
rpcs3/Emu/RSX/GCM.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Gui/RSXDebugger.cpp
rpcs3/Gui/RSXDebugger.h

This PR adds transform and shader programs associated to a draw call. It also dump the frame commands to command_dump.log.
It was used to find what were wrong with SH3 character models.

Rsx debug: Add some features

---

rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp
rpcs3/Emu/RSX/D3D12/D3D12Formats.h
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
rpcs3/Emu/RSX/D3D12/D3D12MemoryHelpers.h
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h

Another round of fixes for Jet Set Radio, Castle of Illusion Staring Mickey Mouse, and depth read samples.

D3d12: some fixes

---

rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp

rsx: Avoid mixing float4 and int4 in declaration of AddrReg.

---

.mention-bot
rpcs3/Emu/SysCalls/Modules/cellGcmSys.cpp

Fixes the main menu colours in Terraria - Trial, but character creation menu's colours on the character's display worsened.
Also adds AlexAltea to mention-bot blacklist.

GCM and minor DX12 fixes

---

rpcs3/Gui/GameViewer.cpp

Fixes #1326
Also fix crash introduced by https://github.com/RPCS3/rpcs3/commit/3465106456283b2f460842ec8526de3514bd4df6
though I don't know why it was working fine before.

Fix removing game from game list

---

rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp

Fix issue https://github.com/RPCS3/rpcs3/issues/1340

Fix for Shovel Knight

---

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp

rsx/common: Support RSX_FP_OPCODE_DIV for scb

---

rpcs3/Emu/SysCalls/Modules/cellL10n.cpp

Needed for Tales of Vesperia.
I tried to avoid breaking the Windows code, but I don't have a Windows environment to build in, so someone will need to check that that code still works.

cellL10n: Implement SJIS<->Unicode conversions.

---

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h

It's required for Bleach Resurection Soul.

rsx/common/d3d12/gl: Implement draw inline array support

---

Utilities/File.cpp

* Simplify create_path
* More sane permissions
* Create entire path of configuration directory
Moved this over from https://github.com/RPCS3/common/pull/1
Is the common submodule gone for good?

Fix configuration path creation.

---

rpcs3/Emu/Cell/PPUInterpreter.h
rpcs3/Emu/SysCalls/Modules/cellGame.cpp
rpcs3/Emu/SysCalls/Modules/cellNetCtl.cpp
rpcs3/Emu/SysCalls/Modules/cellResc.cpp
rpcs3/Emu/SysCalls/Modules/cellSysmodule.cpp
rpcs3/Emu/SysCalls/Modules/sys_net.cpp
rpcs3/config.h

The relocations, imports and exports no longer spam the log as much, with default settings. I felt it was unnecessary for usual logs and only made them bigger.
Also fixed AlexAltea not being properly ignored.

Logging fixes, minor HLE improvements

---

rpcs3/Emu/RSX/CgBinaryProgram.h
rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.h
rpcs3/Emu/RSX/Common/ProgramStateCache.cpp
rpcs3/Emu/RSX/Common/ProgramStateCache.h
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.h
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp
rpcs3/Emu/RSX/D3D12/D3D12PipelineState.h
rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.h
rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLFragmentProgram.h
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLProgramBuffer.h
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.h
rpcs3/Emu/RSX/GL/gl_helpers.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Use a_b_c format.
Use using =
Use tuple as output
Use RAII to delete program safely
Ensure const correctness.
Use span<>

rsx/common/d3d12/gl: Clean ProgramStateCache

---

Utilities/GNU.h
asmjitsrc/asmjit.vcxproj
rpcs3/Crypto/unedat.cpp
rpcs3/Crypto/unself.cpp
rpcs3/Emu/ARMv7/Modules/sceFios.h
rpcs3/Emu/ARMv7/Modules/sceLibKernel.cpp
rpcs3/Emu/ARMv7/PSVFuncList.h
rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/Emu/Cell/PPULLVMRecompilerCore.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Memory/vm_ptr.h
rpcs3/Emu/Memory/vm_var.h
rpcs3/Emu/RSX/CgBinaryProgram.h
rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
rpcs3/Emu/SysCalls/Modules/cellAdec.cpp
rpcs3/Emu/SysCalls/Modules/cellAudio.cpp
rpcs3/Emu/SysCalls/Modules/cellDmux.cpp
rpcs3/Emu/SysCalls/Modules/cellGifDec.cpp
rpcs3/Emu/SysCalls/Modules/cellSpurs.cpp
rpcs3/Emu/SysCalls/Modules/cellSpursSpu.cpp
rpcs3/Emu/SysCalls/Modules/cellVdec.cpp
rpcs3/Emu/SysCalls/Modules/sceNp.cpp
rpcs3/Emu/System.cpp
rpcs3/Gui/ConLogFrame.cpp
rpcs3/Loader/ELF64.cpp
rpcs3/Loader/TROPUSR.cpp
rpcs3/stdafx.h
rpcs3_default.props

/dev_bdvd/, rap file loading fix

Fixes (#1432)

---

Utilities/Thread.cpp
rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/Common/BufferUtils.h
rpcs3/Emu/RSX/Common/surface_store.cpp
rpcs3/Emu/RSX/Common/surface_store.h
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp
rpcs3/Emu/RSX/D3D12/D3D12Formats.h
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.h
rpcs3/Emu/RSX/D3D12/D3D12Overlay.cpp
rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.h
rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
rpcs3/Emu/RSX/D3D12/D3D12Utils.cpp
rpcs3/Emu/RSX/GCM.cpp
rpcs3/Emu/RSX/GCM.h
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/gl_helpers.cpp
rpcs3/Emu/RSX/GL/gl_helpers.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/Emu/SysCalls/Modules/cellResc.cpp
rpcs3/Gui/RSXDebugger.cpp

RSX vertex/OpenGL texture cache preparation

---

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp

According to investigation on Resogun.

rsx/common: Div is vector over scalar division

---

rpcs3/Emu/RSX/Common/ProgramStateCache.cpp
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/GCM.cpp
rpcs3/Emu/RSX/GCM.h
rpcs3/Emu/RSX/RSXFragmentProgram.h
rpcs3/Emu/RSX/RSXThread.cpp

Fix After burner climax cloud effects.

rsx/common/d3d12: Support non default alpha function

---

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp

Properly handle inlined vertex data. This should fix missing geometry in alot of games.

Properly handle inlined vertex data

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/Common/BufferUtils.h
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/emucore.vcxproj

I tested with GL and DX12 and it has apparently no regression.
The new function adds some safety over the previous one by checking bounds.

rsx/common/d3d12/gl: Use span in vertex upload function.

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp

AMD drivers are strict on enforcing shader input binds when validating program state. Always binding inputs for declared shader inputs even when the game is not using them at the time should fix shaders failing to validate.
Also renames attribute offsets to improve redability.

gl: Always bind null for unused shader inputs

---

Utilities/Thread.cpp
rpcs3/Emu/SysCalls/Modules/cellL10n.cpp
rpcs3/Emu/SysCalls/Modules/cellPngDec.cpp
rpcs3/Emu/SysCalls/Modules/sys_libc.cpp

~~cellHddGameCheck function definitely doesn't set getParam values.~~
Also implemented _sys_memmove for Resogun.

Implement _sys_memmove, minor fixes

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp

Don't normalize in software natively normalized data formats. Also, changes the native format for decoded compressed format from float to integer format and the explicitly unnormalized format ub256.

gl: Minor fixes and improvements

---

rpcs3/Emu/RSX/Common/BufferUtils.cpp
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/GCM.cpp
rpcs3/Emu/RSX/GCM.h
rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/RSXFragmentProgram.h
rpcs3/Emu/RSX/RSXThread.cpp

This PR adds support for quad strip and fog mode/parameters.
It makes Hitman 2 at least half playable. It's maybe even playable since it seems to work nicely.

Rsx: Fix for hitman 2

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp

Since https://github.com/RPCS3/rpcs3/pull/1510 was merged, I noticed some regressions due to lack of padding for 3-component attributes. DX12 is not affected due to the remapping of components, but GL and vulkan are affected. This adds a pre-filling step that allows the backend to prepare the destination buffer before it is filled by BufferUtils.

gl: Allow attrib padding for types that require expansion

---

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp

Should fix incorrect shader generation. Also, lighting is correct with OpenGL with this fix. Only glitch is that some characters heads are missing some geometry on the backs of their heads (bad culling?)

gl: Properly set up fog parameters for openGL

---

rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp

Mipmap generation was being done wrong. GL_GENERATE_MIPMAP is part of the texture object state that causes mipmaps to be generated after level 0 is updated. However, it was being set after the texture had been uploaded causing no mipmaps to be created. It has however been superseded by glGenerateMipmap that causes immediate mipmap generation and the GL_GENERATE_MIPMAP flag is part of the deprecated 1.4 spec.
Should fix black textures in alot of games especially on nvidia. Also, checks if a texture is mipmap-accessible when setting the minification filter.

gl: Checks for texture completeness, remove legacy GL_GENERATE_MIPMAP

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/1544

gl: Clean up invalidated resources to fix mem leak

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTexture.cpp

This fixes a crash with nvidia driver in present call (likely because of
some uninitialized member)

vulkan: Zero initialize as much structure info as possible.

---

rpcs3/Emu/RSX/GL/gl_texture_cache.h
rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp

Add min and max blend ops that were missing (Steins Gate)

vk/gl: Add some more blend ops for vulkan; fix immutable storage for opengl

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp

This PR fix both issues in #1590

Vulkan: Fixes

---

rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
rpcs3/Emu/RSX/GL/gl_texture_cache.h
rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp
rpcs3/Emu/RSX/RSXTexture.cpp
rpcs3/Emu/RSX/RSXTexture.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTexture.cpp
rpcs3/Emu/RSX/VK/VKTextureCache.h

Fix invalid textures in gl backend.

rsx/common/gl/d3d12/vulkan: Use exact mipmap counts.

---

README.md

Solves building on Ubuntu (tested on 15.10)
Before:
After:

Adds missing lib (libedit-dev) - Solves #1570

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.h
rpcs3/Emu/RSX/VK/VKHelpers.h

This is PR #1620 reworked, hope this time it'll work better.

Vulkan: Avoid extra sync

---

.gitmodules

I'm submitting this to avoid problems with fixing conflicts in `.gitmodules`. For some reason, it becomes problematic. Also removed unnecessary files in forks.

Added yaml-cpp and pugixml submodules

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.h
rpcs3/Emu/RSX/VK/VKHelpers.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTexture.cpp
rpcs3/Emu/RSX/VK/VKTextureCache.h
rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
rpcs3/VKGSRender.vcxproj

Various fixes for Vulkan, some spotted using debug layer.

Vulkan: Some fixes

---

rpcs3/Emu/RSX/GL/GLCommonDecompiler.cpp
rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/gl_render_targets.cpp
rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp

This PR fixes cubemap uploading and some format used in After Burner Climax.

Gl: Fix for cubemap and R5G6B5 rtt format.

---

rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/1651

vulkan: Properly handle ssa variable as local

---

.travis.yml
Utilities/rXml.cpp
Utilities/rXml.h
appveyor.yml
rpcs3/CMakeLists.txt
rpcs3_default.props

`git reset --hard upstream/master` automatically closed the previous PR. At least now its clean.

Replace wx/xml with pugixml in rXML

---

Utilities/rXml.cpp
Utilities/rXml.h

Not sure if it works completely now but at least it doesn't crash in
Metal Slug 3 now.
It occurred when there was already a trophy data for the game.

rXml: fix broken things

---

Utilities/GSL.h
Utilities/types.h
rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp
rpcs3/Emu/Cell/Modules/cellSysmodule.cpp
rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/RSX/Common/BufferUtils.h
rpcs3/Emu/RSX/Common/ProgramStateCache.h
rpcs3/Emu/RSX/Common/TextureUtils.h
rpcs3/Emu/RSX/Common/surface_store.h
rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/rsx_utils.h
rpcs3/GLGSRender.vcxproj
rpcs3/Gui/RSXDebugger.cpp
rpcs3/Loader/PSF.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/stdafx.h

Added GSL.h helper for correct including

GSL moved from stdafx.h

---

rpcs3/Gui/GameViewer.cpp

Re: #1697 
I've added a dialog that appears as attached when selecting "Remove Game" from the right-click context menu.

Added confirm to delete

---

rpcs3/Gui/GSFrame.cpp
rpcs3/Gui/GSFrame.h
rpcs3/Gui/SettingsDialog.cpp

Display render on title frame

---

rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/gl_render_targets.cpp
rpcs3/Emu/RSX/VK/VKFormats.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTextureCache.h
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp

Blade Arcus from Shining EX issues a clear command before selecting a surface target at the very begining of the game. https://github.com/RPCS3/rpcs3/issues/1681

dx12/gl/vk: Rendering fixes; surface format enhancements and bugfixes for vulkan

---

rpcs3/Emu/RSX/GL/rsx_gl_texture.cpp

Thanks @danilaml  and @kd-11  to bring this out.

Texture bias minor fix

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.h

Second attempt at window resizing. I've cleaned up the flip code a bit as well and added proper synchronization that will hopefully allow nvidia users to resize without crashing.

vk: Properly enable window resizing

---

rpcs3/Emu/RSX/VK/VKHelpers.cpp

AMD has a special heap type that is not present on NV. It's a small 256M section that is device_local, coherent and host_visible. The current algorithm settles on this partition for device local since we dont check the size of the heap before deciding it is the better one. This pull request ignores this partition for device local invisible storage (used primarily for textures) since we can easily exceed allocation here and run into performance issues.
The new system prefers larger device local vram blocks since we cannot access it from the host, and prefers the cached visible vram for general purpose uploads. It should work fine with future hardware from any vendor.
A similar problem with the steam client overlay has recently been fixed, improving AMD performance on commercial vulkan …

vk: Better VRAM heap selection by memory properties (AMD)

---

rpcs3/Emu/IdManager.cpp
rpcs3/Emu/IdManager.h

Debug build fixed
Allowed get/remove with forward declarations

IdManager fix

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp

Should help #1466.
It's not a complete fix, it also makes file operations slower.

cellFsRead workaround

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/PPUTranslator.h

PPU LLVM: Some instructions simplified

---

rpcs3/Emu/RSX/VK/VKFormats.cpp
rpcs3/Emu/RSX/VK/VKFormats.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h

Thanks @kd-11 . Both Outrun Arcade and DBZ Burst limit look good .

vk: push back border color to sampler

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp

Align with DX12 front face handling for Vulkan and GL backend

Vulkan/GL: add default case for front face in case of garbage value

---

Utilities/Thread.cpp
rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/PPUTranslator.h
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/Cell/lv2/sys_prx.h
rpcs3/Emu/System.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Improved compatibility, compilation speed.

PPU: New analyser

---

rpcs3/Emu/RSX/rsx_methods.cpp

fix regression https://github.com/RPCS3/rpcs3/pull/1853

RSX: check vertex_draw_count

---

rpcs3/Emu/RSX/rsx_methods.cpp

fix https://github.com/RPCS3/rpcs3/issues/1860

RSX: throw exception removal for user_command()

---

rpcs3/Emu/RSX/rsx_methods.cpp

Proper fix for https://github.com/RPCS3/rpcs3/issues/1853

rsx: properly check for inlined array before discarding draw

---

Utilities/File.cpp
Utilities/File.h
rpcs3/Emu/System.cpp

This reimplements #1880 partially.
@GhettoGirl I just discovered some problems so it was faster to fix them immediately...

fs::get_data_dir implemented

---

rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp

Removed interpreter dependencies
Reciprocal instructions improved

PPU LLVM improvements

---

appveyor.yml

Should fix #1896 according to @raven02

Vulkan: glslang workaround

---

rpcs3/Emu/Cell/PPUAnalyser.cpp
rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUDisAsm.h
rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUOpcodes.h
rpcs3/Emu/Cell/PPUTranslator.cpp

PPU LLVM: Analyser fix

---

rpcs3/Emu/Cell/PPUAnalyser.cpp

PPU Analyser improved

---

rpcs3/Emu/RSX/rsx_methods.cpp

https://github.com/RPCS3/rpcs3/issues/1901

rsx: typo fix

---

README.md

Update donation link

---

rpcs3/Emu/RSX/rsx_methods.cpp

Fixes crash in Ar Tonelico and other games.

NV0039_OFFSET_IN fix

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp

vk: Fix vertex winding

---

rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp

Inline stencil test as GL and Vulkan backend

D3D12: inline stencil test as GL and Vulkan backend

---

rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp

RSX exception fix

---

Utilities/File.cpp
Utilities/File.h
Utilities/Log.cpp
Utilities/Log.h
Utilities/version.cpp
Utilities/version.h
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Gui/AboutDialog.h
rpcs3/Gui/ConLogFrame.cpp
rpcs3/Gui/ConLogFrame.h
rpcs3/Gui/MainFrame.cpp
rpcs3/rpcs3.cpp
rpcs3/rpcs3_version.cpp
rpcs3/stdafx.h

logs::listener resurrected
rpcs3 version: constexpr

GUI logging improved

---

rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/Modules/cellVdec.h

cellVdec improved (requires LLE dmux)

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTextureCache.h
rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp

While investigating the NV vulkan crashes, I realized we were violating spec in several ways. Some of these have been there since the beginning and others have crept in during refactoring efforts.

vk: Conform to current spec

---

rpcs3/Emu/Cell/Modules/cellSysmodule.cpp

fix https://github.com/RPCS3/rpcs3/issues/1971

PPU: register undocumented functions in cellSysmodule

---

rpcs3/Emu/Audio/XAudio2/XAudio27Thread.cpp
rpcs3/Emu/Audio/XAudio2/XAudio28Thread.cpp

Neko want to have better/correct implementation. I temporary revert it.

Revert "Audio : allow XAudio2 to run its own thread"

---

Utilities/JIT.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/PPUTranslator.h

Global variables modified:
__mptr: pointer to memory base addr
__cptr: pointer to function map addr
Use 32 bit pointers in function map

LLVM: Use small code model

---

rpcs3/Emu/RSX/GL/gl_helpers.h
rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp

file: ensure the parent directory exists if the open mode contains the 'create' or 'write' flag

---

rpcs3/Emu/Audio/XAudio2/XAudio27Thread.cpp
rpcs3/Emu/Audio/XAudio2/XAudio28Thread.cpp
rpcs3/Emu/Audio/XAudio2/XAudio2Thread.cpp
rpcs3/Emu/Audio/XAudio2/XAudio2Thread.h

XAudio2 version priority

---

rpcs3/Emu/Cell/lv2/sys_timer.cpp

Regression fix #1995

---

rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp

vk: front_diff_color typo fix

---

rpcs3/Emu/RSX/GL/rsx_gl_cache.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKTextureCache.h

As was reported here https://github.com/RPCS3/rpcs3/issues/1679 some games can have enabled textures with bogus dimensions. Gracefully handle such cases instead of crashing the driver.
Also fixes depth writes for opengl.  https://github.com/RPCS3/rpcs3/issues/1989

vk/gl: bug fixes

---

rpcs3/Emu/RSX/Common/TextureUtils.cpp

fix https://github.com/RPCS3/rpcs3/issues/1628

Ignore texture upload if texture width > pitch

---

rpcs3/Emu/Cell/Modules/cellSysutil.cpp

cellSysutilCheckCallback fix

---

rpcs3/Emu/RSX/GL/vertex_buffer.cpp

It is typo fix https://github.com/RPCS3/rpcs3/issues/2029

Regression fix #2029

---

rpcs3/Emu/RSX/VK/VKTextureCache.h

Should fix most crashes during queuePresentKHR
Fixes issues mentioned here https://github.com/RPCS3/rpcs3/issues/1942 and https://github.com/RPCS3/rpcs3/issues/1679
The texture cache was initially made to work with the original vulkan implementation which submitted work after every draw call. With that system, immediately destroying old textures was not an issue, but we now buffer all the work in a queue and submit at once, requiring that all object creation/destruction is buffered/delayed as well.

vk: delay texture removal when cache is clobbered

---

rpcs3/Emu/Cell/Modules/cellFont.cpp
rpcs3/Emu/Cell/Modules/cellFs.cpp
rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/Cell/Modules/cellOvis.cpp
rpcs3/Emu/Cell/Modules/cellRtc.cpp
rpcs3/Emu/Cell/Modules/cellSail.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/Modules/sys_heap.cpp
rpcs3/Emu/Cell/Modules/sys_libc_.cpp
rpcs3/Emu/Cell/Modules/sys_net.cpp
rpcs3/Emu/Cell/Modules/sys_ppu_thread_.cpp
rpcs3/Emu/Cell/Modules/sys_spu_.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_ptr.h
rpcs3/Emu/PSP2/Modules/sceLibKernel.cpp
rpcs3/Emu/PSP2/Modules/sceLibc.cpp

Also fixed game directory deletion

String fantasia for vm::ptr

---

rpcs3/Emu/Audio/XAudio2/XAudio28Thread.cpp

XAudio2.8+ fix

---

rpcs3/Emu/Cell/PPUThread.h

fix https://github.com/RPCS3/rpcs3/issues/2067

Workaround id_min/max

---

rpcs3/Emu/RSX/Common/ProgramStateCache.h
rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.h
rpcs3/Emu/RSX/VK/VKProgramBuffer.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTextureCache.h
rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp

1. https://github.com/RPCS3/rpcs3/issues/2085
2. https://github.com/RPCS3/rpcs3/issues/1935
3. Addendum to https://github.com/RPCS3/rpcs3/pull/2083

vk/rsx: Bug fixes

---

rpcs3/Emu/RSX/GL/gl_texture_cache.h

fix https://github.com/RPCS3/rpcs3/issues/2096

GL: ignore texture upload if invalid dimension found

---

rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp

fix https://github.com/RPCS3/rpcs3/issues/2102

GL: minor fixes

---

.clang-format
git-clang-format
pre-commit.readme
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/GL/gl_render_targets.cpp
rpcs3/Emu/RSX/GL/vertex_buffer.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/Emu/RSX/rsx_methods.h
rpcs3/Emu/RSX/rsx_vertex_data.h
rpcs3/Gui/SettingsDialog.cpp

This PR removes some obsolete code left by previous refactoring effort.

Rsx refactor: Some cleanups

---

rpcs3/Emu/RSX/gcm_enums.cpp
rpcs3/Emu/RSX/gcm_enums.h

workaround https://github.com/RPCS3/rpcs3/issues/2116

RSX: fix unknown vertex base type

---

rpcs3/Emu/RSX/gcm_enums.cpp
rpcs3/Emu/RSX/gcm_enums.h

Revert "RSX: fix unknown vertex base type"

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp

fix https://github.com/RPCS3/rpcs3/issues/2095

Vulkan: enable cull face again

---

rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12MemoryHelpers.cpp
rpcs3/Emu/RSX/rsx_vertex_data.h

This PR fixes #1878 and a potential race condition in texture invalidation.

Dx12 fixes

---

rpcs3/Emu/RSX/Common/TextureUtils.cpp
rpcs3/Emu/RSX/Common/TextureUtils.h
rpcs3/Emu/RSX/D3D12/D3D12Texture.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLTexture.cpp
rpcs3/Emu/RSX/GL/GLTexture.h
rpcs3/Emu/RSX/RSXTexture.cpp
rpcs3/Emu/RSX/RSXTexture.h
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKTexture.cpp
rpcs3/Emu/RSX/VK/VKTextureCache.h
rpcs3/Emu/RSX/rsx_methods.h

Separate texture from fragment and vertex .

RSX texture refactor

---

appveyor.yml

Hopefully fix appveyor build

---

rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp

DX12: enable alpha kill

---

rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp

https://github.com/RPCS3/rpcs3/issues/2129

vk: Sync subpass output [WIP]

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellVideoOut.cpp

Basically this allows SARPBC to startup (see discussion [here](http://www.emunewz.net/forum/showthread.php?tid=176091)) Also it seems to fix this [issue](https://github.com/RPCS3/rpcs3/issues/2220)

Allow UE3 games to startup

---

rpcs3/Crypto/unpkg.cpp

This PR fixes "debug" package decryption.
This fixes homebrew package installation.

PKG Installer fix

---

rpcs3/Emu/Cell/Modules/cellMsgDialog.h
rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
rpcs3/Emu/Cell/Modules/cellOskDialog.h
rpcs3/Gui/MsgDialog.h
rpcs3/Gui/OskDialog.cpp

Tested with different languages like Chinese, Japanese, Russian, and special characters like éàüåäö. Also tested cases like entering too long strings, or none at all. Finally it implements some more functionality like canceling input (just close the OSK GUI).

Add OSK GUI

---

.gitmodules

Fix corect number branch release llvm

---

rpcs3/Crypto/unself.cpp
rpcs3/Crypto/unself.h
rpcs3/Crypto/utils.cpp

Removes all trace of malloc from the crypto files.

Un-malloc Crypto

---

rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Register missing function in cellSysutil and sysPrxForUser.
Add forget osk file in emucore.
I have only add function with correct name available.

Register missing cellSysutil and sysPrxForUser function.

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

Registers missing functions exported from sceNp on firmware 4.76

sceNp: Register missing functions

---

Utilities/types.h
rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/D3D12/D3D12RenderTargetSets.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp

Seemed like some rather low-hanging fruit to me. :)
Closes #2200.

Switch to always using a steady clock

---

rpcs3/Emu/RSX/gcm_enums.cpp
rpcs3/Emu/RSX/gcm_enums.h
rpcs3/Emu/RSX/rsx_methods.cpp

Fix Issue https://github.com/RPCS3/rpcs3/issues/2243 Thx @kd-11 for help

rsx: Fix error context dma #2243

---

Utilities/StrFmt.cpp
Utilities/Thread.cpp
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/Cell/lv2/sys_ppu_thread.h
rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
rpcs3/Emu/Cell/lv2/sys_semaphore.h
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Gui/KernelExplorer.cpp

Need to finally remove damned LV2_LOCK

Refactoring

---

rpcs3/Gui/AboutDialog.h

Add Patreon link on about dialog
Change PS3 to A PlayStation 3
Change Ok to Close for close Window About RPCS3
Preview this change

Add Patreon link on about dialog

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

proper error code when file not found . This should fix issue #1923

---

rpcs3/Emu/Cell/Modules/cellVideoOut.cpp

[O1L] cellVideoOut: X8B8G8R8 fix

---

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
rpcs3/Emu/RSX/GCM.h
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLHelpers.cpp
rpcs3/Emu/RSX/GL/GLHelpers.h
rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
rpcs3/Emu/RSX/rsx_methods.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/2260. GTA San Andreas (BLUS31584) goes ingame (with OpenGL renderer).

RSX: minor fixes

---

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/RSX/D3D12/D3D12Formats.cpp

Notes:
Needs proper implementation (!)
The functions shows similarities but the bits in argument "type" may vary a little.
Comparing both functions but testing in NPJA00014 I believe it could be acceptable until it be implemented properly
Feel free to reject if it´s not allowed

cellMsgDialogOpen: Go further using cellMsgDialogOpen2.

---

rpcs3/MMJoystickHandler.cpp
rpcs3/MMJoystickHandler.h
rpcs3/rpcs3.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters

Tested on a few joysticks it should be ok. To work you must select MMJoystick on pad selection in settings
#2266

Joystick support using mmsystem library on windows

---

Utilities/File.cpp
Utilities/File.h
rpcs3/Crypto/unself.cpp
rpcs3/Crypto/unself.h
rpcs3/Emu/Cell/Modules/sys_spu_.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/System.cpp
rpcs3/Gui/MainFrame.cpp
rpcs3/Gui/SettingsDialog.cpp

Unfortunately, I found some problems after reviewing #2286.
Also I implemented container_stream according to my ideas.
This way it would be faster.

File fixes

---

rpcs3/Crypto/unself.cpp

Nekotekina's fix for preventing loading nonexistent libs

Nekotekina: Fix loading nonexistent libs

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellGame.h

This should fix the looping on that function . at least BCES-0001 seems to go much further now (has different issues)

Implemented cellDiscGameGetBootDiscInfo

---

rpcs3/Gui/GameViewer.cpp
rpcs3/Gui/GameViewer.h

The popup menu can be reused more than once.  No need to delete everything and recreate the contents every time.  Also, deleting stuff from the same list in a for each loop is generally a bad idea. ;)

Simplify the popup menu code

---

rpcs3/Emu/RSX/RSXThread.cpp

Rough implementation of GCM_CONTEXT_DMA methods.
Fixes #1487

Rough implementation of GCM_CONTEXT_DMA methods

---

rpcs3/Gui/GameViewer.cpp
rpcs3/Gui/SettingsDialog.cpp

this will fix the issue when trying to configure a game before running the game for the first time

pergameconfig : create directory if not exists

---

rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h
rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12PipelineState.cpp
rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/RSXVertexProgram.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
rpcs3/Emu/RSX/rsx_methods.h
rpcs3/Emu/RSX/rsx_utils.cpp
rpcs3/Emu/RSX/rsx_utils.h

This was mostly done in my repo anyway, but needed some tests to narrow down the direction bit. Fortunately diablo 3 ships with an rsx-compatible cg compiler.

Implement BRB opcode

---

.travis.yml
CMakeLists.txt

Build time cut down from 8min to 3min (a single job).

TravisCI: use ccache

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
rpcs3/Emu/RSX/GL/GLTextureCache.cpp
rpcs3/Emu/RSX/GL/GLTextureCache.h

- Fix endianness bug
- Fix r/w when real pitch is <= 64
- Fix deadlock/crash where secondary thread has lower priority than rsx::thread

gl: Fix texture cache bugs

---

rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
rpcs3/Emu/Cell/lv2/sys_vm.cpp
rpcs3/Emu/Memory/vm.cpp

Changes from previous comments changed. Had to clean it up a bit by force

Mmapper fixes

---

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp

Fixes vp rsq opcode that I broke when updating common decompiler

rsx/vp: Fixes

---

rpcs3/Gui/GameViewer.cpp
rpcs3/Gui/GameViewer.h

Add remove custom config to right click, solution by comet0 for issue #2511 ; Author of issue seemed satisfied with it, so decided to commit it since comet0 didn't. Close if inappropriate.

remove custom config (#1)

---

Vulkan/Vulkan-build/Vulkan-build.vcxproj
Vulkan/glslang-build/glslang-build.vcxproj
llvm_build/llvm_build.vcxproj

Adds the ```/m``` switch to the build command for LLVM, GLSL and Vulkan.

Multithreaded compile on Windows for llvm, glsl, vulkan

---

rpcs3/Emu/Cell/Modules/cellSysmodule.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/cellCrossController.cpp
rpcs3/cellSysutilNpEula.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/libmedi.cpp

**cellSysmodule: Register 0xF044 module (cellSysutilNpEula)**
Found by debugging Uncharted 2 Demo (NPEA90055)
Helps in all games that register sys module configuration 'multi-player'
**cellSysmodule: Register 0x0054 module (libmedi)**
Found on Motorstorm Apocalypse [NPEA00315] (thanks Zangetsu for the log)
**cellSysmodule: Register 0x005C module (cellCrossController)**
Found on LittleBigPlanet 2 [BCES00850] (thanks Zangetsu for the log)

HLE: Register cellSysutilNpEula, libmedi, cellCrossController

---

rpcs3/Emu/Cell/Modules/cellSpurs.cpp

! LDR: **** cellSpurs export: [0x31F5196B] at 0x13ab56c
! LDR: **** cellSpurs export: [cellSpursRemoveSystemWorkloadForUtility] at 0x13ab56c

Register cellSpursRemoveSystemWorkloadForUtility

---

rpcs3/Emu/Cell/Modules/cellBgdl.cpp
rpcs3/Emu/Cell/Modules/cellBgdl.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

- Functions cellBGDLGetInfo and cellBGDLGetInfo2 return the value 0 as we are expecting a number of entries. 0 means not found here.

Stub cellBgdl module

---

rpcs3/Emu/Cell/Modules/cellFont.cpp
rpcs3/Emu/Cell/Modules/cellFontFT.cpp
rpcs3/Emu/Cell/Modules/cellFs.cpp
rpcs3/Emu/Cell/Modules/cellHttp.cpp
rpcs3/Emu/Cell/Modules/cellRtc.cpp
rpcs3/Emu/Cell/Modules/cellSsl.cpp
rpcs3/Emu/Cell/Modules/cell_FreeType2.cpp
rpcs3/Emu/Cell/Modules/sys_io.cpp
rpcs3/Emu/Cell/Modules/sys_net.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Stub more functions missing.
Implement and stub cell_FreeType2.
Reorder cellRtc.
If you want change anything, request me.
For cell_Freetype2 i think is better register this module is alone, because more clear for log and for module cellfont and have very long list function, 249 register in sprx, i have register only 27 name is know, other name is actually unknow.

Registers more functions missing.

---

rpcs3/Emu/Cell/Modules/cellFontFT.cpp
rpcs3/Emu/Cell/Modules/cellFs.cpp
rpcs3/Emu/Cell/Modules/cell_FreeType2.cpp

! LDR: **** cellFontFT export: [0x05F214E0] at 0x22b13e0
! LDR: **** cell_FreeType2 import: [0x0124A94B] -> 0x22b04e0
! LDR: **** sys_fs export: [0x06E681ED] at 0x23acb90
! LDR: **** cellFontFT export: [FTFaceH_GetMaxVerticalAdvance] at 0x22b13e0
! LDR: **** cell_FreeType2 import: [FT_Done_Library] -> 0x22b04e0
! LDR: **** sys_fs export: [cellFsAccess] at 0x23acb90

Add FTFaceH_GetMaxVerticalAdvance, FT_Done_Library and cellFsAccess functions

---

rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp

- cellGamePs1Emu
- cellSysconfPs1emu
- sysBdMediaId (which included sys_get_bd_media_id)
- sysConsoleId (which included sys_get_console_id)
- sysPs2Disc

Stub new modules

---

rpcs3/Emu/RSX/D3D12/D3D12Buffer.cpp
rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/D3D12/D3D12VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp

Implement userclipping for dx/vulkan. Changed opengl to use same api as the others. Fixes #2152,

[Render] Userclip for d12/vk/ogl

---

Utilities/Config.cpp

Fixes an old bug appeared in recent PR

Config fix

---

Utilities/CRC.h
rpcs3/Crypto/key_vault.cpp
rpcs3/Crypto/key_vault.h
rpcs3/Crypto/unself.cpp
rpcs3/Crypto/unself.h
rpcs3/DS4PadHandler.cpp
rpcs3/DS4PadHandler.h
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Main changes are to DS4 - Use calibration data from controller and scale values correctly, fixes gyro reporting while making it all more accurate. Use crc values for BT and only report vibration data when changed, which should help with the latency issues.
The rest of the commits should be self explanatory

DS4 improvements + misc

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Gui/SettingsDialog.cpp

Should fix broken settings dialog when device does not support vulkan at all, or the vulkan runtime is not installed.

ui/vk: Reimplement vulkan GS selection; minor fixes for broken contexts on unsupported devices

---

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/GL/GLHelpers.h

- Fix BRK/RET fp instruction
- Minor typo fix affecting intel GPUs with OGL

rsx/fp/gl: Minor fixes

---

.travis.yml

Update TravisCI to build+upload AppImage for Linux

---

.travis.yml

Fix TravisCI #2830 additions

---

rpcs3/main.cpp
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/gs_frame.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/welcome_dialog.cpp

- this should fix the latest issue #2831 
- fix about dialog icon showing game icon
- fix game configs saving to global config if not exist yet
- fix dpi scaling on windows OS
- fix welcome screen #2539
- fix dpi scaling for gsframe #2539

Some Qt fixes

---

rpcs3/Emu/Cell/Modules/cellHttp.cpp
rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp
rpcs3/Emu/Cell/Modules/sys_rsxaudio_.cpp
rpcs3/Emu/Cell/PPUFunction.cpp
rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

**Before**
! LDR: **** cellHttp export: [0x33347DDD] at 0xac1f90
! LDR: **** cellHttp export: [0xD33AD4D0] at 0xac1fe8
! LDR: **** cellHttp export: [0xDA56BFAA] at 0xac2000
! LDR: **** cellHttp export: [0xF92217C5] at 0xac1fe0
! LDR: **** sysPrxForUser export: [0x2F256B29] at 0xa00a68
! LDR: **** sysPrxForUser export: [0x39E9B068] at 0xa00a70
! LDR: **** sysPrxForUser export: [0x7B034C78] at 0xa00a88
! LDR: **** sysPrxForUser export: [0x87C87495] at 0xa00a60
! LDR: **** sysPrxForUser export: [0x9C9605EE] at 0xa00a90
! LDR: **** sysPrxForUser export: [0xA9879A33] at 0xa00a78
! LDR: **** sysPrxForUser export: [0xB1BD7A61] at 0xa00a80
! LDR: **** sysPrxForUser export: [0xC839BB4C] at 0xa00a58
! LDR: **** sysPrxForUser export: [0xFF34C76C] at 0xa00a98
**After**
! LDR: **** cellHttp export: …

Stub for cellHttp and sysPrxForUser modules

---

.travis.yml
CMakeLists.txt

Fix da build

---

rpcs3/rpcs3qt/msg_dialog_frame.h

Fix [this issue](https://github.com/RPCS3/rpcs3/issues/2904).

Qt Fix -- Msg Dialog

---

rpcs3/Emu/Cell/PPUModule.cpp

kept bothering me until i realized what was wrong with it

REF 57 plus FREF fix

---

rpcs3/Emu/RSX/VK/VKGSRender.cpp

Add value missing for fix Lbp karting in vulkan.
thx @kd-11 for have review this.

VK: Fix for lbp karting

---

README.md

resolves review comment from https://github.com/RPCS3/rpcs3/pull/2941#discussion_r125332896 by @Zangetsu38

remove invalid comment

---

.gitignore
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.h
rpcs3/rpcs3qt/vfs_dialog.cpp
rpcs3/rpcs3qt/vfs_dialog_tab.cpp
rpcs3/rpcs3qt/vfs_dialog_tab.h

Just combining about 4 small PRs into one to avoid spamming builds.

Misc Gui Adjustments

---

rpcs3/rpcs3qt/game_list_frame.cpp

[Fix this.](https://github.com/RPCS3/rpcs3/issues/2995)

Patch crash regression in game grid

---

rpcs3/Json/tooltips.json

also Jarves please implement sysutils

Fix various typos and capitalisation inconsistencies.

---

rpcs3/rpcs3qt/main_window.cpp

Fix bug reported in #2958 after the merge.

Fix bug with std::stof being locale-dependant

---

rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

I could leave out the setText() parts and have settings_dialog.ui dictate the button text.

bakuretsu bakuretsu la la la string duplication

---

rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/debugger_frame.h
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp

This annoyed me enough that I wanted to fix it.

Debugger Frame Scroll Fix

---

rpcs3/xinput_pad_handler.cpp
rpcs3/xinput_pad_handler.h

Defaut 8000, go lower to go closer to (0,0) corner.

Adds config file entry for pad squircling factor

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

Fixes Persona 5 saving/loading on linux.
Thanks to tyler274 for awesome debugging!

Put PARAM.SFO in caps for linux users.

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h

should fix reported row size issues on sort
should fix reported scroll shenanigans on refresh

game_list: fix sort and scroll

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/settings_dialog.ui

GUI: enable smooth icon size slider

---

rpcs3/Emu/Cell/Modules/sys_net.cpp
rpcs3/Emu/Cell/Modules/sys_net.h

This changes Bomberman Ultra, Duke Nukem 3D: Megaton Edition and probably a bunch of other games from nothing -> Ingame/Playable for linux.
Weird socketselect timeout behaviour was verified on HW with @clienthax and I.
I don't have any experience with sockets and such, so if stuff doesn't make sense, please point it out.

Fix linux sysnet

---

rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/rsx_methods.cpp

Yield instead of sleeping rsx thread.

---

rpcs3/Emu/Cell/Modules/cellSysutil.cpp

Registers five missing functions in cellSysutil.

Register missing functions in cellSysutil

---

Utilities/Log.cpp
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp

Adds cpu to log.
Adds [DO NOT USE] to D3D12 selection.

ssshadow requests

---

rpcs3/Emu/Cell/Modules/cellHttp.cpp
rpcs3/Emu/Cell/Modules/cellNetCtl.cpp

Registers nine more unregistered functions.

Register more unregistered functions

---

rpcs3/rpcs3_app.cpp
rpcs3/rpcs3qt/about_dialog.ui
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_grid.cpp
rpcs3/rpcs3qt/game_list_grid_delegate.cpp
rpcs3/rpcs3qt/game_list_grid_delegate.h
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/welcome_dialog.ui

Stylesheet adjustments for [B]Ani PR

---

rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKTextureCache.h

Addendum to #3200 without risk of polluting an already massive changeset
- Fix immediate indexed rendering when immediate index array is provided but vertex data is sourced from registers and array inputs (Wolfenstein)
- Fix windowed mode -> fullscreen mode transition hangs and crashes https://github.com/RPCS3/rpcs3/issues/3243#issuecomment-323105978
- Fix a vulkan texture memory leak https://github.com/RPCS3/rpcs3/issues/3201

rsx: Bug Fixes

---

rpcs3/Emu/Cell/Modules/cellAtrac.cpp
rpcs3/Emu/Cell/Modules/cellAtracMulti.cpp

**Before**
! LDR: **** cellAtracMulti export: [0xF197CCAA] at 0x33d058
! LDR: **** cellAtrac export: [0x77E24BB0] at 0x33e058
**After**
! LDR: **** cellAtracMulti export: [cellAtracMultiGetSamplingRate] at 0x33d058
! LDR: **** cellAtrac export: [cellAtracGetSamplingRate] at 0x33e058
Credits to @Talkashie (source: http://www.psdevwiki.com/ps3/VSH_Imports)

Add cellAtracGetSamplingRate and cellAtracMultiGetSamplingRate functions

---

rpcs3/rpcs3_app.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/main_window.cpp

had the enableUIColors bool confused and forgot some styles in default stylesheet
I don't know how i missed that earlier

stylesheets: UI_Colors hotfix

---

rpcs3/rpcs3_app.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.h
rpcs3/rpcs3qt/settings_dialog.ui

Clean up remaining issues with UI Colors.
UI Colors will now be applied immediately on change.
UI Colors will now be reset on UI reset button.
TODO:

GUI: figssss

---

rpcs3/Emu/Audio/Pulse/PulseThread.cpp

Correct typo in PulseAudio

---

rpcs3/rpcs3qt/auto_pause_settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.cpp

See https://doc.qt.io/qt-5.9/qtalgorithms.html#qt-and-the-stl-algorithms
Thanks to @danilaml for pointing it out in #3255

[Qt] Replace deprecated qSort function by std::sort

---

rpcs3/Emu/Cell/Modules/cellGame.cpp

Used by some media apps, 
YouTube boots now.

Add missing game categories

---

rpcs3/rpcs3_app.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/settings_dialog.cpp

fixes the stylesheet changes not adjusting as expected whenever the dialog was closed without saving

unbelievably insignificant fixes

---

rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_prx.h

It expected to know segment file size so I added a u32 to ppu_segment to represent it.
I set it to 0 on sections for consistency.

Implement _sys_prx_get_module_info

---

rpcs3/rpcs3qt/about_dialog.ui

[Qt] add scrollbar to about dialog

---

rpcs3/Emu/Cell/Modules/cellSsl.cpp

Let's leave this one open for review for a while this time :wink:

Fix buffer overrun in cert loading, made it more accurate. Fixes #3408

---

rpcs3/rpcs3qt/msg_dialog_frame.cpp

[Qt] add char count label to osk dialog

---

rpcs3/CMakeLists.txt

The previous urls are not accessible anymore so I replaced them by newer ones.

[Qt] Fix repository urls to install Qt

---

Utilities/geometry.h
rpcs3/Emu/RSX/Common/GLSLCommon.h
rpcs3/Emu/RSX/Common/ProgramStateCache.h
rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/D3D12/D3D12FragmentProgramDecompiler.cpp
rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLHelpers.cpp
rpcs3/Emu/RSX/GL/GLHelpers.h
rpcs3/Emu/RSX/GL/GLRenderTargets.h
rpcs3/Emu/RSX/GL/GLTexture.cpp
rpcs3/Emu/RSX/GL/GLTextureCache.h
rpcs3/Emu/RSX/RSXFragmentProgram.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKTextureCache.h
rpcs3/Emu/RSX/rsx_utils.h
rpcs3/Emu/System.h
rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

- Adds support for internal resolution scaling. Compatible with most applications out-of-the-box unless 'write color buffers' is required. Note that strict rendering mode disables this scaling.
- Enables forced anisotropic filtering upto 16x
- Implements vsync mode for vulkan

rsx: Enhancements

---

rpcs3/rpcs3.vcxproj
rpcs3_default.props

Add two path missing by @scribam in Visual Studio file project for Optional submodule

Fix compile Visual Studio for Optional submodule

---

rpcs3/rpcs3.vcxproj

 Fix experimental build warning

---

Utilities/types.h

Fix compile in Visual Studio with change sugered by @Nekotekina, verified and good working

Fix compile VS

---

rpcs3/rpcs3qt/log_frame.cpp
rpcs3/rpcs3qt/log_frame.h

[Qt] add "clear" option to tty log contextmenu

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/save_manager_dialog.cpp
rpcs3/rpcs3qt/save_manager_dialog.h

Make size only 60% height of window screen initially.
Add ability to delete/select multiple rows.
Add ability to open the directory of the save.

Save manager improvements

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.h
rpcs3/Emu/System.h
rpcs3/Json/tooltips.json
rpcs3/Loader/TROPUSR.cpp
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3_app.cpp
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/save_data_dialog.cpp
rpcs3/rpcs3qt/save_data_dialog.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/trophy_notification_frame.cpp
rpcs3/rpcs3qt/trophy_notification_frame.h
rpcs3/rpcs3qt/trophy_notification_helper.cpp
rpcs3/rpcs3qt/trophy_notification_helper.h

Make a basic trophy notification dialog

---

rpcs3/rpcs3qt/save_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_notification_frame.cpp

Added a flag that makes it so that it doesn't covet focus from game_window.  Also off by one error yay.

Trophy/Save Manager Patch

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/rpcs3qt/trophy_notification_frame.cpp

Coded by @flash-fire after request it for test, him accorded for open PR.
Fix issue for user show trophy in jap, and for user want show trophy in own language.
Can use with this use all language inside trophy file depending language set in system.
Little improve for trophy dialog no dispear if user click on window game

Fix trophy show correct language.

---

rpcs3/Emu/Cell/Modules/cellMouse.cpp

Moves Dark Souls 2 from Nothing -> Ingame.

cellMouseGetDataList fixes

---

rpcs3/rpcs3qt/gs_frame.cpp

Fix HEAD or master showing up in titlebar

---

rpcs3/Emu/Cell/lv2/sys_spu.cpp

Allows Kidou Senshi Gundam Extreme VS [BLJS10131] to boot.

Fix bug in sys_spu_thread_group_create

---

rpcs3/Emu/Cell/Modules/cellSearch.cpp

Allows BLJS10131 to get ingame ;)

Fire callback in cellSearchInitialize

---

Utilities/Thread.cpp
Utilities/cond.cpp
Utilities/cond.h

Thanks to @Farseer2 for debugging cond_variable timeout @ #3708

Fixes again

---

appveyor.yml

Thanks to **wffl** from Discord who found the issue.
The last AppVeyor update introduced a breaking change for Qt (see https://www.appveyor.com/updates/).

AppVeyor Qt fix

---

rpcs3/rpcs3qt/settings_dialog.ui

This will trigger some muscle memory fetishists
should fix some small screen issues

Qt: change settingsdialog to horizontal layout

---

rpcs3/mm_joystick_handler.cpp
rpcs3/mm_joystick_handler.h
rpcs3/rpcs3qt/gamepads_settings_dialog.cpp
rpcs3/xinput_pad_handler.cpp

Input Fixerinno

---

Utilities/StrUtil.h
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/rpcs3_app.cpp
rpcs3/rpcs3qt/main_window.cpp

This is rebased and corrected #3444 PR.

Added installation for additional packages to game boot (rebased)

---

rpcs3/keyboard_pad_handler.cpp
rpcs3/keyboard_pad_handler.h
rpcs3/mm_joystick_handler.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp

Input: more fixes

---

rpcs3/Emu/Cell/MFC.cpp
rpcs3/Emu/Cell/RawSPUThread.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.h
rpcs3/Emu/Cell/SPUAnalyser.cpp
rpcs3/Emu/Cell/SPUInterpreter.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/Emu/Cell/lv2/sys_memory.h
rpcs3/Emu/System.h

- PR for jarves SPU fixes while jarves is not available

Pull jarves SPU fixes

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

savedata: avoid passing vm memory to fs::file

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellNetCtl.cpp
rpcs3/Emu/Cell/Modules/cellUserInfo.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp

This fixes Singstar Intro, moving it from Nothing->intro, and probably a bunch of the other singstar games in nothing right now. I was able to get it to the main menu, but all other attempts have proved otherwise, an issue with savedata or something.
This also fixes Gal gun BLJM60434 (and probably the demo), moving it from Nothing->Ingame, and probably playable if the graphics glitches are fixed.

various memory access violation fixes (and friends)

---

rpcs3/keyboard_pad_handler.cpp
rpcs3/keyboard_pad_handler.h

numpad wasn't registered ingame anymore

Qt/Input: fix numpad (regression)

---

rpcs3/evdev_joystick_handler.cpp
rpcs3/evdev_joystick_handler.h

this should enable evdev users to whitelist axis/sticks that don't use negative values in their range

Input: evdev: add positive axis list yml to handle 0+ range sticks

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Loader/PSF.h

Should fix some issues appeared in #3984

Some fixes again

---

.travis.yml

Attempt to see what's going on with Travis, as it has been failing randomly for the past days

Travis: Pass verbose to Qt installer

---

Utilities/JIT.cpp
rpcs3/Emu/Cell/PPUThread.cpp

Fix #4005 regression

---

rpcs3/Emu/Cell/Modules/cellNetCtl.cpp

Thanks to Zangetsu for the tip. This moves PAIN from intro->Ingame. It's not playable imo due to some graphical issues in the vehicles.

Better stub cellGameUpdateCheckStartAsyncEx/FinishAsyncEx, fixes PAIN

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/rpcs3qt/game_list_frame.cpp

let's hope this fixes missing columns.

Qt: handle zero-width columns in gamelist

---

.travis.yml

- It fixes the 404 when trying to retrieve the glew deb packages
- Add https for vulkan deb packages

[Travis] Update urls to retrieve glew and vulkan deb packages

---

rpcs3/Emu/Cell/MFC.cpp

SPU/MFC: check for sync command before doing a list transfer

---

.travis.yml
rpcs3/CMakeLists.txt
rpcs3/Emu/RSX/overlay_controls.h

Fixes #4100 
Here is an AppImage to test: https://transfer.sh/jOALk/2973644-349_linux64
I only need testing with the AppImage, only making sure the GUI shows up, preferably with different distros.

Misc. Linux improvements [Linux testers wanted]

---

CMakeLists.txt
README.md
rpcs3/CMakeLists.txt

It's a fix for the issues encountered in #4187 
We'll still need to contact package creators and tell them to add the flag to the build.

Fix for linux -march=native

---

rpcs3/Emu/Cell/Modules/cellMusicDecode.cpp

Add callbacks for cellMusicDecode

---

rpcs3/Emu/Cell/Modules/cellCrossController.cpp
rpcs3/Emu/Cell/Modules/cellMusicExport.cpp
rpcs3/Emu/Cell/Modules/cellPhotoDecode.cpp
rpcs3/Emu/Cell/Modules/cellPhotoImport.cpp
rpcs3/Emu/Cell/Modules/cellPrint.cpp
rpcs3/Emu/Cell/Modules/cellStorage.cpp
rpcs3/Emu/Cell/Modules/cellSysconf.cpp
rpcs3/Emu/Cell/Modules/cellUserInfo.cpp

Avoid games to freeze in specific cases, tested with samples and games.
Games tested:

Add callbacks for some modules

---

rpcs3/rpcs3_app.cpp
rpcs3/rpcs3_app.h
rpcs3/rpcs3qt/auto_pause_settings_dialog.cpp
rpcs3/rpcs3qt/cg_disasm_window.cpp
rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/rpcs3qt/log_frame.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/memory_string_searcher.cpp
rpcs3/rpcs3qt/rsx_debugger.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/trophy_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_notification_frame.cpp
rpcs3/rpcs3qt/vfs_dialog.cpp

reads ttf fonts from fonts and dev_flash/data/font.
use the actual font name in your stylesheets (look into the ttf)

Qt: enable custom fonts for stylesheets

---

bin/GuiConfigs/YoRHa by Ani.qss

– Fixed Library List
-- Removed uppercasing
-- Formatted checkboxes
-- Fixed selected text being white (unreadable)
– Fixed Log readability issues
-- Uses dark flat color background for improved readibility
-- Uses default font family and size for improved readibilty
-- Adjusts success, always, stack and TTY colors
– Fixed Debugger issues
-- Removed uppercasing
-- Restored default font family
-- Restored default font size
– Styled QSliders
– Added border to SpinBox
---

gui/themes: YoRHa by Ani - Usability Improvements

---

rpcs3/Emu/RSX/RSXThread.cpp

Here's one half of the fix for some of the ratchet and clank games that I was able to verify for now, on the offchance it helps others, I figured I could at least pr this part as is
test here for those curious: https://github.com/jarveson/rpcs3elfs/tree/master/rsx_test/vertex_base_addr_mask

rsx: add vertex data base to offset and mask before translating address

---

.travis.yml

Using a PPA that has been up to date constantly should not give us any problems :)

Fix Travis by using a PPA to install QT.

---

Utilities/Thread.cpp
Utilities/mutex.cpp
rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/Cell/lv2/sys_process.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/Emu/VFS.cpp
rpcs3/Emu/VFS.h

Allow some PSN games with DG category to boot

Relax /dev_bdvd mounting requirements

---

.travis.yml

I swear to god it works now.
Thanks @hcorion

Travis Fixup Fixup

---

Utilities/JIT.cpp
Utilities/JIT.h
Utilities/StrFmt.cpp
Utilities/StrFmt.h
rpcs3/Emu/Cell/PPUAnalyser.h
rpcs3/Emu/Cell/PPUFunction.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/System.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/main_window.cpp

This PR enables SPRX precompilation for firmware (after installation) and games (need to select in the game list manually).
Limitation:
* EBOOT.BIN and other executables are not compiled
* MSELF archives are not yet implemented
* Some files may require additional data for decryption

Create LLVM Cache menu

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

probably not entirely correct, but the game now goes ingame with beautiful graphics

"Fix" Luftrausers

---

rpcs3/Emu/Cell/MFC.h
rpcs3/Emu/Cell/SPUThread.h

unimportant teepo fix

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

sceNpTrophyGetGameInfo did not actually read any trophies

improve sceNpTrophyGetTrophyInfo and sceNpTrophyGetGameInfo

---

.travis.yml

Bundle libstdc++6 with AppImage to make it work on trusty

---

Utilities/mutex.h
Utilities/types.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h

Only processors with TSX are getting improved performance currently. If you don't have TSX, just ignore this PR for now.

[WIP] TSX masterrace

---

rpcs3/rpcs3.appdata.xml

Turns out you can't actually manage your computer's power through RPCS3.

Fix appstream copypasta, thanks to @Dominator56 for pointing it out

---

rpcs3/Emu/Cell/PPUDisAsm.cpp
rpcs3/Emu/Cell/PPUOpcodes.h

http://www.ds.ewi.tudelft.nl/vakken/in1006/instruction-set/b.html

Fix PPU disasm for branch opcodes with AA or LK set

---

.travis.yml
rpcs3/rpcs3.appdata.xml

Fix appimage graphics, cleanup and appdata.xml fix

---

bin/GuiConfigs/Kuroi (Dark) by Ani.qss

Also tweaks a few things visually and removes dead code

gui/themes: Refactor Kuroi (Dark)

---

Utilities/VirtualMemory.cpp

See [error log](https://ptpb.pw/v4Mi)

Unbreak build on FreeBSD

---

.gitignore
rpcs3/Emu/RSX/Capture/rsx_capture.cpp
rpcs3/Emu/RSX/Common/ProgramStateCache.cpp
rpcs3/Emu/RSX/Common/ProgramStateCache.h
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.cpp
rpcs3/Emu/RSX/Common/VertexProgramDecompiler.h
rpcs3/Emu/RSX/D3D12/D3D12GSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/RSXFragmentProgram.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKFormats.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.h
rpcs3/Emu/RSX/VK/VKHelpers.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
rpcs3/Emu/RSX/rsx_cache.h
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/Emu/RSX/rsx_utils.h

Changes:
**Main**
- Introduces the base for the gpu programs analysis and management. This will be expanded in future but right now it preparses the program ucode and tracks some statistics like usable ucode start, texture units consumed, etc to minimize number of generated shaders in some poorly coded titles.
-  Properly works around two AMD driver bugs, one vulkan bug relating to primitive restart and another opengl bug caused by broken generation of gl_vertexID in some situations
- FP: Properly initialize CC registers to fix some poorly written assembly shader ucode
- VP: Implement flow control. This implements properly jumps and function calls (CAL, BRI, RET, etc). This adds proper support for subroutines.
**Other Improvements**
- Optimize transform constant management on vulkan
- …

rsx: Stuff

---

rpcs3/rpcs3qt/custom_table_widget_item.h
rpcs3/rpcs3qt/game_compatibility.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/game_list_grid.cpp
rpcs3/rpcs3qt/game_list_grid.h
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/gui_settings.h

Also fixes some sorting issues and hides path and firmware by default

Qt: Add "Move Support" column to the gamelist

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp

Addendum to https://github.com/RPCS3/rpcs3/pull/4623

Fixup: Overlays

---

appveyor.yml

Setup Mirror for Vulkan SDK executable.
If the mirror is down it will fail back to lunar cdn.
In worst case we will force it to add Human=true, but hopefully that doesnt happen.

Vulkan SDK Mirror

---

rpcs3/rpcs3qt/cg_disasm_window.cpp
rpcs3/rpcs3qt/cg_disasm_window.h
rpcs3/rpcs3qt/syntax_highlighter.cpp
rpcs3/rpcs3qt/syntax_highlighter.h

- fix multi-line comments
- remove compilation warnings "unknown escape sequence"
- fewer lines of code (-155)

qt: rewrite syntax highlighter

---

rpcs3/evdev_joystick_handler.cpp

Requesting review from @Megamouse

Add nullptr check, fixes #4713

---

3rdparty/zlib.vcxproj

zlib.vcxproj: remove PreprocessorDefinitions "Z_SOLO"

---

Utilities/geometry.h
rpcs3/Emu/RSX/GL/GLOverlays.h
rpcs3/Emu/RSX/Overlays/overlay_controls.h
rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/VK/VKOverlays.h
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

* Position:
* Font (only via `config.yml`)
example[:](https://user-images.githubusercontent.com/6632271/41185963-24dc077e-6b97-11e8-9a8f-4c6b83725d30.png)
Edit: Also 2 more options, see below.

More perf overlay config options & overlay refactoring/fixes

---

rpcs3/rpcs3qt/register_editor_dialog.cpp

Not sure if Linux or newer Qt broke it.
Requesting review from @Megamouse

Make register editor dialog work

---

bin/shaderlog/.gitignore
rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
rpcs3/Emu/RSX/GL/GLHelpers.h
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
rpcs3/Emu/System.cpp

create shaderlog dir in Emu.Init()

---

README.md

readme prebuilt library link update

---

rpcs3/Emu/System.h
rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

Also rework the layout a bit.
We need to think about creating a firmware tab.

Qt: add new spu options to the settings dialog

---

rpcs3/Emu/Cell/Modules/cellGame.cpp

Fix cellGameDataCheckCreate2

---

README.md
appveyor.yml
rpcs3/CMakeLists.txt

Tell me if this works or I missed/confused something.
I'll be back in a few hours

Qt 5.11 for appveyor

---

rpcs3/Emu/RSX/GL/GLRenderTargets.h
rpcs3/Emu/RSX/Overlays/overlay_controls.h
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/Emu/RSX/rsx_utils.h

- Fixes https://github.com/RPCS3/rpcs3/issues/4864
- Silences some needless warnings

rsx: Fixups

---

rpcs3/Emu/Cell/SPUThread.cpp

the public documents mention address alignment is not being checked on mfc atomic commands, but they do not mention how many low bits are being ignored if at all.
so I made a [testcase](https://github.com/elad335/myps3tests/tree/master/spu_tests/atomic%20commands%20address%20alignment) that tries to get the data from an unaligned address, while the data itself is 128 byte aligned, the command adds an offset of 127 bytes to make the address being used unaligned. the returned data is the same as it would return if the address was 127 bytes lower. (this returns different data when adding an offset of 255 bytes etc)
this makes sense since atomic command's data is a 128 bytes cache line and cache lines are always aligned.
this fixes [Blades of Time](https://forums.rpcs3.net/thread-180966.html) …

mfc: clamp atomic cmd's address

---

rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.h
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp

cellSaveData: print SECUREFILE secureId, this can help to decrypt savedata

Usability fixes

---

rpcs3/rpcs3qt/settings_dialog.cpp

Qt: fix stylesheet warning

---

rpcs3/Emu/Cell/PPUThread.cpp

Fixes #4986
May fix #5003 
Fixes #5004 
Thanks to @Xcedf for noticing the broken commit

Revert d1fd4d5

---

rpcs3/Emu/RSX/Common/GLSLCommon.h
rpcs3/Emu/RSX/Common/TextureUtils.h
rpcs3/Emu/RSX/Common/texture_cache.h
rpcs3/Emu/RSX/GL/GLHelpers.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKOverlays.h
rpcs3/Emu/RSX/VK/VKTexture.cpp

Follow-up to https://github.com/RPCS3/rpcs3/pull/4996
- Implements a software decoder for format swizzles when using apple
- Implements fallback paths for buffer types that may not support host access

vk: Improve portability

---

rpcs3/Emu/Cell/lv2/sys_memory.cpp

Fix sys_memory_free

---

rpcs3/Emu/Cell/PPUFunction.cpp
rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/Emu/Cell/lv2/sys_usbd.cpp
rpcs3/Emu/Cell/lv2/sys_usbd.h

Source: http://www.psdevwiki.com/ps3/LV2_Functions_and_Syscalls

sys_usbd: add sys_usbd_event_port_send function

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

Hopefully fixes #5056 - requires testing

Fix trophy regression

---

rpcs3/Emu/Cell/Modules/cellKb.cpp
rpcs3/Emu/Io/KeyboardHandler.h
rpcs3/Emu/System.h
rpcs3/basic_keyboard_handler.cpp

Improve basic keyboard.
Sadly the shift in Qt is a bit counter productive. You'll have to hack another key as shift until i figured it out, but if you do, it should work almost flawlessly

cellKb/Qt: Improve basic keyboard 

---

Utilities/File.cpp
Utilities/Log.cpp
Utilities/Log.h
Utilities/StrFmt.cpp
Utilities/StrUtil.h
Utilities/Thread.cpp
Utilities/Thread.h
Utilities/bit_set.h
Utilities/mutex.cpp
Utilities/mutex.h
rpcs3/Emu/Cell/Modules/sys_net_.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_fs.h
rpcs3/Emu/System.cpp
rpcs3/Emu/VFS.cpp
rpcs3/Emu/VFS.h
rpcs3/rpcs3qt/trophy_manager_dialog.cpp
rpcs3/stdafx.h

This should fix multiple problems, like escaping mounted location with double dots.

[WIP] Rewrite VFS

---

.travis/build-mac.bash
.travis/deploy-linux.bash

This PR is part of the solution to https://forums.rpcs3.net/thread-199535.html with the rest of the work being done here: https://github.com/RPCS3/AppImageKit-checkrt/commit/c1674be2528769a8181fdd863eec5f86f8449726.
This may also fix https://forums.rpcs3.net/thread-199534.html but we'll have to see.
It also includes some misc. cleanup and a mac build fix.

Misc travis/appimage fixes

---

rpcs3/Emu/System.cpp

Fix Emu.Restart()

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp

- Fixes regressions introduced by #5166 
Fixes https://github.com/RPCS3/rpcs3/issues/5168

rsx: Fix vertex attrib parsing

---

rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

See Settings->Emu->Shader Loading Screen

Qt: Add shader loading screen options to the settings dialog

---

rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/RSX/Overlays/overlay_controls.h
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

Switches the X and O buttons in the overlay dialogs

RSX/Overlays: Add option for japanese button layout

---

rpcs3/Emu/Cell/PPUInterpreter.cpp

Testcase: https://github.com/RPCS3/ps3autotests/tree/master/tests/cpu/ppu_vpu

ppu-interpreter: improve vsl/vsr instructions

---

rpcs3/main.cpp

Requesting review from @Megamouse

Fix help command line argument, add --version and set Qt application name

---

rpcs3/Emu/Cell/lv2/sys_rsx.cpp
rpcs3/Emu/RSX/Capture/rsx_replay.cpp
rpcs3/Emu/RSX/Capture/rsx_replay.h
rpcs3/Emu/System.cpp
rpcs3/rpcs3qt/debugger_list.cpp
rpcs3/rpcs3qt/rsx_debugger.cpp

fix rsx thread capture booting.

rsx-capture: unbreak

---

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp

Fix hle cellGcmInit

---

rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp

ppu: Lwmutex, lwcond and scheduler fixes

---

rpcs3/Emu/RSX/RSXThread.cpp

rsx: inlined array stride fix

---

rpcs3/Emu/Cell/SPUThread.cpp

Fixes [BLUS30026](https://forums.rpcs3.net/thread-197389.html) , [BLUS30049](https://forums.rpcs3.net/thread-197872.html)

Implement sys_spu_thread_tryreceive_event

---

Utilities/File.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp

Time fixes

---

Utilities/Log.cpp
Utilities/asm.h
Utilities/cond.cpp
Utilities/cond.h
Utilities/mutex.cpp
Utilities/sync.h
rpcs3/Emu/Cell/Modules/cellCamera.h
rpcs3/Emu/Cell/Modules/cellMouse.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_event.h
rpcs3/Emu/Cell/lv2/sys_event_flag.h
rpcs3/Emu/Cell/lv2/sys_lwcond.h
rpcs3/Emu/Cell/lv2/sys_lwmutex.h
rpcs3/Emu/Cell/lv2/sys_mmapper.h
rpcs3/Emu/Cell/lv2/sys_mutex.h
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_net.h
rpcs3/Emu/Cell/lv2/sys_rwlock.h
rpcs3/Emu/Cell/lv2/sys_semaphore.h
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/Cell/lv2/sys_spu.h
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Emu/Cell/lv2/sys_timer.h
rpcs3/Emu/Io/MouseHandler.h
rpcs3/Emu/Memory/vm.h
rpcs3/rpcs3qt/log_frame.cpp

First commit is nothing noticeable.
Maybe I'll push more changes with optimizations for Windows 10 and 8.1.

Low-level changes

---

rpcs3/rpcs3qt/gs_frame.cpp

Fixes issues with fullscreen not working on amd cards anymore because of my previous fix. 🤦‍♂️
Maximizing window still works.

Fullscreen fix

---

rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/main_window.ui

Itty Bitty Fixes

---

rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/game_list_grid.cpp
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/input_dialog.cpp
rpcs3/rpcs3qt/input_dialog.h

Customizable Game List Titles

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp

Please test all the games that need cellCamera
~~maybe I broke some~~

Fix some loadable games

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

Fix counters in Deathmatch Village (previously stuck at 30min in the example below)

Time is precious

---

bin/GuiConfigs/Classic (Bright).qss
bin/GuiConfigs/Darker Style by TheMitoSan.qss
bin/GuiConfigs/Kuroi (Dark) by Ani.qss
bin/GuiConfigs/ModernBlue Theme by TheMitoSan.qss
bin/GuiConfigs/YoRHa by Ani.qss

Qt: fix game grid font for unfocused tiles

---

Utilities/Thread.cpp

This or something like this is needed for building on systems with musl c.

Fix builds with musl c

---

rpcs3/Emu/Io/PadHandler.h
rpcs3/Json/tooltips.json
rpcs3/keyboard_pad_handler.cpp
rpcs3/keyboard_pad_handler.h
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/pad_settings_dialog.ui
rpcs3/rpcs3qt/settings_dialog.ui

implements #5329 
implements #5157 
implements #4461

Add mouse movement and stick lerp settings

---

rpcs3/Emu/Cell/PPUThread.cpp

Add log messages for PPU compilation

---

rpcs3/Emu/Io/MouseHandler.h
rpcs3/Emu/Io/PadHandler.h
rpcs3/Emu/RSX/Common/texture_cache_utils.h
rpcs3/ds4_pad_handler.cpp
rpcs3/ds4_pad_handler.h
rpcs3/evdev_joystick_handler.cpp
rpcs3/evdev_joystick_handler.h
rpcs3/mm_joystick_handler.cpp
rpcs3/mm_joystick_handler.h
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/register_editor_dialog.cpp
rpcs3/xinput_pad_handler.cpp
rpcs3/xinput_pad_handler.h

- Only allow hex values with length 8 in "Go to address"
- Better handling of the "No Thread" option to prevent crashes
- fix some warnings
fixes #5489
fixes #5490

Improve debugger and handle some warnings

---

.travis.yml
.travis/build-mac.bash

fix travis

---

rpcs3/rpcs3_app.cpp
rpcs3/rpcs3qt/custom_dock_widget.h
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.h
rpcs3/rpcs3qt/main_window.ui

Adds a new checkbox to Menu->View

Make dock-widget title bars optional

---

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/Cell/Modules/cellMsgDialog.h
rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
rpcs3/Emu/Cell/Modules/cellOskDialog.h
rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/Modules/cellSysutil.h
rpcs3/Emu/RSX/Overlays/overlays.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3_app.cpp
rpcs3/rpcs3_app.h
rpcs3/rpcs3qt/custom_dialog.cpp
rpcs3/rpcs3qt/custom_dialog.h
rpcs3/rpcs3qt/msg_dialog_frame.cpp
rpcs3/rpcs3qt/msg_dialog_frame.h
rpcs3/rpcs3qt/osk_dialog_frame.cpp
rpcs3/rpcs3qt/osk_dialog_frame.h

So far I fixed the Nier regression 🤦‍♂️.
Update: 
I hope all the games which worked before still work with this PR. After my initial facepalm commit I fixed some weird behaviours with Diablo 3 that ultimately led to the conclusion that the facepalm commit was wrong (There was a reason why It was like that after all).
Sadly I can't find a proper fix for Class of Heroes that doesn't crash Diablo 3, so I'll give up for now. It seems like there is only a small detail missing though, so maybe I'll find it sometime in the Nier future.
Update 2:
Finally added the message to the On-Screen-Keyboard. I have no clue why we forgot about that one.

More game dialog fixes and add OSK message

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.h

- Adds error_code to cellSaveData

cellSaveData error_code

---

rpcs3/rpcs3qt/game_list_frame.cpp

Qt: use patch version for PS3 disc games

---

bin/GuiConfigs/Kuroi (Dark) by Ani.qss
bin/GuiConfigs/YoRHa by Ani.qss

<details><summary>Before</summary>
<p>
</p>
</details>
<details><summary>After</summary>
</p>
</details>

gui/themes: Add QDoubleSpinBox styling

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

Try to fix random save data failure

---

rpcs3/rpcs3qt/game_list_frame.cpp

I accidentally confused the locations :facepalm:

Fix "Open custom config location" option

---

rpcs3/rpcs3qt/main_window.cpp

Updates the latest FW 4.84 version according to: https://www.playstation.com/en-us/support/system-updates/ps3/

Update FW Latest Version

---

rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/GameInfo.h
rpcs3/Emu/RSX/CgBinaryFragmentProgram.cpp

It's just accepted to do this for safety.

Fix clear string

---

rpcs3/rpcs3qt/settings_dialog.cpp

Qt: hide viewport settings on custom configs

---

rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp
rpcs3/Emu/Cell/Modules/sysPrxForUser.h

this might fix some crashes that could appear in the todo logging itself

sysPrxForUser: improve crash dump functions

---

rpcs3/Emu/Cell/Modules/cellPad.cpp
rpcs3/Emu/Io/PadHandler.h
rpcs3/ds4_pad_handler.cpp
rpcs3/evdev_joystick_handler.cpp
rpcs3/keyboard_pad_handler.cpp
rpcs3/mm_joystick_handler.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/pad_settings_dialog.ui
rpcs3/xinput_pad_handler.cpp

Lets you play with your guitar with mmjoystick on certain guitar hero(tested on 5).
Also lets use your pad as a guitar on the same games(might need to rebind buttons for usability though).

Adds class type to controller options

---

Utilities/lockless.h

Fixes random hanging when using --version or --help.

Fix lf_queue destructor

---

Utilities/JIT.cpp
Utilities/JIT.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.h
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h
rpcs3/Emu/Cell/SPUThread.cpp

How to test:
1) Get a game which has Out Of Memory error.
2) Make sure SPU ASMJIT is selected, SPU Cache is disabled.

SPU: Fix Out Of Memory Error

---

rpcs3/Emu/Cell/Modules/cellNetAoi.cpp
rpcs3/Emu/Cell/Modules/sceNpMatchingInt.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

**Before:**
```
! LDR: ** Exported module 'cellNetAoi' (0x1c000001, 0x90004, 0x0, 0x0)
! LDR: **** cellNetAoi export: [0x222FD339] at 0x8b00f4
! LDR: **** cellNetAoi export: [0x480886AF] at 0x8b011c
! LDR: **** cellNetAoi export: [0x62FEC3B7] at 0x8b0124
! LDR: **** cellNetAoi export: [0x8202AA2B] at 0x8b00ec
! LDR: **** cellNetAoi export: [0x86F19F82] at 0x8b0114
! LDR: **** cellNetAoi export: [0x8AA68668] at 0x8b0104
! LDR: **** cellNetAoi export: [0xB4335A81] at 0x8b012c
! LDR: **** cellNetAoi export: [0xBDACA3AF] at 0x8b010c
! LDR: **** cellNetAoi export: [0xC9151906] at 0x8b0134
! LDR: **** cellNetAoi export: [0xDC3AA14B] at 0x8b00fc
```
```
! LDR: ** Exported module 'sceNpMatchingInt' (0x1c000001, 0x90001, 0x0, 0x0)
! LDR: **** sceNpMatchingInt export: [0x033D5BA0] at 0x890a48
! …
```

hle: Add cellNetAoi module and some sceNpMatchingInt functions

---

rpcs3/Emu/Cell/Modules/cellDtcpIpUtility.cpp
rpcs3/Emu/Cell/Modules/cellPesmUtility.cpp
rpcs3/Emu/Cell/Modules/cellVideoPlayerUtility.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

**Before:**
```
! LDR: ** Exported module 'cellDtcpIpUtility' (0x1c000001, 0x90002, 0x0, 0x0)
! LDR: **** cellDtcpIpUtility export: [0x0836F1F7] at 0x87011c
! LDR: **** cellDtcpIpUtility export: [0x4659CA92] at 0x87017c
! LDR: **** cellDtcpIpUtility export: [0x48FF0164] at 0x87016c
! LDR: **** cellDtcpIpUtility export: [0x8BD01379] at 0x870164
! LDR: **** cellDtcpIpUtility export: [0x9413678F] at 0x870174
! LDR: **** cellDtcpIpUtility export: [0x9ADE62E5] at 0x87010c
! LDR: **** cellDtcpIpUtility export: [0xAC14B8E3] at 0x87019c
! LDR: **** cellDtcpIpUtility export: [0xB2176B06] at 0x870124
! LDR: **** cellDtcpIpUtility export: [0xB89105CA] at 0x8701bc
! LDR: **** cellDtcpIpUtility export: [0xCB1E777F] at 0x87012c
! LDR: **** cellDtcpIpUtility export: [0xE0ACE309] at 0x8700fc
! LDR: **** …
```

hle: add cellDtcpIpUtility, cellPesmUtility and cellVideoPlayerUtility modules

---

rpcs3/Emu/Cell/Modules/cellCelpEnc.cpp
rpcs3/Emu/Cell/Modules/cellHttp.cpp
rpcs3/Emu/Cell/Modules/sceNpMatchingInt.cpp

0xBA50BC23 => cellCelpEncOpenExt
0x1AC58D11 => cellHttpFlushCache
0xA39FE9DC => cellHttpEndCache
0xB4FA3111 => cellHttpInitCache
0x4A18A89E => sceNpMatchingSetRoomInfoNoLimit
0xB020684E => sceNpMatchingGetRoomInfoNoLimit

hle: Add some missing functions

---

.travis/build-linux.bash

cd returns an error code, thus overwriting '$?'
someone made a dumdum

Correct travis deploy behavior (bug).

---

rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/Modules/cellFont.cpp
rpcs3/Emu/Cell/Modules/cellFontFT.cpp
rpcs3/Emu/Cell/Modules/cellFs.cpp
rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Emu/Cell/Modules/cellHttp.cpp
rpcs3/Emu/Cell/Modules/cellImeJp.cpp
rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
rpcs3/Emu/Cell/Modules/cellRtcAlarm.cpp
rpcs3/Emu/Cell/Modules/cellRudp.cpp
rpcs3/Emu/Cell/Modules/cellSsl.cpp
rpcs3/Emu/Cell/Modules/cellSysmodule.cpp
rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/Modules/cellUsbd.cpp
rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/Modules/cellVideoOut.cpp
rpcs3/Emu/Cell/Modules/cell_FreeType2.cpp
rpcs3/Emu/Cell/Modules/libad_async.cpp
rpcs3/Emu/Cell/Modules/libad_core.cpp
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/Modules/sceNp2.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

Some functions were found using a dictionary attack but because the names match so well, I decided to add them here.
These function names and their respective fnids can be found here: https://github.com/scribam/rpcs3/wiki/External

hle: Add more missing functions

---

rpcs3/rpcs3qt/game_compatibility.cpp
rpcs3/rpcs3qt/game_compatibility.h
rpcs3/rpcs3qt/game_list_frame.cpp

Qt: add version update hint to game list

---

rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/Modules/cellGameExec.cpp
rpcs3/Emu/Cell/Modules/cellRtcAlarm.cpp
rpcs3/Emu/Cell/Modules/cellUsbd.cpp
rpcs3/Emu/Cell/Modules/libad_async.cpp
rpcs3/Emu/Cell/Modules/libad_core.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

Another set of function names found through a dictionary attack. IMHO, they look pretty genuine.

hle: Add some more functions

---

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp

Fix some regressions after #4097 and #5784

---

rpcs3/Emu/Cell/Modules/StaticHLE.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp

This PR was changed several times significantly, please refer to commit messages.

Minor refactoring

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/SPUThread.cpp

Fixes #5867, Fixes #5868.
Also minor cool addition: print SPU thread group id on the debugger.

 cellSaveData: Add missing SDK version check

---

rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/PPUTranslator.h
rpcs3/Emu/Cell/SPURecompiler.cpp

No functional difference expected.

LLVM DSL refactoring

---

rpcs3/ds3_pad_handler.cpp
rpcs3/ds3_pad_handler.h

Fix for the ds3 pad handler for linux.
Thanks to z0z0z for testing.

DS3 Linux fix

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUAnalyser.h
rpcs3/Emu/Cell/SPUInterpreter.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h

SPU LLVM: fix déjà vu

---

rpcs3/Emu/RSX/rsx_utils.h

Fixes bits setting when x, y or z coords' s log2 is lower than width, height or z-length's, which happens.. all the time.
Fixes #5725.

rsx: Fix 3d swizzled texture to linear conversation

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.h
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/System.h

Settings:
* Block size: Safe or Mega
* SPU LLVM

[WIP] SPU PIC support

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp

Addressed huge regression in speed and cache size.

Giga regressions

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp

Please test for performance regression.

[WIP] SPU analyser fixes

---

rpcs3/Emu/RSX/D3D12/D3D12PipelineState.h
rpcs3/Emu/RSX/GL/GLHelpers.h
rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

Miscellaneous fixes

---

Utilities/File.cpp

Regression was caused by #6047

Fix sad bug

---

Utilities/cond.cpp

Fixing cellVdec regression

---

rpcs3/rpcs3qt/game_list_frame.cpp

Fixes accumulation of trailing slashes in games.yml

fix games.yml

---

rpcs3/rpcs3qt/pad_settings_dialog.ui

Since #5933 was merged, now you don't need to use WinUSB afaik, so I'm updating the description again so it's accurate again.
Top tier contributions, as always. Feel free to send me back to my corner if I messed something up, I deserve it after my mess up on #6062

Update DS3 message in Pads settings

---

rpcs3/evdev_joystick_handler.cpp
rpcs3/evdev_joystick_handler.h

This should fix an issue with evdev that led to KEY_BACK and KEY_HOMEPAGE not being registered in-game.
fixes #6079

Input: fix evdev buttons

---

rpcs3/rpcs3qt/game_list_frame.cpp

Adds the option "Remove All Caches" to the game context menu
closes #6073

Remove All Caches

---

rpcs3/evdev_joystick_handler.cpp

Previously, when using the evdev device handler, the buttons in the pad settings dialog were shown as disabled until you pressed a button.

Properly activate buttons when rebinding evdev

---

Utilities/JIT.cpp
Utilities/JIT.h
Utilities/Thread.cpp
Utilities/cond.cpp
Utilities/cond.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/sysPrxForUser.h
rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp
rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp
rpcs3/Emu/Cell/Modules/sys_mempool.cpp
rpcs3/Emu/Cell/Modules/sys_ppu_thread_.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUInterpreter.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Cell/lv2/sys_cond.cpp
rpcs3/Emu/Cell/lv2/sys_cond.h
rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/Emu/Cell/lv2/sys_mutex.cpp
rpcs3/Emu/Cell/lv2/sys_mutex.h
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h

Remove Accurate PUTLLC option.
Implement fallback path for SPU transactions.

[Need Testing] Implement TSX fallback

---

rpcs3/Emu/Io/PadHandler.h
rpcs3/rpcs3qt/pad_settings_dialog.cpp

Set Mouse Acceleration limit to 10
closes #5501

Set Mouse Acceleration limit to 10

---

rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp
rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
rpcs3/Emu/Cell/lv2/sys_lwcond.h
rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
rpcs3/Emu/Cell/lv2/sys_lwmutex.h

On TSX path it was supposedly broken.

Fix SPU Loop Detection

---

rpcs3/Emu/Cell/lv2/sys_timer.cpp

This is inspired by: https://github.com/RPCS3/rpcs3/pull/4716
This commit causes usleep to only sleep until one quantum before the requested time on linux. There is no change to how usleep works on windows. 
<details>
<summary>before</summary>
```
Application started
Calculating baseline delay...(0us)
Testing usleep(0)...
Latency = 0us
Testing usleep(1)...
Latency = 2us
Testing usleep(10)...
Latency = 11us
Testing usleep(50)...
Latency = 50us
Testing usleep(100)...
Latency = 100us
Testing usleep(200)...
Latency = 281us
Testing usleep(300)...
Latency = 385us
Testing usleep(400)...
Latency = 493us
Testing usleep(500)...
Latency = 585us
Doing the special tests...
Testing usleep(250)...
Latency = 274us
Testing usleep(280)...
Latency = 285us
Testing usleep(290)...
Latency = 294us
Testing …
```

lv2: sys_timer_usleep improvements for linux

---

rpcs3/Emu/Memory/vm.cpp

Fix encoding in vm.cpp

---

rpcs3/Emu/RSX/RSXOffload.cpp
rpcs3/Emu/RSX/rsx_methods.cpp

Fixup for fixup

---

rpcs3/rpcs3qt/settings_dialog.ui

Fix #6180 (typo in UI options)

---

rpcs3/rpcs3qt/emu_settings.cpp

Do not attemp to join dev enumeration thread on Emu.Stop().

Fix Emu.Stop() with vulkan device enumeration hack

---

rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h

SPU: Fix for JIT: Out of Memory

---

Utilities/Thread.cpp
Utilities/Thread.h

Also fix and note `__APPLE__` path.

Expand thread affinity mask to u64

---

rpcs3/util/atomic.cpp

Add fallback implementation for waitable atomics

---

rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/Emu/RSX/rsx_utils.cpp
rpcs3/Emu/RSX/rsx_utils.h

- Fixes a resize missing in https://github.com/RPCS3/rpcs3/pull/6314

rsx: Minor fixup

---

rpcs3/CMakeLists.txt
rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/RSX/GSRender.cpp
rpcs3/Emu/RSX/rsx_cache.h
rpcs3/Emu/System.cpp
rpcs3/headless_application.cpp
rpcs3/headless_application.h
rpcs3/main.cpp
rpcs3/main_application.cpp
rpcs3/main_application.h
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3_app.cpp
rpcs3/rpcs3_app.h
rpcs3/rpcs3qt/CMakeLists.txt
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_application.h
rpcs3/rpcs3qt/stylesheets.h
rpcs3/rpcs3qt/user_manager_dialog.cpp

Adds the option hidpi <enabled> to start rpcs3 with or without high dpi scaling (1 for enabled, 0 for disabled, default is 1). This does not override QT_AUTO_SCREEN_SCALE_FACTOR set in the environment. 
Adds the option no-gui to start rpcs3 without a Qt GUI.
Qt is still required to compile and run the main application.

Create headless application

---

rpcs3/Emu/RSX/GL/GLHelpers.h
rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
rpcs3/Emu/RSX/GL/GLRenderTargets.h
rpcs3/Emu/RSX/GL/GLTexture.cpp
rpcs3/Emu/RSX/GL/GLTextureCache.h

- Fix broken support for rgb pack16 formats
- Add rgba444 transport values required by AB: Climax
- Cleanup and refactor

gl: Texture and surface fixes

---

rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/emu_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

Adds a new tab to settings and couple of new options to it, some of them new and some moved from debug tab. Also changes the default value of sleep timer accuracy from host to usleep.

Add advanced tab to settings

---

rpcs3/main.cpp

https://bugs.kde.org/show_bug.cgi?id=401637

Work around a crash on startup on current versions of KDE on Linux.

---

rpcs3/Emu/Cell/PPUAnalyser.cpp

Fixes The Bourne Conspiracy (from hanging the emulator more than half an hour into booting instantaneously). 
Fixes #3942.

Add another pattern to ppu analyzer imports

---

rpcs3/xinput_pad_handler.cpp
rpcs3/xinput_pad_handler.h

This PR separates a part of #6208. Please refer to that PR for details.

Improvements to XInput vibration

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/GL/GLGSRender.h
rpcs3/Emu/RSX/RSXOffload.cpp
rpcs3/Emu/RSX/RSXOffload.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.h

- All spinlocks must invoke a wait callback in the backend to ensure we're not deadlocked
Fixes https://github.com/RPCS3/rpcs3/issues/6358
Fixes https://github.com/RPCS3/rpcs3/issues/6351

rsx: Fix offloader deadlock

---

rpcs3/Emu/Cell/Modules/StaticHLE.cpp
rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/Emu/Cell/lv2/sys_cond.cpp
rpcs3/Emu/Cell/lv2/sys_event.cpp
rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
rpcs3/Emu/Cell/lv2/sys_mutex.cpp
rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
rpcs3/Emu/System.cpp

Should fix firmware install crash.

Fixup after #6411

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Fix SPRX building on AppImage builds

---

rpcs3/Emu/Cell/lv2/sys_cond.cpp
rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
rpcs3/Emu/VFS.cpp

May fix #6410 problem other way.

VFS: Escape Control Characters

---

rpcs3/Emu/RSX/RSXThread.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/6395

[Hotfix] rsx: Check for stencil writes when determining zeta_write flag

---

Utilities/asm.h
rpcs3/Emu/Cell/lv2/sys_time.cpp

There was an issue with system time wrapping around about every 30 minutes or something.

Fix system time wraparound

---

rpcs3/rpcs3qt/main_window.cpp

Updates the latest FW version according to: https://www.playstation.com/en-us/support/system-updates/ps3/
* What's New in Version 4.85
This system software update improves the quality of system performance.

Update FW 4.85 Latest Version

---

rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
rpcs3/Emu/Cell/Modules/cellDaisy.cpp
rpcs3/Emu/Cell/Modules/cellFont.cpp
rpcs3/Emu/Cell/Modules/cellFs.cpp
rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
rpcs3/Emu/Cell/Modules/cellGifDec.cpp
rpcs3/Emu/Cell/Modules/cellJpgDec.cpp
rpcs3/Emu/Cell/Modules/cellL10n.cpp
rpcs3/Emu/Cell/Modules/cellPngDec.cpp
rpcs3/Emu/Cell/Modules/cellRemotePlay.cpp
rpcs3/Emu/Cell/Modules/cellSync.cpp
rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/Modules/cellSysutilAvc.cpp
rpcs3/Emu/Cell/Modules/cellVideoOut.cpp
rpcs3/Emu/Cell/Modules/cellWebBrowser.cpp
rpcs3/Emu/Cell/Modules/libsnd3.cpp
rpcs3/Emu/Cell/Modules/libsynth2.cpp
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/Modules/sceNpCommerce2.cpp
rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp
rpcs3/Emu/Cell/Modules/sys_game.cpp
rpcs3/Emu/Cell/Modules/sys_heap.cpp
rpcs3/Emu/Cell/Modules/sys_io.cpp
rpcs3/Emu/Cell/Modules/sys_libc_.cpp
rpcs3/Emu/Cell/Modules/sys_lv2dbg.cpp

Don't throw on unimplemented HLE functions.

---

rpcs3/Emu/RSX/Common/texture_cache.h

- Avoids crazy situations like trying to merge from a 3d or cubemap in memory
Fixes https://github.com/RPCS3/rpcs3/issues/6443

rsx: Do not include read-only data when attempting to do section merge

---

Utilities/File.cpp
Utilities/File.h
rpcs3/Emu/Cell/Modules/cellGame.cpp

This game won't boot unless the reported size is exactly correct.
[BLJM60468] loadable -> ingame

Reviving dead memes

---

rpcs3/Crypto/unself.cpp

Much nicer solution. Makes it easy to solve on one's own.

Add user message for uppercase RAP

---

rpcs3/Emu/Cell/Modules/cellPad.cpp

Fixes Rumble.
Apparently we added an unnecessary check without proper tests (TODO)

Fix Vibration

---

rpcs3/Emu/Io/PadHandler.h

Input: increase mouse acceleration max to x30

---

rpcs3/Emu/Audio/ALSA/ALSABackend.cpp

Improve ALSA backend

---

rpcs3/Emu/Cell/Modules/cellGem.cpp
rpcs3/Emu/Cell/Modules/cellGem.h
rpcs3/Emu/Cell/Modules/cellMouse.cpp
rpcs3/Emu/Cell/Modules/cellMouse.h
rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/Modules/cellVdec.h

Adds error_code to cellGem and fixes a log message.
Adds error_code to cellMouse.
Adds error_code to cellVdec.

Add error_code

---

rpcs3/Emu/RSX/Common/texture_cache.h

- Removes region optimization hack when moving inverted data. Calculating a different range from the one used to scan the memory range can result in unexpected collisions in the cache.
Fixes Macross 30 crash.

rsx: Fixup for blit engine when moving inverted regions

---

Utilities/cond.cpp
Utilities/cond.h
Utilities/lockless.h
Utilities/sync.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/Memory/vm_reservation.h
rpcs3/util/atomic.cpp
rpcs3/util/atomic.hpp

Atomic fix

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp

With changes from idm to fxo initialization checks were lost.

Adds initialization checks back in sys_usbd

---

Utilities/typemap.h
rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/Modules/cellCamera.h
rpcs3/Emu/Cell/Modules/cellKb.cpp
rpcs3/Emu/Cell/Modules/cellMouse.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/lv2/sys_memory.cpp
rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
rpcs3/Emu/Cell/lv2/sys_mmapper.h
rpcs3/Emu/Cell/lv2/sys_usbd.cpp
rpcs3/Emu/Cell/lv2/sys_vm.cpp
rpcs3/Emu/Cell/lv2/sys_vm.h
rpcs3/Emu/Io/KeyboardHandler.h
rpcs3/Emu/Io/MouseHandler.h
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/RSX/Capture/rsx_replay.cpp
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/main_application.cpp
rpcs3/pad_thread.cpp
rpcs3/pad_thread.h
rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/util/fixed_typemap.hpp
rpcs3/util/init_mutex.hpp
rpcs3/util/typeindices.hpp

Bug fix and maintenance quest

---

rpcs3/Emu/Cell/Modules/sceNp2.cpp

Fixes #6574 and RDR's regression.

Fix sceNp2Init

---

rpcs3/Emu/Cell/PPUDisAsm.cpp

BC now includes all possible variants.
LWSYNC, BCTR names added.

PPU Disassembly improvements

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

cellSaveData: Log param error code

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp
rpcs3/Emu/Cell/lv2/sys_usbd.h

Fixes https://github.com/RPCS3/rpcs3/issues/6608 .

Implement sys_usbd_event_port_send

---

Utilities/File.cpp

Don't try to create already existing parents

Fix fs::create_path

---

rpcs3/keyboard_pad_handler.h

input: fix missing override in keyboard pad handler

---

rpcs3/ds3_pad_handler.cpp

I forgot to check for the non pressure sensitive buttons.
fixes #6640

Fix DS3 button presses

---

rpcs3/Emu/IdManager.h

Debug build fix

---

rpcs3/Emu/RSX/RSXThread.h

Oops
Fixes https://github.com/RPCS3/rpcs3/issues/6632

rsx: Add missing initialization

---

rpcs3/Emu/Cell/Modules/sceNp.cpp

Also lower logging level as seen spammed in some games.

Bugfix for sceNpUtilCmpNpId

---

rpcs3/rpcs3qt/gs_frame.cpp
rpcs3/rpcs3qt/gs_frame.h

This is just for future use when configs are gonna become dynamic during gameplay.

Use current config value for fps in title

---

rpcs3/main.cpp

Fixes the default high dpi setting and the --hidpi cli argument.
I accidentally broke the high dpi setting when I added the cli arguments before, because I forgot that this setting has to be set before creating the QApplication.
Linux users were probably mostly oblivious of this bug since they may use environment variables.

Qt: fix high dpi setting

---

rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/vfs_dialog.cpp
rpcs3/rpcs3qt/vfs_dialog.h
rpcs3/rpcs3qt/vfs_dialog_tab.cpp
rpcs3/rpcs3qt/vfs_dialog_tab.h

Use the default Qt layout for save and cancel in the settings dialog and vfs dialog.
Once upon a time this was requested by a reviewer.
I hope your muscle memory won't be too upset.

Use Qt standard button layouts

---

Utilities/File.cpp

SPU recompilers optimization

---

CMakeLists.txt
rpcs3/Emu/CMakeLists.txt
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/GDB.cpp
rpcs3/Emu/GDB.h
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters

Drop "WITH_GDB" option, build with it by default.
Bind on 127.0.0.1:2345 by default.

[WIP] Re-enable GDB server

---

Utilities/Log.h
rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/Cell/Modules/cellPngDec.cpp
rpcs3/Emu/GDB.cpp
rpcs3/Emu/GDB.h

And harden internal API against further errors.

Fix log format misuse

---

rpcs3/Emu/RSX/VK/VKHelpers.h

Cry in log if initialization failed.

Error handling for vkCreateInstance()

---

rpcs3/Emu/Cell/Modules/cellVoice.cpp
rpcs3/Emu/Cell/Modules/cellVoice.h

Added error_code and arguments and some reversed error checks to cellVoice.

stub cellVoice

---

Utilities/Thread.cpp
Utilities/Thread.h
Utilities/lockless.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/Cell/Modules/cellMic.cpp
rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_usbd.cpp
rpcs3/Emu/GDB.cpp
rpcs3/Emu/System.cpp
rpcs3/util/fixed_typemap.hpp

Should fix freezes in some cases.

Fix TSX freezes

---

rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/Cell/Modules/cellCamera.cpp
rpcs3/Emu/Cell/Modules/cellCamera.h
rpcs3/Emu/Cell/Modules/cellMic.cpp

Fixes a regression with cellMic and fxo management.

cellMic: Bugfix

---

.travis/deploy-linux.bash

Fix path for rpcs3_version.cpp

Hotfix for #6573

---

Utilities/File.cpp
rpcs3/Emu/Cell/ErrorCodes.h

This should work around 260 character limitation.

Use long path on Windows

---

rpcs3/Emu/Cell/Modules/cellGame.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/PPUDisAsm.cpp
rpcs3/Emu/Cell/PPUDisAsm.h

Also log last fs error on ACCESS_ERROR hle return values.

Fix unknown BCLR forms formatting

---

Utilities/File.cpp
Utilities/JIT.cpp
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h

Adds option "SPU Profiler" (Core).

Implement internal SPU profiler

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Regression after #6770 
Fixes #6778

Fix "SPU Interpreter (fast)"

---

rpcs3/Emu/RSX/GL/GLRenderTargets.h
rpcs3/Emu/RSX/VK/VKRenderTargets.h
rpcs3/Emu/RSX/VK/VKResolveHelper.cpp

See https://github.com/RPCS3/rpcs3/issues/6783

rsx: Fixup

---

rpcs3/Emu/Cell/lv2/sys_vm.cpp
rpcs3/Emu/Cell/lv2/sys_vm.h

Fix sys_vm_t destructor

---

Utilities/cond.cpp
Utilities/sync.h
rpcs3/util/atomic.cpp
rpcs3/util/init_mutex.hpp

Give up on winapi semaphores since something with them makes perf worse.

Restore using keyed events in waitable atomics on Windows

---

rpcs3/Emu/Cell/Modules/cellKey2char.cpp

Add some error checks to cellKey2Char.
Maybe this will improve something.
Disclaimer: I'm not very confident in this code this time around so I'll hope for reviews

stub cellKey2Char

---

rpcs3/Emu/Cell/Modules/cellNetCtl.cpp
rpcs3/Emu/Cell/Modules/cellNetCtl.h

Improve parameter checks in cellNetCtl.
Might fix something maybe.

cellNetCtl: improve param checks

---

rpcs3/Emu/RSX/Common/texture_cache.h

Hotfix for https://github.com/RPCS3/rpcs3/issues/6799

rsx: Fixup for aspect mismatch

---

rpcs3/Emu/Cell/Modules/cellVoice.cpp
rpcs3/Emu/Cell/Modules/cellVoice.h

Implement system service events, error checking and some functions.
Test for port ID pattern and some error checks can be found at https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellVoice%20tests.
Should fix HLE load of libvoice.sprx for some games. (LLE was working by accident)
Following #5151.

cellVoice: Initial Implementation

---

rpcs3/git-version.cmake

Fix missing commit hash on linux builds

Partially revert git-version.cmake

---

Utilities/Log.cpp

Conserve error value when trying to open log file

---

rpcs3/rpcs3qt/game_list_frame.cpp

My code introduced some random crashes when reloading the game list.
I'll try to fix this for now by adding a mutex.

Fix random game list crash

---

3rdparty/qt5.cmake
BUILDING.md

Commits 5b59c18dcc969a6af691ea119149c39cba27ae3a and f3ed26e9dbbb5aa31c7ddb5fb1f252f22bfb78a0 do not work with older Qt versions, 5.11 is the minimum.

Update minimum Qt version

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h

This PR does not affect Safe mode.
Also fix regression with compiling existing SPU cache.

SPU LLVM: Enable "Giga table" in Mega mode

---

rpcs3/Emu/Cell/Modules/cellMic.cpp
rpcs3/Json/tooltips.json
rpcs3/rpcs3qt/update_manager.cpp

Super-important PR

---

rpcs3/rpcs3qt/game_list_frame.cpp

QList isn't supposed to be modified concurrently.
Use lf_queue to collect game_info data.

Qt: fix crash on startup in game_list_frame::Refresh

---

rpcs3/Emu/CMakeLists.txt
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/util/atomic2.cpp
rpcs3/util/atomic2.hpp

Implement atomic2 and multi_cas

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_application.h
rpcs3/rpcs3qt/gui_settings.cpp
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/main_window.cpp

Qt: implement time played

---

rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/rsx_methods.h

Improve logging when some required features do not exist. Crashes or glitches will still happen, but this makes it easier to diagnose the cause.

vk: Improved crash message for missing MSAA features

---

rpcs3/Emu/Cell/PPUDisAsm.h

PPU Disasm: Fix RC OE enabled instructions view

---

rpcs3/Emu/VFS.cpp

Elad reported that it stopped working correctly on Windows

Fix vfs::host::remove_all

---

rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/util/init_mutex.hpp

How to test: remove SPU cache and start game clear with SPU LLVM.

Trying to improve SPU LLVM experience

---

Utilities/JIT.cpp
Utilities/sysinfo.cpp
Utilities/sysinfo.h

LLVM: Add workaround for znver2

---

rpcs3/Emu/RSX/Common/texture_cache.h

Fixes https://github.com/RPCS3/rpcs3/issues/7023

rsx: Remove redundant check

---

Utilities/File.cpp
Utilities/Log.cpp
Utilities/Thread.cpp
Utilities/VirtualMemory.cpp
Utilities/cfmt.h
Utilities/dynamic_library.cpp
Utilities/dynamic_library.h
rpcs3/Crypto/aes.cpp
rpcs3/Crypto/ec.cpp
rpcs3/Crypto/ec.h
rpcs3/Crypto/lz.cpp
rpcs3/Crypto/md5.cpp
rpcs3/Crypto/sha1.cpp
rpcs3/Crypto/sha256.cpp
rpcs3/Crypto/utils.cpp
rpcs3/Crypto/utils.h
rpcs3/Emu/Cell/PPUModule.h
rpcs3/Emu/RSX/VK/VKOverlays.h
rpcs3/Emu/RSX/VK/VKTextOut.h
rpcs3/Emu/System.h

Replace C-style casts with C++ casts.

C-style cast cleanup (partial)

---

rpcs3/Emu/Cell/Modules/cellSsl.h
rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/PPUInterpreter.cpp

sceNpBasicAddPlayersHistoryAsync fix

---

rpcs3/Emu/Cell/PPUDisAsm.cpp

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.

PPU DisAsm: Fix branch target of B opcode

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

* Add missing multiplication by 100.
* Force round-to-nearest regardless of currrent rounding mode. (may be important in the future with ppu precise interpreter changes)

Fix sceNpTrophyGetGameProgress

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Loader/TROPUSR.cpp

Optimize some code in sceNpTrophy, some functions were called twice for no reason.

sceNpTrophy: minor optimizations

---

rpcs3/Emu/Cell/Modules/cellNetCtl.cpp

Should improve on #7114, also revert some wrong changes.

Fix cellNetCtlNetStartDialogUnloadAsync

---

Utilities/types.h
rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/RSX/Common/TextureUtils.cpp
rpcs3/Emu/RSX/VK/VKCompute.h
rpcs3/Emu/RSX/rsx_utils.h

Simplifies sceNpTrophyGetGameProgress, also fixes potential truncation warnings in aligned_div.

Implement round-to-nearest integral devision helper

---

rpcs3/rpcs3qt/game_list_frame.cpp

By adding some code to notes/titles reading, it is possible to leverage default value behaviour in QMap `value()` which simplifies code a bit.

Qt: Simplify custom titles and notes

---

rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_net.h

Potential fix for WSAPoll bug(see https://daniel.haxx.se/blog/2012/10/10/wsapoll-is-broken/ ).
Concept from: https://github.com/edenhill/librdkafka/commit/25353027141e5f40484e50611e482020919ff9e1

WSAPoll workaround

---

Utilities/BitField.h
Utilities/types.h
rpcs3/Emu/Cell/Modules/cellVdec.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/Cell/SPUDisAsm.h
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/RSX/CgBinaryProgram.h
rpcs3/Emu/RSX/Common/ring_buffer_helper.h
rpcs3/Emu/RSX/GL/GLTextureCache.h
rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.h
rpcs3/Emu/RSX/VK/VKTextureCache.h
rpcs3/main.cpp
rpcs3/rpcs3qt/cheat_manager.cpp
rpcs3/rpcs3qt/cheat_manager.h
rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/rpcs3qt/rsx_debugger.cpp

Some warnings were driving me nuts.

silence some annoying warnings

---

rpcs3/rpcs3qt/game_list_frame.cpp

1. Fix cache removal in gamelist after cache compression changes
2. Use nameFilters to simplify game list removal code

cache fixes

---

bin/GuiConfigs/Darker Style by TheMitoSan.qss
bin/GuiConfigs/Envy.qss
bin/GuiConfigs/ModernBlue Theme by TheMitoSan.qss
bin/GuiConfigs/Skyline (Nightfall).qss
bin/GuiConfigs/Skyline.qss
bin/GuiConfigs/YoRHa by Ani.qss

I was editing colors and i couldn't find where to change background color of the search bar.

In file comment typo

---

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp

Keeps games running in the background while savedata confirmation dialogs are being shown.

Don't pause games during save data dialogs

---

3rdparty/GPUOpen/include/vk_mem_alloc.h
appveyor.yml

- Updates glslang to latest stable.
- Updates GPUOpen/VulkanMemoryAllocator to latest stable.

vulkan: Update 3rd party resources

---

rpcs3/rpcs3_version.cpp

rpcs3_version: Bump to 0.0.8

---

rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
rpcs3/Emu/Cell/lv2/sys_process.cpp
rpcs3/Emu/Cell/lv2/sys_sync.h

Fixup after #6933

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

I forgot to check for a parameter that specifies if the error dialog is supposed to be shown during auto-load / auto-save / auto-delete.

Fix error dialog spam

---

.gitmodules
Vulkan/glslang-build/glslang-build.vcxproj
appveyor.yml
rpcs3/Emu/Cell/lv2/sys_tty.cpp
rpcs3_glslang.props

Fighting with vcruntime140_1.dll dependency again.

Fixup for glslang build options

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/VFS.cpp
rpcs3/Emu/VFS.h

Recreate path from actual decoded components.

Fix lv2_fs_object::name

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Loader/TROPUSR.cpp
rpcs3/Loader/TROPUSR.h
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

This should unlock platinum trophies once you unlock the last necessary regular trophy.
Please back up your save and trophy dirs before testing.

Unlock platinum trophies

---

rpcs3/Emu/Cell/Modules/cellGame.cpp

I found this old code on some branch.
It just adds some missing parameter checks to cellGame.

cellGame: add more checks

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_fs.h

sys_fs fixup

---

rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
rpcs3/Emu/RSX/VK/VKFragmentProgram.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/Emu/RSX/VK/VKHelpers.cpp
rpcs3/Emu/RSX/VK/VKHelpers.h
rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
rpcs3/Emu/RSX/VK/VKVertexProgram.h

Calculates the optimal binding layout depending on the driver and hardware in use. This should avoid limitations of one driver hurting other platforms.
Fixes https://github.com/RPCS3/rpcs3/issues/7154

vk: Generate dynamic binding table

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Loader/TROPUSR.cpp
rpcs3/Loader/TROPUSR.h

Games aren't supposed to unlock platinum trophies.
The error-code exists, but I couldn't confirm if it is actually used and when.
Hence the draft pull request.

Deny unlocking of platinum trophies

---

rpcs3/Emu/Cell/Modules/cellVdec.cpp

Update cellVdecSetFrameRate error checking

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp

This is very obvious when glancing at fw disasm, all "fail paths" lead to writing internal variable to nread/nwrite which was initialized with 0.
In cellFs nread/nwrite is untocuhed anywhere else, unlike cellFsWriteWithOffset/cellFsReadWithOffset where nwrite/nread is written with 0 after executing the syscall if error code is not CELL_OK.

Write nread/nwrite in cellFsWrite/Read regardless of error checks

---

rpcs3/Emu/Cell/Modules/cellVideoOut.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/rpcs3.vcxproj.filters
rpcs3/rpcs3qt/debugger_frame.cpp
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/qt_utils.h

Handles Qt deprecation warnings (see #7131).
Handles some random warnings in cellVideoOut and RSXThread (shouldn't affect anything)
Fixes a weird change in the VS filters that moved some random files to unwanted places.
closes #7131

Fix some warnings

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h

Correct NPC after STOP and avoid race

SPU: fixup for STOP 0w0

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/pad_settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.cpp

Gamepads Settings -> Gamepad Settings
Save -> Save custom configuration
Configure -> Create custom configuration -> Change custom configuration
Configure pads -> Create custom pad configuration -> Change custom pad configuration

Qt: Change some labels

---

rpcs3/Emu/Cell/PPUThread.cpp

Partial revert of #7180

---

rpcs3/Emu/RSX/Common/texture_cache.h

- Reject writes to RTT if the source data is of unknown origin.
non-RTT data and only 1 line in length is suspicious and often GPU data like programs or other rendering inputs.
Fixes https://github.com/RPCS3/rpcs3/issues/7063
Fixes https://github.com/RPCS3/rpcs3/issues/7240

rsx: Tweak blit engine heurestics a bit

---

rpcs3/Emu/RSX/Common/surface_store.h

Plugs a stupid data leak that was marked TODO for a while and forgotten about.
Fixes https://github.com/RPCS3/rpcs3/issues/6032

rsx: Preserve pixel data when splitting sections

---

rpcs3/Emu/Audio/AL/OpenALBackend.cpp

HOTFIX NO REVIEW ONLY MERGE

---

Utilities/Log.cpp
Utilities/Log.h
rpcs3/Loader/TRP.cpp

* Move logs::channel registration out of the constructor - Allow constinit initialization of logs::channel.

More log improvements

---

rpcs3/Emu/RSX/Common/texture_cache.h

Modifies how atlas stitching behaves when WCB/WDB is enabled. Basically, with such conditions, data will be forcefully reuploaded from CPU if it is found not to fulfill the criteria. Previously, every time the data source was from a render target and any surface had a positive match, the cache would use the incomplete data which can cause problems.
Fixes https://github.com/RPCS3/rpcs3/issues/5872

[TESTERS NEEDED] rsx: Improve atlas stitching requirements

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/System.h

Preferred spu threads made to be compatible with it.

Two more dynamically adjustable settings

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/game_list_frame.h
rpcs3/rpcs3qt/gui_settings.cpp

Fixes game grid not showing games.

Fix game grid regression

---

rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlays.cpp

- Avoid calling join on self thread.
- Avoid use-after-free.

overlays: Fixup

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp

It's based on the behavior of PPU devision instructions with 0 dividend, but it's just a guess at the end of the day.

two sceNpTrophy fixes

---

rpcs3/util/atomic.hpp

Use 2 bits to indicate "locked" and "dirty" state.

Fix fat atomics (doesn't affect anything)

---

rpcs3/rpcs3qt/main_window.cpp

It has annoyed me more than once that it defaults to *.BIN so time to change it!

Make decrypt default to All Binaries

---

3rdparty/qt5.cmake

Bump minimum Qt5 version to 5.14.0 in CMake

---

rpcs3/emucore.vcxproj.filters

Fix visual studio filters

---

rpcs3/Emu/RSX/Common/surface_store.h
rpcs3/Emu/RSX/Common/texture_cache.h

Fixes two asserts that appear when compiling with audits enabled.

rsx: Fix some asserts

---

rpcs3/Emu/Cell/Modules/cellSearch.cpp

~~More fixes will come along later, don't merge this pr yet.~~ soon™.

cellSearch: Fix id memory access

---

rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
rpcs3/util/atomic.hpp

Regression fix from #7489

---

rpcs3/rpcs3qt/game_list_frame.cpp

game_list: fix duplicate removal from games.yml

---

rpcs3/rpcs3qt/game_list_frame.cpp

Fix startup failure on invalid games.yml

---

rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui

1. Add reset button to game window title
2. Center the label in the emulator tab

Add reset button to game window title

---

rpcs3/Emu/RSX/VK/VKRenderPass.cpp

No combination of options makes this have a null impact on some drivers, so I might as well just disable it for drivers that don't need it.

vk: Only declare explicit subpass dependencies for RADV

---

.gitmodules

gitmodules contained some old unused branch

gitmodules: Fix LLVM branch

---

Utilities/StrUtil.h
Utilities/lockless.h
rpcs3/Crypto/unpkg.cpp
rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
rpcs3/Emu/Cell/Modules/cellSaveData.cpp
rpcs3/Emu/Cell/Modules/cellSysCache.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_prx.cpp
rpcs3/Emu/Cell/lv2/sys_spu.cpp
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Emu/System.cpp
rpcs3/rpcs3qt/register_editor_dialog.cpp
rpcs3/rpcs3qt/user_manager_dialog.cpp
rpcs3_default.props

Use more starts_with/ends_with.

---

rpcs3/Emu/Cell/lv2/sys_spu.cpp

Fix max SPURS threads regression

---

.gitignore
bin/GuiConfigs/YoRHa by Ani.qss

Also adds workaround for YoRHa theme background on Trophy Window until the issue is properly solved

.gitignore: maintenance, add missing files

---

rpcs3/Emu/System.cpp
rpcs3/Emu/system_config.h

Restore some /dev_flash logic

---

rpcs3/Emu/Cell/lv2/sys_spu.cpp

Fixup for #7304

---

rpcs3/Emu/System.cpp

Please test, something is weird

Fix deprecation warning in System.cpp

---

rpcs3/Emu/Cell/Modules/cellAdec.cpp
rpcs3/Emu/Cell/Modules/cellVdec.cpp

This PR fixes #6875 and supercedes it.

Fix cellVdec/cellAdec deprecation warnings

---

rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/System.cpp
rpcs3/util/fixed_typemap.hpp

Issue #7588 (broken OSK thread).
Also fix wrong internal API naming.

Try to fix threads more

---

rpcs3/rpcs3qt/update_manager.cpp
rpcs3/rpcs3qt/update_manager.h

Fix possible inconsistency in date parsing in auto-updater

---

rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp
rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.h
rpcs3/Emu/RSX/Overlays/overlay_controls.h
rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h
rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_save_dialog.h
rpcs3/Emu/RSX/Overlays/overlay_shader_compile_notification.cpp
rpcs3/Emu/RSX/Overlays/overlay_shader_compile_notification.h
rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp
rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.h
rpcs3/Emu/RSX/Overlays/overlays.cpp
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/RSX/RSXThread.h
rpcs3/Emu/RSX/VK/VKGSRender.cpp
rpcs3/emucore.vcxproj
rpcs3/emucore.vcxproj.filters
rpcs3/headless_application.cpp
rpcs3/rpcs3qt/save_data_dialog.cpp
rpcs3/rpcs3qt/trophy_notification_helper.cpp

Moves some code around.
Untangles some more headers.
Specifically removes visibility of cell headers from overlays.h

Overlays Maintenance

---

rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
rpcs3/Emu/RSX/Overlays/overlays.cpp
rpcs3/Emu/RSX/Overlays/overlays.h
rpcs3/util/fixed_typemap.hpp

overlays: add "thread bits" to wait on and avoid lockup

---

rpcs3/Emu/RSX/VK/VKRenderTargets.h

- Images must be in TRANSFER_DST_OPTIMAL or GENERAL layouts to call the image upload routines.
Fixes https://github.com/RPCS3/rpcs3/issues/7517

vk: Fixup for RCB/RDB in special cases

---

rpcs3/Emu/Cell/lv2/sys_ss.cpp

sys_ss: use BCryptGenRandom on Win32

---

Utilities/Thread.cpp

* Getting rid of handled exception handler fixes 2 things:
* Visual Studio debugger won't force it's own handler on unhandled exception.
* SPU segfaults in recompiler can now be reported. (probably didn't work for similar reasons as to #7493)
Do it moving the code from code from SetUnhandledExceptionFilter's callback into 
AddVectoredExceptionHandler's callback.
* Log vm memory bases.

Segfault/exceptions reports: Get rid of unhandled exeption handler (Windows), log memory bases.

---

Utilities/Log.cpp
Utilities/Thread.cpp

It looks like with https://github.com/RPCS3/rpcs3/commit/5871c4e93f06b233abe9c54411e4e0fec8bff1d2 RPCS3 doesn't even startup properly, need more investigation.

Exceptional fixups

---

rpcs3/Emu/GameInfo.h

Compilation fix

---

rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/rpcs3qt/main_window.cpp

Previously showed "Unknown error" dialog.

Add error dialog if firmware is missing

---

rpcs3/rpcs3qt/update_manager.cpp
rpcs3/rpcs3qt/update_manager.h

There's been some strange timecodes in updater, maybe adding some logging could help figure out what's causing them
Also includes minor cleanup for the update manager file.

Add more logging to updater

---

rpcs3/Emu/Cell/Modules/cellSaveData.cpp

* Fix doneGet->sizeKB to measure kilobytes imstead bytes, fix rounding.
* Improve statGet->sizeKB narrowing conversion.

cellSaveData: fix doneGet->sizeKB

---

Utilities/Thread.cpp
Utilities/Thread.h

[WIP] Thread.h cleanup

---

rpcs3/Crypto/utils.cpp

Fix Crypto/utils.cpp: extract_file_name

---

rpcs3/Emu/System.cpp

Fixup for firmware installation

---

rpcs3/Emu/Cell/PPUModule.cpp

Try to use designated initializers

---

rpcs3/Emu/System.cpp

Shows fatal error if stopping takes more than 5s.

Implement stop watchdog

---

rpcs3/Emu/RSX/Common/texture_cache_helpers.h

Fixes https://github.com/RPCS3/rpcs3/issues/7732

[HOTFIX] rsx: Fix copypasta

---

rpcs3/Emu/RSX/VK/VKTextureCache.h

Fixes https://github.com/RPCS3/rpcs3/issues/7682

[HOTFIX] vk: Properly release dma resources.

---

.travis/build-linux.bash

This shrinks the size of the AppImages. This is the start of some work to try to make the size of the AppImages smaller.
On the clang build we now link with lld, and on GCC we now link with Gold.
For reference:
Master AppImage size:
49.3MiB
This PR AppImage size:
47.6MiB

Build rpcs3's AppImages with link time optimization

---

rpcs3/rpcs3qt/update_manager.cpp

Apparently the time is sometimes wrong ("Your build is x day(s), y hour(s) and z minute(s) old").
So by using QDateTime instead of istringstream and mktime I hope this is fixed.
We now additionally print the date of both versions.
This also unifies some behaviour when using a custom build and prints the age of the latest build.

Fix shown time in Update Manager

---

rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp

Minor fixup after #7826

---

README.md

Hype™️
Thanks to @JohnHolmesII for the hint

[README.md] Update to Visual C++ Redistributable 2019

---

rpcs3/Emu/System.cpp

Don't assume local path has '/dev_hdd0' in it.

Fix PS1 game_path

---

rpcs3/Emu/Cell/lv2/sys_net.cpp

Should fix page faults notifications on unmapped memory in Gran Turismo 5.

sys_net: Fix access violation handling

---

rpcs3/rpcs3qt/main_window.cpp

Updates the latest FW version according to: https://www.playstation.com/en-us/support/system-updates/ps3/
What's New in Version 4.86
* This system software update improves system performance.

Update FW 4.86 Latest Version

---

rpcs3/main.cpp

I'll try to figure out why fatal error dialog is broken with appimage

[Linux] Fix fatal error dialog in AppImage

---

rpcs3/rpcs3qt/game_list_frame.cpp

Qt: fix nullptr

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/7761

Add Lego Dimensions Portal to usb passthroughs

---

Utilities/JIT.cpp
Utilities/JIT.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp

SPU: Fix SPU Precise interpreter

---

rpcs3/Input/pad_thread.cpp

Might fix https://github.com/RPCS3/rpcs3/issues/7898

AddLddPad fix

---

rpcs3/Emu/Cell/lv2/sys_rsx.cpp

* Allow ENOTCONN in event sending, gcm events queue destruction is part of normal exit process.
* Add assertations for zcull/tiles referencing.
* Remove single get+put writes which are no longer needed.

sys_rsx: Fixup after #7978

---

rpcs3/rpcs3qt/localized.cpp

Qt: fix time played

---

rpcs3/Emu/Cell/Modules/cellRtc.cpp
rpcs3/Emu/Cell/Modules/cellRtc.h

Will need a bit more work currently,
Whats left is mainly the parsing and a couple of syscalls, along with tidying up all the copypasta

Implement cellRtc HLE

---

rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/tooltips.h

~~#7930~~ now merged.
Suggestions for description are welcome.

gui: don't allow cpu with fma support disable accurate path

---

Utilities/File.cpp
Utilities/StrUtil.h
Utilities/VirtualMemory.cpp
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/GDB.cpp
rpcs3/rpcs3qt/cheat_manager.cpp

This PR fixes numerous code confusions. 
Fixes #7997

[Code enhancements] Fix various explicitness, laziness, hard codes

---

rpcs3/Emu/Cell/lv2/sys_usbd.cpp

Closes https://github.com/RPCS3/rpcs3/issues/8010

Add Disney Portal to passthroughs

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp

Incorrect arithmetics.
Fixes #8041

Fix regression in SPU ASMJIT

---

Utilities/VirtualMemory.cpp
Utilities/VirtualMemory.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm.h
rpcs3/Emu/Memory/vm_locking.h
rpcs3/Emu/Memory/vm_reservation.h

If there is no noticeable degradation, I may consider using it. Currently it's very unclear.
Both TSX and non-TSX CPUs are welcomed to test.

Experimental code for shared memory reservations

---

rpcs3/Emu/Cell/lv2/sys_rsx.cpp

Should fix a regression in COD MW2.

sys_rsx: Fix tiles on MAIN memory error checking

---

rpcs3/rpcs3qt/emu_settings_type.h
rpcs3/rpcs3qt/settings_dialog.cpp

- fixes clocks scale default in the settings dialog
- removes some unused legacy settings

Settings cleanup

---

rpcs3/Crypto/key_vault.cpp
rpcs3/Crypto/key_vault.h
rpcs3/Crypto/unpkg.cpp
rpcs3/Crypto/unpkg.h
rpcs3/Emu/System.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.h

Do not allow the installation of a package that has a _**TARGET_APP_VERSION**_ if:
- there is no game data installed for this title
- the installed game data's **_APP_VER_** does not match the **_TARGET_APP_VERSION_**
Do not allow the installation of a package that has no **_TARGET_APP_VERSION_** but an **_APP_VER_** if:
- the installed game data's **_APP_VER_** is bigger than the package's **_APP_VER_**
fixes #5576

Restrict package installations

---

rpcs3/Input/evdev_joystick_handler.cpp

evdev: fixup for relax controller criteria

---

rpcs3/Emu/Cell/SPUThread.cpp

Fine-tuned for:
1) MSVC
2) GCC AppImage build
3) GCC custom build with AVX

Implement mov_rdata_avx

---

rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/gui_application.h

Qt: update playtime and last played every 10 seconds

---

rpcs3/Emu/RSX/RSXThread.cpp

* When timestamp_subvalue was equal to 1000 the reported time is the next microsecond, which means in comparison to other time reporting features with microsecond accuracy such current flip or vblank time (they use get_system_time()), `rsx::thread::timestamp()` has reported time ahead of the time flip/vblank reported.
Even comparisons of two or more values from `rsx::thread::timestamp()` could have indicated such "time traveling". e.g if the first call had `x` value reported from get_system_time() and timestamp sub value that was greater than 1000, so if in the next call to `rsx::thread::timestamp()` the value reported by get_system_time() is greater than `x` but less than `x` + subvalue then this is illegal.
To fix this, forcefully wait in `rsx::thread::timestamp()` until the next time …

rsx: Fix zcull time to not time travel to the future

---

rpcs3/Emu/Cell/Modules/cellAudioOut.cpp

* When audioOut is not a valid device, CELL_AUDIO_OUT_ERROR_ILLEGAL_PARAMETER should be returned. If the specific function does not support it ERROR_UNSUPPORTED_AUDIO_OUT is returned.
* Reset all bytes of some structures in cellAudioOutGetState, cellAudioOutGetConfiguration, cellAudioOutGetDeviceInfo.
Writeback data when the function returns CELL_OK. (fixed in cellAudioOutGetState)
* Add some ERROR_UNSUPPORTED_AUDIO_OUT checks for CELL_AUDIO_OUT_SECONDARY.
*  add checks for deviceIndex using cellAudioOutGetNumberOfDevice in functions cellAudioOutGetState, cellAudioOutGetDeviceInfo.
Note that error handling of it varies between CELL_AUDIO_OUT_SECONDARY and CELL_AUDIO_OUT_PRIMARY.
Testcase: https://github.com/elad335/myps3tests/tree/master/ppu_tests/cellAudioOut

cellAudioOut Improvements

---

rpcs3/Input/evdev_joystick_handler.cpp

evdev facepalm

---

rpcs3/Emu/Cell/SPURecompiler.cpp

Let's optimize SPU FMA instructions just like I did with the altivec FMA instructions earlier.
The odd thing here is that there's no real reason for SPU code to be written this way, as the SPU ISA includes a floating multiply instruction. But this kind of thing exists in retail code, so let's optimize it.
It's a common pattern in games such as god of war 3 and demons souls.

SPU: Optimize FMA ops with 0 addend

---

rpcs3/rpcs3qt/gs_frame.cpp
rpcs3/rpcs3qt/gs_frame.h
rpcs3/rpcs3qt/gui_settings.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/tooltips.h

Doesn't seem to work on my setup.
Maybe it's a driver issue?
Or maybe I'm just too stupid.

Show mouse in fullscreen

---

Utilities/JIT.cpp
Utilities/JIT.h
Utilities/Thread.cpp
rpcs3/Emu/CPU/CPUTranslator.cpp
rpcs3/Emu/CPU/CPUTranslator.h
rpcs3/Emu/Cell/Modules/StaticHLE.cpp
rpcs3/Emu/Cell/Modules/StaticHLE.h
rpcs3/Emu/Cell/Modules/cellSpurs.h
rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp
rpcs3/Emu/Cell/PPUFunction.cpp
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUModule.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/Emu/Cell/PPUTranslator.h
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/rpcs3qt/main_window.cpp

Workaround some intellisense problems. For some reason "module" is treated like a full keyword although it's supposed to be contextual.

Minor cleanup

---

.travis.yml
azure-pipelines.yml

https://github.com/hcorion/rpcs3-docker/pull/4#issuecomment-626374393

[CI] xenial 1.2->1.3

---

rpcs3/Emu/NP/np_handler.cpp

Fix possible cur_ip nullptr usage in np_handler.cpp

---

.ci/build-linux.sh
.travis.yml
azure-pipelines.yml

This updates
- Qt to 5.14.2
- Ninja to 1.10.0
- SDL2 to 2.0.12

Bump Linux CI depedencies

---

Utilities/types.h
rpcs3/Emu/RSX/rsx_utils.h

Implement std::countl_zero and friends for macos

---

rpcs3/Emu/system_config.cpp
rpcs3/Emu/system_config.h
rpcs3/rpcs3qt/settings_dialog.cpp

Handle some emu settings issues

---

rpcs3/Emu/Cell/Modules/sceNp.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp
rpcs3/main.cpp
rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/pad_settings_dialog.ui
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/welcome_dialog.ui

Note: in main.cpp there are many dirs similar to Program Files, so tip should be appropriate.

Fix some misspells

---

rpcs3/Emu/RSX/GL/GLGSRender.cpp
rpcs3/Emu/RSX/VK/VKGSRender.cpp

Thanks for Jo on discord for reporting this.

rsx: Fix possible case NULL zcull_ctrl in on_exit()

---

rpcs3/Emu/System.cpp
rpcs3/Emu/System.h

Compile EBOOT.BIN on 'Create PPU Caches'

---

rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/system_config.h
rpcs3/rpcs3.vcxproj
rpcs3/rpcs3.vcxproj.filters

I don't know if this is correct.
Please test and compare with master

Make master volume dynamic

---

rpcs3/Emu/Cell/lv2/sys_semaphore.cpp

`sem` has been referenced by value instead of reference, this is a minor change.

Avoid copying std::shared_ptr in sys_semaphore

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.h

Should fix possible crash on exit.

SPU LLVM: fix spu_cache dependency

---

rpcs3/Emu/System.cpp

Try to compile patched version of EBOOT.BIN

Add game patch support in 'Create PPU Caches'

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/System.cpp

Prevent termination if PPU LLVM compilation is in progress.

Improve Stop Watchdog

---

rpcs3/Emu/RSX/Common/FragmentProgramDecompiler.cpp

- Sometimes, usually with shaders that do pack/unpack operations, there is a write-to-self operation.
e.g `r0.xy = r0.xy` Obviously no new data was introduced into "r0" by this, so we should not mark the register as having new data.
- TODO: Investigate on realhw if self-reference is needed to "cast" the overlapping half registers to their full register counterparts. This pattern has been noted in more than one game and for the cg compiler to emit it, it must mean something.
Fixes https://github.com/RPCS3/rpcs3/issues/6303

rsx/fp: Ignore self-referencing register writes.

---

.mention-bot

This PR removes mentionbot config because mentionbot not used.

Remove mentionbot config

---

rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/rpcs3qt/kernel_explorer.h
rpcs3/rpcs3qt/qt_utils.cpp
rpcs3/rpcs3qt/qt_utils.h

kernel_explorer: keep existing trees expanded

---

azure-pipelines.yml
rpcs3/Emu/Cell/PPUInterpreter.cpp

Destination register was wrong, fixes #8387.

PPU interpreters: Fix VRFIM, VRFIN, VRFIP, VRFIZ

---

Utilities/bin_patch.cpp
Utilities/bin_patch.h
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.h
rpcs3/rpcs3qt/patch_manager_dialog.ui

Legacy patches are enabled by default

patch manager: add checkbox "Enable Legacy Patches"

---

rpcs3/Emu/Cell/lv2/lv2.cpp
rpcs3/Emu/Cell/lv2/sys_cond.cpp
rpcs3/Emu/Cell/lv2/sys_cond.h
rpcs3/Emu/Cell/lv2/sys_event.h
rpcs3/Emu/Cell/lv2/sys_event_flag.h
rpcs3/Emu/Cell/lv2/sys_lwcond.h
rpcs3/Emu/Cell/lv2/sys_lwmutex.h
rpcs3/Emu/Cell/lv2/sys_mutex.h
rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/Cell/lv2/sys_net.h
rpcs3/Emu/Cell/lv2/sys_rwlock.h
rpcs3/Emu/Cell/lv2/sys_semaphore.h
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Emu/Cell/lv2/sys_timer.cpp
rpcs3/Emu/Cell/lv2/sys_timer.h
rpcs3/rpcs3qt/kernel_explorer.cpp
rpcs3/rpcs3qt/kernel_explorer.h
rpcs3/rpcs3qt/qt_utils.cpp

* Protocol information of lv2 objects has been added.
* Add Mutex ID of conditional variables, same goes for LW mutex and LW cond.
* Shared memory section has been renamed to "Shared Memory" instead of "Memory" as I may add sys_memory allocations info in the future and try to avoid ambiguity when it happens.
* Virtual Memory (from sys_vm) information has been added.
* Timers information has been added.
* Network sockets information has been added.

Kernel Explorer: More Improvements

---

rpcs3/Emu/RSX/GL/GLRenderTargets.cpp

Fixes some random verification errors in texture cache.

gl: Fix depth buffer byteswap hint

---

rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
rpcs3/Emu/IdManager.h

A function which clears all objects of a specified type.

IDM: Implement idm::clear<typename>

---

rpcs3/Emu/Cell/lv2/sys_net.cpp

Output some string I found on hw tests, 
Fixes EINVAL on sys_net_bnet_connect in PS3 Youtube App.

sys_net: Stub sys_net_infoctl command 9

---

rpcs3/Emu/System.cpp
rpcs3/rpcs3qt/emu_settings.cpp

Protection against data corruption.

Atomically overwrite config.yml

---

Utilities/bin_patch.cpp

Fixes embedded spu elf patches, which broke after the recent patch manager PR

Fix embedded spu elf patching

---

rpcs3/Emu/Cell/lv2/sys_vm.cpp

A single PS3 process can hold up to 256 MB of Virtual Memory, after that an EBUSY error code is returned.

sys_vm: Limit total process vsize to 256MB

---

rpcs3/Emu/Cell/Modules/cellAudio.cpp
rpcs3/Emu/RSX/RSXThread.cpp
rpcs3/Emu/system_config.h

rsx: Make "Disable ZCull Occlusion" setting dynamic

---

rpcs3/Emu/RSX/RSXThread.cpp

Depth buffers can be in special "read" state when writes are disabled. Account for this.
Followup to https://github.com/RPCS3/rpcs3/pull/8434

[HOTFIX] rsx: Fix surface option invalidation

---

.github/ISSUE_TEMPLATE/3-feature-request.md

I've noticed many feature requests issues opened recently.
I decided to create a template for them.
Under the line goes the design for the template.
---
Please briefly describe what feature you would like RPCS3 to have.
Please describe the feature as accurately as possible.
* Gameplay
* Debugging
* UI
* Patches
* Installation
* Github
* CI
* etc.
* OS
* CPU
* GPU
* Driver version
* etc.
* Anything else you deem to be important

Create Github Issue Template: Feature Request

---

Utilities/BEType.h
rpcs3/Emu/Cell/SPUThread.cpp

Optimize comparison operators, bitwise NOT operator and clear() method.

v128: A few optimizations

---

.github/ISSUE_TEMPLATE/2-bug-report.md

I decided to renovate Github Bug Issue Template.
I tried to make it as simple as possible. 
* Add big banner "Don't ask for support"
* Details are now separated in groups.
* Add an instruction on how to find log.
* Add an instruction on how to attach RSX captures.
* Add a screenshot with performance overlay with at least medium level of details request.
Under the line goes new design.
---
Please briefly describe what is not working correctly.
Please describe the problem as accurately as possible.
* Run the game until you find the issue.
* Completely close RPCS3, or move to the next step in case it has crashed.
* Locate RPCS3's log file:
+ ```RPCS3.log``` (It can show up as just RPCS3 and have a notepad icon)
or
+ ```RPCS3.log.gz``` (It can show up as RPCS3.log and have a zip or rar icon) …

Update Github Issue Template: Bug

---

.github/ISSUE_TEMPLATE/1-regression-report.md

I decided to renovate Github Regression Issue Template.
I tried to make it as simple as possible. 
* Every link is now stylized properly.
* Details are now separated in groups.
* Add an instruction on how to find log.
* Add an instruction on how to attach RSX captures.
* RenderDoc is now with capital ```D```
* Add a screenshot with performance overlay with at least medium level of details request.
Under the line goes new design.
---
Please briefly describe what has stopped working correctly.
Please describe the regression as accurately as possible.
* Please see [How to find the build that caused a regression](https://wiki.rpcs3.net/index.php?title=Help:Using_different_versions_of_RPCS3#How_to_find_the_build_that_caused_a_regression.3F) in our wiki.
* You can find [History of RPCS3 …

Update Github Issue Template: Regression

---

rpcs3/Emu/Audio/FAudio/FAudioBackend.cpp

Same as commit 66d13da2acfa288 for the XAudio2 backend

FAudio: remove 4x volume factor

---

Utilities/bin_patch.cpp

patch_manager: fix missing config path

---

rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/qt_utils.cpp
rpcs3/rpcs3qt/qt_utils.h

Show available information when clicking on some random branch node.

patch_manager: more information for branch nodes

---

rpcs3/rpcs3qt/register_editor_dialog.cpp

It checked outdated register prefixes.

debugger: Fix registers editor

---

Utilities/bin_patch.cpp
Utilities/bin_patch.h
rpcs3/rpcs3qt/patch_manager_dialog.cpp

sigh, I already had this ready and tested but forgot to push 4 hours ago

patch manager: fix import

---

rpcs3/rpcs3qt/patch_manager_dialog.cpp

The import stuff still has some harmless glitches.
This should fix some of them.

Minor patch manager fix

---

Utilities/bin_patch.cpp
Utilities/bin_patch.h
rpcs3/rpcs3qt/patch_manager_dialog.cpp
rpcs3/rpcs3qt/patch_manager_dialog.h

This will open a warning dialog whenever the patch manager is opened and incompatible patches are detected.

patch_manager: warning for incompatible patches

---

rpcs3/Emu/Cell/lv2/sys_net.cpp

Without this, cellHttpSendRequest will use the hardcoded dns 192.168.1.1, which won't work if you're not on that network.
First time looking at the project really. Open to any improvements.

sys_net: Use np_handler dns if possible for sys_net_infoctl

---

bin/GuiConfigs/Skyline (Nightfall).qss
bin/GuiConfigs/Skyline.qss
bin/GuiConfigs/YoRHa by Ani.qss
rpcs3/rpcs3qt/cg_disasm_window.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

Fix themes

---

rpcs3/Emu/Cell/PPUInterpreter.cpp
rpcs3/Emu/Cell/PPUTranslator.cpp

Makes the testcase https://github.com/elad335/ps3autotests/tree/master/tests/cpu/ppu_integer_arithmetic match rpcs3.

PPU: Fix DIVW, DIVWU, MULHW, MULLW, MULHWU when op.rc is set

---

rpcs3/Emu/RSX/rsx_cache.h

This pull request fixes an old issue on shader cache's load and compile stages.
When on single worker mode, which is used by OpenGL (or Vulkan if you had a single-core PC) shader load would skip 10% of the cache's shaders and shader compilation would skip another 10% of the already 90% loaded shaders.
This one was a headache but it's finally gone. Off-by-one bug.
---
```
> First worker
stop_at = 10
processed = 9
pos = processed++
pos = 10
processed = 10
> Next worker
stop_at = 20
processed = 10
pos = processed++
pos = 11
...
```
Every shader on `pos % 10 == 0` would be skipped by accident.

rsx: Fix cache skipping shaders on load+compile

---

rpcs3/rpcs3qt/main_window.cpp

Trying to make the messages easier to understand without completely removing all techical details. Also switched around expected and actual values on log message about size mismatch.

Improve error messages in firmware install

---

rpcs3/main.cpp

Don't open an error dialog in headless mode

---

rpcs3/main.cpp

Try to fix ugly GUIs

---

rpcs3/rpcs3qt/main_window.cpp

Accidentally ignored .PKG files

Qt: fixup for PKG installation

---

rpcs3/Emu/RSX/VK/VKHelpers.cpp

- Properly match image_type->image_view_type for placeholder dummy textures.
Fixes https://github.com/RPCS3/rpcs3/issues/8674

vk: Some shader improvements

---

rpcs3/rpcs3qt/main_window.cpp
rpcs3/rpcs3qt/main_window.ui
rpcs3/rpcs3qt/settings_dialog.ui

- add advanced, emulator and GUI to Configure tab
- moves accurate rsx access to advanced tab

Minor UI improvements

---

rpcs3/Emu/RSX/GL/GLTextureCache.h
rpcs3/Emu/RSX/VK/VKTextureCache.h

- Some texture accesses require image compositing steps to assemble the requested image from existing subresources. Handle all the common routines in a unified manner to avoid having one broken path (e.g mipmap gather not supporting bitcast operations)
Fixes https://github.com/RPCS3/rpcs3/issues/8229

rsx: Unify composite texture creation and management

---

rpcs3/Emu/Cell/SPURecompiler.cpp

* Fix a few bugs with +- extended SPU floats range (x86 NaNs), whilst improving performance in theory because of removing all vector constants dependencies and allowing out-of-order execution for most steps. pinging @Whatcookie to review.
* Add optimization regarding nonzero constants.

SPU LLVM: Improve approx FCGT

---

.ci/github-upload-windows.sh
azure-pipelines.yml

Requesting review from @AniLeo and @JohnHolmesII

Manually upload windows Github Release using curl

---

.ci/github-upload-windows.sh
azure-pipelines.yml

Improve id variable parsing and print release.json output to catch errors.

Windows GitHub release hotfix

---

Utilities/types.h
rpcs3/Emu/Cell/lv2/sys_cond.cpp

Warning fixes

---

bin/GuiConfigs/YoRHa by Ani.qss
rpcs3/main.cpp

- Fix QT_AUTO_SCREEN_SCALE_FACTOR copy pasta typo
- Fix YoRHa treewidget item checkbox styles

Minor Qt fixes

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/save_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

This resize call was basically doubling the list refresh time for me.
Removing it doesn't seem to make any visual difference.
The more games you have the more you'll feel an impact.

Qt: speed up list refresh

---

rpcs3/rpcs3qt/kernel_explorer.cpp

kernel-explorer: Add RSX handlers events info

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/save_manager_dialog.cpp
rpcs3/rpcs3qt/trophy_manager_dialog.cpp

This reverts commit 715f4f0669e7faeaa846b2b3e0b4ea516ec37ccf.
probably fixes #8755
I guess now we know why the code was there.

Revert "Qt: speed up list refresh"

---

rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/cellSpurs.h
rpcs3/Emu/Cell/PPUModule.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/System.cpp

* Retry of #7180 for PPU LR logging in HLE functions for debugging purposes.
* Implement cellSpursAddUrgentCommand.
* Fix UB in Emulator::Load, fixes #8781.

PPU: log LR in HLE functions

---

rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Cell/lv2/sys_sync.h
rpcs3/Emu/System.cpp

@Megamouse reported some threads possibly stuck on exit.

Minor fixup for RPCS3 termination

---

rpcs3/Emu/Cell/lv2/sys_net.cpp
rpcs3/Emu/NP/rpcn_client.cpp

tcp_timeout_monitor deadlock fix

---

rpcs3/Emu/RSX/Common/GLSLCommon.h
rpcs3/Emu/RSX/VK/VKTexture.cpp

- Fix format mismatch detection
- Fix shadow emulation filtering
Fixes https://github.com/RPCS3/rpcs3/issues/8784

rsx: Depth fixups

---

rpcs3/Emu/RSX/VK/VKCompute.h
rpcs3/Emu/RSX/VK/VKFormats.cpp
rpcs3/Emu/RSX/VK/VKTexture.cpp

- Adds upload and download routines. Mostly untested, an error message is added to help identify titles that may use this format extensively.
Fixes https://github.com/RPCS3/rpcs3/issues/8786

vk: Improve D16F handling

---

rpcs3/rpcs3qt/localized.cpp

Added description 'Never played' for games with no elapsed time indicated.
Tidied up game list times to handle translation for larger unit of time in each time pairing, and if there is a language with different time unit ordering big/small (I'm not aware of any however).
NOTE: Latin will be a problem (sorry for any native Latin ~~speakers~~readers)

GUI: gamelist: further internationalisation updates

---

rpcs3/Emu/VFS.cpp

VFS: fix off-by-one error in vfs::escape()

---

rpcs3/Emu/Cell/PPUThread.cpp

* Do not allow unaligned addresses for PPU reservation instructions.
* Do not allow unmapped addresses for PPU reservation store.

PPU: Throw exceptions on unaligned/unmapped reservation addresses

---

rpcs3/Emu/RSX/VK/VKTextureCache.h

All data going through raw DMA transfer has byteswap enabled but not all formats are expected to do this. An exception has been added for this corner case.
Fixes https://github.com/RPCS3/rpcs3/issues/8803

vk: Fix nul section crash due to unexpected format (B8)

---

rpcs3/rpcs3qt/gs_frame.cpp

Add rsx capture shortcut

---

rpcs3/rpcs3qt/settings_dialog.ui

This should make it easier to handle dynamic settings.

Qt: allow handling of the game window while the settings dialog is open

---

rpcs3/Crypto/unedat.cpp
rpcs3/Crypto/unself.cpp

I really have no idea what rap files are, but this makes my Warhawk demo work.

Look for rap file for network license

---

rpcs3/Emu/RSX/Common/texture_cache.h

Fixes https://github.com/RPCS3/rpcs3/issues/8743

rsx: Release misconfigured texture memory before attempting reupload

---

Utilities/File.cpp

FindFile API was not capable of handling drives directly, use the old API instead.
Fixes https://github.com/RPCS3/rpcs3/issues/8896

Win32 FS: Fix fs::stat for drives

---

rpcs3/Emu/Cell/Modules/cellGame.cpp

Fix cellGameBootCheck PARAM.SFO reads

---

rpcs3/rpcs3qt/game_list_frame.cpp
rpcs3/rpcs3qt/gui_application.cpp
rpcs3/rpcs3qt/persistent_settings.cpp
rpcs3/rpcs3qt/persistent_settings.h

Qt: Fix playtime datatype

---

rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp

They are mostly "boring" channel counts as their value is constant but might as well implement them.

SPU: Implement many missing channel counts

---

rpcs3/Loader/TRP.cpp

Only affects cases where you do not have trophies installed.

Trophy fixup

---

rpcs3/rpcs3qt/emu_settings.cpp

The findData() on the invalid value correction wasn't working, and was still returning -1.
This was then used in the enable_buffering lambda as the IndexChanged callback, and throwing the Assert.
Have replaced this usage with a lambda to manually find the appropriate entry.  Since we localise the text displayed, neither findData nor findText of the combo box did the job.
I haven't touched the is_ranged use of findData.
Fixes #8971

GUI: Fix exception on invalid AudioRenderer

---

rpcs3/Emu/Cell/Modules/cellSearch.cpp

It was completely redundent to use xxhash here.

cellSearch: use std::hash

---

Utilities/File.cpp
Utilities/File.h

Do not decay array to pointer.

Fix fs::delim type, fix "." and ".." processing in fs::get_parent_dir

---

rpcs3/Emu/Cell/Modules/cellGame.cpp

Idk if this improves any game, but it seemed reasonable.

cellGameSetParamString: fix string sizes

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp
rpcs3/Emu/Cell/lv2/sys_fs.h
rpcs3/Emu/VFS.cpp
rpcs3/Emu/VFS.h
rpcs3/Loader/TRP.cpp

Also fix edge case bug in trophy initialization.

Improve mountpoint detection

---

rpcs3/Emu/Cell/lv2/sys_fs.cpp

Fixes https://github.com/RPCS3/rpcs3/issues/9026

[HOTFIX] sys_fs: return ENOENT for relative paths

---

rpcs3/Emu/Cell/Modules/cellSpurs.cpp

Fix GCC compilation

---

rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/cellSpurs.h
rpcs3/rpcs3qt/kernel_explorer.cpp

kernel-explorer: Initial SPURS debugger

---

rpcs3/Emu/Cell/PPUModule.cpp

* Makes filesystem not think it has some unique huge file extensions when the image name has "." in it. (very common case)
* Show only the original filename and not the original full path of it (which can be relatively long and full of unicode backslashes).
* Force file extension to be ".elf".
* Remove string truncation if filesz does not allow it - I encountered some cases where this truncation is not intented and the final image name would appear cut off.
* Use '_' instead of '-' to separate filename and hash.
Before:
After:

Prettify SPU image name of dumped images

---

Utilities/JIT.cpp
Utilities/JIT.h
Utilities/mutex.cpp
Utilities/mutex.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/cellSpurs.h
rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_reservation.h
rpcs3/Emu/RSX/rsx_methods.cpp
rpcs3/rpcs3qt/cheat_manager.cpp

~~Unfinished, test only with TSX enabled.~~

Make TSX Work Once Again

---

Utilities/Thread.cpp

Also add size of data being accessed in access violation in log.

SPU: Fix minor segfaults

---

Utilities/asm.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Cell/lv2/sys_fs.cpp

Please test with TSX (not sure which games).

Implement some SPU events, bonus statistics and bugfix

---

rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp

Not everything worked as expected, you know.

Late night fixup for #9070

---

Utilities/JIT.cpp
Utilities/JIT.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp

It was my fault it seems.
Also made a new memory manager for asmjit-generated functions.

Fix "Accurate PPU Reservations"

---

rpcs3/Emu/Cell/Modules/cellSpurs.h
rpcs3/rpcs3qt/kernel_explorer.cpp

Improve SPURS debugger

---

rpcs3/Emu/perf_meter.hpp

Shouldn't really be an issue but let's avoid this scenario.

Hotfix for startup crash

---

rpcs3/Emu/Cell/SPUThread.cpp

After fixing SPU loads and stores in Ghidra scripts.. I've noticed that memory that is referenced outside of saved segments is not allowed and does not appear in decompiler output because of this.
Revert the optimization that only saves non-zero segments, save the entire 256kb LS as one segment.
If you already have such old "broken" image you can open it in rpcs3 and recapture it using this version and so on.

SPU: Save LS capture executable in one segment

---

rpcs3/Emu/Cell/SPUThread.cpp

Try to find function entry point of where current PC is at.
Fixes garbage function and code analysis because of illegal function entry in disassemblers.

SPU: Fix LS capture entry point

---

rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp

Improving CPU flags

---

Utilities/BEType.h
Utilities/types.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/util/atomic.cpp
rpcs3/util/atomic.hpp

~~Creating PR since compilers are mean. I will rename it later and add something useful.~~

Fixup for incorrect cpu_flag::temp usage assertion

---

.ci/setup-windows.sh

Forgot to set on #9124, my bad

ci: Set glslang checksum back to auto-builds

---

rpcs3/Emu/Io/PadHandler.cpp
rpcs3/Input/ds4_pad_handler.cpp
rpcs3/Input/ds4_pad_handler.h

This may help in finding DS4 connectivity issues

DS4: Add error logging and remove some unused code

---

rpcs3/util/atomic.hpp

Fixes load after load, store after store ordering.

atomic.cpp: fix memory ordering loads and release stores

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp

This reverts commit ff550b5c3cd819bd1938c66835c0dc4fb0adf5cd.
Broken commit, no time to debug.

Revert "TSX: adjust transaction logic"

---

Utilities/JIT.cpp
Utilities/JIT.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/PPUThread.h
rpcs3/Emu/Cell/RawSPUThread.cpp
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Cell/SPUThread.h
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/perf_meter.hpp
rpcs3/rpcs3qt/cheat_manager.cpp
rpcs3/util/logs.cpp

Salvaged some changes from faulty commit.
Improves some SPURS test values, although not much.

TSX tweaks

---

rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h

Tentative, please test and report if something similar still happens in other games.

Fix Skate 3

---

rpcs3/Emu/Cell/PPUThread.cpp

Make reservation load a simple load from memory when "Accurate PPU reservations" is off, this does not affect its actual accurcy though.
Reservation failures are extremely rare on PPU and shouldnt be optimized for it with the downside of making reservation success slower.

PPU: Optimize reservation load for success

---

rpcs3/Emu/RSX/rsx_methods.cpp

Fix maximum conatnts loaded.
Fixes https://github.com/RPCS3/rpcs3/issues/9009

rsx: Fix transform contants load

---

rpcs3/rpcs3qt/settings_dialog.cpp

Qt: Fix Resolution combobox default value

---

rpcs3/Emu/Cell/Modules/cellSysutil.cpp
rpcs3/Emu/Cell/Modules/cellSysutil.h
rpcs3/Emu/Cell/Modules/cellSysutilMisc.cpp
rpcs3/Emu/system_config.h
rpcs3/rpcs3qt/emu_settings.cpp
rpcs3/rpcs3qt/emu_settings_type.h
rpcs3/rpcs3qt/settings_dialog.cpp
rpcs3/rpcs3qt/settings_dialog.ui
rpcs3/rpcs3qt/tooltips.h

@AniLeo are you sure that this is correct?

Add License Area Setting

---

Utilities/JIT.h
Utilities/asm.h
rpcs3/Emu/CPU/CPUThread.cpp
rpcs3/Emu/CPU/CPUThread.h
rpcs3/Emu/Cell/Modules/cellSpurs.cpp
rpcs3/Emu/Cell/Modules/cellSpursSpu.cpp
rpcs3/Emu/Cell/PPUThread.cpp
rpcs3/Emu/Cell/SPUThread.cpp
rpcs3/Emu/Memory/vm.cpp
rpcs3/Emu/Memory/vm_locking.h
rpcs3/Emu/Memory/vm_reservation.h
rpcs3/Emu/System.cpp
rpcs3/Emu/System.h
rpcs3/Emu/system_config.h

I have rewritten logic for transaction fallback. Now it's based on wasted time, not some weird flags or useless counters. Or useless flags or weird counters? Doesn't matter.

TSX is not dead yet

---

rpcs3/Emu/Cell/SPUDisAsm.cpp
rpcs3/Emu/Cell/SPUDisAsm.h
rpcs3/Emu/Cell/SPURecompiler.cpp
rpcs3/Emu/System.cpp

e.g. from insertion mask creation instructions.

SPU Debugger: SHUFB insertion patterns
