RPCS3/rpcs3

- rpcs3/rpcs3qt/update_manager.cpp
Replace GetEmuDir() with GetExeDir() in handle_rpcs3. If RPCS3_CONFIG_DIR is set, the update will be extracted there, and not in the exe folder.
Not sure on how to test this, though.
> Fix auto updater when RPCS3_CONFIG_DIR is set

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/cg_disasm_window.cpp
- rpcs3/rpcs3qt/cg_disasm_window.h
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/log_viewer.cpp
- rpcs3/rpcs3qt/log_viewer.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/syntax_highlighter.cpp
- rpcs3/rpcs3qt/syntax_highlighter.h
Adds a rudimentary log viewer with color highlighting.
I'll add a search tool later.
Let's see if this builds at all first.
> GUI: initial log viewer

- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Disable features still unimplemented by lavapipe when using it:
- samplerAnisotropy
- shaderStorageBufferArrayDynamicIndexing
- wideLines
as of mesa 21.1.0-dev (aea36ee05e9, 2020-02-10)
Ideally we also need to disable Anisotropic Filtering on runtime in order to not violate Vulkan spec, but it works as is for now
Some games work such as Demon's Souls and Drakengard 3 (tested on mobile i7-6700HQ)
Naturally, as lavapipe improves, so will performance
Partially solves #9642 as lavapipe is Mesa's software mode Vulkan driver
> vk: Support incomplete lavapipe

- rpcs3/Emu/RSX/Common/ProgramStateCache.h
This offers a huge improvement in startup performance. With around 13,000 shaders we go from ~1:30 to under 10 seconds. It looks like this was the original intention of the author given the outer scope recompile variable.
> Fixup for multi-thread shader compilation (loading stage)

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
What is a PRX file? PRX stands for "PPU Relocatable Executable". What "relocatable" means in this context you ask? it means that the data/code segments of the PRX file can be mapped at any given address as long as the address is free from another memory mapping. Because every single PS3 application has different memory layout (it can even change within different boots of the same application!) we need PRX patches to be able to exist at any address based on relative offsets from segments instead of hardcoded addresses. This is fixed by this pull request.
* Make PRX patches relocatable as they should.
* Due to the changed control for PRX patches depending of knowing the segments addresses, I made them display in kernel explorer.
* Added patch validation checks for PRX segments bounds. …
> Reimplement/fix PRX patches

- rpcs3/Emu/Cell/lv2/sys_process.cpp
Emu.CallAfter only queues a signal to stop the emulator, keyword is **queues**. There could have been a signal to stop the emulation and then even rerun it before the signal from PPU was executed.
So check if a stop signal was not issued already by checking PPU caller thread state.
> Fix PS3 process exit/exitspawn

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Loader/ELF.h
* Clear elf_object and decrypted file memory before compiling PPU LLVM cache.
* Set initial error of elf_object to "file not found" instead of no error as it makes more sense.
> PPU LLVM: Reduce PRX/OVL compilation memory usage a little

- rpcs3/Emu/Cell/PPUThread.cpp
* Never display a newline because it breaks the constant placement of registers. (treat it as null terminator)
* Restrict text to contain only printable characters.
* If text ends with newline allow its size to be one character only because the chances of it being valid text are high.
> debugger: Improve PPU string constraints

- rpcs3/Emu/Cell/PPUModule.cpp
* Add SPRX/OVL filenames to the log messages.
* Make the log messages' level warning when no patches were applied. This makes the ones with patches applied much more noticeable as they should.
This should resolve all the confusion around it.
For example:
```
S {PPU[0x1000000] Thread (main_thread) [0x008a09ac]} PAT: Applied patch (hash='PRX-rbYkgZMgx8Prd7WUAA39oYAdWcNo-0', description='cellSpurs urgent commands hack - Metal Gear Solid 4', author='elad335', patch_version='1.0', file_version='1.2') (<- 1)
S {PPU[0x1000000] Thread (main_thread) [0x008a09ac]} ppu_loader: PRX hash of libsre.sprx[0]: PRX-rbYkgZMgx8Prd7WUAA39oYAdWcNo-0 (<- 1)
W {PPU[0x1000000] Thread (main_thread) [0x008a09ac]} ppu_loader: PRX hash of libsre.sprx[1]: PRX-rbYkgZMgx8Prd7WUAA39oYAdWcNo-1
```
> Update log messages of PPU/SPU hashes and patches applied

- rpcs3/Emu/Memory/vm.cpp
Handle unaligned addresses properly.
Fixes #9763
> Fix vm::falloc()

- .gitignore
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/instance.hpp
- rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp
- rpcs3/Emu/system_config.h
This is helpful for people streaming RPCS3, or to prevent disabling HDR mode in Windows.
Fixes #7975
New option is under `Vulkan` section of config.yml, it is disabled by default to maintain current behavior.
```yml
Video:
Vulkan:
Force Disable Exclusive Fullscreen Mode: false
```
People with multimonitor setup should test if switching to full screen works on different screens as expected.
> Add a new config-only option to prevent exclusive full screen mode

- rpcs3/main.cpp
In the intial log message, emphasize the fact that there is no firmware installed instead of not logging anything.
> Log "Missing Firmware" if firmware is missing

- Utilities/JIT.h
- rpcs3/Emu/Cell/PPCDisAsm.h
- rpcs3/Emu/RSX/VK/VKCommonDecompiler.cpp
- rpcs3/Emu/RSX/VK/VKMemAlloc.cpp
- rpcs3/cmake_modules/ConfigureCompiler.cmake
- rpcs3/rpcs3qt/custom_table_widget_item.h
- rpcs3/rpcs3qt/log_frame.cpp
> Add error on missing 'override'

- rpcs3/Emu/system_config.h
"@@@" is used as a separator not ';'.
> Fix mic device default in config

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/rpcs3qt/debugger_frame.cpp
Fixes single stepping inside PPU syscalls, manually set PPU breakpoints, SPU stop opcodes, RSX idle modes and many more due to flawed single stepping mechanism globally.
> debugger: Fix single stepping (globally)

- rpcs3/util/asm.hpp
* Do not use value + nonzero as it can overflow if dectype(value) is u64 or s64.
* Negating minimum negative values does not work and results in the same value, do not do that.
> Fix potential overflows in utils::aligned_div, utils::rounded_div

- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/Modules/sceNp2.cpp
- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/NP/np_handler.h
The code from sys_bnet_connect was a relic from a time when we didn't give the proper IP to the software when it requested DNS.
Added a lock to sceNpInit and other Init/Term functions to avoid concurrency(I feel some code should be pushed into np_handler for it to handle the concurrency rather than the sceNp code but for now it's still better than it was).
> Some NP fixes

- rpcs3/Emu/RSX/VK/VKDMA.cpp
Some DMA block entries are stubs whose parents are DMA_block_EXT entries. Performing load() in this case becomes a memcpy(address, same_address_again, length) which wastes performance and introduces bugs.
Improves performance when using passthrough DMA. I've only tested on an AMD GPU, NV GPUs have other more complicated issues with passthrough that are still being worked on behind the scenes.
> vk: Fix cyclic read-write in dma_block::load/flush

- rpcs3/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds3_pad_handler.h
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
Calls hid_enumerate periodically and updates the virtual DS4 list accordingly.
In order for this to work, I had to change the logic a little bit to always register 7 vitual DS4 controllers in the handler.
Currently, devices will be assigned to the 7 slots based on the order of enumeration, and whenever a device is disconnected, its slot gets unoccupied and is free to connect to the next unknown device.
Controllers that stay connected should not change positions.
This can probably be improved by additionally saving the serial/path to the config in the future.
fixes #9130
> DS3/DS4/DualSense: enumerate devices periodically

- rpcs3/Emu/RSX/VK/VKDMA.cpp
- rpcs3/Emu/RSX/VK/VKDMA.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/instance.hpp
- rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp
This is part of the long series of upcoming PRs that lay the foundation for some features just coming out of development. This is part 2 of many, first part was already committed (DMA bugfix)
- Clean up some DMA leftovers
- Refactor device and swapchain handling to support creating separate hw transfer queue. Not used in this PR.
> vk: Refactor device handling

- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/rpcs3qt/gui_application.cpp
It's a bit mysterious, but the confirmation box doesn't like being called in this mode.
So let's just return false.
> fix no-gui crash if no firmware was installed

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Loader/ELF.h
- rpcs3/Loader/PSF.cpp
- rpcs3/Loader/PSF.h
- rpcs3/Loader/TRP.cpp
- rpcs3/rpcs3qt/emu_settings.cpp
* Fix all the Loader/PSF.cpp assertations for newly created/overwritten PARAM.SFO from this pr and on, old corrupted PARAM.SFO will still trigger assertations and should be deleted manually.
Example for the assertation: https://discord.com/channels/272035812277878785/277227681836302338/812657008779329537
* Fix atomicity of savedata/trophy data writes, add missing file buffers flushing.
* Write SPU and RSX captures attomically.
> Atomic PARAM.SFO modifications

- rpcs3/Emu/NP/rpcn_client.cpp
Closes https://github.com/RPCS3/rpcs3/issues/9821
Bug introduced by https://github.com/RPCS3/rpcs3/pull/9813 as rpcn_client is used outside game emulation when registering.
> Fix rpcn registration

- Utilities/CPUStats.h
- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.h
- The frametime_timer was restarted at the end of the update method, instead of immediately after reading its value.
This means that the frametime was lower than expected when an expensive task was executed in-between.
The main culprit for the spikes is the `get_thread_count` method, which is very slow on windows at least.
It takes a couple of ms and therefore caused a decrease in elapsed_time for one cycle.
- The perf_metrics_overlay didn't handle the visible flag properly. So let's return an empty compiled_resource in get_compiled.
- Fixed a division by 0 that could cause some random inf to suddenly appear and mess up the graph.
- Fixed the body size. It was wrong for a brief period initially and after each detail level settings change.
The body was lagging behind the text. This was …
> overlays: Fix frametime graph spikes

- rpcs3/Emu/Cell/PPUThread.cpp
If liblv2.sprx is HLEd, compile_fw is true in ppu_initialize(void) resulting in directories being scanned and the PPU progress dialog is being spuriously spawn and then closes pretty fast after because there's nothing to compile. Just add a condition to not attempt to call any precompilation related code when using interpreters.
> Minor GUI fix for PPU interpreter at "precompilation"

- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/rpcs3qt/save_data_dialog.cpp
Most Emu.CallAfter usages were extremely wrong when ordered after Emu.Stop(). could result in anywhere from emulation stopping hangs to even segfaults. I implemented a condition to only call callback if Emu.Stop/Emu.Run were not called inbetween enqueuing the callback to the GUI thread actual execution.
> Even more emulation stopping bugfixes (GUI callbacks)

- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/util/cpu_stats.cpp
- Fixes updating cpu usage in performance overlay during low detail mode
- Fixes division by zero in cpu_stats::get_usage (maybe the logic is wrong anyway)
> Fix cpu usage statistics

- rpcs3/Emu/System.cpp
This is the proper way to do it for when Emu.CallAfter is called by emulation threads as Emu.Stop can execute concurrently with it waiting for them to finish.
> Tiny Emulator::CallAfter condition fix

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKHelpers.h
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/VK/vkutils/commands.cpp
- rpcs3/Emu/RSX/VK/vkutils/commands.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
- rpcs3/Emu/RSX/VK/vkutils/image_helpers.cpp
- rpcs3/Emu/RSX/VK/vkutils/image_helpers.h
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
Part 3 of many.
- Refactor some texture upload code to reduce size of some megafunctions
- Implement image queue family migration (acquire/release)
- Implement per-queue-family scratch buffers
- Implement explicit command pool queue family for non-graphics command buffer support.
Ideally there should be no difference compared to master, with the exception of potential very slight performance gains from the double-buffered scratch usage pattern.
> vk: More groundwork

- rpcs3/Emu/RSX/VK/vkutils/commands.cpp
Followup to previous PR. Fixes an assignment problem.
Multi-queue streams still are unused at this time.
> vk: Fix inadvertent self-assign

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/Cell/Modules/cellNetCtl.cpp
- rpcs3/main.cpp
- rpcs3/util/shared_ptr.hpp
Since it's hard and tricky to properly use lf_queue and other explicit channel mechanisms, and they weren't that great anyway.
> Add internal task queue to the named_thread

- rpcs3/Emu/Cell/Modules/cellScreenshot.cpp
- rpcs3/Emu/Cell/Modules/cellScreenshot.h
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/screenshot_manager_dialog.cpp
This PR adds all of the missing functionality of the cellScreenshot utility.
- Save cell screenshots in `/dev_hdd0/photo/<year>/<month>/<day>/` with inreasing file number.
- Add png metadata to all screenshots (if available).
- Apply the specified overlay image if possible.
> Improve cellScreenshot

- rpcs3/Loader/PUP.cpp
- rpcs3/Loader/PUP.h
- rpcs3/Loader/TAR.cpp
- rpcs3/rpcs3qt/main_window.cpp
* Fix race condition in PUP installation abortion.
* Fix freezes of emulator in case the PUP installation failed.
* Use fs::create_path as opposed to fs::create_dir as it is can create upper directories in case they are missing and is better in error handling.
* Report TAR errors on failure to create directories.
* Fix pup_object constructor to not crash on invalid PUP file header. (report an error)
* Fix pup_object::validate_hashes to not crash on invalid PUP file entries. (report an error)
* Do not call Qt functions inside a named_thread because it is wrong.
> Firmware installation bugfixes part 1

- rpcs3/cmake_modules/ConfigureCompiler.cmake
- rpcs3/rpcs3qt/config_adapter.h
- rpcs3/rpcs3qt/emu_settings.h
- rpcs3/util/shared_ptr.hpp
- rpcs3/util/yaml.hpp
Enabled -Wattributes warnings for GCC 10+. It's incomplete since it needs Clang 12 also.
> Last boss warning fix

- Utilities/Thread.cpp
Finally report which threads were failing to terminate at Emu.Stop().
> Report deadlocked thread names in failures to stop emulation

- rpcs3/Loader/TROPUSR.cpp
Do not cause trophy status file to be corrupt in case RPCS3 terminated unexpectedly when updating it, which can cause crashes on reading it and all trophies to be lost.
> Atomic trophy status updates

- Utilities/bin_patch.h
- rpcs3/Emu/Cell/Modules/StaticHLE.h
- rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
- rpcs3/Emu/Cell/Modules/cellFs.cpp
- rpcs3/Emu/Cell/Modules/cellMusic.cpp
- rpcs3/Emu/Cell/Modules/cellMusicDecode.cpp
- rpcs3/Emu/Cell/Modules/cellRec.cpp
- rpcs3/Emu/Cell/Modules/cellRudp.cpp
- rpcs3/Emu/Cell/Modules/cellScreenshot.cpp
- rpcs3/Emu/Cell/Modules/cellScreenshot.h
- rpcs3/Emu/Cell/Modules/cellSearch.cpp
- rpcs3/Emu/Cell/Modules/cellWebBrowser.cpp
- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Input/pad_thread.h
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/util/fixed_typemap.hpp
Require objects in g_fxo (singletons with lifetime equalling emulated process) to be non-copyable (move is still allowed).
I noticed most of them are immovable anyway due to the presence of atomics and mutexes of sorts.
If accidental copy happends, it may be pretty bad with this design since it will be undesired but unnoticed.
> fixed_typemap.hpp: make it a bit fool-proof

- rpcs3/Emu/Cell/SPUThread.cpp
cmp_rdata and mov_rdata are using `__attribute__((always_inline))`,
without inline, that is not supported on current g++ (see #1546).
Moreover `__attribute__((always_inline))` is a noop if used without inline so
just remove it.
A proper fix is to move the 2 functions in an header file as static
(with FORCE_INLINE) so it can be correctly inlined by the compiler.
```
/home/tredaell/dev/sources/fedora-copr/rpcs3/rpcs3/rpcs3/rpcs3/Emu/Cell/SPUThread.cpp:195:13: warning: 'always_inline' function might not be inlinable [-Wattributes]
195 | extern void mov_rdata(spu_rdata_t& _dst, const spu_rdata_t& _src)
|             ^~~~~~~~~
/home/tredaell/dev/sources/fedora-copr/rpcs3/rpcs3/rpcs3/rpcs3/Emu/Cell/SPUThread.cpp:139:13: warning: 'always_inline' function might not be inlinable [-Wattributes]
139 …
```
> SPUThread.cpp: remove "__attribute__((always_inline))"

- rpcs3/Emu/Io/pad_config.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
Pad Settings Dialog:
- Fixed wrong battery indicator state under certain circumstances
DS3/DS4:
- Fix possible cause for input lag: Battery LED was always updated.
- fixes #9878 
DualSense:
- Read DualSense Firmware and Hardware versions.
- Read DualSense battery levels.
- Add DualSense Battery Level LED indicator
> Input: DualSense battery level LED indicator and other fixes

- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/tooltips.h
* Install PS3UPDAT.PUP at the spot when booting games whenever firmware is missing. The option to boot games without firmware is still supported when all firmware SPRX are HLEd in firmware settings.
* Pop-up a confirmation dialog in firmware installation if firmware is already installed and log it.
> GUI: Improve missing firmware handling

- rpcs3/Input/dualsense_pad_handler.cpp
Small hotfix for DualSense:
The LED was not properly initialized when connecting a DualSense ingame.
> DualSense: Fix initial ingame LED update

- rpcs3/util/sysinfo.cpp
* Do not crash on invalid file contents.
* Do not crash on unexpected file.open() error.
> Fix utils::get_firmware_version()

- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/main.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/update_manager.cpp
- If the .exe path contains spaces, execl does convert it to several args. So let's not pass the exe as arg0
- Clean up the emulator before rebooting during an update. This may fix some crashes.
- Don't allow updates while ingame.
> Fix updater bugs

- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.h
I found out that I still had this code lying around somewhere.
- Adds the battery level of XInput controllers to the pad settings dialog. Please test.
> Input/Qt: implement XInput battery level

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.h
implements #9919
- Changes "Configure Game Patches" to "Manage Game Patches"
- Expand the matching entry for the game version when you click "Manager Game Patches"
- Expand the "All Versions" entry if the version was not found
> patch_manager: expand first search results

- rpcs3/Emu/RSX/VK/VKDMA.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
Possible workaround for #9901.
The chip table edit is quick and dirty, since I'm unsure how to figure it out since from what I've seen the IDs overlap between desktop chips which are fine.
EDIT: seems like I got all the mobile chips into the table.
> Possible workaround for mobile Kepler chips

- rpcs3/Emu/Cell/SPURecompiler.cpp
Rearranges the FM instruction to allow the comparisons and the multiplication to be processed in parallel. This doesn't save any instructions, but still results in a speedup.
In the mandelbrot homebrew performance increased from 120 --> 122fps on my 7700K at 5ghz.
On a cpu with more out of order execution resources available, such as my i5-1135G7 at 2.6ghz performance was increased from 69 --> 74fps.
> SPU LLVM: Rearange FM instruction for better performance

- bin/GuiConfigs/Envy.qss
- bin/GuiConfigs/Skyline (Nightfall).qss
- bin/GuiConfigs/Skyline.qss
Corrects the missing color highlights from the currently executing instruction and the breakpoints. Affected stylesheets are `Envy`, `Skyline`, and `Skyline (Skyfall)`. Also fixes the notice-level log message color in the `Skyline` theme.
Fixes #9930
> stylesheets: fix debugger instr coloring (and then some)

- rpcs3/rpcs3qt/render_creator.cpp
Do not terminate RPCS3, set vulkan flag to unsupported state.
When Vulkan is not working properly due to faulty drivers a segfault can happen in Vulkan code, so fallback to openGL.
See https://discord.com/channels/272035812277878785/277227681836302338/818756194135048213
> Workaround segfaults in Vulkan enumeration thread

- rpcs3/Emu/RSX/VK/VKDMA.cpp
Var chip is only used in the WIN32 ifdef block
move it there to silence the compiler warning 'bout
unused variable.
> Move the chip var to the ifdef block

- rpcs3/Emu/Cell/PPUModule.cpp
Should help with identifying module functions in IDA etc.
> Loader: Log FNID of imported/exported functions

- rpcs3/Emu/RSX/GL/GLOverlays.cpp
- rpcs3/Emu/RSX/Overlays/overlay_controls.h
- rpcs3/Emu/RSX/Overlays/overlay_edit_text.cpp
- rpcs3/Emu/RSX/Overlays/overlay_list_view.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
Currently, the pulse in the native UI is continuous and provides a rather bad user experience.
Sometimes it's hard to see that you selected a different element if the pulse glow is currently at 0.
This PR improves this behaviour by immediately highlighting the current element after a user interaction.
Technically this is achieved by resetting the sinus curve, using an individual offset for each element.
The offset is calculated with the current time and a hardcoded speed modifier.
The sinus reset values are kinda half assed and it would probably be easier to understand if we use cos.
Since the time is taken twice (once when setting the offset and once when drawing the elements) it won't be 100% accurate, but this should not be noticeable by any human being.
This affects the
- **OSK keys** …
> Overlays: Implement individual element pulse

- Utilities/Thread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/fatal_error_dialog.cpp
- rpcs3/rpcs3qt/fatal_error_dialog.h
- rpcs3/util/logs.cpp
* If thread is unnamed, keep log name empty for main thread, otherwise print thread id. In fatal dialog, main thread is handled with special remark that it's main thread.
* Always print thread id in fatal dialog, regardless of thread type.
> Add information about unnamed/main threads in logs and fatal dialog 

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.cpp
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.h
- rpcs3/Emu/RSX/VK/VKDMA.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKHelpers.h
- rpcs3/Emu/RSX/VK/VKResourceManager.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
- rpcs3/Emu/system_config.h
- rpcs3/Emu/system_config_types.cpp
- rpcs3/Emu/system_config_types.h
- rpcs3/VKGSRender.vcxproj
- rpcs3/VKGSRender.vcxproj.filters
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Adds remaining pieces for separate upload path vs 3D rendering. Disabled by default as it still needs to be tuned.
Since passthrough DMA is fixed on NVIDIA when not using separate paths, this technically solves the NVIDIA DMA regressions but probably costs some performance.
> [TESTERS NEEDED] vk: Add remaining pieces

- rpcs3/Emu/Cell/lv2/lv2.cpp
* Previously, when a PPU thread was paused by the debugger, it could not process PPU scheduler events properly. As a result when pausing a single PPU *which was running* all other PPUs were stopped as well which is not intended.
> debugger: Fix PPU threads pausing

- rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- rpcs3/rpcs3qt/main_window.cpp
* When Emu.Stop() is called by GUI thread, PPU threads should still be able to send sysutil events.
* Reset main_window::m_sys_menu_opened at Emu.Stop().
* When sysutil_cb_manager is not initialized in FXO, sysutil_send_system_cmd would invoke UB.
> Fix sysutil_send_system_cmd at Emu.Stop()

- rpcs3/Crypto/unself.cpp
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/rpcs3qt/main_window.cpp
* When attempting to either drap-and-drop or install uppercase RAP files from menu, detect it as RAP file (instead of trying to execute it as a PS3 executable) and rename extension to be lowercase ".rap" automatically.
This is a quality of life improvement. Especially on Windows which on atleast on my Windows 10 and exFAT does not let me rename files if the only difference with its new filename is its characters' case, probably a broken "optimization" of File Explorer which attempts to detect same name before rename and avoids rename is such case. FYI to workaround this bug of File Explorer you need to rename the file to something different (so characters case would not be the only difference) and only then rename it to the final name.
* Handle all PUP files in drag-and-drop, not just …
> GUI: Handle uppercase RAP file extension

- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
and refactor icon import.
- fixes aspect ratio of shader loading backgrounds
- fixes game icon canvas size. The calculations were wrong:
> Qt: Import Custom Shader Loading Icons

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/Turntable.cpp
- rpcs3/Emu/Io/Turntable.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
This adds emulation of the DJ Hero Turntable controller using inputs from controller 7. This allows DJ Hero 1 & 2 to be playable with controllers other than a real PS3 turntable, including KB&M, gamepad, and other console turntables.
Based on #7336
Fixes #9111
Bindings are loosely based on Xbox 360 turntable bindings.
Platter buttons are bound to Pad 7 cross/circle/square. This is fine because turntable controllers double-bind platter buttons to both cross/circle/square and dedicated platter button inputs.
Standalone face buttons are not commonly used in DJH games, but are still required (at least Cross is needed for skipping Tutorial dialogue & performing DJH2 calibration), so standalone face buttons are bound to Pad 7 R1/L1/R2.
Known quirks:
* DJ Hero 2 accepts inputs from both pad & …
> sys_usbd: DJ Hero Turntable Emulation

- Vulkan/spirv-tools-build/spirv-tools-build.vcxproj
> SPIRV: disable error on warnings

- Utilities/File.h
* If pos() is greater than size at the time of writing, allocate new memory only once instead of twice.
> Improve fs::container_stream::write

- rpcs3/Emu/Cell/PPUThread.cpp
Do not lose important debugger output such as the inlined memory viewer and string viewer with register panel values for modified syscall arguments.
> PPU Debugger: Fixup for syscall arguments

- rpcs3/Emu/Cell/Modules/cellFs.cpp
- rpcs3/Emu/Cell/Modules/cellSysCache.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/VFS.cpp
* Much alike the fixes in #9819, commit gamedata directory creation with its contents atomically by flushing contents to disk before rename.
Just here there is a catch, in Win32 path I inserted the sync() inside sys_fs for gamedata write operations. I've read you can achieve similar action an POSIX's syncfs by passing a file handle to a volume to FlushFileBuffers but only with Admin rights. I wonder if we can workaround that in the future.
* ~~Fix sys_fs_fsync and sys_fs_fdatasync for read-only filesystems such as /dev_bdvd, do not crash, return an error as it should.~~
> Make gamedata installation truly atomic as real PS3

- rpcs3/Loader/PUP.cpp
- rpcs3/Loader/PUP.h
- rpcs3/Loader/TAR.cpp
- rpcs3/Loader/TAR.h
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/main_window.ui
* Implement full extraction of PS3UPDAT.PUP.
* Implement TAR extraction via GUI.
* Use VFS to implement missing PS3 filesystem characters escaping.
* Use VFS to error on illegal paths. (illegal paths such as malware pointing to "/../../..and so on../C:/Windows")
* Do not crash on missing 0x100 and 0x300 PUP file entries.
* Fix overflow in file-size against header check.
* Add new PUP error types and descriptions.
* Report an error on missing PUP package inner files.
* Move all header errors to pup_object class.
* Move verbose error descriptions to pup_object class.
Implements step 1 and 2 of #9905
> GUI: Implement full extraction of PUP and improve installation error handling

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm.h
It was 1mb due to default initialized flag which is wrong.
> Fix SPU mapped memory page size

- rpcs3/main.cpp
It seems that this option escaped setting windows timer resolution to 0.5 ms.
> Workaround poor performance in --no-gui mode (Win32)

- rpcs3/Crypto/unpkg.h
- rpcs3/main.cpp
- rpcs3/rpcs3qt/game_compatibility.cpp
- rpcs3/rpcs3qt/game_compatibility.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/pkg_install_dialog.cpp
- Adds --installpkg cli option (can handle a single path).
- Adds a missing check when passing crap to the package installer
fixes #5374
> Qt: Allow package installation through cli

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
It seems like this got mixed up somehow.
Maybe I should change the help description instead @elad335 ?
> Qt: Fix debugger step shortcuts

- rpcs3/rpcs3qt/memory_string_searcher.cpp
- rpcs3/rpcs3qt/memory_string_searcher.h
* Search the entire PS3 4GB address space instead of a small area of memory which is meant mostly for PRX/SELF memory aka vm::main segment. This limitation rendered string searcher nearly useless.
* Implement hexadecimal byte-string, hexadecimal integer, float and double value search formats.
* Multi-thread searching.
* Optimize searching algorithm vastly.
* Fix crash on empty string, report an error.
* Implement case-insensitive string search.
> Memory string searcher improvements

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/save_data_list_dialog.cpp
- rpcs3/rpcs3qt/settings.cpp
- rpcs3/rpcs3qt/settings.h
- rpcs3/rpcs3qt/user_manager_dialog.cpp
If you currently remove a custom name and already had a deprecated name before, you'll never get rid of it.
This applies to all of the deprecated settings.
> Qt: prepare for removal of deprecated GUI settings

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Loader/ELF.h
- rpcs3/Loader/PUP.cpp
- rpcs3/Loader/TROPUSR.cpp
- rpcs3/Loader/TRP.cpp
* Do not crash if memory allocation size is too high in resize() because of an invalid argument in file header. This is especially important in ELF loader because we scan random memory unconditionally looking for SPU images to patch and the slightest corrupted image could crash the emulator. Same goes for TRP and TROPUSR loaders. Similar checking was implemented in PUP loader.
> Improve ELF/Trophy loader's error checking

- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings.h
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Let's the user decide if they want to remove unused config entries from old builds. (Or maybe garbage)
I don't really like that it asks when saving.
Maybe it should ask when opening the dialog instead.
closes #9981
> Qt: Remove unused GUI entries when saving a config

- rpcs3/main.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_application.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
The updater will be hidden if RPCS3 is booted with any command line argument that may invoke Emu.Boot
closes #6839
> Qt: don't show updater if booted with cli arg

- rpcs3/rpcs3qt/emu_settings.cpp
Fixes a bug that causes custom configs to inherit obsolete settings of the global config.
This should not affect its own existing obsolete settings.
> Qt: clean global cfg before adding custom cfgs

- rpcs3/rpcs3qt/find_dialog.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
Some informational messages kept spamming the log since we now have a bunch of multithreaded operations like shader generation.
Having the option to remove the log prefix from the view seems like the obvious choice to me, as it has several advantages:
1. Faster log_frame. The less text we write to the gui the less work our cpu needs to do.
2. Less visual clutter. Most people don't need to know the details that are present in the prefix.
3. Certain messages can stack up again. Previously they were unique due to their thread ID.
I defaulted this to hide the prefix. Developers or anyone who needs it can just enable it in the log frame (saved in GuiConfigs).
> Qt: add option to hide the log prefix

- rpcs3/main.cpp
While reading through some issue (#9554 ) I noticed that we were only accepting integer values for QT_SCALE_FACTOR_ROUNDING_POLICY (cli arg --dpi-rounding).
So let's also accept the string versions.
> Qt: Properly set QT_SCALE_FACTOR_ROUNDING_POLICY

- rpcs3/rpcs3qt/fatal_error_dialog.cpp
> Qt: add AppIcon to fatal_error_dialog

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/GDB.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
* In ready state emulator threads such as of FXO were running due to flawed pause check, so check ready state as well.
* Solve minor race between IDM cpu_thread constructor and Emulator::Pause.
* Solve minor race between IDM cpu_thread constructor and Emulator::Stop.
* Do not obey auto-exit setting after creating firmware cache.
> Fix Emulator::IsPaused()

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
Previously RSX waited until PPU called sys_rsx syscalls to compile shaders, then it let SPU and PPU run at fullspeed when doing so which can choke CPUs with not many threads.
This is also a bug which can cause timeout assertations from CELL side at startup due to RSX not responding for long period of time at startup when compiling shaders. (emulation must not observe the time in which RSX compiles shaders)
To solve it compile shaders before CELL is running, do not wait for PPU to execute some syscall. In fact now PPU will wait until RSX has been fully initialized to execute any stuff.
> rsx: Compile shaders when CELL is not running

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h
- rpcs3/Emu/System.cpp
Show native overlay for ingame ppu and spu module compilation.
A good testcase is NGS2.
~~This does not affect the initial ppu/spu compilation before the game starts, as I haven't figured out how to draw overlays before the rsx was initialized.~~
TODO:
> Emu/overlay: ingame native overlay PPU compilation

- rpcs3/Emu/System.cpp
Users were reporting crashes in System.cpp line 1689 if Emu.Pause is called inbetween, fix that, and fix missing firmware dialog to also show when auto-start setting is disabled.
> Fix #9879 and fix firmware confirmation dialog when auto-start is disabled

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
ctrl+B invokes new breakpoints settings window with a setting to alter default breakpoint behavior. When unchecked: only the hitted thread will be paused (previous breakpoints behavior). When checked (the new default): the emulatoion will paused entirely on such case.
> debugger: Implement ability to pause entire emulation on breakpoint

- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/headless_application.cpp
- rpcs3/main.cpp
- rpcs3/main_application.cpp
- rpcs3/main_application.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/user_account.cpp
- rpcs3/rpcs3qt/user_account.h
- rpcs3/rpcs3qt/user_manager_dialog.cpp
- rpcs3/rpcs3qt/user_manager_dialog.h
- Let the user boot RPCS3 with any valid user-id (will be created if necessary)
- Adds stricter error handling when setting a new user
- Fix a possible crash if the emulator is Quit before being initialized (usually unreachable code)
closes #10052
> cli: set user-id per command line

- rpcs3/rpcs3qt/main_window.cpp
> Set userland firmware SPRX directory as the default PS3 decryption tool path

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/Cell/lv2/sys_process.h
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.h
- rpcs3/Emu/Cell/lv2/sys_sm.cpp
* Probably a limitation of vsh.self loader itself, it does not load imports/exports nor its information is recorded within its ELF sections. What vsh.self does is to load it manually via a previously unimplemented syscall.
* Do not require special settings to load VSH such as Debug Console Mode or HLE liblv2.sprx.
Gets it to further to execute sys_rsxaudio stuff.
> Fix vsh.self imports/exports and more improvements

- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h
- rpcs3/Emu/System.cpp
This is just a workaround, but we probably need kd to fix this properly.
fixes #10051
> hotfix: skip progress dialogs if msg dialogs are open

- rpcs3/Emu/IdManager.cpp
- rpcs3/Emu/IdManager.h
- rpcs3/Emu/System.cpp
Much simplifies multi-process and save-states support. In an ideal emulator state FXO will contain all information possible about a PS3 process.
> core: Move IDM to FXO

- BUILDING.md
Added `libqt5gui-private-headers-devel` dependency to fix `fatal error: qpa/qplatformnativeinterface.h: No such file or directory`
> Update OpenSUSE dependencies

- CMakeLists.txt
- options.cmake
Moved the CMake build options to a dedicated file. Makes
configuring build options easier when not using the CMake
GUI.
> moved build options to options.cmake

- rpcs3/Emu/Memory/vm.h
- rpcs3/util/shared_ptr.hpp
- rpcs3/util/typeindices.hpp
> More fixes for shared_ptr

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Loader/PSF.cpp
- rpcs3/Loader/PSF.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/save_manager_dialog.cpp
Previously it crashed the whole emulator if you renamed any random file to PARAM.SFO and place it inside the game/ELF directory.
Now even with hex editor modifying any bit from a valid PARAM.SFO you won't succeed in crashing the emulator. Includes checks from #9998 as well.
Reminder that games technically have permission to (over)write PARAM.SFO files bitwise in /dev_hdd0 game data directories for example so this is a fix for emulation as well. I have used this "feature" in hw tests in the past. cellGame already supports the appropriate error codes for invalid PARAM.SFO.
> Loader/cellGame: Do not crash on invalid PSF files

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Loader/PSF.cpp
Should fix #10085
Was caused by too many nested assignments which rendered it impossible to return this sort of error.
> Fixup for #10085 (PR #10041)

- rpcs3/main.cpp
- rpcs3/main_application.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/persistent_settings.cpp
- rpcs3/rpcs3qt/user_manager_dialog.cpp
- rpcs3/rpcs3qt/vfs_dialog_tab.cpp
- rpcs3/rpcs3qt/vfs_dialog_tab.h
- This fixes "Firmare missing" for users who use VFS for dev_flash
- Fixes some glitch with the VFS dir remove button. It was sometimes enabled but didn't work.
- Also removes some deprecated setting due to latest updates.
> Log firmware after Emu was initialized

- Utilities/File.cpp
- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_config.cpp
- rpcs3/Emu/system_config.h
* Windows: Fix fs::create_dir error on drives - fixes fatal error in log when setting mounted paths for /dev_hdd0 etc on root drives for example.
* Rewrite fmt::replace_all to take advantage of std::string_view.
* Ensure emulated VFS mount paths end with a delimeter because the code relies on this.
> Win32 FS: Improve fs::create_dir

- .cirrus.yml
Comment out the GitHub upload token for now, since we're not using Cirrus to upload master builds. Also Azure builds are still configured as required for PRs, someone should probably change that.
Avoids this:
> Cirrus warning fix

- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Common/TextureUtils.h
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- Removes several subtle hacks that hid the real issue. A compressed texture has more than one texel per 'block' - represent this information consistently.
- Rewrites the decompression routines for said textures to align with the correct rules.
Fixes https://github.com/RPCS3/rpcs3/issues/9757
> rsx: Fix decompression of RB_RG textures.

- rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp
- rpcs3/Emu/RSX/Overlays/overlay_controls.h
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- Fixes the enabled state of some sliders in the GUI
- Update the shader loading background dynamically. The settings were just pseudo dynamic before.
This might give some of you guys a nice distraction while waiting for ppu modules.
> overlays: update shader/ppu dialog backgrounds dynamically

- rpcs3/Emu/RSX/Overlays/overlay_controls.h
- rpcs3/Emu/RSX/Overlays/overlay_edit_text.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/osk_dialog_frame.cpp
fixes #10100
- Adds a value member to the overlay text edit in order to seperate the visible text from the actual text value
- Uses the new value member to implement a proper placeholder logic (when the text edit is empty)
- Uses the new value to implement the password mode (visible text is displayed as a string of ＊)
- Adds the password echo mode to the Qt version of the OSK dialog when single line input is used (doesn't make much sense on multi-line text edits anyway)
- Adds more auto-repeat buttons to the OSK
- Properly resets auto-repeat when a different button was pressed
> overlays: fix osk placeholder and add password mode

- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.h
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.h
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.h
- rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
- rpcs3/Emu/Cell/lv2/sys_rwlock.h
- rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
- rpcs3/Emu/Cell/lv2/sys_semaphore.h
`flags` argument affects the construction process of the object, not the object itself. Saving it is futile and only represents the value at the first time at which the IPC object was constructed.
> lv2: Remove flags from IPC-supported objects

- rpcs3/Emu/RSX/CgBinaryFragmentProgram.cpp
removed extra parentheses pair from an `ensure()`
statement in `/rpcs3/emu/RSX/CgBinaryFragmentProgram.cpp`
> [TYPO] removed extra perentheses pair

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/NP/signaling_handler.cpp
- rpcs3/Loader/PSF.cpp
- rpcs3/util/fixed_typemap.hpp
- rpcs3/util/shared_ptr.hpp
Example of a name (differs between compilers):
GCC:
``id_manager::id_map<named_thread<ppu_thread>>``
clang:
``id_manager::id_map<named_thread<ppu_thread> >``
MSVC:
``struct id_manager::id_map<class named_thread<class ppu_thread> >``
> Add debug names for objects

- rpcs3/Emu/CPU/CPUTranslator.cpp
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
This PR adds a new setting, called "Full Width AVX-512". At the moment only 512 bit wide SPU verification is hidden behind this option, but in the future more code can be put behind it. 
This code needs to be hidden behind a setting thanks to some cpus that downclock upon executing 512 bit wide AVX-512 code. While newer cpus like the 11900K don't experience any downclocking (see https://travisdowns.github.io/blog/2020/08/19/icl-avx512-freq.html), older cpus based on skylake-x will aggressively downclock, and the setting is better off for these cpus. 
Users may also prefer this option disabled if they've overclocked their CPU with a negative AVX-512 offset.
This new setting is off by default and cannot be toggled if the users cpu doesn't support AVX-512.
For an example this reduces the …
> SPU LLVM: add AVX-512 SPU verification

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/custom_table_widget_item.cpp
- rpcs3/rpcs3qt/custom_table_widget_item.h
- rpcs3/rpcs3qt/game_list.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/game_list_grid.cpp
- rpcs3/rpcs3qt/game_list_grid.h
- rpcs3/rpcs3qt/game_list_grid_delegate.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/movie_item.h
I finally transformed last year's april fools joke into a proper feature.
Since we can't have proper game videos for now, this seems like a nice workaround in the meantime.
- Allows the user to import, remove, replace, enable and disable "Hover Gifs" (Similar to the existing custom icons)
- The gifs will be played when you hover with the mouse on the gamelist icon
> Hover Gifs

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/save_data_list_dialog.cpp
- rpcs3/rpcs3qt/save_manager_dialog.cpp
This also fixes a savedata notes bug.
The detail section notes were always taken from the deprecated settings.
> Qt: remove uncritical deprecated notes and titles

- 3rdparty/libusb_cmake/config.cmake
- CMakeLists.txt
- rpcs3/cmake_modules/ConfigureCompiler.cmake
the `CMAKE_COMPILER_IS_GNUCXX` function is deprecated 
and should be replaced instead with `CMAKE_CXX_COMPILER_ID`.
> replaced CMAKE_COMPILER_IS_GNUCXX with CMAKE_CXX_COMPILER_ID

- rpcs3/Emu/Memory/vm.cpp
- rpcs3/util/vm_native.cpp
- Attempt to fix some issues on BSD.
- Document some specifics of unmap_critical on Linux/BSD/POSIX and don't call mprotect twice (for sudo mem).
> vm_native: supply only one madvise flag at a time

- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/qt_utils.cpp
- rpcs3/rpcs3qt/qt_utils.h
Fix initial game window position calculations.
fixes #10136 (probably)
> Qt: Fix initial gs_frame position on multi-monitor

- rpcs3/Emu/NP/np_handler.cpp
This line currently logs a thousand NUL characters.
Idk if this fix works. I just took RipleyTom's proposal and commited.
> fix null chars in hostname log message

- rpcs3/Emu/Cell/PPUThread.cpp
It confused people into thinking their dump is corrupted.
> Reduce precompilation failure log level (error -> notice)

- rpcs3/Emu/RSX/Overlays/overlays.cpp
Turns out there was an undocumented reason for this.
Nobody warned me that "It's a trap!".
I wonder how this hasn't summoned a shitstorm yet.
> overlays: hotfix for dialog interaction

- rpcs3/Emu/Cell/SPURecompiler.cpp
The code was broken because the constant mask for gf2p8affineqb was being passed as the first argument, instead of the second argument by accident.
It was still working in most situations because the common case where 0x80 must = 0 was correct.
> SPU LLVM: Final fixup for icelake shufb paths

- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
Prevents loss of work, hair, and life expectancy when multitasking with a text editor on the side. Happens rather often.
Fixes #10161
Shows a middle finger to #2831
> GUI: take out some unwise shortcuts

- rpcs3/Emu/Cell/SPURecompiler.cpp
Removes icelake shufb paths until I can actually verify that they work properly
Also improves byteswap elimination by using the unswapped data directly, instead of relying on llvm to cancel out 2 back to back byteswaps. 
fixes #10165
> SPU LLVM: Remove icelake shufb paths for now

- rpcs3/Emu/Cell/SPURecompiler.cpp
The constant mask was accessing bits in reverse order of what was expected, and was accidentally extracting bits from the least significant end of the spectrum, instead of from the most significant.
I tested against the spu_alu tests and everything should be perfect now.
I'm surprised that the previous version was working in any games at all.
> SPU LLVM: Absolute final fixes for icelake shufb paths

- rpcs3/Emu/System.cpp
Emulator::Load was incorrectly participating in the emulation stopping timeout detection, leading to possible "Stopping emulator took too long" errors.
> Fix emulation restart

- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_event.h
- rpcs3/rpcs3qt/kernel_explorer.cpp
Show its IPC key or ID, depends on the queue's type.
Example: `Event Port Ox0e007600: LOCAL, Name: 0, Event Queue (ID): 0x8d007500`
> kernel-explorer: Show bound queue to port information

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
Fixes broken FBO swizzle for depth textures. WDB was basically broken for these. With this fix R&C ACiT looks like a game when WDB is enabled.
> vk: Fix WDB when swizzled raster output is active

- rpcs3/Emu/system_progress.cpp
- rpcs3/rpcs3qt/update_manager.cpp
The "update available" dialog currently pops up in the center of the primary screen.
This is not what I intended and is caused by the missing progress bar dialog during these automatic checks.
You can test this by checking manually on master. It should popup correctly on top of the download progress dialog.
fixes #8752
> Qt: Fix popup position of the update dialog

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
This is likely not the best way to do this, but it seems to work 👀
> Fcntl e0000025

- .cirrus.yml
Shaves ~1 minute of build time. In the past, caching failed to prevent https://github.com/RPCS3/rpcs3/issues/9518.
> CI: don't cache downloaded packages on FreeBSD

- .ci/build-freebsd.sh
- .ci/deploy-linux.sh
- .ci/install-freebsd.sh
- .cirrus.yml
- BUILDING.md
- CMakeLists.txt
- azure-pipelines.yml
Switches to a Ubuntu 18.04 docker container for Linux builds. Now it uses GCC 10.3 and Clang 12 for compilation, CMake (minimum as well) and Ninja versions are also bumped. Also bumps the LLVM submodule to a later commit. Removes the xcb hack, bumps minimum compiler versions. Switches BSD to Clang 12.
~~edit: do not merge yet, waiting on hcorion to push a newer docker image.~~
> Toolchain upgrades

- rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
- rpcs3/Emu/RSX/GL/GLFragmentProgram.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/GL/GLHelpers.cpp
- rpcs3/Emu/RSX/GL/GLPipelineCompiler.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/GL/GLShaderInterpreter.cpp
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKFormats.cpp
- rpcs3/Emu/RSX/VK/VKFormats.h
- rpcs3/Emu/RSX/VK/VKFragmentProgram.h
- rpcs3/Emu/RSX/VK/VKHelpers.cpp
- rpcs3/Emu/RSX/VK/VKProgramPipeline.cpp
- rpcs3/Emu/RSX/VK/VKResolveHelper.h
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
- rpcs3/Emu/RSX/VK/VKVertexProgram.h
- rpcs3/Emu/RSX/VK/vkutils/image_helpers.cpp
- rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp
- Fixes some ReSharper warnings (too lazy for const functions).
- Found some unused enum values that might be the cause for some bugs (kd-11 maybe you can defuse them)
> GL/VK: ReSharper findings

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
Allowing for more flexible constructors without explicit name argument, matching the context's contructors.
> Simplify named_thread construction

- 3rdparty/7z/7zlib.vcxproj
- 3rdparty/hidapi.vcxproj
- 3rdparty/libcurl.vcxproj
- 3rdparty/libpng.vcxproj
- 3rdparty/libusb/libusb_static.vcxproj
- 3rdparty/pnglibconf.vcxproj
- 3rdparty/wolfssl.vcxproj
- 3rdparty/xxhash.vcxproj
- 3rdparty/yaml-cpp.vcxproj
- 3rdparty/zlib.vcxproj
- asmjitsrc/asmjit.vcxproj
- rpcs3/GLGSRender.vcxproj
- rpcs3/OpenAL.vcxproj
- rpcs3/VKGSRender.vcxproj
- rpcs3/XAudio.vcxproj
- rpcs3/emucore.vcxproj
- rpcs3/rpcs3.vcxproj
Links to common props files are relative; build files should avoid
relative links when/if at all possible.
> BUILD:  fix relative links to common_default* props

- rpcs3/Crypto/ec.h
- rpcs3/Crypto/lz.cpp
- rpcs3/Crypto/lz.h
- rpcs3/Crypto/utils.cpp
- rpcs3/Crypto/utils.h
5 files in Crypto were licensed under GPL-3.0-only which is incompatible with our project's GPL-2.0-only license. They have now been corrected to use GPL-2.0-or-later.
Approval from all contributors with copyrightable changes has been obtained.
> Correct mismatched licenses in Crypto

- rpcs3/Emu/Memory/vm.cpp
- rpcs3/util/types.hpp
- rpcs3/util/v128.hpp
- rpcs3/util/vm.hpp
- rpcs3/util/vm_native.cpp
- Implement s128 type (unused, maybe it's better to remove it completely)
- Add native API flag for CoW memory (copy-on-write)
- Dig for portable memory overcommitting technique. For now, try to map temporary sparse file (which is filled with zeros and doesn't occupy disk space) with mentioned cow flag. Try to get 32G of "writable" memory. There was an idea of implementing scalable breakpoint framework on base of it (interrupts, conditionals, memory access bp, etc).
> Digging for some features

- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.h
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_event.h
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.h
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.h
- rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
- rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/IPC.h
- rpcs3/rpcs3qt/kernel_explorer.cpp
* Remove custom event queue's IPC management in favour of universal LV2 approach.
* Fix ipc_manager internal storage memory leak: deallocate entry when IPC object destroyed.
* Rewrite lv2_obj::create to be simpler (remove many duplicated code).
* Always execute lv2_obj::create under both IPC and IDM mutexes at once (not in non-atomic single-steps). Fixing potential case where concurrency can cause IDM to contain 2 or more different objects with the same IPC key with SYS_SYNC_NOT_CARE (instead of the same object).
* Do not rely on smart ptr reference count to tell if the object exists. Use similar approach as event queues as it makes error checkings accurate.
* Move ipc_manager to FXO.
* Fix EAGAIN check for IPC enabled objects.
* Do not touch ps3 memory under IDM/IPC mutexes because it's …
> LV2: Improve IPC support

- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.h
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.h
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.h
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.h
- rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
- rpcs3/Emu/Cell/lv2/sys_rwlock.h
- rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
- rpcs3/Emu/Cell/lv2/sys_semaphore.h
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/rpcs3qt/kernel_explorer.cpp
* Fix typo in lv2_obj::create.
* Always save ipc_key as 0 for non-shared object creations, regardless of thbe value set by creation attribute.
* Show IPC key of shared memory (sys_mmapper) memory objects in kernel explorer.
Fixes #10248
> LV2: Fixup for IPC

- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3qt/user_manager_dialog.cpp
Since the dialog cannot be opened ingame, there should be no reason to disable the rename user option.
fixes #10242
> Qt: allow renaming of the current user

- rpcs3/Emu/Memory/vm.cpp
- rpcs3/util/vm_native.cpp
- Try two different locations on windows.
- Don't delete empty sparse file, try to overwrite instead. Something is going wrong here.
- If sparse file cannot be created, warn and fallback to empty 32G file.
> Don't fatal on sparse file initialization failure

- Utilities/File.h
Avoid wasting resources if a handle has been opened before the call to *open*, so only one lives at a time at maximum.
This is also a bugfix in case the existence of the two handles contradict with each other such as if both refer to the same path and use a locking flag.
> fs: Optimize/fix filesystem handle reconstruction

- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/9995
> vk: Ensure MSAA surfaces are in RW state before attempting to transfer data.

- rpcs3/Emu/RSX/Common/GLSLCommon.cpp
- rpcs3/Emu/RSX/GL/GLHelpers.h
Without this fix, I couldn't run anything with OpenGL on my Surface Pro 7 (i7 version), now it works.
> gl: Intel GPU shader fix

- cmake_modules/ConfigureCompiler.cmake
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/util/logs.hpp
- rpcs3/util/types.hpp
- rpcs3/util/vm_native.cpp
- Don't recreate rpcs3_vm sparse file every time.
- Try to verify sparse file support in portable way (Linux/Unix).
- Unconditionally re-enable warnings about attributes (became possible with newer compilers).
- Fix pessimising returning move in `lv2_obj::create`
> Fixup collection

- rpcs3/Emu/Cell/lv2/sys_timer.cpp
While working on saving the state of lv2 timers, I've noticed a bug can cause infinite events to be sent by timer thread. In the case of expire + period result overflowing such as if period was set to UINT64_MAX. 
This is not an issue on real PS3 as I tested in https://github.com/elad335/myps3tests/tree/master/ppu_tests/timer%20overflow%20attempt
I've used explicit overflow checks because it's simpler to manage for an absolute periodic timer.
Moved ETIMEDOUT error check to its proper position.
> lv2: Fix overflows of periodic timers

- rpcs3/Emu/Cell/SPURecompiler.cpp
Optimizes BRZ/BRNZ by using vpmovmskb and a check against the sign bit where possible.
For whatever reason vpextrd is 2 uops on both intel and ryzen cpus, while vpmovmskb is just 1 uop. 
It's only a small speedup but the optimization is pretty common (about 5,000/10,000 BRZ/BRNZ in wipeout HD can hit this optimization)
> SPU LLVM: Optimize branching

- 3rdparty/CMakeLists.txt
Wolfssl was already supported, but used a cmake file despite the distribution packages only shipping a pkg-config file.
The other three didn’t have this option despite working perfectly with the system version (tested on ArchLinux).
I also tried to use the system version of other libraries, but:
- yaml-cpp and cereal make use of exceptions in their headers, despite that being disabled by rpcs3.
- hidapi uses a [non-upstreamed function](https://github.com/RPCS3/hidapi/commit/c095a22c53f13ccafc54dc59b5c882cd4036afd9) which we should eventually upstream.
- asmjit isn’t present in ArchLinux yet.
> Allow building against more system libs

- rpcs3/Emu/system_config.h
This setting is NOT ready for dynamic modifications. Games can crash due to changing this setting dynamically as suddenly MFTB can returns values from hours ago or after relatively toe the time of changing the setting.
This is sad but I can't do anything until time resetting and restoration is implemented which is part of savestates.
> Fix bugs due to clocks scale setting being dynamic

- rpcs3/util/logs.hpp
Should fix #10310 
Really one character typo.
> logs.hpp: fix fatal typo

- rpcs3/util/logs.cpp
Don't print channel names for initial messages.
> logs.hpp: another fixup for RPCS3.log

- rpcs3/Crypto/md5.cpp
- rpcs3/Crypto/sha1.cpp
- rpcs3/Crypto/sha256.cpp
- rpcs3/Crypto/utils.cpp
- rpcs3/Crypto/utils.h
using volatile f/p guaranting assembly will generate call* instruction on memset for secure buffer zeroing. usage in sha1 api as well.
> crypto light refactoring.

- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/Loader/TROPUSR.cpp
- rpcs3/Loader/TROPUSR.h
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
* Add magic test in TROPUSR.
* Optimize TROPUSR::Save.
* Replace invalid TROPUSR.DAT with empty new ones. (+report an error)
* Fix return code of Load whenever TROPUSR.DAT hadn't existed before.
* sceNpTrophyRegisterContext will abort if TROPUSR.DAT generation failed.
> Improve trophy context loader

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.h
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/rpcs3qt/kernel_explorer.cpp
Implemented lv2_obj::ppu_state() which accurately tells the current running state of a PPU.
> kernel-explorer: Implement PPU scheduler state information

- .ci/deploy-linux.sh
- .cirrus.yml
- azure-pipelines.yml
Docker-side commit here: https://github.com/RPCS3/rpcs3-docker/commit/14ff5ad31d6b8ec5125798f069057005fe2a22c0
Summary of changes:
- GCC bumped to version 11
- SDL2 bumped to 2.0.14
- Shellcheck bumped to 0.7.2
- Qt patched to support GCC 11
> Bump gcc to 11, shellcheck and SDL2

- rpcs3/Emu/Cell/lv2/sys_memory.cpp
- rpcs3/Emu/Cell/lv2/sys_memory.h
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
* Show used memory conatiner ID for shared memory and sys_vm objects, "Global" means the global memory container instead of specific instances created with syys_memory_container_..
* May simplify state representation saving of memory container references.
> kernel-explorer: Save self mem-container ID and use it

- rpcs3/util/vm_native.cpp
> vm_native: trying to fix sparse file issues

- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.h
Consume PS3 memory only at shared memory creation.
> sys_mmapper: Fix IPC-enabled instances memory consumption

- rpcs3/util/vm_native.cpp
Fix fast path condition (xnor is not ==, facepalm).
Increase probe size.
Should fix #10334
Closes #10335
Co-authored-by: Jan Beich <jbeich@FreeBSD.org>
> vm_native: fix Linux/Posix sparse file check

- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- Updates the performance overlay update interval tooltip.
- Reduces the maximum update interval from 5 seconds to 1 second.
I don't think anyone uses a value that large and it also made it harder to configure the more common lower values in the GUI.
> Update performance overlay settings 

- .cirrus.yml
Not sure if it's worth having separated runs, though it may be better in the short term since 13 is relatively new.
Closes #10212
> CI: Add FreeBSD 13

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
Fix crash on boot for linux users with RADV driver and async texture streaming enabled.
> [Hotfix] vk: Fixup on linux + RADV combo

- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
Move owning ptr from IDM in order to not trigger te thread handle destructor of the sane thread, but still remove PPU ID.
> Simplify PPU exit

- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GL/GLTextOut.h
- rpcs3/Emu/RSX/GSFrameBase.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKTextOut.h
- rpcs3/rpcs3qt/gl_gs_frame.h
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
Depending on the dpi settings, the debug overlay was almost unreadable.
I also took the liberty to add some margin to the left.
This entire code module will probably be replaced sometime soon anyway, but whatever.
> Scale debug overlay based on current dpi settings

- rpcs3/Emu/Cell/PPUAnalyser.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/System.cpp
* Modules opened by FD with 0 offset will be considered the same as opened by path with no offset.
* Modules opened by FD will no longer be considered the same as opened with path with filename suffix that is the same as the one used by FD opening. (such as "_x0" for 0 offset)
Found while working on savestates. (also needed by it)
> sys_prx/overlay: Fix disambiguator of module names opened by FD

- rpcs3/Emu/RSX/VK/VKDMA.cpp
- rpcs3/Emu/RSX/VK/VKDMA.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- This reverts commit dbcf1b5a03bfef18f404aa6827515af319abd744.
- Avoid unmapping buffers used for GPU upload/download. It is very slow to do so on some platforms. Strangely most other drivers don't have any measurable impact either way.
> vk: Properly fix slow bo upload + copy when using RADV

- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
The native user interface may currently cause deadlocks due to recursive locking of g_pad_mutex.
I couldn't find a better way to handle this right now and it could be possible that there still exists a similar recursion.
hopefully fixes #10366
> Try to fix pad interception

- rpcs3/Emu/NP/np_handler.h
- rpcs3/Emu/RSX/GL/GLTextOut.h
- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/Emu/RSX/VK/VKTextOut.h
- rpcs3/emucore.vcxproj
- rpcs3/rpcs3qt/memory_string_searcher.cpp
The guide lines falsely started from the top and not from the bottom, as all datapoints do.
> perf_overlay: fix guide line locations

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- rpcs3/rpcs3qt/tooltips.h
- Only log time_base errors once per stream.
- Log framerate as well. Maybe it is useful in some cases. 
mitigates #2550
> cellVdec: silence "Unsupported time_base" error log spam

- rpcs3/stdafx.cpp
- rpcs3/util/shared_ptr.hpp
- rpcs3/util/typeindices.hpp
- rpcs3/util/types.hpp
Use constexpr allocator instead of fake static object. Fake static object can't be abstract.
It's required to compare numeric values of pointers at compile time, without actually knowing them. Knowing this, it becomes possible to put reference counter directly behind the object and still permit casting custom smart pointer between different types within the "main inheritance" line.
It's also used to preallocate space for "unknown set of objects" (see fxo and typeindices).
> shared_ptr.hpp: improve compile-time pointer comparison

- .gitmodules
- 3rdparty/CMakeLists.txt
- Utilities/span.h
- buildfiles/msvc/rpcs3_default.props
- rpcs3/Crypto/utils.cpp
- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.h
- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Common/TextureUtils.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/Program/ProgramStateCache.h
- rpcs3/Emu/RSX/Program/program_state_cache2.hpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3qt/rsx_debugger.cpp
This is just to track implementation progress of std::span in the main 3 compilers we use. It is not possible to do such change now because none of the compilers are ready for std::span.
- Removes 3rdparty/span.
- Replaces gsl::span with std::span.
**Implemented on currently used compilers (0/3):**
According to https://en.cppreference.com/w/cpp/compiler_support Clang should support it since version 7, but importing `<span>` doesn't work
> Replace gsl::span for std::span (c++20)

- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKPipelineCompiler.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/sampler.cpp
- rpcs3/Emu/RSX/VK/vkutils/sampler.h
Features such as wide lines, anisotropic filtering, MSAA, etc that can be disabled without hurting too much can be optionally detected as unsupported and disabled quietly. They are not particularly critical to the emulation.
Fixes https://github.com/RPCS3/rpcs3/issues/6916
> vk: Improve compatibility with sub-par drivers and hardware

- buildfiles/cmake/ConfigureCompiler.cmake
- rpcs3/Emu/Memory/vm_ref.h
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/rpcs3qt/rsx_debugger.cpp
* Don't use -fconcepts, was only required for older gcc.
* Remove vm::ref default constructor (was wrong).
* Replace as_span workarounds with utils::bless.
> Fix some C++20 usage

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
I accidentally forgot to update the custom config icon after custom config creation/removal.
This happened during some refactoring back in mid-april.
> Qt: fix game list custom config icon refresh

- .gitmodules
Don't specify SSH or HTTPS explicitly. Can save some time if manually changing it is necessary.
> Unify .gitmodules url as relative ones.

- rpcs3/Emu/system_utils.cpp
Always return a sample of valid RAP path, even if actual file does not exist. Fixes path of RAP logging on failure to decrypt SELF due to missing RAP file.
> Fix missing game licence logging

- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
This bug aside from the fact that it alters PS3 memory where it shouldn't (should only after syscall is complete and PPU is notified) messes up with savestates' "atomicity" of saving.
> Tiny fix of sys_event_flag_wait

- rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/GL/GLTexture.h
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.h
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLTypes.h
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
PS3 gamma pack/unpack (PKG/UPG) are based on some obsolete nvidia-only instructions that were dropped from the published spec of NV_fragment_program. There are still references to them in some early Cg and CineFX manuals.
These instructions allow cheap and easy sRGB<->linear conversion which seems to be a trick some games are using.
e.g packGamma(value) ... unpackNoGamma(value2) will convert a value from sRGB to linear color space.
Fixes https://github.com/RPCS3/rpcs3/issues/7357
Additionally adds a debug view for OGL. This was crucial in debugging said problem because renderdoc has issues with some OpenGL commands. This is WIP, and will be migrated to use the overlay system when the debug text is being rewritten. It is only accessible programmatically for now until a proper debugging …
> rsx: Fix support for gamma pack/unpack instructions

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
Not needed anymore since async compute is disabled for every Kepler GPU. Also adds missing IDs for GK210 (Tesla K80 and such).
> Get rid of mobile Kepler class and add missing Kepler GPUs

- rpcs3/rpcs3qt/game_list.cpp
- rpcs3/rpcs3qt/game_list.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
Makes the game list load games and icons asynchronously.
The Game window will be opened faster and then populated when all games were processed.
The Icons will be displayed first come first serve.
It takes some time to repaint icons, so this step is seperated from the prior game list initialization.
This might be more interesting for people with huge game collections.
> Qt: lazy loading game list ("kinda")

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- Rebuilding when strict mode is enabled was incomplete.
The copy has to be redone if the source has been updated.
Fixes https://github.com/RPCS3/rpcs3/issues/9887
> rsx: Fix expired sampler descriptors

- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.h
By only loading trophy icons on a need to know basis, we can decrease the initial trophy manager loading times to a fraction of what it currently takes.
> Improve Trophy Manager loading times

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- rpcs3/Emu/RSX/VK/VKTextureCache.h
Addresses some minor bugs identified while working on https://github.com/RPCS3/rpcs3/issues/9133
- Fix deduplication test range. This fixes https://github.com/RPCS3/rpcs3/issues/10079. Due to an unrelated issue this can ironically trigger some crashing with verification failed elsewhere. I have fixes for this second issue in the works together with some other restructuring efforts.
- Fix a random verification failure in texture cache due to depth/color render target hit mismatch. Only depth->color actions were defined, color->depth handling was not properly done.
> rsx: Minor improvements

- rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.cpp
- rpcs3/Emu/RSX/Program/FragmentProgramDecompiler.h
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
- ~~Actually obey the no perspective flag. Adds affine interpolation when requested by the shader.~~
- Add a workaround for NVIDIA gpus where there is some arithmetic drift interpolating primitive-constant attributes across the fragments. Maybe a bug? This is a known issue and seems to be hardware specific.
Fixes https://github.com/RPCS3/rpcs3/issues/9299
> [TESTERS NEEDED] rsx: Improve fragment attribute precision

- Utilities/StrFmt.cpp
- Utilities/StrFmt.h
- rpcs3/main.cpp
- rpcs3/util/types.hpp
- Add simple message to second argument of ensure()
- Minor cleanup (function duplication)
- Add ensure() with formatting support, requires fmt::tie
- Implement fmt::tie to pack multiple formatting arguments
> types.hpp: Improve ensure util, add fmt::tie

- rpcs3/Emu/Memory/vm_ptr.h
- rpcs3/Emu/Memory/vm_var.h
- rpcs3/util/atomic.hpp
- rpcs3/util/endian.hpp
- rpcs3/util/serialization.hpp
- rpcs3/util/types.hpp
- rpcs3/util/v128.hpp
* Fix serailization of objects viewed through const-lvalue-ref reference.
* Fix operator T(), do not not allow non-copyable types.
* Add support for v128, s128, u128, atomic_t<>, se_t<> and vm::_ptr_base<> types. 
* Move specialized size serialization pattern to its own function.
Fixes regression when using new serialization helper with my savestates work.
> serialization.hpp: Fixes

- rpcs3/rpcs3qt/main_window.cpp
- Fixes the shortcut of the Play/Pause/Resume menu button in the Main Window.
I noticed that the shortcuts in our main window were based on some old Qt version (if they ever worked at all).
By using a proper KeySequence instead of some hint in the button text, we can just trigger the button without the use of key events.
This also implicitly fixes a mismatch between the key event code and the "OnPlayOrPause" slot.
> Qt: Fix Play/Pause/Resume Shortcuts

- rpcs3/Emu/Memory/vm_ptr.h
- rpcs3/Emu/Memory/vm_var.h
- rpcs3/Emu/RSX/Capture/rsx_replay.h
- rpcs3/util/atomic.hpp
- rpcs3/util/endian.hpp
- rpcs3/util/serialization.hpp
- rpcs3/util/v128.hpp
* Allows to declare bitcopy trait for locally defined class/union. (any static member is not allowed, even if constexpr)
> Improve bitwise serialization trait

- rpcs3/util/vm_native.cpp
- Prefer temp dir over RPCS3 cache dir
- Rename to rpcs3_vm_sparse.tmp
> vm_native.cpp: change rpcs3_vm name/location priority (Win32)

- rpcs3/Emu/System.cpp
Prevent threads from executing and attempting logging stuff before logs were fully configured.
> Logs: Prevent minor race in Emu.Run() regarding logging levels

- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/Cell/lv2/sys_timer.h
* Implement missing functionality of timer thread at Emu.Stop().
* Manage all sys_timer instances by one thread instead of thread for each.
* Simplify sys_timer instance construction.
> lv2: Implement missing abort op for timer thread

- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Cell/Modules/cellMouse.cpp
When once the application passed incorrect information to initialization process the entirety of cellKb/cellMouse collapsed at once.
> Fix cellMouse/Keyboard initialization

- rpcs3/Emu/CPU/CPUThread.h
This indirectly fixes GOW Ascension after emulation (or RSX) was paused then stopped when RSX was executing semaphore_acquire. See https://github.com/RPCS3/rpcs3/blob/c3415bcff263a22d4718da0b869af75373f2af03/rpcs3/Emu/RSX/rsx_methods.cpp#L91
Semantics of pause test should match Emu.IsPaused() which evaluates to false after emulation was stopped because pause flags lose their meaning in that situation.
> rsx: Fix emulation stopping when at semaphore_acquire

- rpcs3/Emu/Cell/Modules/cellCamera.cpp
- rpcs3/Emu/Cell/Modules/cellCamera.h
- rpcs3/Emu/Cell/Modules/cellGem.cpp
cellGem and cellCamera exposed bugs when changing clocks scale setting from 100%.
> cellCamera/cellGem: Fix time stretching setting support

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
May affect #9857 for savedata.
Default sync operation is very expensive on windows for some reasons, something is documented and can be found online.
MoveFileEx supports a writethrough flag which seems to have similar effect, but whether it's equally expensive I don't know.
I recommend to test it.
> fs: alternative fs::pending_file implementation (Win32)

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/rpcs3qt/kernel_explorer.cpp
* Make lv2_fs_object an abstract structure.
* Improve kernel-explorer information for filesystem objects.
> kernel-explorer/lv2: Make lv2_fs_object an abstract structure

- rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp
- rpcs3/rpcs3qt/localized_emu.h
Same trophy notification, but better. The notification is no longer squished in the corner and readability has been improved a lot. 
Size, color, transparency, spacing, position and duration are now the same as the original PS3 trophy notification.
What is still missing:
- Icon indicating the type of trophy
- Sound
- Rounded edges
- Fade-in and fade-out animation
- Font
Comparison:
After / Original
Before
https://user-images.githubusercontent.com/16064499/122832011-1e12c600-d2c1-11eb-9719-f32eba3b1450.mp4
> Trophy notification improvements

- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.h
This fixes the annoying issue of accidentally clicking the settings dialog's save or apply buttons after changing stylesheets, 
and the stylesheet doesn't apply
> Qt: apply gui settings on regular apply and save

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
When mount point does not exist path is empty and it passes to get_mp(path). (empty path is root)
> sys_fs: Fix ENOTMOUNTED of open

- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/System.cpp
Inheritance is a bit more annoying, it disables operator= implicitly.
Should fix #10499
> Fixup for regression from #10490

- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings.h
It turned out that if config of games exists before VFS manager saved modified paths, new paths set from VFS manager will be ignored completely by the game!
> VFS: Fix paths override

- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- rpcs3/Emu/RSX/Program/ProgramStateCache.h
- rpcs3/Emu/RSX/Program/RSXVertexProgram.h
- rpcs3/Emu/RSX/Program/VertexProgramDecompiler.cpp
- rpcs3/Emu/RSX/Program/VertexProgramDecompiler.h
- rpcs3/Emu/RSX/Program/program_util.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/rsx_cache.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/RSX/rsx_methods.h
- rpcs3/Emu/RSX/rsx_utils.h
Some games are kinda pushing it with RSX register space and spilling VP data into adjacent unused register space. This has some unexpected implications such as bumping the number of instruction addressing bits from 9 to 10 to cover the extended address space. This PR adds support for the extended size data as well as the results of the RE work to find the missing instruction bits. Due to this, the structure of the programs has changed and this requires a shader cache version bump.
Fixes https://github.com/RPCS3/rpcs3/issues/8500
> rsx: Implement support for extended-length vertex programs

- rpcs3/Emu/Cell/PPUCallback.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Memory/vm_ptr.h
- rpcs3/Emu/Memory/vm_var.h
* Fix stack alignment of PPU HLE callbacks within context of HLE PPU stack variables.
* HLE PPU stack variables: save some guest (PS3) memory by saving allocation size locally. (instead in PS3 memory)
* Use c++20 concepts in vm_ptr.h
> Improve ppu_thread::stack_push, use concepts in vm_ptr.h, PPU HLE callbacks fix

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/RSX/rsx_methods.h
Vertex offsets can be updated mid-draw to dynamically render different meshes without breaking up draw call submissions.
Fixes vertex explosions when rendering certain effects in Rachet & Clank: A crack in time.
> rsx: Implement dynamic vertex offset updates

- rpcs3/rpcs3qt/kernel_explorer.cpp
- rpcs3/rpcs3qt/kernel_explorer.h
* Default width of dialog has been increased to fit PPU, SPURS and filesystem objects' description length.
* Height has been increased as well to allow viwwing more objects at once.
* Added title of the game to the kernel explorer's windows' title.
* Added the ability to log all of what's currently viewed in kernel explorer.
> Improve kernel explorer

- 3rdparty/CMakeLists.txt
- rpcs3/Emu/Audio/FAudio/FAudioBackend.h
moved FAudio files into its own directory structure,
and fixed a bad header import.
> Refactor faudio submodule

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- Fixes the error during game data installation of PlayTV by treating all app categories as HDD_GAME in cellGame
- Fixes an issue that causes disc games to show the old version even though patches were installed, if the patch category was something other than "GD" (for example AT for APP TV)
- Fixes an issue where the virtual bluray drive wasn't mounted if the loaded patch was not of type GD (This might not have any effect or even be wrong though)
PlayTV only seems to "work" if you first boot the game version 01.00 and install its game data.
You can then install version 02.04 and it will still boot with the same result.
If you install 02.04 before letting the 01.00 game install its data, then it will fail with a mem access violation.
I don't know if this is a bug on PS3 as well or if we …
> Improve PlayTV

- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/rpcs3qt/kernel_explorer.cpp
Lock PPU state mutex once for all PPUs so the information reported is accurate for global threads state. Previously it could have reported non-existing states such as 3 running PPUs etc because it was not atomic.
> kernel_explorer: Atomic PPU state updates

- Utilities/StrFmt.cpp
- Utilities/StrFmt.h
char8_t is a new fundamental integral type for UTF-8 characters. Adding missing pieces to allow formatting.
> fmt: implement char8_t string support

- rpcs3/Emu/RSX/Common/TextureUtils.h
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Common/texture_cache_utils.h
- rpcs3/Emu/RSX/VK/VKDMA.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKResourceManager.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/VKTextOut.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/VK/vkutils/buffer_object.cpp
- rpcs3/Emu/RSX/VK/vkutils/buffer_object.h
- rpcs3/Emu/RSX/VK/vkutils/data_heap.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
- rpcs3/Emu/RSX/VK/vkutils/memory.cpp
- rpcs3/Emu/RSX/VK/vkutils/memory.h
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
- rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
This PR adds a lot of stuff I've been working on the past few weeks that tries to keep the emulator from dying when we run out of video memory. Due to rpcs3's architecture, some applications can trigger runaway conditions where all the video memory can be consumed in seconds sometimes even with a RTX 3090.
**Changes**
Multiple strategies are used here to handle out of memory situations:
1. Track memory allocations in coarse "pools". This will help track which part of the emulator is using too much memory and take appropriate actions based on this.
2. Adds improved heurestics to avoid false positives. Sometimes the memory is there, just fragmented. If we keep panicking in such situation and deleting everything, performance can be very bad.
3. Allow emergency texture cache eviction if we're …
> [TESTERS NEEDED] rsx/vk: Rewrite memory management

- 3rdparty/glslang/glslang.vcxproj
- buildfiles/msvc/common_default.props
- rpcs3/emucore.vcxproj
- glslang - fixed wrong path to common props
- emucore - fixed for VS2022, it's a 64-bit app now
- common_default.props - use C++20 standard for VS2022 and further
`git-version-gen.cmd` seems to work correctly with both 32/64-bit `cmd` so there should be no reason to force 64 bits unless i missed something.
Please verify `common_default.props` work under VS2019, due to some installer issues because of VS2022 preview i had to uninstall all other versions.
> [MSVC] glslang fix + vs2022 fixes

- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/debugger_frame.cpp
Unlike the callstack viewer, this debugging feature does not forget its calls once they return!
The list expands and expands up to 4096 addresses when you set in "PPU Calling History" setting.
Once size limit is reached, oldest record is removed in favour of a new address record.
For BCLR/BCTRL: The recorded address is of the branched address.
For BCL/BL: The recorded address of the current instruction address, this is done in order to provide additional information about the location of the call.
Key D while viewing the thread dumps current list.
> PPU debugger: Implement PPU calling history

- rpcs3/Loader/TAR.cpp
- rpcs3/Loader/TAR.h
* Implement the ability to save directory contents as TAR.
* With the ability to customize saving of specific files and also select which files are saved and which aren't. 
* Implement full original TAR USTAR 255 characters path support.
* Implement file modification time and access time support for extracted/archived TAR.
This will be used for savestates support, optionally saving /dev_hdd1 and game data directories for when "Suspend Emulation Savestate Mode" is disabled.
> Implement TAR-based directory archiver

- Utilities/StrFmt.cpp
- Utilities/StrFmt.h
- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
T = std::byte or unsigned char.
`std::vector<T>, T[N], std::span<T, N>, std::basic_string<T>, std::basic_string_view<T>` are all compatible.
> Formatting Library: Implement byte arrays formatting

- Utilities/StrFmt.h
- rpcs3/Crypto/unself.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Memory/vm_ptr.h
> LV2: Fix IPC key reading from attributes

- rpcs3/Emu/Cell/PPUDisAsm.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
* Display the LLE function name at the first instruction an an ASM style comment.
* Add disasm of first instruction in PPU calling history logging. With this feature seeing LLE functions history!
> PPU debugger: Implement function names at the starting instruction

- rpcs3/Emu/Cell/lv2/sys_rsxaudio.cpp
Will be replaced with Vestrel's implementation, but required to not crash vsh currently.
> Stub rsxaudio for vsh

- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
Only BCTRL based wrappers to exported functions were working before. (they are rare)
BCTR based exported functions trampolines were not detected as a call because non-link variant is more tricky to detect than old implmentation could.
> PPU debugger: Make calling history detect common LLE functions trampolines

- Utilities/Thread.h
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
NOTE: Operating system thread renaming only works for current thread. But name associated with logging and RPCS3 debugger area always changed.
Used by VSH.
> sys_ppu: Implement sys_ppu_thread_rename

- rpcs3/Emu/Cell/lv2/sys_uart.cpp
- rpcs3/Emu/Cell/lv2/sys_uart.h
Implementation of sys_uart_* calls used by VSH to configure audio/video backend. Prerequisite for rsxaudio.
Reopen of #10513
> Initial implementation of sys_uart

- rpcs3/rpcs3qt/main_window.cpp
The `All pup files` filter was only allowing lowercase .pup files. Most firmware files I've seen so far have uppercase extension, so the filter wouldn't show any files on these cases.
Before:
After:
Second PR, because I can't open PRs to this repo without something going wrong.
> Include different case files on file selection filters

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/main_window.ui
- Add "Boot VSH/XMB" option to the main menu
- Add VSH to "All Titles -> Create PPU Caches"
- Fix a bug that occasionally crashed RPCS3 after the "Create PPU Caches" dialog was canceled
- Fix a bug that didn't properly kill the current PPU compilation when the "Create PPU Caches" dialog was canceled
> Add VSH to GUI

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
Unfortunately there is no way on NVIDIA GPUs after driver 470 to schedule work on two queues with dependency without going through a vkQueueSubmit. This is because queue priority is not observed and attempting to park one queue with a vkEvent and signal based on completion of another task on another queue leads to deadlock. It seems the queue is not unscheduled when reaching a sync point and other queues do not actually run concurrently. This is true for all card generations since this new driver released. Unfortunately going through vkQueueSubmit is horrendously slow. A fallback path will be experimented with later on, although given the submit overhead, it may not really end up amounting to much in terms of tangible performance benefits. Simply removing the feature on affected cards …
> vk: Disable async texture streaming on all NVIDIA cards

- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/tooltips.h
- rpcs3/rpcs3qt/update_manager.cpp
- rpcs3/rpcs3qt/update_manager.h
- rpcs3/util/media_utils.cpp
Add option "Automatic" to automatically update RPCS3
Doesn't ask for user confirmation on startup
Does still ask for confirmation if you click the update button manually
Does still show the progress bar which can still be aborted
Does not happen if you boot a game from the command line
> Qt: Add option to automatically update RPCS3

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/VK/VKResourceManager.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/buffer_object.cpp
- rpcs3/Emu/RSX/VK/vkutils/buffer_object.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
- rpcs3/Emu/RSX/VK/vkutils/memory.cpp
- rpcs3/Emu/RSX/VK/vkutils/memory.h
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
Improves the video memory manager a bit more:
1. Pool similar memory types into one virtual type. Video memory budget checks do not properly respect this behaviour due to how the vma code works, but I decided to handle it separately in another PR.
2. Tries to be smart about the action boundaries by taking resolution scale into account. It is no secret that higher resolutions require more memory and therefore the boundaries need to be moved around a bit.
3. Do not waste memory when building scratch resources. This is to cater to devices where the amount of video memory may be low. In most games, we do not need more than 4MB of scratch anyway.
4. Fix some crashes caused by use-after-free in texture cache code.
This improves stability of the memory manager while under pressure. There still …
> rsx/vk: Video memory manager improvements [2]

- rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKHelpers.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
- rpcs3/Emu/RSX/VK/vkutils/memory.cpp
- rpcs3/Emu/RSX/VK/vkutils/memory.h
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
- rpcs3/Emu/RSX/VK/vkutils/scratch.h
Implements several critical fixes to the video memory manager which is partly broken:
- Avoids running into budget constraints by spreading out memory allocations within pooled types.
- Allows creating 'null' textures which can signal that we could not create something due to running out of memory.
- Fix out of bounds access for scratch buffers after the last PR (VMM improvements 2)
- Properly initialize scratch images with correct format class. Fixes some error spam.
- Fixes a bug with memory type comparison that caused memory spilling to not work at all since the last PR (VMM improvements 2)
- Gracefully handle OOM situations which occur during texture binding. If we cannot create the texture, do not invoke spilling or any destructive restructuring of the surface cache. Instead, handle …
> vk: Video memory management improvements [3]

- Utilities/StrFmt.cpp
I think this was the intended format?
Currently it will print something like: `{ 01, 23 45 67 89, AB CD EF  }`
when it should be: `{ 01 23 45 67, 89 AB CD EF  }`
> StrFmt: fix comma placement in format_byte_array

- rpcs3/Emu/RSX/VK/VKTexture.cpp
We have to use double the memory because the transformation does not occur in-place like normal bswap.
Fixes the remaining cases of vulkan memory assert. See https://github.com/RPCS3/rpcs3/issues/10612
> vk: Fix scratch allocation when doing GPU deswizzle

- rpcs3/Emu/RSX/Common/ring_buffer_helper.h
Apparently adding an offset to a delta when trying to grow the heap wasn't such a good idea.
> [TESTERS NEEDED] RSX: fix 'Working buffer not big enough' in Menu of Space invaders [NPUB30305]

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/system_progress.cpp
- rpcs3/Emu/system_progress.hpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/msg_dialog_frame.cpp
GUI:
- Disable "Boot VSH/XMB" if there is no vsh.self.
- Batch PPU compilation: Adds current state as "Progress: x/y. Compiling PPU caches for BLUS12345...".
- Batch PPU compilation: Fixes VSH compilation. It was hilarously skipped cuz I forgot that the initial call is not blocking.
- Batch PPU compilation: Compile the entire vsh/module folder instead of only vsh.self.
- Batch PPU compilation: Also abort batch compilation if the top dialog is closed.
- Firmware compilation: Compile the entire sys folder instead of only sys/external
Boot process:
- Scanner/Compiler: Compile vsh.self first when scanning vsh/module
- Scanner/Compiler: Skip searching for games if the title ID is empty
- Scanner/Compiler: Reset boot path to m_path_old after compilation. This fixes the "Play" button in the GUI
> Qt/System: VSH fixes

- rpcs3/util/vm_native.cpp
FreeBSD >= 13.0 has [memfd_create(3)](https://man.freebsd.org/memfd_create/3) and [MFD_HUGETLB](https://github.com/freebsd/freebsd-src/commit/3ef55e8f254c), [implemented](https://reviews.freebsd.org/D21393) via `SHM_ANON`.
Similar to https://github.com/yuzu-emu/yuzu/pull/6758
> vm_native: enable memfd_create on FreeBSD

- rpcs3/Emu/Memory/vm_ptr.h
* Allow if T is not a default constructible type, use bit cast to construct it. Fixes reading vm::ptr<vm::ptr<T, const u32>> for example.
* Simplify usage, no longer needing to manually construct the destination data and thus always spelling its type. (f.e. `if (CellSaveDataSetList list{}; setList.try_read(list))` can become `if (auto [ok, list] = setList.try_read(); ok)`
* Use std::addressof where needed.
> vm_ptr.h: Improve try_read()

- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Add a mouse lock setting in order to control the lock state when entering in fullscreen mode.
It can be useful when having multiple monitors.
> Qt: add fullscreen mouse lock setting

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/GDB.cpp
- rpcs3/rpcs3qt/breakpoint_handler.cpp
- rpcs3/rpcs3qt/breakpoint_list.cpp
- rpcs3/rpcs3qt/breakpoint_list.h
- rpcs3/rpcs3qt/debugger_frame.cpp
* Show error window when setting breakpoints on these conditions
* SPU/RSX are selected. (not supported)
* When using non-interpreters decoders.
* Non-executable memory is specified.
* Do not allow instruction stepping for non-interpreters decoders.
* Clear breakpoints when the game is stopped.
* Fix setting breakpoints on HLE functions.
> Debugger: Add some error pop-ups for invalid operations

- rpcs3/Emu/Cell/PPUThread.cpp
This could cause dialogs to seemingly finish at e.g. 50/100 modules because the existing modules weren't accounted for.
> System: add progress update on existing modules

- rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp
- rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp
- rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUModule.h
This setting did nothing in the past because function registeration only occured at RPCS3 startup, although the setting depends on it to occur at every PS3 application startup.
Fixes #6736
> Fix HLE LWMutex setting - Implement dynamic initialization of HLE functions

- rpcs3/Crypto/ec.cpp
This reduces the size of the stripped .o by 3 KiB, and the non-stripped one by 21 KiB, when not doing LTO.
> Crypto/ec: Make internal functions static

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- Fixes "regression"... some modules weren't counted before the offending commit. Afterwards they were counted twice.
- log name in _sys_prx_unload_module
> Fix counting of exisitng ppu modules

- rpcs3/Emu/Cell/PPUInterpreter.cpp
16-byte loads were previously not included, fixed.
> PPU: Fix accuracy of "Accurate PPU 128 reservations" mode

- rpcs3/Emu/Cell/Modules/cellGem.cpp
Fixes Deadstorm Pirates regression.
The error checks should be slightly more accurate now.
- Fixes and adds some error checks
- Adds calibration logic with 0.5 sec delay. Maybe some game depends on this.
- Implements a common variant of cellGemHSVtoRGB (hopefully correct, not really RE'd)
> cellGem: More stuff

- rpcs3/Emu/Cell/Modules/cellGem.cpp
This should temporarily fix the Time Crisis Razing Storm collection.
I'm not sure what's wrong here.
Maybe it's a bug or it's correct and the game simply expects something new.
I'll disable it for now though because I don't have time to work on it for a while.
> cellGem: Disable Alignment Checks

- rpcs3/rpcs3qt/settings_dialog.ui
just changed back what didn't seem important from kd's changes lol
before:
after:
> ui: fix spacing on gpu tab

- rpcs3/Emu/RSX/VK/VKPresent.cpp
The following set of conditions can fail
1. We hit a RTT owned texture
2. The texture is invalidated (failed memory integrity test) and set to write/read-through
In this situation, RTT overlap check will skip this surface, and a match can be found in texture cache if WCB/WDB is enabled.
The incoming hit however has no managed payload. This is expected behavior, the search should load from CPU.
> [HOTFIX] vk: Do not force check for successful texture cache load

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- Do not scale Z values for 2D proj shadows.
- Fix unnormalized sampling for 3D textures. Previously it was blocked by a silly check.
Fixes https://github.com/RPCS3/rpcs3/issues/10662
> rsx: Fix coordinate scaling for shadow access

- rpcs3/Emu/RSX/VK/VKPipelineCompiler.h
Generate hash keys using the full attachment state.
Fixes https://github.com/RPCS3/rpcs3/issues/10671
> rsx: Check all attachments when generating pipeline hash key

- rpcs3/Emu/RSX/RSXThread.cpp
If a large value is set (e.g 0.5) rounding will sample 'up' and we can read the wrong texel. In most cases this does not matter but sometimes this can be the difference between sampling NaN and a valid input.
Fixes https://github.com/RPCS3/rpcs3/issues/10673
> rsx: Significantly reduce the applied subpixel bias when handling unnormalized access

- rpcs3/rpcs3qt/tooltips.h
Apparently artefacts is not a typo, but the en-gb spelling?
Fixes #10692
> gui: change the FSR tooltip to american english [hotfix]

- rpcs3/Emu/Io/Null/NullPadHandler.h
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds3_pad_handler.h
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
I noticed that the player id - which is used to indicate the player on DS3 and DualSense - was unique per handler instead of unique per device.
- Fixes player LEDs if 2 or more DS3 are used
- Fixes player LEDs if 2 or more DualSense are used
> input: fix player ID/LED if handler has 2 or more pads

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
* Fixes race condition due to doing SPU group state transition asnyc instead of immediate as it should.
* Fix sys_spu_thread_group_resume: Do not remove suspend flag when SPU group state is not SPU_THREAD_GROUP_STATUS_RUNNING after operation!
No idea if it fixes some games random crashes.
> SPU/event queue: Atomically resume SPU group, Fix sys_spu_thread_group_resume

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_event.cpp
* First commit should fix regressions, SPU resume is no longer async hence other SPUs could have called exit by the time the thread called receive event wakes up.
* Implement protocol for SPU event queue.
> SPU: Remove outdated assertation, Implement protocol for SPU event queue

- rpcs3/Emu/RSX/VK/VKHelpers.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/memory.cpp
With cubemaps, each mip0 is repeated 6 times, so we need 6x the memory to get things done.
Fixes https://github.com/RPCS3/rpcs3/issues/10612
> vk: Properly calculate cubemap memory size

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/rpcs3qt/rsx_debugger.cpp
- rpcs3/rpcs3qt/rsx_debugger.h
The old viewer is inferior to the new one in the main debugger.
> Remove old RSX instructions viewer

- rpcs3/rpcs3qt/main_window.cpp
QoL change, from now on you can see the package information before installing when installing from main menu. This feature used to be hidden in drag-and-drop.
This feature allows to view package information without installing it.
EDIT: + Log the information even when the package installation has been cancelled.
> GUI: Display PKG information & installation confirmation from main menu

- Utilities/Config.cpp
- Utilities/Config.h
- rpcs3/Emu/Io/Null/NullPadHandler.h
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Emu/Io/pad_config.cpp
- rpcs3/Emu/Io/pad_config.h
- rpcs3/Emu/system_utils.cpp
- rpcs3/Emu/system_utils.hpp
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds3_pad_handler.h
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/mm_joystick_handler.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
(I'll use the XInput handler as an example, but this applies to all handlers)
- A pad profile is always tied to a handler.
So there can be multiple "Default Profiles" that each are meant for XInput, DS3 ... and so on.
- The original idea was that you could just make an Xinput profile for yourself and for example a different Xinput profile for each family member. Then everyone just had to select their profile in the correct player tab in the pad dialog and everyone would be happy...
- Changing the second Xinput pad's button mapping will also change all others unless you select a different profile for each.
- The resulting folder structure is a mess... There are a huge amount of files per handler in multiple directories (InputConfigs for example)
Since this turned out to be super …
> Redesign pad profiles

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/pad_thread.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- fixes some warnings
- fixes loading pad configs in the pad_thread when the file was empty (use same double load approach as in the dialog)
> Fix input if the pad config file was empty

- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/signaling_handler.cpp
- rpcs3/emucore.vcxproj
The warning in question is: "Warning	C4996	'inet_ntoa': Use
inet_ntop() or InetNtop() instead or define
_WINSOCK_DEPRECATED_NO_WARNINGS"
Simply adding the _WINSOCK_DEPRECATED_NO_WARNINGS preprocessor silences
the warnings.
> Removes warnings about using deprecated inet function

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/rsx_methods.h
- rpcs3/Emu/System.cpp
* Create lock file after installation, preventing a case where after system crash RPCS3 would assume games files were already installed although in reality the installation might have not been completed. With the new behaviour in such case RPCS3 will attempt tpo reinstall files.
* Move lock files to a hidden directory from games. (hdd0 is not hidden)
* Add game version identifier for installation lock file.
> Loader: Improve just-in-time installation of disc game files

- rpcs3/rpcs3qt/gs_frame.cpp
Deferred windows are not supported by the protocol. Technically it is possible, if you run rpcs3 under a compositor directly with no WM, but that's not how any sane person is using wayland.
Fixes https://github.com/RPCS3/rpcs3/issues/9882
> Add workaround for wayland session

- rpcs3/Emu/Cell/SPURecompiler.cpp
Accurately emulate SPU floating compare equals by using integer comparisons when the floating value will be interpreted as NAN by x86 hardware.
> SPU LLVM: Improve approximate FCEQ/FCMEQ

- rpcs3/Emu/RSX/VK/VKRenderPass.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/upscalers/fsr1/fsr_pass.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
- rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp
- Move RADV to unreliable OUT_OF_DATE category. This event doesn't always trigger, so just use polling as a fallback.
- Add support for fallback FSR formats. Fixes issues with some drivers like ANV not supporting BGRA8.
- Adds a workaround to disable compression as much as possible on AMD cards. This is a temporary measure until I get the required hardware. Performance is worse with this workaround in place, but at least the cards are usable for now.
Fixes https://github.com/RPCS3/rpcs3/issues/10726
Fixes https://github.com/RPCS3/rpcs3/issues/10709
> vk: Compatibility improvements

- rpcs3/Emu/Cell/lv2/sys_time.cpp
- rpcs3/Emu/Cell/timers.hpp
- rpcs3/Emu/System.cpp
Adds an offset to get_timebased_time at the time of booting a game in the emulator. This can fix some issues that appeared at very high uptime, due to games misusing floating point math.
Problematic games used a pattern of:
```
read_clock();
convert_to_float();
calculate_delta();
```
instead of:
```
read_clock();
calculate_delta();
convert_to_float();
```
which caused problems with floating point rounding at extreme values of PC uptime.
fixes: https://github.com/RPCS3/rpcs3/issues/10632
Also fixes some issues with elder scrolls and fallout games
> Offset get_timebased_time at game boot

- rpcs3/Input/mm_joystick_handler.h
It defaulted to JOY_POVFORWARD (same dumb facepalm bug as with XInput earlier)
> mmjoy: fix pressure sensitivity button

- rpcs3/Emu/RSX/VK/upscalers/fsr1/fsr_ubershader.glsl
Works around a hardware limitation on intel + ANV when using BGRA8 output.
Fixes https://github.com/RPCS3/rpcs3/issues/10726
> fsr: Mark output images explicitly as nonreadable

- rpcs3/Emu/Memory/vm.cpp
Not only check_addr is more optimized, but is also overflow-proof (returns false for amy corner case). May be needed for #10747.
> vm: Fix vm::page_protect error checking

- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- Adds a confirmation dialog that notifies about duplicate button assignments when saving the pad settings.
- Adds a config entry for skipping the dialog to GUI tab in the settings dialog
- Disables more checkboxes and dropdowns in the pad settings dialog during key input (only low hanging fruits. others are sus)
- Fixes some newlines after the info box code was changed to use rich text
- Removes some obsolete code
fixes #7479
> Pad Settings: Detect duplicate buttons and show warning dialog

- rpcs3/main.cpp
- Makes path argument a requirement on windows
- Makes argument order a bit more dynamic to allow preceding arguments
- Adds some logging to know what's going on
- Reduces some indentations
> improve get-commit-db

- rpcs3/Emu/system_utils.cpp
Now uses success log level, with the new description "Disabling logging! Do not create issues on GitHub or on the forums while logging is disabled."
> Mark "Disable Logging", add explanatory log message

- rpcs3/Emu/RSX/Common/TextureUtils.h
- The previous enumeration was a holdover from older access management.
- A bitflag of 0 seriously messes up the mask tests as it passes all the if_xxxx tests
Fixes https://github.com/RPCS3/rpcs3/issues/10775
> rsx: Fix surface access bit flags

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/rpcs3qt/downloader.cpp
- Removes a mutex that was added for seamless input data consistency.
It caused stutter due to some handlers taking too much time.
- Adds buffers to the button value translations in the handlers for a more atomic single assignment.
This might fix some "noise" in the button values, or even unwanted button presses, caused by assigning the values twice.
This also paves the way for the next change:
- Moves pressure sensitivity button code to the handlers.
This fixes a data race, e.g. when you keep pressing that button but it might sometimes "slip" during gameplay,
causing another button to be fully pressed instead of half pressed.
fixes #10786
> Fix DualShock stutter

- rpcs3/Emu/Cell/lv2/sys_spu.cpp
'Cooperate with system' SPU groups are special, should fix #10772 
TODO afterwards:
* Hwtest get priority syscall with it.
* Test this on realhw.
* There can be only one of this group type at a time on realhw, implement this behavior.
> Patch cooperate with system SPU group creation

- rpcs3/Emu/RSX/Program/GLSLCommon.h
- rpcs3/Emu/RSX/RSXTexture.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
This was marked TODO for a long time since we fixed remapping for UE3
- Unsigned remap seems to be overriden by gamma mask (Resistance 3)
- We already know sign mask overrides gamma mask from UE3 titles
Fixes https://github.com/RPCS3/rpcs3/issues/10789
> rsx/fp: Handle signed operator precedence

- rpcs3/util/vm_native.cpp
sys/sysctl.h was removed from glibc starting with 2.32 on linux:
> * The deprecated <sys/sysctl.h> header and the sysctl function have been
>   removed.  To support old binaries, the sysctl function continues to
>   exist as a compatibility symbol (on those architectures which had it),
>   but always fails with ENOSYS.  This reflects the removal of the system
>   call from all architectures, starting with Linux 5.5.
(see https://sourceware.org/pipermail/libc-announce/2020/000029.html )
> Removes need for sys/sysctl.h on linux

- rpcs3/Emu/CPU/CPUTranslator.cpp
- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/SPURecompiler.cpp
Expands the byteswap elimination to work with more of the rotate family instructions. These instructions are rarer but may also be used to rotate recently loaded values.
Optimizes SUMB with a special VNNI path. This path uses VPDPBUSD with a multiplied value of 1 and an added value of 0 to horizontally add twice from 8 bit to 16 bit and from 16 bit to 32 bit. This instruction is only a single uop, and is the fastest way to horizontally add on x86, despite needing to multiply with 1 and add with 0.
> SPU LLVM: Assorted optimizations

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm.h
Continuation of #10747, implements two new patch types which should ake patches easier to make while also allowing much greater possibilities!
Called "calloc" (code allocator): First argument is the address of instruction to save the starting address of allocation code (where we put the branch to it).  The second argument is count of instructions to be allocated . This always allocates `instructions + 1` as it also writes a branch to return to original code at `((uint32_t*)allocated_code_addr)[instructions]`
The address of instructions allocated will be remembered for further patch nodes with incremented address after each node until ran out of instructions.
Example 
```
Patch:
- [ calloc, 0x02f20030, 4 ] # Allocate 4 instructions, entry is at 0x02f20030
- [ be32, 0x0, 0x60000000 ] # …
```
> Patches/PPU: Extend and improve patching capabilities (code allocations, jumps to any address)

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_viewer.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/patch_creator_dialog.cpp
- rpcs3/rpcs3qt/patch_creator_dialog.h
- rpcs3/rpcs3qt/patch_creator_dialog.ui
- rpcs3/rpcs3qt/save_manager_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
Adds a new dialog "Utilities -> Patch Creator".
The dialog is basically a big input form that can be used to create a valid patch in yml format.
Features:
- Input fields for the usual keys that need to be added to a patch (one game only for now)
- Editable instruction table for easy patch creation. Uses dropdowns for instruction type.
Instruction table controls:
Rightclick: context menu with a couple of actions (including the following)
Del: Delete Selection
Ctrl+Up/Down: Move Selection (if contiguous)
- Patch file export (Ctrl+E)
- Patch validation on the fly
- yml preview on the fly
- Splitter to resize both sides to your liking
Future ideas:
- Validators for the offset and value fields depending on the chosen type
- Stricter yml validation (Game version or Title-ID for example)
- Patch …
> Qt: patch creator

- rpcs3/Emu/System.cpp
In addition for every pause event there's a unique mark in its log message in case you log important debugging information while emulation is paused such as kernel explorer's content and want to easily refer to it afterwards.
> Log emulation pause/unpause events

- rpcs3/Emu/system_progress.hpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/pad_thread.h
- rpcs3/main_application.cpp
- rpcs3/rpcs3qt/main_window.cpp
- Transforms pad_thread into a named_thread
- Adds a missing loop optimization that got lost during the last refactoring
- Increases sleep times while the thread is inactive and also adds sleep during emulation pause,
this reduces CPU usage while paused
> Input: pad_thread optimizations

- rpcs3/rpcs3qt/game_list.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_grid.cpp
- The scaled icons were permamently kept in memory, even when they were already drawn (and thus duplicated into Qt memory).
By using shared pointers we can make sure that all icons are released from both contexts after they were drawn.
- Release old list data when switching list modes.
> Qt: release more memory when possible

- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_utils.cpp
- rpcs3/Emu/system_utils.hpp
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- Removes reading custom configs from the /data directory which we removed a long time ago.
- Removes reading playtime info from the gui settings. We've switched to persistent_settings almost 2 years ago.
The data was already silently moved to the newer settings and removed from the gui settings if you opened the emulator at least once in that timeframe.
> Remove some deprecated stuff

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/main.cpp
Added a "fatal" paused state which cannot be resumed from, used with fatal errors. Previously the user could resume emulation after a fatal error occured, but it used to be a top secret flaw only developer knew. After #10830 it became less of a secret...
+ Fixes #10590
> Do not allow to unpause after fatal error occured in emulation

- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/main.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
* ❗❗ **Extremely useful feature for tweaking/testing config options: Implement forced default config option.** ❗❗
This simulates the config that is made when you first use the emulator.
* Implement manual selection of config file: opens a file selection dialog which is used to select used config file.
* Fix a bug which led to 'force global config' to not work for some games. (any game using process relaunch such most game collections, RDR, MGS4 etc)
* Relax CLI config purpose - instead the emulator forever ignoring any other config except for the one provided in arg, use it only for the CLI-booted game.
This is how the new context menu for it looks like:
> Improve config selection options for game startup

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm.h
* Make code allocation patches work properly.
* Add a second 32-bit branch capable jump patch type: "jumpl" - like "jump" but also saves CIA + 4 onto LR.
> Fixup for code allocation patches, Implement 32-bit jump-link patch type

- rpcs3/Emu/Cell/Modules/sysPrxForUser.cpp
- rpcs3/Emu/Cell/Modules/sys_libc_.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_tty.cpp
- rpcs3/Emu/Cell/lv2/sys_tty.h
- rpcs3/Emu/Memory/vm.cpp
Added some debug commits as well.
Fixes #10856
> Fix vm::try_alloc regression

- Utilities/bin_patch.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_vm.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm.h
* Make vm::unmap atomic, squash the memory unmapping process inside this function while still using the same VM mutex ownership. (previously the unmapping process was executed in the block destructor after this function finishes, if the last shared_ptr went out of scope)
* Make vm::unmap not fail due to random vm::get calls, shared_ptr reference count is no longer a condition.
* Fix sys_mmapper_free_address spuriously failing with EBUSY due to random vm::get calls.
* Fix sys_vm_unmap race condition due to non-atomic vm::unmap.
* Add an optional verification block ptr arg to vm::unmap, used by patches.
> vm: Fix vm::unmap

- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
The reason it crashed is because enqueued task which releases thread bits never executed in RSX overlays code, user_interface class.
Aims to fix #10845
> Fix user_interface::alloc_thread_bit() usage

- rpcs3/Emu/Cell/lv2/sys_prx.cpp
The old structure is only 32 bytes long, not containing prologue/epilogue functions.
Seen when using FW 1.93,and 1.85 in #help, so I grabbed 1.93 myself to fix it.
No idea from which version it uses newer PRX structures.
> sys_prx: Fix old firmware

- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- Adds more logging to Emu.Init and Emu.Load
- Fixes pad settings dialog. Switching to Player 2 null handler and then back to Player 1 resulted in a reset of player 1.
- Reset config and GUI parameters when changing handlers. This fixes some visual inconsistencies in the dialog.
> Qt: Pad settings dialog fixes

- 3rdparty/7z/CMakeLists.txt
- 3rdparty/CMakeLists.txt
- 3rdparty/asmjit/CMakeLists.txt
- 3rdparty/curl/CMakeLists.txt
collection of changes to cmake for fixing MSVC building.
> BUILD: cmake corrections

- rpcs3/Emu/Cell/lv2/sys_prx.cpp
Used by sys_prx_get_my_module_id.
> sys_prx: Implement sys_prx_get_module_id_by_address

- rpcs3/Emu/System.cpp
* If the user has set an invalid path, ignore it.
* Always end custom path with a delimiter because RPCS3 code relies on this.
* Fix **Add Games** when using custom BDVD path.
> Fix BDVD path setting

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/SPUInterpreter.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/system_config.h
A brief summary on what is MFC and what was so problematic about emulating it accurately:
The MFC (Memory Flow Controller) is what allows the SPU to perform reads and writes to memory outside of its own small memory "cache".
Unlike literally all processors, no CPU is known to be able to see the status of completion of its reads/writes, nor perform them out of order of its own execution.
Meaning if we write the value y to address x, then read from it. We expect on all processors to read the value y (assuming no concurrent writes involved) right? Wrong! SPU is the exception to this basic fundamental rule in processors.
Infact, the reads and writes the MFC is performing are executed at unpredicatable timing, without ordering to its own reads/writes (unless barriers are involved).
In Narcor …
> SPU MFC: Implement MFC commands execution shuffling

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
In accurate SPU DMA mode notify_all() is used in do_mfc() thus check_state is called within it. Also adds an option to explicitly disable check_state() calls in atomic wait callback by using flag cpu_flag::temp.
> CPUThread: Prevent recursive check_state calls (fixup after #8514)

- Utilities/bin_patch.cpp
- rpcs3/Emu/System.cpp
The progress_dialog and patch system aren't needed unless a game is started.
Before, the progress_dialog was initialized everytime we added a single game to the game list or even when we simply started RPCS3. This means that a thread was needlessly idling all the time.
The patch.yml was also read every time when we didn't need it, e.g. when changing the user.
> System: skip unnecessary fxo initializations

- rpcs3/Emu/Audio/audio_device_listener.h
- rpcs3/Emu/RSX/RSXThread.cpp
This decreases my cpu usage in GMPADTEST from ~9% to <1% during Emu.Pause() (together with the other pad_thread PR)
> RSX: wait when emulation is paused (reduces CPU usage)

- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.h
Currently the horizontal position of the performance graphs is smegged when the main overlay detail level is set to none.
Since the main body has no width in this case, the offset wasn't properly calculated.
This is fixed by using the max width of the main body and the graphs instead.
I used the occasion and moved the code segments to where they're actually needed.
> Fix position of centered performance overlay

- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
We leaked 64k of PS3 memory each time an OSK dialog was accepted. Idk about you but I dislike memory leaks especially if they are of PS3 memory which can cause PS3 syscall failures and crashes.
> Fix memory leak in cellOskDialog

- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
- rpcs3/Emu/Cell/Modules/cellOskDialog.h
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/rpcs3qt/osk_dialog_frame.cpp
- rpcs3/rpcs3qt/osk_dialog_frame.h
- Fixes an issue where CELL_SYSUTIL_OSKDIALOG_INPUT_ENTERED was sent even if the seperate window wasn't set to "keep open"
- Fixes an issue where dialog abort by game or system was treated as user abort
- Adds some parameters in preparation for further implementations (which I still had on another branch)
maybe fixes #10894
> Improve cellOskDialog. Partially fixes some more games that use it (mostly online games)

- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
> Fix initial perf overlay graph positions when the detail level is set to none

- rpcs3/Crypto/unedat.h
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
* cellFsSdataOpenByFd only ever uses read-only flag, even if the original FD has read-write proerty.
* Fix EDATADecrypter::stat() timestamps (use the original file's), fixes sys_fs_fstat for SDATA/EDATA descriptors.
* Skip error checking of sys_fs_read/write (and remove specific side-effect of sys_fs_write when using APPEND mode) if nbytes is 0. The only things that are checked is if FD exists at all and if locked by file stream API. (EBADF/EBUSY respectively)
- This does not seem to affect cellFsRead/WriteWithOffset.
- This was also confirmed by looking at syscalls disasm which explicitly checks if size==0 then skips the entire execution.
* Add noticable log messages for when trying to write onto SDATA/EDATA file descriptors.
Testcase: …
> sys_fs: SDATA/EDATA fixes and more

- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/10910
> vk: Fix scanning for upload heap types.

- .ci/setup-windows.sh
The current mirror is currently offline and is causing CI builds to fail
> ci: Switch QT mirror

- rpcs3/rpcs3qt/instruction_editor_dialog.cpp
- rpcs3/rpcs3qt/instruction_editor_dialog.h
When option is enabled, the edited instruction will be applied for all SPUs in the group at the same address. This checkbox appears only for a threaded SPU thread and if its group contains more than one thread.
> Debugger: Implement editing instruction for entire SPU group

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/NP/rpcn_config.cpp
- rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp
- rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/VFS.cpp
- rpcs3/Emu/system_config.cpp
- rpcs3/Emu/system_config.h
- rpcs3/Emu/system_utils.cpp
- rpcs3/Emu/vfs_config.cpp
- rpcs3/Emu/vfs_config.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/main.cpp
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/patch_creator_dialog.cpp
- rpcs3/rpcs3qt/vfs_dialog.cpp
- rpcs3/rpcs3qt/vfs_dialog_tab.cpp
- rpcs3/rpcs3qt/vfs_dialog_tab.h
- rpcs3/util/sysinfo.cpp
A recent PR introduced a new config path emu member.
- This new logic that solely relied on the path introduced a bug that caused games, which primarily use loaders, to skip loading the global config which contains the crucial VFS settings.
- The second issue was that manually selected shared configs also acted as an override, which also skipped the VFS settings. This obviously isn't what the user wants.
In the future we should detach VFS and similar global settings from the regular config file to prevent this issue from happening.
But for now this shall act as an alternative (and hotfix as is).
Hopefully fixes #10862
Fixes #10867 (at least the idea behind it)
> Fix VFS regression

- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.h
The SnapSlider function is used to snap the current slider to certain values if modified with the mouse.
But it only triggered if the user was dragging the handle of the slider and not if the bar itself was clicked.
This is fixed by using an eventFilter that listens for mousepress and mouserelease events instead of the sliderPressed and sliderReleased signals.
Maybe this is a Qt bug, but I don't want to bother with reporting this right now.
fixed #10932
> Qt: Fix SnapSlider in settings

- Utilities/bin_patch.cpp
- Utilities/bin_patch.h
- rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUModule.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
This new patch type allows to insert function calls to exported functions and custom HLE functions. Not only this extends greatly the potential of functionality patches can do by itself by providing access to all PS3 firmware functions and custom PRX ones - you can register custom HLE functions in RPCS3 code with custom module name and use that in patches. In other words you can inject real C++ code into games! The downside of that is that you need to use a custom RPCS3 build which those functions exist in it, but @isJuhn had an idea a while ago that real DLL files can be used to inject such code without the need to use custom RPCS3 builds. So in the future we might see an "HLE" function loading DLL functions and injecting to games. Potential is basically endless here.
Ideas for such C++ …
> Patches/PPU: Implement HLE/LLE/With-TOC function call patches

- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
I don't know if there's a reason for the warning message.
So I'll just change it and see how many developers throw insults at me :)
> Remove some lwmutex log spam

- rpcs3/Emu/Cell/PPUDisAsm.cpp
- rpcs3/Emu/Cell/PPUDisAsm.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUDisAsm.cpp
For example: https://user-images.githubusercontent.com/18193363/134966023-593dadb9-19ef-41dd-86b4-c65e30bd1f88.png
Previously it just displayed "sc" and nothing more.
This is done by trying to get a constant value of r11 from the point of the syscall backwards, by analysing previous instructions. This process is called constant folding.
If r11 is not a constant (as far as we know), simply "sc" will be printed.
> Debugger/Disasm: Name PPU Syscalls

- rpcs3/Emu/RSX/Common/bitfield.hpp
- rpcs3/Emu/RSX/VK/VKCommandStream.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKHelpers.h
- rpcs3/Emu/RSX/VK/vkutils/commands.cpp
- rpcs3/Emu/RSX/VK/vkutils/commands.h
- Explicitly declare one version for CB flush and the other for Async flush
- Always flush descriptors on CB flush in case of page fault handling.
Other threads other than offloader can also enter the method and require normal flow.
- Fix overlapping interrupt IDs.
- Minor formatting fixes
Fixes rare flickering or flushing when WCB is enabled with the previous optimizations active. Also improves driver stability in theory.
> vk: Clean up around vkQueueSubmit handling

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKHelpers.h
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/device.h
Attempts to adjust number of pre-allocated descriptors based on device limits. This solely exists because of intel's windows drivers which advertises a relatively tiny sized pool. A small performance hit (~1-2%) is expected.
Should fix https://github.com/RPCS3/rpcs3/issues/10941
I do not have an intel iGPU system, we need testers with this hardware to verify if games run for them without crashing. Preferably graphically intensive applications tested over at least 5-10 minutes.
> [TESTERS NEEDED] vk: Use a dynamic number of descriptor allocations

- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/microphone_creator.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.h
- rpcs3/rpcs3qt/settings_dialog.ui
- Adds a "Restore Defaults" button to the settings dialog.
When pressed, the current emu settings will be reset and all GUI toggles will be adjusted accordingly.
The settings will not be applied immediately. You still have to press "Apply" or "Save".
**The GUI settings won't be touched for now since they are applied immediately, which could turn out to be annoying.**
- Fixes the default value of RadioButtons in the settings, which was previously only properly found under certain conditions.
- Fixes the default value of ranged ComboBoxes in the settings.
> Qt: Add "Restore Defaults" Button to Settings Dialog

- rpcs3/rpcs3qt/downloader.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
- rpcs3/rpcs3qt/msg_dialog_frame.cpp
- rpcs3/rpcs3qt/msg_dialog_frame.h
- rpcs3/rpcs3qt/progress_dialog.cpp
- rpcs3/rpcs3qt/progress_dialog.h
Windows:
- fixes taskbar progress of the downloader's progress dialog
Linux:
- Should fix an issue where the taskbar progress would stay at 0 after the dialogs are finished
- May add error notifications (needs testing)
> Taskbar progressbar fixes for Windows and Linux (Unity Launcher)

- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/SPURecompiler.cpp
I overlooked this instruction earlier when optimizing the VNNI path for SUMB.
This AVX-512 instruction first calculates the absolute difference between 2 vectors before summing bytes horizontally. By using a vector of all zeroes, we can effectively use the instruction to just sum bytes horizontally.
This instruction should be faster than the VNNI alternative since we don't need to zero out the destination register, and we don't need to load a vector full of the constant 0x01. Additionally, when op.ra == op.rb, we only need a single instruction for the correct behavior.
> SPU LLVM: Use VDBPSADBW in SUMB

- rpcs3/Emu/Cell/PPUThread.cpp
Description is in the code itself.
> Suggest tweaking the setting "Stub PPU Traps" after PPU trap

- 3rdparty/SPIRV/spirv.vcxproj
- 3rdparty/glslang/glslang.vcxproj
This makes VS use its own cmake instead of the one in PATH, if available. Thus, dependencies can now be built without cmake in PATH.
> Set up VS environment before calling cmake in glslang and spirv

- .clang-format
There has been some update that causes some ugly spaces to appear when formatting function argument lambdas.
Changing the UseTab value should help resolve this problem. I didn't test every possibility though,
Before:
After:
> Fix clang-format for new ugly lambda indentations

- rpcs3/Crypto/unedat.cpp
- rpcs3/Crypto/unedat.h
- rpcs3/Crypto/unpkg.cpp
- rpcs3/Emu/system_utils.cpp
- rpcs3/rpcs3qt/main_window.cpp
In addition to PPU SELF/SPRX/OVL decryption, the tool "Decrypt PS3 Binaries" will now be able to decrypt SDAT and EDAT files.
Note that EDAT files may require KLIC and RAP file, I've added logging of the needed licence file (NPD content_id) for such cases.
> GUI Utilities: Implement PS3 SDAT/EDAT decryption

- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
Fixes padding underflow when setting font_sizes smaller than 8.
The padding is half the font size and the top padding is set to padding-4.
So everything smaller than 8 would go below 0 which would increase the top padding to u32 max, causing the text to get rendered off-screen.
> Overlays: fix small performance overlay font sizes

- 3rdparty/yaml-cpp/yaml-cpp.vcxproj
- 3rdparty/yaml-cpp/yaml-cpp.vcxproj.filters
- Utilities/Thread.h
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/System.cpp
- Rebases yaml-cpp to version 0.7
- Fixes some random typo
- Adds missing cpu_flag formatting
Needs merge of matching rebase PR in RPCS3/yaml-cpp first.
> Update yaml-cpp to version 0.7

- rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp
- rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.h
- rpcs3/Emu/System.h
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/trophy_notification_helper.cpp
- Fixes start and end positions of the trophy pop-up slide animation
- Adds a fade in/out animation
- Adds an optional sound-effect to the popup. It looks for the file "/sounds/trophy.wav"
Before:
After:
> Improve trophy pop-up

- rpcs3/Emu/CPU/CPUDisAsm.h
- rpcs3/Emu/Cell/PPUDisAsm.cpp
- rpcs3/rpcs3qt/memory_string_searcher.cpp
- rpcs3/rpcs3qt/memory_string_searcher.h
* Allow to combine modes of search, such as "Float" + "Double" + "SPU Instruction". Mode list is cleared after a click on "Select search mode(s)..".
* Implement a mode to search SPU instructions within PPU memory such as at SPU embedded images, as well as searching withing all SPU threads at once. Along with #11077 allows to search SPU floating point numbers.
> PS3 String Searcher: Implement instruction searching in embedded SPU images (as well as SPU floats)

- rpcs3/Emu/RSX/Overlays/overlay_trophy_notification.cpp
- rpcs3/Loader/TROPUSR.cpp
- rpcs3/Loader/TROPUSR.h
- rpcs3/rpcs3qt/screenshot_manager_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.h
- Adds multithreaded icon loading, just like in the game list. I noticed that clicking on a game didn't feel very smooth.
- Fixes empty Trophy manager after stopping any game and adds some more sanity checks after vfs::get calls.
- Fixes softlock of Screenshot manager after stopping any game due to Qt searching every folder in existence
- Fixes trophy pop-up sound when multiple trophies are queued
> Trophy manager improvements

- rpcs3/Emu/GDB.cpp
- rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog.cpp
- rpcs3/Emu/RSX/Overlays/Shaders/shader_loading_dialog_native.cpp
- rpcs3/Emu/system_progress.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/user_manager_dialog.cpp
This should give us more insight into the conditions that cause emulation stops.
This may also help find false issue reports.
> Add more logging for Emulator Stop events

- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- Fixes an issue where the framerate graphs would halfway disappear at the right edge of the screen in detail level none
- Fixes an issue where the framerate graphs would appear at the old origin of the detail body if you toggle from any detail level to detail level none, when they instead should be centered.
> Performance overlay position fixes

- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Common/texture_cache.h
- A pitch of 0 still allows 1-dimensional addressing.
Fixes https://github.com/RPCS3/rpcs3/issues/8377
> rsx: Fix sampling in X when 0 pitch is given

- rpcs3/Emu/Cell/lv2/sys_rsx.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/system_config.h
Added a setting called "VBlank NTSC Fixup" in config.yml, off by default.
What this setting does is to multiply the rate of VBLANK by 1000/1001.
For this to work with such "hard to measure" ratio, I have fixed rounding errors with the previous implementation ~~using accurate 128-bit integer based multiplication~~. This is also applied even the setting is turned off.
Fixes #11039, needs this setting turned on.
> rsx: Implement NTSC fixup mode, improve VBLANK accuracy

- rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
According to @Yahfz this setting with asmjit crashes every game.
> SPU ASMJIT: Disable 512 wide spu verification

- rpcs3/Emu/System.cpp
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
Since stability and performance aren't ideal on cpus with TSX-FA, let's just disable it by default. It can be force enabled via the forced option, just like with haswell and TSX.
Additionally, support detecting the new RTM_ALWAYS_ABORT bit in cpuid. This is a new bit that only appears in new microcodes with disabled TSX. (see this commit for details https://github.com/torvalds/linux/commit/1348924ba8169f35cedfd0a0087872b81a632b8e)
When TSX is disabled via this new microcode it can be re-enabled by writing 0x4 to the msr 0x0000010F. When enabled in this way, the performance of TSX seems to be the same as the pre TSX-FA microcodes. Intel has also removed the need for TSX to clobber the perfomance counters when TSX is in use (which perhaps indicates that intel removed their "workaround" for …
> SPU/SYSINFO: Disable TSX by default for TSX-FA cpus

- rpcs3/Crypto/unedat.cpp
- rpcs3/Crypto/unedat.h
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_overlay.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/rpcs3qt/main_window.cpp
* Return EFSSPEIFIC if encountered corrupted EDAT or an unmatched key in sys_fs_open and sys_fs_read.
* Fix `validate_dev_klic()` for license-free EDAT.
* Fix `EDATADecrypter::ReadData()` for when size + pos > file_size but pos < file_size.
* Try to save up to 16 decryption keys. Educated guess based on NPDRM file descriptors count llimit.
* Return LICENCE_NOT_FOUND if needed RAP file is not found in sceNpDrmIsAvailable.
* Check additional sys_fs_open errors for sceNpDrmOpen. (EISDIR, ENOTMOUNTED)
Attempts to fix:
#10984 
#3841
> Fixes of PS3 filesystem EDAT/SDAT handling

- rpcs3/Emu/RSX/GL/GLExecutionState.h
- rpcs3/Emu/RSX/Program/CgBinaryFragmentProgram.cpp
- rpcs3/Emu/RSX/Program/CgBinaryProgram.h
CGdisasm is now only used to process data from the host system where there is no mismatch in endianness. Restores the disassembler to working state.
> rsx: Restore shader disassembler to working state

- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- Resets upscaler on settings change. Although FSR is currently marked as a dynamic config option, it couldn't change during gameplay.
- Fixes a theoretical bug that led to an unwanted respective missing call to scale_output when you change the upscaler in the settings just at the right moment
- Improves the FSR sharpening strength tooltip area by introducing a parent widget as tooltip target
> Vulkan: Make upscaler dynamic (FSR on/off)

- rpcs3/Emu/system_config.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/settings_dialog.cpp
> Qt: Fix initial TSX selection in settings dialog 

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellNetCtl.cpp
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/Modules/sceNp2.cpp
- rpcs3/Emu/Cell/Modules/sceNp2.h
- rpcs3/Emu/Cell/Modules/sceNpSns.cpp
- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/NP/fb_helpers.cpp
- rpcs3/Emu/NP/generated/np2_structs.fbs
- rpcs3/Emu/NP/generated/np2_structs_generated.h
- rpcs3/Emu/NP/np_allocator.h
- rpcs3/Emu/NP/np_cache.cpp
- rpcs3/Emu/NP/np_cache.h
- rpcs3/Emu/NP/np_dnshook.cpp
- rpcs3/Emu/NP/np_dnshook.h
- rpcs3/Emu/NP/np_event_data.h
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/np_handler.h
- rpcs3/Emu/NP/np_helpers.cpp
- rpcs3/Emu/NP/np_helpers.h
- rpcs3/Emu/NP/np_notifications.cpp
- rpcs3/Emu/NP/np_requests.cpp
- rpcs3/Emu/NP/np_structs_extra.cpp
- rpcs3/Emu/NP/np_structs_extra.h
- rpcs3/Emu/NP/rpcn_client.cpp
- rpcs3/Emu/NP/rpcn_client.h
- rpcs3/Emu/NP/signaling_handler.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
-Contains the changes from Velocity's PR: https://github.com/RPCS3/rpcs3/pull/10547 rebased on Rpcn 0.4.0.
-Refactored np_handler(now everything is under a "np" namespace, the class implementation has been split into several files and a few header only objects have been added).
-Huge rework of the memory allocator for the match2 events data with an allocator that manages relocations when copying to game memory. This means that SceNp out of memory errors after playing a lot shouldn't happen anymore.
-Added a cache manager and an implementation of most *Local( np functions
Test server is: test-np.rpcs3.net (doesn't require email validation/token).
> Rpcn 0.5.0

- rpcs3/Emu/Cell/Modules/sceNp2.cpp
- rpcs3/Emu/NP/signaling_handler.cpp
Signaling thread would fail to send more than one signal_connect packet if the thread is never woken up.
Subsequent packets result in scheduling before going back to wait so no wakeup needed anywhere else.
> NP: add signaling_handler wakeup on connect queue

- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/util/logs.hpp
lv2_obj::awake_all() was not called due to a bug, fix that and log waiters forcefully signalled and unread events.
> sys_event: Fix PPU queue forced uproot of waiters

- rpcs3/Crypto/unedat.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
Fixes #11145, it seems like empty EDAT is valid and the game uses it in order to register a decryption key.
> Account empty EDAT

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/RSX/rsx_vertex_data.cpp
- rpcs3/Emu/RSX/rsx_vertex_data.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
Fixes behaviour of the classic glBegin/glEnd style of command streams.
- Just like classic GL, ATTR0 is the provoking attribute.
- Missing updates are carried forward from previous writes.
As this is a feature that has always been broken (and very sensitive to any changes), please test if any games break. Many engines use this unbuffered mode for elements where performance is not critical, such as game HUD, menus or billboarded ingame effects (fog, fire, halos/coronas, etc)
Fixes https://github.com/RPCS3/rpcs3/issues/7076
> rsx: Fix immediate-mode rendering

- rpcs3/rpcs3qt/log_frame.cpp
"Always" messages are supposed to be humanly readable
> Qt: only show prefix for fatal messages

- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/memory_string_searcher.cpp
This tool has been renamed to "Memory Searcher". If one-to-one string is found, there will be no peek of it because it is basically the same as the inputted string. Turned out case-insensitive string search caused a log buffer overflow, fixed that.
> Memory Searcher: Peek full string in log, fix case-insensitive search

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
Continuation of [#8137](https://github.com/RPCS3/rpcs3/pull/8137/commits/2bc05ab216dcad314fd8c40dea75b8c24f527b72).
> lv2: Add missing PPU reservation disowning in lv2_obj::yield

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
* Implement ENAMETOOLONG.
* If path argument is not prefixed with atleast one delimiter, return ENOENT as one of the first encountered checks.
* True addressee PS3 memory validity checks have been implmeneted for path argument.
> sys_fs: Place all path-format checks upfront, implement more checks

- rpcs3/CMakeLists.txt
- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
This is helpful for distros and for other users that may install rpcs3 to a non-standard path. For example a distro may want `/usr/games/rpcs3`, `/usr/share/games/rpcs3/` or another arbitrary path.
Reference: https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html
> cmake: Use GNUInstalldirs

- rpcs3/Emu/Io/Turntable.cpp
Fast interrupt transfers allows for more consistent/expected inputs when using non-PS3 turntables. Tested by other DJ Hero players, with very positive feedback.
Also add missing mutex, as described in this review comment: https://github.com/RPCS3/rpcs3/pull/11188#discussion_r754602331
> sys_usbd: make emulated turntable interrupt transfer as fast as possible

- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Current lavapipe version now has support for shaderStorageBufferArrayDynamicIndexing
> vk: Remove lavapipe workaround

- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
Even when DATADIR is defined the other paths may still be correct.
NOTE: I did not test AppImage, but I think this should work, please confirm.
See: https://github.com/RPCS3/rpcs3/pull/11189#issuecomment-977515204
Edit:
Fixes: https://github.com/RPCS3/rpcs3/issues/11195
> rpcs3: Fix the DATADIR path for AppImage

- rpcs3/rpcs3qt/emu_settings.cpp
Avoids getting a warning about obsolete config when going into configuration if some log options are set.
> Ignore Log subsection for config obsolete check

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/usb_device.cpp
- rpcs3/Emu/Io/usb_device.h
Change from a global locking to a mutex for the transfers(mutex_transfers) and reliance on sys_usbd internal locking(which changes some transfer into busy loops for passthroughs), also adds a mutex specifically for the ppu dequeue.
All the internal locks are moved into functions and only the global usb_handler_thread lock is accessible to sys_usbd functions.
Fixes https://github.com/RPCS3/rpcs3/issues/11201 and https://github.com/RPCS3/rpcs3/issues/8666.
> sys_usbd improvements

- .ci/build-freebsd.sh
- .ci/install-freebsd.sh
Downstream made a [similar change](https://github.com/freebsd/freebsd-ports/commit/11e15e9fac67). To be simplified once [llvm13 includes libc++](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=260139).
Now building libc++ as using only headers is [error-prone](https://github.com/freebsd/freebsd-ports/commit/6551900e74bb). Hopefully, the whole build isn't too slow.
> CI: upgrade FreeBSD to Clang 13

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/system_utils.cpp
- rpcs3/Loader/ELF.h
- rpcs3/Loader/PSF.cpp
- rpcs3/Loader/PUP.cpp
- rpcs3/Loader/TROPUSR.cpp
- rpcs3/Loader/TRP.cpp
* Always use strict reading mode whenever size is above 1MB, allotting less than this amount is not expected to fail.
* If the desired size of read elements in the container is 0, we did not empty the container as we should.
> fs: Fix POD vector reading, always use optimized strict reading mode

- Utilities/Thread.cpp
Use the word "executing" instead of "reading" when PC matches addressee VM memory offset.
> logging: Tell apart PPU access violation caused by executing unmapped memory

- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/Program/ProgramStateCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- Ignore all processing for NOP instructions, it is legal to contain garbage in other fields.
- Fix static flow instructions jumping over the input scanning block.
- Add missing depth32f format for ogl.
Fixes https://github.com/RPCS3/rpcs3/issues/11235
> rsx: Improve vertex program analyzer

- rpcs3/display_sleep_control.cpp
Warnings are bad, mkay? It's already defined in the vcxproj.
`6>D:\GitHub\rpcs3\rpcs3\display_sleep_control.cpp(4,1): warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition
6>D:\GitHub\rpcs3\rpcs3\display_sleep_control.cpp : message : see previous definition of 'WIN32_LEAN_AND_MEAN'`
> Remove unnecessary define

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Proof (from Discord):
```
0x00000000006f190e in s_terminate_handler_set::{lambda()#1}::operator()() const::{lambda()#1}::_FUN() ()
(gdb) bt
#0  0x00000000006f190e in s_terminate_handler_set::{lambda()#1}::operator()() const::{lambda()#1}::_FUN() ()
#1  0x00007f4a401e529c in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>)
at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#2  0x00007f4a401e5307 in std::terminate() () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#3  0x00007f4a401e55a9 in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*))
(obj=<optimized out>, tinfo=0x7f4a40349208 <typeinfo for std::out_of_range>, dest=0x7f4a401fb2c0 <std::out_of_range::~out_of_range()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#4  0x00007f4a401dc47f …
```
> cellSaveData: prevent some potential crashes due to corrupt files

- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.ui
- Adds the stick multipliers to the keyboard pad handler. It works basically the same as in other pad handlers.
- Fixes a bug that caused the stick values of the keyboard pad handler to be always at least 1.
This means that there was no way to fully reach the maximum value for up or left with the keyboard.
I doubt that this changes anything for anyone, but it was wrong nonetheless.
> Input: Add stick multipliers to the keyboard pad handler

- Utilities/JIT.cpp
- Utilities/JIT.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.h
- rpcs3/Emu/RSX/GL/GLTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKQueryPool.cpp
- rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/util/shared_ptr.hpp
Optimize CPU capability tests for arch-tuned builds.
Separate streaming and non-streaming utilities.
Rewritten copy_data_swap_u32(_cmp) with AVX2 path.
> BufferUtils: refactoring

- .ci/deploy-linux.sh
Fixes a serious problem with non-debian *nix OSes.
The wayland client library is different (so exports are not 1:1) on arch based distros at the very least and since the windowing APIs are linked to the graphics drivers, this leads to a hilarious situation where the appimage (which is ubuntu) cannot run on arch with mesa drivers. Well, technically it runs but no vulkan capable GPU can be enumerated.
> Drop libwayland-client from official appimages

- BUILDING.md
Provided build steps didn't work on Fedora 35, these packages seem to settle things 😄
Fedora defaults to Pipewire... with Wireplumber as a session manager - or the 'basic' one built into Pipewire.
(Context: this may change by DE/WM as they may tend to launch this on login.  eg: `i3`, `sway`.  Other times with systemd user services)
Through dependency resolution we find a conflict with `jack-audio-connection-kit-devel` (pre-change).
This wants to pull in `jack-audio-connection-kit` that conflicts with `pipewire-jack-audio-connection-kit`.  We want `pipewire-jack-audio-connection-kit-devel` instead!  
Aside from that, some QT dependencies: 
- `qt5-qtmultimedia-devel`
- `qt5-qtsvg-devel`
> Fedora (35): Adjust to Pipewire adoption ++QT deps

- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_net.h
Improve net logging.
Should allow latest vsh to load (Depending on windows version apparently..)
Seems to work on 19043.1415, but not on 22000.348 - https://docs.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse ?
```
[0x0001b1e0] sys_net: sys_net_bnet_socket(family=INET, type=DGRAM, protocol=IPPROTO_IP)
[0x0001b3c4] sys_net: sys_net_bnet_setsockopt(s=54, level=SYS_NET_IPPROTO_IP, optname=IP_TTL, optval=*0xd00b1130, optlen=4)
[0x0001b3c4] sys_net: optval: 0x00000001
[0x0001b3c4] sys_net: sys_net_bnet_setsockopt(s=54, level=SYS_NET_SOL_SOCKET, optname=SO_RCVTIMEO, optval=*0xd00b1138, optlen=16)
[0x0001be74] sys_net: sys_net_bnet_bind(s=54, addr=*0x13e0c64, addrlen=16)
[0x0001be74] sys_net: Trying to bind 0.0.0.0:9309
[0x0001b1e0] sys_net: …
```
> Handle SYS_NET_IPPROTO_IP get/setsockopt

- rpcs3/Emu/Cell/Modules/cellAtrac.cpp
- rpcs3/Emu/Cell/Modules/cellAtrac.h
- rpcs3/Emu/Cell/Modules/cellAtracMulti.cpp
- rpcs3/Emu/Cell/Modules/cellAtracMulti.h
- rpcs3/Emu/Cell/Modules/cellFiber.h
- rpcs3/Emu/Cell/Modules/cellGifDec.h
- rpcs3/Emu/Cell/Modules/cellPamf.cpp
- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/Cell/Modules/sceNpTus.h
- rpcs3/Emu/Cell/Modules/sys_crashdump.h
Just some random stuff I found that might be right or wrong.
> HLE: Fix some types

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
Modern implementations of memcpy will use the REP MOVSB instruction when the size of the copy is large, and when the CPU is known to have a fast implementation of the instruction. The speed of the instruction is checked through 2 bits on cpuid, ERMS (enhanced rep movsb) and FSRM (fast short rep movsb). Support for detecting these flags has been added, and you will see in your log whether your CPU supports these flags or not.
On intel ERMS is supported as far back as ivy bridge, while FSRM is supported on icelake and up.
On amd, only the latest zen3 cpus have either (zen3 has both ERMS and FSRM)
Because I don't have access to every cpu out there, I based the thresholds for when rep movsb is preferred over simd copies roughly off of glibc.
On my 7700K, I couldn't measure any positive or …
> SPU: Use REP MOVSB in do_dma_transfer

- rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
Improve SingStar emulation for the games which use cellAudioInGetAvailableDeviceInfo. Partial fix for #7739.
- SingStar MegaHits (playable, but everything is green/blue)
- SingStar Ultimate Party (playable, but everything is green/blue)
- SingStar Frozen (playable, but everything is green/blue)
- SingStar ABBA (detects the microphone, but then freezes)
- SingStar Vol 2 (detects the microphone, but then freezes)
- SingStar Vol 3 (detects the microphone, but then freezes)
Other games are not fixed: 
- SingStar Back to the 80s
> USB: Improve SingStar emulation

- .ci/build-mac.sh
- .cirrus.yml
- 3rdparty/hidapi/CMakeLists.txt
Fixes hidapi/CMakeLists.txt (thanks to xddxd, who also helped me with ccache) and adds a Cirrus task for macOS builds.
The task generates both a .7z and a .dmg (which also includes a link to the Applications folder and a link to the Quickstart page).
Since RPCS3.app is not signed, the user must right-click on it and select "Open" when attempting to run it for the first time.
> Add macOS CI builds

- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/System.h
Always initilialize method registers to valid values. In addition, untemplate some stuff. (using template is unjust for these simple cases, and may slow down compilation)
Fixems that misleasing "Unknown context dma 0x0"  after a different crash at RSX startup. This happens because we try to log method registers values but some are invalid in early RSX state.
> rsx: Fix wrong fault report in initialization

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/Common/texture_cache.h
Fixes https://github.com/RPCS3/rpcs3/issues/11316
> rsx: Minor surface cache improvements

- Utilities/Thread.cpp
- Utilities/simple_ringbuf.cpp
- Utilities/simple_ringbuf.h
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_rsxaudio.h
- rpcs3/Emu/Cell/lv2/sys_uart.cpp
- rpcs3/Emu/Cell/lv2/sys_uart.h
- More than half of packets are now implemented
- Warning fix in lv2.cpp
HDMI now works in vsh
> More sys_uart packets

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/RSX/Common/surface_utils.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- rpcs3/Emu/RSX/Common/texture_cache_utils.h
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/rsx_utils.h
- Max RSX pitch is 17 bits (65536) so use 32-bit integers for that. It is possible for wide 1D textures to hit this limit. 4096-length RGBA32F data can be used as a compute SSBO and will consume pitch greater than UINT16_MAX.
- Also adds a fallback for cellGameDataCheckCreate2, old SFOs do not contain a APP_VER key, only a VERSION key. This allows old titles to boot without any patches applied if they rely on matching application version with data version (e.g verify HDD installed data)
Fixes https://github.com/RPCS3/rpcs3/issues/9100
> rsx: Fix pitch bit-width in texture+surface cache

- rpcs3/Emu/system_config.h
- rpcs3/headless_application.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/render_creator.cpp
macOS only supports OpenGL 2.1 / 4.1 core, which is not enough for RPCS3.
This PR effectively makes Vulkan (moltenVK) mandatory.
OpenGL is disabled on macOS like Vulkan is disabled on unusupported GPUs, and as such, it is not removed completely (as that would require major changes to the code).
> Disable OpenGL on macOS

- rpcs3/Input/keyboard_pad_handler.cpp
Arrow keys are considered to be part of the keypad on macOS.
While the d-pad can be remapped to the "numpad" arrows by the user, it causes inputs to work incorrectly, so we need to intercept these inputs anyway.
> macOS: Fix arrow keys

- Utilities/Thread.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
On macOS, this sets maxfiles to 4096, as well as thread stack size to 2M (fixes shader cache and SPU LLVM).
maxfiles are logged to both file and stderr on macOS/Linux/BSD.
> Fix macOS maxfiles/Shader Cache/SPU LLVM, and log maxfiles on *NIX

- 3rdparty/wolfssl/extra/win32/user_settings.h
- 3rdparty/wolfssl/wolfssl.vcxproj
- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/rpcs3qt/curl_handle.cpp
Fixes loading cacert.pem from Unicode directories, e.g. when RPCS3 is placed in a directory with Unicode characters.
> WolfSSL: Use a custom UTF-8 aware fopen on Windows

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Crypto/aes.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/VFS.cpp
- rpcs3/main_application.cpp
- rpcs3/util/shared_ptr.hpp
Removed the the dependency on QT initialization, use it for vfs::mount. `weakly_canonical` allows resolving of paths that do not exist, unlike `canonical` which returns an empty string for it which is not intended. Didn't test.
> fs: Reimplement path resolving using std::filesystem::weakly_canonical

- Utilities/File.cpp
- rpcs3/Emu/VFS.cpp
> VFS: fix missing path deliminators

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/VFS.cpp
- rpcs3/main_application.cpp
The changes in #11178 broke path handling for Windows users as seen in #11360. The fixes in #11365 did not fully fix every use case and there's still a lot of complaints about broken path handling causing various issues.
Pull request #11367 aims to fix the remaining bugs, but I think we should roll back the entire feature and take our time to implement it properly instead of rushing in with one quickly merged and poorly tested fix PR after another.
> Revert recent file system changes

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
This is a hack, ideally we should be using coverage-based masking when writing the exploded texture. We do not have access to the fragment coverage mask and it is non-trivial to integrate it in a competent manner. RSX does not do hw resolve, instead, resolve is done using specialized shaders that sample the MSAA memory as a flat 2D texture. On PC GPUs, if sample shading rate is not forced, we sometimes get holes where some fragment samples are skipped and when we blow up the image holes appear. Forcing unique samples across the board fixes this issue. This is the same root cause as the "MSAA wireframe bug" that we had for AMD navi GPUs.
Fixes https://github.com/RPCS3/rpcs3/issues/8612
> vk: Enable shading rate hack for all GPUs

- rpcs3/rpcs3qt/settings_dialog.cpp
On current master, the enabled state of the accurateXFloat checkbox may not show the intended behaviour.
> Qt: Fix accurateXFloat enabled state in settings dialog

- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
Got annoyed by false negatives in ppu_vpu test.
> PPU LLVM: improve accuracy of VSL/VSR

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLTypes.h
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/rsx_utils.h
TODO:
N/B: Colormask for XBGR is not subject to swapping - verified with hw test.
Fixes https://github.com/RPCS3/rpcs3/issues/8902
> rsx: Surface format remapping enhancements

- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
Fixes https://github.com/RPCS3/rpcs3/issues/11377
> rsx: Fix invalid descriptor setup if subdraw0 has broken vertex setup

- Utilities/JIT.h
- Utilities/Thread.cpp
- rpcs3/Emu/Cell/PPUFunction.cpp
- rpcs3/Emu/Cell/PPUInterpreter.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/util/simd.hpp
- rpcs3/util/sysinfo.cpp
Some other refactoring.
Use efficient runtime dispatch for SSSE3 version of VPERM (built at runtime) and fallback. The main point is that the final function doesn't contain branches for runtime dispatch, it's only done at program startup. While it may seem silly, it completely bypasses compiler shenanigans regarding different target options (for example, if target differs for two functions, one cannot inline another in GCC/clang; MSVC has some problems as well).
ARM version of VPERM instruction is also written.
> Build VPERM At Runtime (Again?)

- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.h
Checks for patch updates when opening the patch manager.
TODO:
- add some options
- check first, download later
> Qt: Automatically check for patch updates

- rpcs3/rpcs3qt/settings_dialog.cpp
For some reason rpcs3 crashes when I restore the defaults of multiple configs one after another in the settings dialog.
Using the other signal seems to work.
I don't wanna investigate this nonsense though, so I'll just accept the fix as is.
> Qt: fix RestoreDefaults crash

- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/vkutils/descriptors.cpp
- rpcs3/Emu/RSX/VK/vkutils/descriptors.h
- rpcs3/Emu/RSX/VK/vkutils/memory.h
- rpcs3/Emu/RSX/VK/vkutils/sampler.cpp
Multiple fixes are going to be added to this. Highlights:
- Keep maximum number of samplers allowed under control. This should solve a lot of VK_ERROR_DEVICE_LOST errors experienced on nvidia hardware. NV cards can only keep 4000 (actually 4096) sampler objects while other vendors can handle more than 1 million. This change attempts to keep the allocated number under 75% of max capacity and also tries to never exceed 2048 allocated samplers at any given time. In practice we will go over this limit, but we have enough headroom to avoid maxing out the driver.
- Fix lost descriptor updates when pushing copy operations. The previous CB may have queued writes that then need to be copied after the fact, and also if all we do is make a copy without push or make a copy but only push …
> vk: Fix VK_ERROR_DEVICE_LOST crashes

- rpcs3/Emu/Cell/Modules/cellAdec.cpp
- rpcs3/Emu/Cell/Modules/cellVdec.cpp
Regressed by https://github.com/ffmpeg/ffmpeg/commit/626535f6a169 + https://github.com/ffmpeg/ffmpeg/commit/56450a0ee4fd. From [error log](https://github.com/RPCS3/rpcs3/files/7914663/rpcs3-0.0.20.13190.log):
```c++
rpcs3/Emu/Cell/Modules/cellAdec.cpp:325:12: error: assigning to 'AVCodec *' from 'const AVCodec *' discards qualifiers
codec = avcodec_find_decoder(AV_CODEC_ID_ATRAC3P);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rpcs3/Emu/Cell/Modules/cellAdec.cpp:326:19: error: assigning to 'AVInputFormat *' from 'const AVInputFormat *' discards qualifiers
input_format = av_find_input_format("oma");
^~~~~~~~~~~~~~~~~~~~~~~~~~~
rpcs3/Emu/Cell/Modules/cellAdec.cpp:331:12: error: assigning to 'AVCodec *' from 'const AVCodec *' discards qualifiers
codec = avcodec_find_decoder(AV_CODEC_ID_MP3); …
```
> Unbreak build with FFmpeg 5.0

- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/VK/VKCompute.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKHelpers.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
- rpcs3/Emu/RSX/VK/vkutils/swapchain.hpp
- rpcs3/Emu/system_config.h
Fixes various black screens in games such as Life is Strange (might fix #11363), and projected shadows in Project DIVA Dreamy Theater.
Also adds a code path for Apple GPUs in case driver-specific workaround are needed in the future.
By default, native float16 is now disabled (fixes NieR), and timer accuracy is set to "as host" by default (partially fixes The Last of Us and other games, with no side effects so far, although technically none of the options currently provides very accurate timers).
> Remove macOS swizzling workarounds, initial support for Apple GPUs

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- Do not write out of bounds when loading resources in system memory
- Take subresource Z into account when calculating coverage. It is possible to have the first slice covered but have the rest missing, we can just reupload in such a case.
Fixes device lost crash in MLB series and maybe other titles.
> vk: Improve sanity checks around subresource gathers

- rpcs3/rpcs3qt/rpcn_settings_dialog.cpp
People were confused by the 2nd edit appearing as a line separator for the buttons.
> Add a QGroupBox in RPCN password window

- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Fix VkDeviceCreateInfo::pNext propagation. I think it broke during descriptor indexing implementation and a spec bug regarding some broken hyperlinks sent me looking in the wrong direction.
Fixes spammy error about usage of float16 types in SPIRV shaders when validation layers are active.
> vk: Fix float16 requirement issue

- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
A user experienced fs::file null handle around this function, haven't dug into it.
> overlay_controls.cpp: Improve image_info ctor withstandability

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/GL/GLTexture.h
- rpcs3/Emu/RSX/GL/GLTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKFormats.h
- Remove a check that stopped the src_gcm_format field from the typeless_info structure from being filled. We rely on this structure to determine whether to do assisted transfers later - keeping it blank can cause unexpected aspect mismatch further down the pipe.
- Properly implement bitcast compatibility checks for OpenGL.
- Register missing R32F format class for OpenGL
Fixes https://github.com/RPCS3/rpcs3/issues/11441
Fixes https://github.com/RPCS3/rpcs3/issues/11434
> rsx: Minor texture fixes

- .ci/build-mac.sh
This should prevent any future errors if the brew packages are updated.
> macOS CI: Don't hardcode moltenVK and llvm version-specific paths

- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/vkutils/data_heap.cpp
- Fix scratch memory calculations for D16F (emulated with D32F)
- Fix grow behaviour when the max heap limit is reached.
Fixes https://github.com/RPCS3/rpcs3/issues/11451
Fixes https://github.com/RPCS3/rpcs3/issues/11450
> vk: Improve working buffer behavior

- rpcs3/Emu/Cell/SPUThread.h
Debug build with clang-13 fails with "undefined references" to the
static const members in `spu_channel` class. This patch replaces the const
definitions with `constexpr` constants.
The following is the output when the build fails:
```
$ CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Debug ../rpcs3 && make
...
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/mm_joystick_handler.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/pad_thread.cpp.o
[100%] Building CXX object rpcs3/CMakeFiles/rpcs3.dir/Input/xinput_pad_handler.cpp.o
[100%] Linking CXX executable ../bin/rpcs3
/usr/bin/x86_64-pc-linux-gnu-ld: Emu/librpcs3_emu.a(SPUASMJITRecompiler.cpp.o): in function `operator()':
/home/hyogi/workspace/rpcs3/rpcs3/rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp:1358: undefined …
```
> Fix linkage error on debug build with clang-13

- Utilities/Timer.h
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.h
- rpcs3/Input/keyboard_pad_handler.cpp
DRAFT: multithreaded pad handlers (1 thread each + hid enumeration threads).
I only had a couple of USB ports free, so I could only test with 3 controllers (1 XInput, 1 DS4, 1 MMJOY) and the keyboard.
The following timings represent the averages and the maxima of each handler, gathered over 1 second each.
**Old timings (current master):**
```
E Input: Timings (ms): Keyboard: avg=0.000004, max=0.002000 / DualShock 4: avg=0.005743, max=0.014000 / XInput: avg=0.041130, max=0.080000 / MMJoystick: avg=0.005774, max=0.062000 / Total: avg=0.055034, max=0.117000
E Input: Timings (ms): Keyboard: avg=0.000006, max=0.001000 / DualShock 4: avg=0.010601, max=3.781000 / XInput: avg=0.041367, max=0.106000 / MMJoystick: avg=0.005719, max=0.028000 / Total: avg=0.060065, max=3.827000
E Input: Timings (ms): …
```
> Input: Improve pad latency

- rpcs3/Emu/NP/np_requests.cpp
- rpcs3/Emu/NP/rpcn_client.cpp
- rpcs3/Emu/NP/rpcn_client.h
Adds support for cookies to be included in the ticket(not 1:1 with ps3 but no information could be found about cookie encoding in the ticket).
Merge needs to be synced with rpcn update.
> rpcn: add cookie impl to tickets

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- Creating new images is expensive. We can keep around a set of images that have been recently discarded and use them instead of creating new ones from scratch each time. Gives a slight 2-5% performance boost in tested scenarios.
- Also fixes several bugs in the texture cache. An image cache existed before, but it was completely useless as the core did not dereference resources properly. The new mechanism introduces an ordered eviction queue, with oldest resources getting removed first to improve the hit-rate.
- Adds the disposable_t wrapper for the garbage collector which will be used to manage resources going forward. This migration will take place in the future, the old arrays of unique_ptr remain.
- Fixes a use-after-free inside the driver when closing native UI dialogs. Not sure how …
> vk: Use image hot-cache for faster allocation times

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKTexture.cpp
Fix out-of-bounds access when tagging memory for duplicate removal. The algorithm needs to be moved to the GPU down the line to make use of hardware occlusion queries, but for now, let's also add some overrun cookie to ensure we're not corrupting the heap.
Fixes https://github.com/RPCS3/rpcs3/issues/11495
Fixes https://github.com/RPCS3/rpcs3/issues/11435
> rsx: Fix duplicate data removal checks in surface cache

- rpcs3/Emu/system_config.h
- rpcs3/Emu/system_config_types.cpp
- rpcs3/Emu/system_config_types.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Implements naive multithreading for input handlers.
Adds the option to choose between single-threaded and multi-threaded pad handlers.
This may improve latency if you play with 2 or more different pad handlers.
It probably won't make a difference if you only play with 2 or more pads of the same type (e.g. only DualShock3).
But I also added a config only option "Pad handler sleep (microseconds)" for the hardcore input latency fanatics.
This setting can be used in both single and multithreaded modes.
By fiddling with that value (0-100000), you may notice faster response times.
I observed a theoretical decrease in latency by 700-800 microseconds in the best case scenario.
Keep in mind that setting this value to something close to 0 will increase your cpu usage on each used core drastically …
> Input: multithreaded handlers

- rpcs3/Emu/RSX/VK/VKAsyncScheduler.cpp
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.h
- rpcs3/Emu/RSX/VK/VKCommandStream.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKHelpers.h
- rpcs3/Emu/RSX/VK/VKResourceManager.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/commands.cpp
- rpcs3/Emu/RSX/VK/vkutils/commands.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
- rpcs3/Emu/RSX/VK/vkutils/image_helpers.cpp
- rpcs3/Emu/RSX/VK/vkutils/image_helpers.h
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
- rpcs3/Emu/RSX/VK/vkutils/scratch.h
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
- rpcs3/Emu/system_config.h
- rpcs3/Emu/system_config_types.cpp
- rpcs3/Emu/system_config_types.h
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/tooltips.h
Reimplements the async task scheduler to work without violating spec so much with the old hacky synchronization method. This allows GeForce drivers newer than 470 to use this feature for users with large GPUs.
Fixes https://github.com/RPCS3/rpcs3/issues/9968
> Spec-compliant async compute for texture streaming

- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
Offhanded yet loyal to proper PS3 emulation semantics fix for the problem mentioned in #11501. 
PS3 savedata filenaming format is fortunately pretty limited. Only uppercase A-Z, `_`, space, dot and `-` are allowed. And only if fitting the notorious 8.3 naming length constraints.
> cellSaveData: Check filename format of savedata files

- rpcs3/Emu/RSX/VK/VKDMA.cpp
It is possible to lose data when uploading since the result of map_dma can change types and handles. Not a problem when using passthrough DMA, but this extension does not work properly on NVIDIA + windows forcing us to fall back to mixed mode. When a copy-based slice takes over for a passthrough slice, leakage can occur. Simply initialize the block memory on creation instead of using uninitialized contents. It costs almost nothing and new blocks are spawned so rarely that it really shouldn't be a problem.
Fixes random weirdness on NVIDIA cards when running async texture streaming.
> vk/dma: Initialize COW DMA block contents to avoid leaks

- .ci/build-mac.sh
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/VK/vkutils/instance.hpp
- rpcs3/Emu/system_config.h
- rpcs3/Emu/system_config_types.cpp
- rpcs3/Emu/system_config_types.h
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Since MoltenVK 1.1.7, due to synchronization issues making API calls randomly inaccurate, software emulation is used to simulate vkSemaphore, rather than MTLFence, when running under Rosetta or on NVIDIA. Software emulation causes screen tearing and a huge performance loss compared to MTLFence, with no real benefits for RPCS3.
This PR changes the default behaviour to MTLEvent + MTLFence (the former takes priority when not running under Rosetta or on NVIDIA), and adds a new option in the Debug tab to let developers change it at runtime.
Note that when using the loader library (libvulkan.1.dylib) instead of directly loading MoltenVK (libMoltenVK.dylib), the configuration cannot be set at runtime and the ``MVK_ALLOW_METAL_EVENTS`` and/or ``MVK_ALLOW_METAL_FENCES`` environment variables must …
> macOS: Add MoltenVK Semaphore setting and fix performance regression

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
I've had this lying around for ages but never added it because I wanted to implement the shortcut manager first (which never happened).
So I'll just make a draft and see what happens.
> rsx: add boost mode shortcut

- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Pass host GPU state directly to CELL threads. CELL synchronizes with RSX, but this is handled on the CPU using fake signals that do not reflect the actual nature of data. Some games have tightly synchronous engines that require RSX semaphores to be accurate. This is not a problem for OpenGL due to how the texture system works there, but vulkan has a simulated coherent FlexIO DMA layer which persists between draws. This means that we need to tell the game when it is safe to clobber memory for example instead of just signaling the semaphores when we see them on the CPU side of things.
Fixes flickering vegetation in Avatar. ~~In theory, this should also fix flickering in Toy Story 3 without strict mode enabled.~~
Note that the "Allow Host GPU Labels" toggle needs to be checked to enable this …
> vk: Allow host GPU to synchronize directly with CELL via RSX semaphores

- rpcs3/main.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/persistent_settings.h
1. This should simplify testing many games (for example for PR testing) by looking at the time of day of the 'last played' section and checking if it occurs after the time point that you booted RPCS3. I.e. Simplifying the process of knowing which games you have already tested from a large list.
2. By knowing current time with date when RPCS3 boots viewers/recipients of the log can attest early the provided logs from users such as the of PR testers or of users on forums instead of wasting time reading irrelevant logs.
> Qt: show time of day in 'last played' game info, log current time when RPCS3 boots

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
There are still some kinks to work out. Host labels do not fix all the bugs which means I missed something. Revert to old behavior for now.
Fixes https://github.com/RPCS3/rpcs3/issues/11571
Fixes https://github.com/RPCS3/rpcs3/issues/11573
Fixes https://github.com/RPCS3/rpcs3/issues/11574
> vk: Do not enable passthrough DMA unconditionally (yet)

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
Fixes problems with implicit view types derived from image dimensions.
> rsx: Downgrade depth-1 3D images to 2D

- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
Fixes mismatched image type lookups that can cause flickering. While auto-downgrading also works, it may break games that rely on bad behavior on real hardware, so let's just let the games decide what they want to do.
> vk: Encode view type when caching images

- rpcs3/Emu/RSX/Common/profiling_timer.hpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/Common/surface_utils.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Common/texture_cache_helpers.h
- rpcs3/Emu/RSX/Common/time.hpp
- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/RSXFIFO.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRenderTypes.hpp
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
Mostly fixes some consistency issues with the texture cache, which are easier to notice when MSAA is active. During this investigation I also realized some surface util methods are being called millions of times per second, so I converted them to templates which improves performance a bit. Also removed excessive calls to get_system_time() which reduces zcull latency significantly in some titles.
Needs performance and crash testing. Hopefully no regressions (I tested this quite a bit)
Fixes https://github.com/RPCS3/rpcs3/issues/9339
> rsx: Surface cache optimizations and other improvements

- rpcs3/Emu/system_utils.cpp
- rpcs3/Emu/system_utils.hpp
This makes it so GUI elements like game list and main window title bar use a simpler check for C00 unlock EDATs where it simply checks if .edat file with the required name exists. In-game sceNpDrmVerifyUpgradeLicense call still uses the full check. This remedies the slowdown of game list refresh introduced in the initial implementation and also appears to match XMB behavior.
> Use simpler C00 unlock EDAT check in GUI

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/Common/surface_utils.h
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- Remove archaic render_targets_config start-count object that is now just redundant and inefficient. It just led to overly verbose iteration code.
- Do not perform a full surface sync every draw call. This can harm performance when MSAA is enabled.
Followup to https://github.com/RPCS3/rpcs3/pull/11607
> rsx: Clean up surface cache routines around RTT invalidate

- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
Turns out we only handled ONE evdev event per loop...
That means the theoretical max was 1000 events per second per default due to the 1ms sleep of the pad thread.
Extensive movement of all sticks and triggers can easily cause a congestion and thus a "rubber banding" delay of the input.
It's very easy to repoduce and kinda funny to watch if you increase the pad thread sleep to 10ms.
To fix this, I now fetch all new events at once on each iteration.
The issue is now completely resolved on my slow laptop, no matter how long the thread sleeps.
fixes #11609
> evdev: fix latency issues

- rpcs3/Emu/RSX/Common/ranged_map.hpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.cpp
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
Implements a segmented lookup structure that optimizes collision testing. When trying to find a resource and/or its neighbours, there is no need to search through all available surfaces, we can determine from the ranged map a small subset of surfaces that have a higher chance of a successful hit. This can speed up texture cache lookups from the surface cache a fair bit. Things can be optimized further, but this is good enough for now.
> rsx: Implement segmented surface cache for faster performance

- rpcs3/Emu/Audio/FAudio/FAudioBackend.cpp
- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/Modules/cellSpurs.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_tty.cpp
- rpcs3/Emu/Cell/lv2/sys_uart.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/Emu/RSX/VK/VKAsyncScheduler.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/gcm_enums.cpp
- rpcs3/rpcs3qt/camera_settings_dialog.cpp
- rpcs3/util/atomic.cpp
Fixes the following clang warnings(gcc issues 3 additional warnings but they seem to be gcc miswarnings):
```
/Repos/rpcs3/rpcs3/util/atomic.cpp:936:6: warning: variable 'total' set but not used [-Wunused-but-set-variable]
u32 total = 0;
^
--
/Repos/rpcs3/rpcs3/Emu/Audio/FAudio/FAudioBackend.cpp:93:11: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
if (res = FAudioSourceVoice_FlushSourceBuffers(m_source_voice))
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--
/Repos/rpcs3/rpcs3/Emu/Cell/SPUThread.cpp:1605:86: warning: bitwise operation between different enumeration types ('vm::block_flags_3' and 'vm::alloc_flags') is deprecated [-Wdeprecated-enum-enum-conversion]
ensure(vm::get(vm::spu)->falloc(vm_offset(), SPU_LS_SIZE, &shm, …
```
> Warning Fixes

- Utilities/StrUtil.h
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.h
- rpcs3/Emu/RSX/Common/buffer_stream.hpp
- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.h
- rpcs3/Emu/RSX/GL/GLShaderInterpreter.cpp
- rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
- rpcs3/Emu/RSX/GL/GLVertexProgram.h
- rpcs3/Emu/RSX/Program/ProgramStateCache.h
- rpcs3/Emu/RSX/Program/ShaderParam.h
- rpcs3/Emu/RSX/Program/VertexProgramDecompiler.cpp
- rpcs3/Emu/RSX/Program/VertexProgramDecompiler.h
- rpcs3/Emu/RSX/Program/program_state_cache2.hpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKShaderInterpreter.cpp
- rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
- rpcs3/Emu/RSX/VK/VKVertexProgram.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
For non-skinning shaders, there is rarely any use of dynamic memory indexing (using a variable to calculate address). Instead, in most cases the non-uniform input comes in from the vertex attributes and the vertex program has a simple memory access pattern after compilation. Vertex programs have about 8KB of program memory we need to update every time the program is changed, but if the program has static memory addressing, the actual bits that will be consumed are known beforehand. We can therefore relocate the addresses and "pack" the data for each vertex program instead of updating a huge 8KB block each time. With this setup, the 8KB of updates shrinks down to a few dozen bytes per program which is significantly faster. Gives upto ~10% performance uplift in RSX-constrained scenarios.
> rsx: Implement relocatable vertex program constants for static programs [optimization]

- rpcs3/Emu/RSX/Common/texture_cache.cpp
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/VK/VKDMA.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- Fixes DeS crashing on loading levels. Fromsoft engine has some quirky PS3 behavior that is well known regarding dynamic image usage to get around some hw limitations. This can cause in-place swapping of locked regions, with no change to the underlying protection.
- Check for page holes when initializing DMA layer to fix games that use segfault handlers to initialize data.
- Skip unnecessary protect syscalls. They are not cheap.
Fixes https://github.com/RPCS3/rpcs3/issues/11549
Fixes https://github.com/RPCS3/rpcs3/issues/11703
> rsx: Fix possible crashing after surface cache refs PR

- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
- rpcs3/rpcs3qt/main_window.cpp
Should fix #11694 
To explain:
What happened was that if you opened the settings dialog directly after terminating the game, then waited until it was finished, and finally closed the dialog, RPCS3 would crash.
The immediate cause of the crash was a duplicate call to deleteLater of gs_frame, after the gs_frame was already destroyed.
By replacing Emu.Stop() with GracefulShutdown() in gs_frame::close(), the game window was now unknowingly closed recursively, causing RPCS3 to crash in some cases.
The reason as to why this is only an issue after opening and closing the settings dialog lies in the fact that we call QApplication::processEvents while we wait for the game to finish. Somehow the code does not return from one of the processEvents calls while the dialog is open, suggesting that the …
> Fix RPCS3 crash caused by double free of the game window

- Utilities/bin_patch.cpp
- rpcs3/Emu/vfs_config.cpp
- rpcs3/rpcs3qt/config_adapter.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/update_manager.cpp
- rpcs3/util/yaml.cpp
- rpcs3/util/yaml.hpp
- Adds missing check for invalid value nodes in the patch files. Fixes a validation issue where a comma was missing in the node Sequence.
- Added the node location to the log messages. This makes it much easier to find the error in the file.
- Added a collapseable detail textfield if the displayed log gets too long in the warning dialog.
Example:
> Patch Manager: Check for missing value nodes. Add node location to log messages. Add collapseable textbox to warning dialog.

- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_raw.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_raw.h
- rpcs3/Emu/Cell/lv2/sys_net/nt_p2p_port.h
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.h
Improves select interface and adds an implementation for P2PS sockets.
Fixes a bug in sendto for P2P sockets which didn't account for the extra 2 bytes for the vport in the return value.
> Various sys_net improvements

- rpcs3/rpcs3qt/log_viewer.cpp
- rpcs3/rpcs3qt/log_viewer.h
- Adds the ability to hide thread names
- Adds the ability to only show the last 10 lines of each thread since the last boot
> Log viewer: add thread options

- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
Snap resulting Z values to integral stops to try and account for precision errors.
The cause of the errors is actually the inversion of w. Large w values will give very small results that have tiny precision loss. The computed NDC Z is then very slightly outside the range we want (e.g 1.0000001 in a Z range of 0.99-1.0)
Fixes https://github.com/RPCS3/rpcs3/issues/11669
Fixes https://github.com/RPCS3/rpcs3/issues/11765
> rsx: Implement Z value snapping to account for precision errors

- Utilities/git-version-gen.cmd
- rpcs3/main.cpp
- rpcs3/rpcs3_version.cpp
- rpcs3/rpcs3_version.h
- rpcs3/rpcs3qt/about_dialog.cpp
- rpcs3/rpcs3qt/main_window.cpp
- Adjust git version script to cirrus ci logic
- Unify GUI version displays
The only version that is different is the game window due to some formatting.
And the update message is left unchanged due to some checks with upstream.
Local builds:
RPCS3 0.0.21-d2fed339 Alpha | da_branch | local_build
PR/Fork builds:
RPCS3 0.0.21-d2fed339 Alpha | da_branch
Master:
RPCS3 0.0.21-13444-d2fed339 Alpha
Ain the window title:
RPCS3 0.0.21-13444 Alpha
> Windows: Version display fixes

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
Atm we pretend we send the packets but don't, instead return -SYS_NET_ENETDOWN.
Fixes https://github.com/RPCS3/rpcs3/issues/9293
Fixes https://github.com/RPCS3/rpcs3/issues/9360
> sys_net: SYS_NET_ENETDOWN for offline dns rqsts

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
On closing dnshook was destroyed before network_context which could still hold shared_ptr of lv2_socket_native objects.
Upon nc termination destructor was called which called close() which called a dnshook method and crashed.
Now just closing the socket if necessary and ignore dnshook in the destructor(this doesn't affect in-game behaviour as the socket can be removed from idm only through close() ).
> sys_net: Fix race between dnshook and nc

- Utilities/bin_patch.cpp
- rpcs3/util/yaml.cpp
In older versions of RPCS3, you were able to use negative values for unsigned integers. However, with the yaml-cpp update in #10961 this was no longer possible, as yaml-cpp cannot read negative values as unsigned integer anymore.
This PR makes it so negative values can be used again. If a value fails with u64 read (default), then it will try s64 instead.
> Add signed integer support for game patches

- rpcs3/Emu/Cell/Modules/cellGame.cpp
Makes the whole cellGameGetParamString code a bit more readable.
I found the old code unnecessarily confusing.
Also changes the logic a bit:
- Add TODO to cellGameGetParamString check since it should theoretically only exist in debug mode
- Adds some checks to make sure that the getter is called when an access preparation function was set
- Restrict access by default
> cellGameGetParamString: improve readability and add some logic changes

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- rpcs3/Emu/Cell/Modules/cellVdec.h
- rpcs3/util/media_utils.cpp
- Implemented a missing error CELL_VDEC_ERROR_SEQ in cellVdec.
The error is returned whenever a function is called during the wrong state of the sequence decode.
This could have an impact on all games and might break some (hopefully none) while fixing others.
- Fixed the output line offsets for YUV formats (which fixes video output issues in Uncharted 2)
- Added lots of error handling that was missing before. This might or might not impact some games.
- Added a bunch of other random stuff that's probably not gonna change anything
Apparently also fixes #4167
Also seems to fix #8394
> [TESTERS NEEDED] cellVdec overhaul -> fixes broken videos in Uncharted 2

- rpcs3/rpcs3qt/pad_settings_dialog.cpp
Fixes a crash when opening the pad settings before the pad handlers are initialized.
fixes #11844
> Qt: fix access to uninitialized Pad object

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/util/atomic.cpp
* Notify callback in wait engine was implemented with theoretical optimization in mind. It is necessary for PPU threads (no-TSX). However it seems that removing it actually improves performance in some cases. Please report testing results, especially for TSX-FA if possible.
> [Need test] CPU optimizations

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- Do not send any packets to av while the decode process was restarted by the game.
- Send AU_DONE before PICOUT
- Add some more logging
fixes #11853
> [TESTERS NEEDED] Fix cellVdec Sequence Restart regression

- Utilities/cfmt.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
- Adds an option to the log frame to enable/disable the cell error aggregation
- Adds a missing space to cell error messages
- Check if the fmt exists
> CellError log improvements

- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Cell/Modules/cellKb.h
- rpcs3/Emu/Cell/Modules/cellMouse.cpp
- rpcs3/Emu/Cell/Modules/cellMusic.cpp
- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
- rpcs3/Emu/Cell/Modules/cellOskDialog.h
- rpcs3/Emu/Io/KeyboardHandler.cpp
- rpcs3/Emu/Io/KeyboardHandler.h
- rpcs3/Emu/Io/MouseHandler.h
- rpcs3/Emu/Io/Null/NullKeyboardHandler.h
- rpcs3/Emu/Io/Null/NullMouseHandler.h
- rpcs3/Emu/Io/interception.cpp
- rpcs3/Emu/Io/interception.h
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlay_save_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_user_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/Input/basic_keyboard_handler.cpp
- rpcs3/Input/basic_mouse_handler.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/rpcs3qt/osk_dialog_frame.cpp
- rpcs3/rpcs3qt/osk_dialog_frame.h
- Adds keyboard support to the On-Screen-Keyboard of the native user interface
- Implements some missing error checks in cellOskDialog
- Implements a pseudo consumer logic for the pad/keyboard/mouse events during loaded OSK dialogs
- Adds some more TODOs for cellOskDialog. I'll implement some of them for MGSO later if needed.
- Some minor keyboard refactoring
Disclaimer:
- Needs basic keyboard handler.
- The OSK will only recognize characters that are supported by the current keyboard layout.
So if you need other characters, you can try to toggle the layouts with L2 and R2, as always.
TODO
> cellOskDialog: Implement keyboard input support

- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
- rpcs3/Emu/Cell/Modules/cellOskDialog.h
- rpcs3/Emu/Io/interception.cpp
- rpcs3/Emu/Io/interception.h
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/rpcs3qt/osk_dialog_frame.cpp
- rpcs3/rpcs3qt/osk_dialog_frame.h
- Fixes a regression in PS-Home that makes it impossible to enter keyboard input in the debug console
- Fixes a bug that might have disabled intentional pad input to the background game while an OSK dialog was open
- Properly log pad interception
> cellOskDialog: fix input interception

- BUILDING.md
The qt5-multimedia dependency is required for compilation on Arch Linux, otherwise you will receive the following error.
```
CMake Error at 3rdparty/qt5.cmake:12 (target_link_libraries):
The link interface of target "3rdparty_qt5" contains:
Qt5::Multimedia
```
> Update buid instructions for Arch

- rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/VertexProgramDecompiler.cpp
- rpcs3/Emu/RSX/VK/VKVertexProgram.cpp
Introduces a consistent error of about 7.81E-7 which matches RSX behavior when using NVIDIA hardware. Adding a flat constant of 16.0 manipulates the bits just right so that values around the [-1,+1] range compare correctly.
This fixup only applies to NVIDIA hardware.
Fixes https://github.com/RPCS3/rpcs3/issues/10955
Fixes https://github.com/RPCS3/rpcs3/issues/10923
I need help testing "SRW Dark prison" as this fix replaces the workaround I devised for that game. See the old bug here: https://github.com/RPCS3/rpcs3/issues/4799
If you have that title, please update so that we can proceed with this one.
> [NVIDIA TESTERS NEEDED] rsx: Improve lowered precision comparison emulation

- rpcs3/rpcs3qt/debugger_frame.cpp
This fixes:
* RSX code not being updated with newly inserted code by PPU. Especially after a sync point.
* Editing instruction does not show the new contents of the edited instruction.
> Debugger: Keep instruction's panel up-to-date with memory changes

- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
- rpcs3/rpcs3qt/debugger_list.cpp
- rpcs3/rpcs3qt/debugger_list.h
Although #11893 made this problem consistent as ShowPC() is called in master unconditionally. But this has always used to be a problem - when wandering in memory, sometimes most unexpectedly, the instruction pointer of the debugger went to thread PC. Once thread state has been changed (reasons vary greatly), ShowPC() has been called and the debugger bounded back to PC.
This PR makes the debugger able to distinguish when we want to stroll in memory and when we want to view the current code the thread executes by disabling auto-branching to PC when the user has scrolled or clicked on "Go To Addresss". This is re-enabled whenever the user pauses the thread, requested an instruction stepping or clicked "Go To PC".
> Debugger: Fix instruction pointer for good

- rpcs3/Emu/Cell/PPUTranslator.cpp
> PPU LLVM: match interpreter for VEXPTEFP/VLOGEFP

- Utilities/bit_set.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Loader/ELF.h
These are compiler-used file responsible for inserting functions or inlined SPU/PPU libs. (so called .a and .o files, .a files can be extracted using 7z and similar tools and contains many .o files)
This is important for reversing or optimizing SPU/PPU libraries with the possibility of HLE them.
> SPU/PPU Loader: Implement linker/PS3 compiler executable files loading

- Utilities/Thread.h
- rpcs3/Emu/Cell/SPUThread.cpp
* Optimize resevation validation while waiting for events by prefetching shared memory handle of reservation in order to needing not lock VM mutex each iteration.
* It's now possible to wait for any combination of implemented events, instead of crashing with few.
* Allow diverse combinations of events mask whenever reading events, previously some were not allowed and had had terminated thread execution.
> SPU: Cache reservation memory direct access handle (optimization)

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/System.cpp
This is actually the result of testing something completely different, but it turns out if exitspawn failed to launch a new PS3 process  (https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/Cell/lv2/sys_process.cpp#L436)
argv and other members of `Emu` are not resetted as they normally do in `Emulator::Kill`. Which causes weird bugs such as wrong argv[0] with succeeding boots because it didn't fix itself at https://github.com/RPCS3/rpcs3/blob/master/rpcs3/Emu/System.cpp#L1354
> Fix Emulator::argv state after failed PS3 exitspawn

- rpcs3/util/atomic.cpp
> Fix Regression in Waitable Atomics

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/gui_application.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
This hides the audio_provider box in the settings and forces the proper provider based on boot path.
Stop-gap solution until we decided what to do with vsh settings.
- Fixed the exception in get_guest_system_time. The timestamp in cellAudio wasn't properly initialized.
> Workaround: Force audio provider

- Utilities/Config.cpp
- Utilities/Config.h
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/vfs_config.cpp
- rpcs3/Emu/vfs_config.h
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/vfs_dialog.cpp
- rpcs3/rpcs3qt/vfs_dialog.h
- rpcs3/rpcs3qt/vfs_dialog_path_widget.cpp
- rpcs3/rpcs3qt/vfs_dialog_path_widget.h
- rpcs3/rpcs3qt/vfs_dialog_tab.cpp
- rpcs3/rpcs3qt/vfs_dialog_tab.h
- rpcs3/rpcs3qt/vfs_dialog_usb_input.cpp
- rpcs3/rpcs3qt/vfs_dialog_usb_input.h
- rpcs3/rpcs3qt/vfs_dialog_usb_tab.cpp
- rpcs3/rpcs3qt/vfs_dialog_usb_tab.h
- Adds device info to VFS
- Adds device info to fsys_fs_ctnl
TODO:
> Add device info to VFS

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
Mark registers whom value has been originated in a PPU-LI alike instructrion with the copyright character, it does not affect spacing.
> Debugger: Show constant-formed attribute of register value

- rpcs3/Emu/Cell/SPUThread.h
Ensure the most recent value written to the mailbox is the one the SPU reads by making try_pop reiterate (as compare-exchange fails) upon value3_inval update thus reloading value3 if an update occured.
> SPU: Fix race on SPU Mailbox last value reading

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/rpcs3qt/main_window.cpp
Fixes https://github.com/RPCS3/rpcs3/issues/11979
> PPU LLVM: Precompile system-internal executables if booting a dev_flash's program

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
* Fix memory capacity if SDK version of the following executable differs from the original process'.
* Keep user memory containers, they are not freed at exitspawn!
Hw test https://github.com/elad335/myps3tests/commit/4bf60023ee3779a221da968732fc622b85266c5b
> LV2: Memory state post-exitspawn fixes

- rpcs3/Emu/Cell/PPUModule.cpp
There was no need to manually align size, it only creates a bug with memcpy usage.
> Loader: Fix out-of-bounds access of string

- rpcs3/rpcs3qt/debugger_list.cpp
Not sure why, but in some random go-to or scrolling with the debugger, QListWidgetItem::setSelected caused a resizeEvent to trigger internally, in resizeEvent we called showAddress again and the recursion continued until it crashed.
Removed showAddress completely from resizeEvent as it is not needed anyways. (as #11893 refreshes the view all the time)
Additionally, fix instructions "pop-in" when resizing. IMO it is more natural to allow displaying incomplete elements without blank space as if it's a window to an infinite view of instructions.
> Fix recursion crash in the debugger

- rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
SPU decrementer freezes when writing TM bit to SPU_WrEventAck and the events mask bit TM is off, resumes when writing to WrDec.
> SPU: Implement timer freezing ability

- rpcs3/Emu/Cell/PPUThread.cpp
HLEd libraries are not allowed to be precompiled.
> VSH: Refrain from libfs_utility_init.sprx precompilation

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
Reimplement the current frame limiter to use mechanisms which had been used on PS3.
Most curiously fixes https://github.com/RPCS3/rpcs3/issues/3020, perhaps it does something sneaky with this mechanism. Also fix debugger RSX single stepping in semaphore_acquire.
> rsx: Implement HW accurate frame limiter

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/RSXZCULL.cpp
Fixes games randomly hard-locking when the "Accurate RSX reservations" option is enabled.
> rsx: Deadlock avoidance of accurate RSX reservations

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/cache_utils.cpp
- rpcs3/Emu/system_config.h
- rpcs3/Loader/TRP.cpp
- rpcs3/rpcs3qt/main_window.cpp
Furthermore:
* Discontinue the harmful cleaning of HDD1 cache during game process respawn. Cache should remain intact during so.
* Attempt to remove all HDD0's temporary game data created by cellGame, at boot - It may persist if RPCS3 has been closed unexpectedly.
Fixes https://github.com/RPCS3/rpcs3/issues/11330
> Wipe clean VSH's temporary directory of choice, remove game install cache at boot

- rpcs3/Emu/RSX/VK/VKGSRender.cpp
Improve detection of fast path query resolution where only a single source query is to be considered.
Fixes https://github.com/RPCS3/rpcs3/issues/12066
> vk: Fix conditional render fast-path

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
Followup on https://github.com/RPCS3/rpcs3/pull/5346.
Fixes https://github.com/RPCS3/rpcs3/issues/5856, idk how common this race is nowadays.
In hw testes I did years ago the SPU Out Interrupt Mailbox write does not wait until the interrupt is finished, the existence of sys_spu_thread_throw_event can attest that.
Here is a complete list of games which may be affected by this pr if you want to test.
[sys_raw_spu_create_interrupt_tag.txt](https://github.com/RPCS3/rpcs3/files/8761697/sys_raw_spu_create_interrupt_tag.txt)
> RawSPU: Reinvoke pending interrupts if missed

- rpcs3/Emu/Cell/lv2/sys_spu.cpp
PPU has refused to acknowledge it does not use memory, leading the SPU to wait for it in PUTLLC infinitely while the PPU waits for  the SPU itself to terminate.
> sys_spu: Fix spu_thread_group_terminate deadlock

- rpcs3/Emu/Cell/lv2/sys_rsx.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
* Convert host VBLANK to guest (PS3) VBLANK time as it should.
* Fix rate of flip time to become microseconds instead of MFTB rate.
> rsx: Fix VBLANK and FLIP time

- rpcs3/Emu/Cell/lv2/sys_rsx.cpp
Turns out that both VBLANK time and flip time clock at 80Mhz which is MFTB rate, just that cellGcmGetLastFlipTime is missing conversion to microseconds in GCM code, so odd.
Test #12118
> rsx: Fix cellGcmGetLastSecondVTime, revert FLIP time fix

- rpcs3/Emu/Cell/SPURecompiler.cpp
Tiny optimization, use wider instructions when possible. Likely no noticeable improvement outside of synthetics.
> SPU LLVM: Optimize inline MFC transfers

- rpcs3/Emu/Cell/SPURecompiler.cpp
The code previously emitted aligned loads when LS was constant and 32 byte aligned. This worked just fine, except when dst and src were swapped.
Just use unaligned instructions instead, since they're the same speed on anything that supports AVX anyways.
Fixes: https://github.com/RPCS3/rpcs3/issues/12122
> SPU LLVM: Fixup for inline MFC transfers

- rpcs3/Emu/RSX/RSXThread.cpp
PPU is the owner of m_mtx_task, it is possible for RSX to wait on it and meanwhile not acknowledge PPU pause resulting in a deadlock.
> rsx: Fix deadlock in vm::_page_unmap

- rpcs3/rpcs3qt/settings_dialog.cpp
Fixes a bug where the NTSC fixup checkbox is always enabled, even in global configs.
> Qt: fix tooltips and widget states in settings

- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/util/vm.hpp
- rpcs3/util/vm_native.cpp
System vm allocation granularity, previously assumed to be 4096, should be obtained at runtime.
> Obtain system memory page size

- rpcs3/CMakeLists.txt
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/main_window.ui
Adds the tests to the AppImage and adds a "Boot Test" option to the menu which point to relevant directories depending on OS.
> feat: add boot test menu entry

- rpcs3/Emu/RSX/GL/glutils/common.h
Fixes broken UBO/SSBO binding due to slot overwriting.
> gl: Disallow overlapping binding points

- rpcs3/Emu/Cell/SPURecompiler.cpp
I previously broke this path in https://github.com/RPCS3/rpcs3/pull/11231 due to a misunderstanding after writing some test code outside of RPCS3. I decided to revisit this after I wrote some other optimizations that rely on the vgf2p8affineqb instruction (said optimizations are still pending).
In short `_mm_set_epi8(15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0);` != `build<u8[16]>(15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0);`
> SPU LLVM: Reneable icelake shufb paths

- rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
- rpcs3/Emu/Cell/Modules/cellAudioOut.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
Follow-up to #12112 . Based on hardware tests in the comments.
- Load PARAM.SFO from disc if possible, as game data SFOs do not contain info about SOUND_FORMAT
- Pre-select the first available format based on SFO and config.yml in the following order:
LPCM 7.1 > LPCM 5.1 > AC3 > DTS > LPCM 2
- Only report LPCM 2ch. for the secondary outport
- Don't return speculative error in cellAudioOutConfigure
- Seperate active config from set config in cellAudioOutConfigure.
cellAudioOutGetConfiguration seems to return the set config and not the active config.
- Set latency to 13
- Add some unknown 8 channel enum values
> cellAudioOut: Improve sound mode enumeration

- rpcs3/Emu/Cell/lv2/sys_rsxaudio.h
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/rpcs3qt/about_dialog.cpp
- rpcs3/rpcs3qt/about_dialog.h
- rpcs3/rpcs3qt/camera_settings_dialog.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/pad_led_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_led_settings_dialog.h
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- rpcs3/rpcs3qt/patch_creator_dialog.h
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/patch_manager_dialog.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.h
- rpcs3/rpcs3qt/welcome_dialog.cpp
- rpcs3/rpcs3qt/welcome_dialog.h
Newer versions of the DualSense return 64, while old versions return 65.
fixes #12007
> DualSense: Fix firmware report on newer versions

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellGame.h
- rpcs3/Emu/Memory/vm_var.h
* Use non-temporary storage for stats, I noticed on Wall-E it actually saves the pointer to stats instead of saving its data. After some time the stack data got corrupted and messed up the filesystem calls. proof: passed funcStat callback of cellHddGameCheck 
* Add missing default cbSet->setParam in cellGameDataCheckCreate2, this function si basically the same as cellHddGameCheck internally so it's needed as https://github.com/RPCS3/rpcs3/pull/4539.
* Ensure 16-bytes alignment of vm::gvar to make it compatible with vector PPU instructions. We do not know which are ensured to be aligned so may as well align them all. 
Fixes [Wall-E [NPUB90129]](https://forums.rpcs3.net/thread-178974.html) from loadable to ingame.
> cellGame: Make stats storage non-temporary, fix cbSet->setParam

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
This fixes the slow motion and rubber banding in the pad settings dialog while using HID handlers (DS3, DS4, DualSense).
Previously everything was running on the main thread including the UI updates.
This meant that the poll rate was simply too slow and we were never up to date with the current data.
To test this, all you need to do is open the pad settings and play around with different pad handlers and states.
If it doesn't work, it will probably freeze RPCS3 or something on those lines.
> [Testers Needed] Qt: use dedicated thread for getting input in the pad settings

- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
- rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- rpcs3/Emu/Cell/Modules/cellSysutil.h
- rpcs3/Emu/Cell/Modules/cellUserInfo.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/save_data_dialog.cpp
This game doesn't use the cellMsgDialog callback, it uses the system GUI callbacks to tell if the dialog has finished.
Implemented those callbacks for savedata dialog and user selection as well.
Moves Twisted Land out of loadable
> cellSysutil: Implement DRAWING callbacks, optimize emulation stopping time

- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
The on_close callback is not used at all in cellMsgDialogAbort.
So we also need to send CELL_SYSUTIL_DRAWING_END for the native UI.
Fixes deadlocks in all games that use it, so it's highly important to merge this quickly.
> [Hotfix] cellMsgDialogAbort: send DRAWING_END also with native UI

- rpcs3/Emu/Cell/SPURecompiler.cpp
- Avoid vpermb path in shufb when op.ra == op.rb
- Reverse indices with (c ^ 0xf) rather than (~c) in vpermb path, vpternlogd is a 3 input operation and requires needless mov instructions to avoid destroying inputs
> SPU LLVM: Microfixes

- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
Fixes crash due to eviction and subsequent memory reuse. This only happens when MSAA is active because it is the only scenario where we have 32-bit remap ids that occupy the high bits of the storage key.
Fixes https://github.com/RPCS3/rpcs3/issues/12061
Fixes https://github.com/RPCS3/rpcs3/issues/12191
> vk: Fix image view search and destroy

- rpcs3/Input/ds3_pad_handler.cpp
The Report size seems to be generic here, so let's only check if anything got returned at all.
Probably fixes #12199
> DS3: fix report size check

- Utilities/lockless.h
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/util/dyn_lib.hpp
- rpcs3/util/vm.hpp
- rpcs3/util/vm_native.cpp
Use the Windows 10 memory mapping API which has the functionality required for preserving memory space for mappings.
Previously RPCS3 hacked it by releasing the reserved memory space temporarily and then mapping file mapping. But this induces a horrible race in which another memory reserving call in another thread can take the placement of the file mapping when the memory space is completely free for everyone to take possession of.
Fixes this error: "**Memory mapping failed - blame Windows**" on Windows 10+.
> [Testers Needed] vm_native.cpp: Remove the blame from Windows

- rpcs3/Emu/Cell/SPURecompiler.cpp
The previous code actually didn't work for any type other than u32[4].
> SPU LLVM: Improve expression matching detection for moved registers

- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/SPURecompiler.cpp
This AVX-512 instruction can perform a min/max while ignoring the sign bit of the first source operand, then later copy the sign bit from the first source to the result. This allows us to clamp both negative and positive values down to normalized floating point values for x86 in one instruction. 
On my tigerlake laptop, brings the spu float perf test down from 1147ms to 1041ms. (approx xfloat). Also grants 2-3 fps in the mandelbrot test.
> SPU LLVM: Use vrangeps in clamp_smax

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
This is pointless now, since we always exit games with this command.
> Qt: remove "Send Exit CMD" menu option

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
Fixes timeout in situations in which the RSX is paused such as Visual Studio Debugger pause, RPCS3 debugger pause, Steam Deck sleep and more.
> rsx: Fix NV406E semaphore_acquire timeout detection

- rpcs3/Emu/Cell/SPURecompiler.cpp
Fixup for #12182
Should fix #12217
> SPU LLVM: fix vrangeps usage in clamp_smax

- rpcs3/Emu/Cell/SPUAnalyser.h
Moved IOHL to integer instructions.
> SPUAnalyzer.h: Add missing category check functions

- rpcs3/Emu/Audio/AudioBackend.cpp
- rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
- rpcs3/Emu/Cell/Modules/cellAudioOut.h
Turns out some games don't configure proper channel counts after all, which triggers an ensure in cellAudioOutGetState.
Let's select the current sound_mode in cellAudioOutConfigure instead and keep the old one if no match was found.
Also moves some code from AudioBackend to cellAudioOut for thread safety (see mutex).
Follow-up to #12186.
Tagging @capriots for a retest. Main goal of the test should be to check if nothing regresses.
> cellAudioOut: fix sound_mode exception

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/Cell/Modules/cellAudio.h
- rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
The audio output format configured with cellAudioOutConfigure() never actually went into effect because audio::configure_audio() in cellAudio didn't detect any changes.
I simply added an argument to configure_audio() to force a reset of the audio renderer, I hope this is ok.
I also removed "format" from the raw_config struct because configuring the output format is handled in cellAudioOut and it wasn't used anywhere anymore.
This probably shouldn't be merged until #12245 is fixed.
> Reset audio renderer after cellAudioOutConfigure() was called

- 3rdparty/pine/pine_server.h
- rpcs3.sln
- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/IPC_config.cpp
- rpcs3/Emu/IPC_config.h
- rpcs3/Emu/IPC_socket.cpp
- rpcs3/Emu/IPC_socket.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/ipc_settings_dialog.cpp
- rpcs3/rpcs3qt/ipc_settings_dialog.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
I suppose there is no point in sitting on this any longer. Code style resembles the PCSX2 implementation which was used as base to ease future feature parity. Motivations can be found in #9872.
Stuff left to do/figure out:
PINE IPC client reference implementation: https://github.com/GovanifY/pine/
It can be seen in action for mouse injection on my youtube: https://www.youtube.com/channel/UCsI4PYmdQUUqdmAPDq4P51g/videos
> Implement PINE IPC Server

- 3rdparty/SoundTouch/CMakeLists.txt
- Utilities/JIT.cpp
- rpcs3/Emu/Cell/PPUFunction.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
Always override the LLVM triple on macOS arm64 to prevent linking errors. This line was removed in https://github.com/RPCS3/rpcs3/pull/12228
Fixes the function manager trampoline with a proper arm64 implementation, and clean up the code a bit.
Disables warnings on soundtouch dependency to allow Clang debug builds to work.
This gets LLVM PPU w/SPU interpreter on arm64 Mac to start a game with no segfaults, but it fails with `id 101 is not supported in the current check mode: content_permission::check_mode::disc_game`. Currently working on figuring out if this is caused by arm64 or if it's macOS because it works just fine in Rosetta.
Build instructions same as https://github.com/RPCS3/rpcs3/pull/12115
> [ppu] Fix arm64 trampoline

- rpcs3/Emu/Cell/SPUDisAsm.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
What Sonic The Hedgehog does is to send a pair of succeeding values to the SPU SNR. If the SPU does not wait on SNR reading, the first value should be overwritten by the second and this is what RPCS3 does.
On real hw however concluded by reversing this game, If the SPU currently reads from the empty SNR channel, the insertion of the first value keeps the channel empty and the SPU quits reading SNR, the SNR is available the obtain the second value freely.
This implements this mechanism and allows Sonic The Hedgehog to display some images and fixes the random crashes with its loading, but it is still not the same as the hacked build of mine which also waits for SNR to empty and thus ensuring values are not overwritten. Because on real hw the SPU finished its execution path faster than PPU …
> SPU: Implement "double" SNR storage

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/qt_utils.cpp
- rpcs3/rpcs3qt/qt_utils.h
Adds 3 optional states to the toolbar icons, which can be customized in the stylesheets.
The normal and already used color is
- toolbar_icon_color
The optional new states are:
- toolbar_icon_color_disabled
- toolbar_icon_color_active
- toolbar_icon_color_selected
Although I don't think we use "selected", since the buttons do not have such a state, I added it anyway.
Nothing should change in existing stylesheets, but it makes it possible to improve them.
In case you didn't know, you can set the colors like this:
```
QLabel#toolbar_icon_color {
color: #FFFFFF;
}
QLabel#toolbar_icon_color_disabled {
color: #FF0000;
}
QLabel#toolbar_icon_color_active {
color: #00FF00;
}
QLabel#toolbar_icon_color_selected {
color: #0000FF;
}
```
> Qt: add optional states to toolbar icons

- rpcs3/Emu/Cell/lv2/sys_config.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/IdManager.h
- rpcs3/rpcs3qt/kernel_explorer.cpp
- rpcs3/util/types.hpp
* Allow to select multiple inherited object types for idm::select.
* Allow function reference types in idm::select. (they don't allow access to operator() directly, use deducing std::function constructor instead) 
* Ensure ::PtrSame<T, object_type> and  ::Ptr<T, Derived> are true.
* Allow id_base, id_step and id_count to be of enumeration type.
* Remove idm::remove, usage can be replaced with idm::withdraw.
* Changed return value of idm::check to bool.
> IdManager.h: Improve idm::select

- Utilities/Thread.cpp
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/RSX/RSXDisAsm.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
Improve the responsiveness of the debugger during interactions such as single-stepping. If the thread is running the refresh rate is kept at 20fps in order to not cause a seizure or hurt performance. How does it work? if no update to thread information has occurred in the last 1/20 second period, increase the priority of checking for thread information changes to 100hz. Once an update is found the rate of checking reverts back to 20hz.
> Debugger: Refresh at 100fps during debugger interaction (was 20fps)

- rpcs3/rpcs3qt/debugger_frame.cpp
Do not put on a wary watch unless we explicitly run/step the thread.
> Debugger: Simplify and optimize #12269

- rpcs3/rpcs3qt/qt_music_handler.cpp
Should fix some of the "The emulator took too long" errors
> Qt: fix music handler destructor

- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
The menu icons weren't repainted when the active stylesheet was changed...
> Qt: Properly repaint the Emulation menu icons

- Utilities/Thread.cpp
- Utilities/Thread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/system_config.h
Implement an option to wait on important synchronization points such waiting for cellSpurs jobs or sending SPU mailbox interrupts.
Two settings were added in help to achieve desirable execution length for specific threads: "SPU Wake-Up Delay" (the delay, measured in miliseconds) and "SPU Wake-Up Delay Thread Mask": controls which of the threads in group delay their execution.
The settings' value is a bitmask of 6 SPU thread indexes. When a bit of the mask is set to "1" the delay is enabled, "0" is disabled.
To determine the SPU index in the group all you have to do is `SPU Thread ID >> 24`. By default all 6 threads of SPU are delayed.
Example:
SPU ID = 0x02000100, Index = 2, Bitmask for it alone = 0x4.
Implements SPU side of #8464
> SPU: Implement execution wake-up delay

- Utilities/address_range.h
- rpcs3/Emu/RSX/Common/texture_cache.cpp
- rpcs3/Emu/RSX/RSXZCULL.cpp
Trivial fixes to get commercial games running on arm64. I only tested with a few simple titles as I'm using Asahi Linux for this and there is no GPU driver. With PPU LLVM working now, performance is much better, although SPU LLVM still doesn't run. Games technically worked before the recent LLVM improvements, but performance was awful. This PR only addresses the hangs caused by page misalignments in RSX which is the primary (ab)user of the memory locking system.
With this PR, arkedo 01 is playable, although I need to use 50% res scale to get 60fps with the software rendering offered by llvmpipe. Vulkan doesn't work for some reason, but OpenGL is ok.
> Aarch64 fixes for RSX

- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Shows the current UUID and adds a button to create a new one.
implements #12293
> Qt: add UUID reset button

- rpcs3/Emu/Cell/ErrorCodes.h
- rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
- rpcs3/Emu/Cell/Modules/cellAudioOut.h
- rpcs3/Emu/Cell/Modules/sys_lwcond_.cpp
- rpcs3/Emu/Cell/Modules/sys_lwmutex_.cpp
- rpcs3/Emu/Cell/Modules/sys_spinlock.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/SPUASMJITRecompiler.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/IdManager.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/util/serialization.hpp
* Fix LV2 timers reloading, fixing audio and freezes in many games with savestates.
* Save cellAudioOut.
* Save SPU timer state.
* Initial HLE saving API implemented. (currently only POC in sys_lwmutex HLE)
* Fixes HLE VDEC contexts detection in savestates.
* Optimize SPU LLVM register value store insurence for savestates.
* Fix SPU instruction address in savestate if aborted on a WRCH instruction. (fixes random SPU crashes on savestate load)
* Replace bugged read-only block optimization with an optimization compatible with PPU patches and savestate inspection mode, not to mention it had a bugged check which made some executables not able to load.
> Savestates: Compatibilty improvements

- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Cell/Modules/cellMouse.cpp
- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Io/Buzz.cpp
- rpcs3/Emu/Io/GHLtar.cpp
- rpcs3/Emu/Io/pad_config_types.h
- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/system_config.h
- rpcs3/Input/basic_mouse_handler.cpp
- rpcs3/Input/pad_thread.cpp
- rpcs3/main_application.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- Adds an option to disable background input to the IO tab in the settings dialog.
This will disable pad, keyboard and mouse input as well as ps move and overlays input while the game window is not in focus.
- Fixes some horrible input emulation code that was modifying pad members for no reason.
- Implemented Left Stick position for PS Move fake handler
- Made PS Move handler dynamic
fixes #11950
probably fixes #9837
> Input: Add background input option and fix some horrible code

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/RSX/Overlays/overlay_cursor.cpp
- rpcs3/Emu/RSX/Overlays/overlay_cursor.h
- rpcs3/Emu/RSX/Overlays/overlay_message.h
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/Emu/system_config.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
- Adds a new dynamic option "Show PS Move Cursor"
This will display a cursor for two seconds whenever the PS Move (Fake or Mouse) position is changed.
The cursor will depict the raw screen position, not the actual ingame values.
- Adds a simple new cursor overlay system inspired by the message queue overlay
This can obviously be updated with other cursors in the future.
- Fixes a minor issue with the newly added cursor position of the Fake move handler
In my experience this can be very useful if you need to calibrate the controller and no ingame cursor is visible.
Notice the green crosshair in the target:
> PS Move: add "show cursor" option

- rpcs3/Emu/System.cpp
It redirected the disc path to an invalid one, it affected savestates because I use the same mechanism as exitspawn to boot executables.
> Savestates/Not Savestates: Fix exitspawn to HDD0 executable with mounted disc

- Utilities/Thread.cpp
- rpcs3/main.cpp
- rpcs3/util/logs.cpp
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
pthread_self() usually returns a big opaque pointer type such as 0x7ffd7d7fa700, we can do better than this. On Linux there is a gettid() syscall which returns much shorter PID-alike number such as 12345.
Windows should be unaffected.
> Refactor thread id printing, drop std::thread::id

- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
- rpcs3/Emu/Cell/Modules/cellCamera.cpp
- rpcs3/Emu/Cell/Modules/cellGem.cpp
- rpcs3/Emu/Cell/Modules/cellMusic.cpp
- rpcs3/Emu/Cell/Modules/cellVoice.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/RSX/RSXFIFO.cpp
- rpcs3/Emu/RSX/RSXFIFO.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/Emu/system_config.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
- rpcs3/main.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/util/atomic.hpp
- rpcs3/util/types.hpp
Ctrl+R to reload savestate during gameplay if it exists and is compatible with the current RPCS3 version.
You need the "Suspend Emulation Savestate Mode" setting on in the config file to use it.
The reason this setting is not on by default is that there is a risk HDD0 state has been changed by the game when playing after the savestate has been created in a way that is not compatible with the created savestate file. (because HDD0 state is not saved by default at the moment, so use with caution)
In addition save RSX semaphore waiting state, for synchronization should not be harmed when reloading.
> Savestates: Implement reload savestate shortcut and some bugfixes

- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_net.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.cpp
- rpcs3/Emu/Cell/lv2/sys_net/sys_net_helpers.h
~~Attempts to address https://github.com/RPCS3/rpcs3/issues/12236.~~
Implement type 0 and 4 commands.
> sys_net: Implement sys_net_abort

- 3rdparty/SPIRV/spirv.vcxproj
- 3rdparty/glslang/glslang.vcxproj
Hi!
I happened to clone rpcs3 into `D:\Source Code\C++\rpcs3` and ran into some issues when compiling `spirv` and `glslang`. I don't have the exact errors handy but they fail during `msbuild.exe` when passing the project path to `/p:ForceImportBeforeCppTargets`.
All other parts of `rpcs3` seem to compile fine without this assumption in mind (I have the build up and running on MSVC 2019).
The fix is simply to wrap `$(PropsAbsPath` and `GetFullPath`-related calls with quotes so that it interprets those spaces correctly.
Cheers
P.S. it's a bit controversial to use spaces in paths, so maybe I should get rid of that and use `Source` instead of `Source Code` :-P
> Fixed spirv/glslang.vcxproj to support paths with spaces in it

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.h
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/VFS.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/log_frame.cpp
* Fix RAW SPU creation after loading the savestate.
* Fix Ctrl+R reload savestate shortcut bug.
* Fix bugs of vfs::retrieve.
* Do not restart after Ctrl+S for now.
* sys_mutex_unlock saving bugfix.
> Savestates: QoL improvements

- rpcs3/Emu/Cell/Modules/cellMusic.cpp
- rpcs3/Emu/Cell/Modules/cellMusicDecode.cpp
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.h
- rpcs3/rpcs3qt/save_data_list_dialog.cpp
- rpcs3/rpcs3qt/save_data_list_dialog.h
During my cellMusicDecode testing I found a couple of bugs in the media list dialog.
- Fixed the title. It defaulted to "No media found"
- Added ability to jump out of a directory and into the previous one using the "Back" button (circle)
- The list now focuses the current directory after going back
- The Qt savedata dialog now uses the rsx overlays selection codes
> Overlays: Improve media list dialog

- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/GL/glutils/program.cpp
- rpcs3/Emu/RSX/Program/GLSLSnippets/GPUDeswizzle.glsl
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- Disable robust buffer access on ANV if descriptor indexing is in use. This is a long-standing driver bug with no solutions expected any time soon, so we might as well add an official workaround.
- Temporary workaround for OpenGL shaders not compiling on intel. This workaround will be dropped soon and we shall switch to SPIRV shaders on that platform. INTEL will only be supported for OpenGL when the GL_ARB_gl_spirv extension is supported after that point. The OpenGL driver is too broken to be considered usable otherwise.
Fixes https://github.com/RPCS3/rpcs3/issues/12285
Fixes ANV incompatibility
Adds one task to https://github.com/RPCS3/rpcs3/issues/12166
> rsx: Intel workarounds

- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Emu/vfs_config.h
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/vfs_dialog.cpp
- Adds dev_bdvd back to vfs dialog
- Mounts empty dev_bdvd if a disc game in HDD game disguise is booted
Should fix White Knight Chronicles II, one of the loadable games (needs game data cleared).
The game sees the data as corrupt if it can't find "/dev_bdvd", so by mounting an empty dir, we can circumvent this.
> Mount custom dev_bdvd if a disc game was mounted from dev_hdd0

- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/VKTextureCache.h
- rpcs3/Emu/RSX/VK/upscalers/fsr1/fsr_pass.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.h
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
The purpose of flushing the CB for every upload was to improve parallelism, but it triggers a driver bottleneck handling queue submits. There are much better ways to optimize job parallelism if it is indeed required.
Performance now matches the 'fast' mode on AMD and I can see a healthy uptick in performance on NVIDIA hardware as well, accompanies by lower GPU usage (yes, this is a good thing) and lower RSX latency when async streaming is enabled.
If there are any regressions, I have several ideas on how to handle job scheduling to avoid building long dependent chains. Ideally this shouldn't matter too much as a long tail on the leading submit actually improves parallelism with the next leading sequence.
Tested on AMD 22.5.1 and NVIDIA 512.15.
Fixes …
> vk: Rework async texture uploads

- rpcs3/rpcs3qt/qt_utils.cpp
- rpcs3/rpcs3qt/qt_utils.h
- rpcs3/rpcs3qt/screenshot_manager_dialog.cpp
> Qt: fix image ratio in screenshot_manager_dialog

- rpcs3/Emu/Cell/Modules/cellPhotoDecode.cpp
- rpcs3/Emu/Cell/Modules/cellPhotoImport.cpp
- rpcs3/Emu/System.h
- rpcs3/main_application.cpp
This decreases the loading times of images in media dialogs by ~20%
(It's not used in media Dialogs though. That's just how I tested it.)
> cellPhotoDecode: optimize get_scaled_image

- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
- rpcs3/Emu/RSX/Overlays/overlay_fonts.cpp
Old positioning was completely wrong in certain cases. How did I miss that?
I'll just show the good versions. On master these are all off-center or aligned to the left (apart from the first one, which works).
> Overlays: smash some bugs in message dialogs

- rpcs3/Input/keyboard_pad_handler.cpp
A bit useless but at least now the default config can be used by human beings.
> Update default right-stick mapping of keyboard handler

- rpcs3/Emu/System.cpp
I originally wanted it to occur only when booting games from GUI but command line doesn't have an option to boot a game (not just booting direct ELF) and there are software and users which already depend on it. So if we want to boot the unupdated EBOOT we should rename the one in the update directory for now. Fixes #12418
> Enable Disc update redirection specifically for EBOOT.BIN

- rpcs3/Emu/RSX/RSXZCULL.cpp
- ZPASS data is still accessible in unbuffered mode.
The only thing that buffered ZCULL enables is something closer to early-Z where large blocks of pixels can be dicarded earlier.
It is strictly a performance optimization and not required for ZPASS to work.
- Update ZCULL stat calculations to take into account unbuffered Z
Fixes https://github.com/RPCS3/rpcs3/issues/10869
Fixes https://github.com/RPCS3/rpcs3/issues/7741
> rsx: Do not require ZCULL buffer binding to enable ZPASS counting

- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/Emu/Cell/Modules/cellPhotoExport.cpp
- rpcs3/Emu/Cell/Modules/cellPhotoImport.cpp
- rpcs3/Emu/Cell/Modules/cellVideoExport.cpp
- Use the title passed to param in cellPhotoExport as proper filename.
- Use the title passed to param in cellVideoExport as proper filename.
- Allow /dev_hdd1 as destination in cellPhotoImport.
- Fallback to file extension when determining the subtype of an image.
> cellPhotoExport/cellVideoExport: fix filenames

- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/RSX/RSXFIFO.cpp
Seems like std::unique on MSVC always return an end iterator, I've encountered this bug in the past. For now push a hotfix to RPCS3.
Fixes Killzone 3 savestates, it uses PS3 memory mirrors that's why it happens to it.
> Savestates/MSVC: Replace bugged std::unique (compiler bug)

- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
This is the correct decoding of the vertex value here, it affected Demon Souls because it passed an integer of 0 to the vertex shader and then raised it to the power of -1. RPCS3 previously believed that it results in a float of 0 but no it results in float(1)/65535. So when raising it to -1 instead of NaN being produced it now results in precisely 65535. If you want to benefit from this you need to clear the Shaders cache.
Fixes #4302
> rsx/vp: Fix Demon Souls missing graphics

- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
Call awake under mutex lock if we attempt to wake an lwmutex waiter, in a case a call for _sys_lwmutex_lock with timeout attempted to abort waiting and awake could have been executed after it has aborted waiting. (so it's a loose awake call which can wake the thread from another syscall as a bug)
> sys_lwcond: Fix rare race on mode 3 signal

- rpcs3/Emu/System.cpp
Need to create a new savestate for this pr to take effect, because it does not bump the savestate version.
Attempts to fix #12463
> Savestates: Save SFO directory path for PSN games

- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/pad_thread.h
- rpcs3/main_application.cpp
Seems like someone changed the pad initialization and bastardised the reset flag for some thread yield loop.
This meant that the pads were never initialized in certain scenarios, because the reset flag was set to false right before they were supposed to be ... reset.
fixes #12331
> Input: fix pad initialization

- rpcs3/rpcs3qt/log_viewer.cpp
- Fixes filtering when a new log is opened.
- Adds a save button. This way you can filter out nasty stuff from the log first, then save it to a file and finally compare it with meld. (who knows, maybe we will add our own diff tool to the log viewer in the future)
> Qt: Improve log viewer

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKTextureCache.cpp
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
If pitch of a surface is changed, the only way to preserve data is to do a cache flush and rebuild from raw memory. While this is a huge task in and of itself, we do not need to implement all of that. For now, just set erase background flag but keep the old memory access tag. This forces a memory reload.
Of course this setup falls on its face if certain combinations of options are enabled, so I'd like to get some testing going.
I will still implement the full version of this, but it will take a long while to get ready (some re-architecting is required).
The only game I found affected by this issue is R&C ACiT, but I'm sure there are others.
Fixes https://github.com/RPCS3/rpcs3/issues/11205
> rsx: Partial handling of surface pitch change

- rpcs3/Emu/RSX/Common/ranged_map.hpp
- rpcs3/Emu/RSX/Common/surface_cache_storage.hpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
Refactor surface cache storage a bit to allow a persistent GPU memory cache to back all the surfaces. This layer can be used as a data source in case of unexpected corner cases, such as pitch mismatch reconstruction. This is only boilerplate code at this stage and no changes to functionality are expected at this time.
Part of https://github.com/RPCS3/rpcs3/issues/10208
> rsx: Refactor surface cache storage

- rpcs3/Input/hid_pad_handler.cpp
Prevents DS4 (and possibly DS3 and DualSense) from disconnecting from bluetooth after 15 minutes by using hidapi's non-exclusive mode. 
The most recent version of hidapi, 0.12 from two months ago, added "macOS-specific function(s) to open device(s) in non-exclusive mode".
Fixes #12290
Testing: Try using DualShock 3, DualShock 4 and Dualsense with bluetooth for more than 15 minutes.
This PR should not affect Windows or Linux.
Note that this PR just prevents the controller from disconnecting. RPCS3 will probably still crash if the controller is disconnected for any other reason. 
Credit to Behodar
> [macOS] [Needs Testing] Update hid_pad_handler.cpp to prevent DS4 from disconnecting

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/PPUThread.h
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.h
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.h
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
- rpcs3/rpcs3qt/log_frame.cpp
* Optimize lv2_obj::yield, fix a bug that existed before the pr and some which were introduced by it.
* A hotfix in sys_lwmutex/mutex.
* Fix a race in savestates with sys_lwcond.
* Improve the accuracy of LV2 timers regardless of the setting used. (count time passed from the time of sleep, not of wait_timeout)
* ~~**_Fix a race condition which existed before the pr as well. For me it fixes a freeze in Demon Souls after a while but it improves overall PPU stability in nearly every game. description is in the commit: https://github.com/RPCS3/rpcs3/pull/12482/commits/bf4791f571c9ea7be59fbc9b958ae73731ab0672_**~~ Removed from this pr.
Fixes #12480 
Fixes #12485
Fixes #12486
Fixes #12489
> LV2 Fixups

- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
Adds 2 new bug fixes.
* ### Fix an LV2 bug that over time can randomly kill the PPUs at once. Timeline of the race condition:
1. The PPU is in SLEEP state. state = suspend.
2. lv2_obj::awake is called on the traced thread and is now in ONPROC state, state = signal.
3. lv2_obj::awake is called by another thread externally with a priority higher than our traced thread and appends it to g_pending. state = suspend + signal.
4. lv2_obj::sleep/set_priority (highering priority) is called on any thread which is in ONPROC. Causing it to enter SLEEP or RUNNING state, while the traced thread is back in queue in ONPROC. state = suspend + signal.
5. The traced thread finally calls lv2_obj::awake on itself, g_pending decrements to 0 and we a have a rescheduling event, after XOR state = no flags (no …
> Stability fixes

- .cirrus.yml
FreeBSD Project currently doesn't keep recent binary packages for EOL versions. `/release_0` packages (non-default) frozen at 13.0 release (2021-04-13) will remain after 13.0 EOL (2022-08-31) for 13.* branch lifetime (until 2026-01-31) but likely too old for RPCS3 CI.
> CI: upgrade FreeBSD to 13.1 to avoid future breakage

- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
Overriding the pitch directly was a bad idea. Very rarely, a mismatch will occur when the surface has an external read reference pending. This causes access with the wrong pitch which triggers some asserts down the line and crashes the emulator.
> rsx: Do not tamper with surface variables in convert_pitch stub

- Utilities/JIT.cpp
- Utilities/JIT.h
- Utilities/Thread.cpp
- rpcs3/Emu/Cell/Modules/cellSpurs.cpp
- rpcs3/Emu/Cell/PPUAnalyser.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm_locking.h
- rpcs3/Emu/system_config.h
- rpcs3/util/atomic.cpp
- rpcs3/util/atomic.hpp
* "SPU GETLLAR polling detection" setting (which was yielding resources when it's set to true) has been transformed to "SPU Reservation Busy Waiting Percentage" and is off ("0") by default. (0 is yielding resources, 100 is always busy-waiting)
* It's now responsible for SPU events waiting as well, so the yielding can be replaced with busy-waiting there. You can test if you get perf gains with it set to on if your CPU has many threads. 
* It's not allowed to be changed for TSX users because TSX is very sensitive to memory touching. It's always as if this setting is set to "0" for it.
* Fix the detection of GETLLAR spin and optimize the actual yielding.
* Add some more minor optimizations.
* Fix PPU HLE injection.
* Fix PPU function analysis for savestates.
* Added an experimental SPU …
> SPU: Lock-line reservation optimizations + Savestates bugfix

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/system_config.h
Revert GETLLAR polling detection to be off (100 by default now) and the setting has been remaned to "SPU GETLLAR Busy Waiting Percentage", added a new setting with the old one's name "SPU Reservation Busy Waiting Percentage" which controls busy-waiting in reading SPU_RdEventStat channel (0 by default). Demon Souls needs GETLLAR to be 0 to have the results of pr #12523.
> Fix GETLLAR spin detection and restore default configuration as before #12523

- Utilities/Thread.h
- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
* Fix LV2 deleted-file descriptor check. Saves GBs off the created savestate file with some games.
* Improve saving performance by notifying SPU LLVM worker threads immediately.
* Postpone thread-abort notifications to post context-abortion in order to improve saving performance.
> Savestates/sys_fs: Fix incredibly large savestates and improve saving performance

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
Fixed the error which occurred when a game attempted to read the VID/PID of an undefined VFS USB device:
SIG: Thread terminated due to fatal error: Failed to read hex string: invalid argument
(in file C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\rpcs3\Emu\Cell\lv2\sys_fs.cpp:1942[:25], in function sys_fs_fcntl)
> Fixed SIG: Thread terminated due to fatal error: Failed to read hex string: invalid argument

- 3rdparty/SoundTouch/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/cellGifDec.cpp
- rpcs3/Emu/Cell/Modules/cellPngEnc.cpp
- rpcs3/Input/evdev_joystick_handler.h
Noticed today a [[deprecated]] wasn't generating any warning, turns out the warnings were being suppressed for the whole project from a leaking 3rdparty project.
EDIT:
Added some stuff for GCC to build again since the warnings being interpreted as errors are not being suppressed anymore.
> Fixes warnings suppression in CMake build

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/debugger_list.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
Pulling the debugger's contents when PPU/SPU debug options are enabled on emulation stopping.
This is for remote debugging. (user sends log)
> Add some debugging information

- bin/GuiConfigs/YoRHa by Ani.qss
- Fixes #11526
- Fixes settings being too big when Debug Tab is enabled on 720p screens
- Fixes calendar styling on System > Console Time
- Fixes text boxes missing border color
- Fixes search text box styling on the main window
- Fixes disabled text boxes not showing disabled grey color
- Fixes vertical alignment of text inside combo boxes
- Fixes the color of sorting arrows in table headers such as the ones in game list and trophies list
- Increases visibility for the patch validity label on Patch Creator
> gui/themes: YoRHa by Ani (r3)

- rpcs3/Emu/Cell/SPUThread.cpp
In sys_spu_thread_receive_event/sys_event_port_send the order of mutex locking is: queue mutex then group mutex.
In sys_spu_thread_send_event the order of mutex locking is: group mutex then queue mutex.
Fix it by making sys_spu_thread_send_event not hold both mutexes at a time.
> SPU: Fix potential deadlock in event queue syscalls

- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/RSX/RSXOffload.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
Implement RSX 128-byte atomic vertex fetching when "Strict Rendering Mode" is used. May fix 3D model or color flickering in some cases. It makes sense performance-wise for games to be able to update vertex coordinates at run-time of RSX if the developer actually knew it would fetch it atomically and the scene on screen is changing.
> rsx: Implement atomic vertex upload (with Strict Rendering Mode)

- rpcs3/Emu/Cell/Modules/sceNp.cpp
Reduces extreme log spam in LittleBigPlanet and probably more games.
> Unlog sceNpUtilCmpNpId

- rpcs3/Emu/Cell/PPUInterpreter.cpp
Fixes Sly 2 and Sly 3 crash on boot (RSX desync).
Regression happened on #11412 (https://github.com/RPCS3/rpcs3/pull/11412/commits/17b1a34ebf124f4f2bab09fc6125290599a87059).
Not 100% sure the fix is correct, didn't bother to fully read the code / instruction semantics, but the values produced by the instruction for these particular games are identical to before the regression.
Reviewer: @Nekotekina
> PPU Interpreter: Fix STVLX

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
> Fix ARM build

- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
- Fixes missing space between log message and suffix in stacked log
- Only patch the old suffix once. There's no need to do it several times in 7ms.
> GUI: Log fixes and possible optimizations

- rpcs3/Emu/Cell/Modules/cellVdec.cpp
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
vm::writer_lock inside SPU constructor can lead to a deadlock when the waiting PPU waits for SPU to finish a lock-line update, but the SPU waits for a different PPU which hasn't unlocked its memory mutex because it is waiting on IDM mutex to unlock. (owned by the PPU creating the SPU)
Also, improve cellVdec performance with reservations. That is also where I've seen the second PPU deadlocks initially.
> Fix a deadlock with non-TSX and SPU creation

- rpcs3/Emu/Io/usio.cpp
Fixed the following error which occurred when the game attempted to send firmware-related commands (such as FW update and reset state):
F {PPU[0x1000019] Thread (usj_usio_worker_thread) [0x019c85e8]} usio_log: Unexpected write channel: 0x01!
It needn't handle FW updates as the emulation doesn't use any firmware.
> Fix USIO fault when it received unsupported FW commands

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/IdManager.cpp
- rpcs3/Emu/IdManager.h
* Fix cellFs IDs to always take the lowest ID value possible, this fixes this game's installation: tries to access the ID of a closed installation file after opening different ones after. It works on PS3 because the old ID should be equal to one of the newer ones.
I've limited this fix very specifically to cellFs because I really do not want regressions.. Testcase which now matches RPCS3: https://github.com/elad335/myps3tests/commit/51b12574b71d52b48f35647ab1e6c248d25e7702
* Fix custom PS3 disc insertions, due to some typo it wasn't actually working. Also, remove wrong error checking - this allows for games to register only the eject callback as seen in this game.
Fixes [Spider-Man: Web of Shadows](https://forums.rpcs3.net/thread-179539.html), Intro -> Ingame. (if you already ran this …
> IdManager.cpp: Fix cellFs IDs

- rpcs3/Emu/Cell/SPURecompiler.cpp
Clean up asmjit usage so we don't unnecessarily allocate/leak memory anymore for SPURecompiler functions.
Tested with spurs test and 2 basic games and doesn't appear to cause any regressions.
> spu/arm64: clean up assembly code generation

- Utilities/JIT.cpp
- Utilities/JIT.h
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/RSX/Common/BufferUtils.cpp
Rewritten remaining intrinsic code in BufferUtils
> [Test] simd_builder ver. 2

- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/RawSPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
Bring the changes of #12258 to the SPU inbound mailbox channel, improving performance and accuracy.
Also fix an always-executed notification in spu_channel. (optimization)
> SPU: Implement "quintuple" Inbound MBOX storage

- Utilities/JIT.cpp
- rpcs3/main.cpp
> Linux: delete JIT announcement file on exit

- rpcs3/Emu/System.cpp
> System.cpp: Fix Create Firmware Cache

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/GL/GLVertexBuffers.cpp
- rpcs3/Emu/RSX/RSXFIFO.cpp
- rpcs3/Emu/RSX/RSXFIFO.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/RSXZCULL.cpp
- rpcs3/Emu/RSX/RSXZCULL.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKVertexBuffers.cpp
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- rpcs3/util/asm.hpp
- Avoid unordered_map insert/erase in hot loop. Use a ring allocation instead. This was an issue in ZCULL code where frequent insert/erase cycles were wasting performance.
- Avoid malloc/realloc/free in the vertex analysis routine. This method is called several times for every draw call and the cost was adding up quite a bit.
- Elide contention by aborting FIFO puller cache load if we have at least 50% of the data already loaded. Since the usecase for this is a "chase" situation, it is a far better use of resources to let CELL run ahead further and reduces time wasted spinning. This speeds up the FIFO read routine by ~12% when using atomic FIFO.
- Fix image concurrency access when using async compute with vulkan.
Overall, this set of changes gives a ~10% uplift on average which is nice.
> rsx: Misc optimizations and fixes

- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
Example: FMOD BGM status query threa -> FMOD BGM status query thread
> sys_ppu_thread: Fix max thread name size

- rpcs3/Emu/Cell/lv2/sys_ss.cpp
- rpcs3/Emu/system_config.h
The SingStar game has DLC songs which are encrypted to the PSID of the system. RPCS3 currently always returns a PSID of 0. This patch allows the PSID to be set in the config file allowing use of games which have content that is tied to a given PSID. 
(Ideally it would be settable in the GUI)
> Add the ability to set the PSID from the configuration

- rpcs3/Emu/Cell/Modules/cellMusic.cpp
- rpcs3/Emu/Cell/Modules/cellMusic.h
- rpcs3/Emu/Cell/Modules/cellMusicSelectionContext.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
Check if we have an attached context.
fixes #2526. 
Based on hw test https://github.com/elad335/myps3tests/commit/23826062007a255e225b5c5e3d3e2beca5b813d1.
> cellMusic: Implement some error checking

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
Lower CPU usage and power consumption significantly when SPUs are waiting for SPURS tasks. This is because when Acuurate SPU Resevations are disabled all reservation writes notify the SPU, so it's possible to drop the timeout on sleep condition, making the SPUs able to be fully relaxed. This requires "Accurate SPU Reservations: false" in config.
> SPU: Power consumption reduction when using SPU inaccurate reservations

- rpcs3/Emu/Cell/lv2/sys_game.cpp
The data that sys_game_board_storage_read() generates should be corresponding to the PSID by XOR.
Before #12637, the PSID was always set to 0 so it was fine to use the fixed data without XOR directly.
This PR fixed the regression that sys_game_board_storage_read() generated incorrect data when PSID was not set to 0;
> sys_game_board_storage_read(): Fix regression after #12637

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/CPU/CPUThread.h
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_sync.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Emulation poses a problem when it runs on the host system because the emulated programs are not optimized for the host system which often creates issues. A common pattern is that coded CPU sleep is adjusted to the console's performance and oftentimes reduced to a minimum because it benefits much less when the game is the only application the console is optimized to run. (doesn't need to care about the performance of other applications while it's running). This is especially an issue on older consoles or CELL SPU emulation where CPU sleep is barely supported by the hardware. This means that even when emulating on strong hardware which can be 100 times faster than the original console, CPU usage is often high even when the FPS never drops.
High CPU usage often means fast battery drainage, …
> Implement CPU usage reduction feature

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/system_config.h
* Make CPU preemption work in more cases.
* Make CPU preemption as sparse as possible allowing better performance and reduced side effects at higher values.
* Fix missed CPU preemptions.
* Add some debugging information.
* Avoid CPU preemptions in CELL reservations operations. (critical sections)
> CPU preemption control: bugfixes and performance improvements

- rpcs3/Emu/RSX/GL/GLCompute.cpp
- rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
- rpcs3/Emu/RSX/GL/glutils/common.h
- rpcs3/Emu/RSX/GL/glutils/state_tracker.hpp
- rpcs3/Emu/RSX/Program/GLSLSnippets/CopyBufferToColorImage.glsl
- rpcs3/Emu/RSX/VK/vkutils/image.cpp
- Some drivers don't like this. Actually only Radeonsi. For some reason their slots aren't duplicated across different targets, so writing slot 0 UBO erases slot 0 SSBO and vice-versa :man_facepalming: 
- Almost all GPUs going back 15 years have a large number of UBO slots but limited SSBO slots. Move UBO slots up as we have tons more headroom there. e.g The 6600M has like 75 UBO slots but only 8 SSBO slots.
Fixes https://github.com/RPCS3/rpcs3/issues/12476
> gl: Avoid UBO/SSBO binding index collisions

- rpcs3/Emu/RSX/GL/GLGSRender.cpp
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
We need to set all the data to 0 to match RSX behaviour.
Fixes some random glitching in games such as God of War III when diving under water.
> rsx: Fix initialization of null cubemap resources

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
This adds the Densha de GO! Type 2 controller to the list of controllers supporting USB passthrough. The first Railfan game (BLJM60013) is compatible with this controller.
More info here: https://marcriera.github.io/ddgo-controller-docs/controllers/usb/tcpp20009/
> Allow USB passthrough for Densha de GO! controller

- rpcs3/Emu/Io/usio.cpp
This PR enables some games that adopt USIO to save their settings so that the games will no longer be reset to their initial status each time players (re)start the emulation.
Note: In this PR, the game data is saved in the memory, meaning that the data still gets lost **when RPCS3.exe gets closed**.
Permanent data saving should be expected to be implemented in another PR in the near future.
> USIO: Save Game Settings

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_interrupt.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
- rpcs3/Emu/Cell/lv2/sys_memory.cpp
- rpcs3/Emu/Cell/lv2/sys_mmapper.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Cell/lv2/sys_vm.cpp
Writing to VM memory while cpu wait flag is set is no laughing material, in this case SPU reservation operations may eliminatte these writes because they aren't tracked by the CPU in case they share a single byte or more of reservation data within the 128-byte cache line.
> SPU/LV2: Fix tiny race conditions

- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_ppu_thread.cpp
There was no check_state() call between awake and sleep, so cpu_flag::signal could have been set by awake and not been caught making sleep fail (rare and random bug). Thanks to @jenci8888 for reporting it, seen in the game dark souls 2 but it can happen in any game which uses surmix.
> sys_ppu_thread: Fix surmixer hack

- rpcs3/rpcs3qt/richtext_item_delegate.h
From:
To:
I'm not sure what's going on with this painting code, I'm not sure anyone does.
> Fix pkg batch install dlg on linux

- rpcs3/Emu/RSX/Common/TextureUtils.cpp
- rpcs3/Emu/RSX/Common/surface_cache_dma.hpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/GL/GLCompute.cpp
- rpcs3/Emu/RSX/GL/GLCompute.h
- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/GL/GLOverlays.cpp
- rpcs3/Emu/RSX/GL/GLOverlays.h
- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/GL/glutils/state_tracker.hpp
- rpcs3/Emu/RSX/Program/GLSLSnippets/CopyBufferToGenericImage.glsl
- rpcs3/Emu/RSX/Program/GLSLSnippets/CopyD24x8ToBuffer.glsl
- Fix multiple broken image conversion routines for OpenGL
- Optimize/cleanup some suboptimal code in the GL state tracker
- Fix a bug that stopped hardware byteswap from working when deswizzling is unsupported. Affects texture upload performance.
- Fix a regression in overlays/compute caused by incorrect save-object initialization.
Fixes https://github.com/RPCS3/rpcs3/issues/12675
> rsx/gl: Fixes and improvements

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/SPUThread.h
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
Rename with the prefix "old-". (add some debug commits)
> Savestates: Don't actually delete savestates

- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2p.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_p2ps.h
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_raw.cpp
- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_raw.h
Used by Destiny for server communication.
The implementation does not support control messages, as it uses the `send` function instead of `sendmsg` for native sockets because the sendmsg function does not appear to exist on Windows.
> sys_net: Implement sys_net_bnet_sendmsg for native sockets

- rpcs3/Emu/Cell/lv2/sys_game.cpp
Added one more known code (0xC0), whose expected data is exactly the same as 0xF0's.
Also improved the conversion from u64[2] to u8[16];
> sys_game_board_storage_read(): Add more known code & Improve byte casting

- rpcs3/rpcs3qt/settings_dialog.ui
Some people think that this is a toggle to enable and disable AVX-512 support, let's make it more clear
Renamed to **Increase AVX-512 instruction width**
> gui: Rename "Full Width AVX-512" setting

- rpcs3/Emu/RSX/Common/simple_array.hpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKRenderPass.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VulkanAPI.h
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
- Fix framebuffer configuration notification on surface target change. Fixes broken graphics in FUSE.
- Silence a ton of compiler warnings coming from RSX code.
- Update vulkan framebuffer loop handling to match the current version of the VK_EXT_attachment_feedback_loop_layout specification. Fixes some VK_ERROR_DEVICE_LOST errors on linux + mesa-git.
Fixes https://github.com/RPCS3/rpcs3/issues/10766
> rsx: Maintenance fixes [2]

- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/Io/usio.h
This PR implemented permanent USIO game data saving, serving as a supplement to #12686.
> USIO: Save Game Settings - Full Implementation (Supplement to #12686)

- rpcs3/Emu/Cell/SPUThread.cpp
The idea was that if we have pulled an atomic state of memory in the past we can declare new data as atomic as well if it matches its bytes without further checks. But this doesn't work if there was a GET or PUT command in between 2 GETLLARs with different data. This hopefully fixes some games needing "Accurate SPU GETLLAR" set to true that hadn't needed the setting before.
> SPU: fix atomicity of inaccurate GETLLAR

- rpcs3/Emu/RSX/RSXZCULL.cpp
Silly computational error when I switched from signed arithmetic to unsigned. Generates an invalid index when the stars align and you get a start index of 0 during a hard sync (0.012% chance).
Fixes https://github.com/RPCS3/rpcs3/issues/12729
> rsx: Fix underflow in ZCULL sync

- rpcs3/Emu/CMakeLists.txt
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
Fixes incorrectly disabled buttons when changing from a handler with a disconnected pad to any other handler
> Qt: pad settings: clear input data on thread pause

- rpcs3/Emu/CPU/CPUTranslator.h
- rpcs3/Emu/Cell/PPUTranslator.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/util/sysinfo.cpp
- rpcs3/util/sysinfo.hpp
The intel cpus that support AVX512-VBMI have a slow implementation of the VPERMI2B/VPERMT2B instructions. They need 3 uops to execute these instructions. So I wrote an alternative implementation that achieves the same functionality as these instructions, but with only 2 uops.
The recently released Zen4 based cpus finally support AVX-512, and they even support single cycle/uop VPERMI2B/VPERMT2B. So let's allow them to use the "unoptimized" path instead.
> PPU/SPU LLVM: Fast path for Zen4 VPERMI2B/VPERMT2B

- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/Io/usio.h
Do not create a new USIO Backup file (when one doesn't exist) if USIO is not actually used by the game.
> USIO Backup Minor Optimization

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
> Add origin PRX names for log messages

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/RSX/Common/simple_array.hpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
This one is a bit annoying, but sometimes, games will reuse the same 2D surface address for a smaller region and we have to split the memory into separate chunks. However, sometimes the program is planning to reuse the leftover memory for something else, such as regular system memory. To prevent data loss, we lock these leftover chunks together with the new parent to recreate an atlas of the original image area, but this can cause race conditions where CELL is already reusing the memory and we lock it up and flush back old data due to our faulty tamper detection on surface memory. This can break game memory and cause strange behavior and instability.
In this scenario, let's just be paranoid with the relock and avoid it unless the original area is still protected. If the data is already …
> rsx: Do not clobber CELL memory when a surface is partially inherited

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/PPUModule.h
- rpcs3/Emu/RSX/Capture/rsx_replay.h
- rpcs3/Emu/System.cpp
- rpcs3/rpcs3qt/gs_frame.cpp
* Removed modification of CIA when saving inside HLE functions.
* Fix minor race of RSX abort when stopping emulation.
* Make Ctrl+R able to boot the last savestate when no game is running (in the same RPCS3 session) if no other game has booted since saving. Restore Ctrl+R when emulation is stopped to allow boot of the last game.
* Fix unintentional pause when saving with HLE VDEC contexts.
> Savestates: Improvements

- rpcs3/Emu/CPU/CPUThread.cpp
- rpcs3/Emu/Cell/Modules/cellMsgDialog.cpp
- rpcs3/Emu/Cell/SPURecompiler.cpp
- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_cond.cpp
- rpcs3/Emu/Cell/lv2/sys_event.cpp
- rpcs3/Emu/Cell/lv2/sys_event_flag.cpp
- rpcs3/Emu/Cell/lv2/sys_lwcond.cpp
- rpcs3/Emu/Cell/lv2/sys_lwmutex.cpp
- rpcs3/Emu/Cell/lv2/sys_mutex.cpp
- rpcs3/Emu/Cell/lv2/sys_net.cpp
- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/Cell/lv2/sys_rwlock.cpp
- rpcs3/Emu/Cell/lv2/sys_semaphore.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_list.cpp
- rpcs3/rpcs3qt/debugger_list.h
* Don't refresh "No Thread" list in the RPCS3 debugger at a high rate because it wastes CPU time. This makes "No Thread" view nearly truly as optimized as if the debugger is completely disabled.
* Optimize SPU DMA transfers a bit in non-TSX path.
* Avoid using multi-variable atomic wait on cpu_thread::state wait, multi-variable waiting is slower and all the notifications we need go through cpu_thread::state already.
> Some minor optimizations

- rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLTypes.h
Mostly relates to radeonsi. This fixes some awful Z-fighting when a game is running depth-prepass.
Fixes https://github.com/RPCS3/rpcs3/issues/12752
> gl: Explicitly declare gl_Position as invariant when using mesa drivers

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_spu.cpp
Improves massively the speed of emulation stopping because it skips the compilation of modules after the user has specified he wants to abort it, this only applies when there is more than one file to compile.
> PPU Precompilation: fix really long wait to abort VSH/firmware compilation

- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/GL/GLTextureCache.cpp
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/vkutils/commands.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- Fix program invalidation. Avoids referencing the wrong backend shader when the current pipeline is changed for a similar one.
- vk: Avoid unnecessary dynamic state updates every draw call. Improves performance and makes debug traces easier to follow.
- gl: Fix texture slice gather/reconstruction for cubemap and 3D. Fixes broken reflections in most games when using OpenGL.
Fixes https://github.com/RPCS3/rpcs3/issues/12580
> rsx: Maintenance fixes [3]

- rpcs3/Emu/RSX/VK/VKDraw.cpp
Do not release the invalidation flags just because the backend saw them. They need to get loaded as well which happens asynchronously. Deleting the flags makes the bind operation skip updates incorrectly.
Fixes https://github.com/RPCS3/rpcs3/issues/12766
Fixes https://github.com/RPCS3/rpcs3/issues/12765
> [HOTFIX] vk: Fixup for scissor/viewport invalidation rules

- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/VK/vkutils/sync.cpp
Seems like the main bugfix here is related to the change to get_system_time() which is more accurate than rsx::uclock but there may be another bug somewhere.
Fixes #12123
> rsx: Frame limiter bugfixes, fixes Seam Deck sleep

- 3rdparty/pine/pine_server.h
This fixes the following compiler deprecation warning
`warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.`
> [3rdParty] Pine: Replace sprintf with snprintf to silence compiler warning

- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
This feature is rarely used, but affects GOWA shadows on some GPUs.
Fixes https://github.com/RPCS3/rpcs3/issues/12778
> [HOTFIX] vk: Reload state if depth bounds changes

- rpcs3/Emu/Cell/SPUThread.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/Memory/vm_locking.h
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/perf_meter.hpp
Reduces overall CPU profiling load of this function from 9.6% to 6.8% and grants me about 2 fps in Sly 4. ~~This has a bit more effect when disabling Atomic RSX FIFO although it's partially active without it.~~
> SPU: Inline and batch MFC list transfers

- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings.h
- rpcs3/rpcs3qt/settings_dialog.cpp
This will force developers to add translations to settings in case they are used in the settings dialog.
> Qt: throw exception if settings translation is missing

- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
This fixes the log not scrolling automatically when we first open RPCS3 with a low log level.
> Qt: delay first log frame update

- rpcs3/Emu/Audio/AudioBackend.h
- rpcs3/Emu/Audio/Cubeb/CubebBackend.cpp
- rpcs3/Emu/Audio/Cubeb/CubebBackend.h
- Added more debug log messages. Cubeb was practically mute and logs were not helpful at all. These messages should be rarely logged. So I don't expect any spam from them.
- Replaced tuple with a struct for semantics. Also replaced m_current_device for m_default_device, which seems more appropriate.
- Added a bunch of sanity checks. I don't trust any third party software.
> cubeb: add some more logging and error checks

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/Cell/lv2/sys_game.h
Corrected the implementation of sys_game_board_storage_read() according to @elad335's suggestion in #12769.
After doing some experiments, I came to the conclusion that the value of *buffer2 must be always set to 0x00 (regardless of the PSID, unlike *buffer1), otherwise the game will throw an error saying the check has failed.
Also implemented sys_game_get_system_sw_version(), which represents the PS3 firmware version in an u64 form (firmware_version * 10000), e.g. 48900 for 4.89.
> Improved some sys_game syscalls

- rpcs3/Emu/System.cpp
This happens if you launch the used savestate directly when Suspend Savestate Mode is on.
https://cdn.discordapp.com/attachments/861435507967262740/1028632417067606027/unknown.png
Also, change the prefix to "used_" in order to (hopefully) better convey the intention.
> Savestates: fix endless renaming of used savestates

- rpcs3/Emu/RSX/GL/GLOverlays.cpp
- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
- rpcs3/Emu/RSX/Overlays/overlay_controls.h
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.h
- rpcs3/Emu/RSX/Overlays/overlay_message_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/Emu/RSX/VK/VKOverlays.cpp
- rpcs3/main.cpp
- Renames the exit member of the overlays to something more fitting
- Simplifies the overlay_media_list_dialog.
It was basically 2 dialogs before that had a delay between hiding and showing one another and also unintentionally allowed the player to interact with the game.
Now, we only spawn a single dialog that replaces its UI based on the current context.
Marked as draft, since there is a bug that randomly shuffles the icons of the media items 😠
> Overlays: Simplify overlay_media_list_dialog

- rpcs3/Emu/RSX/RSXFIFO.cpp
- rpcs3/Emu/RSX/RSXFIFO.h
- rpcs3/Emu/RSX/rsx_methods.cpp
Fix parsing of broken command streams with hanging begin/end commands without a pair. While these are game bugs, the parser shouldn't break on encountering them.
Fixes https://github.com/RPCS3/rpcs3/issues/12580
> rsx: Maintenance Fixes [4.1]

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/usb_device.cpp
- rpcs3/Emu/Io/usio.cpp
A few games (e.g. Tekken) will call control_transfer with bmRequestType=0x80 when booting up, which caused the whole booting up process to be frozen by sys_usbd.fatal() as the request type (0x80) was unhandled.
I added 0x80 to the switch-case and gave it a sys_usbd.todo() so that the booting up process will no longer be frozen by sys_usbd.fatal().
Also added USB passthrough for H050 USJ PCB, which is used on System 369 PS3-based arcade systems.
In addition, according to the game manual, last_game_status in the USIO SRAM is not kept after power off, so we shouldn't save it in the backup file either.
> Misc improvements for arcade games

- rpcs3/rpcs3qt/log_frame.cpp
- rpcs3/rpcs3qt/log_frame.h
The previous code tried to handle it without success, I discovered this bug while tinkering with LV2 making PPU write to TTY very fast.
In addition, add optimization for when TTY is disabled in GUI.
> GUI/TTY: fix UI deadlock when TTY is being spammed

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/Cell/lv2/sys_game.h
I implemented three sys_game_watchdog syscalls (sys_game_watchdog_start, sys_game_watchdog_stop, and sys_game_watchdog_clear) as a few games seem to rely on the watchdog to reboot the game itself.
> Implemented sys_game_watchdog syscalls

- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/evdev_joystick_handler.cpp
Fixes DualSense handler gyro yaw axis.
The gyro yaw axis of the Dualsense was mixed up with the pitch axis.
This seems to have been a copy pasta error from the DS4, which had the order of axis mixed up, but used the proper axis anyway.
Additionally, the used gyro resolution of 1024 seems to be way too high.
This means that we could never get the full range of the DS3, since the s16 dataype maxed out too early.
I calculated the best value for our purposes to be 86 and also applied that to the DualShock4 handler to get a smoother resolution.
fixes #12504
> Input: Fix Dualsense gyro axis

- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/System.h
Requesting @brian218 to review.
> sys_game_watchdog minor fixups

- rpcs3/Emu/CPU/CPUThread.cpp
It had a weird issue which prevented cpu_thread::flush_profilers() from printing results after the first emulation pause. Instead of the old broken logic add a 'new samples' count which prevents printing when not much has changed since the last print. The count of new samples is also printed now.
> SPU Profiler: nearly always print performance report on Emu.Pause()

- rpcs3/Emu/Cell/lv2/sys_sm.cpp
sys_sm_shutdown() log minor fixup
> sys_sm_shutdown() log minor fixup

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
- rpcs3/Emu/system_config.h
Fixes https://github.com/RPCS3/rpcs3/issues/12833 on its default value (default to false).
When set to true this hack is disabled.
> cellAudio: Implement setting to disable sampling skip

- rpcs3/Emu/Cell/lv2/sys_game.cpp
Changed the log level of LV2 Watchdog's being triggered from `warning` to `success`.
> Changed the log level of LV2 Watchdog's being triggered

- rpcs3/Emu/Io/Null/NullPadHandler.h
- rpcs3/Emu/Io/PadHandler.cpp
- rpcs3/Emu/Io/PadHandler.h
- rpcs3/Emu/Io/pad_types.h
- rpcs3/Emu/RSX/Overlays/overlay_controls.cpp
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/Input/ds3_pad_handler.h
- rpcs3/Input/ds4_pad_handler.cpp
- rpcs3/Input/ds4_pad_handler.h
- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- rpcs3/Input/evdev_joystick_handler.cpp
- rpcs3/Input/evdev_joystick_handler.h
- rpcs3/Input/hid_pad_handler.cpp
- rpcs3/Input/hid_pad_handler.h
- rpcs3/Input/keyboard_pad_handler.cpp
- rpcs3/Input/keyboard_pad_handler.h
- rpcs3/Input/mm_joystick_handler.cpp
- rpcs3/Input/mm_joystick_handler.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/Input/pad_thread.h
- rpcs3/Input/xinput_pad_handler.cpp
- rpcs3/Input/xinput_pad_handler.h
- rpcs3/main_application.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.cpp
- rpcs3/rpcs3qt/pad_settings_dialog.h
- Refactors pad rumble propagation: There's no need to deal with vibration levels outside of the handlers. All we need to know is the 0-255 DS3 range which is given by the u8 type.
- Fixes a rare issue that causes a newly selected pad handler with no pads to try to connect a previously selected pad from another handler.
- Fixes some minor race condition in the UI that had no real consequences just by chance.
> Input: refactoring and bugfixes

- rpcs3/Input/dualsense_pad_handler.cpp
- rpcs3/Input/dualsense_pad_handler.h
- Name some more output report bytes based on SDL2 information.
- Read the firmware version as seen in the official firmware installer and log it.
- Release the LEDs when the the game is closed.
- Enable improved rumble emulation to stop your hands from aching.
- Disable unused audio haptics to save some power.
> DualSense improvements

- rpcs3/Emu/RSX/GL/GLTexture.cpp
- rpcs3/Emu/RSX/VK/VKTexture.cpp
- Add missing OpenGL memory barrier after a CS dispatch on the image decoder.
- Fix scratch buffer calculation. Fixes a "verification failed" exception in VKTexture.cpp that randomly happens in games when WDB is enabled.
Fixes https://github.com/RPCS3/rpcs3/issues/12561
> rsx: Maintenance fixes [5]

- rpcs3/Emu/Cell/Modules/sceNpTrophy.cpp
- rpcs3/rpcs3qt/log_viewer.cpp
- Fix truncated log viewer caused by nul characters
- log tls error in sceNpTrophyRegisterContext
> sceNpTrophy: improve logging

- rpcs3/Emu/System.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
* Make RPCS3 not ignore savestates after their use by default, allowing their reuse.
* Import the "Suspend-Emulation Mode Savestates" setting to the Advanced tab.
* Fix a bug with savestates with HDD1 caused by naivety and ignorance.
* Automatic relaunch of savestate when suspend-emulation savestates mode is off.
* Add "Create Savestate" menu button in Utilities tab.
* Fix the logic of suspend-emulation savestates mode, ignore savestate after regular game boot as well.
> Sly Savestates Improvements 

- rpcs3/Emu/System.cpp
Do not move savestate if the actual boot is unsuccessful.
> System.cpp: Minor regression fix

- Utilities/Config.cpp
- Utilities/Config.h
- Utilities/StrUtil.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/system_config.h
* Unlimited Texture LOD Bias Addend to values from -32 to +32 instead of the old limit of -16 to +16, which are the maximum values that have an effect. This is because even though the actual range is -16 to 16 if the game value is currently 16, adding -16 can only make it go to 0 and not -16 like we want it to be able to at max limit.
* Implemented fractional value support in config making this setting able to support non-integral values such as `0.5`.
* Implement a custom fractional second frame limiter in the config entry "Second Frame Limit", when it's 0 it has no effect but when it's positive it limits further maximum fps.
>  rsx/cfg: Unlimit texture LOD bias addend, add custom frame limit

- rpcs3/Emu/Cell/Modules/sceNp.cpp
- rpcs3/Emu/NP/np_contexts.cpp
- rpcs3/Emu/NP/np_contexts.h
- rpcs3/Emu/NP/np_requests.cpp
- Non async sceNpScore functions actually put the thread to sleep(sys_semaphore_wait call), now we put it to sleep too
- Fixed sceNpScoreWaitAsync
- Various logging changed from todo to warning
> SceNpScore: improvements

- 3rdparty/MoltenVK/CMakeLists.txt
- rpcs3/Emu/RSX/VK/vkutils/device.cpp
Removed line that sets the Semaphore Support Style to Vulkan single queue. This line is no longer needed as MVK will select the appropriate support style automatically. See [here]( https://github.com/KhronosGroup/MoltenVK/pull/1738) for details. 
Fixes #12774 
Removal of the line was suggested by Tellowkrinkle [here](https://github.com/RPCS3/rpcs3/issues/12774#issuecomment-1288070314), but the PR should probably be looked over by @nastys as they wrote the initial code.
> [macOS] [Arm] Remove MVK Semaphore Support Style & Update MoltenVK

- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/VFS.cpp
- rpcs3/Emu/VFS.h
Implemented sys_fs_mount() and sys_fs_unmount() for VSH.
Solve:
```
SYS: 'sys_fs_stat' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_hdd1/crash_report/kernel/ps3crash-kernel.dat.tmp”
SYS: 'sys_fs_disk_free' failed with 0x80010002 : CELL_EINVAL, “/dev_hdd1”
SYS: 'sys_fs_open' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_hdd1”
SYS: 'sys_fs_unlink' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_hdd1/PS3UPDATE/ps3version.txt”
SYS: 'sys_fs_rmdir' failed with 0x8001003a : CELL_ENOTMOUNTED, “/dev_hdd1/PS3UPDATE”
```
Also corrected some existing typos of `dev_flash` things in System.cpp by the way.
> VSH: implement sys_fs_mount() and sys_fs_unmount()

- rpcs3/Emu/System.cpp
Third time trying to implement it correctly, this time is because I have heard that the bug was only affecting game collections. This made me realize that savestate hiding was not done for all games when booting regularly.
Also move savestate hiding to after SPU/PPU cache were built which makes more sense.
> Savestates/System.cpp: Realized fix for suspend mode

- rpcs3/Emu/Io/KeyboardHandler.cpp
- rpcs3/Emu/Io/KeyboardHandler.h
- rpcs3/Emu/RSX/Overlays/overlay_edit_text.cpp
- rpcs3/Emu/RSX/Overlays/overlay_edit_text.hpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/Input/basic_keyboard_handler.cpp
- Added delete action to the overlay text edit and the OSK keyboard interaction
- Added cursor movement with arrow keys to the OSK keyboard interaction
- Added a string-based fallback for keys unknown to cellKbCnvRawCode to the OSK keyboard interaction.
This should fix input for stuff like öäü
- Changed the language behaviour of the keypresses.
Before, we interpreted each keypress based on the current osk panel (you can actually change this with L2 and R2).
Now, we interpret each keypress based on the configured keyboard layout in the system settings.
- Changed the logic of how the keyboard interactions with the OSK panels.
Before, the OSK would only register keypresses that matched a letter that was currently visible on the current page.
Now, it will register any keypress that matches …
> overlays/osk: allow key input of all available pages

- rpcs3/Emu/Cell/Modules/cellAudio.cpp
For some reason this function uses the order Front Left, Center, Front Right, Surround Left, Surround Right, LFE (see documentation).
Fixes FMV audio in Tekken Tag Tournament HD/2:
<Details><Summary>Before</Summary>
https://user-images.githubusercontent.com/29807355/198859609-b16fb5ef-08ed-4aac-83b2-5626f268adc8.mp4
</Details>
<Details><Summary>After</Summary>
https://user-images.githubusercontent.com/29807355/198859662-3e8ce720-57c9-4ebe-86ff-e4d059746613.mp4
</Details>
> cellAudio: fix channel order in cellAudioAdd6chData

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_ss.cpp
- rpcs3/Emu/VFS.cpp
- rpcs3/Emu/VFS.h
This solves error 80029519 when you come across FSELF or non-retail games in XMB.
XMB only accepts this kind of game when the console is DECR, DECH, or GECR; so by changing the Product Code to DECR's, the system will deem the emulator a DECR console.
Error 80029519 screenshot:
This also adds support for mounting dev_hdd1 as a raw disk image file; With the file_system of sys_fs_mount() set to "CELL_FS_SIMPLEFS", the device is mounted as a file, instead of a directory.
> Misc improvements and bug fix for VSH for non-CEX firmware

- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
Fixed up some code in sys_fs_mount().
Also captured sys_fs_newfs(), which is used when the VSH attempts to format a device, for logging.
Log example:
`sys_fs TODO: sys_fs_newfs(dev_name=“CELL_FS_UTILITY:HDD1”, file_system=“CELL_FS_FAT”, unk1=0x0, str1=“”)`
> VSH: sys_fs: Minor fixup

- Utilities/Config.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_config.h
- rpcs3/Input/pad_thread.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Don't start savestates paused by default, lower pressing delay to unpause, move the setting to start paused to UI, don't automatically restart savestates.
> Popularity fixes

- rpcs3/Emu/RSX/GL/GLVertexProgram.cpp
- rpcs3/Emu/RSX/VK/VKDraw.cpp
- Fix point size export when using OpenGL. Fixes broken point rendering in some frostbite games, such as NFS: Rivals
- Add a workaround for broken point rendering with proprietary AMD drivers. Rendering points fails silently if LineWidth is not set.
> rsx: Maintenance fixes [6]

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.h
- rpcs3/Emu/savestate_utils.cpp
* Make PRX functions thread-safe, odd that they weren't before.
* Use std::map instead of std::unordered_map to fix potential pointer invalidation on insert where matters.
* Export PRX functions on start_module() instead of load_module().
Fixes #5080
> Restrained PRX fixes

- rpcs3/Emu/Cell/Modules/cellGcmSys.cpp
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/system_progress.cpp
Actually wait for the renderer to initialize when creating the system progress dialog.
- Fixes a crash when compiling PPU cache more than once.
- Fixes a bug where the system progress always falls back to the Qt dialogs when OpenGL is selected.
Fixes https://github.com/RPCS3/rpcs3/issues/12933
> rsx: Maintenance fixes [7]

- rpcs3/Emu/Cell/Modules/cellAvconfExt.cpp
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Loader/TAR.cpp
- Disable unsupported PPU settings on boot and log a TODO message
- aligned_div only takes unsigned values. fixes compilation on VS 17.4
fixes #12832
> Disable unsupported PPU settings on boot

- rpcs3/Emu/RSX/GL/GLFragmentProgram.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/Program/GLSLCommon.h
- rpcs3/Emu/RSX/Program/GLSLTypes.h
- rpcs3/Emu/RSX/RSXThread.cpp
- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/VK/VKFragmentProgram.cpp
- Perform 8-bit quantization/rounding before emulated operations like ALPHA_TEST.
- Refactor ROP emulation code a bit. This thing was a mess with magic constants all over the GPU code.
Fixes https://github.com/RPCS3/rpcs3/issues/8370
> rsx: Improve ROP output handling

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_ss.cpp
- rpcs3/Emu/VFS.cpp
Made the VSH willing to access /dev_usbXXX, which wasn't deemed mounted by VSH when the device wasn't in the list provided by sys_fs_get_mount_info().
For example, PS3UPDAT.PUP in /dev_usb000/PS3/UPDATE/ now can be detected by the VSH with this PR.
> VSH: Filesystem Mounting Enhancement

- rpcs3/rpcs3.metainfo.xml
Add some fields according to specification from https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
There are still some warnings I would like to point out
```LANG=en appstreamcli validate --explain ./rpcs3.metainfo.xml 
W: RPCS3:4: cid-desktopapp-is-not-rdns RPCS3
The component ID is not a reverse domain-name. Please update the ID to avoid future issues and
be compatible with all AppStream implementations.
You may also consider to update the name of the accompanying .desktop file to follow the latest
version of the Desktop-Entry specification and use a rDNS name for it as well. In any case, do
not forget to mention the new desktop-entry in a <launchable/> tag for this component to keep
the application launchable from software centers and the .desktop file data …
```
> Update AppStream Metadata

- Utilities/StrFmt.cpp
- Utilities/cfmt.h
- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellGifDec.cpp
- rpcs3/Emu/Cell/Modules/cellJpgDec.cpp
- rpcs3/Emu/Io/Skylander.cpp
- rpcs3/Emu/Memory/vm.cpp
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/np_notifications.cpp
- rpcs3/Emu/RSX/Common/surface_store.h
- rpcs3/Input/ds3_pad_handler.cpp
- rpcs3/rpcs3qt/rsx_debugger.cpp
- rpcs3/util/types.hpp
Implemented some TODOs and some new functionality: tool to avoid UB and able to replace misused reinterpret_cast and utils::bless. Done by avoiding referencing trivial objects in memory or arrays and just use memcpy on reads and writes.
> [NEED TESTUtility fixups

- Utilities/Thread.cpp
- rpcs3/Emu/Cell/ErrorCodes.h
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/System.cpp
* Allow silencing pending errors manually for ignored errors.
* Allow setting error as warning level so HDD1 errors would be logged as warnings.
* Prevent double error reports in the same syscall/function.
Implements https://github.com/RPCS3/rpcs3/issues/12667
> Improve error_code, make HDD1 errors be warnings

- rpcs3/Crypto/unpkg.cpp
- rpcs3/Emu/Cell/Modules/cellAudioOut.cpp
- rpcs3/Emu/Cell/Modules/cellGame.cpp
- rpcs3/Emu/Cell/Modules/cellKb.cpp
- rpcs3/Emu/Cell/Modules/cellMouse.cpp
- rpcs3/Emu/Cell/Modules/cellPad.cpp
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/system_utils.cpp
- rpcs3/Loader/PSF.cpp
- rpcs3/Loader/PSF.h
- rpcs3/Loader/disc.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
Helps identifying the erroneous files in #12985
> Improve PSF log message

- rpcs3/rpcs3.metainfo.xml
We noticed this naming changed through the [Flathub CI/CD](https://github.com/flathub/net.rpcs3.RPCS3/pull/1270).
The change originates from Related to https://github.com/RPCS3/rpcs3/pull/12974.
The ID should be `net.rpcs3.RPCS3` rather than `net.rpcs3.rpcs3`. The `RPCS3` project name is usually written in uppercase, not rpcs3 - except for the GitHub repository. `net.rpcs3.RPCS3` is used by the Flatpak package as such. Both should be valid though.
> Use uppercase RPCS3 name in the metainfo file

- Utilities/Thread.cpp
- rpcs3/util/logs.cpp
- rpcs3/util/logs.hpp
* Do not use unsafe pointer arithmetics exceeding existing memory. (exceeding m_fptr)
* Properly use the entire 32MB of the buffer, previously only 16MB were used for concurrent access.
* Fix a bug occurring after attempting to push 1TB (40 bits).
* Flush the log before hitting a debugging breakpoint.
> logs improvements

- rpcs3/main.cpp
- rpcs3/util/logs.cpp
Attempts to address #12994 
Also don't crash RPCS3  on startup if there is not enough space for logs, disable logging in this case.
> logs.cpp: Steer the ship before hitting the rocks

- rpcs3/Emu/Cell/lv2/sys_net/lv2_socket_native.cpp
- rpcs3/Emu/NP/np_handler.cpp
- rpcs3/Emu/NP/np_handler.h
- rpcs3/Emu/system_config.h
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Add ability to bind sockets to a local IP address, which is very helpful for LAN
> Add ability to bind sockets to a local IP address

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
I observed that the VSH wants to format /dev_hdd1 during the process of firmware update check (no matter whether a valid update file is found or not), so I implemented sys_fs_newfs() for it to format /dev_hdd1.
> sys_fs: Implemented sys_fs_newfs() for VSH to format /dev_hdd1

- Utilities/File.cpp
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
- rpcs3/Loader/PSF.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/vfs_dialog_path_widget.cpp
* Create a directory called "games" in RPCS3 program directory which disc games can be put and automatically be added to the games list. 
* Support PSN games outside of /dev_hdd0/game. Technically RPCS3 never forbid it, it just crashed most of the time when attempting to load them. Updates are not installed for it. (meaning it can be used as a backup in case updating fails)
* Do not load PARAM.SFO with TITLE_ID that has non-alphabetic or non-digits characters, this is to protect from potential malware files with special filesystem redirections.
> Add RPCS3/games/ for automatic games detection, support PSN games outside HDD0

- Utilities/Thread.cpp
- rpcs3/Emu/System.cpp
- rpcs3/main.cpp
- rpcs3/module_verifier.hpp
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/fatal_error_dialog.cpp
- rpcs3/rpcs3qt/fatal_error_dialog.h
Prevents running the emu with downloaded dll files. Some more details are given on how to properly install a protected library and a link to the real download site provided.
Examples:
Fixes https://github.com/RPCS3/rpcs3/issues/6318
> ux/core: Add module verification step for some critical libraries

- rpcs3/rpcs3qt/trophy_manager_dialog.cpp
- rpcs3/rpcs3qt/trophy_manager_dialog.h
- Adds "Copy Info" submenu to trophy list in trophy manager. You can copy name+description, name or description.
- Adds additional context menu to game list in trophy manager.
- Adds "Open Trophy Directory" entry to game list in trophy manager (same as the one in the trophy list).
- Adds "Copy Name" entry to game list in trophy manager.
fixes #13018
> Trophy manager: add more context menu actions

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
Given that get_vfs(), which calls get_mp() inside to determine the mount point, is usually called along with get_mp(), I integrated the function of get_vfs() into get_mp() so as to avoid unnecessary iteration.
`get_mp("/device_path")` still works as usual, and in case you need the associated vfs path as well, simply pass a pointer to a string to it like `get_mp("/device_path", &a_string)`.
> sys_fs: Integrated the function of get_vfs() into get_mp() to avoid unnecessary iteration

- .ci/build-freebsd.sh
- .ci/install-freebsd.sh
After https://github.com/freebsd/freebsd-ports/commit/855947ebf7e738232a8bbf6d47cc56f2896f276f [Qt5 itself](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=266007) brings LLVM 15 as a dependency, so avoid having to install more than one llvm package.
> CI: switch FreeBSD to Clang/libc++ 15

- rpcs3/Crypto/unpkg.cpp
- rpcs3/Crypto/unpkg.h
- rpcs3/Emu/System.cpp
- rpcs3/main.cpp
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/shortcut_utils.cpp
- rpcs3/rpcs3qt/shortcut_utils.h
* Add an option to create a desktop and start menu shortcut when installing PKG of a bootable game.
* Make game shortcuts not using hardcoded file paths but instead use game serial in order to resolve the boot path. So it works even if the disc game directory has been moved. This is done using the feature detailed below.
* Add CLI support for booting games using PS3 filesystem paths and TITLE ID. 
- Boot by TITLE_ID example: `rpcs3.exe --no-gui "%RPCS3_GAMEID%:BCES01584"`
- Boot using PS3 filesystem example: `rpcs3.exe --no-gui "%RPCS3_VFS%:dev_hdd0/game/NPUB30695/USRDIR/EBOOT.BIN"`
* Windows only: Create the directory RPCS3/game/shortcuts/ where shortcuts are created when installing PKGs regardless of user consent. Allows simulating a game library without even opening RPCS3 UI. Also …
> Game management improvements

- rpcs3/util/media_utils.cpp
Changes AVCodec* to a constant rather than a variable in two places. 
Building on macOS for Arm with Xcode 14.1 would fail with the following errors: 
```
/Users/XXXX/Downloads/rpcs3/rpcs3/util/media_utils.cpp:702:17: error: cannot initialize a variable of type 'AVCodec *' with an rvalue of type 'const AVCodec *'
if (AVCodec* encoder = avcodec_find_encoder(used_codec); !!encoder)
^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/XXXX/Downloads/rpcs3/rpcs3/util/media_utils.cpp:727:19: error: cannot initialize a variable of type 'AVCodec *' with an rvalue of type 'const AVCodec *'
if (AVCodec* encoder = avcodec_find_encoder(codec->id); !!encoder)
^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Allows RPCS3 to build on macOS again
Testing: 
1: Build on macOS (Edit: ARM and Intel)
2: Check that …
> [macOS] Fix build errors in media_utils.cpp 

- rpcs3/rpcs3qt/gs_frame.cpp
In #12894, the shown path in the overlay message "Recording stopped: " is too long to be fully shown in some cases due to a long absolute path.
This fix is inspired by the implementation of the overlay message "Screenshot saved: ", which shows a relative path instead.
Comparison
Before this PR:
After this PR:
> Qt: Improved the shown path in overlay message "Recording stopped"

- Utilities/bin_patch.cpp
- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/Modules/HLE_PATCHES.cpp
- rpcs3/Emu/Cell/Modules/StaticHLE.cpp
- rpcs3/Emu/Cell/PPUFunction.h
- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/PPUModule.h
- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
I wanted to add a new patch type for sonic. But then I realized I already implemented the needed functionality in #10859 and #10779, just need to add the new function for waiting for SNRs to empty.
Fixes SONIC THE HEDGEHOG graphics with a patch.
Patch: (currently only BLUS30008 1.01 is supported)
```
PPU-4b46d0161ca657ab16b0a779d9062810ea5ea2dd:
Graphics Fix:
Games:
"SONIC THE HEDGEHOG":
BLUS30008: [ 01.01 ]
Author: elad335
Notes: "Fixes missing graphics ingame."
Patch Version: 1.0
Patch:
- [ calloc, 0x00f07714, 0x4 ]
- [ be32  , 0x0, 0x38800003 ] # LI r4, 3
- [ jumpf , 0x0, "RPCS3_HLE_LIBRARY:WaitForSPUsToEmptySNRs"] # Args: (SPU ID, 3)
- [ be32  , 0x0, 0x38800000 ] # LI r4, 0
- [ be32  , 0x0, 0x44000002 ] # SC
```
> PPU: Add new patch function for SONIC 06

- rpcs3/Emu/RSX/RSXThread.h
- rpcs3/Emu/RSX/rsx_methods.cpp
- rpcs3/rpcs3qt/debugger_frame.cpp
- rpcs3/rpcs3qt/debugger_frame.h
- rpcs3/rpcs3qt/rsx_debugger.cpp
- rpcs3/rpcs3qt/rsx_debugger.h
- Fixed textures display of RSX debugger, it ended up not really showing textures before due to many bugs.
- Add new compressed texture formats support to it.
- Allow dumping images from it by right-clicking on them.
- Step RSX draw calls using the "step over" button in the RSX **instructions** debugger (the one with PPU/SPU threads).
Keep in mind that in order to view them correctly you need to step RSX into a draw call and may use Write Color Buffers in order to dump rendered images. (source textures can mostly be viewed fine without it though)
Also, RSX needs to be paused. (due to performance issues I disabled view when it's running)
If you want to dump rendered depth buffer "images" you need Write Depth Buffer enabled.
https://cdn.discordapp.com/attachments/272875751773306881/105108461 …
> Texture Dumper + RSX Draw Call Stepping

- rpcs3/Emu/Cell/lv2/sys_fs.cpp
Although RPCS3 VFS doesn't really mount g_mp_sys_dev_root (path: "/"), it should always be deemed mounted in sys_fs_get_mount_info().
Reference:
https://www.psdevwiki.com/ps3/Talk:Files_on_the_PS3
and what sys_fs_get_mount_info() reported before PR #12917.
> sys_fs: sys_fs_get_mount_info(): Made g_mp_sys_dev_root always reported as mounted

- rpcs3/rpcs3qt/rsx_debugger.cpp
Pitch can't be lower than width * bpp on color/depth buffers, it is common to set it to 64 or 0 when not using them. So avoid displaying garbage in this case.
> RSX Debugger: Do not show invalid color buffers

- rpcs3/Emu/Cell/lv2/sys_process.cpp
- rpcs3/Emu/Cell/lv2/sys_process.h
- rpcs3/Emu/Cell/lv2/sys_sm.cpp
- rpcs3/Emu/Cell/lv2/sys_sm.h
Attempt to implement sys_sm_shutdown() based on @elad335's suggestion in #12836.
> sys_sm: Implemented sys_sm_shutdown()

- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_sm.cpp
- rpcs3/Emu/Cell/lv2/sys_sm.h
- rpcs3/Emu/Cell/lv2/sys_ss.cpp
- rpcs3/Emu/Cell/lv2/sys_ss.h
Mainly implemented sys_ss_get_console_id(), and added sys_sm_set_shop_mode(), which is used not only by SHOP firmware but also by GEX firmware.
> Misc and minor improvements of syscalls used by VSH

- rpcs3/Emu/RSX/VK/VKTexture.cpp
- rpcs3/Emu/RSX/VK/vkutils/scratch.cpp
- rpcs3/Emu/RSX/VK/vkutils/scratch.h
- Zero scratch vram allocations unless we're reusing a resource.
- Introduce some extra barriers in copy_image_typeless. Without these some fast paths had back-to-back CmdCopyImageToBuffer and CmdCopyBufferToImage on the same scratch resource with 0 activity in between, causing garbage to get transferred in the second call and corrupting GPU memory.
Fixes https://github.com/RPCS3/rpcs3/issues/11328
> vk: Improve memory integrity

- rpcs3/Emu/Cell/Modules/cellSysutil.cpp
- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/Cell/lv2/sys_game.h
- rpcs3/Emu/System.cpp
- rpcs3/Emu/System.h
Whenever the LV2 Watchdog is triggered, the game should have already been ready to be killed forcefully (and then restarted).
> sys_game: Made the LV2 Watchdog restarts the game forcefully

- rpcs3/Emu/GameInfo.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gui_settings.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/qt_utils.cpp
- rpcs3/rpcs3qt/qt_utils.h
* Add the "Space On Disk" column in the game grid. This also means you can sort games by their size.
* Report game size and current free space when trying to remove a game to help the user make an informed decision.
> UI: Report Game Size On Disk, Make Game Removal An Informed Decision

- Utilities/Thread.cpp
- rpcs3/Emu/RSX/GL/GLDraw.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/gcm_enums.cpp
- rpcs3/Emu/RSX/gcm_enums.h
- rpcs3/Loader/PUP.cpp
- Do not crash RPCS3 when encountering some invalid RSX instructions in the debugger.
- Fix RSX exception message in some rare cases.
Fixes the log message in #13075, the anti-corruption mechanism was actually working just fine.
Fixes #9644
> rsx: Fix exceptions

- Utilities/stack_trace.h
- rpcs3/Emu/RSX/Common/surface_utils.h
- rpcs3/Emu/RSX/Common/texture_cache.h
- rpcs3/Emu/RSX/Common/texture_cache_utils.h
- rpcs3/Emu/RSX/GL/GLRenderTargets.cpp
- rpcs3/Emu/RSX/GL/GLRenderTargets.h
- rpcs3/Emu/RSX/GL/GLTextureCache.h
- rpcs3/Emu/RSX/VK/VKGSRender.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/VKTextureCache.h
Currently only tracks protection setting which is important for validating orphaned slices.
While we're at it, let's also use it to speed up redundant flush operations.
Fixes https://github.com/RPCS3/rpcs3/issues/12971
> rsx: Improve surface<->texture cache communication

- Utilities/StrUtil.h
Fixes a bug in _sys_prx_get_module_info with its usage when filename_size is 0.
> StrUtil.h: Prevent an underflow in strcpy_trunc

- Utilities/Config.h
- rpcs3/Emu/Cell/Modules/cellSaveData.cpp
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/config_checker.cpp
- rpcs3/rpcs3qt/config_checker.h
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/log_viewer.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.ui
- Adds a config checker to Utilities -> Check Config
- Adds a config checker to the context menu of the log viewer
- The config checker accepts .log files and .yml files
- The config checker currently only cares for the first found config in a log
> Qt: Implement config check in Utilities and log viewer

- rpcs3/Emu/Cell/PPUModule.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.cpp
- rpcs3/Emu/Cell/lv2/sys_prx.h
- rpcs3/Emu/Cell/lv2/sys_timer.cpp
- rpcs3/Emu/savestate_utils.cpp
- rpcs3/rpcs3qt/kernel_explorer.cpp
* I made a hw test that uses its own SPRX to reference it multiple times and show results, I tracked where the function is actually loaded and the possible error codes, which surprisingly were non-existent on real hw. It seems it allows one to reference a library multiple times, the addresses of the first reference are the ones used. It does this on a per-library basis, so if a PRX exports multiple it does it individually and keeps track of what's actually used. stop() in the case of being unused does nothing.
Hardware test: https://github.com/elad335/myps3tests/commit/3c4d4e68bb7e4690f145f88bfff0ee4aaf192704
Allowing [Asdivine Hearts](https://forums.rpcs3.net/thread-179705.html) and [Revenant Saga](https://forums.rpcs3.net/thread-195514.html) to no longer be loadable.
Fixes …
> PRX: Implement multi-referenced library management

- rpcs3/Emu/RSX/VK/vkutils/chip_class.cpp
- rpcs3/Emu/RSX/VK/vkutils/chip_class.h
Adds identification for RDNA3 and RTX40 GPUs.
> vk: Add some missing PCI IDs

- rpcs3/Emu/RSX/VK/VKRenderTargets.cpp
- rpcs3/Emu/RSX/VK/VKRenderTargets.h
- rpcs3/Emu/RSX/VK/vkutils/barriers.cpp
Refactored and simplified barrier management for the cyclic reference situation of a framebuffer loop. The result is that we only pay for the stalls that we absolutely have to as well as catching some tricky corner cases that failed before.
Fixes https://github.com/RPCS3/rpcs3/issues/8642
> vk: Restructure framebuffer loop barrier management

- Utilities/File.cpp
- Utilities/File.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/game_list_frame.h
> Make game size calculation not affect UI responsiveness

- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/qt_utils.h
- Do not cancel size watcher on soft refresh
- Set the cancel flag manually since the canceled signal seems to be very unreliable (I managed to trigger it rarely)
- Add Ctrl+F5 for hard refresh
> Qt: fix size watcher cancellation on soft refresh

- rpcs3/Emu/RSX/RSXTexture.cpp
The commit was originally added to restore previously working functionality that was still not understood at the time. It solved the regression but I never went back to figure out if the "fix" was correct after making all the texture encoding discoveries using realhw. Turns out this hack actually breaks tons of games and the original bug was fixed properly years ago.
See notes in the guilty commit: https://github.com/RPCS3/rpcs3/commit/f559c088a1eff7988e71feb7e05dde303c944f10
Fixes https://github.com/RPCS3/rpcs3/issues/8718 and probably a multitude of other alpha-related glitches.
> rsx: Remove incorrect hack

- rpcs3/Emu/System.cpp
Fixes #11126
PR #10849 introduced a bug that lead to games being unable to boot from the root of drives be it either when booting from a mounted decrypted ISO or an actual drive.
The directory check fails on these games as their dir_path is already "%DRIVELETTER%:/" with an terminating slash, making them get treated as HDD Games instead.
This is my first PR so please correct me if I did something wrong here.
> FS - Fix booting games from the root of drives

- rpcs3/rpcs3qt/qt_utils.cpp
- rpcs3/rpcs3qt/update_manager.cpp
I found out that opening paths with double slashes doesn't work with the explorer.exe /select call:
`explorer.exe '/select,"D:\dev\rpcs3\bin\dev_flash\vsh\module\\vsh.self"'` <- Opens default location (e.g. Desktop or Documents).
`explorer.exe '/select,"D:\dev\rpcs3\bin\dev_flash\vsh\module\vsh.self"'` <- opens `D:\dev\rpcs3\bin\dev_flash\vsh\module` with `vsh.self` selected.
Also use utf8_to_wchar util call in updater.
> Qt: Fix file explorer call when opening file paths with double slashes

- .ci/deploy-linux.sh
> AppImage: Do not bundle libgmodule-2.0 and libglib-2.0

- rpcs3/rpcs3.plist.in
https://developer.apple.com/documentation/bundleresources/information_property_list/lsapplicationcategorytype This makes it show up in the macOS Launchpad Games folder
> macOS: Set LSApplicationCategoryType to games

- rpcs3/Emu/Cell/Modules/cellMouse.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/log_viewer.cpp
- rpcs3/rpcs3qt/log_viewer.h
- rpcs3/rpcs3qt/patch_manager_dialog.cpp
- rpcs3/rpcs3qt/update_manager.cpp
- rpcs3/util/cpu_stats.hpp
This PR just takes some bloat out of the Qt6 PR.
- Fixes some miscellaneous includes and warnings
- Decreases some log levels in cellMouse
- Use the emulator's play_sound callback instead of QSound.
This way we only have a single place that handles in-game emulator sounds.
> Road to Qt6: preparations

- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/gs_frame.cpp
- rpcs3/rpcs3qt/gs_frame.h
- rpcs3/rpcs3qt/msg_dialog_frame.cpp
- rpcs3/rpcs3qt/msg_dialog_frame.h
- rpcs3/rpcs3qt/progress_dialog.cpp
- rpcs3/rpcs3qt/progress_dialog.h
- rpcs3/rpcs3qt/progress_indicator.cpp
- rpcs3/rpcs3qt/progress_indicator.h
- Moves duplicate progress indicator code to separate file
- This will simplify any further changes to the taskbar progress functionality
- In Qt6 we will have to change all this anyway, so this commit will greatly simplify the Qt6 PR
> Road to Qt6: move progress indication to own handler

- rpcs3/Emu/Io/usio.cpp
- rpcs3/Emu/Io/usio.h
There's no need to keep the backup file opened throughout the emulation.
> USIO: Backup file fixup

- rpcs3/Crypto/unpkg.cpp
- rpcs3/Crypto/unpkg.h
- rpcs3/Emu/system_utils.cpp
- rpcs3/rpcs3qt/main_window.cpp
- Fix check_target_app_version when installing multiple packages (compromise: no more optimized singular file installs)
- Abort installation if any thread has errors
- Clean directories if fill_path fails
- Only clean the directories of packages that actually had errors
- Additionally clean the directories of packages that were cancelled before they could finish
- Clear boot path in case of error or cancelation
- Propagate result to caller
- Skip success message if the installation was canceled
fixes #13207
> Package installation fixes

- rpcs3/Emu/RSX/GL/GLOverlays.cpp
- rpcs3/Emu/RSX/GL/GLOverlays.h
- rpcs3/Emu/RSX/GL/GLPresent.cpp
- rpcs3/Emu/RSX/VK/VKGSRender.h
- rpcs3/Emu/RSX/VK/VKPresent.cpp
- rpcs3/Emu/RSX/VK/upscalers/nearest_pass.hpp
- rpcs3/Emu/system_config.h
- rpcs3/Emu/system_config_types.cpp
- rpcs3/Emu/system_config_types.h
- rpcs3/VKGSRender.vcxproj
- rpcs3/VKGSRender.vcxproj.filters
- rpcs3/rpcs3qt/emu_settings.cpp
- rpcs3/rpcs3qt/emu_settings_type.h
- rpcs3/rpcs3qt/settings_dialog.cpp
- rpcs3/rpcs3qt/settings_dialog.ui
- rpcs3/rpcs3qt/tooltips.h
Partially addresses https://github.com/RPCS3/rpcs3/issues/11187 by adding a bilinear/nearest option and provides a config/UI implementation so that more scaling/filtering options may be added later.
As per @kd-11, FSR is currently unimplemented for OpenGL but is intended to be added later, so for now, while FSR can be selected under OpenGL, it just falls to bilinear.
The new combobox option is shown here:
The options are Nearest, Bilinear (default) and FSR.
> Add output scaling filtering options

- rpcs3/Emu/Cell/Modules/cellNetCtl.cpp
- rpcs3/Emu/Cell/Modules/cellNetCtl.h
- rpcs3/rpcs3.vcxproj
- rpcs3/rpcs3.vcxproj.filters
- rpcs3/rpcs3qt/CMakeLists.txt
- rpcs3/rpcs3qt/main_window.cpp
- rpcs3/rpcs3qt/main_window.h
- rpcs3/rpcs3qt/main_window.ui
- rpcs3/rpcs3qt/system_cmd_dialog.cpp
- rpcs3/rpcs3qt/system_cmd_dialog.h
It's not pretty, but it works.
> Qt: add (very basic) system command utility

- rpcs3/Emu/RSX/Program/GLSLCommon.cpp
- rpcs3/Emu/RSX/rsx_methods.cpp
- Allow vertex fetch on uninitialized attribute channels
- Do not override state signal for MSAA control flags
Fixes https://github.com/RPCS3/rpcs3/issues/13237
Fixes https://github.com/RPCS3/rpcs3/issues/13239
> rsx: More regression fixes

- Utilities/Config.cpp
- Utilities/Config.h
- Utilities/StrFmt.cpp
- Utilities/StrUtil.h
- rpcs3/Emu/CMakeLists.txt
- rpcs3/Emu/Cell/lv2/sys_fs.cpp
- rpcs3/Emu/Cell/lv2/sys_fs.h
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/usb_device.cpp
- rpcs3/Emu/Io/usb_device.h
- rpcs3/Emu/Io/usb_vfs.cpp
- rpcs3/Emu/Io/usb_vfs.h
- rpcs3/Emu/Io/usio.cpp
- rpcs3/emucore.vcxproj
- rpcs3/emucore.vcxproj.filters
1. Implemented `control_transfer(0x80)`, which is used to retrieve the descriptor of a USB device.
2. Added VFS USB mass storage devices to the USB device list.
A number of System 357 games (e.g. Tekken and Razing Storm) retrieve the VID/PID/Serial Number information of a USB mass storage device via `control_transfer(0x80)` instead of  `sys_fs_fcntl(0xc000001c)`.
This PR makes those games pass the USB dongle check as long as proper USB information is set.
> USB: Added VFS USB mass storage devices to the USB device list

- Utilities/Thread.cpp
Error since #7524 which predates  #11315 but around #11868 [built fine by accident](https://pkg-status.freebsd.org/ampere3/data/latest-per-pkg/rpcs3/0.0.23.14067/130arm64-default.log). From [error log](https://pkg-status.freebsd.org/ampere2/data/main-arm64-default/p65c6f35619ce_s4883f347f6/logs/rpcs3-0.0.26.14568_1.log):
```c++
Utilities/Thread.cpp:1799:48: error: comparison of integers of different signs: 'uptr' (aka 'unsigned long') and '__register_t' (aka 'long') [-Werror,-Wsign-compare]
const bool is_executing = uptr(info->si_addr) == RIP(context);
~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~
```
```c++
rpcs3/util/types.hpp
131:using uptr = std::uintptr_t;
/usr/include/machine/_types.h
75:typedef __int64_t       __register_t;
82:typedef __uint64_t      __uintptr_t; …
```
> Thread: silence -Wsign-compare on FreeBSD aarch64

- rpcs3/Emu/Cell/Modules/cellOskDialog.cpp
- rpcs3/Emu/Cell/Modules/cellOskDialog.h
- rpcs3/Emu/RSX/Overlays/overlay_controls.h
- rpcs3/Emu/RSX/Overlays/overlay_cursor.cpp
- rpcs3/Emu/RSX/Overlays/overlay_cursor.h
- rpcs3/Emu/RSX/Overlays/overlay_media_list_dialog.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.cpp
- rpcs3/Emu/RSX/Overlays/overlay_osk.h
- rpcs3/Emu/RSX/Overlays/overlay_osk_panel.h
- rpcs3/Emu/RSX/Overlays/overlays.cpp
- rpcs3/Emu/RSX/Overlays/overlays.h
- rpcs3/rpcs3qt/osk_dialog_frame.cpp
- rpcs3/rpcs3qt/osk_dialog_frame.h
- Some languages/panels in the osk need to be activated by the developer. They are not available otherwise.
So let's check if they were pre-configured and only add the panels if they are supported.
- Improve the error checks and logic of the initial key layout. Layouts are only supported if they were allowed as kay layout option first.
- Try to position and scale the osk based on the game's parameters
- Add a rudimentary osk pointer/mousecursor based on cell parameters. The game will toggle it and also set its position live.
- Parse paths in IME dictionary functions
- Improve cellOskDialogSetSeparateWindowOption. This will allow us to parametrize the "Separate Window" version of the OSK
- Add analog movement with right stick if CELL_OSKDIALOG_NO_INPUT_ANALOG is unset
> overlays/osk: improvements

- rpcs3/Emu/System.cpp
- rpcs3/Emu/vfs_config.h
- rpcs3/rpcs3qt/game_list_frame.cpp
- rpcs3/rpcs3qt/gui_settings.h
- rpcs3/rpcs3qt/shortcut_utils.cpp
- rpcs3/rpcs3qt/vfs_dialog.cpp
* Do not create /dev_hdd0/disc anymore, mounting /dev_bdvd inside /dev_hdd0 is wrong and creates a file reflection situation.
> Deprecate HDD0/disc, make RPCS3/games movable

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
Fixes exception on emulation stop when using usb passthrough.
libusb was deinitialized before usb device was unreferenced.
Fixes #12329
> sys_usbd: fix usb handler deinitialization

- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
These are some kind of wrist- and legbands that communicate with one specific game through a dongle.
Attempts to close #11996.
> Whitelist EA Active 2 accessories

- rpcs3/Emu/Cell/PPUThread.cpp
- rpcs3/Emu/Cell/lv2/lv2.cpp
- rpcs3/Emu/Cell/lv2/sys_game.cpp
- rpcs3/Emu/Cell/lv2/sys_game.h
- rpcs3/Emu/Cell/lv2/sys_usbd.cpp
- rpcs3/Emu/Io/usio.cpp
After looking into a number of System 357 games' decompilation, I figured out that the buffer `status` is supposed be set to all 0 by `sys_game_get_rtc_status()` if the RTC is successfully checked (required by Dark Escape 4D).
Also, with more System 357 games being discovered, I figured out that sys_game_board_storage_read() should always give `buffer1` all 0, and players are responsible for setting a correct PSID in the emulator configuration on a game basis in order to play System 357 games.
> sys_game: Implemented sys_game_get_rtc_status() & Updated sys_game_board_storage_read()

- rpcs3/Emu/RSX/Overlays/overlay_perf_metrics.cpp
- rpcs3/Input/pad_thread.cpp
- Fix dynamic pad handler mode reset
- Fix minimal graph detail level in performance graphs. Min and max graph values were never calculated.
This led to the following bug:
> perfoverlay: fix minimal graph min/max calculation

- rpcs3/Emu/Cell/SPURecompiler.cpp
- Tweak shuffle to allow LLVM to emit a cheap blend instruction instead of the expensive VPERMI2W instruction
- Also avoids the need to load a constant from memory for the VPERMI2W indices
> SPU LLVM: Minor SUMB AVX-512 path optimization

- rpcs3/Emu/RSX/VK/VulkanAPI.h
Regressed by https://github.com/KhronosGroup/Vulkan-Headers/commit/6f62a95edbfe. From [error log](https://github.com/RPCS3/rpcs3/files/10523789/rpcs3-0.0.26.14614.log)
```c++
In file included from rpcs3/Emu/System.cpp:55:
rpcs3/Emu/RSX/VK/VulkanAPI.h:17:10: fatal error: 'vulkan/vk_sdk_platform.h' file not found
#include <vulkan/vk_sdk_platform.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~
```
> Unbreak build with Vulkan-Headers >= 1.3.240

- 3rdparty/MoltenVK/CMakeLists.txt
Attempt 2: The errors I was getting with the previous attempt have been fixed in #13302 
[New release](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.2.2) for MoltenVK with the following changelog:
```
Fix Metal validation error caused by CAMetalDrawable released before  MTLCommandBuffer is finished using it.
Fix memory leak of MVKFences and MVKSemaphores when a swapchain image is acquired more than it is presented.
Fix issue where fragment shader was not run when no render attachment is available.
Ensure Vulkan public symbols are not stripped from the library when statically linked to an app that calls all Vulkan functions dynamically.
Per Vulkan 1.2 spec, support calling vkGetInstanceProcAddr() with a null instance, when vkGetInstanceProcAddr itself is the function name. …
```
> [3rd Party] Update MoltenVK to 1.2.2 (VK 1.3.239)

- 3rdparty/CMakeLists.txt
- rpcs3/Input/evdev_gun_handler.cpp
On Linux `-ludev` is added implicitly via bundled hidapi but on FreeBSD it needs to be explicit.
https://github.com/RPCS3/rpcs3/blob/3196ada48151e25dc38ab07d9cbd64e08f4f78e8/3rdparty/hidapi/CMakeLists.txt#L15
Note, FreeBSD >= 13 supports [hidraw(4)](https://man.freebsd.org/hidraw/4) but it's not used by hidapi yet.
> evdev_gun: enable libudev on FreeBSD
